### ISSUE TITLE
docker should support setting run args. 

### ISSUE THREAD

**Issue by kailuowang** [ansible/ansible-modules-core#1008]
I mean the ARGs in the following docker command

```
docker create  --name my_container my_image ARGs
```

Setting it in the command doesn't work (I do have an entry point in my docker file).  
 Here is what I tried
playbook

```
- name: deploy docker image
  sudo: yes
  docker:
    image: "{{ docker_image_name }}:{{ docker_image_version }}"
    state: reloaded
    name: "{{ docker_container_name }}"
    command: "{{ docker_args }}"
```

in my group vars I have something like

```
my_hosts:vars
  docker_args="-Dconfig=qa.conf"
```

my docker file has an entry point

```
ENTRYPOINT ["bin/my_application"]
```
