### ISSUE TITLE
[Feature] Docker rolling restarts

### ISSUE THREAD

**Issue by MrMMorris** [ansible/ansible-modules-core#1028]
Heya!

Not sure how it works with `pull: always`, but it would be totally rad if there was some way of allowing for rolling restarts of containers when `pull: always` matches more than one. 

This would mean Zero Downtime Continuous Delivery™ and would be oh so marvelous.

**Comment by MrMMorris** [comment]
CCing @smashwilson

**Comment by smashwilson** [comment]
That would be cool, although I'm not sure how it would actually be implemented. A pause between relaunching each container perhaps?

The trickiest part of doing this is knowing when a relaunched container is "ready" to serve traffic again - I believe Docker will bind the port while it's launching the container, so the service may not actually be ready to serve requests yet even when the port is listening. Setting a pause time would be a kludgy workaround, but what you really want is to wait for some kind of health check before continuing, and that's application-specific.

You will also often want to do things like drain traffic from a load balancer on the old containers before shutting them down, which would be pretty far out of scope for an Ansible module, I feel.

What I've thought about doing for this is managing two pools of containers, "blue" and "green", and toggling between them with a latch:

``` yaml
- name: relaunch {{ latch_active }} containers
  docker:
    image: smashwilson/foo
    name: foo_{{ latch_active }}_{{ item }}
    pull: always
    state: reloaded
    restart_policy: always
  with_sequence: count=4

- name: add {{ latch_active }} containers to the load balancer
  command: do that thing

- name: drain {{ latch_inactive }} container connections from the load balancer
  command: do that thing
```

I've also got a little project called [heatlamp](https://github.com/heatlamp) you might be interested in -- basically, the idea is to accept a webhook from DockerHub, quay, Jenkins, wherever, and take some action as a result... such as execute an Ansible playbook. Essentially, I'm trying to close the loop on a full, more simple continuous delivery system built on Ansible and Docker.
