### ISSUE TITLE
ec2_elb_lb doesn't update zones

### ISSUE THREAD

**Issue by ryanwalls** [ansible/ansible-modules-core#1106]
Setup the elb with 3 zones...

```
- name: Setting up Elastic Load Balancer
  local_action:
    module: ec2_elb_lb
    name: "{{ env }}-{{ region }}-login-elb"
    state: present
    connection_draining_timeout: 60
    cross_az_load_balancing: "yes"
    region: "{{ region }}"
    zones: 
      - us-west-2a
      - us-west-2b
      - us-west-2c
    listeners:
      - protocol: http
        load_balancer_port: 80
        instance_port: 80
```

Then try to change it to just 2 zones...

```
- name: Setting up Elastic Load Balancer
  local_action:
    module: ec2_elb_lb
    name: "{{ env }}-{{ region }}-login-elb"
    state: present
    connection_draining_timeout: 60
    cross_az_load_balancing: "yes"
    region: "{{ region }}"
    zones: 
      - us-west-2a
      - us-west-2b
    listeners:
      - protocol: http
        load_balancer_port: 80
        instance_port: 80
```

And the result is that the ELB still has 3 zones.
