### ISSUE TITLE
execute command "/usr/local/tomcat/bin/shutdown.sh" on the target, but the stdout is empty

### ISSUE THREAD

**Issue by chefunli** [ansible/ansible-modules-core#1121]
I execute command "/usr/local/tomcat/bin/shutdown.sh" on the target machine, but the stdout is empty!
Here all the yaml file that I used.

```
- name: Restart Tomcat
  hosts: all
  gather_facts: false
  user: root

 tasks:
    - name: stop tomcat
      shell: /usr/local/tomcat/bin/shutdown.sh
```

When I login into the target machine, and execute the same command in the terminal, the stdout is not empty!

Ansible version: 1.8.4

**Comment by mscherer** [comment]
Could you share the file, since it is quite hard to debug without being able to run it ?

**Comment by chefunli** [comment]
Example:
playbook file content

```
- name: Test tty output
  hosts: all
  gather_facts: false
  user: root

  tasks:
     - name: execute a.sh file and fetch the output

       shell: /tmp/a.sh
```

The a.sh file content:

```
#!/bin/sh
sh /tmp/b.sh
```

The b.sh file content:

```
#!/bin/sh

have_tty=0
if [ "`tty`" != "not a tty" ]; then
    have_tty=1
fi

if [ $have_tty -eq 1 ]; then
    echo "this is test"
fi
```

I can't fetch the output! But I can fetch the output by using ssh -t IP "/tmp/a.sh".
