### ISSUE TITLE
copy module should preserve mode of src file when mode is not explicitly set

### ISSUE THREAD

**Issue by eikef** [ansible/ansible-modules-core#1124]
##### Summary:

When using the copy module to copy multiple files to their destination, it would be really useful if the mode of the source was preserved. This would allow copying several files in a list without explicitly setting modes for each one.

In any case, this is the expected behavior when going by the documentation (which does not specify a default for mode -- leading one to assume the mode would be preserved unless explicitly specified).
##### Steps To Reproduce:

```
- name: copy test
  copy: src={{ item }} dest=/destination owner=root group=root
  with_items:
    - test1.sh
    - test1.conf
```

with test1.sh locally with 0755 permissions and test1.conf locally with 0644 permissions
##### Expected Results:

test1.sh on target with 0755 permissions and test1.conf on target with 0644 permissions
##### Actual Results:

test1.sh and test1.conf on target with 0644 permissions.

If you were to want to maintain the current behavior for backwards compatibility, the default mode should at least be documented (with possibly a recommendation to look at the synchronize module instead). Alternatively this could be done with something like 

```
- name: copy test
  copy: src={{ item }} dest=/destination owner=root group=root mode=preserve
  with_items:
    - test1.sh
    - test1.conf
```
