### ISSUE TITLE
copy module removes indentation with content param

### ISSUE THREAD

**Issue by bobrik** [ansible/ansible-modules-core#1127]
##### Issue Type:

Bug Report
##### Ansible Version:

```
λ ansible --version
ansible 2.0.0
  configured module search path = ../library
```

and

```
λ ansible --version
ansible 1.9.0.1
  configured module search path = ../library
```
##### Environment:

N/A
##### Summary:

I'm trying to set configuration from ansible playbook with copy module:

```
copy: content="{{ huh|to_nice_yaml }}\n" dest=/tmp/wtf.yaml
```

but target file lacks indentation leading to invalid configuration.
##### Steps To Reproduce:

Example playbook:

``` yaml
- hosts: web414
  vars:
    huh:
      ha:
        boo:
            hey:
            - 1
            - 2
            - 3
    uhm:
    - 1
    - 3
  tasks:
    - name: write some yaml
      copy: content="{{ huh|to_nice_yaml }}\n" dest=/tmp/wtf.yaml
```

My test python script that does what `copy` module should do:

``` python
#!/usr/bin/python

import jinja2
import yaml

e = jinja2.Environment()
e.filters["to_nice_yaml"] = lambda x: yaml.safe_dump(x, indent=4, allow_unicode=True, default_flow_style=False)

print e.from_string("{{ huh|to_nice_yaml }}").render({"huh":{"ha":{"boo":{"hey":[1,2,3]}},"uhm":[1,3]}})
```
##### Expected Results:

From my script:

``` yaml
ha:
    boo:
        hey:
        - 1
        - 2
        - 3
uhm:
- 1
- 3
```
##### Actual Results:

From ansible playbook:

``` yaml
ha:
boo:
hey:
- 1
- 2
- 3
uhm:
- 1
- 3
```
