### ISSUE TITLE
Docker: 'reloaded' state not recreating container

### ISSUE THREAD

**Issue by discordianfish** [ansible/ansible-modules-core#1129]
Hi,

according to the docs it should recreate the container if parameters changed:

> "reloaded" asserts that all matching containers are running and restarts any that have any images or configuration out of date. 

But that doesn't seem to work. Sometimes it doesn't reload even though parameters changed:

```
- hosts: 127.0.0.1
  connection: local
  tasks:
  - docker:
      image: ubuntu
      name: test
      state: reloaded
      command: "nc -l -k 2342"
```

Running this, creates a container. Running it again, doesn't touch it. So far so good. Now I added 'restart_policy: always', ran the play again and it didn't recreate the container.

I'm running the latest devel branch (just pulled, including the sub repos).
