### ISSUE TITLE
ec2 module cannot create encrypted volumes

### ISSUE THREAD

**Issue by jbrendel** [ansible/ansible-modules-core#1134]
While with the ec2_vol module encrypted volumes can be created, the 'built-in' volume specification in the ec2 module does not allow for it. The 'encrypted' attribute can be set, but it's ignored.

Example:

```
- ec2:
    instance_type: m3.medium
    image: ami-123456
    volumes:
      - device_name: /dev/sdb
        device_type: gp2
        volume_size: 100
        encrypted: true
```

However, the created volume will not be encrypted.

Fortunately, the fix is very straight forward:

In cloud/amazon/ec2.py, at the end of create_block_device() add this parameter to the "return BlockDeviceType(....) call:

```
...
encrypted=volume.get('encrypted', False),
....
```

I confirmed locally that this produces an encrypted volume.
