### ISSUE TITLE
ec2_eip changes the public ip of the instance without updating the inventory

### ISSUE THREAD

**Issue by Pallokala** [ansible/ansible-modules-core#1141]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 2.0.0 (devel 02e7385002) last updated 2015/04/15 13:09:17 (GMT +300)
  lib/ansible/modules/core: (detached HEAD 04c34cfa02) last updated 2015/04/07 15:56:08 (GMT +300)
  lib/ansible/modules/extras: (detached HEAD 21fce8ac73) last updated 2015/04/07 15:56:15 (GMT +300)
  v2/ansible/modules/core: (detached HEAD 34784b7a61) last updated 2015/04/07 15:56:21 (GMT +300)
  v2/ansible/modules/extras: (detached HEAD 21fce8ac73) last updated 2015/04/07 15:56:28 (GMT +300)
  configured module search path = None
##### Environment:

Ansble is run from MacOS Yosemite.
##### Summary:

When binding AWS Elastic IP to an instance which is already in inventory the new ip is not added to the inventory nor is the instances old ip removed from the inventory. This causes errors in subsequent tasks when ansible tries to access non-existent hosts.

AWS Elastic IP module should update the in-memory inventory to reflect the change of the host ip.
##### Steps To Reproduce:

This requires an AWS account, an existing instance with non-elastic-ip public ip and existing elastic ip. Run with dynamic ec2 -inventory script:

```

---
  - hosts: localhost
  - tasks:
    - name: Bid elastic IPs to the feeds
      ec2_eip:
        instance_id: "{{ ec2_id_of_the_instance }}"
        public_ip: "{{ ip_of_reserver_elastic_ip }}"
        region: "{{ aws_region_in_use }}"
  # gather facts, this shows error when trying to access eip -bound instances old ip
  # new eip instances do not show up
  - hosts: all
  - action: setup
```
##### Expected Results:

Inventory is updated and hostvars are moved to new host ip.
##### Actual Results:

Inventory is not updated, subsequent tasks miss the elastic ip -hosts and show error with the old ips of the elastic ip bound instances.
