### ISSUE TITLE
route53: incorrectly handles string TTL

### ISSUE THREAD

**Issue by moorereason** [ansible/ansible-modules-core#1156]
##### Issue Type:

Bug Report (with proposed fix below)
##### Ansible Version:

ansible 1.9.0.1
  configured module search path = None
##### Environment:

CentOS Linux release 7.1.1503 (Core)
ansible-1.9.0.1-1.el7.noarch
python-boto-2.34.0-4.el7.noarch
##### Summary:

Setting the `ttl` value to a string causes the task to always return `changed=True`.  I ran across the issue file doing a `item.ttl | default('3600')` in a task.  I'm in the habit of quoting default values as strings for some reason. :innocent: 
##### Steps To Reproduce:

``` yaml
- route53:
    command: create
    zone: abc.com.
    record: host.abc.com.
    type: A
    ttl: '3600'
    value: 127.0.0.1
    overwrite: yes
```
##### Expected Results:

Expect subsequent plays to return `changed=False`.
##### Actual Results:

Always returns `changed=True`.
##### Proposed Fix

Change [this line](https://github.com/ansible/ansible-modules-core/blob/d960dc1584fb17ebdb720c0c65f7ae155ab612fa/cloud/amazon/route53.py#L212) to:

``` python
ttl_in = int(module.params.get('ttl'))
```

**Comment by moorereason** [comment]
I just realized that using a `default()` filter triggers this bug.  I thought the issue only happened when quoting the ttl as the `default` parameter; however, using filters requires that the `value` is quoted, so the `value` always ends up being a string.

Example that triggers this bug:

``` yaml
- route53:
    command: create
    zone: item.zone
    record: item.record
    type: item.type
    ttl: "{{ item.ttl | default(3600) }}"
    value: item.value
    overwrite: yes
  with_items: records
```
