### ISSUE TITLE
Docker 1.6 cannot mount a volume with a single file

### ISSUE THREAD

**Issue by mkuzmin** [ansible/ansible-modules-core#1158]
Issue Type: bug report
Ansible Version: 1.9.0.1
Environment: Ubuntu 14.04

**Summary:**
Docker allows mounting volumes specifying a single file, like `docker run -v /etc/profile:/etc/profile:ro busybox`
Starting from Docker version 1.6, Ansible cannot mount such volumes, if the file already exist within an image, but needs to be overwritten by a copy from the host.

This is probably a bug in Docker engine or`docker-py` library, but I can reproduce it only from Ansible.
Docker-compose has a similar issue: https://github.com/docker/compose/issues/424

**Steps To Reproduce:**
Run this playbook:

```

---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - docker:
        image: busybox
        volumes:
        - "/etc/profile:/etc/profile:ro"
```

**Expected Results:**
Having Docker 1.5 it applies normally.

**Actual Results:**
With Docker 1.6 Ansible fails:

```
TASK: [docker ] ***************************************************************
failed: [127.0.0.1] => {"changed": false, "failed": true}
msg: Docker API Error: file exists at /var/lib/docker/aufs/mnt/f2ed605b182792d69c397b6dcc7d7c6c40193e89d49d047b33934f779423c38f/etc/profile, can't create volume there
```
