### ISSUE TITLE
synchronize: comma as an rsync_opts separator conflicts with rsync's chmod separator

### ISSUE THREAD

**Issue by UnkindPartition** [ansible/ansible-modules-core#1163]
##### Issue Type:

Bug report
##### Ansible Version:

```
ansible 1.8.2
  configured module search path = None
```
##### Summary:

synchronize interprets commas inside `--chmod` as an rsync_opts separator
##### Steps To Reproduce:

Attempt to pass `--chmod=Du=rwx,Dgo=rx,Fu=rw,Fgo=r` to rsync.
##### Expected Results:

There should be a way to make this work, e.g.
- have a way to escape commas, or
- make chmod a separate option of synchronize
##### Actual Results:

```
failed: [vagrant -> 127.0.0.1] => {"cmd": "rsync --delay-updates -FF --compress --delete-after --checksum --archive --rsh 'ssh -i /home/feuerbach/.vagrant.d/insecure_private_key -S none -o StrictHostKeyChecking=no' --prune-empty-dirs --chmod=Du=rwx Dgo=rx Fu=rw Fgo=r --copy-links --exclude=/tmp/ --out-format='<<CHANGED>>%i %n%L' \"~/www/main/_site/\" \"root@192.168.33.15:/var/www/\"", "failed": true, "rc": 23}
msg: rsync: link_stat "/home/feuerbach/www/server/Dgo=rx" failed: No such file or directory (2)
rsync: link_stat "/home/feuerbach/www/server/Fu=rw" failed: No such file or directory (2)
rsync: link_stat "/home/feuerbach/www/server/Fgo=r" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1165) [sender=3.1.1]
```

**Comment by Jmainguy** [comment]
@feuerbach Can you show the whole command you passed to create this error?

**Comment by abadger** [comment]
At least in 2.0 passing rsync_opts like this will work:

```
---
- hosts: rhel6-test
  tasks:
  - name: synchronize something from central mirror to localhost
    synchronize:
      src: /etc/yum.repos.d
      dest: "/tmp/foobar/"
      delete: yes
      recursive: yes
      mode: pull
      rsync_opts:
        - "--chmod=Du=rwx,Dgo=rx,Fu=rw,Fgo=r"
```
