### ISSUE TITLE
Template module fails to create files that require sudo permission with password

### ISSUE THREAD

**Issue by iandyh** [ansible/ansible-modules-core#1192]
##### Environment:

Both Cent OS 6 for source machine and target machine
##### Summary:

The template module fails(err: `ssh connection closed waiting for password prompt`) at creating files that require sudo permission with password.
##### Steps To Reproduce:

``` yml
- name: create some init script
  template: src=tmpl.j2 dest=/etc/init.d/{{ item }}
  with_items: [1,2,3]
  sudo: yes
```

with the command: `ansible-playbook -i inventory xxx.yml --ask-become-pass`
##### Expected Results:

Login as a normal user, sudo as a root user and create the init script under /etc/init.d.
##### Actually Results:

`ssh connection closed waiting for password prompt`

However, I have tried other modules, for instance, `file` module, it's working fine with same setup.
For your information, I have turned off the pipelining.

Looking forward to your reply! Thanks.

**Comment by blackreed9** [comment]
I was unable to reproduce this in my CentOS environment running 1.9.1.  Is there anything else you can add about your environment?  I'll try to load up a 1.9.0.1 and see if I can reproduce it there.

Environment: CentOS release 6.3 (Final)
Ansible: ansible 1.9.1

```
---
- hosts: all
  tasks:
    - name: create some init script
      template: src=files/foo.j2 dest=/etc/init.d/{{ item }}
      with_items: [1,2,3]
      sudo: yes
```

```
@core-jd 01:25:56 ~/ansible$ ansible-playbook -i hosts --ask-become-pass monkey.yml
SUDO password:

PLAY [all] ********************************************************************

GATHERING FACTS ***************************************************************
ok: [10.20.0.26]

TASK: [create some init script] ***********************************************
changed: [10.20.0.26] => (item=1)
changed: [10.20.0.26] => (item=2)
changed: [10.20.0.26] => (item=3)

PLAY RECAP ********************************************************************
10.20.0.26                 : ok=2    changed=1    unreachable=0    failed=0
```

```
@core-a1 01:26:47 /etc/init.d# ls -l /etc/init.d/
total 176
-rw-r--r--  1 root root     7 May  4 13:26 1
-rw-r--r--  1 root root     7 May  4 13:26 2
-rw-r--r--  1 root root     7 May  4 13:26 3
...snip...
```
