### ISSUE TITLE
Parameter ec2_ami is not legal parameter

### ISSUE THREAD

**Issue by wmarra** [ansible/ansible-modules-core#1200]
Hi, I'm having a error `ERROR: ec2_ami is not a legal parameter of an Ansible Play` when I execute my playbook to create a new image in ec2 Amazon. I checked that modules comes with ansible installation by default, but this parameter doesn't work. What I do to fix? Thanks!

Playbook:

```
- ec2_ami:
    aws_access_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    aws_secret_key: xxxxxxxxxxxxxxx
    instance_id: i-xxx
    wait: yes
    name: testing
  register: instancese
```
