### ISSUE TITLE
Docker module: can't link same container with different aliases

### ISSUE THREAD

**Issue by bandesz** [ansible/ansible-modules-core#1209]
##### Affected module:

cloud/docker
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 2.0.0 (devel 946c37fd88)
##### Environment:

N/A
##### Summary:

I need to link the same docker container with different aliases, but I can't - it will be only linked with the last alias. 
##### Steps To Reproduce:

Write a docker task similar to this:

```
- name: run docker container
  docker:
    links:
    - "container1:alias1"
    - "container1:alias2"
```
##### Expected Results:

container1 should be linked with "alias1" and "alias2" aliases
##### Actual Results:

container1 is linked only with "alias2" alias
