### ISSUE TITLE
lxc_conf parameters of docker module appended incorrectly 

### ISSUE THREAD

**Issue by ksoftirqd** [ansible/ansible-modules-core#1214]
Issue Type: bug report
Ansible Version: 1.9.0.1
Environment: Ubuntu 14.04
##### Summury

When lxc_conf parameter value contains colon (e.g. like in lxc.network.[ipv6|ipv6.gateway|hwaddr], value split incorrectly, so that only part of it gets into containers hostconfig.

E.g.:

``` yaml
- name: some container
  docker:
    [...]
    lxc_conf:
      - "lxc.network.ipv6:1234:4567::1/64"
      [...]
```
##### Expected results:

`"LxcConf":[{"Key":"lxc.network.ipv6","Value":"1234:4567::1/64"}]`
##### Actual results:

`"LxcConf":[{"Key":"lxc.network.ipv6","Value":"1234"}]`

Seems like setting `maxsplit` to 1 in modules/core/cloud/docker/docker.py:525 fixes the problem:

``` python
                parts = option.split(':', 1)
```
