### ISSUE TITLE
Feature Idea : cloudformation "describe" state

### ISSUE THREAD

**Issue by wojtek-oledzki** [ansible/ansible-modules-core#1224]
What do people thing about "describe" or "available" state for cloudformation module. I'm happy to add it in and send pull req I just want to make sure it will get accepted before I start it :)

**Use case:**

build stack in separate playbook/ansible run, and then I would like to use it like

``` YML
  - name: Get MyStack tier
    cloudformation:
      aws_access_key: "{{ aws.access_key }}"
      aws_secret_key: "{{ aws.secret_key }}"
      stack_name: my-stack-name
      state: available
    register: mystack_data

  - name: use {{ mystack_data.outputs.* }} in some awesome ways
```

I really don't want to use lookup plugins, as it's a bit ugly and limited to specify aws secrets and keys per run. Also I need to run lookup for each stack output.
