### ISSUE TITLE
Docker module requires image with state=absent

### ISSUE THREAD

**Issue by lorin** [ansible/ansible-modules-core#1239]
##### Ansible Version:

```
ansible 1.9.1
  configured module search path = None
```
##### Environment:

OS X (boot2docker)
##### Summary:

Attempting to remove a running docker container without specifying an image results in an error, even though an image name shouldn't be required.
##### Steps To Reproduce:

Failing playbook:

```
- hosts: localhost
  tasks:
    - name: start redis container
      docker: name=redistest image=redis ports=6379:6379

    - name: remove redis container
      docker: name=redistest state=absent
```
##### Expected Results:

Output that looks like:

```
TASK: [remove redis container] ************************************************
changed: [localhost]
```
##### Actual Results:

Following error:

```
TASK: [remove redis container] ************************************************
failed: [localhost] => {"failed": true}
msg: missing required arguments: image

FATAL: all hosts have already failed -- aborting
```
