### ISSUE TITLE
win_user module fails when 'fullname' or 'description' parameters are specified for the new user

### ISSUE THREAD

**Issue by mkoshelev** [ansible/ansible-modules-core#1241]
##### Issue Type:

Bug report
##### Ansible Version:

ansible 1.9.1
  configured module search path = None
##### Environment:

Master system: Fedora 21
Target system: Windows 2012 r2
##### Summary:

When either of 'fullname' or 'description' parameters are specified when creating a **new** user, win_user module fails with "Cannot convert value to type System.String" error message.
Note, the same code works without problem if user already exists on the target system - in this case full name / description for this user is updated to the value specified.
##### Steps To Reproduce:

Provided there's no 'testuser' account on the target system:

```
- name: Test win_user module
  hosts: win-test

  tasks:
  - name: Create test user
    win_user:
      name: "testuser"
      fullname: "Test User"
      description: "Testing win_user module"
      password: "testPwd0"
      state: present
```
##### Expected Results:

User created as requested.
##### Actual Results:

Task fails with the following error message:

```
TASK: [Create test user] ****************************************************** 
failed: [win-test] => {"failed": true}
msg: Cannot convert value to type System.String.
```
