### ISSUE TITLE
authorized_keys with exclusive=yes doesn't work as expected

### ISSUE THREAD

**Issue by slankes** [ansible/ansible-modules-core#1253]
This snipped from the documentation works as expected:

```
- name: Set up authorized_keys for the deploy user
  authorized_key: user=deploy
                  key="{{ item }}"
  with_file:
    - public_keys/doe-jane
    - public_keys/doe-john
```

But as soon as I add

```
exclusive=yes
```

I'll end up with only doe-john in my authorized_keys file instead of both (which I would expect)

I'd think that exclusive should work on all keys in the block and not on only on the one it is working _with_.
