### ISSUE TITLE
Mount module "state: unmounted" should not require src and fstype arguments

### ISSUE THREAD

**Issue by tetherit** [ansible/ansible-modules-core#1259]
When wanting to ensure a particular path has nothing mounted on it, I would like to be able to do:

```
- name: "Ensure chroot paths are not mounted"
  mount:
    name: "{{ item }}"
    state: unmounted
  with_items:
    - var/cache/apt
    - dev
    - proc
    - sys
```

But Ansible throws this error:

```
failed: [testhost] => (item=proc) => {"failed": true, "item": "proc"}
msg: missing required arguments: src,fstype
```

I believe when making sure a path is not mounted, the arguments src and fstype should be optional.
