### ISSUE TITLE
fetch module fails checksum when user's shell set to /bin/tcsh 

### ISSUE THREAD

**Issue by breathe** [ansible/ansible-modules-core#1297]
I was running into a strange issue where the fetch module checksum was failing against some hosts -- but not others.

Extracting out a minimal example playbook:

```
- hosts: all
  remote_user: root
  tasks:
    - name: "Synchronize repositories version of the hostkey from the remote version"
      fetch: src=/etc/ssh/ssh_host_rsa_key.pub dest={{playbook_dir}}/files flat=yes
```

Steps to reproduce:
1. ssh root@some_host
2. chsh -s /bin/tcsh
3. exit
4. rm -rf ~/.ansible/cp/ansible-ssh-some_host-root
5. re-run playbook with an inventory that includes some_host

Note that I'm removing the ssh control process after changing the remote_user's shell -- without doing so the bug won't get triggered as the ssh control process is apparently already established in a way independent of the user's login shell setting (?)

Control node is osx yosemite, remote node is centos 7.1.  Using ansible as installed by homebrew.

```
> ansible --version
ansible 1.9.1
  configured module search path = None
```
