### ISSUE TITLE
Ansible is unable to restart ssh on Ubuntu 14.04

### ISSUE THREAD

**Issue by svetlyak40wt** [ansible/ansible-modules-core#1298]
Hi! I'm trying this simple playbook:

```
- hosts: any
  user: root
  tasks:
    - name: Restart sshd
      service:
        name: 'ssh'
        state: 'restarted'
```

I receive this error on hosts with Ubuntu 14.04:

```
TASK: [Restart sshd] **********************************************************
failed: [clupea.svetlyak.ru] => {"failed": true}

FATAL: all hosts have already failed -- aborting
```

but it completes with success on Ubuntu 12.04.

And if I run manually `service ssh restart` then it restarts as expected.

Probably, solving #882 issue could provide more info about what is happening.
