### ISSUE TITLE
ec2 module. Instance tags is not available immediately after creating the instance.

### ISSUE THREAD

**Issue by wangqiang8511** [ansible/ansible-modules-core#1302]
# module

ec2 module
# Description

Instance tags is not available immediately after creating the instance.

Tasks:

``` yaml

---
# == Create ec2 instance
- name: Bootstrap ec2 instance
  ec2:
    region: "{{ region }}"
    key_name: "{{ keypair }}"
    instance_type: "{{ instance_type }}"
    image: "{{ image }}"
    count: "{{ number_of_instance}}"
    wait_timeout: 500 
    instance_profile_name: "{{ iam_role }}"
    group_id: "{{ security_group_ids }}"
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    wait: true
    wait_timeout: 500 
    instance_tags:
      Name: test.ansible
      ansible: "true"
    volumes:
      - device_name: /dev/xvda
        volume_size: 10
        delete_on_termination: true
      - device_name: /dev/xvdf
        volume_size: 10
        delete_on_termination: true
      - device_name: /dev/sdb
        ephemeral: ephemeral0
  register: ec2 

- name: debug tag info
  sudo: yes 
  debug: "var={{ item }}"
  with_items: ec2.instances
```

Result:

``` bash
TASK: [bootstrap | debug tag info] ******************************************** 
ok: [127.0.0.1] => (item={xxx}) => {
    "item": {
        "ami_launch_index": "0",
        "architecture": "x86_64",
        "dns_name": "",
        "ebs_optimized": false,
        "groups": {
            "sg-xxx": "xxx"
        },
        "hypervisor": "xen",
        "id": "i-xxx",
        "image_id": "ami-1ecae776",
        "instance_type": "t2.micro",
        "kernel": null,
        "key_name": "razerbigdata",
        "launch_time": "2015-05-11T03:52:17.000Z",
        "placement": "us-east-1d",
        "private_dns_name": "xxx",
        "private_ip": "x.x.x.x",
        "public_dns_name": "", 
        "public_ip": null,
        "ramdisk": null,
        "region": "us-east-1",
        "root_device_name": "/dev/xvda",
        "root_device_type": "ebs",
        "state": "running",
        "state_code": 16, 
        "tags": {}, 
        "tenancy": "default",
        "virtualization_type": "hvm"
    },  
    "var": {
        "{'kernel':": "{'kernel':"
    }
}

```

The tag fields is empty.
# Fix

The reason for this is, tag is added after the boto.instance object is create. They need to be updated to get tags.

https://github.com/ansible/ansible-modules-core/pull/1303
