### ISSUE TITLE
ec2_vol reports changed = false even if a new vol is created or attched

### ISSUE THREAD

**Issue by bennojoy** [ansible/ansible-modules-core#1308]
##### Issue Type:

Bug Report
##### Component Name:

ec2_vol 
##### Summary:

ec2_vol reports changed = false even if a new vol is created or attched
##### Ansible Version:

1.9 +
##### Environment:

N/A
##### Steps To Reproduce:

The Playbook to create a new volume and attach to a instance

```
- hosts: localhost
  tasks:
    - ec2_vol:
        instance: i-12345
        volume_size: 3
        name: benz
        zone: "us-east-1c"
        device_name: xvdq
```
##### Expected Results:

```
Changed=True
```
##### Actual Results:

```
{"changed": false, "device": "xvdq", "volume_id": "vol-816b9d6f", "volume_type": "standard"}
```
