### ISSUE TITLE
command/shell + with_items ignores failures

### ISSUE THREAD

**Issue by tetherit** [ansible/ansible-modules-core#1312]
HI there,

I have this in my task:

``` yaml
- name: Run deploy commands in app dir
  shell: "RAILS_ENV={{ app_env }} {{ item }}"
  args:
    chdir: "{{ deploy_to }}"
  with_items:
    - 'bundle install --retry=3'
    - 'bundle exec rake assets:precompile'
    - 'bundle exec whenever -w'
  sudo: no
```

There was an upstream issue which caused bundle install to fail, but the shell module seems to ignore this and run all the other commands anyway.

It should really stop whenever it fails to run a command, just like it does when not using with_items.
