### ISSUE TITLE
Teach ec2_lc to automatically generate names from a base name

### ISSUE THREAD

**Issue by jsternberg** [ansible/ansible-modules-core#1321]
The ec2_lc module gives us a little bit of difficulty right now because it can't modify a launch configuration. We would like it if the module allowed an option to automatically generate a hash of the module parameters and include it in the launch configuration name. Right now, we have to manually update the uuid like this:

```
- ec2_lc:
    name: myservice-<hash1>
    state: present

- ec2_asg:
    launch_config_name: myservice-<hash1>
    replace_all_instances: yes
    state: present
```

We'd have to go and replace hash1 with hash2 manually every time we make a change. Sometimes, changes are made implicitly by a variable getting updated somewhere in the system (like a new global AMI).

I would like to be able to use `register` with `ec2_lc` and then pass the result to `ec2_asg` and have `ec2_lc` automatically determine the name using something like an md5 hash. So I would do:

```
- ec2_lc:
    name: myservice
    hash_method: md5
    state: present
```

Then have this create a launch configuration with `myservice-<md5hashofparams>`.

I'm not sure what the desired method is nor do I know what the argument should be named.
