### ISSUE TITLE
package:apt, documentation issue

### ISSUE THREAD

**Issue by zerkms** [ansible/ansible-modules-core#1328]
##### ISSUE TYPE

Documentation Report
##### COMPONENT NAME

apt module
##### ANSIBLE VERSION

N/A
##### SUMMARY

```
  install_recommends:
    description:
      - Corresponds to the C(--no-install-recommends) option for I(apt). Default behavior (C(yes)) replicates apt's default behavior; C(no) does not install recommended packages. Suggested packages are never installed.
    required: false
    default: yes
    choices: [ "yes", "no" ]
```

The problem here is that the default apt's behaviour for interactive session is to **NOT** install recommended packages. So the "replicates apt's default behavior" part is not precisely correct I think.

It's only by default if you specify `-y` option.
