### ISSUE TITLE
stat module documentation claims checksum and md5 are boolean

### ISSUE THREAD

**Issue by ploxiln** [ansible/ansible-modules-core#1371]
This is in latest master.

checksum and md5 are strings (of hex chars), when they are present.

**Comment by ploxiln** [comment]
I'll go ahead and quote the documentation source:

```
        md5:
            description: md5 hash of the path
            returned: success, path exists and user can read stats and path supports hashing and md5 is supported
            type: boolean
            sample: True
        checksum:
            description: hash of the path
            returned: success, path exists and user can read stats and path supports hashing
            type: boolean
            sample: True
```

"type" and "sample" are wrong
