### ISSUE TITLE
vsphere_guest vm_disk 'type' parameter is silently ignored

### ISSUE THREAD

**Issue by aioue** [ansible/ansible-modules-core#1380]
##### Issue Type:

Bug Report
##### Ansible Version:

1.9.1
##### Ansible Configuration:

n/a
##### Environment:

OS X 10.10.3, vCenter 6
##### Summary:

Input to vsphere_guest module, vm_disk 'type' parameter is ignored. Does not throw errors for bad input.
##### Steps To Reproduce:

Run module with this input:

```
- name: Create other-app VM for testing
  connection: local
  vsphere_guest:
    vcenter_hostname: 110.120.113.333
    username: foo
    password: bar
    guest: other-app-{{ 9 |random}}{{ 9 |random}}{{ 9 |random}}{{ 9 |random}}{{ 9 |random}}
    vm_disk:
      disk1:
        size_gb: 32
        type: funkyChicken
        datastore: foo_VMFS_1
    vm_hardware:
      memory_mb: 8192
      num_cpus: 2
      osid: ubuntu64Guest
      scsi: lsi
    vm_nic:
      nic1:
        type: vmxnet3
        network: foo-other-app
        network_type: dvs
    vm_extra_config:
      notes: this is a test VM
    esxi:
      datacenter: foo-DC
      hostname: foo-dc2-esxi2
```
##### Expected Results:

Error saying 'funkyChicken' is not a valid disk type.
##### Actual Results:

```
<localhost> REMOTE_MODULE vsphere_guest vcenter_hostname=110.120.113.333 guest=other-app-22732 password=VALUE_HIDDEN username=foo
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1432134778.87-76768885543882 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1432134778.87-76768885543882 && echo $HOME/.ansible/tmp/ansible-tmp-1432134778.87-76768885543882']
<localhost> PUT /var/folders/s0/jy7xj1915_bg41nmvc3cjcdw0000gn/T/tmpMEX1JT TO /Users/tpai/.ansible/tmp/ansible-tmp-1432134778.87-76768885543882/vsphere_guest
<localhost> EXEC ['/bin/sh', '-c', u'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /Users/tpai/.ansible/tmp/ansible-tmp-1432134778.87-76768885543882/vsphere_guest; rm -rf /Users/tpai/.ansible/tmp/ansible-tmp-1432134778.87-76768885543882/ >/dev/null 2>&1']
changed: [localhost] => {"ansible_facts": {"hw_eth0": {"addresstype": "assigned", "ipaddresses": null, "label": "Network adapter 1", "macaddress": "00:50:56:b6:36:91", "macaddress_dash": "00-50-56-b6-36-91", "summary": "DVSwitch: 33 aa 36 50 12 b3 ba a6-1f b5 1d 2b e8 04 c2 01"}, "hw_guest_full_name": "Ubuntu Linux (64-bit)", "hw_guest_id": "ubuntu64Guest", "hw_memtotal_mb": 8192, "hw_name": "other-app-22732", "hw_processor_count": 2, "hw_product_uuid": "42360560-b591-a15d-f6bd-de2341927943", "module_hw": true}, "changed": true, "changes": "Created VM other-app-22732"}
```
