### ISSUE TITLE
Mutiple inputs to vsphere_guest module are silently ignored when launching from a template

### ISSUE THREAD

**Issue by aioue** [ansible/ansible-modules-core#1381]
[![Bountysource](https://www.bountysource.com/badge/issue?issue_id=16226901)](https://www.bountysource.com/issues/16226901-mutiple-inputs-to-vsphere_guest-module-are-silently-ignored-when-launching-from-a-template?utm_source=16226901&utm_medium=shield&utm_campaign=ISSUE_BADGE)
#### Issue Type:

Bug Report
#### Ansible Version:

1.9.1
#### Ansible Configuration:

n/a
#### Environment:

OS X 10.10.3, vCenter 6
#### Summary:

Mutiple inputs to vsphere_guest module are ignored when launching from a template. Does not throw errors for invalid data either.

vm_nic, vm_disk & vm_hardware parameters are all ignored.
#### Steps To Reproduce:

This command creates VM with but ignores valid options. Invalid options are ignored as well.

```
  - name: Create other-app VM for testing
    connection: local
    vsphere_guest:
      vcenter_hostname: 110.120.113.333
      username: foo
      password: bar
      guest: other-app-{{ 9 |random}}{{ 9 |random}}{{ 9 |random}}{{ 9 |random}}{{ 9 |random}}
      vm_disk:
        disk1:
          size_gb: 32
          type: thin
          datastore: foo_VMFS_1
      vm_hardware:
        memory_mb: 8192
        num_cpus: 2
        osid: ubuntu64Guest
        scsi: lsi
      vm_nic:
        nic1:
          type: vmxnet3
          network: slartibartfast
          network_type: dvs
      vm_extra_config:
        notes: this is a test VM
      cluster: Ontrack-Cluster1
      resource_pool: /Resources/foo-default
      from_template: yes
      template_src: ubuntu-14.04-template
      esxi:
        datacenter: foo-DC
```
#### Expected Results:

VM launched with specific NIC, disk and hardware settings. Invalid settings (such as mis-spelt NIC networks should produce an error).
#### Actual Results:

VM is launched but network, CPU and RAM that was originally specified in the template is retained.

```
<localhost> REMOTE_MODULE vsphere_guest template_src=ubuntu-14.04-template vcenter_hostname=110.120.113.333 cluster=Ontrack-Cluster1 guest=other-app-03770 password=VALUE_HIDDEN resource_pool=/Resources/foo-default username=foo
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1432138365.27-28886126071913 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1432138365.27-28886126071913 && echo $HOME/.ansible/tmp/ansible-tmp-1432138365.27-28886126071913']
<localhost> PUT /var/folders/s0/jy7xj1915_bg41nmvc3cjcdw0000gn/T/tmpDWPVuq TO /Users/tpai/.ansible/tmp/ansible-tmp-1432138365.27-28886126071913/vsphere_guest
<localhost> EXEC ['/bin/sh', '-c', u'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /Users/tpai/.ansible/tmp/ansible-tmp-1432138365.27-28886126071913/vsphere_guest; rm -rf /Users/tpai/.ansible/tmp/ansible-tmp-1432138365.27-28886126071913/ >/dev/null 2>&1']
changed: [localhost] => {"changed": true}
```
