### ISSUE TITLE
vsphere_guest reconfigure powers on VM

### ISSUE THREAD

**Issue by gsatliawol** [ansible/ansible-modules-core#1391]
Issue type: Bug Report

Ansible  Version:  ansible 1.9.1

Ansible Configuration: 

n/a

Environment: 
CentOS 6 -> ESX 5.0.0

Summary: 

Reconfiguring a VM also powers on a powered off VM.  

Steps to Reproduce: 

Running the following play:

```
  - name: change nic
    vsphere_guest:
      vcenter_hostname: {{ my_vc }}
      username: "{{ vc_user }}"
      password: "{{ vc_pw }}"
      guest: "{{ vm_hostname }}"
      state: reconfigured
      force: yes
      vm_nic:
        nic1:
          type: vmxnet3
          network_type: standard
          network: "VM Network"
      vm_hardware:
        memory_mb: 8192 # was 4096
        num_cpus: 2
      esxi:
        datacenter: "{{ my_dc }}"
        hostname: "{{ my_esxhost }}"
```

Expected behaviour: VM is reconfigured, but left powered off

Exhibited behaviour: VM is reconfigured but unexpectedly powers on!
