### ISSUE TITLE
Add support for port ranges to the Docker module

### ISSUE THREAD

**Issue by olvesh** [ansible/ansible-modules-core#1397]
##### Issue Type:

Bug
##### Ansible Version:

ansible 1.9.1
##### Environment:

Master Mac OSX to Ubuntu Trusty hosts and docker 1.6.2
##### Summary:

Docker supports port ranges, e.g. by specifying '-p 9300-9400'. When trying this with ansible I get: 

```
failed: [10.0.2.55] => {"failed": true, "parsed": false}
BECOME-SUCCESS-ghryqjnlpehwkqtbyehqprvyxgwqabtn
Traceback (most recent call last):
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1432289474.53-189612252973916/docker", line 3110, in <module>
    main()
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1432289474.53-189612252973916/docker", line 1449, in main
    manager = DockerManager(module)
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1432289474.53-189612252973916/docker", line 534, in __init__
    self.port_bindings = self.get_port_bindings(self.module.params.get('ports'))
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1432289474.53-189612252973916/docker", line 710, in get_port_bindings
    container_port = int(parts[-1])
ValueError: invalid literal for int() with base 10: '9300-9400'
OpenSSH_6.2p2, OSSLShim 0.9.8r 8 Dec 2011
```
##### Steps To Reproduce:

Try the following play:

``` yaml
- name: Install elastic search docker image
  docker:
    name:     elasticsearch
    image:    elasticsearch:1.5.2
    state:    started
    restart_policy: always
    ports:
     - 9200:9200
     - 9300-9400:9300-9400
```
##### Expected Results:

A working and running docker image 
##### Actual Results:

An exception.

**Comment by olvesh** [comment]
Workaround: 

``` yaml
- name: Install elastic search docker image
  docker:
    name:     elasticsearch
    image:    elasticsearch:1.5.2
    state:    started
    restart_policy: always
    ports:
     - 9200:9200
     #Workaround for: https://github.com/ansible/ansible-modules-core/issues/1397
     - 9300:9300
     - 9301:9301
     - 9302:9302
     - 9303:9303
     - 9304:9304
     - 9305:9305
     - 9306:9306
     - 9307:9307
     - 9308:9308
     - 9309:9309
     - 9310:9310
     - 9311:9311
     - 9312:9312
     - 9313:9313
     - 9314:9314
     - 9315:9315
     - 9316:9316
     - 9317:9317
     - 9318:9318
     - 9319:9319
     - 9320:9320
     - 9321:9321
     - 9322:9322
     - 9323:9323
     - 9324:9324
     - 9325:9325
     - 9326:9326
     - 9327:9327
     - 9328:9328
     - 9329:9329
     - 9330:9330
     - 9331:9331
     - 9332:9332
     - 9333:9333
     - 9334:9334
     - 9335:9335
     - 9336:9336
     - 9337:9337
     - 9338:9338
     - 9339:9339
     - 9340:9340
     - 9341:9341
     - 9342:9342
     - 9343:9343
     - 9344:9344
     - 9345:9345
     - 9346:9346
     - 9347:9347
     - 9348:9348
     - 9349:9349
     - 9350:9350
     - 9351:9351
     - 9352:9352
     - 9353:9353
     - 9354:9354
     - 9355:9355
     - 9356:9356
     - 9357:9357
     - 9358:9358
     - 9359:9359
     - 9360:9360
     - 9361:9361
     - 9362:9362
     - 9363:9363
     - 9364:9364
     - 9365:9365
     - 9366:9366
     - 9367:9367
     - 9368:9368
     - 9369:9369
     - 9370:9370
     - 9371:9371
     - 9372:9372
     - 9373:9373
     - 9374:9374
     - 9375:9375
     - 9376:9376
     - 9377:9377
     - 9378:9378
     - 9379:9379
     - 9380:9380
     - 9381:9381
     - 9382:9382
     - 9383:9383
     - 9384:9384
     - 9385:9385
     - 9386:9386
     - 9387:9387
     - 9388:9388
     - 9389:9389
     - 9390:9390
     - 9391:9391
     - 9392:9392
     - 9393:9393
     - 9394:9394
     - 9395:9395
     - 9396:9396
     - 9397:9397
     - 9398:9398
     - 9399:9399
     - 9400:9400
```
