### ISSUE TITLE
ec2_elb: Ansible claims changed=true when removing instance not in elb

### ISSUE THREAD

**Issue by lorin** [ansible/ansible-modules-core#140]
##### Summary:

When using the ec2_elb module to remove an instance from a load balancer, if the instance was not in the load balancer before running the task, Ansible incorrectly reports the state has changed.
##### Steps To Reproduce:

Invoke the ec2_elb module to remove an instance that's not in a load balancer (or just run it twice)

```

---
- name: remove instance from a load balancer
  hosts: localhost
  vars:
    instances:
      - i-123456ab
    lb: my-load-balancer
  tasks:
    - name: take the instances out of the load balancer
      local_action: ec2_elb
      args:
        instance_id: "{{ item }}"
        ec2_elbs: "{{ lb }}"
        state: absent
      with_items: instances
```
##### Expected Results:

```
TASK: [take the instances out of the load balancer] ***************************
ok: [localhost -> 127.0.0.1] => (item=i-123456ab)

PLAY RECAP ********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0
```
##### Actual Results:

```
TASK: [take the instances out of the load balancer] ***************************
changed: [localhost -> 127.0.0.1] => (item=i-123456ab)

PLAY RECAP ********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0
```
