### ISSUE TITLE
yum module cannot handle @Group in with_items

### ISSUE THREAD

**Issue by eparis** [ansible/ansible-modules-core#1409]
$ ansible --version
ansible 1.9.0.1
## Fails

``` yaml
- name: Install all my packages
  yum: name={{ item }} state=latest
  with_items:
        - '@Development Tools'
```
## Works

``` yaml
- name: Install all my packages
  yum: name='@Development Tools' state=lastest
```

**Comment by eparis** [comment]
```
TASK: [common | Install all my packages] ************************************** 
failed: [10.12.7.214] => (item=@Development Tools) => {"failed": true, "item": "@Development Tools"}
msg: this module requires key=value arguments (['name=@Development', 'Tools', 'state=latest'])

FATAL: all hosts have already failed -- aborting
```

**Comment by Jmainguy** [comment]
@eparis you got to qoute the qoutes basically

```
- name: Install rpms
  yum: name={{ item }} state=present
  with_items:
    - "'@Development Tools'"


TASK: [yum | Install rpms] **************************************************** 
ok: [centos5.soh.re] => (item='@Development Tools')
changed: [centos6.soh.re] => (item='@Development Tools')

PLAY RECAP ******************************************************************** 
centos5.soh.re             : ok=1    changed=0    unreachable=0    failed=0   
centos6.soh.re             : ok=1    changed=1    unreachable=0    failed=0  

```

**Comment by bcoca** [comment]
closing as this was a quoting issue not a support issue

**Comment by eparis** [comment]
I still think it's a bug, I explicitly entered a list where the items were clearly delineated and the parser screwed it up.  but I do have a workaround.

**Comment by akerekes** [comment]
Even if it is not a bug, the documentation should be updated as the examples there use only ```"``` to quote the name insted of ```"'```:
http://docs.ansible.com/ansible/yum_module.html#examples

**Comment by richard-scott** [comment]
Using the suggested quoting, this has just failed for me:

```
  - name: Install packages
    become: true
    yum: name={{ item }} state=latest
    with_items:
      - kernel-devel
      - "'@development tools'"

TASK [Install packages] ********************************************************
failed: [default] => (item=[u'kernel-devel', u"'@development tools'"]) => {"failed": true, "item": ["kernel-devel", "'@development tools'"], "msg": "Failure talking to yum: near \"@development\": syntax error"}
```

However, moving the quotes about fooled me into thinking it had worked:

```
  - name: Install packages
    become: true
    yum: name='{{ item }}' state=latest
    with_items:
      - kernel-devel
      - "@development tools"

TASK [Install packages] ********************************************************
ok: [default] => (item=[u'kernel-devel', u'@development tools'])

```

I say fooled, as the "development tools" group is still not not installed even tho Ansible didn't tell me the task had failed!

In the end I gave up with installing this via a with_items list and used this:

```
 - name: Install 'development tools' group of packages
    become: true
    yum: name='@development tools' state=installed
```

I also had to change state=latest" as this does not seem to work with yum groups. Once I change this to "state=installed" then the group installed just fine on its own. BTW, changing this to installed fixed Ansbile fooling me and installed the group via the with_items list way.

It could be worth updating the [documentation ](http://docs.ansible.com/ansible/yum_module.html) stating that package groups can't be installed with yum using the state=latest option.

I hope this helps someone else and doesn't cause them many hours of head banging like I have just endured.

**Comment by knirbhay** [comment]
Same here 

```
TASK [common : Install yum packages] *******************************************
failed: [localhost] (item=[u'python-lxml', u"'@Development tools'", u'openssl-devel', u'libffi', u'libffi-devel', u'python-devel', u'libxml2-devel', u'libxslt-devel']) => {"failed": true, "item": ["python-lxml", "'@Development tools'", "openssl-devel", "libffi", "libffi-devel", "python-devel", "libxml2-devel", "libxslt-devel"], "msg": "Failure talking to yum: near \"@Development\": syntax error"}
```

```
- name: Install yum packages
  yum: 
    name={{ item }}
    state=present
  with_items:
    - python-lxml
    - "'@Development tools'"
    - openssl-devel
    - libffi 
    - libffi-devel
    - python-devel
    - libxml2-devel
    - libxslt-devel
  tags: common
  when: ansible_os_family == "RedHat"
```

**Comment by richard-scott** [comment]
You need speech marks in the right places:

```
---
- hosts: localhost

  tasks:

    - name: Install yum packages
      yum:
        name="{{ item }}"
        state=present
      with_items:
      - "@Development tools"
```

**Comment by likan999** [comment]
I am seeing similar issue. It works if I specify state=present. However, if I use state=latest, yum doesn't install the package yet doesn't report failure, which is pretty misleading.

**Comment by geerlingguy** [comment]
Note that you can also bypass this issue without dealing with the quoting if you use the shorthand/machine name of the package set, e.g. `'@development'`; see, for example: https://github.com/geerlingguy/ansible-role-ruby/blob/master/tasks/install-from-source.yml#L5

**Comment by ericamador** [comment]
I am also seeing @likan999's observation (thanks BTW!) that specifying `state=latest`, like in the example below _does not_ work, while stating `state=present` does:

```
- name: Install desktop environment
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - "@basic-desktop"
    - "@desktop-platform"
    - "@x11"
    - "@fonts"
```
