### ISSUE TITLE
apt module upgrading "held" packages, even when using safe-upgrade.

### ISSUE THREAD

**Issue by bhcopeland** [ansible/ansible-modules-core#142]
Issue Type:

Originally posted on the Ansible Google groups page https://groups.google.com/forum/#!searchin/ansible-project/ben$20copeland/ansible-project/LYq9pIUhW2M/nNIqjOtUFT4J

Issue Type: Bug Report
Ansible Version: ansible 1.7.2
Environment: Running from Arch Linux 3.16.3-1-ARCH, deploying to Ubuntu 12.04 and 14.04 only.

Summary:

The default behaviour of "apt-get upgrade" is to not upgrade _held_ packages. Parameter "--ignore-hold" needs to be specified for the ability to upgrade held packages. Yet, ansible is upgrading _held_ packages, which in the case breaks openssh, as it needs to held back only on 12.04 for a feature we use.

Steps To Reproduce:

A basic playbook using the apt module using "safe-upgrade".

```
- name: hold openssh-client only if OS is 12.04
  shell: echo "openssh-client hold" | sudo dpkg --set-selections
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'precise'

- name: hold openssh-server only if OS is 12.04
  shell: echo "openssh-server hold" | sudo dpkg --set-selections
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'precise'

- name: update and upgrade a server
  apt: upgrade=safe update_cache=yes
  sudo: yes
```

Expected Results:

openssh should not have been updated.

The state of apt before ansible:

```
The following packages have been kept back:
linux-headers-generic linux-headers-virtual linux-image-virtual linux-virtual openssh-client openssh-server
```

Actual Results:

```
The following packages have been kept back:
linux-headers-generic linux-headers-virtual linux-image-virtual linux-virtual
```

openssh-client and openssh-server were upgraded, even know they were held.

**Comment by ansibot** [comment]
# Can You Help Us Out?

Thanks for filing a ticket! I am the friendly GitHub Ansibot. 

It looks like you might not have filled out the issue description based on our standard issue template.  You might not have known about that, and that's ok too, we'll tell you how to do it.

We have a standard template because Ansible is a really busy project and it helps to have some standard information in each ticket, and GitHub doesn't yet provide a standard facility to do this like some other bug trackers.  We hope you understand as this is really valuable to us!. 

Solving this is simple: please copy the contents of this [template](https://raw.githubusercontent.com/ansible/ansible/devel/ISSUE_TEMPLATE.md) and **paste it into the description** of your ticket.  That's it!

# If You Had A Question To Ask Instead

If you happened to have a "how do I do this in Ansible" type of question, that's probably more of a user-list question than a bug report, and you should probably ask this question on the project mailing list instead.  

However, if you think you have a bug, the report is the way to go!  We definitely want all the bugs filed :)  Just trying to help!

# About Priority Tags

Since you're here, we'll also share some useful information at this time.

In general tickets will be assigned a priority between P1 (highest) and P5, and then worked in priority order. We may also have some follow up questions along the way, so keeping up with follow up comments via GitHub notifications is a good idea.

Due to large interest in Ansible, humans may not comment on your ticket immediately.  

# Mailing Lists

If you have concerns or questions, you're welcome to stop by the ansible-project or ansible-development mailing lists, as appropriate.  Here are the links:
- https://groups.google.com/forum/#!forum/ansible-project - for discussion of bugs and how-to type questions
- https://groups.google.com/forum/#!forum/ansible-devel - for discussion on how to implement a code change, or feature brainstorming among developers

Thanks again for the interest in Ansible!

**Comment by alberto-re** [comment]
I think this is not strictly speaking an Ansible issue. The problem is that apt-get and aptitude seem to rely on different hold functions, thus "dpkg --set-selections" doesn't assure that aptitude (which is the command that performs the safe-upgrade) will not touch the held packages.

I believe the best solution is to pin the packages on both systems:

``` yaml
  - name: hold openssh-client only if OS is 12.04 (with dpkg)
    shell: echo "openssh-client hold" | sudo dpkg --set-selections
    when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'precise'
  - name: hold openssh-server only if OS is 12.04 (with dpkg)
    shell: echo "openssh-server hold" | sudo dpkg --set-selections
    when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'precise'
  - name: hold openssh-client only if OS is 12.04 (with aptitude)
    shell: aptitude hold openssh-client
    sudo: yes
    when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'precise'
  - name: hold openssh-server only if OS is 12.04 (with aptitude)
    shell: aptitude hold openssh-server
    sudo: yes
    when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'precise'
```
