### ISSUE TITLE
Unable to use env in docker module (v2.0.0)

### ISSUE THREAD

**Issue by jfindley** [ansible/ansible-modules-core#1421]
When using env in the docker module, I get the error:

`msg: argument env is of invalid type: <type 'dict'>, required: list`

The playbook looks like this:

```
- name: ecs-agent container
  sudo: yes
  docker:
    name: ecs-agent
    image: amazon/amazon-ecs-agent
    state: restarted
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /var/log/ecs/:/log
    - /var/lib/ecs/data:/data
    ports:
    - "51678:51678"
    env:
      ECS_LOGFILE: /log/ecs-agent.log
      ECS_LOGLEVEL: info
      ECS_DATADIR: /data
      ECS_CLUSTER: "{{ecs_cluster_name}}"
```

```
ansible --version
ansible 2.0.0 (devel 5f246dc1a6) last updated 2015/05/26 12:28:15 (GMT +100)
  lib/ansible/modules/core: (detached HEAD 32e609720a) last updated 2015/05/26 12:29:17 (GMT +100)
  lib/ansible/modules/extras: (detached HEAD 8dfa63d1d8) last updated 2015/05/26 12:29:17 (GMT +100)
  v2/ansible/modules/core: (detached HEAD 85c8a892c8) last updated 2015/05/21 17:30:11 (GMT +100)
  v2/ansible/modules/extras: (detached HEAD 70ea058563) last updated 2015/05/21 17:30:15 (GMT +100)
  configured module search path = None
```
