### ISSUE TITLE
[Feature] Docker module provide moar useful output

### ISSUE THREAD

**Issue by MrMMorris** [ansible/ansible-modules-core#1428]
**Issue Type:**
Feature Request

**Summary:**
Provide more info from docker module output such as IP/port 

**Steps to Reproduce:**

``` yaml
- docker:
    image: tianon/true
    count: 2
    ports:
      - "9090:9090"
  register: containers
```

**Expected Results:**

``` yaml
- debug: 
    var: containers
```

``` yaml
ok: [x.x.x.x] => {
  "var": {
      "containers": {
          "results": [
              {
                "ansible_facts": {
                  "docker_containers": [
                    {
                      "Id": "d2986cc8a7600ba43c4b62cd9dcc78096109ff95b6e6235953fa6de924",
                      "IPAddress": "172.17.0.2",
                      "Ports": {
                        "9090/tcp": [
                          {
                            "HostIp": "0.0.0.0",
                            "HostPort": "32768"
                          }
                      ],
                      "Warnings": null
...
```

**Actual Results:**

``` yaml
ok: [52.4.115.45] => {
    "var": {
        "csm_tv_client": {
            "changed": true,
            "msg": "All items completed",
            "results": [
                {
                    "ansible_facts": {
                        "docker_containers": [
                            {
                                "Id": "5715a0d2986dwa4b62cd9dcc78096109ff95b6e6235953fa6de924",
                                "Warnings": null
                            },
                            {
                                "Id": "dda3934awd910b6f898736feeb210e3eb879522fbf6b4468e0a07742fa",
                                "Warnings": null
                            }
                        ]
                    },
                    "changed": true,
                    "containers": [
                        {
                            "Id": "5715a0d2986cc8awdba43c4b62cd9dcc78096109ff95b6e6235953fa6de924",
                            "Warnings": null
                        },
                        {
                            "Id": "dda393472bf94edaw6f898736feeb210e3eb879522fbf6b4468e0a07742fa",
                            "Warnings": null
                        }
                    ],
                    "invocation": {
                        "module_args": "",
                        "module_name": "docker"
                    },
                    "item": "dev",
                    "msg": "started 2 containers, created 2 containers.",
                    "reload_reasons": null,
                    "summary": {
                        "created": 2,
                        "killed": 0,
                        "pulled": 0,
                        "removed": 0,
                        "restarted": 0,
                        "started": 2,
                        "stopped": 0
                    }
                }
            ]
        }
    }
}
```
