### ISSUE TITLE
Can't use strings in docker commands

### ISSUE THREAD

**Issue by MrMMorris** [ansible/ansible-modules-core#1470]
**Issue Type:**
Bug

**Ansible Version:**

```
ansible 2.0.0 (devel 388827a636) last updated 2015/05/28 10:25:04 (GMT -700)
  lib/ansible/modules/core: (detached HEAD 2b5e932cfb) last updated 2015/05/28 10:25:04 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD b2e4f31beb) last updated 2015/05/28 10:25:04 (GMT -700)
  v2/ansible/modules/core: (detached HEAD 85c8a892c8) last updated 2015/05/06 16:00:34 (GMT -700)
  v2/ansible/modules/extras: (detached HEAD 70ea058563) last updated 2015/05/06 16:00:34 (GMT -700)
```

**Summary:**
Docker module `command` option removes quotes

**Steps To Reproduce:**

``` yaml
- name: start monitoring-node container
  docker:
    name: monitoring-node
    image: prom/node-exporter
    command: >
      -collector.enabled='diskstats,filesystem,loadavg,meminfo,stat,textfile,time,netdev'
```

**Expected Results:**

``` json
"Cmd": [
            "-collector.enabled='diskstats,filesystem,loadavg,meminfo,stat,textfile,time,netdev'"
        ]
```

**Actual Results:**

``` json
"Cmd": [
            "-collector.enabled=diskstats,filesystem,loadavg,meminfo,stat,textfile,time,netdev"
        ]
```

See https://gist.github.com/MrMMorris/4851e54d763a88df22e3#comment-1467272 for possible fix

@smashwilson

**Comment by bcoca** [comment]
try quoting it, -  is a yaml reserved character that indicates the start of a list.

**Comment by MrMMorris** [comment]
@bcoca hmmm.. it seems to give me what I want according to `docker inspect`:

```
"Args": [
        "run",
        "-collector.enabled='diskstats,filesystem,loadavg,meminfo,stat,textfile,time,netdev'"
    ],
```

 but the container logs tell me `flag provided but not defined: -collector.enabled`...

Not sure if that's a node-exporter problem or not

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by MrMMorris** [comment]
@bcoca this is still an issue. Tried with a different Prometheus Exporter. Here's what happens:

```yaml
- name: start monitoring-mongo container
  docker:
    name: monitoring-mongo
    image: commonsense/mongodb-exporter:latest
    command: >
      "-mongodb.uri='mongodb://user:pass@csm-tv-mongo-1.node.consul/admin'"
    env:
      SERVICE_NAME: monitoring
      SERVICE_TAGS: mongo
    publish_all_ports: True
    restart_policy: always
```

`docker logs monitoring-mongo`
`Cannot connect to server using url: 'mongodb://user:pass@csm-tv-mongo-1.node.consul/admin'`

`docker inspect monitoring-mongo`
```
"Cmd": [
            "-mongodb.uri='mongodb://user:pass@csm-tv-mongo-1.node.consul/admin'"
        ],
```

I know it's not the image because:

`docker run -d commonsense/mongodb-exporter:latest -mongodb.uri='mongodb://user:pass@csm-tv-mongo-1.node.consul/admin'` works
