### ISSUE TITLE
Bug Report - can't loop in aync tasks

### ISSUE THREAD

**Issue by fdutheil** [ansible/ansible-modules-core#1474]
##### Issue Type: Bug Report

To me, it's not some corner use case or some tricky issue in twisting the tool to do something it is not supposed to do. So this issue is not rated "Feature Idea".
##### Ansible Version: 1.9.1

Control machine: Ubuntu 14.04
##### Ansible Configuration:

Basic with Pipelining, ssh ControlMaster enabled.
##### Environment:

Remote machines: Debian 7
##### Summary:

We have async tasks, and we have loops. We use each of them quite often. Why wouldn't one want to loop over an async taks? These basic features are not antagonist at all.
It is sooo needed for shell and command modules.
##### Steps To Reproduce:

Use an inventory like this:

```
[producers]
producer1

[brokers]
broker1
broker2
```

Use a playbook like this (isolated part, the problematic task):

```
- name: Simulate network load | Start IPerf client
  hosts: producers:brokers
  gather_facts: no
  tasks:
    - name: Producers | Run IPerf client
      command: "/usr/bin/screen -D -m  /usr/bin/iperf -c {{ item }} -p 10000 -P {{ producers_conc|default('1') }}"
      register: producers_sleeper
      with_items: groups['brokers']
      async: 12
      poll: 0
      when: inventory_hostname in groups['producers']

```
##### Expected Results:

Each machine in "producers" group will fire an iperf command towards each machine in the "brokers" group.
##### Actual Results:

Task ends up in error:

```
fatal: [producer1] => lookup plugins (with_*) cannot be used with async tasks
fatal: [broker1] => lookup plugins (with_*) cannot be used with async tasks
fatal: [broker2] => lookup plugins (with_*) cannot be used with async tasks

```

I've seen this (https://groups.google.com/forum/#!topic/ansible-devel/lhvukkszKUA) but I'm a bit shocked to discover the hard way that it's not possible to loop on async tasks. What would be the timeline on this feature?
