### ISSUE TITLE
Add ability to control systemd user instance services

### ISSUE THREAD

**Issue by firecat53** [ansible/ansible-modules-core#1479]
### Issue Type:

Feature Idea
### Ansible Version:

1.9.1
### Ansible Configuration:

N/A
### Environment:

Linux - (systemd)
### Summary:

It would be useful to be able to control systemd --user services from the
service module. I'm still researching how/if this can be done from the command
line...those aren't the easiest search terms to narrow down.
### Steps To Reproduce:

Possible usage:

```
service:
  name: syncthing
  user: firecat53
  state: restarted
```
### Expected Results:

N/A
### Actual Results:

N/A
