### ISSUE TITLE
ec2_metric_alarm shows changes every other run

### ISSUE THREAD

**Issue by jagibson** [ansible/ansible-modules-core#1527]
ansible 1.9.1
When I re-run ec2_metic_alarm, it seems that about every other run shows a change even though the data I'm feeding it is the same.  Ideally it would show no changes.

config:

``` yml
- name: autorecovery
  ec2_metric_alarm:
    alarm_actions: [
      "arn:aws:sns:{{ region }}:{{ aws_account_id }}:AutoRecoveryEvent",
      "arn:aws:automate:{{ region }}:ec2:recover"
    ]
    metric: "StatusCheckFailed_System"
    evaluation_periods: 2
    period: 60
    name: "Instance {{ item.tagged_instances.0.id }} AutoRecovery"
    state: present
    statistic: "Minimum"
    dimensions: {
      'InstanceId':"{{ item.tagged_instances.0.id }}"
    }
    description: 'Recover EC2 instance when health checks fail'
    comparison: ">"
    insufficient_data_actions: []
    region: "{{ region }}"
    threshold: 0.0
    namespace: "AWS/EC2"
    ok_actions: []
  with_items:
    - "{{ node_region_1.results }}"
```

node_region_1 is the register output from the ec2 module and can contain multiple hosts.
