### ISSUE TITLE
GCE Metadata field not usable

### ISSUE THREAD

**Issue by julianseeger** [ansible/ansible-modules-core#154]
When using the GCE Module, the metadata field is not usable or at least not like documented.
My Playbook looks like 

``` YAML
- name: Create a sandbox instance
  hosts: localhost
  tasks:
    - name: Launch instances
      local_action:
        module: gce
        instance_names: '{{names}}'
        machine_type: '{{machine_type}}'
        image: '{{image}}'
        zone: '{{zone}}'
        service_account_email: '{{ service_account_email }}'
        pem_file: '{{ pem_file }}'
        project_id: '{{ project_id }}'
        metadata: '{"db":"postgres"}'
      register: gce
```

But it fails with

```
msg: Unexpected error attempting to create instance moon, error: {'domain': 'global', 'message': "Required field 'value' not specified", 'reason': 'required'}
```

("moon" is the instance name).
I also tried {"key":"db","value":"postgres"} but it doesn't change anything.

Using the gcloud cli it works fine:

``` BASH
$ gcloud compute instances add-metadata moon --metadata testkey=testvalue
...
Updated [https://www.googleapis.com/compute/v1/projects/***/zones/europe-west1-a/instances/moon].
```

I also tried with

```
      local_action: gce instance_names={{names}} machine_type={{machine_type}}
                    image={{image}} zone={{zone}} service_account_email={{ service_account_email }}
                    pem_file={{ pem_file }} project_id={{ project_id }}
```

But same effect there.

I need the metadata field to add ssh-keys that will later allow ansible to connect and provision that instance. Any ideas?

> ansible 1.7.1
> libcloud 0.15.1

**_Edit to please the ansibot:**_
##### Issue Type:

Bug Report
##### Ansible Version:

1.7.1
##### Environment:

Ubuntu 14.04.1
##### Summary:

The Ansible GCE Module does not except the format of "metadata" that the google compute engine (or libcloud) needs .. just guessing the reason here..
##### Steps To Reproduce:

use a play like this

> - name: Create a sandbox instance
>   hosts: localhost
>   tasks:
>   - name: Launch instances
>     local_action:
>       module: gce
>       instance_names: '{{names}}'
>       machine_type: '{{machine_type}}'
>       image: '{{image}}'
>       zone: '{{zone}}'
>       service_account_email: '{{ service_account_email }}'
>       pem_file: '{{ pem_file }}'
>       project_id: '{{ project_id }}'
>       metadata: '{"db":"postgres"}'
>     register: gce

and fill in some values ... the only important thing seems to be gce + metadata
##### Expected Results:

An instance with the given metadata
##### Actual Results:

The exception quoted above

```
msg: Unexpected error attempting to create instance moon, error: {'domain': 'global', 'message': "Required field 'value' not specified", 'reason': 'required'}
```

**Comment by erjohnso** [comment]
@julianseeger - I just got bit by this too but haven't tracked it down. The GCE module hasn't specifically changed, so I suspect it's a new internal way of handling module options/params.  If you're OK with a quick hack, you can fix it by changing one line of code[1] in the GCE module.

Change from:

```
    md = literal_eval(metadata)
```

To:

```
    md = literal_eval(str(metadata))
```

FWIW, I submitted a PR for a new `metadata_from_file` option[2].  I'll update that PR to add the `str()` guard.

[1] https://github.com/ansible/ansible-modules-core/blob/devel/cloud/gce.py#L289
[2] https://github.com/ansible/ansible-modules-core/pull/114

**Comment by ansibot** [comment]
@erjohnso, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/jctanner/ansibullbot/blob/ISSUE_TRIAGE_CLASS/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@supertom, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@supertom, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@supertom, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by supertom** [comment]
The following snippet is valid and demonstrates the proper use of the metadata field.  This snippet is from the gce module documentation:

```
    gce:
      instance_names: my-test-instance
      zone: us-central1-a
      machine_type: n1-standard-1
      state: present
      metadata: '{"db":"postgres", "group":"qa", "id":500}'
      tags:
        - http-server
        - my-other-tag
      disks:
        - { 'name' : 'disk-2', 'mode': 'READ_WRITE' }
        - { 'name' : 'disk-3', 'mode': 'READ_ONLY' }
      disk_auto_delete: false
      network: foobar-network
      subnetwork: foobar-subnetwork-1
      preemptible: true
      ip_forward: true
      service_account_permissions:
        - storage-full
        - taskqueue
        - bigquery
      service_account_email: "your-sa@your-project-name.iam.gserviceaccount.com"
      credentials_file: "/path/to/your-key.json"
      project_id: "your-project-name"
```

@ryansb I recommend we close this ticket as this issue has been resolved.
