### ISSUE TITLE
EC2 Volume example doesn't work

### ISSUE THREAD

**Issue by hutchic** [ansible/ansible-modules-core#1551]
##### Issue Type:

Bug Report
##### Versions:

```
ansible 1.9.1
Python 2.7.9
boto 2.38.0
```
##### Ansible Configuration:

```
[defaults]
display_skipped_hosts = True
nocows = 1
remote_tmp = /tmp
```
##### Environment:

OSX 10.10.2
##### Summary:

The ansible ec2 volume example to create a volume with the given name if it doesn't exist or use an existing one if it already exists does not work
##### Steps To Reproduce:

Try the example:

```
- name: 'Sandbox'
  hosts: 'localhost'
  tasks:

  - name: ec2
    ec2:
      keypair: "ecs-key-pair"
      image: "ami-637b8c08"
      id: unique_name_doesnt_exist
      wait: yes
      count: 1
      instance_type: m3.medium
    register: ec2

  - name: ec2_vol
    ec2_vol:
      instance: "{{ item.id }}"
      name: unique_name_doesnt_exist
      device_name: /dev/xvdf
    with_items: ec2.instances
    register: ec2_vol
```
##### Expected Results:

It should create the volume successfully if the volume doesn't already exist
##### Actual Results:

It fails

```
msg: Could not find volume in zone (if specified): unique_name_doesnt_exist
```

Full sample can be found here: https://gist.github.com/hutchic/d75f67db22214fb22dfe
