### ISSUE TITLE
ec2_asg module doesn't delete the ASG when we do fire and forget

### ISSUE THREAD

**Issue by vanga** [ansible/ansible-modules-core#1571]
When I do fire and forget while deleting an ASG, it only updates the ASG parameters (min,max,desired) to zero, and does not delete the ASG.

https://github.com/ansible/ansible-modules-core/blob/devel/cloud/amazon/ec2_asg.py#L507-L515
Why not directly make the delete call? ASG does terminate the instances and deletes the group afaik.

```
- name: create Auto Scaling Group  
  local_action:
    module: ec2_asg
    name: "{{asg_name}}"
    load_balancers: "{{load_balancers | default(omit)}}"
    region: "{{region}}"
    availability_zones: '{{zone | default(omit)}}'
    launch_config_name: '{{launch_config_name}}'
    health_check_type: '{{health_check_type | default("EC2")}}'
    min_size: "{{min_size}}"
    max_size: "{{max_size}}"
    desired_capacity: "{{desired_capacity}}"
    replace_all_instances: "{{replace_all_instances | default('yes')}}"
    vpc_zone_identifier: "{{vpc_subnet_ids}}"
    tags:
      - deployment: "{{deployment | default('new')}}"
      - environment: "{{env | default('test')}}"
      - project: "{{tag_project}}"
      - customer: "{{tag_customer}}"
      - roleis: "{{tag_role}}"
      - Name: "{{tag_name}}"
        propagate_at_launch: yes
    state: "{{state}}"
    wait_timeout: 900
  async: 120
  poll: 0
```
