### ISSUE TITLE
Add recursive template copying

### ISSUE THREAD

**Issue by dellis23** [ansible/ansible-modules-core#159]
##### Issue Type:

"Feature Idea"
##### Ansible Version:

1.7.1
##### Environment:

Running on Mac OSX and managing Ubuntu 12.04
##### Summary:

This actually goes along with a couple of other issues we've had lately (and part of what I'm mentioning is related to https://github.com/ansible/ansible/pull/8533).  Our team has a setup that seems pretty basic, but is difficult to pull off in Ansible.  We have a number of files that we need copied, some of which are encrypted.  For instance:

```
/dir/
    /private/
        private_file_1
        private_file_2
        ...
        private_file_99
```

Ideally, we'd be able to just `copy` /dir/ and be done with it, but since we need them encrypted, they won't be copied over.  Unfortunately, copying encrypted files doesn't work, so we're forced to instead create template files for all of these, store the contents in variables, and encrypt those files.  Even more unfortunately, `template` isn't recursive, so we now have to duplicate a line for each of these files to copy them!

So what's ultimately started as a simple one line copy operation has now turned into dozens of additional copy incantations, another layer of indirection in the form of variables with encrypted content, and templates that do nothing but repeat the defined variables.  It's completely destroying our attempts to keep things not repeated.
##### Steps To Reproduce:

N/A
##### Expected Results:

N/A
##### Actual Results:

N/A

**Comment by damncabbage** [comment]
I threw together something for our own setup that might be helpful: https://gist.github.com/damncabbage/12af8915e12fbf71b897

The key bit that you might be missing is that instead of creating templates, you can use `content` from the Copy action:

``` yaml
- name: "Some Files"
  copy:
    dest: "/tmp/keys/{{ item }}.key"
    content: "{{ lookup('file', 'keys/' + item + '.key.enc') | decrypt_with(vaulted_key_password) }}"
  with_items:
  - "example_one"
  - "example_two"

# ...
# Note the "copy:" hash, instead of the usual Ansible key=value pairs.
# See https://github.com/ansible/ansible/issues/9067
```

(Alternatively, have a look at [DebOps](https://github.com/debops/debops/), in particular [debops.secret](https://github.com/debops/ansible-secret).)
