### ISSUE TITLE
authorized_key reports ok if no key is actually installed due to missing local key

### ISSUE THREAD

**Issue by donjohnson** [ansible/ansible-modules-core#1608]
Found this as I have my ssh config IdentityFile pointed to a different key filename (~/.ssh/id_rsa.$org.key).

If no ~/.ssh/id_rsa.pub exists, the module will report back that the operation succeeded, implying that the key was installed, when in fact no key was installed (nor was the ~/.ssh directory on the target created).

In my case, I solved this with a symlink, but I had to dig for a while to figure out what was going on.

**Comment by verm666** [comment]
Hi @donjohnson, can you provide information about Ansible version and your OS?

**Comment by verm666** [comment]
And can you provide playbook example. I'll try to repeat described behaviour by myself.

**Comment by donjohnson** [comment]
Ubuntu 12.04, Ansible 1.7.2.

The playbook is dead simple:

```
- hosts: world
  sudo: False
  vars:
    home: "{{lookup('env', 'HOME')}}"
    id_rsa_file: "{{home}}/.ssh/id_rsa.pub"
    key: "{{lookup('file', id_rsa_file)}}"
    user: "{{ lookup('env','USER') }}"
  tasks:
    - name: SSH | copy ssh public key to host
      authorized_key: user="{{user}}" key="{{key}}"
```

Steps to reproduce: run this playbook (with appropriate vars) with keys pointing to id_rsa pub/key files which do not exist--the authorize_key code should not notice this, and report success.
