### ISSUE TITLE
ansible unarchive dest must be an existing dir with csh on managed server

### ISSUE THREAD

**Issue by Fazik** [ansible/ansible-modules-core#1625]
Issue Type:

Bug Report

Ansible Version:

ansible 1.9.1

Environment:

Ansible running on FreeBSS 10.1
Managing FreeBSD 9-10.1
Summary:

When unarchive module  executing on FreeBSD with default root shell csh it fails with "msg: dest 'some_dest' must be an existing dir" even if such dir exist, if change shell to sh at managing server than everything works fine

Steps To Reproduce:

```
- name: test
  hosts: main1
  tasks:
   - name: create dir
     file: path=/usr/work/src/test state=directory                                  

   - name: extrac                               
     unarchive: src=/usr/work/src/archives/php-5.6.10.tar.bz2 dest=/usr/work/src/test copy=no
```

```
 ansible-playbook test2.yml
PLAY [test] ******************************************************************* 

GATHERING FACTS *************************************************************** 
ok: [main1]

TASK: [create dir] ************************************************************ 
changed: [main1]

TASK: [extract] ************************************************************** 
failed: [main1] => {"failed": true}
msg: dest '/usr/work/src/test' must be an existing dir

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/root/test2.retry

main1                      : ok=2    changed=1    unreachable=0    failed=1  
```

If we change on managed host shell to csh, then there will be no problem with extract:

```
ansible main1 -m command -a "chsh -s /bin/sh"
main1 | success | rc=0 >>
chsh: user information updated

 ansible-playbook test2.yml

PLAY [test] ******************************************************************* 

GATHERING FACTS *************************************************************** 
ok: [main1]

TASK: [create dir] **************************************************************
ok: [main1]

TASK: [extract] *****************************************************************
changed: [main1]

PLAY RECAP ******************************************************************** 
main1                      : ok=3    changed=1    unreachable=0    failed=0
```

Expected Results:

unpacked archive

Actual Results:

fail with "msg: dest '/usr/work/src/test' must be an existing dir" even if such dir exist"
