### ISSUE TITLE
pip module reports changed when installing from github

### ISSUE THREAD

**Issue by michaelrice** [ansible/ansible-modules-core#1645]
In [ansible/1705](https://github.com/ansible/ansible/issues/1705) this issue was reported to be fixed, but I am still having this on 1.9.2

I have the following:

``` yaml
- name: Install pypi-mirror from github
  sudo: yes 
  sudo_user: "{{pypi_user}}"
  pip: virtualenv=/home/{{pypi_user}}/venvs/pypi_server name="git+https://github.com/openstack-infra/pypi-mirror#egg=pypi-mirror-master"
```

No matter how many times I run this it reports "changed"
