### ISSUE TITLE
ec2_lc fails with TypeError: LaunchConfiguration:test-lc is not JSON serializable (devel branch)

### ISSUE THREAD

**Issue by joshm** [ansible/ansible-modules-core#1655]
Running a lc create as simple as:

```
- name: s launch configuration
  ec2_lc:
    name: test-lc
    instance_type: m3.medium
    region: us-west-2
    state: present
```

Returns:

`TASK [s_setup : s_setup : s launch configuration] *******************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: LaunchConfiguration:test-lc is not JSON serializable
fatal: [localhost]: FAILED! => {"invocation": {"module_name": "ec2_lc", "module_args": {"instance_type": "m3.medium", "region": "us-west-2", "name": "test-lc", "state": "present"}}, "failed": true, "changed": false, "parsed": false}`
