### ISSUE TITLE
apt: upgrade docs vs. code mismatch

### ISSUE THREAD

**Issue by egroeper** [ansible/ansible-modules-core#1667]
Issue Type:
“Bug Report”

Ansible Version:
ansible 1.9.2 (but looks the same in devel branch)

Environment:
Ubuntu 14.04

Summary:
Docs say upgrade="yes" is default, but it isn't:

```
    upgrade = dict(choices=['yes', 'safe', 'full', 'dist']),
```

Either docs or code should be fixed. Don't know which one is better. Perhaps quite a few people now depend on the current behaviour. So it could be better to fix the docs.

Steps To Reproduce:
In my playbook:

```
- hosts: all
  tasks:
  - apt:
      cache_valid_time: 3600
      update_cache: yes
  sudo: yes
```

Expected Results:
Since 'upgrade="yes"' is default, according to docs, `aptitude safe-upgrade` should be run, but isn't.

Actual Results:
No package upgrades.
