### ISSUE TITLE
Support systemd reenable

### ISSUE THREAD

**Issue by tetherit** [ansible/ansible-modules-core#1673]
I have this task:

``` yml
- template: 
    src: "init/timeagent.service.j2"
    dest: "/etc/systemd/system/timeagent.service"
- service: name=timeagent enabled=yes state=started
```

This works OK the first time, but if I edit the service file (particularly the [Install] section), ansible says "ok" but it actually does not enable the current/new service - it ignores it and keeps the old one :(

This leads to confusion and inconsistency. Right now I run "systemctl reenable timeagent" manually to actually enable the service after editing it. It would be great if Ansible's "service" module supported this (or even used it by default with systemd).
