### ISSUE TITLE
docker_module volumes fails

### ISSUE THREAD

**Issue by anthonygreen** [ansible/ansible-modules-core#1681]
#### Issue Type:

Bug Report
#### Component Name

_docker module
#### Ansible Version:

1.9.2
### Ansible Configuration

```
[defaults]
inventory = ./hosts
private_key_file = /Users/vagrant/.vagrant.d/insecure_private_key
remote_user = vagrant
host_key_checking = False
ask_sudo_pass: yes
```
#### Docker.py version

1.2.3
#### Environment

Running from: OS X 10.9.5
Managing: Ubuntu 15.04
#### Summary:

volumes in docker_module fails to bind to the correct path on host machine
#### Steps to reproduce

This playbook fails

```
- name: Create Jenkins data directory on host
  file: "path=/home/{{ansible_ssh_user}}/.jenkins state=directory mode=0777"

- name: Jenkins data directory
  docker: 
    name: jenkins_data 
    image: busybox
    state: present
    volumes: "/home/{{ansible_ssh_user}}/.jenkins:/var/jenkins_home"
  sudo: yes  

- name: Start Jenkins container
  docker: 
    name: jenkins_master
    image: mediaplayout/jenkins
    volumes_from: jenkins_data
    pull: always
    state: started
    ports: 
      - 8080:8080
      - 50000:50000
  sudo: yes  
```

whilst this playbook correctly attachs the volume at ~/.jenkins:

```
- name: Create Jenkins data directory on host
  file: "path=/home/{{ansible_ssh_user}}/.jenkins state=directory mode=0777"

- name: Jenkins data directory
  command: "docker create -v {{ansible_env.HOME}}/.jenkins:/var/jenkins_home --name jenkins_data busybox"
  sudo: yes

- name: Start Jenkins container
  docker: 
    name: jenkins_master
    image: mediaplayout/jenkins
    volumes_from: jenkins_data
    pull: always
    state: started
    ports: 
      - 8080:8080
      - 50000:50000
  sudo: yes  
```
#### Expected Results

```
ls /home/vagrant/.jenkins
```

should show the data volume of the Jenkins instance running within container
