### ISSUE TITLE
yum list and name parameters are mutually exclusive

### ISSUE THREAD

**Issue by ghost** [ansible/ansible-modules-core#1706]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.9.2
##### Ansible Configuration:

Default /etc/ansible/ansible.cfg
##### Environment:

RHEL 7.1 on EC2. RHEL-7.1_HVM_GA-20150225-x86_64-1-Hourly2-GP2 (ami-12663b7a) if it really matters.
##### Summary:

Using yum module to list specific named updates reports 'name' and 'list' are mutually exclusive parameters. This is not the case with the yum utility.
##### Steps To Reproduce:

```

---
- name: Local yum
  hosts: 127.0.0.1
  connection: local
  tasks:

  - name: yum list updates kernel.x86_64
    sudo: yes
    yum:
      name: kernel.x86_64
      list: updates
```
##### Expected Results:

Expected similar output to command line operation `yum list updates kernel.x86_64`. For example:

```
[awx@localhost]$ sudo yum list updates kernel.x86_64
Loaded plugins: product-id, subscription-manager
Updated Packages
kernel.x86_64                    3.10.0-229.7.2.el7                     rhui-REGION-rhel-server-releases
```
##### Actual Results:

```
TASK: [yum list updates kernel.x86_64] ****************************************
failed: [127.0.0.1] => {"failed": true}
msg: parameters are mutually exclusive: ['name', 'list']

FATAL: all hosts have already failed -- aborting
```
