### ISSUE TITLE
ec2_vpc report a changed on each run 

### ISSUE THREAD

**Issue by mogadanez** [ansible/ansible-modules-core#1717]
sample config

```
 ec2_vpc:
    state: present
    cidr_block: 172.30.0.0/16
    resource_tags: { "Environment":"Development" }
    subnets:
      - cidr: 172.30.1.0/24
        az: c
        resource_tags: { "Environment":"Dev", "Tier" : "Misc" }
      - cidr: 172.30.2.0/24
        az: a
        resource_tags: { "Environment":"Dev", "Tier" : "Main" }
      - cidr: 172.30.3.0/24
        az: b
        resource_tags: { "Environment":"Dev", "Tier" : "Reserve" }
    internet_gateway: True
    route_tables:
        - subnets:
          - 172.30.1.0/24
          - 172.30.2.0/24
          - 172.30.3.0/24
          routes:
            - dest: 0.0.0.0/0
              gw: igw
```

on each run it is report `changed=1`

**Comment by bcoca** [comment]
could this be a dupe of #122 ?

**Comment by mogadanez** [comment]
Looks like, in which version it was fixed?
I'm running 1.9.2

**Comment by ghost** [comment]
Got the same issue with similar configuration on 1.9.2.

**Comment by wyaeld** [comment]
@bcoca I'm still seeing this behaviour on 1.9.4.  Task as follows

``` yaml
- name: Create the VPC
  ec2_vpc:
    state: present
    region: "{{region}}"
    cidr_block: "{{cidr_block}}"
    resource_tags: { Name: "vpc-{{vpc_name}}", Environment: "{{environment}}" }
    subnets:
      - cidr: "{{cidr_subnet_1}}"
        az: "{{zone_1}}"
        resource_tags: { Name: "subnet-{{vpc_name}}-web-2a", Environment: "{{environment}}", Tier: "app" }
      - cidr: "{{cidr_subnet_2}}"
        az: "{{zone_2}}"
        resource_tags: { Name: "subnet-{{vpc_name}}-web-2b", Environment: "{{environment}}", Tier: "app" }
      - cidr: "{{cidr_subnet_3}}"
        az: "{{zone_1}}"
        resource_tags: { Name: "subnet-{{vpc_name}}-db-2a", Environment: "{{environment}}", Tier: "db" }
      - cidr: "{{cidr_subnet_4}}"
        az: "{{zone_2}}"
        resource_tags: { Name: "subnet-{{vpc_name}}-db-2b", Environment: "{{environment}}", Tier: "db" }
    internet_gateway: True
    route_tables:
      - subnets:
          - "{{cidr_subnet_1}}"
          - "{{cidr_subnet_2}}"
          - "{{cidr_subnet_3}}"
          - "{{cidr_subnet_4}}"
        routes:
          - dest: 0.0.0.0/0
            gw: igw
  register: vpc
```

resulting in

```
changed: [localhost] => {"changed": true, ....}
```
