### ISSUE TITLE
File/directory mode must be string

### ISSUE THREAD

**Issue by bkeroackdsc** [ansible/ansible-modules-core#1735]
##### ISSUE TYPE

Bug Report
##### COMPONENT NAME

file
##### ANSIBLE VERSION

N/A
##### SUMMARY

In the following example task, directory permissions will be incorrectly set:

``` yaml
- name: Create example directory
  file:
    state: directory
    path: /opt/example
    owner: root
    group: root
    mode: 0755
  sudo: yes
```

After executing the playbook, the actual permissions will be (as reported by `stat`):

```
Access: (1130/d--x-wx—T)
```

The issue is that when using the syntax above, you must explictly pass the mode as a string:

``` yaml
...
mode: "0755"
...
```

At the very least this should be called out in the documentation. Better behavior would be for Ansible to display a warning during the run ("WARNING: integer passed as file/directory mode!"). Ideally Ansible should error out completely if the intended behavior is to never allow integer mode arguments.
