### ISSUE TITLE
aws_key not honoring --check

### ISSUE THREAD

**Issue by dexa187** [ansible/ansible-modules-core#1739]
The aws_key module is not honoring --check flag.

In my play I have:

```
- name: Remove aws keys
  local_action: ec2_key name=infra_{{ stack }} region={{ ec2_region }} state=absent
  ignore_errors: yes
  tags:
```

When I run the play with --check the key is actually being deleted!
