### ISSUE TITLE
Container-Update if image has changed

### ISSUE THREAD

**Issue by jarmoni** [ansible/ansible-modules-core#1785]
My playbook looks something like this:

```

---
- name: run xyz
  hosts: docker
  tasks:
  - name: start container
    docker:
      docker_api_version: 1.19
      docker_url: tcp://my_host:2375
      restart_policy: always
      image: my_image:1
      name: my_container
      state: restarted
      pull: always
      state: restarted
```

The above example works, after execution the container _my_container_ based on _my_image:1_ is running.
Now I'd like to change the image-tag (e.g. _my_image:2_ or _my_image:0_) and execute ansible again:

I would expect, that my container will be rebuilt based on the new image (e.g. _my_image:2_) and started afterwards. But this is not the case. Neither 'pull: always' nor change of state can change this behaviour. I have to remove the container by hand, run ansible again and at the end of the day the container fullfils the declaration in the playbook (automation at it's best ;-) )

I would expect that ansible does **not** only check the container-name but also the image-name. How should I perform upgrades (and sometimes downgrades) if the presence of a container with a specific name is enough?
