### ISSUE TITLE
ec2_lc spot_price not working

### ISSUE THREAD

**Issue by garlandkr** [ansible/ansible-modules-core#1787]
Issue type: Bug report
Ansible version: stable-1.9
Ansible configuration: NA
Environment: NA
Summary: When creating a launch configuration with spot_price set the launch configuration is created but it does not have a spot price.

Task portion:

``` yaml
- ec2_lc:
    name: somename
    image_id: "{{ lc_ami_id | default(ami_image) }}"
    key_name: removed
    security_group: removed
    instance_type: m3.medium
    instance_profile_name: removed
    ebs_optimized: false
    instance_monitoring: true
    assign_public_ip: true
    spot_price: "{{ ec2_spot_prices.m3.medium }}"
```

Variables:

``` yaml
# EC2 Spot price index
ec2_spot_prices:
  m3:
    2xlarge: 0.532
    large: 0.133
    xlarge: 0.266
    medium: 0.067
```
