### ISSUE TITLE
file mode is wrong set on certain yaml format styling

### ISSUE THREAD

**Issue by therealmarv** [ansible/ansible-modules-core#1798]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.9.2
##### Ansible Configuration:

Nothing changed in Ansible configuration.
##### Environment:

Host OS: OS X 10.10.4

Node OS: Ubuntu 14.04 LTS
##### Summary:

mode parameter is wrong set when using a certain yaml format style.
##### Steps To Reproduce:

I made a repo where you can start up a Vagrant VM which shows the reproducable output: https://github.com/therealmarv/ansible-mode-bug

Main problem is [in this role](https://github.com/therealmarv/ansible-mode-bug/blob/master/roles/copy_mode_test/tasks/main.yml) in the **first task** which has only a different "yaml-fomat-styling". At the end all dummy files should have the same mode setting:

```

---
- name: copy a file with mode, test 1, bug here
  copy:
    src: dummyfile
    dest: /tmp/dummy1
    mode: 755

- name: copy a file with mode, test2
  copy:
    src: dummyfile
    dest: /tmp/dummy2
    mode: 0755

- name: copy a file with mode, test 3
  copy:
    src: dummyfile
    dest: /tmp/dummy3
    mode: "755"

- name: copy a file with mode, test 4
  copy:
    src: dummyfile
    dest: /tmp/dummy4
    mode: "0755"

- name: copy a file with mode, test 5
  copy: src=dummyfile dest=/tmp/dummy5 mode=755

- name: copy a file with mode, test 6
  copy: src=dummyfile dest=/tmp/dummy6 mode=0755

- name: copy a file with mode, test 7
  copy: src=dummyfile dest=/tmp/dummy7 mode="755"

- name: copy a file with mode, test 8
  copy: src=dummyfile dest=/tmp/dummy8 mode="0755"
```
##### Expected Results:

All files should have mode `755` or `-rwxr-xr-x`
##### Actual Results:

The yaml-format-styling of the first file will let Ansible make a wrong mode setting:  
`362` or `--wxrw--wt`

Screen output of `ls -all` command:  
![image](https://cloud.githubusercontent.com/assets/1050582/8882226/9e519490-3245-11e5-90f9-3e599ff8a540.png)

and also with ls command which [shows the mode numerically](http://stackoverflow.com/a/1796009/756056):  
![image](https://cloud.githubusercontent.com/assets/1050582/8882246/c7a2931c-3245-11e5-9cfc-057d54286313.png)
