### ISSUE TITLE
docker_api_version not published to get_differing_containers

### ISSUE THREAD

**Issue by jarmoni** [ansible/ansible-modules-core#1828]
Because of #1158 and #1766 I have switched to ansible's develop branch. Both issues disappeard but another one occured:

```
 - name: install docker-registry
    docker:
      docker_api_version: "1.19"
      docker_url: "tcp://192.169.91.100:2375"
      name: registry
      image: registry:2
      restart_policy: always
      state: reloaded
      volumes:
      - /volumes/registry:/var/lib/registry
      - /etc/localtime:/etc/localtime:ro
      ports:
      - 0.0.0.0:5000:5000
```

state=reloaded triggers a call of 'get_differing_containers' and there the variable 'docker_api_version' is undefined:

```
TASK [install docker-registry] **************************************************
fatal: [devdocker1]: FAILED! => {"changed": false, "failed": true, "msg": "BECOME-SUCCESS-zavjakzbuzsrxpeustpzfsfmejvnmidj\r\nTraceback (most recent call last):\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1438113744.06-142230277179787/docker\", line 3425, in <module>\r\n    main()\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1438113744.06-142230277179787/docker\", line 1703, in main\r\n    reloaded(manager, containers, count, name)\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1438113744.06-142230277179787/docker\", line 1568, in reloaded\r\n    for container in manager.get_differing_containers():\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1438113744.06-142230277179787/docker\", line 1039, in get_differing_containers\r\n    if docker_api_version >= 1.19:\r\nNameError: global name 'docker_api_version' is not defined\r\n", "parsed": false}
```

Maybe this problem is caused by docker-py (I use 1.2.3 because of https://github.com/ansible/ansible-modules-core/issues/1707).

When if fixed docker.py like this (just a quick hack)

```
 #For v1.19 API and above use HostConfig, otherwise use Config

            docker_api_version = 1.19

            if docker_api_version >= 1.19:
                actual_mem = container['HostConfig']['Memory']
            else:
                actual_mem = container['Config']['Memory']
```

everything works fine

The problem only occurs when I invoke my playbook and the container already exists.
