### ISSUE TITLE
docker-module does not work with tls-enabled

### ISSUE THREAD

**Issue by jarmoni** [ansible/ansible-modules-core#1838]
I use a self signed certificate, docker-daemon is properly configured, when I execute docker-commands from the command-line, everything works fine.
- I'm running the devel-Branch (ansible and ansible-modules-core
- docker-version is 1.7.1 (API-version 1.19)
- Issue occurs with docker-py  v1.3.1 and v1.2.3 as well
- environment variable ${DOCKER_CERT_PATH} is set

```
- hosts: hosts
  tasks:
  - name: install docker-registry
    docker:
      docker_api_version: "1.19"
      docker_url: "tcp://{{inventory_hostname}}:2376"
      name: registry
      image: registry:2
      restart_policy: always
      state: reloaded
      use_tls: "verify"
      volumes:
      - /volumes/registry:/var/lib/registry
      - /etc/localtime:/etc/localtime:ro
      ports:
      - 0.0.0.0:5000:5000
```

results in:

```
fatal: [devdocker1]: FAILED! => {"changed": false, "failed": true, "msg": "SSLError(SSLError(SSLError(1, '_ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed'),),)"}
```

when I set *use_tls: "encrypt" I get:

```
fatal: [devdocker1]: FAILED! => {"changed": false, "failed": true, "msg": "SSLError(SSLError(SSLError(1, '_ssl.c:510: error:14094412:SSL routines:SSL3_READ_BYTES:sslv3 alert bad certificate'),),)"}
```

when I set _tls_ca_cert_, _tls_client_cert_ and _tls_client_key_ explicit (either with _use_tls: verify_ or _use_tls: encrypt_ I receive:

```
fatal: [devdocker1]: FAILED! => {"changed": false, "failed": true, "msg": "BECOME-SUCCESS-mcmhixmneemjuvplykneygttkgbqapwr\r\nTraceback (most recent call last):\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1438202239.97-81917707480990/docker\", line 3428, in <module>\r\n    main()\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1438202239.97-81917707480990/docker\", line 1673, in main\r\n    manager = DockerManager(module)\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1438202239.97-81917707480990/docker\", line 706, in __init__\r\n    tls_config = docker.tls.TLSConfig(**params)\r\n  File \"/usr/local/lib/python2.7/dist-packages/docker/tls.py\", line 46, in __init__\r\n    'Path to a certificate and key files must be provided'\r\ndocker.errors.TLSParameterError: Path to a certificate and key files must be provided through the client_config param. TLS configurations should map the Docker CLI client configurations. See http://docs.docker.com/examples/https/ for API details.\r\n", "parsed": false
```
