### ISSUE TITLE
ec2_vpc module ignoring aws profile name

### ISSUE THREAD

**Issue by tusharm** [ansible/ansible-modules-core#1852]
- OS: OSX 10.10.2
- Ansible: 1.9.1 (using brew)
- boto: 2.38.0

```

---
- name: create vpc
  ec2_vpc:
    cidr_block: "{{ aws.vpc.cidr }}"
    profile: my-profile
    region:  "{{ aws.region }}"
    resource_tags: ...
    subnets:
      - cidr: "{{ aws.vpc.subnets[0].cidr }}"
        az: "{{ aws.vpc.subnets[0].az }}
        resource_tags: ...
```

```
TASK: [network | create vpc] **************************************************
<localhost> REMOTE_MODULE ec2_vpc region=ap-southeast-2 cidr_block=10.0.0.0/24 profile=my-profile
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1438470713.2-165236904662012 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1438470713.2-165236904662012 && echo $HOME/.ansible/tmp/ansible-tmp-1438470713.2-165236904662012']
<localhost> PUT /var/folders/_g/dr_vp3lx07db_tljn5b76d0w0000gp/T/tmpvL4NL1 TO /Users/*****/.ansible/tmp/ansible-tmp-1438470713.2-165236904662012/ec2_vpc
<localhost> EXEC ['/bin/sh', '-c', u'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /Users/*****/.ansible/tmp/ansible-tmp-1438470713.2-165236904662012/ec2_vpc; rm -rf /Users/*****/.ansible/tmp/ansible-tmp-1438470713.2-165236904662012/ >/dev/null 2>&1']
ok: [localhost] => {"changed": false, "subnets": [{"az": "ap-southeast-2a", "cidr": "x.x.x.x/x", "id": "subnet-xxxxxxxx", "resource_tags": {}}], "vpc": {"cidr_block": "10.0.0.0/24", "dhcp_options_id": "dopt-xxxxxxx", "id": "vpc-cf1cbbaa", "region": "ap-southeast-2", "state": "available"}, "vpc_id": "vpc-cf1cbbaa"}

```

I can't find this VPC using the profile I specified:

```
$ aws --region ap-southeast-2 --profile my-profile  ec2 describe-vpcs --vpc-id vpc-cf1cbbaa

A client error (InvalidVpcID.NotFound) occurred when calling the DescribeVpcs operation: The vpc ID 'vpc-cf1cbbaa' does not exist
```

However, the VPC is created in the account associated with my `default` profile:

```
$ aws --region ap-southeast-2 ec2 describe-vpcs --vpc-id vpc-cf1cbbaa
{
    "Vpcs": [
        {
            "VpcId": "vpc-cf1cbbaa",
            "State": "available",
            ....
        }
    ]
}
```

Related #1701?
