### ISSUE TITLE
os_floating_ip errors if an ip is attached.

### ISSUE THREAD

**Issue by mcameron** [ansible/ansible-modules-core#1858]
##### Issue Type:

Regression (so inevitably a feature idea).
##### Ansible Version:

ansible 2.0.0
##### Ansible Configuration:

```
< lookup_plugins = ./lookup_plugins:~/.ansible/plugins/lookup_plugins/:/usr/share/ansible_plugins/
< timeout = 120

---
> timeout = 10
```
##### Environment:

OSX -> Ubuntu
##### Summary:

If you add an ip with os_floating_ip to a server, when you rerun your play, it errors.
##### Steps To Reproduce:

```
- os_floating_ip:
    cloud: envvars
    state: present
    reuse: yes
    server: cwp-goserver-1
    network: vlan3320
    fixed_address: "{{ lookup('os_private_ip', 'cwp-goserver-1') }}"
    wait: true
    timeout: 180
```
##### Expected Results:

If the server already has a floating ip from the network, expect the task to pass, as unchanged.
##### Actual Results:

```
unable to bind a floating ip to server f23ce73c-82ad-490a-bf0e-7e3d23dce449: Cannot associate floating IP 10.12.71.112 (57a5b6e0-2843-4ec5-9388-408a098cdcc7) with port f2c6e8bb-b500-4ea0-abc8-980b34fc200f using fixed IP 192.168.101.36, as that fixed IP already has a floating IP on external network 8b3e1a76-f16c-461b-a5b5-f5987936426d
```
