### ISSUE TITLE
Docker module throws error when container state=absent

### ISSUE THREAD

**Issue by jarmoni** [ansible/ansible-modules-core#1863]
I want to remove a container setting its state to absent:

```
- name: purge {{current_container}}
  docker:
    docker_api_version: "{{docker_api_version}}"
    docker_url: "{{docker_url}}"
    use_tls: verify
    tls_ca_cert: "{{docker_tls_ca_cert}}"
    tls_client_cert: "{{docker_tls_client_cert}}"
    tls_client_key: "{{docker_tls_client_key}}"
    state: "absent"
    image: "{{registry_url}}/{{db_image}}:{{db_version}}"
    name: "{{current_container}}"
  when: purge_containers_on_redeploy == true
```

This works - the container will be removed during ansible-run.
But unfortunately the operation is considered "FAILED" due to the following error

```
"Docker API Error: no such id: f044faed41f02d7dc311569080a9a4c9d03b58b00ff06eaaa51054611d4701c1"
```

(The reported container-id is the id the container had before getting purged)

The cause of this problem seems to be the following call:

```
containers.notice_changed(containers.deployed)
```

when commenting this line, the message disappears. I assume that all 'changed' containers are inspected in a subsequent step and there the container is expected to be present....
