### ISSUE TITLE
os_subnet does not support not having a Gateway IP

### ISSUE THREAD

**Issue by pwnall** [ansible/ansible-modules-core#1880]
##### Issue Type:
- Bug Report
##### Ansible Version:

2.0.0
##### Ansible Configuration:

Valid clouds.yml
##### Environment:

N/A
##### Summary:

The [os_subnet module](https://github.com/ansible/ansible-modules-core/blob/devel/cloud/openstack/os_subnet.py) does not support creating / updating a neutron subnet without any gateway IP. This feature is necessary for creating a network that does not route to the outside world.
##### Steps To Reproduce:

```

---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: create internal network
      os_network:
        name: "test-private"
        admin_state_up: yes
        shared: no
        cloud: "test"

    - name: add subnet to internal network
      os_subnet:
        name: "test-private-net"
        network_name: "test-private"
        cidr: "10.60.0.0/16"
        enable_dhcp: yes
        gateway_ip: null
        cloud: "test"
```
##### Expected Results:

I'd expect to be able to set some value for `gateway_ip` that results in the equivalent of `--no-gateway-ip`
in the [neutron CLI](http://docs.openstack.org/cli-reference/content/neutronclient_commands.html#neutronclient_subcommand_subnet-create). I check this by inspecting the created network in the Horizon UI and checking that the `Gateway IP` heading shows a dash `-`
##### Actual Results:

Currently, all I can do is leave out `gateway_ip` completely, which sets the gateway IP to the first valid IP in the subnet. I think that the underlying issue is that shade doesn't support `--no-gateway-ip`. I filed a bug for that issue.
https://github.com/openstack-infra/shade/blob/master/shade/__init__.py#L2719
https://storyboard.openstack.org/#!/story/2000328
