### ISSUE TITLE
lineinfile module incorrectly converts Tab characters to '\t' in files

### ISSUE THREAD

**Issue by drybjed** [ansible/ansible-modules-core#1892]
##### Issue Type:

Bug Report
##### Ansible Version:

Ansible devel
##### Ansible Configuration:

Stock `ansible.cfg`
##### Environment:

Debian, Ubuntu
##### Summary:

Tab characters are not expanded correctly in `lineinfile` module `line=` parameter (they work as expected in current 1.9.2 stable Ansible). This results in `lineinfile` module not finding the correct line using `regexp=` parameter and adding the line multiple times, with `\t` character in place of Tabs.
##### Steps To Reproduce:

```

---
- hosts: all
  tasks:

    - name: Make sure test file exists
      file:
        dest: '/tmp/lineinfile-test'
        state: 'touch'
      changed_when: False

    - name: Add a line with Tabs
      lineinfile:
        dest: '/tmp/lineinfile-test'
        regexp: '^First\s'
        line: 'First\tSecond\tThird'
        state: 'present'

    - name: Ensure line with Tabs is present
      lineinfile:
        dest: '/tmp/lineinfile-test'
        regexp: '^First\s'
        line: 'First\tSecond\tThird'
        state: 'present'
```
##### Expected Results:

Playbook run the first time:

```
PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [Make sure test file exists] ******************************************** 
ok: [localhost]

TASK: [Add a line with Tabs] ************************************************** 
changed: [localhost]

TASK: [Ensure line with Tabs is present] ************************************** 
ok: [localhost]
```

Playbook run the second time:

```
PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [Make sure test file exists] ******************************************** 
ok: [localhost]

TASK: [Add a line with Tabs] ************************************************** 
ok: [localhost]

TASK: [Ensure line with Tabs is present] ************************************** 
ok: [localhost]
```

Result (Tabs convered to Spaces by GitHub interface):

```
First   Second  Third
```
##### Actual Results:

Playbook run the first time:

```
PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Make sure test file exists] **********************************************
ok: [localhost]

TASK [Add a line with Tabs] ****************************************************
changed: [localhost]

TASK [Ensure line with Tabs is present] ****************************************
changed: [localhost]
```

Playbook run the second time:

```
PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Make sure test file exists] **********************************************
ok: [localhost]

TASK [Add a line with Tabs] ****************************************************
changed: [localhost]

TASK [Ensure line with Tabs is present] ****************************************
changed: [localhost]
```

Result:

```
First\tSecond\tThird
First\tSecond\tThird
First\tSecond\tThird
First\tSecond\tThird
```

**Comment by chrrrles** [comment]
Ahh - this is because YAML requires escape strings to be enclosed by double-quotes.

The playbook below (using double-quotes) operates as expected.

``` yaml
---
- hosts: all
  tasks:

    - name: Make sure test file exists
      file:
        dest: '/tmp/lineinfile-test'
        state: 'touch'
      changed_when: False

    - name: Add a line with Tabs
      lineinfile:
        dest: '/tmp/lineinfile-test'
        regexp: '^First\s'
        line: "First\tSecond\tThird"
        state: 'present'

    - name: Ensure line with Tabs is present
      lineinfile:
        dest: '/tmp/lineinfile-test'
        regexp: '^First\s'
        line: "First\tSecond\tThird"
        state: 'present'
```
