### ISSUE TITLE
os_server: 'shade is required' error even though its installed

### ISSUE THREAD

**Issue by aaron-trout** [ansible/ansible-modules-core#1910]
Hi,

I'm trying to use os_server to deploy an instance. I am running ansible on Mac OS X 10.10 with Python 2.7.9, ansible from devel branch source, in a virtualenv. I have run `pip install shade` but I still get the following error:

``` bash
 __________________________________
< TASK [Deploy openstack instance] >
 ----------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||


fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "shade is required for this module"}
```

Here is my playbook file:

``` yaml

---
- hosts: localhost
  tasks:
    - name: Deploy openstack instance
      os_server:
        flavor: m1.small
        floating_ip_pools:
          - floating
        image: trusty-20150803
        key_name: mac-main
        name: test
        nics:
          - net-id: 3d245513-3f4d-4931-a1e2-fb614973c440
        security_groups:
          - default
          - ssh
        state: present
```
