### ISSUE TITLE
git:// URLs require accept_hostkey: yes

### ISSUE THREAD

**Issue by ktdreyer** [ansible/ansible-modules-core#1931]
#### Issue Type

Bug Report
#### Ansible Version

ansible 1.9.2
#### Ansible Configuration

standard
#### Environment

Running ansible on Fedora 22 (and my remote host is RHEL 7)
#### Summary

When using the git module to clone from a `git://` URL, I have to set `accept_hostkey: yes`. This doesn't make sense because the git:// protocol doesn't use hostkeys; only SSH does.
#### Steps To Reproduce:

```
- name: clone my-git-repo.git
  git:
    dest: /etc/my-git-repo
    repo: "git://git.example.com/my-git-repo.git"
    update: no
    version: mybranch
```
#### Expected Results:

The git module clones the repository as expected, and `accept_hostkey: yes` is not necessary.
#### Actual Results:

Without any `accept_hostkey:` setting:

```
failed: [puddle.example.com] => {"failed": true}
msg: git.example.com has an unknown hostkey. Set accept_hostkey to True or manually add the hostkey prior to running the git module
```

... and once I add `accept_hostkey: yes`, Ansible runs successfully
