### ISSUE TITLE
os_server: Error fetching server list: Cloud  does not have a compute service

### ISSUE THREAD

**Issue by rosconap** [ansible/ansible-modules-core#2008]
**Issue Type:**

Bug Report

**Ansible Version:**

ansible --version
ansible 2.0.0
  config file = /home/myname/.ansible.cfg
  configured module search path = None

**Ansible Configuration:**

Whatever is provided by "source ./hacking/env-setup"

**Environment:**

Ansible is run on: Ubuntu 12.04.5 LTS \n / 3.2.0-58-generic #88-Ubuntu SMP

**Summary:**

```
ansible-playbook -i inventory boot-os-server.yml

PLAY [launch a compute instance] ***********************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [launch an instance] ******************************************************
fatal: [localhost]: FAILED! => {"changed": false, "extra_data": null, "failed": true, "msg": 
"Error fetching server list: Cloud  does not have a compute service"}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1
```

**Steps To Reproduce:**

Run this playbook:

```
- name: launch a compute instance
  hosts: localhost
  connection: local
  tasks:
    - name: launch an instance
      os_server:
        state: present
        auth:
          auth_url: https://url/v2.0/
          username: username
          password: password
          project_name: project_name
        name: newVM
        region_name: region_name
        availability_zone: region_name
        image: image
        key_name: key-key
        timeout: 200
        flavor: 1
```

Could it be that this openstack setup does not advertise the service catalog correctly?
