### ISSUE TITLE
RFE: iam_policy support for jinja templates for policy_document parameter

### ISSUE THREAD

**Issue by jxn** [ansible/ansible-modules-core#2009]
##### Issue Type:
- Feature Idea
##### Summary:

A good use-case for iam_policy module is to create roles with commonly used policies.  If the policy_document parameter supported templates, this could be much more useful.

For example, a playbook:

``` yaml
vars:
  aws_resource: arn::s3::somebucket/*
tasks:
  - iam_policy: policy_document=somepolicy.json.j2 iam_type=group state=present name=somepolicy
```

With a template somepolicy.json.j2:

``` jinja
{
    ...
    'policy': {
       resource: "{{ aws_resouce }}"
    }
}
```

The resource could be swapped out by variable and reused for many playbooks.

**Comment by wimnat** [comment]
Why don't you use jinja to template?

```
iam_policy:
  policy_json: " {{ lookup( 'template', 'somepolicy.json.j2') }} "
  ...
```

**Comment by ejoubaud** [comment]
@winmat: For some reason that doesn't work for me (see #2687), does it for you?

**Comment by timnee** [comment]
I'm getting the same error `The policy is not in the valid JSON format.` when using file lookup

Task example

```
- name: Create Admin Group
  iam_policy:
    iam_name: Admins
    iam_type: group
    state: present
    policy_name: AdministratorAccess
    policy_json: " {{ lookup( 'file', 'AdministratorAccess.policy') }} "
```

AdminstratorAccess.policy

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "*",
      "Resource": "*"
    }
  ]
}
```

I get the following error

```
fatal: [127.0.0.1]: FAILED! => {"changed": true, "failed": true, "invocation": {"module_args": {"aws_access_key": null, "aws_secret_key": null, "ec2_url": null, "iam_name": "Admins", "iam_type": "group", "policy_document": null, "policy_json": " {\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [\n    {\n      \"Effect\": \"Allow\",\n      \"Action\": \"*\",\n      \"Resource\": \"*\"\n    }\n  ]\n} ", "policy_name": "AdministratorAccess", "profile": "test", "region": "us-east-1", "security_token": null, "skip_duplicates": true, "state": "present", "validate_certs": true}, "module_name": "iam_policy"}, "msg": "The policy is not in the valid JSON format."}
```
