### ISSUE TITLE
azure required for this module

### ISSUE THREAD

**Issue by matiasdecarli** [ansible/ansible-modules-core#2014]
Running the azure default example, im getting stuck at this message error

```
PLAY [all] ********************************************************************

GATHERING FACTS ***************************************************************
ok: [127.0.0.1]

TASK: [azure] *****************************************************************
failed: [127.0.0.1 -> 127.0.0.1] => {"failed": true, "parsed": false}
failed=True msg='azure required for this module'


FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/matias/azure.retry

127.0.0.1                  : ok=1    changed=0    unreachable=0    failed=1
```

This is my playbook

``` html

---
- hosts: all
  connection: local
  tasks:
   - local_action:
      module: azure      
      name: "ansible-vm"
      os_type: linux
      subscription_id: "subscription_id"
      role_size: Small
      image: 'b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_04_3-LTS-amd64-server-20150805-en-us-30GB'
      location: 'East US'
      password: "password"
      storage_account: storage-acc
      user: user
      wait: yes
```

Any idea why? Am I missing something? Thanks in advance

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

In any case, the message mans you need to install the python 'azure' module on which the ansible azure plugin depends on.

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by matiasdecarli** [comment]
Ok, I got this working thanks to @tgerla 

Basically the azure python module 1.0.1 has some updates that broke the integration. Specifically [this](https://github.com/Azure/azure-sdk-for-python/blob/fa3119c497e98343c7f789e07d108d1d2d457bd2/ChangeLog.txt#L47)

The solution was to use the version 0.11.1 of the azure lib

**Comment by CorbanR** [comment]
So this may actually be an issue @bcoca 

I have run `sudo pip install azure` to install the module 

`pip list`

```
azure (1.0.1)
azure-common (1.0.0)
azure-mgmt (0.20.0)
azure-mgmt-common (0.20.0)
azure-mgmt-compute (0.20.0)
azure-mgmt-network (0.20.0)
azure-mgmt-nspkg (1.0.0)
azure-mgmt-resource (0.20.0)
azure-mgmt-storage (0.20.0)
azure-nspkg (1.0.0)
azure-servicebus (0.20.1)
azure-servicemanagement-legacy (0.20.1)
azure-storage (0.20.1)
```

playbook

```
---
- hosts: localhost
  connection: local
  gather_facts: yes

  tasks:
   - local_action:
      module: azure
      name: slkjdkfjlkdjflkjlkjjkkk
      role_size: Small
      image: b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_04_3-LTS-amd64-server-20150908-en-us-30GB
      location: 'East US'
      user: ubuntu
      ssh_cert_path: ~/.ssh/id_rsa.pub
      management_cert_path: ~/.ssh/azure/myCert.pem
      storage_account: testing
      wait: yes
```

I get the following error 

```
failed: [127.0.0.1 -> 127.0.0.1] => {"failed": true, "parsed": false}
failed=True msg='azure required for this module'


FATAL: all hosts have already failed -- aborting
```

When downgrading azure to `0.7.1` I'm able to use the Ansible module (albeit It's failing because I am using a self signed crt, and the azure module does not have the option to turn of crt validation.)
