### ISSUE TITLE
lineinfile doesn't respect sudo:yes?

### ISSUE THREAD

**Issue by astrostl** [ansible/ansible-modules-core#2017]
Howdy,

ansible 1.5.4 on Ubuntu 14.04

Playbook:

```

---
- hosts: "{{ hosts }}"
  sudo: yes
  tasks:
  - name: add root key to authorized_keys file
    lineinfile: dest=/root/.ssh/authorized_keys regexp=foo03$ line="ssh-rsa fhdjksahfsd foo03"
```

CLI:

```
ansible-playbook -u me -U me -kK -e hosts=myhosts  rootkey.yml
```

This reported that the /root/.ssh/authorized_keys file didn't exist. I tried adding `create=yes`, which confirmed that it was a permission issue - that errors out with a permission denied on /root/.ssh.

Are core modules supposed to use sudo when "sudo: yes" is set? It doesn't look like lineinfile does.

Thanks!
