### ISSUE TITLE
ec2_vpc not all resource_tags are supported

### ISSUE THREAD

**Issue by CumpsD** [ansible/ansible-modules-core#2018]
##### Issue Type:
- Bug Report
##### Ansible Version:
- `ansible 1.9.2`
##### Ansible Configuration:
- Clean Installation
##### Environment:
- Running: CentOS 7
- Managing: Amazon AWS
##### Summary:

The `ec2_vpc` module provides `resource_tags` settings for various vpc settings, but some are missing (route tables, internet gateway, network acl, default security group)
##### Steps To Reproduce:

Currently `resource_tags` are available for:
- vpc itself
- subnets
- route tables

When creating a full blown VPC using this module:
- an internet gateway can be toggled as well (`yes/no`), however it is not possible to give it `resource_tags` to provide it a name.
- a default network ACL is created, which cannot be given a name due to missing `resource_tags` possibility
- a default security group is created, which cannot be given a name due to missing `resource_tags` possibility

This is the playbook used according to the `Ansible for AWS` book, with all possible resource tags:

```

---
- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    vpc_name: test
    region: eu-central-1

    cidr: 10.2.0.0/16
    app_cidr: 10.2.1.0/24

    az1: eu-central-1a
    az1_suffix: 1a
    db_cidr1: 10.2.11.0/24

    az2: eu-central-1b
    az2_suffix: 1b
    db_cidr2: 10.2.12.0/24

  tasks:
    - name: create vpc
      local_action:
        module: ec2_vpc
        state: present
        region: "{{ region }}"
        cidr_block: "{{ cidr }}"
        dns_hostnames: no
        dns_support: yes
        resource_tags: '{ "Name": "{{ vpc_name }}" }'
        internet_gateway: yes

        subnets:
          - cidr: "{{ app_cidr }}"
            az: "{{ az1 }}"
            resource_tags: '{ "Name": "{{ vpc_name }}-app-{{ az1_suffix }}" }'

          - cidr: "{{ db_cidr1 }}"
            az: "{{ az1 }}"
            resource_tags: '{ "Name": "{{ vpc_name }}-db-{{ az1_suffix }}" }'

          - cidr: "{{ db_cidr2 }}"
            az: "{{ az2 }}"
            resource_tags: '{ "Name": "{{ vpc_name }}-db-{{ az2_suffix }}" }'

        route_tables:
          - subnets:
              - "{{ app_cidr }}"
            routes:
              - dest: 0.0.0.0/0
                gw: igw
            resource_tags: '{ "Name": "{{ vpc_name }}-app" }'

          - subnets:
              - "{{ db_cidr1 }}"
              - "{{ db_cidr2 }}"
            routes:
              - dest: 0.0.0.0/0
                gw: igw
            resource_tags: '{ "Name": "{{ vpc_name }}-db" }'

      register: vpc

    - name: write region to {{ vpc_name }}_vpc_info file
      sudo: yes
      local_action: shell echo "region"":" "{{ region }}" > "{{ vpc_name }}"_vpc_info

    - name: write vpc name to {{ vpc_name }}_vpc_info file
      sudo: yes
      local_action: shell echo "vpc_name"":" "{{ vpc_name }}" >> "{{ vpc_name }}"_vpc_info

    - name: write vpc id to {{ vpc_name }}_vpc_info file
      sudo: yes
      local_action: shell echo "vpc_id"":" "{{ vpc.vpc_id }}" >> "{{ vpc_name }}"_vpc_info

    - name: write subnets id to {{ vpc_name }}_vpc_info file
      sudo: yes
      local_action: shell echo "{{ item.resource_tags.Name }}"":" "{{ item.id }}" >> "{{ vpc_name }}"_vpc_info
      with_items: vpc.subnets
```
##### Expected Results:

A VPC should be created with tags for:
- VPC itself
- Subnets
- Route tables
- Internet Gateway
- Default network ACL
- Default security group
##### Actual Results:

A VPC is created with tags for:
- VPC itself
- Subnet tags

The tags for the Route Tables apparently didn't get applied. For the rest, there is no way to set the tags.
