### ISSUE TITLE
{get,create}_host_config consolidation breaks syslog logging for me

### ISSUE THREAD

**Issue by waisbrot** [ansible/ansible-modules-core#2019]
After pulling in #2011, I have this ansible-playbook version:

```
ansible-playbook 2.0.0 (devel b2cb3153f1) last updated 2015/09/03 19:50:36 (GMT -400)
  lib/ansible/modules/core: (devel a4149a37ba) last updated 2015/09/04 15:46:58 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD b8803306d1) last updated 2015/09/03 19:50:40 (GMT -400)
  config file = /Users/waisbrot/git/docker-scripts/ansible/ansible.cfg
  configured module search path = None
```

When I try to create a docker container with the options 

```
- name: metrics downsample worker
  when: version_metrics_downsample_worker is defined
  docker:
    name: metrics-downsample-worker
    image: docker.whoop.com/whoop/metrics-downsample-worker:{{version_metrics_downsample_worker}}
    registry: docker.whoop.com
    state: reloaded
    pull: always
    publish_all_ports: yes
    log_driver: syslog
    env:
      SNITCH_URL: "{{snitches[ec2_tag_Name+'-metrics-downsample-worker']['check_in_url']}}"
      AWS_SQS_QUEUE_NAME: "{{env_prefix|default('')}}metrics-to-downsample"
      AWS_SQS_HOST: "sqs.{{region}}.amazonaws.com"
      PGHOST: "{{pg_host}}"
      PGUSER: "{{pg_user}}"
      PGDATABASE: "{{pg_database}}"
      PGPASSWORD: "{{pg_password}}"
      AWS_KINESIS_TARGET_STREAM: "{{env_prefix}}metric-upload-summaries"
      AWS_KINESIS_HOST: "kinesis.{{region}}.amazonaws.com"
```

Then I get an error 

```
failed: [52.27.1.20] => (item={u'key': 2, u'value': {u'version_metrics_downloader': u'master', u'image_metrics_uploader': u'metrics-uploader', u'migrate': 1, u'version_nginx': u'master', u'version_api_server': u'master', u'version_analytics': u'master', u'version_metrics_uploader': u'master', u'version_image_uploader': u'master'}}) => {"changed": true, "failed": true, "item": {"key": 2, "value": {"image_metrics_uploader": "metrics-uploader", "migrate": 1, "version_analytics": "master", "version_api_server": "master", "version_image_uploader": "master", "version_metrics_downloader": "master", "version_metrics_uploader": "master", "version_nginx": "master"}}, "msg": "Docker API Error: Cannot start container 5b14ae0967fda32d22c315246ab77657074b3816b1f75ef33711c5d70439f3f3: Failed to initialize logging driver: Unix syslog delivery error"}
```

Pre-PR #2011, the syslog driver works for me and I have these versions:

```
ansible-playbook 2.0.0 (devel b2cb3153f1) last updated 2015/09/03 19:50:36 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 8f31323b5c) last updated 2015/09/04 16:23:39 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD b8803306d1) last updated 2015/09/03 19:50:40 (GMT -400)
  config file = /Users/waisbrot/git/docker-scripts/ansible/ansible.cfg
  configured module search path = None
```

On the target system, I have 
`Docker version 1.7.1, build 786b29d` 
and 
`Name: docker-py
Version: 1.3.1
Location: /usr/local/lib/python2.6/site-packages
Requires: requests, six, websocket-client`

**Comment by abadger** [comment]
Been unable to reproduce thus far.  here's the playbook I tried:

```
---
- hosts: 192.168.122.241
  tasks:
    - docker:
        name: busybox-test
        image: "busybox:latest"
        state: reloaded
        command: sleep 60
        pull: always
        publish_all_ports: yes
        log_driver: syslog
        insecure_registry: True
        use_tls: "no"
        env:
          SNITCH_URL: "one"
          AWS_SQS_QUEUE_NAME: "two"
          AWS_SQS_HOST: "three"
          PGHOST: "four"
          PGUSER: "five"
          PGDATABASE: "six"
          PGPASSWORD: "seven"
          AWS_KINESIS_TARGET_STREAM: "eight"
          AWS_KINESIS_HOST: "nine"

```

I'm running on fedora 21 to fedora 22.

I'm wondering, it seems like a big coincidence that you updated and then this stopped working but perhaps there's something wrong with syslog on the system.  When I google for the "Unix syslog delivery error" message I get a bunch of hits like this: http://stackoverflow.com/questions/30028007/docker-error-when-using-log-driver-syslog-on-os-x  where syslogd is not running on the target system for some reason.

Are you able to try running the docker command line client with --log-driver syslog to rule out that this something outside of ansible?
