### ISSUE TITLE
file module fails to set correct permissions

### ISSUE THREAD

**Issue by anthonygreen** [ansible/ansible-modules-core#2025]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.9.2
##### Environment:

Running from OS X 10.9.5 
Provisioning Ubuntu 15.04
##### Summary:

file module fails to set correct permissions on a directory
##### Steps To Reproduce:

```
- file: 
    path: "/home/jenkins/.jenkins"
    owner: jenkins
    group: admin
    mode: 0775
    state: directory
    recurse: yes
```

creates permission:

```
drwxr-xr-x
```

instead of 

```
drwxrwxr-x
```

same thing happens if you split the ownership assignment and rights into two separate tasks
