### ISSUE TITLE
pip module always reports changed in --check mode

### ISSUE THREAD

**Issue by mgedmin** [ansible/ansible-modules-core#2030]
**Issue Type**: Bug
**Ansible Version**: 1.9.2
**Environment**: Ubuntu
**Summary**

When I define a task like this

``` yaml
- name: repozo
  pip: name=ZODB virtualenv=/apps/zopes/repozo state=present
```

I can run `ansible-playbook foo.yml` and it reports `ok`, but if I run `ansible-playbook -C foo.yml`, it always reports `changed`.

**Steps To Reproduce**

``` yaml
# test.yml
- hosts: localhost
  gather_facts: no
  tasks:
    - name: virtualenv
      pip: name=check-manifest state=present virtualenv=/tmp/venv
```

Run three commands

```
ansible-playbook test.yml
ansible-playbook test.yml
ansible-playbook test.yml -C
```

The first command reports `localhost                  : ok=1    changed=1    unreachable=0    failed=0`
The second command reports `localhost                  : ok=1    changed=0    unreachable=0    failed=0`

**Expected results**

The third command reports `localhost                  : ok=1    changed=0    unreachable=0    failed=0`

**Actual results**

The third command reports `localhost                  : ok=1    changed=1    unreachable=0    failed=0`

**Comment by bcoca** [comment]
have you tested against current devel?
is it an issue only with virtual env?

**Comment by mgedmin** [comment]
I cannot reproduce with current devel, specifically

```
ansible 2.0.0 (devel 8a7a37b535) last updated 2015/09/08 08:09:55 (GMT +300)
  lib/ansible/modules/core: (detached HEAD 34655e8e29) last updated 2015/09/07 09:38:42 (GMT +300)
  lib/ansible/modules/extras: (detached HEAD 6a3cf63351) last updated 2015/09/07 09:38:42 (GMT +300)
  config file = /etc/ansible/ansible.cfg
  configured module search path = /usr/share/ansible
```

**Comment by mgedmin** [comment]
This seems to be fixed in 1.9.3.

**Comment by jmehnle** [comment]
I'm still seeing this in 1.9.4. Still have to try 2.0.

**Comment by allanlewis** [comment]
I'm seeing this with both 1.9.4 and 2.0.0.2. My task looks something like this:

``` yml
- name: Install 'pip' packages
  become: yes
  become_user: "{{ pip_user|default('foo') }}"
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    extra_args: "--user"
  with_items:
    - { name: mock, version: 1.3.0 }
    - { name: pytest, version: 2.8.0 }
```

These packages have already been installed for user 'foo' (`pip_user` isn't defined for the host in question) but check mode always reports changed in both 1.9.4 and 2.0.0.2.
