### ISSUE TITLE
ec2_elb_lb should allow creation of LBCookieStickinessPolicyType with no expiration

### ISSUE THREAD

**Issue by Yanchek99** [ansible/ansible-modules-core#2039]
This is related to the work done by @haad in #1190 

Amazon and Boto both allow for the creation of a LBCookieStickinessPolicyType that has no expiration time set. However the ec2_elb_lb module requires expiration to be set for type loadbalancer.

Desired Config Example:

```
  ec2_elb_lb:
    name: "example-lb"
    state: present
    region: "us-west-2"
    security_group_ids: "a384j874"
    listeners: 
      - protocol: http
        load_balancer_port: 80
        instance_port: 80
    health_check: 
        ping_protocol: http 
        ping_port: 80
        ping_path: "/ping.php"
        response_timeout: 5
        interval: 30 
        unhealthy_threshold: 2
        healthy_threshold: 2
    scheme: "internet-facing"
    cross_az_load_balancing: yes
    stickiness: 
        type: loadbalancer
        enabled: yes
  register: elb
```
