### ISSUE TITLE
EBS volume_type ignored

### ISSUE THREAD

**Issue by jfindley** [ansible/ansible-modules-core#2040]
## Issue type

Bug report
## Summary

When creating an ec2 volume, volume_type is ignored.

The config:

``` yaml
volumes:
  device_name: /dev/sdb
        volume_size: 100
        volume_type: gp2
```

creates a volume using standard disks, not gp2.

The config:

``` yaml
volumes:
  device_name: /dev/sdb
        volume_size: 100
        volume_type: io1
        iops: 150
```

produces an error message: "Instance creation failed => InvalidParameterCombination: The parameter iops is not supported for standard volumes."
## Ansible version:

```
ansible --version
ansible 2.0.0 (detached HEAD 43cc27084d) last updated 2015/08/13 15:18:18 (GMT +100)
  lib/ansible/modules/core: (devel 1c7e8ef1a0) last updated 2015/09/09 17:21:32 (GMT +100)
  lib/ansible/modules/extras: (detached HEAD ff2386faf4) last updated 2015/07/21 18:18:28 (GMT +100)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/07/21 18:18:36 (GMT +100)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/07/21 18:18:40 (GMT +100)
  config file = /etc/ansible/ansible.cfg
  configured module search path = None
```
## Environment/config:

OSX source install.  Default config.
