### ISSUE TITLE
lineinfile not insertafter 'EOF' if line presents in file

### ISSUE THREAD

**Issue by nghnam** [ansible/ansible-modules-core#2054]
**Issue Type: Bug Report**

**Ansible Version: 1.9.3**

**Ansible Configuration: default**

**Environment: Ubuntu 14.04**

**Summary:**

`lineinfile` won't insert line after EOF if line has presented in file. 

**Steps To Reproduce:**

An example ansible task:

```
- name: test insertafter EOF
  lineinfile:
    dest: /tmp/test.txt
    line: "{{ item.line }}"
    insertafter: 'EOF'
    state: present
  with_items: 
    - { line: Hello Ansible }
```

My /tmp/test.txt:

```
Hello Ansible
=============
```

**Expected Results:**

```
Hello Ansible
=============
Hello Ansible
```

**Actual Results:**

```
TASK: [test insertafter EOF] ************************************************** 
ok: [localhost] => (item={'line': 'Hello Ansible'}) => {"backup": "", "changed": false, "item": {"line": "Hello Ansible"}, "msg": ""}

PLAY RECAP ******************************************************************** 
localhost                  : ok=1    changed=0    unreachable=0    failed=0 
```

And /tmp/test.txt not changed.

In lineinfile.py,
https://github.com/ansible/ansible-modules-core/blob/devel/files/lineinfile.py#L233

The condition  `if index[0] != -1:` checked regexp matched a line in file, but it did not check regexp is defined or not. 
I changed this line into `if index[0] != -1 and regexp is not None:` and re-executed the playbook.  It worked as expected.
