### ISSUE TITLE
[ Docker module ] Add "creates" parameter.

### ISSUE THREAD

**Issue by monokal** [ansible/ansible-modules-core#2092]
Some people use Docker containers on-the-fly to do things such as compile binaries as seen in my example below. What would be nice is to have the "creates" parameter available to allow for the same functionality as seen in the command module. In the below example, the desired behaviour would be to skip the task if the binary already exists.

``` yaml
- name: compile_flannel_binary
  when: clone_flannel_source|success
  docker:
    name:           compile-flannel-binary
    image:          google/golang
    command:        "/bin/bash -c 'cd /opt/flannel/repo && ./build'"
    detach:         False
    state:          "{{ item }}"
    pull:           missing
    restart_policy: "no"
    net:            bridge
    volumes:
        - "/opt/flannel/repo:/opt/flannel/repo"
    creates: "/opt/flannel/repo/bin/flanneld"                  # <<< Add this?
  with_items:
    - "started" # Start the container, generate the binary,
    - "absent"  # then clean up.
  register: compile_flannel_binary
```

Perhaps in the bigger picture "creates" could be a super-parameter like "when"? Anyway, I'm happy to have a crack at implementing this for the Docker module assuming feedback is positive.
