### ISSUE TITLE
service enable=yes always reports "changed: yes" with systemd and LSB scripts

### ISSUE THREAD

**Issue by murphi** [ansible/ansible-modules-core#2095]
**Ansible version:** 1.9.3
**Distributions:**
- Host running ansible: Archlinux
- Host configured by ansible: Debian Jessie

The host to be configured runs Debian Jessie with systemd 215.
Services that provide native *.service files for systemd are handled correct. (e.g. cron)
Services that provide a LSB init script (in /etc/init.d/) are always reported as changed (e.g. ntp)
## Steps to reproduce

**Playbook**

``` YAML

---
- hosts: ansible-test
  remote_user: vagrant
  sudo: yes
  tasks:
    - apt: name=ntp state=latest
    - service: name=ntp enabled=yes
    - apt: name=cron state=latest
    - service: name=cron enabled=yes
```

On executing this playbook twice enabling ntp always reports changed=yes
**Vagrantfile**

``` Ruby
Vagrant.configure(2) do |config|
  config.vm.box = "debian/jessie64"
  config.vm.hostname = "ansible-test"
  config.vm.define "ansible-test" do |host|
  end
  config.vm.network "public_network", bridge: "eth0"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "test.yml"
  end
end
```
## Manual check

```
ansible ansible-test -u vagrant -b -m service -a "name=ntp enabled=yes"
```
## Expected result

``` YAML
ansible-test | success >> {
    "changed": false,
    "enabled": true,
    "name": "cron"
}
```
## Current result

``` YAML
ansible-test | success >> {
    "changed": true,
    "enabled": true,
    "name": "cron"
}
```

```
```
