### ISSUE TITLE
Copy module still copies files to '/' directory instead of specified destination - the 'with_nested' edition

### ISSUE THREAD

**Issue by drybjed** [ansible/ansible-modules-core#2098]
##### Issue Type:

Bug Report, might be related to https://github.com/ansible/ansible-modules-core/issues/1705
##### Ansible Version:

Current Ansible devel (3db8070aa36db3ecd927b1f2cfe8ff680f7a105d)
##### Ansible Configuration:

Default `ansible.cfg`
##### Environment:

Debian, Ubuntu
##### Summary:

Copy module tries to copy files in `/` instead of the specified destination, when file locations are passed with `with_nested`.
##### Steps To Reproduce:

```

---

- name: Prepare test environment
  hosts: localhost

  vars:
    base: '/tmp/files'

    realms:
      - source: 'one'

    dirs: [ 'alpha', 'beta', 'gamma' ]
    file_contents: 'File contents'

  tasks:

    - name: Create directories
      file:
        path: '{{ base + "/" + item.0.source + "/" + item.1 }}'
        state: 'directory'
      with_nested:
        - realms
        - dirs

    - name: Create test files
      copy:
        content: '{{ file_contents }}'
        dest: '{{ base + "/" + item.0.source + "/" + item.1 + "/test-file" }}'
      with_nested:
        - realms
        - dirs

    - name: Create tmp files
      copy:
        content: '{{ file_contents }}'
        dest: '{{ base + "/" + item.0.source + "/" + item.1 + "/tmp" }}'
      with_nested:
        - realms
        - dirs

- name: Execute the test
  hosts: all
  sudo: True

  vars:

    base_local: '/tmp/files'
    base_remote: '/tmp'

    realms:
      - source: 'one'
        dest: 'one'

    dirs: [ 'alpha', 'beta', 'gamma' ]

  tasks:

    - name: Create directories
      file:
        name: '{{ base_remote + "/" + item.0.dest + "/" + item.1 }}'
        state: 'directory'
      with_nested:
        - realms
        - dirs

    - name: Copy files (this task errors out)
      copy:
        src: '{{ base_local + "/" + item.0.source + "/" + item.1 + "/" }}'
        dest: '{{ base_remote + "/" + item.0.dest + "/" + item.1 + "/" }}'
      with_nested:
        - realms
        - dirs
```
##### Expected Results:

This is how the tasks play out on Ansible 1.9.3:

```
PLAY [Prepare test environment] *********************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [Create directories] **************************************************** 
changed: [localhost] => (item=[{'source': 'one'}, 'alpha'])
changed: [localhost] => (item=[{'source': 'one'}, 'beta'])
changed: [localhost] => (item=[{'source': 'one'}, 'gamma'])

TASK: [Create test files] ***************************************************** 
changed: [localhost] => (item=[{'source': 'one'}, 'alpha'])
changed: [localhost] => (item=[{'source': 'one'}, 'beta'])
changed: [localhost] => (item=[{'source': 'one'}, 'gamma'])

TASK: [Create tmp files] ****************************************************** 
changed: [localhost] => (item=[{'source': 'one'}, 'alpha'])
changed: [localhost] => (item=[{'source': 'one'}, 'beta'])
changed: [localhost] => (item=[{'source': 'one'}, 'gamma'])

PLAY [Execute the test] ******************************************************* 

GATHERING FACTS *************************************************************** 
ok: [remote]

TASK: [Create directories] **************************************************** 
changed: [remote] => (item=[{'dest': 'one', 'source': 'one'}, 'alpha'])
changed: [remote] => (item=[{'dest': 'one', 'source': 'one'}, 'beta'])
changed: [remote] => (item=[{'dest': 'one', 'source': 'one'}, 'gamma'])

TASK: [Copy files] ************************************************************ 
changed: [remote] => (item=[{'dest': 'one', 'source': 'one'}, 'alpha'])
changed: [remote] => (item=[{'dest': 'one', 'source': 'one'}, 'beta'])
changed: [remote] => (item=[{'dest': 'one', 'source': 'one'}, 'gamma'])

PLAY RECAP ******************************************************************** 
Create tmp files -------------------------------------------------------- 4.25s
Copy files -------------------------------------------------------------- 2.22s
Create directories ------------------------------------------------------ 0.85s
Create test files ------------------------------------------------------- 0.22s
remote                     : ok=3    changed=2    unreachable=0    failed=0   
localhost                  : ok=4    changed=3    unreachable=0    failed=0  
```

On repeated runs all tasks return OK status.
##### Actual Results:

This is how above playbook runs on Ansible v2:

```
PLAY [Prepare test environment] ************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Create directories] ******************************************************
changed: [localhost] => (item=[{u'source': u'one'}, u'alpha'])
changed: [localhost] => (item=[{u'source': u'one'}, u'beta'])
changed: [localhost] => (item=[{u'source': u'one'}, u'gamma'])

TASK [Create test files] *******************************************************
changed: [localhost] => (item=[{u'source': u'one'}, u'alpha'])
changed: [localhost] => (item=[{u'source': u'one'}, u'beta'])
changed: [localhost] => (item=[{u'source': u'one'}, u'gamma'])

TASK [Create tmp files] ********************************************************
changed: [localhost] => (item=[{u'source': u'one'}, u'alpha'])
changed: [localhost] => (item=[{u'source': u'one'}, u'beta'])
changed: [localhost] => (item=[{u'source': u'one'}, u'gamma'])

PLAY [Execute the test] ********************************************************

TASK [setup] *******************************************************************
ok: [remote]

TASK [Create directories] ******************************************************
changed: [remote] => (item=[{u'dest': u'one', u'source': u'one'}, u'alpha'])
changed: [remote] => (item=[{u'dest': u'one', u'source': u'one'}, u'beta'])
changed: [remote] => (item=[{u'dest': u'one', u'source': u'one'}, u'gamma'])

TASK [Copy files] **************************************************************
failed: [remote] => (item=[{u'dest': u'one', u'source': u'one'}, u'alpha']) => {"checksum": "3b4cbfba4b75ef05d6972a57a0a35c9ab56ff6e9", "failed": true, "item": [{"dest": "one", "source": "one"}, "alpha"], "msg": "attempted to take checksum of directory: /tmp"}
failed: [remote] => (item=[{u'dest': u'one', u'source': u'one'}, u'beta']) => {"checksum": "3b4cbfba4b75ef05d6972a57a0a35c9ab56ff6e9", "failed": true, "item": [{"dest": "one", "source": "one"}, "beta"], "msg": "attempted to take checksum of directory: /tmp"}
failed: [remote] => (item=[{u'dest': u'one', u'source': u'one'}, u'gamma']) => {"checksum": "3b4cbfba4b75ef05d6972a57a0a35c9ab56ff6e9", "failed": true, "item": [{"dest": "one", "source": "one"}, "gamma"], "msg": "attempted to take checksum of directory: /tmp"}

PLAY RECAP *********************************************************************
karma                      : ok=2    changed=1    unreachable=0    failed=1   
localhost                  : ok=4    changed=3    unreachable=0    failed=0
```

On remote host you can notice that `/test-file` has been created in the `/` directory.
