### ISSUE TITLE
OpenStack os_image is_public flag does not make image public in Glance

### ISSUE THREAD

**Issue by vivobg** [ansible/ansible-modules-core#2100]
##### ISSUE TYPE

Bug Report
##### COMPONENT NAME

os_image
##### ANSIBLE VERSION

2.0
##### SUMMARY

I have the following task in an Ansible playbook, using Ansible 2.0:

``` yaml
- name: Push base image to glance
      os_image:
       auth:
          auth_url: *
          username: admin
          password: *
          project_name: admin
       name: centos-6
       container_format: bare
       disk_format: qcow2
       state: present
       filename: centos-6.qcow2
       is_public: yes
```

The image is successfully pushed to Glance, however it is not made public. I have to manually edit the image in Horizon, or use glance cli to make it public.
