### ISSUE TITLE
ec2_elb only looks at first 400 ELBs

### ISSUE THREAD

**Issue by chrisweaver** [ansible/ansible-modules-core#2115]
**Issue Type: Bug Report**

**Ansible Version**: Ansible 1.9.3
**Boto Version**: 2.38.0
**Python Version**: 2.7.5
**Environment**: server OSX Mavericks, destination RHEL 6.6

**Summary**:
The ec2_elb module uses the Boto call "get_all_load_balancers" to dump all ELBs in an account.  However it only looks at the first 400 ELBs.

I verified this by adding debugging to the module to see what it gets back from the Boto call, and it is always exactly 400 ELBs.  However I can see all of our ELBs (currently at 488) when I use the AWS CLI or GUI.

The problem is the ec2_elb module does not make use of the "marker" that the Boto call returns if there are more than 400 ELBs.  The Boto 2.3.8 docs describe the use of an optional "marker" to retrieve the next 400 ELBs:

```
get_all_load_balancers(load_balancer_names=None, marker=None)

marker (string) – Use this only when paginating results and only in follow-up request after you’ve
received a response where the results are truncated. Set this to the value of the Marker element in
the response you just received.
```

**Steps to Reproduce**:
First, you need an account with > 400 ELBs.  Probably rare, but we have one...

Example task:

```
- name: "Register EC2 instance with new ELB"
  local_action:
    module: ec2_elb
    instance_id: my_instance_id
    ec2_elbs: my_test_elb
    state: 'present'
    region: us-east-1
```

Output:

```
TASK: [channel_switch | Register EC2 instance with new ELB] ****************** 
failed: [localhost -> 127.0.0.1] => (item=my_instance_id) => {"failed": true, "item": "my_instance_id"}
msg: ELB my_test_elb does not exist
```
