### ISSUE TITLE
vsphere_guest: need an option to attach an existing disk

### ISSUE THREAD

**Issue by wrouesnel** [ansible/ansible-modules-core#2116]
Using `vsphere_copy` I can upload arbitrary files to the datastore, the missing element is that I cannot attach an existing disk to a new VM from `vsphere_guest`

This breaks a provisioning model where the ansible host may run packer or something similar locally, upload the artifact, and want to create a new machine from it - necessary in cases where you need to open and edit the source disk image before uploading (i.e. to set static network parameters).

**Comment by kbroughton** [comment]
What is the purpose of vm_cdrom if not to attach an existing iso?

```
vm_hardware:
  memory_mb: 2048
  num_cpus: 2
  osid: centos64Guest
  scsi: paravirtual
  vm_cdrom:
    type: "iso"
    iso_path: "DatastoreName/cd-image.iso"
```

When I run with my iso, ansible completes without error.  The vm is created but there is no cd attached.
If i create a vm from the iso via the gui, convert it to a template and use from_template in ansible, the vm works.  
+10 if vm_cdrom cannot reference an existing cdrom.  
Booting from templates is less desireable as you cannot configure different sized vms off a single template. ie burn a new template for each instance type.  :(
