### ISSUE TITLE
FR - update ec2_group to cleanly handle a cidr list in a rule

### ISSUE THREAD

**Issue by halberom** [ansible/ansible-modules-core#2120]
_Description_

Currently running ec2_group with a rule like

```
      - proto: tcp
        from_port: 9200
        to_port: 9200
        cidr_ip:
          - 10.220.130.0/27
          - 172.16.60.0/24
```

Works fine on the first run, but fails on the second with

```
<Response><Errors><Error><Code>InvalidPermission.Duplicate</Code><Message>the specified rule "peer: 10.220.130.0/27, TCP, from port: 9200, to port: 9200, ALLOW" already exists</Message></Error></Errors><RequestID>1fdf97c8-e078-4d0d-89da-cf65e498b710</RequestID></Response>
```

It has been discussed [here](https://groups.google.com/forum/#!msg/ansible-project/Int4x36MDmc/mZoXM9bOxIIJ).

_Ansible version_
1.9.3
devel

_Steps to reproduce_
run an ec2_group task that creates the above rule, then re-run it

_Expected result_
it creates the rules the first time, and then doens't make any changes or error the second time

_Actual result_
it creates the rules the first time, and then errors

_Desired_
Given that it works on the first run, and correctly creates the group and rules, it would be nice for it to work on subsequent runs.  Either that or write a fail statement and stop it working on the first run.
