### ISSUE TITLE
ec2_ami_find  not works

### ISSUE THREAD

**Issue by mogadanez** [ansible/ansible-modules-core#2121]
##### Issue Type:
- Bug Report
##### Component Name:

ec2_ami_find
##### Ansible Version:

ansible 2.0.0 (devel d851df3b31)
##### Ansible Configuration:

ec2.py invetory
##### Environment:

Debian jessie
##### Summary:

`ec2_ami_find` task failed with error:

```
"__init__() got an unexpected keyword argument 'verify'"
```
##### Steps To Reproduce:

```

- name: get ami
  hosts: localhost
  connection: local
  tasks:
    - ec2_ami_find:
        owner: self
        region: "{{region}}"
        aws_access_key: "{{aws_access_key}}"
        aws_secret_key: "{{aws_secret_key}}"
        ami_tags:
          tag1: "value1"
          tag2: "value2"
      register: ami-image
```
##### Expected Results & Actual Results:

Regression v2.0.0-0.2.alpha2 works fine (  but there is another bug there with https://github.com/ansible/ansible/issues/12258 )
