### ISSUE TITLE
Wrong Linode ID with the linode Module

### ISSUE THREAD

**Issue by iwada** [ansible/ansible-modules-core#2131]
Using the Linode Module to Create a new Linode instance. The Instance is created but with the wrong linode_id

```
 - name: Create linode machine
  linode: 
    api_key: 'My_Api_key'
    name: server
    plan: 1
    datacenter: 7
    distribution: 140
    password: 'Some_password'
    linode_id: 12345678
    ssh_pub_key: 's......'
    wait: yes
    wait_timeout: 600
    state: present 
```

Seems  the linode role is not idempotent. 
https://groups.google.com/forum/#!topic/ansible-project/C1EflNukx44
