### ISSUE TITLE
No error when illegal variable is used in loops

### ISSUE THREAD

**Issue by cortopy** [ansible/ansible-modules-core#2144]
I was trying to debug why one of my variables was not being used by `lineinfile`

If I have

``` yaml
- name: my task
  lineinfile: dest=/path/to/file regexp="{{item.regex}}" line="{{item.line}}"
  with_items:
   - { regex: "old-text", line: "{{new-text}}"}
   - { regex: "old-text2", line: "{{new-text2}}"}
```

Ansible passes the variable as a string in the following format

```
(item={'regex': 'old-text', 'line': u'{#new-text#}'})
```

It was only when I tried the variable on its own (i.e.: not using `with_items`) that I got the reason why the variables weren't being used: hyphens are not allowed in variables. 

Would it be possible to create this error when looping too? Otherwise, it's very difficult to debug
