### ISSUE TITLE
Bug with yum and with_items

### ISSUE THREAD

**Issue by jphalip** [ansible/ansible-modules-core#215]
The following works fine on CentOS:

```
$ sudo yum install "@Development tools" python-devel
```

And so does the following with Ansible:

```
- name: Install build essentials
  yum: name="@Development tools"
  sudo: yes

- name: Install python dev tools
  yum: name=python-devel
  sudo: yes
```

However, the following fails (when using `with_items`):

```
- name: Install a few things
  yum: name={{ item }}
  with_items:
    - "@Development tools"
    - python-devel
  sudo: yes
```

Here's the error output:

```
failed: => (item=@Development tools,python-devel) => {"failed": true, "item": "@Development tools,python-devel"}
msg: this module requires key=value arguments (['name=@Development', 'tools,python-devel'])
```

This looks like a bug in the parsing because of the space in `@Development tools`. Do you confirm?

**Comment by Jmainguy** [comment]
@jphalip you need to qoute the qoutes, since you want to send the qoutes with @Development tools, then it will work. Yum on command line would get confused by  yum install @Development tools without any quotes. I guess when with_items is not being used name= with qoutes gets sent? Either way I do not believe this is a bug.

```
---

- name: Install packages without spaces
  yum: name={{ item }} state=installed
  with_items:
    - httpd
    - sendmail
    - php
    - python

- name: Install Dev Tools
  yum: name="@Development tools" state=installed

- name: Install Dev Tools with items
  yum: name={{ item }} state=installed
  with_items:
    - '"@Development tools"'
```

```
PLAY [yum test] *************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [centos7.soh.re]
ok: [centos6.soh.re]
ok: [centos5.soh.re]

TASK: [yum | Install packages without spaces] ********************************* 
ok: [centos7.soh.re] => (item=httpd,sendmail,php,python)
ok: [centos6.soh.re] => (item=httpd,sendmail,php,python)
ok: [centos5.soh.re] => (item=httpd,sendmail,php,python)

TASK: [yum | Install Dev Tools] *********************************************** 
ok: [centos7.soh.re]
ok: [centos6.soh.re]
ok: [centos5.soh.re]

TASK: [yum | Install Dev Tools with items] ************************************ 
ok: [centos7.soh.re] => (item="@Development tools")
ok: [centos6.soh.re] => (item="@Development tools")
ok: [centos5.soh.re] => (item="@Development tools")

PLAY RECAP ******************************************************************** 
centos5.soh.re             : ok=4    changed=0    unreachable=0    failed=0   
centos6.soh.re             : ok=4    changed=0    unreachable=0    failed=0   
centos7.soh.re             : ok=4    changed=0    unreachable=0    failed=0   
```
