### ISSUE TITLE
rules_egress empty array not taken into account

### ISSUE THREAD

**Issue by glnds** [ansible/ansible-modules-core#2153]
##### Issue Type:

Bug Report
##### Component Name:

ec2_group
##### Ansible Version:

1.9.3
##### Summary:

[ec_group module](http://docs.ansible.com/ansible/ec2_group_module.html) empty egress rules array not taken into account

> rules_egress:
> List of firewall outbound rules to enforce in this group (see example). If none are supplied, a default all-out rule is assumed. **If an empty list is supplied, no outbound rules will be enabled.**

If an empty list is supplied there is still a default egress rule created on AWS allowing all outbound traffic.

See also:
http://grokbase.com/t/gg/ansible-project/155c5za9aq/ec2-group-does-not-honour-empty-rules-egress
##### Steps To Reproduce:

```
- name: ensure the rds security group is present
  ec2_group:
    name: RDSSG
    description: RDS security group
    vpc_id: "{{ vpc.vpc_id }}"
    profile: "{{ profile }}"
    region: "{{ region }}"
    rules:
        - proto: tcp
          from_port: 3306
          to_port: 3306
          cidr_ip: 0.0.0.0/0
    rules_egress: []
    purge_rules_egress: true
register: rds_sg
```
##### Expected Results:

No outbound rules in my security group on AWS.
##### Actual Results:

One outbound rule allowing all traffic.
