### ISSUE TITLE
Fetch module dest= relative path when using roles

### ISSUE THREAD

**Issue by dbohdan** [ansible/ansible-modules-core#2157]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 1.9.3
  configured module search path = None
```
##### Ansible Configuration:

N/A
##### Environment:

N/A
##### Summary:

Unlike `copy` or `synchronize`, `fetch` does not make the current role's `files` directory the reference point for relative local paths.

(This was previously discussed at https://github.com/ansible/ansible/issues/4566.)
##### Steps To Reproduce:

Run a task like the following from `roles/myrole/tasks/main.yml`:

``` Yaml
- name: back up remote file
  fetch:
    src: /remote/foo
    dest: foo
    flat: yes
```
##### Expected Results:

`/remote/foo` being copied to `roles/myrole/files/`.
##### Actual Results:

`/remote/foo` is copied to the directory of the playbook that includes the role (e.g., `playbook.yml`).
