### ISSUE TITLE
win_environment is not a legal parameter in an Ansible task or handler

### ISSUE THREAD

**Issue by anthonygreen** [ansible/ansible-modules-core#2187]
#### Issue Type:

Bug Report
#### Ansible Version:

1.9.3
### Ansible Configuration

```
[defaults]
inventory = ./hosts
```
#### Docker.py version

1.2.3
#### Environment

Running from: OS X 10.9.5
Managing: Windows 10
#### Summary:

the win_environment module is not available to ansible
#### Steps to reproduce

This playbook fails

```
- name: Add selenium drivers lcoation to Windows Path
  win_environment:
    state: present
    name: Path
    value: 'PATH=%PATH%;C:\selenium\'
    level: machine
```

with the error

```
ERROR: win_environment is not a legal parameter in an Ansible task or handler
```
