### ISSUE TITLE
msg: Failed to find required executable pip when installing nginx on coreos

### ISSUE THREAD

**Issue by haozhenxiao** [ansible/ansible-modules-core#2189]
I'm following [this](https://coreos.com/blog/managing-coreos-with-ansible/) tutorial to install nginx on coreos with ansible, on coreos, python is located at _/home/core/bin_, and my inventory looks like below:

```
[coreos]
10.11.49.207

[coreos:vars]
ansible_ssh_user=core
ansible_python_interpreter="PATH=/home/core/bin:$PATH python"
```

My yml file looks like this:

```
- name: example nginx website
hosts: coreos
sudo: true
tasks:
- name: Start etcd
  service: name=etcd.service state=started

- name: Install docker-py
  pip: name=docker-py

- name: pull container
  raw: docker pull nginx:1.7.1

- name: launch nginx container
  docker:
    image="nginx:1.7.1"
    name="example-nginx"
    ports="8080:80"
    state=running
```

when running the yml file, I got the following error:

```
msg: Failed to find required executable pip

FATAL: all hosts have already failed -- aborting
```
