### ISSUE TITLE
ansible azure module-error when creating vm

### ISSUE THREAD

**Issue by jdaku** [ansible/ansible-modules-core#2204]
Also try this playbook in azure=0.11.1 and azure=1.0.2

```
Createvm_yml

---
   - local_action:
     module: "azure"
     name: 'vm_ubuntu1'
     role_size: Small
     image: '5112500ae3b842c8b9c604889f8753c3__OpenLogic-CentOS-67-20150815'
     password: "xxxx"
     location: 'East US 2'
     user: admin
     wait: yes
     subscription_id: 'xxxxx'
     management_cert_path: '/auzure.pem'
     storage_account: 'some account'
     endpoints: '22,8080,80'
     register: azure_vm
```

```
root@ansible:/ansible-pbook# ansible-playbook azure_vm.yml
ERROR: password is not a legal parameter of an Ansible Play
```
