### ISSUE TITLE
user_module trys to modify group when generating ssh keys

### ISSUE THREAD

**Issue by anthonygreen** [ansible/ansible-modules-core#2221]
#### Issue Type:

Bug Report
#### Component Name:

user module
#### Ansible Version:

1.9.4.rc3
#### Environment

Running from: OS X 10.9.5
Managing: same workstation
#### Summary:

user_module tries to modify group for a task intended to generate ssh keys
#### Steps to reproduce

This task fails

```
- name: Generate ssh keys
  user:
    name: "{{ accounts.username }}"
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_passphrase: "{{ accounts.ssh_key_passphrase }}"
    ssh_key_comment: "{{ accounts.email }}"
```

with the error

```
failed: [localhost] => {"err": "", "failed": true, "out": "", "rc": 40}
msg: Cannot update property "group" for user "anthonygreen".
```
