### ISSUE TITLE
Incorrect handling of quotes in lineinfile module

### ISSUE THREAD

**Issue by devoto13** [ansible/ansible-modules-core#2227]
### Issue Type

Bug Report
### Component Name

lineinfile module
### Ansible Version

1.9.3
### Summary

I am using Ansible 1.9.3.

I have following content in my `test.yml` file:

``` yaml

---
- hosts: all
  connection: local
  tasks:
    - lineinfile:
        dest: ./example.txt
        create: yes
        line: "something '\"content\"' something else"
```

And I run it as follows:

`ansible-playbook -i localhost, test.yml`
### Expected result

`example.txt` contains `something '"content"' something else`.
### Actual result

`example.txt` contains `something content something else`. Without any quotes.
### Investigation

It seems the problem lies in the `lineinfile` module adding quotes and then executing `line = module.safe_eval(line)`. Relevant [code](https://github.com/ansible/ansible-modules-core/blob/cf88f2786822ab5f4a1cd711761a40df49bd93f0/files/lineinfile.py). 

After adding quotes line looks like `'something '"content"' something else'` and when passed to `module.safe_eval()` the Pythons's implicit string concatenation is applied and it looses all quotes.

---

**Haven't checked if problem exists in development version, it seems module was significantly rewritten.**
