### ISSUE TITLE
ResetPasswordOnFirstLogon parameter is deprecated for ansible azure module

### ISSUE THREAD

**Issue by tksarah** [ansible/ansible-modules-core#2245]
I saw a error below when I tried an azure module to run a windows machine with ansible v2.0.0.

```
fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "msg": "failed to create the new virtual machine, error was: Unknown error (Bad Request)\n<Error xmlns=\"http://schemas.microsoft.com/windowsazure\" xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\"><Code>BadRequest</Code><Message>ResetPasswordOnFirstLogon parameter is deprecated</Message></Error>"}
```

I guess that "reset_pass_atlogon" option can not use.

**Comment by robynbergeron** [comment]
[module: cloud/azure/azure.py]

**Comment by robynbergeron** [comment]
@tksarah -- Thanks for submitting this bug report. You might want to consider giving us the following additional information to help the module maintainer identify the issue: https://github.com/ansible/ansible/blob/devel/ISSUE_TEMPLATE.md

@jwhitbeck -- thanks in advance for taking a look at this bug report and for your ongoing work in maintaining this module.

**Comment by tksarah** [comment]
@robynbergeron -- Thank you. 
@jwhitbeck -- Additional Information.
Ansible version : v2.0.0 and 1.9.3
Ansible Host OS : Ubuntu 14.04 x86_64
Python azure module : 0.11.1
Ansible Configuration : 

Inventory file:

```
127.0.0.1 ansible_connection=local
```

Playbook file:

```
---
- hosts: localhost
  gather_facts: no

  tasks:
  - name: Create Virtual Machine on Azure (for Windows)
    tags: azure_win
    azure:
      auto_updates: no
      enable_winrm: yes
      endpoints: "3389,80"
      image: 'bd507d3a70934695bc2128e3e5a255ba__RightImage-Windows-2012R2-x64-v14.2'
      location: 'Japan West'
      management_cert_path: /home/vagrant/azure/manage.cer
      hostname: "{{ target }}"
      name: "{{ target }}"
      os_type: windows
      user: myuser
      password: "Password_123"
      reset_pass_atlogon: yes
      role_size: Basic_A2
      state: present
      storage_account: <my st account>
      subscription_id: <my id>
      virtual_network_name:
      wait: no
      wait_timeout: 600
      wait_timeout_redirects: 300
```

Run playbook : 

```
$ ansible-playbook -i hosts 2.0_site.yml -t azure_win -e target=tkstudio2 -vvv
Using /etc/ansible/ansible.cfg as config file
1 plays in 2.0_site.yml

PLAY ***************************************************************************

TASK [Create Virtual Machine on Azure (for Windows)] ***************************
ESTABLISH LOCAL CONNECTION FOR USER: vagrant
127.0.0.1 EXEC (umask 22 && mkdir -p "/tmp/ansible-tmp-1444638317.68-145584482033297" && echo "/tmp/ansible-tmp-1444638317.68-145584482033297")
127.0.0.1 PUT /tmp/tmpbWRCgX TO /tmp/ansible-tmp-1444638317.68-145584482033297/azure
127.0.0.1 EXEC chmod a+r /tmp/ansible-tmp-1444638317.68-145584482033297/azure
127.0.0.1 EXEC /bin/sh -c 'sudo -H -n -S -u vagrant /bin/sh -c '"'"'echo BECOME-SUCCESS-mymmnihdyfohddqtfmkcgkjdzqlckmft; LANG=C LC_MESSAGES=C LC_CTYPE=C /usr/bin/python /tmp/ansible-tmp-1444638317.68-145584482033297/azure'"'"''
127.0.0.1 EXEC rm -f -r /tmp/ansible-tmp-1444638317.68-145584482033297/ > /dev/null 2>&1
fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "msg": "failed to create the new virtual machine, error was: Unknown error (Bad Request)\n<Error xmlns=\"http://schemas.microsoft.com/windowsazure\" xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\"><Code>BadRequest</Code><Message>ResetPasswordOnFirstLogon parameter is deprecated</Message></Error>"}

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=0    changed=0    unreachable=0    failed=1
```

By the way, I can create instance when "reset_pass_atlogon" is no.
