### ISSUE TITLE
Script module writing straight to stderr and it's calling ssh -v instead straight ssh

### ISSUE THREAD

**Issue by isopy** [ansible/ansible-modules-core#2276]
Issue Type:

```
Bug Report
```

Ansible Version:

```
ansible 1.9.2
```

Ansible Configuration:

```
Issue exists even with a fresh version of ansible.cfg. My config just changes inventory location and number of forks.
```

Environment:

```
Red Hat Enterprise Linux Server release 7.1 (Maipo)
```

Summary:

```
Seeing output when calling the 'script' module that looks like ssh -v is being called instead of just plain ssh. Also, output is going directly to stderr when there are no errors
```

Steps To Reproduce:

```
Write a basic playbook with a task that calls the script module:
    ---
    - name: Run rhit checks
      script: scripts/rhit-checks.sh
      when: run_rhit_checks
      register: rhit_checks_result
      tags:
          - rhit-checks
```

Expected Results:

```
1. Output should write to stdout if there are no errors.
2. The script module should call ssh instead of ssh -v
```

Actual Results:

```
https://gist.github.com/michaeljfoxy/d7106f9addf3992a0699#file-gistfile1-txt
```
