### ISSUE TITLE
Mount module overrides entries when used with 'with_items'

### ISSUE THREAD

**Issue by drybjed** [ansible/ansible-modules-core#2291]
##### Issue Type:

Bug Report
##### Ansible Version:

Ansible stable (1.9.4), Ansible devel
##### Ansible Configuration:

Default Ansible configuration
##### Environment:

Debian, Ubuntu
##### Summary:

Ansible overrides `/etc/fstab` entry when called with `with_items`.
##### Steps To Reproduce:

```

---

- hosts: localhost

  vars:
    file_list: [ '/aaa', '/bbb' ]
    fstab_file: '/tmp/fstab'

  tasks:
    - mount:
        src: '{{ item }}'
        name: 'none'
        fstype: 'swap'
        opts: 'sw'
        state: 'present'
        fstab: '{{ fstab_file }}'
      with_items: file_list

    - mount:
        src: '{{ item }}'
        name: 'none'
        fstype: 'swap'
        opts: 'sw'
        state: 'present'
        fstab: '{{ fstab_file }}'
      with_items: file_list
```
##### Expected Results:

Two entries are created in specified fstab file, there are no changes in the second task.
##### Actual Results:

```
PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [mount ] **************************************************************** 
changed: [localhost] => (item=/aaa)
changed: [localhost] => (item=/bbb)

TASK: [mount ] **************************************************************** 
changed: [localhost] => (item=/aaa)
changed: [localhost] => (item=/bbb)

PLAY RECAP ******************************************************************** 
mount  ------------------------------------------------------------------ 0.14s
localhost                  : ok=3    changed=2    unreachable=0    failed=0   
```
