### ISSUE TITLE
problem with hash character (#) in path in fetch module

### ISSUE THREAD

**Issue by dron23** [ansible/ansible-modules-core#2293]
Issue Type: Bug Report

Ansible Version: ansible 1.9.3 (ansible-1.9.3-2.fc21)
Ansible Configuration: no changes to /etc/ansible/ansible.cfg made
Environment: Fedora 21, x86_64
Summary: When I use hash character (#) in path in fetch module, file is not fetched and checksum mismatch msg is returned instead
Steps To Reproduce:

1) create ~/ansible/ansible-error.yml playbook

```

---
- hosts: gluster-tst
  remote_user: root
  tasks:
- name: fetch module tester
  fetch: src=/tmp/remote_file.txt dest=~/tmp/#test/ flat=yes
```

2] populate /tmp/remote_file.txt on remote host(s)
3] run playbook ansible-playbook ~/ansible/ansible-error.yml

```
PLAY [gluster-tst] ************************************************************ 

GATHERING FACTS *************************************************************** 
ok: [gluster-tst01]

TASK: [fetch module tester] *************************************************** 
failed: [gluster-tst01] => {"checksum": null, "dest": "/home/dron/tmp/#test/remote_file.txt", "failed": true, "file": "/tmp/remote_file.txt", "md5sum": null, "remote_checksum": "4fe0b800d221d1a61c44cd81d2975a288ffd22e4", "remote_md5sum": null}
msg: checksum mismatch
```

Expected Results: fetched file
Actual Results: file is not fetched at all (does not exists locally) and msg: checksum mismatch is returned
