### ISSUE TITLE
ec2_elb_lb always reports a changed state when specifying a https listener with certificate

### ISSUE THREAD

**Issue by teamdoug** [ansible/ansible-modules-core#23]
This is a copy of ansible/ansible#9073 created by @itarchmerc and is fixed by #22 

Issue Type:

When using the ec2_elb_lb module to create an ELB with a HTTPS listener with a SSL certificate, the module always reports the status as changed even when no changes are made.

Ansible Version:

1.7.1

Environment:

Management Machine: Mac OS X 10.9.4, ansible 1.7.1 installed via homebrew
Target Machine: EC2 ELB

Summary:

When using the ec2_elb_lb module to create an ELB with a HTTPS listener with a SSL certificate, the module always reports the status as changed even when no changes are made. If I remove the HTTPS listener and only specify HTTP, the status is reported correctly.

Steps To Reproduce:

Create an ELB with the ec2_elb_lb module with a HTTP and HTTPS (with SSL certificate) listener. The ELB will be provisioned.
Rerun the same task. The status will report as changed even though no changes were made.
Expected Results:

Status should be ok on subsequent runs of the same task

Actual Results:

Status always shows as changed.

**Comment by endzyme** [comment]
This is still a problem in 1.8.2

**Comment by endzyme** [comment]
poking again :] anyone watch these or is there anything i can help to get this merged in?

**Comment by bcoca** [comment]
we are watching, just a large backlog to get through

**Comment by endzyme** [comment]
Is there an ETA - or anything I can do to help contribute? Testing? etc?

**Comment by juliedavila** [comment]
@endzyme This has been fixed by https://github.com/ansible/ansible-modules-core/pull/22

**Comment by endzyme** [comment]
Thanks!!

**Comment by bcoca** [comment]
closing as this is fixed as mentioned above

**Comment by diranged** [comment]
@bcoca, I believe this issue is still happening to us with the latest Ansible. Is it possible that there is a regression recently in the code?

**Comment by juliedavila** [comment]
@diranged can you let us know what version of Ansible you're using and if you're hitting it with the exact same steps as the OP?

**Comment by diranged** [comment]
`ansible==2.0.0.2` and yes, I think so. If not, then we're seeing some other but similar failure. We use a common task for creating ELBs:

```
# A common module for creating our ELBs
#
# Usage:
#   - include_vars: vars/app_groups.yml
#   - include: tasks/aws_elb.yml
#     vars:
#       app_group: "us1"
#       name: sage
#       region: "us-east-1"
#       health_check:
#         ping_protocol: https # options are http, https, ssl, tcp
#         ping_port: 8013
#         ping_path: "/healthz" # not required for tcp or ssl
#         response_timeout: 5 # seconds
#         interval: 6 # seconds
#         unhealthy_threshold: 2
#         healthy_threshold: 3
#       listeners:
#         - protocol: https
#           load_balancer_port: 443
#           instance_protocol: https
#           instance_port: 8013
#           ssl_certificate_id: "arn:aws:iam::12345678:server-certificate/MDC-eng-Dec-2018"
#       scheme: internal
#       security_group_ids: 
#         - sg-abcdefg
#       subnets: "{{ private_subnets }}"
#       sticky: yes
#       log_bucket: "{{ log_bucket }}"
#       cname: true # creates <elb_name>.stuff.xxx.com
#
---

- name: "Creating ELB {{ full_name }}"
  vars:
    full_name: "{{ app_group }}-{{ name }}-{{ region | regex_replace('-', '') }}"
  ec2_elb_lb:
    name: "{{ full_name }}"
    state: present
    region: "{{ region }}"
    cross_az_load_balancing: "{{ cross_az_load_balancing | default('yes') }}"
    connection_draining_timeout: "{{ connection_draining_timeout | default(60) }}"
    health_check: "{{ health_check }}"
    listeners: "{{ listeners }}"
    idle_timeout: "{{ idle_timeout | default(omit) }}"
    scheme: "{{ scheme | default('internal') }}"
    security_group_ids: "{{ security_group_ids }}"
    subnets: "{{ subnets }}"
    stickiness:
      type: loadbalancer
      enabled: "{{ sticky | default('yes') }}"
      expiration: 600
    access_logs:
      interval: "{{ log_frequency | default(60) }}"
      s3_location: "{{ log_bucket }}"
      s3_prefix: "{{ full_name }}"
  register: new_elb

- name: "Create R53 Record {{ new_elb.elb.name }}.{{ service_domain }}"
  route53:
    command: create
    zone: "{{ service_domain }}"
    record: "{{ new_elb.elb.name }}.{{ service_domain }}"
    type: CNAME
    ttl: 300
    value: "{{ new_elb.elb.dns_name }}"
  when: cname
```

**Comment by juliedavila** [comment]
Looking into this now

**Comment by juliedavila** [comment]
I am unable to replicate with this playbook

``` yml
---
- name: Testing ELB
  hosts: localhost
  connection: local
  tasks:
    - name: Elb test
      ec2_elb_lb:
        name: Testing23
        state: present
        region: us-east-1
        scheme: internal
        listeners:
         - protocol: https
           load_balancer_port: 443
           instance_protocol: http
           instance_port: 80
           ssl_certificate_id: "arn:aws:iam::768876501522:server-certificate/davilacert"
        subnets:
           - subnet-327a1b08
           - subnet-3c61527a
           - subnet-5f207377
           - subnet-983026ec
```

It get created and it does not appear as 'changed' in subsequent runs

**Comment by lflautomation** [comment]
@defionscode I was experiencing this issue and I found the cause was the silently ignored `proxy_protocol` field I had in my `http` listener. I'm not sure this is what the original reporter was experiencing, but since I had cut-and-pasted the first example on http://docs.ansible.com/ansible/ec2_elb_lb_module.html, then I'm guessing others are finding this issue.

You can reproduce it with the following change to your example:

``` yaml
---
- name: Testing ELB
  hosts: localhost
  connection: local
  tasks:
    - name: Elb test
      ec2_elb_lb:
        name: Testing23
        state: present
        region: us-east-1
        scheme: internal
        listeners:
         - protocol: http
           load_balancer_port: 80
           instance_port: 80
           proxy_protocol: True #remove this line to fix the issue
         - protocol: https
           load_balancer_port: 443
           instance_protocol: http
           instance_port: 80
           ssl_certificate_id: "arn:aws:iam::768876501522:server-certificate/davilacert"
        subnets:
           - subnet-327a1b08
           - subnet-3c61527a
           - subnet-5f207377
           - subnet-983026ec
```
