### ISSUE TITLE
cloudformation state: absent requires template or template_url

### ISSUE THREAD

**Issue by adenot** [ansible/ansible-modules-core#2314]
##### Summary:

Using the latest (9eb0c178ec2f4e94ae29329fa9694a381157b413) cloudformation module, below **does not** works:

``` yaml
    - name: Removing RDS instances
      cloudformation2:
        stack_name: "{{ db_stack_name }}"
        state: "absent"
        region: "{{ aws_region }}"
```

But passing a template or template_url, even if dummy, works:

``` yaml
    - name: Removing RDS instances
      cloudformation2:
        stack_name: "{{ db_stack_name }}"
        state: "absent"
        region: "{{ aws_region }}"
        template_url: "it's a bug"
```
##### Expected Results:

According to docs, template/template_url should only be required when state: present.
##### Actual Results:

```
TASK: [Removing RDS instances] ************************************************
failed: [localhost] => {"failed": true}
msg: Either template or template_url expected

cloudformation2 [localhost] =>
{
  "msg": "Either template or template_url expected",
  "failed": true
}
```
