### ISSUE TITLE
glance images uploaded via os_image with is_public: true are not public

### ISSUE THREAD

**Issue by larsks** [ansible/ansible-modules-core#2325]
I have the following in a playbook:

```
- name: uploading centos atomic image to glance
  os_image:
    name: centos-7-atomic
    is_public: yes
    filename: images/centos-7-atomic.qcow2
```

The resulting image is not public:

```
+------------------------------+------------------+
| Property                     | Value            |
+------------------------------+------------------+
| name                         | centos-7-atomic  |
| visibility                   | private          |
+------------------------------+------------------+
```

Whereas if I upload an image from the command line:

```
glance image-create --file images/centos-7-atomic.qcow2 \
  --name larstest --visibility public \
  --disk-format qcow2 --container-format bare
```

The resulting image is publicly visible:

```
+------------------+-------------+
| Property         | Value       |
+------------------+-------------+
| name             | larstest    |
| visibility       | public      |
+------------------+-------------+
```
