### ISSUE TITLE
ec2_vpc ignores profile parameter and uses default AWS credentials from ~/.aws/credentials

### ISSUE THREAD

**Issue by inadarei** [ansible/ansible-modules-core#2355]
This is what my ~/.aws/credentials looks like:

```
# let's assume default is my company credentials
[default]
aws_access_key_id = REDACTED
aws_secret_access_key = REDACTED

[irakli-aws]
aws_access_key_id = REDACTE
aws_secret_access_key = REDACTED
```

This is what a snippet in my role looks like:

```
- ec2_vpc:
    profile: "irakli-aws"
    region: "{{ aws_region }}"
    state: present
    cidr_block: "10.0.0.0/16"
    wait: yes
    wait_timeout: 300
    resource_tags: { Name: "samplevpc" }
  register: vpc_settings
```

Given the `profile: "irakli-aws"` line this should create VPC in my personal AWS account. This is how every other ec2_ Ansible module works (verified), but not ec2_vpc. It clearly created VPC in the default.

Big bummer, obviously.
