### ISSUE TITLE
apt_key unable to process  hkp:// protocol

### ISSUE THREAD

**Issue by inadarei** [ansible/ansible-modules-core#2356]
`hkp://` is a pretty standard protocol, for instance: used by Docker to [install Docker on Ubuntu](https://docs.docker.com/installation/ubuntulinux/).

apt_key is unable to process it, unfortunately. Case in point: following works fine from the command line:

```
$ sudo apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
```

but the equivalent in Ansible:

```
  - name: Add Docker repository key
    apt_key:
      id: "58118E89F3A912897C070ADBF76221572C52609D"
      url: "hkp://pgp.mit.edu:80"
      state: present
```

fails with:

```
failed: [154.133.215.170] => {"failed": true}
msg: Failed to download key at hkp://pgp.mit.edu:80: Request failed: <urlopen error unknown url type: hkp>
```
