### ISSUE TITLE
Docker module -- with_items fails

### ISSUE THREAD

**Issue by luhkevin** [ansible/ansible-modules-core#2359]
Hi,

I'm not sure if this is specific to the Docker module, but I have a "docker" role with subdirs "defaults" and "tasks". In "tasks/main.yml", I have some lines that look like this:

```
- name: Spin down containers
  docker:
    name: "{{ item }}"
    image: some-image
    state: absent
  ignore_errors: True
  with_items: docker_list
```

`docker_list` is a list of items defined in "defaults/main.yml" ... I use "with_items" in the same way with the apt module, and I defined a list of items in "defaults/main.yml" in the same way, under the list "apt-dependencies"

However, I'm getting an error when doing this with the docker module:

```
ERROR: expecting dict; got: None, error in /path/to/tasks/main.yml
```

Any ideas? Am I misusing "with_items" here?
