### ISSUE TITLE
s3 module would benefit from a 'checksum' parameter

### ISSUE THREAD

**Issue by lindes** [ansible/ansible-modules-core#2404]
### Issue Type:

Feature Idea
### Ansible Version:

```
ansible 1.9.4
  configured module search path = None
```
### Ansible Configuration:

No global changes.
### Environment:

ubuntu wheezy/64
### Summary:

I'd like the `s3` module to have a checksum module, for `mode=get` requests, similar to what `get_url` has.
### Steps To Reproduce:

Set up an ansible task such as this:

```
- s3:
    bucket: mybucket
    object: /my/desired/key.txt
    dest: /usr/local/myfile.txt
    mode: get
    checksum: "sha256:D98291AC[...]B6DC7B97"
```
### Expected Results:

I'd expect something like the following to transpire (ruby-esque psuedocode)

```
def cehcksum_matches(file, type, expected, absent_ok = false)
  unless File.exists?(file)
    return false if absent_ok
    raise FileDoesNotExistError # gets handed back as an error
  end
  compute_checksum(file, type) == expected
end

type,expected = checksum_arg.split(':')
if(compare(file, type, expected, true) and not force)
  return {changed: false} # no change
else
  download_s3(bucket, object, file)
  assert(compare(file, type, expected)) # may create an error
  return {changed: true} # indicate that a change was made
end
```
### Actual Results:

```
failed: [details elided]
msg: unsupported parameter for module: checksum
```
