### ISSUE TITLE
rax_clb_nodes moduel wrongfully changes load balancer port and protocol

### ISSUE THREAD

**Issue by wbentley15** [ansible/ansible-modules-core#241]
Issue Type:  Bug Report
Ansible Version: ansible 1.7.2

Environment: MAC OS X
Summary:  when adding a new node using the module the load balancer port and protocol are changed back to default settings (80/HTTP).  No matter what the port and protocol was prior to adding the node.
Steps To Reproduce:  create load balancer with non-default settings, such as port 161 and protocol UDP, create a play or role adding a node to that load balancer and then watch the load balancer port/protocol be updated to the default values (80/HTTP).

Expected Results: new node would be added to the load balancer
Actual Results: new node was added to load balancer and load balancer port/protocol were updated also

**Comment by ansibot** [comment]
# Can You Help Us Out?

Thanks for filing a ticket! I am the friendly GitHub Ansibot. 

It looks like you might not have filled out the issue description based on our standard issue template.  You might not have known about that, and that's ok too, we'll tell you how to do it.

We have a standard template because Ansible is a really busy project and it helps to have some standard information in each ticket, and GitHub doesn't yet provide a standard facility to do this like some other bug trackers.  We hope you understand as this is really valuable to us!. 

Solving this is simple: please copy the contents of this [template](https://raw.githubusercontent.com/ansible/ansible/devel/ISSUE_TEMPLATE.md) and **paste it into the description** of your ticket.  That's it!

# If You Had A Question To Ask Instead

If you happened to have a "how do I do this in Ansible" type of question, that's probably more of a user-list question than a bug report, and you should probably ask this question on the project mailing list instead.  

However, if you think you have a bug, the report is the way to go!  We definitely want all the bugs filed :)  Just trying to help!

# About Priority Tags

Since you're here, we'll also share some useful information at this time.

In general tickets will be assigned a priority between P1 (highest) and P5, and then worked in priority order. We may also have some follow up questions along the way, so keeping up with follow up comments via GitHub notifications is a good idea.

Due to large interest in Ansible, humans may not comment on your ticket immediately.  

# Mailing Lists

If you have concerns or questions, you're welcome to stop by the ansible-project or ansible-development mailing lists, as appropriate.  Here are the links:
- https://groups.google.com/forum/#!forum/ansible-project - for discussion of bugs and how-to type questions
- https://groups.google.com/forum/#!forum/ansible-devel - for discussion on how to implement a code change, or feature brainstorming among developers

Thanks again for the interest in Ansible!

**Comment by sivel** [comment]
I cannot replicate this behavior. Please provide a minimal playbook test case that causes this behavior.

**Comment by wbentley15** [comment]
Here you go...I would be happy if it is just me :)

```
- name: Load Balancer create request
  rax_clb: name={{ lbname }} port={{ lbport }} protocol={{ lbproto }} algorithm={{ lbalgo }} type=PUBLIC api_key={{ raxkey }} username={{ raxuser }}
           region={{ raxregion }} wait=yes state=present
  register: raxlb
  ignore_errors: True

- name: Add node(s) to Load Balancer
  rax_clb_nodes: load_balancer_id={{ raxlb.balancer.id }} address={{ rax_addresses.Private[0].addr }} port={{ nodeport }}
                 region={{ raxregion }} api_key={{ raxkey }} username={{ raxuser }} type=primary wait=yes condition=enabled
```

**Comment by sivel** [comment]
I am still unable to replicate this.  Here is the updated version of the test case that you provided to include vars to allow this to run:

```
- hosts: localhost
  gather_facts: false
  vars:
    lbname: "core-241"
    lbport: 161
    lbproto: UDP
    lbalgo: ROUND_ROBIN

    raxregion: ORD

    rax_addresses:
      Private:
        - addr: "172.16.0.1"

    nodeport: 2161

  tasks:
    - name: Load Balancer create request
      rax_clb: name="{{ lbname }}" port="{{ lbport }}" protocol="{{ lbproto }}" algorithm="{{ lbalgo }}" type=PUBLIC
               credentials=~/.raxpub region="{{ raxregion }}" wait=yes state=present
      register: raxlb
      ignore_errors: True

    - name: Add node(s) to Load Balancer
      rax_clb_nodes: load_balancer_id="{{ raxlb.balancer.id }}" address="{{ rax_addresses.Private[0].addr }}" port="{{ nodeport }}"
                     region="{{ raxregion }}" credentials=~/.raxpub type=primary wait=yes condition=enabled
```

Perhaps you have other vars some place that are overwriting `lbport` and `lbproto`?  Does this still happen even when you don't add nodes via `rax_clb_nodes`? Maybe you are chasing the wrong rabbit down the wrong hole.

What does using `-vv` show you when running ansible?
