### ISSUE TITLE
EC2 module not respecting gp2 volume_type

### ISSUE THREAD

**Issue by gtowne** [ansible/ansible-modules-core#2414]
##### Issue Type:

Bug Report
##### Ansible Version:

```
$ ansible --version
ansible 1.9.4
  configured module search path = None

$ pip freeze
ansible==1.9.4
boto==2.38.0
ecdsa==0.13
Jinja2==2.8
MarkupSafe==0.23
paramiko==1.15.4
pycrypto==2.6.1
PyYAML==3.11
```
##### Ansible Configuration:

Ansible configuration is default from fresh pip install.
##### Environment:

Python 2.7.1 on Mac OS X Yosemite
##### Summary:

The `ec2` module is not respecting the specification of `gp2` (SSD) for the `volume_type` of an attached EBS volume and is instead creating a new instance with the default `standard` (Magnetic) type.
##### Steps To Reproduce:

Run the following playbook, specifying `-e subnet="<your_subnet_id>" -e key_name="<your_key_name>"` at the command line

``` YML
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: launch ec2 instance with root SSD EBS
      ec2:
        vpc_subnet_id: "{{ subnet }}"
        assign_public_ip: true
        region: us-east-1
        key_name: "{{ key_name }}"
        instance_type: t2.micro
        image: ami-9eaa1cf6
        volumes:
          - device_name: /dev/sdb
            volume_type: gp2
            volume_size: 10
        wait: true
        wait_timeout: 500
        instance_tags:
           Name: "Test SSD EBS"
```
##### Expected Results:

Expect a new EC2 instance to be created named "Test SSD EBS" with an SSD EBS volume attached at `/dev/sdb`
##### Actual Results:

The instance is created with the `/dev/sdb` volume as `standard` (Magnetic)
