### ISSUE TITLE
system/mount.py

### ISSUE THREAD

**Issue by Rtzq0** [ansible/ansible-modules-core#2429]
##### ISSUE TYPE

Bug Report
##### COMPONENT NAME

mount module
##### ANSIBLE VERSION

N/A
##### SUMMARY

This ticket is opened because #8377 on ansible core is closed (and this is a more appropriate repo)

This issue is still present as recently as 1.9.4 (cannot test on newer versions).

It looks as though the mount module calls -o remount blindly instead of calling umount followed by mount.

Example:

```
- name: mount a mount
  mount:
    state: "mounted"
    fstype: "nfs"
    name: "/mnt/foo"
    src: "fizz:/buzz"
    opts: "rsize=8192,wsize=8192,timeo=14,intr,nosuid"
```

Will happily mount your mount, but when you run with

```
- name: mount a mount
  mount:
    state: "mounted"
    fstype: "nfs"
    name: "/mnt/foo"
    src: "fizz:/buzz"
    opts: "timeo=14,intr,nosuid"
```

It will fail with an unsupported mount option error, because remount is not a supported mount option for mount.nfs
