### ISSUE TITLE
The os_network module fails on creating a new neutron network in Cisco OpenStack cloud

### ISSUE THREAD

**Issue by bnaydenov** [ansible/ansible-modules-core#2435]
Issue Type:
Bug Report

Ansible Version:

ansible 2.0.0 (devel da4b4a2a33) last updated 2015/11/09 09:40:36 (GMT +300)
  lib/ansible/modules/core: (detached HEAD a3a7cdb9aa) last updated 2015/11/02 12:37:57 (GMT +300)
  lib/ansible/modules/extras: (detached HEAD b1db0e893c) last updated 2015/11/09 09:40:19 (GMT +300)

Ansible Configuration:

Environment:

N/A

Summary:

The os_network module fails on creating a new neutron network in Cisco OpenStack cloud. Account used is with super admin rights. I can successfully create new network from Horizon UI with the same account.

Steps To Reproduce:

```

---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: create internal network
      os_network:
        name: "test-private"
        admin_state_up: yes
        shared: no
        external: no
        cloud: "test"
```

I also get the same result with "shared: yes" & "external: yes"

Expected Results:

I'd expect to be able to set new network named "test-private". 

Actual Results:

Currently I get:
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error creating network test-private: Forbidden"}
