### ISSUE TITLE
add etag option to avoid re-downloading unchanged files

### ISSUE THREAD

**Issue by phraktle** [ansible/ansible-modules-core#2443]
##### ISSUE TYPE

Feature Idea
##### COMPONENT NAME

get_url module
##### ANSIBLE VERSION

1.9.4
##### SUMMARY

(Ansible version 1.9.4)

get_url always re-downloads the file and indicates a change, even though the file does not actually change.

```
- name: get the latest geo data
  get_url: url=http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz dest=/tmp/
```

**Comment by Constantin07** [comment]
In order the module to be idempotent, Ansible would need to know the previos state of the file, e.g. time of last change or md5,sha1 hash, etc.

You can specify the "checksum" option but Ansible will download the file anyway in order to check the hash.

If remote HTTP server provides headers like Etag then it could potentially be used to track the file version and proceed with download if it doesn't match.

I vote to have this feature too. +1

**Comment by phraktle** [comment]
Indeed, standard HTTP caching behavior (checking etag) would be most appropriate (a quick 304 Not Modified response vs downloading the file).

**Comment by simonswine** [comment]
+1

**Comment by ansibot** [comment]
@jpmens, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/jctanner/ansibullbot/blob/ISSUE_TRIAGE_CLASS/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@jpmens, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jpmens** [comment]
needs_contributor

**Comment by Constantin07** [comment]
This is a solution based on file size.

```
  vars:

   url: "https://the.earth.li/~sgtatham/putty/0.67/x86/putty.exe"

  tasks:

  - uri:
      url: "{{ url }}"
      method: HEAD
      validate_certs: no
    register: url_stat

  - stat: path="{{ url | basename }}"
    register: file_stat

  - get_url:
      url: "{{ url }}"
      dest: ./
      force: yes
    when: not file_stat.stat.exists or
          url_stat.content_length != file_stat.stat.size
```
