### ISSUE TITLE
win_lineinfile only replaces the last match in a file, even if multiple lines match

### ISSUE THREAD

**Issue by ianclegg** [ansible/ansible-modules-core#2456]
##### ISSUE TYPE

Bug Report
##### COMPONENT NAME

win_lineinfile module
##### ANSIBLE VERSION

N/A
##### SUMMARY

Hi,

I'm trying to use win_lineinfile to set a username and password in a yml file used by one of our apps. I've found that if multiple lines match, win_lineinfile will only replace the last line that matched - other matching lines are ignored. Is this behavior by design?

Consider a playbook task

```
    - name: Apply cluster configuration
      win_lineinfile:
        dest: "{{ service_path }}\\conf\\{{ service_config_file }}"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        backrefs: no
      with_items:
        - { regexp: 'username:.*$',line: 'username: newuser' }
        - { regexp: 'password:.*$',line: 'password: newpassword' }
```

and the dest file contents (which contains two valid matches)

```
lowFrequencyRepositoryPolicy:
  credentials:
    username: olduser
    password: oldpassword

highFrequencyRepositoryPolicy:
  credentials:
    username: olduser
    password: oldpassword
```

results in the following (where only the last match is updated)

```
lowFrequencyRepositoryPolicy:
  credentials:
    username: olduser
    password: oldpassword

highFrequencyRepositoryPolicy:
  credentials:
    username: newuser
    password: newpassword
```
