### ISSUE TITLE
Ability to create IAM roles for use with Lambda (and other services?)

### ISSUE THREAD

**Issue by mseiwald** [ansible/ansible-modules-core#2468]
When creating IAM roles with the `iam` module by default the trust relationship of the roles is set so that only EC2 instances can assume the roles. I would need the ability to create roles for Lambda functions and other AWS services. I think what's missing is the ability to provide a custom policy for the trust relationship..

**Comment by Constantin07** [comment]
+1

**Comment by fiunchinho** [comment]
:+1:

**Comment by mellowplace** [comment]
:+1: 

Same when trying to use Amazon Cognito - we need to be able to define the trust relationship

**Comment by ranchodeluxe** [comment]
is there a current work around to edit the trust_policy?

**Comment by ranchodeluxe** [comment]
once possibility I guess is that you can just wrap the AWS CLI call with shell module
`local_action: shell aws iam create-role --role-name=<name> --assume-role-policy-document=file://devops/roles/iam_users/files/policies/lambda-s3-execution-trust-policy.json`

**Comment by ghost** [comment]
Quick patched IAM module here allowing custom trust policies: https://github.com/pjodouin/ansible-lambda/blob/master/modules/iam.py

```
  tasks:
  - name: Create IAM role with custom trust relationship
    iam:
      iam_type: role
      name: API2LambdaTestRole
      state: present
      trust_policy: iam_trust.json
```
