### ISSUE TITLE
yum state=latest fails silently, state=present works. maybe groups related.

### ISSUE THREAD

**Issue by joelanders** [ansible/ansible-modules-core#2510]
Issue Type:
Bug Report

Ansible Version:
1.9.4

Ansible Configuration:
probably standard

Environment:
some amazon ami with yum

Summary:
installs nothing:

```
- hosts: localhost
  connection: local
  tasks:
    - name: Install dev tools
      yum: name="@Development Tools" state=latest
      sudo: yes
```

installs stuff:

```
- hosts: localhost
  connection: local
  tasks:
    - name: Install dev tools
      yum: name="@Development Tools" state=present
      sudo: yes
```

Steps To Reproduce:
^
Expected Results:
^
Actual Results:
^
