### ISSUE TITLE
gce_net fails when using src_range

### ISSUE THREAD

**Issue by smcavoy-b** [ansible/ansible-modules-core#252]
##### Issue Type:

Bug Report
##### Ansible Version:

1.7.2
##### Environment:

Mac OS X 10.10
##### Summary:

gce_net fails when using src_range
##### Steps To Reproduce:

YAML at https://gist.github.com/bangmedia-seanmcavoy/ebe6a3b9654fe397db7e
basically gce_net fails is src_range is specified.
I have specified '10.0.0.1/32' and ['10.0.0.1/32'] same error
##### Expected Results:

The module should set the value of the resource.sourceRange field to src_range value
##### Actual Results:

```
failed: [localhost -> 127.0.0.1] => {"changed": false, "failed": true}
msg: Unexpected response: {'code': None,
'driver': None,
'http_code': 400,
 'value': {'domain': 'global',
           'message': "Invalid value for field 'resource.sourceRange': ''.  Must specify either sourceRange or   sourceTag.",
           'reason': 'invalid'}}

FATAL: all hosts have already failed -- aborting
```

**Comment by mpdehaan** [comment]
cc @erjohnso

**Comment by br0ziliy** [comment]
For anyone interested, this simple workaround worked for me:

``` diff
--- a/cloud/google/gce_net.py
+++ b/cloud/google/gce_net.py
@@ -156,7 +156,7 @@ def main():
             ipv4_range = dict(),
             fwname = dict(),
             name = dict(),
-            src_range = dict(),
+            src_range = dict(type='list'),
             src_tags = dict(type='list'),
             state = dict(default='present'),
             service_account_email = dict(),
```

With the above modification, below task is working just fine:

``` yaml
- name: Provision staging tier firewall rules (internal)
  local_action: gce_net name=staging-net
                        fwname=internal-allow
                        allowed={{ item }}
                        src_range=10.241.0.0/16
  with_items:
    - "tcp:1-65535"
    - "udp:1-65535"
    - "icmp"
```
