### ISSUE TITLE
Template module doesn't allow using new network facts on first playbook run.

### ISSUE THREAD

**Issue by DieterZorn** [ansible/ansible-modules-core#2539]
Hi,

I've simplified my playbook to easily reproduce the issue ... running  ansible-1.9.4-1.el6.noarch  on RHEL6.

```
PLAYBOOK:

---
- hosts: all
  sudo: True
  roles:
    - defaults
    - network_test
    - bug_test
```

The default role only contains handlers for network restart and reloading facts.
In the network role the network interface eth1 is configured with an IP address.
The network role itself triggers two handlers, one to restart the network and the other to reload the facts.
The bug_test role has a template task which accesses the variable like this:

```
{{ hostvars[inventory_hostname].ansible_eth1.ipv4.network }}
```

The respective task is:

```

---
- name: Cretae response file
  template: src=grid_11204.rsp.j2 dest=/home/oragrid/grid_11204.rsp owner=oragrid group=oinstall mode=644
  tags: deploy_oracle_gi
```

The network task looks like this:

```

---
- name: "Get IP"
  raw: /usr/bin/host {{ hostvars[inventory_hostname].ansible_hostname }}_{{ bond_dblan.dns }}| awk '{print $4}'
  register: eth1_ip
  failed_when: "'found' in eth1_ip.stdout"
  tags: dcs_network

- name: "Configure eth1 ifcfg"
  template: src=ifcfg-eth1.j2 dest=/etc/sysconfig/network-scripts/ifcfg-eth1
  when: ansible_virtualization_type == "NA"
  notify:
    - restart network
    - reload facts
  tags: dcs_network
```

And the handlers like that:

```
 - name: restart network
   service: name=network state=restarted

 - name: reload facts
   setup: filter=ansible_local
```

Now the first run always fails like this:

```
PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [ob5dx502]

TASK: [network_test | Get IP] ************************************************* 
ok: [ob5dx502]

TASK: [network_test | Configure eth1 ifcfg] *********************************** 
changed: [ob5dx502]

NOTIFIED: [defaults | restart network] **************************************** 
changed: [ob5dx502]

NOTIFIED: [defaults | reload facts] ******************************************* 
ok: [ob5dx502]

TASK: [bug_test | Cretae response file] **************************** 
fatal: [ob5dx502] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'dict object' has no attribute 'ipv4'", 'failed': True}
fatal: [ob5dx502] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'dict object' has no attribute 'ipv4'", 'failed': True}

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/ansible/template_test.retry

ob5dx502                   : ok=5    changed=2    unreachable=1    failed=0   
```

And already the second run succeeds :

```
[dzorn@btpv0300 ~]$ sudo -u ansible ansible-playbook -i /srv/ansible/dcs_ip.inv -l 'ob5dx502' /srv/ansible/template_test.yml 

PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [ob5dx502]

TASK: [network_test | Get IP] ************************************************* 
ok: [ob5dx502]

TASK: [network_test | Configure eth1 ifcfg] *********************************** 
ok: [ob5dx502]

TASK: [bug_test | Cretae response file] **************************** 
changed: [ob5dx502]

PLAY RECAP ******************************************************************** 
ob5dx502                   : ok=4    changed=1    unreachable=0    failed=0   
```

Easy to reproduce.
I already used the debug module to print out the facts just before the template tries to access them.
The needed fact is already there but I nevertheless get above error with the first run. The second and subsequent runs are o.k.
So, maybe the cached facts are not updated correctly during the first run ?

Thanks for any hints and regards,

Dieter.
