### ISSUE TITLE
git module does not properly update bare repository

### ISSUE THREAD

**Issue by chuckyz** [ansible/ansible-modules-core#2540]
_Sorry for opening this in the wrong area...  re-creating here._ :)

The git module does not appear to properly update a bare repository...

Also, please excuse my poor understanding; but it appears that the fetch function never actually runs any commands, as there is no run_command() in the entire function.  Could that be the issue?

If I let Ansible manage my bare repo it _sometimes_ updates it, but randomly does not.  It also appears to only happen when looking at non-master branches (e.g.: origin/foo instead of origin/master).

The following task is what handles the updates, with variables included:

```
    repo_uri:       git@github.com:our/repo.git
    repo_path:      "{{ deploy_path }}/repositories/repo.git"

    - name: update the local repository
      git:
        repo: "{{ repo_uri }}"
        dest: "{{ repo_path }}"
        bare: yes
        clone: yes
        update: yes
        force: yes
        accept_hostkey: True

   # This fails if bare repo is not updated.
    - name: create the release directory
      git:
        repo: "{{ repo_path }}"
        dest: "{{ release_path }}"
        version: "{{ release_sha }}"
        clone: yes
        force: yes
        accept_hostkey: True
```

Simply running what I expect,  and then re-running the playbook allows everything to run smoothly.

I've added this into my playbook as a workaround for now.

```
    - name: ensure local bare repo is actually up to date
      shell: git fetch origin 'refs/heads/*:refs/heads/*'
      chdir: "{{ repo_path  }}"
```
