### ISSUE TITLE
Impossible to use pipe in validate option of copy module

### ISSUE THREAD

**Issue by astorije** [ansible/ansible-modules-core#2597]
##### Issue Type:

Bug Report
##### Ansible Version:

1.9.2 although this is true for older versions.
##### Ansible Configuration:

N/A
##### Environment:

N/A
##### Summary:

When using a pipe (`|`) in a `validate` command of the `copy` module, the command run because the pipe gets escaped.

This is a problem when the command being given does not discriminate on the return code but its output differs whether the check passes or fails. An example of this is `openssl dhparam -check`, which outputs `DH parameters appear to be ok` when passing and `p value is not prime` and/or `the g value is not a generator` when failing.

I haven't checked on other modules having a `validate` option but my guess is that the issue applies there too.
##### Steps To Reproduce:

Assuming `validate_command` always return `0` and outputs `passing`/`failing`:

``` yaml
- copy:
  src: src_path
  dest: dest_path
  validate: validate_command %s | grep -q 'passing'
```
##### Expected Results:

The file being copied if `validate_command` outputs `passing`, stoping the playbook execution otherwise.
##### Actual Results:

``` sh
failed: [default] => {"checksum": "66b...039", "cmd": "validate_command /home/user/.ansible/tmp/ansible-tmp-144...013/source '|' grep -q 'passing'", "failed": true, "rc": 2}
```

The pipe gets escaped, preventing the validation command to pass at all.

**Comment by mscherer** [comment]
The commit I made is a potential fix (din't test yet), but I am wondering on the security implication of doing so. The only potential for injection would be on dest_path, and it should be admin controlled anyway, but if it is constructed from a user supplied value, it would cause trouble. 

Maybe it is better to add a verification, like check if there is a '|' in validate command before enabling it ?

**Comment by astorije** [comment]
@mscherer, thanks for your answer! Did you open a PR by chance?
In particular, submitting your code and asking for discussion around security should bring you the great minds of Ansible to give their opinion :-)

**Comment by abadger** [comment]
Sorry it took a while for us to look into this because of the 2.0 release in the middle.  We've taken a look and don't really want to support complex commands in validate as there's a lot that can go wrong with shell code and validate is very simple in comparison.  For instance, pipelines can succeed in unexpected ways in /bin/sh:

```
$ /bin/sh -c '/bin/false| /bin/true'       
$ echo $?
0
```

The above can be remedied in bash by setting the pipefail option but this and other intricacies of shell code cause us to tell people to use validate for simple invocation and write a script that you can then run validate on if there are more complex things you need.  For instance, you can generate the script with just one extra copy call and take care of the pipe exit code problem using something like this:

```
---
- hosts: localhost
  tasks:
  - copy:
      content: "#!/bin/bash\nset -o pipefail\nvalidate_command $@|grep -q 'passing'\n"
      dest: "~/tmp/validate_copy"
      mode: 0755
  - copy:
      src: "config"
      dest: "~/tmp/configfile"
      validate: "~/tmp/validate_copy %s"
```

In Ansible 2.0 we added blocks.  You can use the error handling mechanism in blocks to do this as well although for your use case i'd recommend the script approach over using blocks (as the block example is much longer and you don't need any of the playbook modules in this case, you can do it all with your validate_command and grep.):

```
---
- hosts: localhost
  tasks:
  - block:
    - copy:
        src: "config"
        dest: "~/tmp/configfile"
        backup: True
      register: initial_copy
    - shell: "set -o pipefail && validate_command ~/tmp/configfile | grep -q 'passing'"
      args:
        executable: /bin/bash

    rescue:
    - copy:
        src: "{{initial_copy['backup_file']}}"
        dest: "~/tmp/configfile"
      when: "{{'backup_file' in initial_copy}}"
    - file:
        path: "~/tmp/configfile"
        state: absent
      when: "{{'backup_file' not in initial_copy}}"

    always:
    - file:
        path: "{{initial_copy['backup_file']}}"
        state: absent
      when: "{{'backup_file' in initial_copy}}"
```
