### ISSUE TITLE
shell: creates or removes useless with with_items

### ISSUE THREAD

**Issue by ghost** [ansible/ansible-modules-core#2624]
##### ISSUE TYPE

Bug Report
##### COMPONENT NAME

shell
##### ANSIBLE VERSION

N/A
##### SUMMARY

shell core module stops when the first creates or removes
is hit this even if you are using with_items. This is useless.

You should change this so it continues the evaluation
of creates and removes for each items in with_items array.

```
  - name: enable apache sites
    action: shell a2ensite {{item}}
    args:
      creates: '/etc/apache2/sites-enabled/{{item}}.conf'
    with_items:
      - site1
      - site2
      - site3
      - site4
    notify:
      - reload apache
    tags: sites
```

At this point the alternative to the above code is to duplicate shell
4 times with shell or create the link with file module...

**Comment by ghost** [comment]
```
  - name: enable php db2 modules
    action: shell php5enmod -s ALL {{item}}
    args:
      creates: /etc/php5/cli/conf.d/60-{{item}}.ini
    with_items:
      - ibm_db2
      - pdo_ibm
    notify:
      - restart apache
```

Same problem here creates is useless as it will stop after ibm_db2
if you want to enable php modules for both cli and fpm without 
using shell you need to create multiple links with file module...
