### ISSUE TITLE
starting a non-existing service results in "ok"

### ISSUE THREAD

**Issue by bitmensch** [ansible/ansible-modules-core#2642]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible@devel
##### Ansible Configuration:

no changes
##### Environment:

Mac OS X 10.11.1
##### Summary:

Starting a non-existing service results in "ok".
##### Steps To Reproduce:

E.g. running the following play against ubuntu:trusty without having `nginx` installed:

```
- hosts: default
  tasks:
    - name: start nginx service
      service:
        name: nginx
        state: started
```
##### Expected Results:

The task would be expected to fail as it cannot start the service.

I could understand when such a task would not fail when stopping a non-existing service, but I would definitely consider this a bug when I want to ensure that a service has been started (but is not actually started due to its non-existence).
##### Actual Results:

```
ok: [default] => {"changed": false, "exists": false, "invocation": {"module_args": {"name": "nginx", "state": "started"}, "module_name": "service"}}
```
