### ISSUE TITLE
Error when using URI module to send JSON body with variables - TypeError: must be string or buffer, not dict

### ISSUE THREAD

**Issue by lancehudson** [ansible/ansible-modules-core#265]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7.2
##### Environment:

centos 7
python 2.7.5
##### Summary:

I am getting a TypeError when attempting to send a JSON body in a URI POST that is using a variable.
##### Steps To Reproduce:

run this playbook - https://gist.github.com/lancehudson/3e7e15b2a11f6cc4b4eb#file-playbook-fails

```
bash-4.2$ ansible-playbook -vvvv -i hosts playbook-fails.yml --connection=local
```
##### Expected Results:

no error, post being sent.
##### Actual Results:

Error: TypeError: must be string or buffer, not dict

https://gist.github.com/lancehudson/3e7e15b2a11f6cc4b4eb#file-error
##### Other:

If I hardcode the response it works: https://gist.github.com/lancehudson/3e7e15b2a11f6cc4b4eb#file-playbook-hardcoded

As soon as I introduce an error it fails with the same error: https://gist.github.com/lancehudson/3e7e15b2a11f6cc4b4eb#file-playbook-fails-2

**Comment by flisky** [comment]
Cross reference:
ansible/ansible#9472

Root analysis:
the varname goes through `utils.safe_eval` in template function from "lib/ansible/utils/template.py", and as it succeeds, which converts our json str **back** into a dict.

Dirty hack:
any way to make `safe_eval` fail, such as adding a key with value 'null'.

So can we fix it?

**Comment by dkerwin** [comment]
:+1: Fix would be highly appreciated. Impossible to use variables in uri's json body

**Comment by clickfreak** [comment]
:+1:

**Comment by tomwidmer** [comment]
Does anyone have a workaround for this? Does loading the json from a file using a lookup help? Anything else? Thanks.

**Comment by flisky** [comment]
@tomwidmer, please see my comment "Dirty hack".

**Comment by evgeny-goldin** [comment]
:+1:

**Comment by wybczu** [comment]
:+1:

**Comment by olvesh** [comment]
Imho a better workaround: 

``` yaml
  - name: post stuff in var 'service_body' to uri
    command: >
      curl -XPOST  -d '{{ service_body | to_json }}' http://example.com/rest/service
```

(although it might need some tweaking if you need it to fail on e.g. a 404)

**Comment by smiller171** [comment]
:+1:

This is a real problem for me.

**Comment by smiller171** [comment]
I tried templating the json into a file and templating it into a var, no dice.

**Comment by swordeh** [comment]
+1 on this issue. I'd like to use uri for some CouchDB work, as using command to curl it instead feels a bit pointless if uri could do it.

**Comment by anandnalya** [comment]
:+1:

**Comment by airandfingers** [comment]
+1

**Comment by sbocahu** [comment]
+1

**Comment by sbocahu** [comment]
I propose #1011

**Comment by aioue** [comment]
+1

**Comment by aioue** [comment]
+1 @flisky do you have an example of the hack please?

**Comment by flisky** [comment]
```
---
- hosts: all
  vars:
    body:
      _hack: null  # an extra key with null value, which fails `utils.safe_eval`

  tasks:
    - uri:
        url: "http://httpbin.org/get"
        HEADER_Content-Type: "application/json"
        body: "{{ body | to_json }}"
```
