### ISSUE TITLE
ACL module doesn't report return code in some cases

### ISSUE THREAD

**Issue by jan-warchol** [ansible/ansible-modules-core#2650]
##### Issue Type:

Bug Report
##### Component Name:

acl module
##### Ansible Version:

ansible 1.9.4
##### Ansible Configuration:

default.
##### Environment:

N/A
##### Summary:

Usually modules include return code in their results.  In case of ACL module, the return code seems to be included only in some cases.  This is a problem because I cannot write a conditional that uses return code.  For example, if I try to add `failed_when: task_result.rc == 1` I get

```
error while evaluating conditional: task_result.rc == 1
```
##### Steps To Reproduce:

Here's an example playbook:

``` yaml
- hosts: localhost
  tasks:
    - name: test acl
      acl:
        path: "{{ item }}"
        entity: "{{ ansible_env.USER }}"
        etype: user
        permissions: r
        state: present
      with_items:
        - ~/.bashrc  # an existing path
        - /some/nonexisting/path
        - /etc/shadow  # existing path that I don't have access to
      register: task_result
      ignore_errors: yes

    - debug: var=task_result
```
##### Expected Results:

I would expect that the result for the first item contains `"rc": 0`, and for the second and third item `"rc": 1`.  
##### Actual Results:

As you can see `rc` key is only included in third case.

``` json
TASK: [debug var=task_result] ************************************************* 
ok: [localhost] => {
    "var": {
        "task_result": {
            "changed": true, 
            "failed": true, 
            "msg": "One or more items failed.", 
            "results": [
                {
                    "acl": [
                        "user::rw-", 
                        "user:codilime:r--", 
                        "group::r--", 
                        "mask::r--", 
                        "other::r--"
                    ], 
                    "changed": true, 
                    "invocation": {
                        "module_args": "", 
                        "module_complex_args": {
                            "entity": "codilime", 
                            "etype": "user", 
                            "path": "~/.bashrc", 
                            "permissions": "r", 
                            "state": "present"
                        }, 
                        "module_name": "acl"
                    }, 
                    "item": "~/.bashrc", 
                    "msg": "user:codilime:r-- is present"
                }, 
                {
                    "failed": true, 
                    "invocation": {
                        "module_args": "", 
                        "module_complex_args": {
                            "entity": "codilime", 
                            "etype": "user", 
                            "path": "/some/nonexisting/path", 
                            "permissions": "r", 
                            "state": "present"
                        }, 
                        "module_name": "acl"
                    }, 
                    "item": "/some/nonexisting/path", 
                    "msg": "path not found or not accessible!"
                }, 
                {
                    "cmd": "/usr/bin/setfacl -m user:codilime:r-- /etc/shadow", 
                    "failed": true, 
                    "invocation": {
                        "module_args": "", 
                        "module_complex_args": {
                            "entity": "codilime", 
                            "etype": "user", 
                            "path": "/etc/shadow", 
                            "permissions": "r", 
                            "state": "present"
                        }, 
                        "module_name": "acl"
                    }, 
                    "item": "/etc/shadow", 
                    "msg": "setfacl: /etc/shadow: Operation not permitted", 
                    "rc": 1, 
                    "stderr": "setfacl: /etc/shadow: Operation not permitted\n", 
                    "stdout": "", 
                    "stdout_lines": []
                }
            ]
        }
    }
}
```
