### ISSUE TITLE
IAM module: Managed policies

### ISSUE THREAD

**Issue by ejoubaud** [ansible/ansible-modules-core#2688]
**Issue Type:** 
Feature Idea

**Summary:** 
Support managed policies. Currently, only inline policies are supported, making it impossible to link a policy to several groups/users/roles. I reckon in the meantime this limitation could be made clearer in the doc.

**Comment by wimnat** [comment]
I'm working on new IAM modules (iam_user, iam_group, iam_role) which addresses this, targeting 2.1

**Comment by ejoubaud** [comment]
Awesome :+1:

For now I'm addressing this with the `cloudformation` module and a CF template creating the policy, which does the job, but doesn't let me set the name for the policies, so I have to create any role/group that depends on that policy in the same json template, which is not a huge improvement over inline policies. That's a limitation Ansible can eventually beat CloudFormation on :)

**Comment by therc** [comment]
@wimnat will iam_role support create_role's assume_role_policy_document argument? Should I file an issue for that?

**Comment by wimnat** [comment]
No need to file an issue.  Once it's available for testing i'll let you know so you can leave feedback on the PR.  It will support the role_policy_document.

**Comment by Constantin07** [comment]
+1

**Comment by stephanadler** [comment]
+1

**Comment by slok** [comment]
+1

**Comment by mykola42** [comment]
+1

**Comment by matthewrkrieger** [comment]
+1

**Comment by wimnat** [comment]
First draft not in PR yet but feel free to provide feedback - https://github.com/wimnat/ansible-modules-extras/tree/feature/iam_role

I know that the policy loading from a lookup() wont work.  I currently have a question open regarding this as it's broken other modules as well.  As a workaround you'll have to just write the json manually as a string 

https://groups.google.com/forum/#!topic/ansible-devel/2C7pl2_kxlY

**Comment by nagas** [comment]
+1

**Comment by wimnat** [comment]
https://github.com/ansible/ansible-modules-extras/pull/2201

**Comment by westover** [comment]
Did this make it into 2.1? Docs aren't super clear

**Comment by wimnat** [comment]
@westover nope. No new iam modules for 2.1

**Comment by hirotaka-iijima** [comment]
+1

**Comment by dhruvbansal** [comment]
+1

Once this is working, it'd be nice to be able to associate IAM managed policies to users/groups/roles by using their names:

``` yaml
- name: Ensure managed IAM policy exists
  iam_policy:
    policy_name: my_policy
    policy_document: "/some/complex/policy.json" # or use policy_string, whatever
    state: present
    # Without `iam_type` and `name` assume we are talking
    # about a managed policy.

- name: Ensure resource has managed IAM policy
  iam_policy:
    iam_type: user  # or group, role
    name: my_resource
    policy_name: my_policy
    state: present
    # Without any further fields, "my_policy" should be resolved as the
    # managed IAM policy defined above.
    #
    # We should still be able to add `policy_string` or 
    # `policy_document` fields and recover the original behavior
    # of using an embedded policy.
```

It would also be nice to be able to refer to managed IAM policy by name in the `iam` module, as well:

``` yaml
- name: Ensure resource and managed IAM policy
  iam:
    iam_type: group
    name: "my_resource"
    state: present
    trust_policy: "my_policy"
```

Even better would be if I could do all of the above with the pre-canned policies AWS gives you (`AdministratorAccess`, `AmazonS3FullAccess`, &c.).

Good luck to you, @wimnat
