### ISSUE TITLE
docker log_opt ignored if log_driver is not specified

### ISSUE THREAD

**Issue by leedm777** [ansible/ansible-modules-core#2700]
##### ISSUE TYPE

Bug Report
##### COMPONENT NAME

_docker module
##### ANSIBLE VERSION

N/A
##### SUMMARY

Even though the `log_driver` defaults to `json-file`, if you do not explicitly put `log_driver: 'json-file'` in a task, it will not use the specified `log_opt`.
### Environment

docker: 1.9.1
docker-py: 1.5.0
ansible: 2.0.0-0.7.rc2 
### Steps to reproduce
1. Configure a container
   
   ``` yaml
   - name: test container
   docker:
     name: tmp
     image: busybox
     command: 'tail -f /dev/null'
     #log_driver: 'json-file'
     log_opt:
       max-size: '100m'
       max-file: '5'
     # Workaround for https://github.com/ansible/ansible-modules-core/issues/1885
     net: default
   tags: tmp
   ```
2. Deploy it
   
   ``` bash
   $ ansible-playbook -v --tags tmp -- site.yml
   ```
3. Inspect the log settings
   
   ``` bash
   $ docker inspect --format '{{json .HostConfig.LogConfig }}'  tmp
   ```
### Expected output

Step 3 should return the log config, with max-files and max-size set.

``` json
{"Type":"json-file","Config":{"max-file":"5","max-size":"100m"}}
```
### Actual output

In step 3, the container's log config is missing.

``` json
{"Type":"json-file","Config":{}}
```
