### ISSUE TITLE
feature request: support running scripts with custom interpreters

### ISSUE THREAD

**Issue by ghost** [ansible/ansible-modules-core#2704]
Ansible's shell module comes very useful at running shell snippets. However, it does not support running a snippet scripted in another language, say, Perl or Python, or even `sed` and `awk`.

One could for sure implement a workaround like:

``` yaml
- name: run a Perl command
  shell: |
    perl -e '
      ...
      print "Hello, world!\n";
      ...
    '
```

But a much cleaner way would be to have something like:

``` yaml
- name: run a Perl command
  shell: shebang="perl -e"
  script: |
    ...
    print "Hello, world!\n";
    ...
```
