### ISSUE TITLE
unarchive permission issues with become and http src

### ISSUE THREAD

**Issue by gregsidelinger** [ansible/ansible-modules-core#2708]
##### ISSUE TYPE

Bug Report
##### COMPONENT NAME

unarchive module
##### ANSIBLE VERSION

N/A
##### SUMMARY

The unarchive module does not appear to honor become permissions when downloading a remote file.  It looks like the module tries to download the file to ansible tmp directory as the become_user however that user does not have permissions to write there since they are owned by the user ansible is running as. It only appears to work when become_user is root.

Here is an example from my playbook that fails.

```
- name: Extract Zip
  unarchive: src=http://someserver.com/files/zipfile.zip dest=/opt/exploded copy=no
  become: yes
  become_user: user2
```

**Comment by Jmainguy** [comment]
using latest 2.1 devel, I am unable to reproduce this. Can you reproduce this on latest devel?

**Comment by gregsidelinger** [comment]
Yes the bug still exists in the 2.1 devel branch.

Here is the error message I get.

```
TASK [Extract Zip] *************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failure downloading https://github.com/ansible/ansible-modules-core/archive/devel.zip, [Errno 13] Permission denied: '/tmp/ansible-tmp-1451356456.51-72820795886431/devel.zip'"}
```

Here is my test playbook which I ran on a pretty vanilla CentOS 7.1 system.  I created two local users, user1 and user2.  Granted user1 full sudo access in /etc/sudoers and setup a ssh key.

The playbook works fine if I unarchive the files as root because root is able to write to the ansible tmp directory unlike user2. 

```
---
- name: Reproduce bug 2708
  hosts: localhost
  remote_user: user1

  tasks:
    - name: Create /opt/exploded
      file: path=/opt/exploded owner=user2 state=directory
      become: yes
      become_user: root

    - name: Extract Zip
      unarchive: src=https://github.com/ansible/ansible-modules-core/archive/devel.zip dest=/opt/exploded copy=no
      become: yes
      become_user: user2
```

I did submit a patch last week to get around the issue of the module using the ansible tmp dir to download the file too.
