### ISSUE TITLE
lineinfile - validate forces "%s" to be present into string

### ISSUE THREAD

**Issue by fpeterschmitt** [ansible/ansible-modules-core#2757]
o Issue Type: Feature Idea
o Ansible Version: 1.9.4
o Environment: GNU/Linux

Hi,

In `lineinfile` module, the `validate` parameters checks for `%s` to be present in the command, passing the configuration file into it.

But many commands doesn't need the configuration file at all.

Here is my example:

``` yaml
$ cat roles/postfix/tasks/configure.yml

---
- name: configure postfix
  lineinfile:
    dest: '/etc/postfix/main.cf'
    regexp: '^relayhost.*'
    line: "relayhost = {{ postfix_relayhost }}"
    validate: 'postfix check #%s'
  when: "postfix_relayhost != False"
  notify: restart postfix
```

I workaround this requirement by inserting `#` before `%s` so the shell just skip it.

Why not letting the choice of passing or not the file's path?
