### ISSUE TITLE
openstack module os_server - Error in creating instance

### ISSUE THREAD

**Issue by GqSteve** [ansible/ansible-modules-core#2797]
Hi,
I am using ansible v2.0.0-0.9.rc4 on a SLES 12:

admin:~/ansible> ansible --version
ansible 2.0.0
  config file = /home/admin/.ansible.cfg
  configured module search path = Default w/o overrides

When I use the os_server module, then I get different error messages....for similar playbooks, e.g.:

1st case - simple playbook with required parameters

```
- name: Setup TEST
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Launch the instance
      os_server:
        state: present
        name: TEST
        image: 814e4b80-e605-4047-a215-dfb342257648
        flavor: m1.large
```

Error:

```
TASK [Launch the instance] *****************************************************
fatal: [localhost]: FAILED! => {"changed": false, "extra_data": null, "failed": true, "msg": "Error in creating instance"}
```

2nd case (added the region_name & availability_zone) - both parameters have the right values

```
- name: Setup TEST
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Launch the instance
      os_server:
        state: present
        name: TEST
        region_name: RegionOne
        availability_zone: nova
        image: 814e4b80-e605-4047-a215-dfb342257648
        flavor: m1.large
```

Error:

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/home/admin/.ansible/tmp/ansible-tmp-1452606056.15-63569152229058/os_server", line 2645, in <module>
    main()
  File "/home/admin/.ansible/tmp/ansible-tmp-1452606056.15-63569152229058/os_server", line 598, in main
    _create_server(module, cloud)
  File "/home/admin/.ansible/tmp/ansible-tmp-1452606056.15-63569152229058/os_server", line 460, in _create_server
    **bootkwargs
  File "<decorator-gen-6>", line 2, in create_server
  File "/usr/lib/python2.7/site-packages/shade/_utils.py", line 471, in func_wrapper
    "'{arg}'".format(f=inspect.stack()[1][3], arg=k))
TypeError: create_server() got an unexpected keyword argument 'region_name'

fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "os_server"}, "parsed": false}
```

3rd case - trying to set the region_one parameter to a wrong value

```
- name: Setup TEST
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Launch the instance
      os_server:
        state: present
        name: TEST
        region_name: RegionTwo
        availability_zone: nova
        image: 814e4b80-e605-4047-a215-dfb342257648
        flavor: m1.large
```

Error:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: os_client_config.exceptions.OpenStackConfigException: Region RegionTwo is not a valid region name for cloud envvars. Valid choices are RegionOne. Please note that region names are case sensitive.
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "parsed": false}
```

Btw, os_auth, os_server_facts are working great.....

**Comment by jsidhu** [comment]
I'm observing the same behavior on  "ansible 2.0.0.1"

I had some time to finally look into this and looks likethe bug is with the shade library, see commit: https://github.com/openstack-infra/shade/commit/684b8b69290d5df1f494a1d2979f06566800ce5f

region_name should be added to @_utils.valid_kwargs

**Comment by GqSteve** [comment]
I updated to "ansible 2.0.0.2", added manually the region_name to @_utils.valid_kwargs in shade/openstackcloud.py => now the error in the 2nd case described above is gone ... ok so far!

Creating an instance using the os_server module is still not working using the playbooks from 1st & 2nd case, the error is stl the same:
`fatal: [localhost]: FAILED! => {"changed": false, "extra_data": null, "failed": true, "msg": "Error in creating instance"}`

When the nics parameter is added to the os_server module, then it works:

```
- name: Setup TEST
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Launch the instance
      os_server:
        state: present
        name: TEST
        image: 814e4b80-e605-4047-a215-dfb342257648
        flavor: m1.large
        nics:
            - net-id: 00d39765-718d-43c3-9568-6c73d4bb3752
```

@jsidhu : Thank you!

**Comment by eagleson** [comment]
I think that shade is correct and region_name is not a valid argument for novaclient.server.create.  Removing region_name from the optional_param list in os_server.py seems to fix this issue.

**Comment by vladah** [comment]
Hello, can you please specify which version of shade you are using. When I try to create a vm on openstack using os_server an exception is thrown but the vm get launched and is accessible. 

https://github.com/ansible/ansible-modules-core/issues/2901

**Comment by GqSteve** [comment]
@vladah Hello. It's 1.4

**Comment by vladah** [comment]
After upgrading the shade to 1.4.0 I got the same error:

TypeError: create_server() got an unexpected keyword argument 'region_name'

After removing the region_name, the instance was created although the job was reported as failed:
"msg": "Timeout waiting for the floating IP to be attached. (Inner Exception: No module named systemd)"}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1

Vlad

**Comment by sivel** [comment]
cc @Shrews @emonty

**Comment by Shrews** [comment]
So having region_name as a parameter is a bug. Region should come from either your clouds.yaml file or from your OpenStack environment variables. I'll submit a patch to remove that.

As for the other mentioned errors, we recently patched shade to fix the timeout value not being passed through to attaching the floating IP. This should be released (probably 1.5.0) very soon.

Also, the latest version of the Ansible modules now output more error information when something goes wrong, so you'll see more info than just "Error in creating instance". That may help us figure out what the deal is with the error when not using the 'nics' parameter.

**Comment by Shrews** [comment]
A caveat: If you're specifying the auth parameters in the playbook, region_name is acceptable, but it shouldn't be passed through to the create_server() call.

**Comment by vladah** [comment]
Hi David,

Thanks for the update.

Vlad

**Comment by vladah** [comment]
Hi David,

I've upgraded the python shade to 1.5.1 and the timeout error doesn't
appear anymore. Now when I launch a vm the task is executed correctly but
the response just hangs. I need to press CTRL + C to get the status of the
job:

[root@vm2 ~]# ansible-playbook launch-ubuntu1204-vm-test.yml

PLAY [launch a vm]

---

TASK [setup]

---

ok: [localhost]

TASK [launch an instance]

---

^C
PLAY RECAP

---

localhost                  : ok=1    changed=0    unreachable=0    failed=0

On the other hand deleting the vm ( just state changed to absent) gives a
response back.

[root@vm2 ~]# ansible-playbook delete-ubuntu1204-vm-test.yml

PLAY [launch a vm]

---

TASK [setup]

---

ok: [localhost]

TASK [launch an instance]

---

changed: [localhost]

PLAY RECAP

---

localhost                  : ok=2    changed=1    unreachable=0    failed=0

Here's the yml file to launch a vm:

---
- name: launch a vm
  hosts: localhost
  tasks:
  - name: launch an instance
    os_server:
      state: present
      auth:
        auth_url: http://10.26.253.15:5000/v2.0
        username: admin
        password: secret123
        project_name: VladVMs
      name: vm-test
      #region_name: RegionOne
      availability_zone: tlapp13
      image: 7312030c-51a8-41d4-973c-4b700d8cdfd7
      #key: /tmp/cloud.key
      key_name: cloud-key-pub
      #timeout: 1000
      flavor: 4
      security_groups: default
      nics:
        - net-id: d3d5e30d-d74a-4426-b400-18737749cf8c
      floating_ip_pools:
        - VN-A-Floats
    ...

Thanks,

Vladimir

**Comment by Shrews** [comment]
How long did you wait?

The default is to wait for the server to reach ACTIVE state. It will wait 3 minutes, by default. You can disable this behavior by setting 'wait' to False in your task, or lower the time by setting 'timeout' to the number of seconds you wish to wait.

**Comment by vladah** [comment]
Hi David,

I think I waited more than 3min. Strangely enough when I ran this from
another newly built ansible host with shade 1.5 the timeout error appeared
again. I'll repeat the test once I've kilo up and running. At the moment
rebuilding the setup.

Vlad

**Comment by GqSteve** [comment]
I've been testing my scripts up to ansible 2.0.1.0 & shade 1.6.2 and everything still works fine.

Thank you for your support!

**Comment by HasmukhDalsaniya** [comment]
Hi,
I'm using "os_floating_ip" module to assign FIP and facing timeout issues consistently however the instance is assigned the FIP when I check it on horizon dashboard.

The timeout is set to 10 mins (for test purpose) and it keeps waiting for 10 minutes and reports below error:

TASK [provision : Assign floating IP] ******************************************
fatal: [localhost]: FAILED! => {"changed": false, "extra_data": null, "failed": true, "msg": "Timeout waiting for the floating IP to be attached. (Inner Exception: No module named systemd)"}

Appreciate your comments.

**Comment by kamsz** [comment]
@Shrews I'm still experiencing this issue - virtual machines are not getting floating ips assigned (task finished with changed=true). Floating ip is also not being defined in output json (either in os_server and os_floating_ip). Using shade 1.7.

**Comment by GqSteve** [comment]
@HasmukhDalsaniya @kamsz 
Our cloud assigns ip's from corporate network and therefore I can't test the issue regarding the floating ip's. Anyway I reopened this bug.

**Comment by HasmukhDalsaniya** [comment]
Thanks @GqSteve for taking it up.

Below are the combinations of packages installed on my Ansible controller VM:

ANSIBLE:
-bash-4.2$ ansible --version
ansible 2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = None

SHADE:
-bash-4.2$ pip list installed | grep shade
shade (1.7.0)
You are using pip version 8.0.2, however version 8.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

Openstack Clients:
msgpack-python (0.4.7)
python-cinderclient (1.6.0)
python-designateclient (2.1.0)
python-glanceclient (2.0.0)
python-heatclient (1.1.0)
python-ironicclient (1.3.0)
python-keystoneclient (2.3.1)
python-neutronclient (4.1.2)
python-novaclient (3.4.0)
python-openstackclient (2.3.0)
python-swiftclient (3.0.0)
python-systemd (0.0.9)
python-troveclient (2.2.0)

As you mentioned earlier, do you see that it's problem with specific version of Ansible/Shade and combination. 

Can you please suggest the latest Ansible & shade combination that you validated and found to be working?

**Comment by Shrews** [comment]
@HasmukhDalsaniya Thanks for the details. Who is your cloud provider?

**Comment by Shrews** [comment]
@kamsz Same question to you: Who is your cloud provider?

**Comment by kamsz** [comment]
As for my setup:

```
os-client-config (1.17.0)
python-cinderclient (1.6.0)
python-glanceclient (2.0.0)
python-heatclient (1.1.0)
python-ironicclient (1.3.0)
python-keystoneclient (2.3.1)
python-neutronclient (4.1.2)
python-novaclient (3.4.0)
python-openstackclient (2.3.0)
python-swiftclient (3.0.0)
python-troveclient (2.2.0)
shade (1.7.0)
```

And latest Ansible from devel.

@Shrews I've Mirantis OpenStack 6.1 (that's Juno) installed if that's what you're asking about (was not sure).

**Comment by emonty** [comment]
Hi! I've seen a problem that looks like this on one cloud - I'm starting to think it's a bug in Juno, but haven't been able to prove that yet. In any case ... the way shade creates and attaches floating ips is to get the port of the fixed ip of the server, and then pass that to the floating ip constructor. We do this because it's the best way to avoid race conditions with creation and re-use of floating ips in high concurrency environments.

However, in Juno, it seems that when you create and attach the floating ip this way purely from neutron, nova does not see it. So if you go and look at the floating ip in neutron, it'll show attached - and you can probably ssh in to the server using it... it just won't show up in the server record.

Can you try adding "has_network: False" to the cloud entry in your clouds.yaml? So like this:

```
clouds:
  tripleo-test-cloud-rh1:
    auth:
      username: 'openstack-nodepool'
      password: 'redacted'
      project_name: 'openstack-nodepool'
      auth_url: 'https://ci-overcloud.rh1.tripleo.org:13000/v2.0'
    has_network: False
```

And see if it works? It's a big sledgehammer that will break other neutron things - but if it works, it lets us know the hypothesis is correct at least and we can think about fixes
