### ISSUE TITLE
add_host overwrites instead of updating existing hosts

### ISSUE THREAD

**Issue by yfried** [ansible/ansible-modules-core#2799]
##### Issue Type:
- Bug Report
##### Ansible Version:

ansible 2.0.0
##### Environment:

Fedora 23
##### Summary:

Invoking add_host a second time for the same host will overwrite host data instead of only updating it like in 1.9
##### Steps To Reproduce:

``` yaml

- name: add the host
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create host
      add_host:
          name: myhost
          groups: group1, group2
          ansible_user: user1
          ansible_ssh_private_key_file: /path/to/id_rsa
          ansible_host: 1.2.3.4
    - name: initial
      debug: var=hostvars["myhost"].ansible_user

    - name: update host
      add_host:
          name: myhost
          ansible_host: 10.20.30.40
    - name: updated
      debug: var=hostvars["myhost"].ansible_user

```
##### Expected Results:

```

TASK [initial] *****************************************************************
ok: [localhost] => {
    "hostvars[\"myhost\"].ansible_user": "user1"
}

TASK [update host] *************************************************************
changed: [localhost]

TASK [updated] *****************************************************************
ok: [localhost] => {
    "hostvars[\"myhost\"].ansible_user": "user1"
}

```

Actual 1.9 results:

```
TASK: [initial] *************************************************************** 
                       [[ previous task time: 0:00:00.010173 = 0.01s / 0.04s ]]
ok: [localhost] => {
    "var": {
        "hostvars[\"myhost\"].ansible_user": "user1"
    }
}


TASK: [updated] *************************************************************** 
                       [[ previous task time: 0:00:00.007457 = 0.01s / 0.06s ]]
ok: [localhost] => {
    "var": {
        "hostvars[\"myhost\"].ansible_user": "user1"
    }
}

```
##### Actual Results:

```

TASK [initial] *****************************************************************
ok: [localhost] => {
    "hostvars[\"myhost\"].ansible_user": "user1"
}

TASK [update host] *************************************************************
changed: [localhost]

TASK [updated] *****************************************************************
ok: [localhost] => {
    "hostvars[\"myhost\"].ansible_user": "VARIABLE IS NOT DEFINED!"
}

```
