### ISSUE TITLE
Ansible 2.0 cloudformation module template path

### ISSUE THREAD

**Issue by p53** [ansible/ansible-modules-core#2819]
##### ISSUE TYPE

Bug Report
##### COMPONENT NAME

cloudformation module
##### ANSIBLE VERSION

```
>1.9
```
##### SUMMARY

I have in template this, it worked in ansible 1.9:

```
- name: Create Virginia VPC
  register: vir_vpc_info
  cloudformation:
    stack_name: "virginia"
    state: "{{ presence }}"
    region: "{{ aws_region }}"
    disable_rollback: true
    template: roles/infra_virginia_vpc/files/network-stack.json
    template_parameters:
        AvailZone1: "{{ aws_region }}c"
        AvailZone2: "{{ aws_region }}d"
        VPCCIDR: "10.1.0.0/16"
        ProdSubnetCIDR: "10.1.0.0/24"
        BackupSubnetCIDR: "10.1.1.0/24"
    tags:
      Stack: "virginia"
```

I am getting this error when i run ansible when my current working directory is outside of my ansible playbooks directory:

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/home/ansible/.ansible/tmp/ansible-tmp-1452850575.64-81158748898401/cloudformation", line 2566, in <module>
    main()
  File "/home/ansible/.ansible/tmp/ansible-tmp-1452850575.64-81158748898401/cloudformation", line 273, in main
    template_body = open(module.params['template'], 'r').read()
IOError: [Errno 2] No such file or directory: 'roles/infra_virginia_vpc/files/network-stack.json'

fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "cloudformation"}, "parsed": false}
```

```
ansible@karamba:/home/karamba$ pwd
/home/karamba
ansible@karamba:/home/karamba$ 

ansible@karamba:/home/karamba$ ls -ald karamba
drwxrwxr-x 12 karamba karamba 4096 Jan 14 13:28 ansible
ansible@karamba:/home/karamba$ 
```

when i switch to ansible directory:

```
ansible@karamba:/home/karamba/ansible$ pwd
/home/karamba/ansible
ansible@karamba:/home/karamba/ansible$ ls -al /home/karamba/ansible
total 208
drwxrwxr-x 12 karamba karamba  4096 Jan 14 13:28 .
drwxr-xr-x 79 karamba karamba  4096 Jan 14 15:01 ..
drwxrwxr-x  9 karamba karamba  4096 Mar  3  2015 dummy_role
-rw-rw-r--  1 karamba karamba   101 Apr  7  2015 exim4.yml
-rw-rw-r--  1 karamba karamba  3620 Dec  9 08:11 exper.yml
drwxrwxr-x  2 karamba karamba  4096 Mar  3  2015 filter_plugins
drwxrwxr-x  7 karamba karamba  4096 Jan 15 08:50 .git
drwxrwxr-x  2 karamba karamba  4096 Jan 15 08:50 group_vars
drwxrwxr-x  2 karamba karamba  4096 Dec 22 11:00 host_vars
-rw-rw-r--  1 karamba karamba 21972 Dec 11 13:27 infrastructure.yml
drwxrwxr-x  2 karamba karamba  4096 Dec 22 11:00 inventories
drwxrwxr-x  2 karamba karamba  4096 Mar  3  2015 library
-rw-rw-r--  1 karamba karamba    61 Mar  3  2015 LICENSE
-rw-rw-r--  1 karamba karamba    53 Mar  3  2015 README
drwxrwxr-x 65 karamba karamba  4096 Dec 15 08:58 roles
drwxrwxr-x  2 karamba karamba  4096 Jan 14 08:21 vault
-rw-rw-r--  1 karamba karamba  2621 Jan 13 13:25 zabbix_1.0_prod.yml
-rw-rw-r--  1 karamba karamba  1098 Apr 22  2015 zabbix_client.yml
```
