### ISSUE TITLE
synchronize broken in ansible 2.0 when setting ansible_ssh_port

### ISSUE THREAD

**Issue by tetherit** [ansible/ansible-modules-core#2831]
I have this host in my inventory:

```
vagrant_timebox       ansible_ssh_host=127.0.0.1 ansible_ssh_port=2231
```

I have this in my playbook:

```
- name: Copy video packages to server
  synchronize:
    src: "packages/Ubuntu-15.04/amd64/fdk-aac_latest_amd64.deb"
    dest: "/data/fdk-aac_latest_amd64.deb"
```

The above used to work in Ansible 1.9, but now it tries to copy the package to the same machine running Ansible, rather than the target machine (VirtualBox) on 127.0.0.1:2231

The verbose output looks like this:

```
TASK [timebox : Copy video packages to server] *********************************
failed: [vagrant_timebox] => (item=fdk-aac_latest_amd64.deb) => {"cmd": "rsync --delay-updates -F --compress --archive --rsh 'ssh  -S none -o StrictHostKeyChecking=no -o Port=2231' --partial --out-format='<<CHANGED>>%i %n%L' \"/Users/Hackeron/Development/test-ansible/roles/testrole/files/packages/Ubuntu-15.04/amd64/fdk-aac_latest_amd64.deb\" \"/data/fdk-aac_latest_amd64.deb\"", "failed": true, "item": "fdk-aac_latest_amd64.deb", "msg": "rsync: change_dir#3 \"/data\" failed: No such file or directory (2)\nrsync error: errors selecting input/output files, dirs (code 3) at main.c(746) [Receiver=3.1.1]\n", "rc": 3}
```

Any ideas?

Note: If I use "copy" instead of "synchronize", it works. But I need synchronize for performance reasons and for recursive copy. I have also tried this and the results are the same:

```
- name: Copy video packages to server
  synchronize:
    partial: true
    use_ssh_args: false
    verify_host: false
    dest_port: "{{ ansible_ssh_port }}"
    src: "package.deb"
    dest: "/data/package.deb"
```
