### ISSUE TITLE
synchronize ignores "connection: chroot"

### ISSUE THREAD

**Issue by tetherit** [ansible/ansible-modules-core#2832]
I have this in my playbook:

```
roles:
    - { role: common, connection: chroot, tags: [ 'minimal' ] }
```

I have this task in the main.yml file:

```
- name: Test synchronize
  synchronize:
    src: "/bin/bash"
    dest: "/tmp/testsync.tmp"
```

When I run with -vvvvv I see the following:

```
TASK [common : Test synchronize] ***********************************************
task path: /data/deployer/xanview-ansible/roles/common/tasks/main.yml:1
ESTABLISH LOCAL CONNECTION FOR USER: root
/data/timebox-bootstrap EXEC mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1453131421.7-90474567189480 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1453131421.7-90474567189480 )"
/data/timebox-bootstrap PUT /tmp/tmpyWDYuc TO /home/deployer/.ansible/tmp/ansible-tmp-1453131421.7-90474567189480/synchronize
/data/timebox-bootstrap EXEC LANG=en_GB.UTF-8 LC_ALL=en_GB.UTF-8 LC_MESSAGES=en_GB.UTF-8 /usr/bin/python /home/deployer/.ansible/tmp/ansible-tmp-1453131421.7-90474567189480/synchronize; rm -rf "/home/deployer/.ansible/tmp/ansible-tmp-1453131421.7-90474567189480/" > /dev/null 2>&1
fatal: [testhostname]: FAILED! => {"changed": false, "cmd": "rsync --delay-updates -F --compress --archive --rsh 'ssh  -S none -o StrictHostKeyChecking=no' --out-format='<<CHANGED>>%i %n%L' \"/bin/bash\" \"root@testhostname:/tmp/testsync.tmp\"", "failed": true, "invocation": {"module_args": {"_local_rsync_path": "rsync", "archive": true, "checksum": false, "compress": true, "copy_links": null, "delete": false, "dest": "root@testhostname:/tmp/testsync.tmp", "dest_port": 22, "dirs": false, "existing_only": false, "group": null, "links": null, "mode": "push", "owner": null, "partial": false, "perms": null, "private_key": null, "recursive": null, "rsync_opts": null, "rsync_path": null, "rsync_timeout": 0, "set_remote_user": true, "src": "/bin/bash", "ssh_args": null, "times": null, "verify_host": false}}, "msg": "ssh: Could not resolve hostname testhostname: Name or service not known\r\nrsync: connection unexpectedly closed (0 bytes received so far) [sender]\nrsync error: unexplained error (code 255) at io.c(226) [sender=3.1.1]\n", "rc": 255}

PLAY RECAP *********************************************************************
icomply-tsi0001            : ok=0    changed=0    unreachable=0    failed=1   
```

It seems synchronize tries to use ssh instead of using the chroot path.

**Comment by abadger** [comment]
What did this do in 1.9.4?  This is actually not using the ssh connection plugin.  However, it's not using the chroot plugin either.  It's using the LOCAL plugin (That's what the "ESTABLISH LOCAL CONNECTION FOR USER: root" means).  The ssh that you see there is how rsync is going to talk to the remote host.

Unfortunately, rsync only knows how to copy via filesystem copy and over ssh.  So that portion of the transfer isn't something we have control over.

**Comment by tetherit** [comment]
I'm not sure I don't have 1.9.4 anymore. But what do you mean? - Rsync can copy to a path on the local server, it isn't limited to only talking to a remote host.

When setting connection: chroot, it shouldn't try to copy to a remote host, but rather just point to the chroot path just like all the other modules in ansible.

If the rsync module doesn't know which path to copy to, why do the other modules know? - isn't this something that should be exposed to the rsync module?

**Comment by abadger** [comment]
Other modules copy the files directly over the ansible connection.  synchronize creates the connection and then runs rsync to transfer the files.  So it cannot work.

**Comment by abadger** [comment]
Since rsync knows how to handle filessystem copying, you can specify a local synchronize rather than a remote one.  ie: don't use the chroot connection, chroot host, and filesystem path inside of the chroot.  Instead use local connection, localhost, and the filesystem path on the host system.

**Comment by tetherit** [comment]
I can't do that because I am sharing the same playbook with remote hosts and chroot hosts. If I set the connection to local, then it will not copy to the chroot path, it will try to overwrite files on the local host.

I would need to duplicate my playbook which would go against DRY and against the philosophy of Ansibles, no?

What do you mean by synchonize creates the connection? - It is using a local connection, so it just needs an if statement: if connection is "chroot" then copy to chroot_path:path, otherwise, copy to user@host:path. Why is this not possible?

**Comment by abadger** [comment]
Operating on the filesystem inside of the chroot from outside of it is not a safe thing for ansible to do in general.  For instance, symlinks can cause security issues as they can reference different files from inside and outside the chroot.

Some options for you:
- You can use copy instead of synchronize.  Since copy does not use rsync under the hood it should be able to cope with alternate methods of connecting to the host.
- If your environment allows it, you can use command with rsync to pull from the controller instead of pushing to it.

```
# rhel6-test is a bare metal host.  chroot-fedora21 is a chroot host
# the controller's accessible hostname is bastion
- hosts: chroot-fedora20:rhel6-test
  tasks:
  - command: "rsync bastion:/var/tmp/host /var/tmp/dest"
```
- You can put a public address for the controller into your inventory and do something similar:

```
# rhel6-test is a bare metal most.  chroot-fedora20 is a chroot host
# roan.lan is my controller
# synchronize is unique in that the host specified in hosts is always
# one end of the connection.  The controller or the host in delegate_to
# if specified is the other end.  So we have to use localhost in the hosts:
# field and change the delegate_to host to make this work.
- hosts: roan.lan
  vars:
    hosts:
      - rhel6-test
      - chroot-fedora20
  tasks:
  # This will run rsync on chroot-fedora21 and rhel6-test.  the rsync on those
  # hosts will copy the controller's /var/tmp/host file to /var/tmp/dest via rsync
  # with ssh
  - synchronize:
      src: /var/tmp/host
      dest: /var/tmp/dest
      mode: pull
    delegate_to: "{{ item }}"
    with_items: "{{ hosts }}"
```
- You can try to use rsync  to push but make use of variables to construct the path.  Note: this is the strategy you were proposing ansible take internally which is insecure.  It's not necessarily safe to do inside of a playbook either but since you control the environment you can decide whether there's symlinks or other things that can cause issues whereas it's hard for ansible to get that right.

```
# rhel6-test is a bare metal host.  chroot-fedora21 is a chroot host
- hosts: chroot-fedora20:rhel6-test
  vars:
    hosts: { "chroot-fedora20": "/var/lib/mock/fedora-20-x86_64/root",
             "rhel6-test": "rhel6-test:"
           }
  tasks:
  - command: "rsync /var/tmp/host {{hosts[inventory_hostname]}}/var/tmp/dest"
    delegate_to: "localhost"
```
