### ISSUE TITLE
Git Module Hangs

### ISSUE THREAD

**Issue by TigerWolf** [ansible/ansible-modules-core#2837]
**Issue Type:**

Bug Report

**Ansible Version:**

ansible 2.0.0.2
  config file =
  configured module search path = Default w/o overrides

**Ansible Configuration:**

Default configuration.

**Environment:**

Control Machine: OS X v10.11.2
Managed Node: Red Hat Enterprise Linux Server 7.1
Summary:

site.yml:

```

---
- hosts: all
  become: sudo
  become_user: m_mobileapps
  vars:
    repo: "***" #Removed
    key_file: "/home/user/.ssh/custom_id_rsa"
    deploy_to: "/var/www/html"
    branch: develop
  tasks:
    - name: create or update the bare Git repository
      git:
        repo: "{{ repo }}"
        dest: "{{ deploy_to }}/scm"
        version: "{{ branch }}"
        bare: yes
        update: yes
        key_file: "{{ key_file | default() }}"
        accept_hostkey: yes
```

**Steps To Reproduce:**

ANSIBLE_KEEP_REMOTE_FILES=1 ansible-playbook -vvvv config/deploy/test.yml -i config/deploy/uat --ask-pass --ask-sudo-pass

Another command was used to upload key files to server. Can provide if helps.

**Expected Results:**

The git repository on the servers is updated.

**Actual Results:**

Ansible hangs and does not complete the command.

When running the command on the server I get:

```
 LANG=en_AU.UTF-8 LC_ALL=en_AU.UTF-8 LC_MESSAGES=en_AU.UTF-8 /usr/bin/python /home/user/.ansible/tmp/ansible-tmp-1453088309.02-27952031568981/git

{"invocation": {"module_args": {"executable": null, "force": false, "refspec": null, "reference": null, "dest": "/var/www/mobileapps/scm", "accept_hostkey": true, "clone": true, "verify_commit": false, "update": true, "ssh_opts": null, "repo": "****", "depth": null, "version": "develop", "bare": true, "recursive": true, "remote": "origin", "key_file": "/home/user/.ssh/custom_id_rsa", "track_submodules": false}}, "changed": false, "after": "6c02766de0aafa613544a883b6539c67490ee241", "before": "6c02766de0aafa613544a883b6539c67490ee241"}
```

This is confusing as it appears as though the command runs correctly but ansible does not return this status.

EDIT: If I press `ctrl+c`, ansible shows the status as ok=1 If I let it run for long enough.
