### ISSUE TITLE
route53_health_check fqdn / resource_path uniqueness ignored

### ISSUE THREAD

**Issue by glnds** [ansible/ansible-modules-core#2847]
## Issue Type:

Bug Report
## Ansible Version:

ansible 2.0.0.2
## Ansible Configuration:

vanilla
## Environment

OS X El Capitan 10.11.2
## Summary

route53_health_check module ignores a duplicate entry on fqdn. Two entries with the same fqdn but a different path are interpreted as the same (second one is ignored).
## Steps To Reproduce:

```
- name: ensure route53 health checks are enabled
  route53_health_check:
    region: "{{ region }}"
    profile: "{{ profile }}"
    state: present
    fqdn: "{{ item.fqdn }}"
    type: "{{ item.type }}"
    resource_path: "{{ item.path }}"
    failure_threshold: 2
  with_items:
    - { fqdn: "some.example.com", type: "HTTPS", path: "/path_a", "threshold": 4}
    - { fqdn: "some.example.com", type: "HTTP", path: "/path_a", "threshold": 4}
    - { fqdn: "some.example.com", type: "HTTPS", path: "/path_b", "threshold": 4}
    - { fqdn: "some.example.com", type: "HTTP", path: "/path_b", "threshold": 4}
  tags:
    - route53
  register: health_checks
```
## Expected Results:

4 Route53 health checks
## Actual Results:

2 Route53 health check both reffering to /path_a
