### ISSUE TITLE
mysql_user passwords not quotet correctly

### ISSUE THREAD

**Issue by crane-denny** [ansible/ansible-modules-core#2867]
Ansible version: 2.0 and devel

Ansible Configuration: none

Environment: N/A

Summary:
When a password is defined as var and it is an integer the password is not quoted when set/update a user password in mysql

```
- hosts: all
  vars:
        # This works not:
        mysql_root_password: 123456
        # This works:
        #mysql_root_password: "123456"
  tasks:
        - name: Update MySQL root password
          mysql_user:
           name: root
           host: localhost
           password: "{{ mysql_root_password }}"
           check_implicit_admin: yes
```

This code results in the following sql query:

```
SET PASSWORD FOR 'root'@'localhost' = PASSWORD(123456)
```
