### ISSUE TITLE
ec2_vpc_route_table "Multiple subnets named XXX"

### ISSUE THREAD

**Issue by nerzhul** [ansible/ansible-modules-core#2876]
Hi,
thanks for your ec2_vpc_route_table module but i noticed a bug anoying with subnet attribute.

I use the following task:

```
- name: Create routing table
  ec2_vpc_route_table:
    vpc_id: "{{ item.0.vpc_id }}"
    region: "{{ item.0.region }}"
    tags: "{{ item.1.tags }}"
    routes: "{{ item.1.routes }}"
    subnets: "{{ item.1.subnets }}"
  with_subelements:
    - amazon.routes
    - config
```

Here is the vars file:

```
amazon:
  routes:
    vpc_test:
      vpc_id: "vpc-aaaaaaaa"
      region: "eu-wtf-1"
      config:
        - tags:
            Name: "test-public"
          subnets:
            - "subnet-XXX"
            - "subnet-YYY"
            - "subnet-ZZZ"
          routes:
            - { dest: "172.16.0.0/16", gateway_id: "vgw-XXX" }
            - { dest: "192.168.1.0/24", gateway_id: "vgw-XXX" }
```

This works with the following syntax with subnet IDs but if i replace subnet-XXX by names, it doesn't work with multiple subnets.

```
failed: [127.0.0.1] => (item=({u'vpc_id': u'vpc-XXX', u'region': u'eu-central-1'}, {u'routes': [{u'dest': u'172.16.0.0/16', u'gateway_id': u'vgw-XXX'}, {u'dest': u'192.168.1.0/24', u'gateway_id': u'vgw-XXX'}], u'subnets': [u'protect-test-a', u'protect-test2-a', u'protect-test3-a'], u'tags': {u'Name': u'test-public'}})) => {"failed": true, "item": [{"region": "eu-wtf-1", "vpc_id": "vpc-XXX"}, {"routes": [{"dest": "172.20.0.0/16", "gateway_id": "vgw-XXX"}, {"dest": "192.168.1.0/24", "gateway_id": "vgw-XXX"}], "subnets": ["protect-test-a", "protect-test2-a", "protect-test3-a"], "tags": {"Name": "test-public"}}], "msg": "Multiple subnets named \"protect-test-a\""}
```

Thanks for your reading
