### ISSUE TITLE
Documentation for Digital Ocean module confusing as it does not follow other module conventions for newbies

### ISSUE THREAD

**Issue by MikeCaspar** [ansible/ansible-modules-core#2879]
Hi there,

I'm new to ansible.

I've been struggling with the v2 api and version 2 and found and posted some notes on how to get it working over at the DO site.

I'd like to know if I could (or if someone else could) (or if there is an objection) change the Examples to something at matches other modules..

For instance...

```
- digital_ocean: >
      state=present
      command=droplet
      name=mydroplet
      api_token=XXX
      size_id=2gb
      region_id=ams2
      image_id=fedora-19-x64
      wait_timeout=500
  register: my_droplet
```

I would like to ask that this be changed to  (: format instead of arrow format) in the documentation

```
- digital_ocean: 
      state: present
      command: droplet
      name: mydroplet
      api_token: XXX
      size_id: 2gb
      region_id: ams2
      image_id: fedora-19-x64
      wait_timeout: 500
  register: my_droplet
```

It might be no big deal for python experts but it certainly makes it difficult for people new to ansible.

I am more than happy to pull the repo and try to make the changes myself.

However, I didn't want to do so until I knew if there was a compelling reason for the difference. 

If I am totally out of line, no biggy, just close this issue.

Thanks
