### ISSUE TITLE
openstack launch vm exception - module os_server

### ISSUE THREAD

**Issue by vladah** [ansible/ansible-modules-core#2901]
##### Issue Type:
- Bug Report
##### Component Name:

os_server module
##### Ansible Version:

```
root@vladvm-u15:~# ansible --version
ansible 2.0.0.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
root@vladvm-u15:~#
```
##### Ansible Configuration:

nothing changed but this:

host_key_checking = False
##### Environment:

```
root@vladvm-u15:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 15.10
Release:        15.10
Codename:       wily
```
##### Summary:

Launching an instance in Openstackcloud using os_server. Seeing an exception but instance launched.
##### Steps To Reproduce:

```
root@vladvm-u15:~# vim launch-vm.yml

---
- name: launch a vm
  hosts: localhost
  tasks:
  - name: launch an instance
    os_server:
      state: present
      auth:
        auth_url: http://10.26.253.15:5000/v2.0
        username: admin
        password: secret123
        project_name: Vlad
      name: vm-ansible
      region_name: RegionOne
      availability_zone: tlapp09
      image: d8ed5faa-9826-4ae0-b5ac-0bb2de4ad672
      key: /tmp/cloud.key
      key_name: cloud-key-pub
      timeout: 200
      flavor: 4
      security_groups: default
      nics:
        - net-id: 4d791e51-2875-4065-90b0-bec4a2e804d7
      floating_ip_pools:
        - VN-A-Floats
...
```
##### Expected Results:

Please enter your expected results in this space.  When running the steps supplied above in the previous section, what did you expect to happen?  If showing example output, please indent your output by four spaces so it will render correctly in GitHub's viewer thingy.
##### Actual Results:

```
root@vladvm-u15:~# ansible-playbook launch-vm.yml -vvv
Using /etc/ansible/ansible.cfg as config file
1 plays in launch-vm.yml

PLAY [launch a vm] *************************************************************

TASK [setup] *******************************************************************
ESTABLISH LOCAL CONNECTION FOR USER: root
127.0.0.1 EXEC ( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1453929262.21-75821022779819 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1453929262.21-75821022779819 )" )
127.0.0.1 PUT /tmp/tmpWsm4Fs TO /root/.ansible/tmp/ansible-tmp-1453929262.21-75821022779819/setup
127.0.0.1 EXEC LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1453929262.21-75821022779819/setup; rm -rf "/root/.ansible/tmp/ansible-tmp-1453929262.21-75821022779819/" > /dev/null 2>&1
ok: [localhost]

TASK [launch an instance] ******************************************************
task path: /root/launch-vm.yml:5
ESTABLISH LOCAL CONNECTION FOR USER: root
127.0.0.1 EXEC ( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1453929262.67-97106069906430 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1453929262.67-97106069906430 )" )
127.0.0.1 PUT /tmp/tmpXsByaG TO /root/.ansible/tmp/ansible-tmp-1453929262.67-97106069906430/os_server
127.0.0.1 EXEC LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1453929262.67-97106069906430/os_server; rm -rf "/root/.ansible/tmp/ansible-tmp-1453929262.67-97106069906430/" > /dev/null 2>&1
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1453929262.67-97106069906430/os_server", line 2645, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1453929262.67-97106069906430/os_server", line 598, in main
    _create_server(module, cloud)
  File "/root/.ansible/tmp/ansible-tmp-1453929262.67-97106069906430/os_server", line 463, in _create_server
    _exit_hostvars(module, cloud, server)
  File "/root/.ansible/tmp/ansible-tmp-1453929262.67-97106069906430/os_server", line 359, in _exit_hostvars
    hostvars = meta.get_hostvars_from_server(cloud, server)
  File "/usr/lib/python2.7/dist-packages/shade/meta.py", line 99, in get_hostvars_from_server
    server_vars.pop('links', None)
  File "/usr/lib/python2.7/dist-packages/novaclient/openstack/common/apiclient/base.py", line 494, in __getattr__
    raise AttributeError(k)
AttributeError: pop

fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "os_server"}, "parsed": false}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1
```
