### ISSUE TITLE
os_image sets min_ram / min_disk to invalid values

### ISSUE THREAD

**Issue by pwnall** [ansible/ansible-modules-core#2927]
##### Issue Type:
- Bug Report
##### Ansible Version:

2.0.0.2
also tried on development branch
##### Ansible Configuration:

No changes
##### Environment:

OSX 10.11.3, ansible installed via Homebrew
##### Summary:

I'm getting an error message (included below) using an os_image invocation that used to work.
##### Steps To Reproduce:

This is the os_image invocation. I tried adding `min_ram: 0` and that didn't change anything.

```
- name: register Fedora 23 VM image
  os_image:
    name: "Fedora 23"
    container_format: bare
    disk_format: qcow2
    timeout: 3600
    filename: "./tmp/images/Fedora 23.qcow2"
    cloud: "{{ os_cloud }}"
```
##### Expected Results:

A few months ago, this used to register an image on OpenStack.
##### Actual Results:

```
fatal: [localhost]: FAILED! => {"changed": false, "extra_data": null, "failed": true, "msg": "Image creation failed: Unable to set 'min_ram' to '0'. Reason: '0' is not of type u'integer'\n\nFailed validating u'type' in schema[u'properties'][u'min_ram']:\n    {u'description': u'Amount of ram (in MB) required to boot image.',\n     u'type': u'integer'}\n\nOn instance[u'min_ram']:\n    '0' (Inner Exception: Unable to set 'min_ram' to '0'. Reason: '0' is not of type u'integer'\n\nFailed validating u'type' in schema[u'properties'][u'min_ram']:\n    {u'description': u'Amount of ram (in MB) required to boot image.',\n     u'type': u'integer'}\n\nOn instance[u'min_ram']:\n    '0')"}
```
