### ISSUE TITLE
user-data of digitalocean doesn't take effect

### ISSUE THREAD

**Issue by janusle** [ansible/ansible-modules-core#2958]
**Issue Type**:
Bug Report

**Component Name**
digital_ocean

**Ansible Version**

```
ansible 2.0.0.2
  config file = 
  configured module search path = Default w/o overrides
```

**Ansible Configuration:**

N/A

**Environment:**

Ubuntu 14.04

**Summary:**

Commands in the user-data are not executed when creating droplets in digitalocean.

**Steps to Reproduce:**

```
      digital_ocean:
        state: present
        command: droplet
        size_id: "1gb"
        region_id: "sgp1"
        image_id: "ubuntu-14-04-x64"
        user_data: "{{ lookup('template', 'user_data.j2') | trim }}"
        api_token: "{{ do_api }}"

```

User data:

``` bash
#!/bin/bash
adduser {{ user }} --disabled-password --gecos ""
adduser {{ user }} sudo
if [[ ! -d /home/{{ user }}/.ssh ]];then
  mkdir /home/{{ user }}/.ssh
fi

echo '{{ user }} ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/{{ user }}
# Import public keys from your github account
apt-get -y install curl
curl https://github.com/janusle.keys>> /home/{{ user }}/.ssh/authorized_keys

# Disable root login
sed -i 's/^PermitRootLogin[:space:]*.*/PermitRootLogin no/g' /etc/ssh/sshd_config
service ssh restart
```

**Expected Results:**

A file aaa containing 'aaa' should be created under /tmp after a droplet created.

**Actual Results:**

No file was created. 

If you do 

```
curl http://169.254.169.254/metadata/v1/user-data
```

nothing returns which means somehow user-data was not passed to digitalocean.
