### ISSUE TITLE
user module bug

### ISSUE THREAD

**Issue by quartzeye** [ansible/ansible-modules-core#2960]
##### Issue Type:

Can you help us out in labelling this by telling us what kind of ticket this this?  You can say:
- Bug Report
##### Ansible Version:

1.9.4
##### Ansible Configuration:

No deviation from standard install
##### Environment:

RHEL 6.7 on both the deployment server and the target server.
##### Summary:

The user module does not create the correct password when using passwords in clear text.
##### Steps To Reproduce:

1) in group variables I created a default password and a dictionary of users

```
**pwd_default: passw0rd**

# All users
usrs:
  db2:
    - { name: 'dasusr1', uid: '10601', groups: 'dasadm1', **pwd: "{{ pwd_default }}"** }
    - { name: 'db2inst1', uid: '10602', groups: 'dasadm1', **pwd: "{{ pwd_default }}"** }
    - { name: 'db2fenc1', uid: '10603', groups: 'db2fadm1', **pwd: "{{ pwd_default }}"** }
  was:
    server:
      - { name: 'was admin', uid: '10611', groups: 'dstage', **pwd: "{{ pwd_default }}"** }
```

2) in a role i created a sigle task to create the users

```
- name: add several users
  debug: msg="name={{item.name}} **pwd={{item.pwd}}**" 
  ignore_errors: yes
  with_items: "{{usrs.db2}}"

- name: add several users
  user: name="{{ item.name }}"
        **password="{{ item.pwd }}"**
        groups="{{ item.groups }}"
        uid="{{ item.uid }}"
        state=present
  ignore_errors: no
  with_items: "{{usrs.db2}}"
```
##### Expected Results:

I expect (3) users to be created with the password 'passw0rd'

```
TASK: [db2-server | add several users] **************************************** 
ok: [db2-server.ibm.com] => (item={**'pwd': u'passw0rd'**, 'name': 'dasusr1', 'groups': 'dasadm1', 'uid': '10601'}) => {
    "item": {
        "groups": "dasadm1", 
        "name": "dasusr1", 
        **"pwd": "passw0rd"**, 
        "uid": "10601"
    }, 
    "msg": "name=dasusr1 **pwd=passw0rd**"
}
ok: [db2-server.ibm.com] => (item={**'pwd': u'passw0rd'**, 'name': 'db2inst1', 'groups': 'dasadm1', 'uid': '10602'}) => {
    "item": {
        "groups": "dasadm1", 
        "name": "db2inst1", 
        **"pwd": "passw0rd"**, 
        "uid": "10602"
    }, 
    "msg": "name=db2inst1 **pwd=passw0rd**"
}
ok: [db2-server.ibm.com] => (item={**'pwd': u'passw0rd'**, 'name': 'db2fenc1', 'groups': 'db2fadm1', 'uid': '10603'}) => {
    "item": {
        "groups": "db2fadm1", 
        "name": "db2fenc1", 
        **"pwd": "passw0rd", **
        "uid": "10603"
    }, 
    "msg": "name=db2fenc1 **pwd=passw0rd**"
}

TASK: [db2-server | add several users] **************************************** 
changed: [db2-server.ibm.com] => (item={**'pwd': u'passw0rd'**, 'name': 'dasusr1', 'groups': 'dasadm1', 'uid': '10601'})
changed: [db2-server.ibm.com] => (item={**'pwd': u'passw0rd'**, 'name': 'db2inst1', 'groups': 'dasadm1', 'uid': '10602'})
changed: [db2-server.ibm.com] => (item={**'pwd': u'passw0rd'**, 'name': 'db2fenc1', 'groups': 'db2fadm1', 'uid': '10603'})

PLAY RECAP ******************************************************************** 
db2-server.ibm.com          : ok=0    changed=3    unreachable=0    failed=0   
```
##### Actual Results:

First, I have no idea where or why the "u" is appearing in the password when the item is listed.  It clearly is not the value as shown in the messages and data when the {{item.pwd}} is echoed to the screen.

Second, the password is not set to 'passw0rd' on the target server.  In /etc/shadow on db2-server the passwords appear in clear text but cannot used to login or su to.

iisuser:$6$VxZOhb49Bt88ytWb$oqwHUmlUY1aBDr9YklVFAItFpdnVMzUIUI/FTHr0uMXbcP8I/udIryX9NfP70gQTxgej8h6Ed5EpEI0ZW.YCZ.:16821:0:99999:7:::
**dasusr1:passw0rd:16835:0:99999:7:::
db2inst1:passw0rd:16835:0:99999:7:::
db2fenc1:passw0rd
