### ISSUE TITLE
File module: incorrect directory permissions using numeric value for mode with a non-zero leading digit

### ISSUE THREAD

**Issue by ssnepenthe** [ansible/ansible-modules-core#2963]
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible 2.0.0.2
  config file = /Users/[USER]/Sites/[PROJECT]/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

```
[defaults]
roles_path = provision/roles
force_handlers = True
inventory = provision/hosts

[ssh_connection]
ssh_args = -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s
```
##### Environment:

Running ansible from OS X 10.11.3.

Managing Ubuntu 14.04.
##### Summary:

File module: incorrect permissions set on directory using a numeric value with a non-zero leading digit for the mode option.
##### Steps To Reproduce:

```
- name: Ensure directory exists
  file:
    dest: /some/path/here
    mode: 2755
    owner: deploy
    state: directory
```
##### Expected Results:

`stat -c %a /some/path/here` =>  `2755`

`ll /some/path` => `drwxr-sr-x 4 deploy deploy 4096 Feb 4 08:02 here/`
##### Actual Results:

`stat -c %a /some/path/here` =>  `5303`

`ll /some/path` => `d-ws----wt 4 deploy deploy 4096 Feb 4 08:02 here/`
##### Further Notes:

I am not sure if this would be considered a bug or just an unsupported feature: the docs state "Leaving off the leading zero will likely have unexpected results" but there is no mention of using a non-zero leading digit.

Using a symbolic mode instead of a numeric one produces the expected results.

Example:

```
- name: Ensure directory exists
  file:
    dest: /some/path/here
    mode: "u=rwx,g=rxs,o=rx"
    owner: deploy
    state: directory
```

Result:
`stat -c %a /some/path/here` =>  `2755`

`ll /some/path` => `drwxr-sr-x 4 deploy deploy 4096 Feb 4 08:02 here/`
