### ISSUE TITLE
postgres_user module doesn't work with AWS RDS databases

### ISSUE THREAD

**Issue by dan-mcdonald** [ansible/ansible-modules-core#297]
##### Issue Type:

Bug report
##### Ansible Version:

ansible 1.7.0
##### Environment:

OSX Mavericks 10.9.4
##### Summary:

When running against an AWS RDS Postgresql instance, the postgres_user module can't set up new users.
##### Steps To Reproduce:

Run this task:

```
- name: Ensure user has access to the database
  postgresql_user: login_host={{ db_host }}
                   port={{ db_port }}
                   login_user={{ db_admin_user }}
                   login_password={{ db_admin_password }}
                   db={{ db_name }}
                   name={{ db_user }}
                   password={{ db_password }}
                   priv=ALL
                   state=present 
```
##### Expected Results:

```
ok: [...] => {"changed": true, "db": "database"}
```
##### Actual Results:

```
failed: [...] => {"failed": true, "parsed": false}
invalid output was: SUDO-SUCCESS-qwpjepgvenunnlewzwjddpnrbfjyptxo
Traceback (most recent call last):
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1407775799.05-32923950289495/postgresql_user", line 1869, in <module>
    main()
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1407775799.05-32923950289495/postgresql_user", line 497, in main
    changed = user_alter(cursor, module, user, password, role_attr_flags, encrypted, expires)
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1407775799.05-32923950289495/postgresql_user", line 201, in user_alter
    cursor.execute(select, {"user": user})
psycopg2.ProgrammingError: permission denied for relation pg_authid
```

Apparently the `pg_authid` relation [is not available in RDS](https://forums.aws.amazon.com/thread.jspa?threadID=151248).

Possible workaround: if access denied for `pg_authid`, then always set the password.

**Comment by dan-mcdonald** [comment]
This is a copy of ansible/ansible#8547, a victim of the module re-organization.

**Comment by smiller171** [comment]
It appears that the problem is not that a user cannot be created. It seems to work only if the user does not already exist.

**Comment by mattwillsher** [comment]
I've see the opposite - it worked first run as long as I created the database first. Subsequent runs fail. 
My code block is 

``` yaml
- name: Create PostgreSQL database
  postgresql_db:
    login_host: "{{ crowd_db_server }}"
    login_user: "{{ crowd_db_admin_user }}"
    login_password: "{{ crowd_db_admin_password }}"
    name: "{{ crowd_db_database }}"
  when: crowd_db_type == 'postgresql'
  register: crowd_db_created

- name: Create PostgreSQL user
  postgresql_user:
    login_host: "{{ crowd_db_server }}"
    login_user: "{{ crowd_db_admin_user }}"
    login_password: "{{ crowd_db_admin_password }}"
    db: "{{ crowd_db_database }}"
    name: "{{ crowd_db_user }}"
    password: "{{ crowd_db_password }}"
    role_attr_flags: CREATEROLE,CREATEDB
  when: crowd_db_type == 'postgresql'
```

Having the second block with `and crowd_db_created.changed` appends to the when clause works around the problem.

**Comment by akurilin** [comment]
can confirm this is still a problem in 1.9.4

**Comment by memelet** [comment]
Also can confirm this is still a problem in 1.9.4. Any workaround? Just drop to shell?

**Comment by PlugIN73** [comment]
So, any movements?

**Comment by smiller171** [comment]
@bcoca This seems to have fallen under the radar?

**Comment by bcoca** [comment]
does the PR merged above 'fix this'? if so was included in 2.0 so 1.9.4 will still have the issue.

**Comment by smiller171** [comment]
@bcoca I missed that PR. I don't use Postgres in my new position, but I can probably set aside some time to test this weekend if no one else can confirm.

**Comment by thanosd** [comment]
This seems to now work ok with the workaround in 2.0.1.0.

**Comment by tjarvstrand** [comment]
Hitting the same issue right now with 2.0.1.0

**Comment by woqer** [comment]
Same issue in ansible 2.1.0.0. Using `role_attr_flags` does not set the attributes on new user. On existing user fails with the error `psycopg2.ProgrammingError: permission denied for relation pg_authid` even without the `password` option.

**Comment by ansibot** [comment]
@grossws, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/jctanner/ansibullbot/blob/ISSUE_TRIAGE_CLASS/ISSUE_HELP.md)

**Comment by singpolyma** [comment]
The workaround in the pull request only works if you don't want to change the password.  I would prefer to force the password change, since then that would still work -- even though it would have to happen every time (even when not changed), that's not a big cost.

**Comment by ansibot** [comment]
@grossws, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by wvidana** [comment]
@singpolyma Not sure if that can be done without permissions on the `pg_authid` table (AWS requirement, not ansible's fault). Still, the workaround is skipping everything https://github.com/ansible/ansible-modules-core/pull/4038

**Comment by singpolyma** [comment]
@woqer my understanding is that the permissions issue means you can't _check_ if the password needs to be changed, not that you can't change it at all.  Might mean doing extra work of changing it from X to X, but that doesn't sound like a big cost to me.

**Comment by wvidana** [comment]
@singpolyma I think you are right, but this can coexists with the `no_password_changes` flag too. Not sure right now on how to implement the password change though, there is some clue on how to get user/role information on the PR I mentioned before (using the `pg_roles` table instead of `pg_authid`)

**Comment by grossws** [comment]
@jctanner, @gregdek, I wasn't `postgres_user` maintainer IIRC. Seems to be some bug in @ansibot notifications.

**Comment by gregdek** [comment]
Hmm, yes. MAINTAINERS-CORE.txt points to "ansible" as the maintainer of this module, so...

bot_broken

**Comment by rgwozdz** [comment]
adding `no_password_changes: true` solved issue for me

**Comment by srkiNZ84** [comment]
For what it's worth, we've been running the following workaround task after calling "postgresql_user" with the "no_password_changes: true" set, to make sure the password actually matches what we need it to:

```
- name: Ensure password matches what we have
  command: "psql -h database.internal -U pg_admin -d postgres -c \"ALTER ROLE foobar WITH PASSWORD 'password';\""
  environment:
    PGPASSWORD=adminuserpass
```
