### ISSUE TITLE
ec2 count_tag and exact_count incorrectly spinning up new instances on every playbook run

### ISSUE THREAD

**Issue by MichaelBaydoun** [ansible/ansible-modules-core#2970]
##### Ansible Version: 2.0.0.2

Though ansible --version reports 2.0.0.0
##### Ansible Configuration: First attempt at using ec2 module

```
- name: spin up a ec2 instances
  ec2:
    count_tag: demo
    exact_count: 1
    image: ami-60b6c60a
    region: us-east-1
    type: t2.nano
    wait: yes
```
##### Summary:

Using count_tag and exact_count, expect instance to be created on first playbook run, and no change on subsequent runs if instance is still running
##### Steps To Reproduce:

```
- name: spin up a ec2 instances
  ec2:
    count_tag: demo
    exact_count: 1
    image: ami-60b6c60a
    region: us-east-1
    type: t2.nano
    wait: yes
```

Run it twice
##### Expected Results:

Instance created on first run, but not on second run if first instance is still running.
##### Actual Results:

Spins up new instance each time

**Comment by jvkersch** [comment]
I ran into this exact same issue and couldn't figure out what went wrong until I looked at the source code. The problem is that `count_tags` specifies a list of _existing_ tags that should be used for counting the instances. If your instance tag list is empty, `find_running_instances_by_tag_count` will return no instances with the given tag, and hence a new instance will be created regardless of whether there already is one.

@IndyMichaelB The workaround is simple, just add your count tag to the list of instance tags:

``` yaml
- name: spin up a ec2 instances
  ec2:
    count_tag: demo
    instance_tags:
        demo: foo
    exact_count: 1
    image: ami-60b6c60a
    region: us-east-1
    type: t2.nano
    wait: yes
```

In general, I think this should either be made explicit in the documentation, and the EC2 module should complain if you try to use a count tag that isn't listed among the instance tags. Alternatively, `create_instances` could just add the count tags to the list of instance tags, so that they always exist.

I can probably do a PR with either solution, if this would help.
