### ISSUE TITLE
Template tasks changes on different hosts without a real change

### ISSUE THREAD

**Issue by crane-denny** [ansible/ansible-modules-core#2978]
When dealing with templates and running Ansible from differents hosts everytime a template is rendered and used with ansible_managed a change is triggered.

This is bad for two reasons:
1. The person who triggered the run assumes that there was something wrong in the configuration
2. We lose the information who has really rolled out that changed at which time 

Ansible should ignore the hole line which will get into ansible_managed and then check for differences.

playbook.yml:

```
- hosts: all
  tasks:
    - name: test render
      template:
        src: test.j2
        dest: /tmp/test.conf
```

test.j2:

```
# {{ ansible_managed }}
foo
```
