### ISSUE TITLE
Apt Module: Provide option to avoid installing specific dependencies

### ISSUE THREAD

**Issue by nhooey** [ansible/ansible-modules-core#3011]
##### ISSUE TYPE

Feature Idea
##### COMPONENT NAME

apt module
##### ANSIBLE VERSION

2.0.0.2
##### SUMMARY

When installing packages with Apt, you can [avoid installing specific dependencies](http://serverfault.com/a/663803/1843) with a trailing `-` character:

``` bash
sudo apt-get install package_to_install dependency_to_avoid-
```

*(Note the trailing `-` character on the dependency)

Currently there is no way to do this with the Apt module. The best alternative is currently to install the package, then immediately uninstall the dependency.

A list parameter called `avoid_dependencies` or similar could be provided.

_Note that supplying a package with a trailing `-` in its name to the Apt module doesn't work with Ansible 2.0.0.2_:

``` yaml
- apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "rkhunter"
    - "postfix-"
```
