### ISSUE TITLE
Add option to get_url for number of retries on checksum mismatch

### ISSUE THREAD

**Issue by wildefires** [ansible/ansible-modules-core#3017]
Issue Type: Feature Idea

Summary:

Add an option "retries" (or similar) to allow for ansible to try multiple times to download a file in get_url if the download checksum doesn't match the first time. 

i.e.:

```
- name: Get ant
  get_url: 
    url: "{{ ant_url }}{{ ant_artifact_name }}"
    dest: "{{ working_directory }}"
    checksum: "md5:{{ ant_md5 }}"
    retries: 5
```

If the first time it downloads and the md5 != ant_md5 it will, instead of failing right away, attempt the download again up to 5 times before failing the host
