### ISSUE TITLE
ansible 2.0.0.2 - aws ec2_group - rules_egress not working 

### ISSUE THREAD

**Issue by ghost** [ansible/ansible-modules-core#3053]
## Issue Type

Bug Report
## Component Name

ec2_group
## Ansible Version

2.0.0.2
## Environment

Ansible 2.0.0.2
Ubuntu 14.03
AWS
## Summary

I am trying to apply outbound firewall rules to AWS using the rules_egress: However, when I log into my AWS account and look at the winrdp security group, all I see are the inbound rules and no outbound rules.
### dev-environment.yml

```
# security groups to be created
security_groups:
  - name: winrdp
    desc: the security group for the winrdp server
    rules:
      - proto: tcp
        from_port: 5986
        to_port: 5986
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 3389
        to_port: 3389
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
```
### playbook

```

---
- name: Provision ec2 instances based on the environment
  hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
    - vars/dev-environment.yml
    - vars/aws-creds.yml

  tasks:

  - name: Create required security groups
    ec2_group:
      name: "{{ item.name }}"
      description: "{{ item.desc }}"
      rules: "{{ item.rules }}"
      region: "{{ ec2_region }}"
      ec2_access_key: "{{ ec2_access_key }}"
      ec2_secret_key: "{{ ec2_secret_key }}"
    with_items: security_groups
```

![screenshot from 2016-02-16 20 31 24](https://cloud.githubusercontent.com/assets/6406166/13097103/63c440a8-d4ec-11e5-8769-2ecc6f1c651e.png)

**Comment by Constantin07** [comment]
As  per module documentation here http://docs.ansible.com/ansible/ec2_group_module.html
purge_rules_egress option is true by default if not specified.

**Comment by ghost** [comment]
documentation for purge_rules_rules says "Purge existing rules_egress on security group that are **_NOT_** found in rules_egress".

I also added this option purge_rules_egress to false, but still nothing. Do you have an example of this working? the example in the document shows rules_egress, but not purge_rules_egress.

**Comment by glenjarvis-repairpal** [comment]
@sarlindo Does this test case pass or fail for you when you specify the VPC id?

e.g.,:

```
- name: example ec2 group
  ec2_group:
    name: example
    description: an example EC2 group
    vpc_id: 12345
    region: eu-west-1a
    aws_secret_key: SECRET
    aws_access_key: ACCESS
[snip]
```
