### ISSUE TITLE
pip module always shows changed in --check mode when state=latest

### ISSUE THREAD

**Issue by mgedmin** [ansible/ansible-modules-core#3055]
**Issue Type**
Bug Report

**Component Name**
pip module

**Ansible version**
ansible 2.1.0 (devel 875ea74621) last updated 2016/02/17 08:28:52 (GMT +300)
  lib/ansible/modules/core: (detached HEAD 8d126bd877) last updated 2016/02/15 09:14:28 (GMT +300)
  lib/ansible/modules/extras: (detached HEAD f6c5ed987f) last updated 2016/02/12 08:50:23 (GMT +300)

**Summary**

This is similar to #2848, except I'm unhappy about the other case in the branch, about `state=latest`.

**Steps to reproduce**

Have a task like this:

``` yml
- name: install letsencrypt
  pip: name={{ item }} virtualenv=/opt/letsencrypt state=latest
  with_items:
    - pip
    - setuptools
    - letsencrypt
    - letsencrypt-apache
```

Run it with `ansible -C`

**Expected behavior**
- doesn't report changed unless there are newer versions of any of the packages requested (or their dependencies) on the Python Package Index

**Actual behavior**
- always reports changed for all packages
