### ISSUE TITLE
VMware Template playbook options

### ISSUE THREAD

**Issue by wintechdevops** [ansible/ansible-modules-core#3056]
##### ISSUE TYPE

Bug Report
##### COMPONENT NAME

vsphere_guest
##### ANSIBLE VERSION

N/A
##### SUMMARY

Hi 
I am setting up a new VMware virtual machine from a template using a Ansible playbook.
I want to be able to change the datastore and the network (vm_disk and vm_nic) of the VM during the setup of the VM. But when I add this information into the playbook (see below), nothing happens.
The new VM is created successfully and Ansible returns a success, but the datastore and network have not been adjust to what I requested in the playbook. They have remained the same as what the template image is.
Am I doing something incorrect in the playbook? Or is this not possible with Ansible?

Playbook (highlighted in bold is what is not being adjusted)
`---
- hosts: 127.0.0.1
  connection: local
  user: root
  sudo: false
  gather_facts: false
  serial: 1
  vars:
   vcenter_hostname: server.local
   esxhost: 172.25.10.10
   nic_type: e1000e
   network: Web Servers
   network_type: standard
   vmcluster: UK-CLUSTER
   username: admin
   password: password
   folder: Utilities
   notes: Created by Ansible
  
  tasks:
  - name: Create VM from template
    vsphere_guest:
      vcenter_hostname: "{{ vcenter_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      guest: "{{ name }}"
      vm_extra_config:
        notes: "{{ notes }}"
        folder: "{{ folder }}"
      from_template: yes
      template_src: "{{ vmtemplate }}"
      cluster: "{{ vmcluster }}"
      vm_disk:
        disk1:
          type: "{{ disktype }}"
          datastore: "{{ datastore }}"
      vm_nic:
        nic1:
          type: "{{ nic_type }}"
          network: "{{ network }}"
          network_type: "{{ network_type }}"
      resource_pool: "/Resources"
    
      esxi:
        datacenter: UK
        hostname: "{{ esxhost }}"`

If I look at the example on the Ansible website, it doesn't look like it gives the option to allow this unless you setup a VM from an ISO file. (http://docs.ansible.com/ansible/vsphere_guest_module.html)
I want to have the same functionality if I use a template.

Cheers

**Comment by kikicarbonell** [comment]
:+1:

**Comment by chrrrles** [comment]
Yeah, the module is written in a way that this operation requires three distinct vsphere_guest tasks:  

The first task is to create the vm from it's template "as is" - using the params `from_template: Yes` and `power_on_after_clone: No`.  
The next vsphere_guest task changes the hardware settings for the powered-off vm; using params  `state: reconfigure`,  and your settings for `vm_disk` & `vm_nic`.
The last step is to power the vm with `state: powered_on`

I agree that this is annoying, but I think this should be a feature request rather than a bug report.

**Comment by sruslanas** [comment]
Can this include also change of MAC address of desired nic?

**Comment by radu-stefanache** [comment]
@chrrrles: I've tried to replicate what you've suggested by doing the following

```
- name: Create VM from template
  vsphere_guest:
    vcenter_hostname: "vcenter.internal"
    username: "user@domain.internal"
    password: "{{ vcenter_pass }}"
    guest: "{{ inventory_hostname }}"
    from_template: yes
    power_on_after_clone: No
    template_src: template_cos7
    cluster: "dev-cluster"
    resource_pool: "/Resources/Dev"
    esxi:
      hostname: "host1.internal"
      datacenter: "dev"
  tags:
    - create

- name: Reconfigure VM
  vsphere_guest:
    vcenter_hostname: "vcenter.internal"
    username: "user@domain.internal"
    password: "{{ vcenter_pass }}"
    guest: "{{ inventory_hostname }}"
    state: "reconfigured"
    vm_extra_config:
      folder: Ansible_Test
      notes: "Created by ansible"
    esxi:
      hostname: "host1.internal"
      datacenter: "dev"
    vm_disk:
      disk1:
        folder: Ansible_Test
        type: thin
        datastore: management-ssd1
    vm_hardware:
        memory_mb: 2048
        num_cpus: 2
    vm_nic:
      nic1:
        type: "vmxnet3"
        network: "Orchestration"
        network_type: "standard"
  tags:
    - reconfigure
```

What I am trying to achieve is to deploy the VM in a specific Folder and a specific Datastore. The RAM&CPU settings are being changed as well as the Network.

I've tried to specify the notes/folder in the 1st task, during template clone process but nothing happens.

Thanks in advance!

Cheers,
Radu

**Comment by radu-stefanache** [comment]
I presume this applies now: https://github.com/ansible/ansible-modules-core/pull/1403

**Comment by dav1x** [comment]
I'm looking into this as well. Folder nor notes are being populated. Here is the short of it:

Here are the clone parameters VMware expects: 
https://www.vmware.com/support/developer/converter-sdk/conv61_apireference/vim.VirtualMachine.html#clone

vsphere_guest uses pysphere for cloning operations:

Here is the code that handles the clone section:
https://github.com/dannvix/pySphere/blob/20b88c3a5c557deb4266cc15f69b016338e97881/pysphere/vi_virtual_machine.py

Vsphere_guest actually uses its own and bypasses for CreateVM_Task

https://github.com/ansible/ansible-modules-core/blob/devel/cloud/vmware/vsphere_guest.py

line 1319:

   if 'notes' in vm_extra_config:
        config.set_element_annotation(vm_extra_config['notes'])
https://www.vmware.com/support/developer/converter-sdk/conv61_apireference/vim.vm.ConfigSpec.html

The folder and notes get created on the CreateVM_Task here at line 1441:

```
    if vm_extra_config:
        vm.set_extra_config(vm_extra_config)
```

Here are the objects for spec objects for VMware's clone 
https://www.vmware.com/support/developer/converter-sdk/conv61_apireference/vim.vm.CloneSpec.html

I'm working on an update to the clone VM section of vsphere_guest

**Comment by jabobs** [comment]
@dav1x I will owe you a beer if you get that working.

**Comment by ansibot** [comment]
@chrrrles, @rhoop, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/jctanner/ansibullbot/blob/ISSUE_TRIAGE_CLASS/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@chrrrles, @rhoop, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by lglussen** [comment]
I would like to add that setting the folder path when creating the VM from a template (as opposed to a raw VM creation or `reconfigure`) is partially working in a very limited scope.  
If you set `vm_extra_config` on the task that creates the VM from a template, you can specify a 1 folder deep path, so long as the folder is a sub-directory relative to the location of the template file.  

For example, with the following folder structure:

```
Datacenter
  templates/template.file
  templates/subdir1/
  templates/subdir1/subdir2/
  other_dir/
```

The following configuration will work

``` yaml
template_src: template.file
from_template: yes
vm_extra_config:
    folder: subdir1
```

Try to make the path any longer (`subdir1/subdir2/`) or reference any top level path (`other_dir`) or even give the full path to the relative subdirectory (`templates/subdir1`) and you will fail with an error:

```
"msg": "Could not clone selected machine: [Object Not Found]: Couldn't find folder .....
```

**Comment by ansibot** [comment]
@chrrrles, @rhoop, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by pvlltvk** [comment]
If i deploy new VM from template in vSphere Web Client i can:
- set name for VM;
- select datacenter and VM folder;
- select cluster and host;
- select disk format;
- select storage for configuration files and disk;
- customize hardware.

So, I want to be able to set all this options in  vsphere_guest module when i deploy vm from template.

**Comment by asifiqbal** [comment]
Any chance to make choosing a folder more flexible than only below subdir of the template?

**Comment by hlavacek87** [comment]
Hello,

still not able to deploy vm from template on the different datastore. The template resides on datastore1 and we need to deploy vm on datatore2. 
It is not possible to achive this even with the second task with "reconfigure".

The only parametr which is working seems to be folder. IPaddress, MEM, CPU or disk dont.
 
Did anybodyfind out how to achive this? Thank you.

Here is simple code:
- name: Clone VM from template
    vsphere_guest:
        vcenter_hostname: "{{vCenter_host}}"
        username: "{{vCenter_user}}"
        password: "{{vCenter_pass}}"
        guest: "{{name}}"
        from_template: yes
        template_src: "{{template_name}}"
        cluster: "{{template_vmc}}"
        power_on_after_clone: no
        vm_extra_config:
          vcpu.hotadd: yes
          mem.hotadd:  yes
          ip_address: "{{ip_address}}"
          notes: This is a test VM for Ansible deploy
          folder: "{{esxi_folder}}"
        vm_hardware:
          memory_mb: 2048
          num_cpus: 4
        vm_disk:
          disk1:
            size_gb: 32
            type: thin
            datastore: "{{datastore}}"
        esxi:
          datacenter: "{{esxi_datacenter}}"
          hostname: "{{esxi_hostname}}"

**Comment by hlavacek87** [comment]
OK, I think that I was able to manage it myself via updating the vsphere_guest.py ansible library manually with the following:

from ROW num: 749

                datastore_mor = None
                for ds_mor, ds_path in vsphere_client.get_datastores().items():
                   if ds_path == vm_extra_config.get("datastore"): datastore_mor = ds_mor; break
                cloneArgs["datastore"] = datastore_mor

                esxi_host_mor = None
                for host_mor, host_name in vsphere_client.get_hosts().items():
                   if host_name == esxi['hostname']: esxi_host_mor = host_mor; break
                cloneArgs["host"] = esxi_host_mor


Now I am able to deploy from template to diff datastore and exactly selected esxi host in the cluster.
What do you think?

The next step would be to add possibility to create customization so we are able to specify hostname and static IP address which will be set after deploy via vmware tools. Unfortunally it would be necessary to update pysphere library as well.

MH

**Comment by mboogert** [comment]
I'm still eperiencing the subfolder issue. The templated can be cloned using the vm_extra_config, folder parameter to a subfolder of the /. If I try to deploy to folder /Folder/Subfolder, it fails with the following message: "msg": "Could not clone selected machine: [Object Not Found]: Couldn't find folder /Folder/Subfolder"

**Comment by temtemtemtem** [comment]
@hlavacek87 if I apply your changes at vsphere_guest.py, what (and where) do I have to define in my playbook to specify the datastore?

**Comment by lglussen** [comment]
@mboogert @asifiqbal try this:

**Don't provide a path**: just provide the `name` of the target directory.

It seems the folder is treated *like* an ID in the same way the vm-name is "sort-of" an ID; just like the fact that you can have VMs by the same name (so long as they are not in the same folder) you can have folders of the same name - so it's not a unique ID.  Just like the API returns the first VM it finds by the name you provide, it seems to do the same with folders.

Somewhere there is obviously a notion of hierarchy so they can render the folder structure in their management consoles, but that all seems to go out the window with whatever API calls are being made.

The following works for me with vShere/vCenter 6.0.0
```
/templates/type2/template.file
/production/webservers/team2/<future location of VM>
```

```yaml
template_src: template.file
from_template: yes
vm_extra_config:
    folder: team2
```

Just be careful not to use the same folder name twice - at least for destination folders (it might be ok in the parent directories).
