### ISSUE TITLE
win_get_url module not working - ansible 2.0.0.2

### ISSUE THREAD

**Issue by ghost** [ansible/ansible-modules-core#3067]
##### Issue Type:
- Bug Report
##### Plugin Name:

win_get_url
##### Ansible Version:

```
ansible 2.0.0.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```
##### Ansible Configuration:

NONE
##### Environment:

Ubuntu: 14.03 ansible control machine
Windows 2012R2 - Target 
##### Summary:

Can't get win_get_url to work and getting this error below: If I run a powershell directly on windows server using Invoke-WebRequest it works fine. Is this my control machine aborting the connection?

<52.71.198.77> WINRM RESULT u'<Response code 0, out "{"msg":"Error downlo", err "">'
<52.71.198.77> WINRM CLOSE SHELL: 1CA3BDC3-A081-4DC4-B68D-980841E93202
fatal: [52.71.198.77]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "win_get_url"}, "msg": "Error downloading https://github.com/sarlindo/WebPI/releases/download/v5.0/WebPlaformInstaller_x86_en-US.msi to c:\users\administrator\appdata\local\temp\WebPlaformInstaller_x86_en-US.msi Exception calling \"DownloadFile\" with \"2\" argument(s): \"The request was aborted: The connection was closed unexpectedly.\""}
##### Part of PlayBook:

```
 - name: Download WebPI
    win_get_url:
      url: 'https://github.com/sarlindo/WebPI/releases/download/v5.0/WebPlaformInstaller_x86_en-US.msi'
      dest: 'c:\users\administrator\appdata\local\temp\WebPlaformInstaller_x86_en-US.msi'

```
##### Expected Results:

For it to work and download the file
##### Actual Results:

I get request was aborted error.

**Comment by jhawkesworth** [comment]
It appears that the file you are attempting to download - https://github.com/sarlindo/WebPI/releases/download/v5.0/WebPlaformInstaller_x86_en-US.msi - does not exist at the url you have specified.
win_get_url should really give a better error message, but the following works for me when downloading from a valid url:

``` yaml
---
- hosts: windows
  tasks:
   - name: Download 7-zip
     win_get_url:
       url: http://www.7-zip.org/a/7z1514-x64.msi
       dest: 'c:\users\administrator\appdata\local\temp\7z1514-x64.msi'
```

**Comment by ghost** [comment]
@jhawkesworth sorry the "msi" did exist when I was testing, but I recently replaced the "msi" package with a 64bit version, but the same issue.

```
- name: Download WebPI
    win_get_url:
      url: 'https://github.com/sarlindo/WebPI/releases/download/v5.0/WebPlatformInstaller_amd64_en-US.msi'
      dest: 'c:\users\administrator\appdata\local\temp\WebPlatformInstaller_amd64_en-US.msi'
```

**Comment by tksarah** [comment]
How about v2.0.1 RC2? You can use v2.0.1 RC2 for testing on Feb 16.
I could get the files through my proxy server  by win_get_url with v2.0.1 RC2. ( CentOS6.6 Target : Windows Server 2012R2 )

**Comment by jhawkesworth** [comment]
@sarlindo With the new url you have supplied I am not able to reproduce this either.

I am using Ansible 2.0.1 RC2 on Lubuntu 14.04 Target Windows Server 2012R2

with the following playbook

``` yaml
---
- hosts: windows
  tasks:
   - name: Download WebPI
     win_get_url:
       url: 'https://github.com/sarlindo/WebPI/releases/download/v5.0/WebPlatformInstaller_amd64_en-US.msi'
       dest: 'c:\users\administrator\appdata\local\temp\WebPlaformInstaller_x86_en-US.msi'
```

Are you using local Administrator account to as your ansible_user ?  If not you won't have access to the destination path (although I would expect an access denied type message if that was the case).

What error do you receive now?
