### ISSUE TITLE
win_msi not working - ansible 2.0.0.2

### ISSUE THREAD

**Issue by ghost** [ansible/ansible-modules-core#3068]
##### Issue Type:
- Bug Report
##### Plugin Name:

win_msi
##### Ansible Version:

```
ansible 2.0.0.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```
##### Ansible Configuration:

NONE
##### Environment:

Ubuntu: 14.03 ansible control machine
Windows 2012R2 - Target 
##### Summary:

Can't get win_msi to work and getting this error below: If I run a directly on windows server using this command it works fine "msiexec /quiet /package c:....msi"

<52.71.198.77> WINRM CLOSE SHELL: BF02CD5E-DF36-4847-8B24-43CE0B2F96C1
fatal: [52.71.198.77]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "win_msi"}, "module_stderr": "#< CLIXML\r\n<Objs Version=\"1.1.0.1\" xmlns=\"http://schemas.microsoft.com/powershell/2004/04\"><S S=\"Error\">Remove-Item : Cannot remove item _x000D__x000A_</S><S S=\"Error\">C:\Users\Administrator\AppData\Local\Temp\tmpE54A.tmp: The process cannot _x000D__x000A_</S><S S=\"Error\">access the file 'C:\Users\Administrator\AppData\Local\Temp\tmpE54A.tmp' _x000D__x000A_</S><S S=\"Error\">because it is being used by another process._x000D__x000A_</S><S S=\"Error\">At C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1455827610.11-25697123_x000D__x000A_</S><S S=\"Error\">7201126\win_msi.ps1:277 char:1_x000D__x000A_</S><S S=\"Error\">\+ Remove-Item $logfile;_x000D__x000A_</S><S S=\"Error\">\+ ~~~~~~~~~~~~~~~~~~~~_x000D__x000A_</S><S S=\"Error\">    + CategoryInfo          : WriteError: (C:\Users\Admini...emp\tmpE54A.tmp:F _x000D__x000A_</S><S S=\"Error\">   ileInfo) [Remove-Item], IOException_x000D__x000A_</S><S S=\"Error\">    + FullyQualifiedErrorId : RemoveFileSystemItemIOError,Microsoft.PowerShell _x000D__x000A_</S><S S=\"Error\">   .Commands.RemoveItemCommand_x000D__x000A_</S></Objs>", "module_stdout": "{\"changed\":true,\"log\":null}\r\nT\u0000h\u0000i\u0000s\u0000 \u0000i\u0000n\u0000s\u0000t\u0000a\u0000l\u0000l\u0000a\u0000t\u0000i\u0000o\u0000n\u0000 \u0000\n\u0000\r\u0000", "msg": "MODULE FAILURE", "parsed": false}
##### Part of PlayBook:

```
- name: Installl WebPI
    win_msi:
      extra_args: "/quiet"
      path: 'c:\\users\\administrator\\appdata\\local\\temp\WebPlaformInstaller_x86_en-US.msi'

```
##### Expected Results:

For it to work and install msi package
##### Actual Results:

I get the error ebove.

**Comment by jhawkesworth** [comment]
So I think I understand what is going on here.

After msiexec has returned, the module code attempts to process the log file and then remove the log file.   The error message you are seeing above implies that it can't remove the log file because it is locked by another process.  This is most likely to be the windows installer service which is probably still busy processing the msi (even though msiexec has returned).

If you don't actually care about the log file output, it would be well worth trying the win_package module (which can install .msi files and .exe installers).

That said, its not clear to me how best to fix this.

msiexec itself does not appear to have a wait option.

I've found a few references to using start /wait but if msiexec is returning before the installer service has actually finished working then I don't see how start /wait could know anything other what it can discover from the return status.

Or perhaps the way to fix it is to poll the log file to check it is not in use before attempting to process this using something like the Test-Filelock function here: http://stackoverflow.com/questions/24992681/powershell-check-if-a-file-is-locked

However that would probably need a timeout and probably ought to either fail or warn if it couldn't open the log file within a reasonable period.

**Comment by ghost** [comment]
@jhawkesworth I switched to using the  win_package module instead and this is working fine.

**Comment by jhawkesworth** [comment]
@sarlindo Thanks for the update.  Lets' leave this issue report open although I think maybe adding logging to win_package might be the best way to solve this.

**Comment by dailyherold** [comment]
@sarlindo I got a nearly [identical error](http://pastebin.com/8j5ZgsTH) when trying to use win_msi. Initially my task was:

```
- name: Install Netuitive agent
  win_msi:
    path: "C:/ansible/CollectdWin-x64.msi"
    state: present
```

...but after changing to below it worked:

```
- name: This works - Install Netuitive agent
  win_msi:
    path: 'C:\ansible\CollectdWin-x64.msi'
    state: present
```

**Ansible Version:**

```
ansible 2.0.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

**Environment:**
Localhost: Mint (Ubuntu 14.04 base) kernel 3.19.0-32-generic
Remote: Win2012R2

**Comment by jhawkesworth** [comment]
@dailyherold 

Single quoted strings are taken literally, but double quoted strings are parsed - this is general feature of ansible.

Since version 2, ansible has got a lot better at handling windows paths and for fixed paths like these you may find it doesn't need quotes at all, i.e.:

``` yaml
- name: Install Netuitive agent no quotes windows-style path separator (not tested)
  win_msi:
    path: C:\ansible\CollectdWin-x64.msi
    state: present
# or even
- name: Install Netuitive agent no quotes linux-style path separators (not tested)
  win_msi:
    path: C:/ansible/CollectdWin-x64.msi
    state: present
```
