### ISSUE TITLE
cloud/docker: creation of containers not possible because of "Could not convert 0 to integer" exception

### ISSUE THREAD

**Issue by berendt** [ansible/ansible-modules-core#3078]
##### Issue Type:
- Bug Report
##### Plugin Name:

cloud/docker
##### Ansible Version:

```
ansible 2.1.0
```
##### Environment:

Fedora 23
##### Summary:

Trying to create a Docker container fails with the following exception:

```
FAILED! => {"changed": false, "failed": true, "msg": "Could not convert 0 to integer"}
```

Issue is in method `_human_to_bytes` (https://github.com/ansible/ansible-modules-core/blob/devel/cloud/docker/docker.py#L531-L545).

Explicitly setting `memory_limit` parameter does not solve the issue. 
##### Steps To Reproduce:

```
- name: start a hello world container
  docker:
    name: container
    image: hello-world
```
##### Expected Results:

A running container.
##### Actual Results:

```
FAILED! => {"changed": false, "failed": true, "msg": "Could not convert 0 to integer"}
```

**Comment by cluetjen** [comment]
same issue here on Ubuntu 14.04 (clean install) with docker host from packages and ansible devel.

**Comment by berendt** [comment]
I tested on Ubuntu 15.10 with `docker-py (1.7.0)` (installed with pip). But it has not worked with the `python-docker` package provided by Ubuntu, too.

**Comment by CaptTofu** [comment]
I have the same error. Docker-py 1.8 dev and Ansible 2.1.0

Just tested with Docker-py 1.8 dev and Ansible 2.0.1.0 and it works.

**Comment by kamsz** [comment]
@kaczynskid pushed a fix that works :+1: :)

**Comment by jmatsushita** [comment]
@kaczynskid Thanks! Your fix work for me!

**Comment by basnijholt** [comment]
Having same issue on Centos 7, Ansible 2.1.0, and pip `docker-py`.

**Comment by lerenn** [comment]
Same issue too (Fedora 23 and Ansible 2.1.0).

**Comment by qwding** [comment]
Same issue on Ubuntu 14.04,Ansible 2.1.0

**Comment by puneetjindal** [comment]
PKMIL if the issue is resolved. I am trying to start the container centos:7 docker image with ansible 1.9

**Comment by puneetjindal** [comment]
@CaptTofu : Can you please share how this problem resolved. Here my piece of code in my tasks file

### ```
- name: Install centos latest docker
  docker:
    name: centos
    image: centos
    state: present
- name: application service
  docker:
    image: centos:7
    name: lab
    state: reloaded

```
```

**Comment by MikeVL** [comment]
I have some error if i set memory_limit via jinja variable:

```
- name: run uwsgi docker container
  docker:
    name: "uwsgi-{{ item.key|replace('_', '-') }}"
    image: "{{ django_container.image }}"
    pull: missing
    expose:
      - "{{ django_container.uwsgi_socket }}"
    ports:
      - "{{ item.value.port }}:{{ django_container.uwsgi_socket }}"
    volumes:
      - "{{ django_container.django_settings }}:/etc/django.conf.py:ro"
      - "/mnt/media:/mnt/media:rw"
    env: "{{ django_container.environment|combine(item.value.get('environment', {})) }}"
    memory_limit: "{{ item.value.get('memory_limit', '0') }}"
    restart_policy: always
    restart_policy_retry: 10
    state: reloaded
    command: "uwsgi {{ item.value.config_name }}"
  with_dict: "{{ uwsgi_backends }}"
```

```
failed: [django1.stack.local] => (item={'value': {u'environment': {u'STATIC_URL': u'/static/'}, u'config_name': u'default_site', u'port': 9104, u'hosts_group': u'uwsgi_backends_ajax'}, 'key': u'ajax'}) => {"failed": true, "item": {"key": "ajax", "value": {"config_name": "default_site", "environment": {"STATIC_URL": "/static/"}, "hosts_group": "uwsgi_backends_ajax", "port": 9104}}, "msg": "Could not convert 0 to integer"}
```
