### ISSUE TITLE
copy module never copies when force is set to no, even if dest file is missing

### ISSUE THREAD

**Issue by jgrigonis** [ansible/ansible-modules-core#3080]
##### Issue Type:

Please pick one and delete the rest:
- Bug Report
##### Plugin Name:

copy
##### Ansible Version:

```
ansible 2.1.0 (devel 11f081cb99) last updated 2016/02/19 11:21:17 (GMT -700)
  lib/ansible/modules/core: (detached HEAD 8d126bd877) last updated 2016/02/11 14:06:38 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD f6c5ed987f) last updated 2016/02/11 14:06:38 (GMT -700)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```
##### Ansible Configuration:

[defaults]
host_key_checking = False
##### Environment:

running from OS X.
managing CentOS 6.7
##### Summary:

Copy module is not copying when I have set 
force: no
This applies when the destination file does not exist
##### Steps To Reproduce:

For bugs, please show exactly how to reproduce the problem. For new
features, show how the feature would be used.

```

---
- hosts: "infrastructure,testservers,devservers,production"
  remote_user: root
  tasks:
    - name: create nrpe cfg
      copy:
        src: files/nrpe.cfg
        dest: /usr/local/nagios/etc/nrpe.cfg
        owner: nagios
        group: nagios
        force: no
```

You can also paste gist.github.com links for larger files.
##### Expected Results:

I expect a file called nrpe.cfg to appear here:
/usr/local/nagios/etc
##### Actual Results:

What actually happened?
The file does not show up.

```
TASK [create nrpe cfg] *********************************************************
ok: [prodgo1]
ok: [prodgo3]
ok: [prodgo2]
ok: [prodgo4]
```
