### ISSUE TITLE
docker : devel head cpu_shares breaks docker-py

### ISSUE THREAD

**Issue by wrouesnel** [ansible/ansible-modules-core#3081]
##### Issue Type:
- Bug Report
##### Plugin Name:

docker
##### Ansible Version:

```
ansible 2.1.0 (devel 11f081cb99) last updated 2016/02/20 18:38:49 (GMT +1100)
  lib/ansible/modules/core: (detached HEAD 8d126bd877) last updated 2016/02/15 03:37:03 (GMT +1100)
  lib/ansible/modules/extras: (detached HEAD f6c5ed987f) last updated 2016/02/15 03:37:03 (GMT +1100)
  config file = 
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

```
[defaults]
nocows = 1
remote_tmp=/tmp

timeout=20

# vault-keyring.py uses the Python 'keyring' module to retrieve and store the
# vault password. This should be reasonably cross-platform and you definitely
# should have a working python environment if you're using this repo.
#vault_password_file = vault-keyring.py

[ssh_connection]
control_path=%(directory)s/%%h-%%r
pipelining=True
```
##### Environment:

N/A
##### Summary:

`cpu_shares` is passed as a string to docker-py, which does not validate it for being a string but which stops it being parsed by the docker daemon (version 1.9 and 1.10 tested).

The following patch fixes the problem in the `docker.py`. It's questionable if this should be fixed in docker-py, but for the purposes of usability this hack it fine.

```
diff --git a/cloud/docker/docker.py b/cloud/docker/docker.py
index bda75f3..db5f3f8 100644
--- a/cloud/docker/docker.py
+++ b/cloud/docker/docker.py
@@ -1774,7 +1774,7 @@ def main():
             devices         = dict(default=None, type='list'),
             memory_limit    = dict(default=0),
             memory_swap     = dict(default=0),
-            cpu_shares      = dict(default=0),
+            cpu_shares      = dict(default=0, type='int'),
             docker_url      = dict(),
             use_tls         = dict(default=None, choices=['no', 'encrypt', 'verify']),
             tls_client_cert = dict(required=False, default=None, type='str'),
```
##### Steps To Reproduce:

Try and deploy a docker image from devel. The following task was being used:

```
  - name: squid container
    docker:
      name: squid
      image: squid3
      state: reloaded
      pull: missing
      restart_policy: always
      ports:
      - "3128:3128"
      volumes:
      - "{{ squid.data_dir }}:/cache"
      env:
        EXTRA: |
          # refresh pattern for debs and udebs
          refresh_pattern deb$   129600 100% 129600
          refresh_pattern udeb$   129600 100% 129600
          refresh_pattern tar.gz$  129600 100% 129600

          # always refresh Packages and Release files
          refresh_pattern \/(Packages|Sources)(|\.bz2|\.gz|\.xz)$ 0 0% 0
          refresh_pattern \/Release(|\.gpg)$ 0 0% 0
          refresh_pattern \/InRelease$ 0 0% 0

          # handle meta-release and changelogs.ubuntu.com special
          # (fine to have this on debian too)
          refresh_pattern changelogs.ubuntu.com/*  0  1% 1
```
##### Expected Results:

The image deploys.
##### Actual Results:

```
PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [monolith]

TASK [squid container] *********************************************************
fatal: [monolith]: FAILED! => {"changed": false, "failed": true, "msg": "Docker API Error: json: cannot unmarshal string into Go value of type int64"}
```
