### ISSUE TITLE
Docker container's state doesn't work on a swarm environment

### ISSUE THREAD

**Issue by tbouvet** [ansible/ansible-modules-core#3107]
##### Issue Type:

Bug Report
##### Plugin Name:

docker
##### Ansible Version:

ansible 2.0.0.2
##### Ansible Configuration:

N/A
##### Environment:

Ubuntu 14.04
##### Summary:

The state of a docker container running in a swarm cluster is not ok.
If a docker container is deployed in a swarm cluster, when the playbook is running again, Ansible try to run again the container so an error occurred: 

```
fatal: [master-1]: FAILED! => {"changed": false, "failed": true, "msg": "Docker API Error: Conflict: The name php-demo-swarm is already assigned. You have to delete (or rename) that container to be able to assign php-demo-swarm to a container again."}
```
##### Steps To Reproduce:

Playbook example:

```
- hosts: master
  tasks:
     - name: Deploy on Swarm Master
       vars:
          docker_cert_path: "/home/ubuntu/.docker"
       docker:
          image: php-test
          state: started
          name: php-demo-swarm
          detach: True
          use_tls: verify
          docker_url: "tcp://localhost:3376"
          tls_ca_cert: "{{ docker_cert_path }}/ca.pem"
          tls_client_cert: "{{ docker_cert_path }}/cert.pem"
          tls_client_key: "{{ docker_cert_path }}/key.pem"
          env:
             "constraint:node==node-1"
          ports:
             - "::80"
```

master-1 is a swam master
node-1 is a swarm agent node included in the cluster.
##### Expected Results:

If this step is running 2 times, the second time it should do nothing because container is already started.
##### Actual Results:

An error:

```
fatal: [master-1]: FAILED! => {"changed": false, "failed": true, "msg": "Docker API Error: Conflict: The name php-demo-swarm is already assigned. You have to delete (or rename) that container to be able to assign php-demo-swarm to a container again."}
```
