### ISSUE TITLE
ec2_vpc remove doesn't work as documented

### ISSUE THREAD

**Issue by mkocikowski** [ansible/ansible-modules-core#3126]
##### Issue Type:

bug report

Module: ec2_vpc
##### Ansible Version:

ansible 2.0.0.2
##### Summary:

Error in documentation: http://docs.ansible.com/ansible/ec2_vpc_module.html#examples
##### Steps To Reproduce:

Documentation states:

```
# Removal of a VPC by id
      ec2_vpc:
        state: absent
        vpc_id: vpc-aaaaaaa
        region: us-west-2
```

However, when run, there is an error:

```
TASK [delete vpc] **************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "missing required arguments: resource_tags"}
```

So it isn't possible to remove a vpc just by stating its id.
