### ISSUE TITLE
Upload binary file possibility in URI module

### ISSUE THREAD

**Issue by mploski** [ansible/ansible-modules-core#3157]
##### Issue Type:
- Feature Idea
##### Plugin Name:

uri
##### Ansible Version:

1.9.2
##### Environment:

N/A
##### Summary:

It would be nice to have option to upload binary file to HTTP endpoint using HTTP PUT. Expecting behaviour similar to following curl command:

```
curl -k -X PUT -u user:password --upload-file  test.jar "https://IP:PORT/endpoint/"
```

and example of possible URI usage:

```
- name: Push jar to nexus
  uri:
    url: "https://{{ inventory_hostname }}:{{ port }}/{{ endpoint }}"
    src: /tmp/{{ file }}.jar
    user: "{{ user }}"
    password: "{{ password }}"
    method: PUT
```
