### ISSUE TITLE
  raw module doesn't support environment: dict

### ISSUE THREAD

**Issue by dch** [ansible/ansible-modules-core#32]
It should be possible to pass environment settings through the raw module, but the raw module does not appear to respect environment: dict settings, e.g. minimal play:

``` yaml
# bootstraps FreeBSD 10 to respect ansible's authority

---
- hosts: bootstrap
  user: root
  gather_facts: no
  tasks:
    - raw: /usr/sbin/pkg -N
      register: pkg
      ignore_errors: True
    - raw: /usr/sbin/pkg bootstrap -f
      environment:
        ASSUME_ALWAYS_YES: 1
      when: pkg|failed
```

Using `env` instead of the `pkg` command shows that ASSUME_ALWAYS_YES is not visible.

FWIW a simple work-around in this case was:

``` yaml
    - raw: env ASSUME_ALWAYS_YES=1 /usr/sbin/pkg bootstrap -f -y
      when: pkg|failed
```

Either this could be documented (I can do this) or the modules should play well together.

(duplicated from https://github.com/ansible/ansible/issues/7692)

@jimi-c commented:

I can reproduce this with this minimal playbook as well:

```

---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - raw: echo $FOO
      environment:
        FOO: "this is foo"
```

**Comment by jctanner** [comment]
Addressed in https://github.com/ansible/ansible/pull/15488

**Comment by ffledgling** [comment]
I recently had to pass `*_proxy` variables for task on a remote box and was forced to use the `raw` module to bootstrap python/python modules for ansible on a remote machine, problem was I couldn't install stuff on the box without a proxy.

Since the environment variables aren't passed to commands run via `raw` and it looks like the PR above only documents this behaviour, I came up with the following work around, which I leave here in case it's useful to someone else:

```
- hosts: ci-server
  gather_facts: no
  become: true
  become_user: root
  environment:
    http_proxy: 'http://my.proxy.mydomain.com:3128'
    https_proxy: 'http://my.proxy.mydomain.com:3128'
    no_proxy: mydomain.com,localhost,0.0.0.0'

  pre_tasks:
    # The setup/gather facts task requires python2-dnf so we install it first
    # and then run the task. Facts are required by the roles.
    # https://stackoverflow.com/questions/31054453/ansible-actions-before-gathering-facts

    - name: Install python
      raw: "http_proxy={{environment[0].http_proxy}} https_proxy={{environment[0].https_proxy}} dnf install -y python2-dnf"

# ...
```
