### ISSUE TITLE
create VM with multiple cdRoms

### ISSUE THREAD

**Issue by tenderitaf** [ansible/ansible-modules-core#3205]
##### Issue Type:

- Bug Report
- Feature Idea
##### Component Name:

vsphere_guest.py/vsphere_guest
##### Ansible Version:

ansible 1.9.1 
##### Summary:

The objectif is to try to create a VM with at least two CDROMs
##### Steps To Reproduce:

This a code snipet of my VM config 

```
vm_hardware:
  memory_mb: "{{ resource_mem_vm }}"
  num_cpus: "{{ resource_cpu_vm }}"
  osid: "{{ vsphere_guestosid }}"
  scsi: "{{ vsphere_guestscsi }}"
  vm_cdrom:
    cdrom1:
    type: "iso"
    iso_path: "/{{ vsphere_file_root_path }}/{{ clusterid }}/cd1.iso"
    cdrom2:
    type: "iso"
    iso_path: "/{{ vsphere_file_root_path }}/{{ clusterid }}/cd2.iso"
```

##### Expected Results:

have a VM with two CDRoms
