### ISSUE TITLE
ec2_vol unable to create volumes of specific size from snapshots

### ISSUE THREAD

**Issue by sgnn7** [ansible/ansible-modules-core#3270]
##### Issue Type:

Bug Report
##### Plugin name

ec2_vol
##### Ansible Version:

2.1.0 from git (cd51ba7965325fd5e7857e4cf2c3725b81b39352)
##### Ansible Configuration:

Default
##### Environment:

Using Ubuntu 15.10 in AWS but this is not affected by OS.
##### Summary:

Some items copied from another user that created [this](https://github.com/ansible/ansible/issues/14007) issue which got closed since it was in the wrong repo but it's pretty much identical:

The changes made to lines 442/443 in this pull request (https://github.com/ansible/ansible-modules-core/pull/1747/files) break the logic, making it so that the user can no longer create a volume of a specific size out of a snapshot.

Lines from pull request:
ORIGINAL: `if volume_size and id:`
NEW BROKEN: `if volume_size and (id or snapshot):`
##### Steps To Reproduce:

Test Playbook:

```
- name: Create volume and attach to this instance
  register: new_volume
  ec2_vol:
    state:  present
    region: XXXXX
    instance: XXXXX
    volume_size: 30
    snapshot: snap-XXXX
    device_name: /dev/sdX
```

Comment out the volume_size and you get a volume the size of the snapshot (1GB) instead of the 30 GB but with that flag there, you get errors about wrong parameters.
##### Expected results:

Successfully creates the 30 GB volume out of the 1GB snapshot
##### Actual Results:

```
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Cannot specify volume_size together with id or snapshot"}
```
