### ISSUE TITLE
size parameter required set to be no when state is absent in os_volume

### ISSUE THREAD

**Issue by tapanswain-zz** [ansible/ansible-modules-core#3278]
##### Issue Type:
- Documentation Report
##### Plugin Name:

os_volume 
##### Ansible Version:

```
2.4
```
##### Environment:

centos 6
##### Summary:

def _absent_volume(module, cloud):
    try:
        cloud.delete_volume(
            name_or_id=module.params['display_name'],
            wait=module.params['wait'],
            timeout=module.params['timeout'])

No need to add size parameter while calling os_volume as delete_volume function does not need size parameter .   http://docs.ansible.com/ansible/os_volume_module.html  this document needs to be modified. 
size parameter required set to be 'NO' when state is absent in os_volume  
##### Steps To Reproduce:

``````
<!-- (Paste example playbooks or commands here)  -->
``` - name: "Delete Volumes attached"
      os_volume:
        state: "absent"
        display_name: "{{ item.id }}"
        timeout: "360"
        auth:
          auth_url: "{{ openstack_auth_url }}"
          username: "{{ openstack_username }}"
          password: "{{ openstack_password }}"
          project_name: "{{ openstack_tenant }}"
      environment:
        OS_VOLUME_API_VERSION: "1"
        OS_IMAGE_API_VERSION: "1"
        security_groups: default

<!-- You can also paste gist.github.com links for larger files.  -->

##### Expected Results:

<!-- What did you expect to happen when running the steps above?  -->

##### Actual Results:

<!-- What actually happened? If possible run with high verbosity (-vvvv) -->

``````

```
```
