### ISSUE TITLE
Handler not firing

### ISSUE THREAD

**Issue by grahamrhay** [ansible/ansible-modules-core#3309]
- Bug Report
##### COMPONENT NAME

Notify
##### ANSIBLE VERSION

```
ansible 2.0.0.2
  config file =
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

Default
##### OS / ENVIRONMENT

Debian Jessie
##### SUMMARY

Config file is updated but handler does not fire
##### STEPS TO REPRODUCE

We used to have all the handlers at the top level (handlers/main.yml) but have now moved them into individual roles (roles/bar/handlers/main.yml) and referenced them from the playbook:

```
- hosts: "app_servers:&{{ target_environment }}"
  serial: 1
  roles:
    - foo
  handlers:
    - include: roles/bar/handlers/main.yml
```

Even though the task with the notify was marked as "changed", the handler was not run. Other handlers at the top level, or in the role being applied, work as expected.

Is this not supported in some way?
