### ISSUE TITLE
acl: entity did not take effect

### ISSUE THREAD

**Issue by jbd** [ansible/ansible-modules-core#331]
Hi,

I'm using ansible 1.7.2.

I'm not able to use the ACL module. I'm trying to apply a default acl to a directory (/data/media) using a specific group (homeusers) :

Here is what I've got :

```
$ getfacl /data/media
getfacl: Removing leading '/' from absolute path names
# file: data/media
# owner: root
# group: root
user::rwx
group::r-x
other::r-x
```

Here is my task :

```
- name: set acls on /data/media                                                      
  acl: name=/data/media entity=homeusers default=yes etype=group permissions=rwx
```

But there is no change :

```
ok: [media] => {"acl": ["user::rwx", "group::r-x", "other::r-x"], "changed": false, "msg": "current acl"}
```

I'm expecting something like that :

```
$ setfacl -d -m g:homeusers:rxw /data/media
$ getfacl /data/media
getfacl: Removing leading '/' from absolute path names
# file: data/media
# owner: root
# group: root
user::rwx
group::r-x
other::r-x
default:user::rwx
default:group::r-x
default:group:homeusers:rwx
default:mask::rwx
default:other::r-x
```

Am I missing something ?

**Comment by bcoca** [comment]
confirmed, it is a bug

**Comment by autotune** [comment]
I can confirm this is still present in the 2.1.0 devel version of ansible:

```
[autotune@ansibledev 331]$ ansible --version|head -n1
ansible 2.1.0 (devel 15135f3c16) last updated 2015/12/16 16:15:58 (GMT -700)

ok: [10.0.2.15] => {"acl": [], "changed": false, "invocation": {"module_args": {"default": "yes",     "entity": "ansibledev", "etype": "group", "name": "/home/autotune/dev/issues/331/test", "permissions": "rwx"}, "module_name": "acl"}, "msg": "current acl"}


[autotune@ansibledev 331]$ getfacl test/
# file: test/
# owner: autotune
# group: ansibledev
# flags: -s- 
user::rwx
user:autotune:r-x
group::r-x
mask::r-x
other::r-x
```

and am looking into it (if this should change I'll delete this comment). 

EDIT: 

@bcoca @jbd 

This works when state=present is enabled as follows:

---

```
- hosts: [local]
 tasks:
   - name: set_acls_on_test
     acl: name=/home/autotune/dev/issues/331/testing entity=ansibledev default=yes etype=group permissions=rwx state=present
...
```

The documentation on this matter is definitely not clear as it states this is not a required parameter: 

```
state:
  required: false
  default: query
  choices: [ 'query', 'present', 'absent' ]
  description:
    - defines whether the ACL should be present or not.  The C(query) state gets the current acl without changing it, for use in 'register' operations.
```

so the question that remains is if this module should be making a change by default to match the documentation, or if the documentation should be updated to note that state=present is required. 

Also pinging @robynbergeron to see if this can get a community_review tag as well and @mpdehaan for any additional thoughts. Would be a fairly easy fix as it's just a matter of changing the default key value in the state dict to a string like  'empty', and changing the line "if state==present" line to "if state==present or 'empty' ".
