### ISSUE TITLE
ops_template.py: Take care of json src variable

### ISSUE THREAD

**Issue by keithnoguchi** [ansible/ansible-modules-core#3312]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

ops_template.py
##### ANSIBLE VERSION

```
air$ ansible-playbook --version
ansible-playbook 2.1.0
  config file = /usr/local/git/github.com/dc-on-docker/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

As mentioned in [ansible/ansible #15133](https://github.com/ansible/ansible/issues/15133), configuring OpenSwitch through the [OpenSwitch switch role](https://github.com/keinohguchi/ops-switch-role).
##### OS / ENVIRONMENT

Reproduced on ArchLinux control machine, just like [ansible/ansible #15133](https://github.com/ansible/ansible/issues/15133).
##### SUMMARY

Call `module.from_json` in case of `dc` or `rest` transport case.
##### STEPS TO REPRODUCE

```

---
- name: fabric switches
  hosts: fabrics
  gather_facts: yes
  vars:
    ansible_user: admin
    ops_system_hostname: "{{ inventory_hostname }}"
    ops_debug: no
  roles:
    - role: switch
      ops_intf_admin_state: up

- name: spine switches
  hosts: spines
  gather_facts: yes
  vars:
    ansible_user: admin
    ops_system_hostname: "{{ inventory_hostname }}"
    ops_debug: no
  roles:
    - role: switch
      ops_intf_admin_state: up

- name: leaf switches
  hosts: leaves
  gather_facts: yes
  vars:
    ansible_user: admin
    ops_system_hostname: "{{ inventory_hostname }}"
    ops_debug: no
  roles:
    - role: switch
      ops_intf_admin_state: up
```
##### EXPECTED RESULTS

Configure the OPS switch both through DC or REST APIs.
##### ACTUAL RESULTS

```
air$ play site.yaml

PLAY [fabric switches] *********************************************************

TASK [setup] *******************************************************************
ok: [fab1]

TASK [switch : print JSON input for this play] *********************************
skipping: [fab1]

TASK [switch : configure the switch] *******************************************
fatal: [fab1]: FAILED! => {"changed": false, "failed": true, "msg": "argument src is of type <type 'str'> and we were unable to convert
to dict"}
```
