### ISSUE TITLE
OpenStack os_server module defines auto_ip and floating_ip_pools as mutually exclusive

### ISSUE THREAD

**Issue by sebastianreloaded** [ansible/ansible-modules-core#3314]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

/cloud/openstack
##### ANSIBLE VERSION

```
ansible 2.0.0.2
  config file = /Users/sebastian/helpers/ansible/ansible-projects.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

The os_server module doesn't allow auto_ip and floating_ip_pools to be defined together.
This prevents me to programmatically decide whether to assign an floatingip or not.
##### STEPS TO REPRODUCE

I setup multiple servers, some of which should receive a floatingip, some don't.
So i define a var floating_ip_pool per server. If it is not set, i want to disable floatingip assignment via auto_ip: no and floating_ip_pools: no.

```
 - name: Generate instances for all defined servers
   os_server:
     name: "{{ item }}"
     image: "{{ os_image }}"
     floating_ip_pools: "{{ item.floating_ip_pool | default(no) }}"
     auto_ip: "{% if item.floating_ip_pool is defined %}yes{% else %}no{% endif %}"
   with_items: "{{groups.all}}"
```
##### EXPECTED RESULTS

I want all servers with auto_ip: no not have a floatingip, no matter what is defined in floating_ip_pools.
##### ACTUAL RESULTS

Ansible won't allow me to define both parameters at once, so there is no way to handle this use case programatically.

```
TASK [os-server : Generate instances for all defined servers] ********
failed: [localhost] => (item=my-server0) => {"failed": true, "item": "my-server0", "msg": "parameters are mutually exclusive: ['auto_ip', 'floating_ip_pools']"}
```

**Comment by sebastianreloaded** [comment]
The responsible code is here: https://github.com/ansible/ansible-modules-core/blob/devel/cloud/openstack/os_server.py#L570

```
    module_kwargs = openstack_module_kwargs(
        mutually_exclusive=[
            ['auto_ip', 'floating_ips'],
            ['auto_ip', 'floating_ip_pools'],
            ['floating_ips', 'floating_ip_pools'],
            ['flavor', 'flavor_ram'],
            ['image', 'boot_volume'],
            ['boot_from_volume', 'boot_volume'],
            ['nics', 'network'],
        ],
        required_if=[
            ('boot_from_volume', True, ['volume_size', 'image']),
        ],
    )
```

**Comment by Shrews** [comment]
Thanks for the report.

This isn't really a bug in os_server since the mutual exclusivity is intentional, but, rather, a roadblock with your current workflow. And I think it is possible to do this programmatically.

I'd suggest splitting this task into two separate ones: one that uses auto_ip and one that uses floating_ip_pools, then use the 'when' conditional to decide which one to execute. Something like:

```
 - name: Generate instances for all defined servers with a pool
   os_server:
     name: "{{ item }}"
     image: "{{ os_image }}"
     floating_ip_pools: "{{ item.floating_ip_pool }}"
   with_items: "{{groups.all}}"
   when: item.floating_ip_pool is defined

 - name: Generate instances for all defined servers without a pool
   os_server:
     name: "{{ item }}"
     image: "{{ os_image }}"
     auto_ip: true
   with_items: "{{groups.all}}"
   when: item.floating_ip_pool is undefined
```

I think this (or some properly tested variant) will work for you. Give it a shot and let us know.

**Comment by sebastianreloaded** [comment]
Thanks for the reply, i understand that it was intentional and not a bug in the usual sense.
I already thought about your solution, but that would lead to a lot of code duplication, as my os_server abstraction is more complex than the simple example playbook i posted.

Ansible will call add_ips_to_server in openstack/shade and it takes both parameters (https://github.com/openstack-infra/shade/blob/master/shade/openstackcloud.py#L3330). 
Also it looks like ansible has no code that really needs this restriction (https://github.com/ansible/ansible-modules-core/blob/devel/cloud/openstack/os_server.py#L491).

I didnt test it with shade myself, but as far as i understand the code the only reason for this behavior is to prevent the case of getting a floatingip when you set auto_ip to no, but still define a floating_ip_pool. All other cases would still work:
- auto_ip: yes floating_ip_pool: pool1
- auto_ip: yes floating_ip_pool: no
- auto_ip: no floating_ip_pool: no

I don't question the good intention, but it seems ansible users should  be able to figure that out by themselves. And i could prevent unnecessary code duplication which would be prone to bugs.
what do you think?

**Comment by stefanandres** [comment]
To better show how complex it gets, this is a more realistic scenario (and the example is not even using all needed parameters for all cases, such as userdata). As you can see there is a lot of duplicate code. The code is getting out of hand quickly.

```
- name: Generate instances for all defined servers (with fip)
  os_server:
    state: present
    name: "{{ item }}"
    image: "{{ hostvars[item].os_image | default(os_image) }}"
    flavor: "{{ hostvars[item].os_flavor | default(os_flavor) }}"
    floating_ip_pools: "{{ os_floating_ip_pools }}"
    key_name: "{{ os_key_name }}"
    security_groups: "{{ os_security_groups + hostvars[item].os_security_groups | default(os_security_groups) }}"
    nics:
      - net-name: "{{ os_net_name }}"
    wait: True
  with_items: "{{ groups.all }}"
  when:
    - item != 'localhost'
    - hostvars[item].use_jumphost is undefined
  register: instances_with_fip

- name: Generate instances for all defined servers (without fip)
  os_server:
    state: present
    name: "{{ item }}"
    image: "{{ hostvars[item].os_image | default(os_image) }}"
    flavor: "{{ hostvars[item].os_flavor | default(os_flavor) }}"
    key_name: "{{ os_key_name }}"
    auto_ip: no
    security_groups: "{{ os_security_groups + hostvars[item].os_security_groups | default(os_security_groups) }}"
    nics:
      - net-name: "{{ os_net_name }}"
    wait: True
  with_items: "{{ groups.all }}"
  when:
    - item != 'localhost'
    - hostvars[item].use_jumphost is defined
  register: instances_without_fip

- name: Add needed attributes from openstack response
  add_host:
    name: "{{ item.openstack.name }}"
    ip_address: "{% if hostvars[item.openstack.name].use_jumphost is defined and hostvars[item.openstack.name].use_jumphost != 'no' %}{{ item.openstack.private_v4 }}{% else %}{{ item.openstack.public_v4 }}{% endif %}"
  with_items:
    - "{{ instances_with_fip.results }}"
    - "{{ instances_without_fip.results }}"
  changed_when: False
  when: item.skipped is undefined
  no_log: True
```
