### ISSUE TITLE
ops_template.py: content argument to take the yaml/json variable

### ISSUE THREAD

**Issue by keithnoguchi** [ansible/ansible-modules-core#3340]
##### ISSUE TYPE
- Feature Idea
##### COMPONENT NAME

network/openswitch/ops_template.py
##### ANSIBLE VERSION

```
ansible 2.1.0
  config file = /Users/kei/vagrant/ansible/dc-on-docker/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

Here is the sample way of passing YAML variable to ops_template module through content:

```
- name: configure through json
  hosts: switch
  become: yes
  vars:
    config:
      system:
        hostname: test
  tasks:
    - ops_template:
      content: "{{ config }}"
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Since the `src` variable of `ops_template` is for the file name, we want to have another variable
to pass the actual content, hence, `content` variable. :)
