### ISSUE TITLE
cloud/docker: field 'registry' ignored when pulling image

### ISSUE THREAD

**Issue by elouanKeryell-Even** [ansible/ansible-modules-core#3419]
##### ISSUE TYPE

 Bug Report
##### COMPONENT NAME

docker
##### ANSIBLE VERSION

```
ansible 2.1.0 (devel 22467a0de8) last updated 2016/04/13 11:42:21 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 99cd31140d) last updated 2016/04/13 11:42:31 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD ab2f4c4002) last updated 2016/04/13 11:42:40 (GMT +200)
  config file =
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

Patched ansible to work around issue #3078 (= #3039). Patched following this comment: https://github.com/ansible/ansible-modules-core/issues/3078#issuecomment-201139661 :

```
curl https://github.com/kaczynskid/ansible-modules-core/commit/46970d6d7add50780e8cedb5067ae5d29a763141.patch | patch /root/installs/ansible/lib/ansible/modules/core/cloud/docker/docker.py
```
##### OS / ENVIRONMENT

CentOS 7

docker version: 1.10.3
docker api version: 1.22

docker-py version: 1.8.0
##### SUMMARY

field `registry` doesn't seem to be taken into account in module docker. Even when specifying a registry, it tries to pull from the default one (docker.io).
##### STEPS TO REPRODUCE

playbook.yml

```

---
-
  hosts: all
  tasks:
    -
      name: run etcd container
      docker:
        image: coreos/etcd
        state: present
        registry: quay.io
```

inventory

```
localhost ansible_connection=local
```

command

```
$ ansible-playbook -vvv -i inventory playbook.yml
```

##### EXPECTED RESULTS

Pull image `quay.io/coreos/etcd`. In docker logs (with daemon on debug log level, option `-D` ), this would print:

```
level=debug msg="Trying to pull quay.io/coreos/etcd from https://quay.io v2"
```
##### ACTUAL RESULTS

Tries to pull image from default registry `docker.io`. In docker logs, it prints:

```
level=debug msg="Trying to pull coreos/etcd from https://index.docker.io v1"
```

Ansible output

```
TASK [run etcd container] ******************************************************
fatal: [localhost]: FAILED! => 
{
   "changed":false,
   "changes":[
      "{\"status\":\"Pulling repository docker.io/coreos/etcd\"}\r\n",
      "{\"errorDetail\":{\"message\":\"Error: image coreos/etcd not found\"},\"error\":\"Error: image coreos/etcd not found\"}\r\n"
   ],
   "failed":true,
   "invocation":{
      "module_args":{
         "cap_add":null,
         "cap_drop":null,
         "command":null,
         "count":1,
         "cpu_set":null,
         "cpu_shares":0,
         "debug":false,
         "detach":true,
         "devices":null,
         "dns":null,
         "docker_api_version":"1.22",
         "docker_url":null,
         "docker_user":null,
         "domainname":null,
         "email":null,
         "entrypoint":null,
         "env":null,
         "env_file":null,
         "expose":null,
         "extra_hosts":null,
         "hostname":null,
         "image":"coreos/etcd",
         "insecure_registry":false,
         "labels":{

         },
         "links":null,
         "log_driver":null,
         "log_opt":null,
         "lxc_conf":null,
         "memory_limit":"0",
         "memory_swap":"0",
         "name":null,
         "net":null,
         "password":null,
         "pid":null,
         "ports":null,
         "privileged":false,
         "publish_all_ports":false,
         "pull":"missing",
         "read_only":null,
         "registry":"quay.io",
         "restart_policy":null,
         "restart_policy_retry":0,
         "signal":null,
         "state":"present",
         "stdin_open":false,
         "stop_timeout":10,
         "timeout":60,
         "tls_ca_cert":null,
         "tls_client_cert":null,
         "tls_client_key":null,
         "tls_hostname":null,
         "tty":false,
         "ulimits":null,
         "use_tls":null,
         "username":null,
         "volumes":null,
         "volumes_from":null
      },
      "module_name":"docker"
   },
   "msg":"Unrecognized status from pull.",
   "status":""
}
```
#### COMMENTS

It works fine with a straight `docker pull`:

```
$ docker pull quay.io/coreos/etcd
Using default tag: latest
latest: Pulling from coreos/etcd
2dc473c309a3: Pull complete
e5b396cd4514: Pull complete
Digest: sha256:150ff52a0b1b4332e56e598881a9ca68454a3b727c82431bbe229f986845d7ab
Status: Downloaded newer image for quay.io/coreos/etcd:latest
```

It works fine without using field `registry` in the playbook (specifying the registry url directly in field `image`):

```

---

-
  hosts: all
  tasks:
    -
      name: run etcd container
      docker:
        image: quay.io/coreos/etcd
        state: present
```

**Comment by elouanKeryell-Even** [comment]
Here is function `pull_image` from source file https://github.com/ansible/ansible-modules-core/blob/devel/cloud/docker/docker.py :

```
    def pull_image(self):

        extra_params = {}
...
...
...
        resource = self.module.params.get('image')
            image, tag = get_split_image_tag(resource)
        if self.module.params.get('username'):
            try:
                self.client.login(
                    self.module.params.get('username'),
                    password=self.module.params.get('password'),
                    email=self.module.params.get('email'),
                    registry=self.module.params.get('registry')
                )

...
...
...
        try:
            changes = list(self.client.pull(image, tag=tag, stream=True, **extra_params))
...
...
...
```

Parameter `registry` seems to be used uniquely for login, not for pulling.

**Comment by elouanKeryell-Even** [comment]
According to the docs, it seems that docker-py `pull` doesn't take any registry argument. So I guess field `registry` in ansible's docker module isn't meant to be used for pull purposes but for login purposes. IMO the doc is confusing since it presents the `registry` field as the "remote registry URL to pull images from".

**Comment by stephanarts** [comment]
Shouldn't it be filling in the registry as part of the repository then?

http://my-registry:5000/repo-name

Docker is a bit ambiguous about repositories and registries, but a registry is part of the repository url.

**Comment by WinstonSureChill** [comment]
Yep, that's how I do and it works fine.

**Comment by nungster** [comment]
I am having the same problem and tried many combinations of having a registry entry or not.  I pass in the variables using --extra-vars and still no pull.  I've verified I can pull the image locally and on the server I am trying to run this playbook against.  Here is the excerpt:

```
   # Create the Grafana container
   - name: Creating the Grafana Container
     become: true
     become_method: sudo
     docker:
       name: grafana
       image: quay.io/mycompany/grafana-graphite:dev
       registry: "https://quay.io"
       username: "{{ docker_username }}"
       email: "{{ docker_email }}"
       password: "{{ docker_password }}"
       detach: true
       state: running
       volumes_from: grafana-storage
       ports:
       - 3000:3000
       - 80:80
       - 2003:2003
       - 2004:2004
       - 2023:2023
       - 2024:2024
       - 8125:8125/udp
       - 8126:8126
```
