### ISSUE TITLE
pip fails when installing a local python package

### ISSUE THREAD

**Issue by mmulich** [ansible/ansible-modules-core#3426]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

pip
##### ANSIBLE VERSION

```
ansible 2.0.1.0
  config file = 
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Installation of local Python packages using the pip module fails. For example, from within the local package's root, `pip install -e .` or `pip install -e .[feature]`.
##### STEPS TO REPRODUCE

Given an archived package installed on a server and unpacked to say `/tmp/requests`, install this package using the pip module.

``` yml
- name: failed local python package install
  hosts: all
  tasks:
    - name: acquire source via the tarball
      become: yes
      unarchive:
        src: "https://pypi.python.org/packages/source/m/mock/mock-2.0.0.tar.gz"
        dest: "/var/tmp/"
        copy: no
    - name: install
      become: yes
      pip:
        name: ".[feature]"
        editable: yes
        chdir: "/var/tmp/mock-2.0.0"
        state: present
```
##### EXPECTED RESULTS

Installation of the local python package as a editable/development package.
##### ACTUAL RESULTS

With the addition of the `extras_require` in the package's `setup.py`, `[feature]` in the example, the module attempts to download the package rather than install from the local directory.

```
fatal: [example.com]: FAILED! => {"changed": false, "cmd": "/usr/bin/pip install .[feature]", "failed": true, "invocation": {"module_args": {"chdir": "/var/tmp/mock-2.0.0", "editable": true, "executable": null, "extra_args": null, "name": ".[feature]", "requirements": null, "state": "present", "use_mirrors": true, "version": null, "virtualenv": null, "virtualenv_command": "virtualenv", "virtualenv_python": null, "virtualenv_site_packages": false}, "module_name": "pip"}, "msg": "stdout: Downloading/unpacking .[feature]\n  Could not find any downloads that satisfy the requirement .[feature]\nCleaning up...\nNo distributions at all found for .[feature]\nStoring debug log for failure in /root/.pip/pip.log\n"}
```

Editable was set to `true`, but it is ignored. Looking at the code, I can see this is because the editable check is part of a compound condition that also checks if the package name containing a VCS prefix. As such, the editable flag `-e` is never applied to the command.

Note, the `mock` package doesn't actually have a requirements extra called "feature", but that's not the point. The internals of pip/setuptools will happily ignore the extra if it doesn't exist.
