### ISSUE TITLE
rax module not idempotent when creating single instance without group

### ISSUE THREAD

**Issue by tuuling** [ansible/ansible-modules-core#3434]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

```
rax
```
##### ANSIBLE VERSION

```
ansible 2.1.0 (devel)
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

When creating a single instance without group and exact_count the command is not idempotent as is expected.
##### STEPS TO REPRODUCE

Run the following code twice.

```

    - name: Server create request
      local_action:
        module: rax
        credentials: ~/.raxpub
        name: asdf
        flavor: general1-1
        image: cf16c435-7bed-4dc3-b76e-57b09987866d #Debian 8
        disk_config: manual
        networks:
          - private
          - public
        region: IAD
        state: present
        meta:
          groups:
            - asdf1
            - web
      register: rax
```

##### EXPECTED RESULTS

Should create only 1 instance.
##### POSSIBLE CAUSE

When looking into the code itself. It checks for matching metadata to confirm if the server(s) match.
line 688 in rax.py

```
if server.metadata != meta
```

When creating the server it shows the metadata as 

```
            "rax_metadata": {
                "groups": "asdf1,web", 
            },
```

When I use rax_facts on the same machine after creation it shows as:

```
            "rax_metadata": {
                "groups": "asdf1,web", 
                "rax_service_level_automation": "Complete"
            }, 
```

I can only assume that this addtional item in metadata fails the check and server.metadata can never equal meta supplied as the argument.
