### ISSUE TITLE
synchronize, implement option for specifying ssh_args (not reading from config)

### ISSUE THREAD

**Issue by stefanandres** [ansible/ansible-modules-core#3539]
##### ISSUE TYPE

- Feature Idea
##### COMPONENT NAME

synchronize
##### ANSIBLE VERSION

```
ansible 2.0.1.0
```
##### SUMMARY

There are several methods of configuring ssh_args in ansible.
Currently, we do it generate a custom ssh_config per inventory.
Because of that our inventories look like

```
server1 ansible_ssh_common_args="-F .ssh_config_live"
server2 ansible_ssh_common_args="-F .ssh_config_live"
```

Other inventories look like

```
server1 ansible_ssh_common_args="-F .ssh_config_dev"
server2 ansible_ssh_common_args="-F .ssh_config_dev"
```

This works fine, as long as you don't use synchronize. Currently there is only the use_ssh_args option which only reads the ssh_args value from the ansbile configuration file.
Source: [synchronize.py](https://github.com/ansible/ansible/blob/65856f2231f4a74e0a8c72ab5e61ec042ff0eaf1/lib/ansible/plugins/action/synchronize.py#L324-L325)
##### EXPECTED RESULTS

I'd expect to an option to actually set the ssh_args myself for the synchronize module.
##### ACTUAL RESULTS

I have to use a workaround for now. I overwrite the rsync -e by using rsync_opts:

```
    - name: "Synchronize abc content from remote server to localhost"
      synchronize:
        use_ssh_args: yes
        archive: yes
        times: yes
        dest: "{{ foo_path }}"
        src: "{{ item }}"
        mode: pull
        rsync_opts:
          - "--delete"
          - "-e 'ssh -F .ssh_config_{{ my_dynamic_part }} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'"
      with_items:
        - /var/lib/abc/repositories/magnolia
```
