### ISSUE TITLE
Fatal: invalid key specified: <!DOCTYPE html> 

### ISSUE THREAD

**Issue by gvenka008c** [ansible/ansible-modules-core#3554]
ISSUE TYPE

Bug Report

ANSIBLE VERSION
# ansible --version

ansible 2.0.0.2
OS / ENVIRONMENT

SUMMARY

```
- name: Add SSH Keys for user from github
authorized_key: user=username key=https://github.com/username.keys
tags: add_admin_user
```

Error: 
fatal: [067cea8f-3725-40ff-aa02-675c54d988da]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"exclusive": false, "key": "https://github.com/username.keys", "key_options": null, "keyfile": "/home/username/.ssh/authorized_keys", "manage_dir": true, "path": null, "state": "present", "unique": false, "user": "username"}, "module_name": "authorized_key"}, "msg": "invalid key specified: <!DOCTYPE html>"}

**Comment by chouseknecht** [comment]
Not able to reproduce. 

Here's my ansible version:

```
ansible 2.0.0.2 (stable-2.0.0.1 3b5d7400de) last updated 2016/04/27 11:28:25 (GMT -400)
  lib/ansible/modules/core: (detached HEAD ce6619bf5d) last updated 2016/04/27 11:28:52 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 29af26884e) last updated 2016/04/27 11:28:58 (GMT -400)
  config file =
  configured module search path = Default w/o overrides
```

Here's my playbook:

```
- name: Test authorized keys
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Add SSH Keys for user from github
      authorized_key: user=vagrant key=https://github.com/chouseknecht.keys
```

I ran my test on Centos 7. Wondering if this could be an OS specific bug. On which OS and version are you experiencing the error?
