### ISSUE TITLE
[2.0.2] SCM Updates with submodules always fail

### ISSUE THREAD

**Issue by leigh-johnson** [ansible/ansible-modules-core#3555]
### Summary

ref ansible/ansible-tower#1694

Sorry about the Tower repro steps on this one! @mckerrj indicated I should preserve the original context that this bug was discovered in.

If an SCM Update includes any git submodules, the job will fail 100% of the time. 
### Environment
- Tower version: 3.0.0 rev `855245d1839bbb9570c19414bbdb6265546b1bc5`
- Ansible version:  2.0.2
- Operating System: Ubuntu 14.04
- Web Browser: Version 49.0.2623.112 (64-bit)
#### via SSH / git://
1. Create a valid SCM Credential with a private key
2. Create a new project. Supply `git@github.com:leigh-johnson/ping.git` as the SCM URL. Supply the Credential created above. 
3. Save & Start an SCM Update
#### via HTTPS
1. Create a valid SCM Credential with a Github username/password pair.
2. Create a new project. Supply `https://github.com/leigh-johnson/ping.git` as the SCM URL. Supply the Credential created above. 
3. Save & Start an SCM Update
#### Notice

Both cases fail identically. 

**STDOUT** from the SCM Update job run:

```
Identity added: /tmp/ansible_tower_sHDMoa/scm_credential (/tmp/ansible_tower_sHDMoa/scm_credential)
Using /etc/ansible/ansible.cfg as config file

PLAY [all] *********************************************************************

TASK [delete project directory before update] **********************************
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}

TASK [update project using git and accept hostkey] *****************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to init/update submodules: Submodule 'modules' (git@github.com:leigh-johnson/ping_2.git) registered for path 'modules'\nSubmodule path 'modules': checked out 'ae640f0712da02277076fbff92467934000d3d14'\nCloning into 'modules'...\nfatal: Not a git repository: ../.git/modules/modules\nfatal: Not a git repository: ../.git/modules/modules\nfatal: Not a git repository: ../.git/modules/modules\nfatal: Not a git repository: ../.git/modules/modules\nfatal: Not a git repository: ../.git/modules/modules\n\nFailed to recurse into submodule path 'modules'\n"}

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @project_update.retry

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    
```

**Comment by chouseknecht** [comment]
Here is the playbook being executed in the above example:

```
---

# The following variables will be set by the runner of this playbook:
# project_path: PROJECTS_DIR/_local_path_
# scm_type: git|hg|svn
# scm_url: https://server/repo
# scm_branch: HEAD
# scm_clean: true/false
# scm_delete_on_update: true/false
# scm_username: username (only for svn)
# scm_password: password (only for svn)
# scm_accept_hostkey: true/false (only for git)

- hosts: all
  connection: local
  gather_facts: false
  tasks:

    - name: delete project directory before update
      file: path={{project_path|quote}} state=absent
      when: scm_delete_on_update|default('')

    - name: update project using git and accept hostkey
      git: dest={{project_path|quote}} repo={{scm_url|quote}} version={{scm_branch|quote}} force={{scm_clean}} accept_hostkey={{scm_accept_hostkey}}
      when: scm_type == 'git' and scm_accept_hostkey is defined

    - name: update project using git
      git: dest={{project_path|quote}} repo={{scm_url|quote}} version={{scm_branch|quote}} force={{scm_clean}}
      when: scm_type == 'git' and scm_accept_hostkey is not defined
```
