### ISSUE TITLE
get_url hides netrc failures 

### ISSUE THREAD

**Issue by larsks** [ansible/ansible-modules-core#3563]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

`get_url` from `ansible-modules-core` @ 22ce32dd93874b7722762a2c38004c15efbf893c
##### ANSIBLE VERSION

ansible 2.2.0 (258d6fcddf51d1abcc7bfea4e1304aaf4d67d67c)
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Calls to `get_url` can fail because of problems with `$HOME/.netrc`,
and when fetching `file://` URLs these errors are not correctly
reported to the user.
##### STEPS TO REPRODUCE

Create a `.netrc` file with open permissions:

```
echo machine host.example.com login you@example.com password secret \
  > $HOME/.netrc
chmod 664 $HOME/.netrc
```

Try fetching a `file://` URL:

```
- hosts: localhost
  gather_facts: false
  tasks:

    - get_url:
        url: file:///etc/motd
        dest: "./destfile"
        force: true
```

Compare this to fetching an `http://` URL:

```
- hosts: localhost
  gather_facts: false
  tasks:

    - get_url:
        url: "http://google.com/"
        dest: "./destfile"
        force: true
```
##### EXPECTED RESULTS

I expect ansible to fail with a warning about the permissions on the
`$HOME/.netrc` file:

```
fatal: [localhost]: FAILED! => {"changed": false, "dest":
"./destfile", "failed": true, "gid": 1000, "group": "lars",
"mode": "0664", "msg": "Request failed", "owner": "lars",
"response": "An unknown error occurred: ~/.netrc access too
permissive: access permissions must restrict access to only the
owner (/home/lars/.netrc, line 1)", "secontext":
"unconfined_u:object_r:user_home_t:s0", "size": 12, "state":
"file", "status_code": -1, "uid": 1000, "url":
"http://google.com/"}
```
##### ACTUAL RESULTS

Ansible fails with an error that doesn't seem to mean anything to
anybody:

```
fatal: [localhost]: FAILED! => {"changed": false, "failed": true,
"msg": "failed to create temporary content file: 'NoneType' object
has no attribute 'read'"}
```
