### ISSUE TITLE
Apt module -  the possibilty to know if a debian package is present or not 

### ISSUE THREAD

**Issue by ronron22** [ansible/ansible-modules-core#3565]
##### ISSUE TYPE
- Feature Idea
##### COMPONENT NAME

apt
##### ANSIBLE VERSION

```
ansible --version
ansible 2.0.2.0
  config file = 
  configured module search path = Default w/o override
```
##### CONFIGURATION

No files and no env
##### OS / ENVIRONMENT

```
lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.4 (jessie)
Release:        8.4
Codename:       jessie
```
##### SUMMARY

Just for obtain an little feature : the possibilty to know if a debian package is present or not .

After, if the condition is true, we can register the package version.

Because, using the shell module is dirty :+1: 

```
 - name: test version
   shell: haproxy -v  | awk '$0 ~ /HA-Proxy/ {print$3}'
   register: haproxyversion
   tags:
      - status
 - name: status of backends
   shell:  echo "show servers state" | nc localhost 666 | grep -Ev "^1|^#|^$" | awk '{print"frontend:"" "$2" ""backend:"" "$4" ""ip:"" "$5" ""status:"" "$6}'
   register: haproxyout
   when: haproxyversion.stdout.find('1.6') != -1
   tags: 
      - status
```
##### STEPS TO REPRODUCE

It's not  a bug
##### EXPECTED RESULTS

It's not  a bug
##### ACTUAL RESULTS

It's not  a bug
