### ISSUE TITLE
get_url change mode doesn't seem to work

### ISSUE THREAD

**Issue by markmurray0** [ansible/ansible-modules-core#3622]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

get_url
##### ANSIBLE VERSION

```
ansible 2.0.0.2
  config file = /home/<redacted>/repos/devops/trunk/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

None
##### OS / ENVIRONMENT

CentOS release 6.5 (Final)
##### SUMMARY

It appears get_url does not do anything in check mode.  No matter how I change destination_file (owner, permissions, content), it will never report any issue in check mode.
##### STEPS TO REPRODUCE

Define a file using the get_url module, change the destination_file on the remote host, run playbook in check mode.  Nothing happens.  But if I run not in check mode, it is reported as changed and correctly replaced.

```
- name: SSH Config
  get_url:
    url: "{{ some_repo }}/ssh_keys/username/config"
    url_username: "{{ username }}"
    url_password: "{{ password }}"
    dest: /home/username/.ssh/config
    owner: username
    group: username
    mode: 0400
    checksum: 
        md5: 14bf0902d9e9ff992acfb594e32b4f61
```
##### EXPECTED RESULTS

I want change mode to tell me the file is out-of-spec.
##### ACTUAL RESULTS

Change mode does not report the file has been changed.

```
ansible-playbook myplaybook.yml -t username_ssh -l host123--check
```

**Comment by alikins** [comment]
I'm wondering if get_url does anything in check mode. The module doesn't seem to have 'supports_check_mode'

If run with '-vvvvv' options, whats the results in check mode? I suspect (haven't tested) it
to be "remote module does not support check mode".

EDIT: needs_info

**Comment by alikins** [comment]
with the playbook:

```
---
 - hosts: localhost
   tasks:
   - name: get a url
     get_url:
       url: "http://ansible.com/index.html"
       dest: /tmp/get_url_test
    # owner: username
    #    group: username
    #    checksum: 
    #        md5: 14bf0902d9e9ff992acfb594e32b4f61
```

running
```ansible-playbook -vvvv test.yml'

```

I get:

```

localhost> ESTABLISH LOCAL CONNECTION FOR USER: adrian
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "`echo $HOME/.ansible/tmp/ansible-tmp-1462820328.27-142922979877225`" && echo "`echo $HOME/.ansible/tmp/ansible-tmp-1462820328.27-142922979877225`" )'
<localhost> PUT /tmp/tmpgNe9f2 TO /home/adrian/.ansible/tmp/ansible-tmp-1462820328.27-142922979877225/get_url
<localhost> EXEC /bin/sh -c 'LANG=en_US.utf8 LC_ALL=en_US.utf8 LC_MESSAGES=en_US.utf8 /usr/bin/python2 /home/adrian/.ansible/tmp/ansible-tmp-1462820328.27-142922979877225/get_url; rm -rf "/home/adrian/.ansible/tmp/ansible-tmp-1462820328.27-142922979877225/" > /dev/null 2>&1'
skipping: [localhost] => {"changed": false, "invocation": {"module_args": {"dest": "/tmp/get_url_test", "url": "http://ansible.com/index.html"}, "module_name": "get_url"}, "msg": "remote module does not support check mode", "skipped": true}

```

So the get_url module will get skipped in --check, which would explain why nothing happens on --check.
```
