### ISSUE TITLE
win_feature for iis with sub features: yes fails on 2012 R2

### ISSUE THREAD

**Issue by javadevmtl** [ansible/ansible-modules-core#3640]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

win_feature
##### ANSIBLE VERSION

ansible 2.0.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
##### CONFIGURATION

Defaults
##### OS / ENVIRONMENT

Ansible: Ubuntu 14.04
Managing: Win 2008 R2 and Win 2012 R2
##### SUMMARY

Testing the Example win_feature playbook

```
- name: Install IIS
  hosts: windows
  gather_facts: true
  tasks:
    - name: Install IIS
      win_feature:
        name: "Web-Server"
        state: present
        restart: yes
        include_sub_features: yes
        include_management_tools: yes
```

The Windows 2008 machines complete correctly, but 2012 fails with

`fatal: [my2012host]: FAILED! => {"changed": false, "exitcode": "Failed", "failed": true, "feature_result": [], "invocation": {"module_name": "win_feature"}, "msg": "Failed to add feature", "restart_needed": false, "success": false}`

If I modify the playbook and disable subfeature like so:

`include_sub_features: no`

I get

```
ok: [my2012host] => {"changed": false, "exitcode": "NoChangeNeeded", "feature_result": [], "invocation": {"module_name": "win_feature"}, "restart_needed": false, "success": true}

PLAY RECAP *********************************************************************
my2012host                  : ok=2    changed=0    unreachable=0    failed=0

```
