### ISSUE TITLE
get_url fails with some ftp servers

### ISSUE THREAD

**Issue by micafer** [ansible/ansible-modules-core#3661]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

get_url
##### ANSIBLE VERSION

```
ansible 2.0.2.0
  config file = 
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

Ansible.cfg does not exist. So it is using all default values.
##### OS / ENVIRONMENT

I think that is not platform-specific.
But I have tested un ubuntu 14.04 and CentOS 6.
##### SUMMARY

The get_url module fails with "fatal" error with some ftp servers.
This is the error shown:

```
fatal: [localhost]: FAILED! => {"changed": false, "dest": "/tmp", "failed": true, "gid": 0, "group": "root", "mode": "01777", "msg": "Request failed", "owner": "root", "response": "OK (282593 bytes)", "size": 4096, "state": "directory", "status_code": null, "uid": 0, "url": "ftp://ftp.surfsara.nl/pub/outgoing/pbs_python-4.6.0.tar.gz"}
```
##### STEPS TO REPRODUCE

Create a simple playbook like that and call ansible-playbook:

```
- hosts: localhost
  connection: local
  tasks:
   - get_url: url=ftp://ftp.surfsara.nl/pub/outgoing/pbs_python-4.6.0.tar.gz dest=/tmp
   # the next one also fails
   - get_url: url=ftp://mirror.cc.columbia.edu/pub/software/apache/hadoop/core/hadoop-1.2.1//hadoop-1.2.1.tar.gz  dest=/tmp
```
##### EXPECTED RESULTS

Correctly download the file and return this output:

```
PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [get_url] *****************************************************************
changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0   
```
##### ACTUAL RESULTS

```
PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [get_url] *****************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "dest": "/tmp", "failed": true, "gid": 0, "group": "root", "mode": "01777", "msg": "Request failed", "owner": "root", "response": "OK (282593 bytes)", "size": 4096, "state": "directory", "status_code": null, "uid": 0, "url": "ftp://ftp.surfsara.nl/pub/outgoing/pbs_python-4.6.0.tar.gz"}

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @test.retry

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1   
```
