### ISSUE TITLE
Unable to run os_server task asynchronously

### ISSUE THREAD

**Issue by msmiths** [ansible/ansible-modules-core#3663]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

os_server
##### ANSIBLE VERSION

```
ansible 2.0.2.0
  config file = /Users/fbloggs/projects/iotf/workspace/iotcloud.infrastructure.openstack.deploy/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
[defaults]
roles_path = roles
nocows = 1
nocolor = 0
transport = ssh
callback_plugins = plugins/callbacks
forks = 25
gathering = smart
retry_files_enabled = false

[ssh_connection]
pipelining=true
```
##### OS / ENVIRONMENT

Ansible playbooks are running on Mac OS X 10.11.4 against Ubuntu 14.04.4 instances.  The instances are hosted/managed by an OpenStack Kilo environment.
##### SUMMARY

I am attempting to run the os_server module asynchronously in order to create multiple instances in OpenStack as quickly as possible.  I get the following error when using the async and poll attributes with the os_server task:

```
  fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "The async task did not return valid JSON: No JSON object could be decoded"}
```
##### STEPS TO REPRODUCE

```
- name: Provision the instances for the environment
  os_server:
    name: "{{ item.key }}"
    state: present
    nics:
      - net-name: "{{ item.value.network }}"
    security_groups: "{{ security_group.id }}"
    image: "{{ item.value.image|default(omit) }}"
    boot_volume: "{{ item.value.boot_volume|default(omit) }}"
    volumes: "{{ item.value.volumes|default(omit) }}"
    flavor: "{{ item.value.flavor }}"
    key_name: "{{ item.value.key_name }}"
    auto_floating_ip: "{{ item.value.auto_floating_ip|default(false) }}"
    meta:
      { 'groups' : "{{ item.value.groups }}" }
  with_dict: "{{ instances }}"
  when: instances is defined
  async: 1000
  poll: 0
```
##### EXPECTED RESULTS

I expected to see the os_server module invoked for each of the entries in the instances dictionary and return immediately.
##### ACTUAL RESULTS

```
ESTABLISH LOCAL CONNECTION FOR USER: fbloggs
localhost EXEC /bin/sh -c '( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1463406308.3-91270693643895 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1463406308.3-91270693643895 `" )'
localhost PUT /var/folders/l_/4tn0fh2x3fn1570whwvktywm0000gn/T/tmpdyHWq9 TO /Users/fbloggs/.ansible/tmp/ansible-tmp-1463406308.3-91270693643895/os_server
localhost EXEC /bin/sh -c 'chmod a+rx /Users/fbloggs/.ansible/tmp/ansible-tmp-1463406308.3-91270693643895/os_server'
localhost PUT /var/folders/l_/4tn0fh2x3fn1570whwvktywm0000gn/T/tmpGceRok TO /Users/fbloggs/.ansible/tmp/ansible-tmp-1463406308.3-91270693643895/async_wrapper
localhost EXEC /bin/sh -c 'chmod a+rx /Users/fbloggs/.ansible/tmp/ansible-tmp-1463406308.3-91270693643895/async_wrapper'
localhost PUT /var/folders/l_/4tn0fh2x3fn1570whwvktywm0000gn/T/tmpdi29J0 TO /Users/fbloggs/.ansible/tmp/ansible-tmp-1463406308.3-91270693643895/arguments
localhost EXEC /bin/sh -c 'LANG=en_GB.UTF-8 LC_ALL=en_GB.UTF-8 LC_MESSAGES=en_GB.UTF-8 /Users/fbloggs/.ansible/tmp/ansible-tmp-1463406308.3-91270693643895/async_wrapper 322166349521 1000 /Users/fbloggs/.ansible/tmp/ansible-tmp-1463406308.3-91270693643895/os_server /Users/fbloggs/.ansible/tmp/ansible-tmp-1463406308.3-91270693643895/arguments'
localhost EXEC /bin/sh -c 'rm -f -r /Users/fbloggs/.ansible/tmp/ansible-tmp-1463406308.3-91270693643895/ > /dev/null 2>&1'
failed: [localhost] (item={'value': {u'key_name': u'iot-dev-key', u'image': u'IOTF-OS-COMMON', u'network': u'internal', u'groups': u'elastic-search-http-nodes', u'flavor': u'm1.medium'}, 'key': u'portal1'}) => {"failed": true, "item": {"key": "portal1", "value": {"flavor": "m1.medium", "groups": "elastic-search-http-nodes", "image": "IOTF-OS-COMMON", "key_name": "iot-dev-key", "network": "internal"}}, "msg": "The async task did not return valid JSON: No JSON object could be decoded"}
```
