### ISSUE TITLE
Docker port ip address defaults to 0.0.0.0 when network present

### ISSUE THREAD

**Issue by ToBeReplaced** [ansible/ansible-modules-core#3670]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

_docker
##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.0.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

An unspecified ip address in "ports" defaults to "0.0.0.0" even if "net" is specified.
##### STEPS TO REPRODUCE

Create a docker bridge network with an ipv4 address:
`docker network create -o com.docker.network.bridge.host_binding_ipv4=10.1.1.1 test_network`

Start a container on the network:

```
- name: Start a docker container
  docker:
    name: registry
    image: docker.io/registry:2
    net: test_network
    ports:
      - '5000:5000'
    state: started
  become: yes
```
##### EXPECTED RESULTS

`docker inspect registry` should reveal that the container binds 5000 to 10.1.1.1:5000 .
##### ACTUAL RESULTS

`docker inspect registry` reveals that the container binds 5000 to 0.0.0.0:5000 .

Unfortunately, I'm not familiar enough with the docker api to fix this one.
