### ISSUE TITLE
iam.py - existing user not added to existing group

### ISSUE THREAD

**Issue by Constantin07** [ansible/ansible-modules-core#3692]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

modules/core/cloud/amazon/iam.py
##### ANSIBLE VERSION

```
ansible 1.9.4
```
##### CONFIGURATION

Default.
##### OS / ENVIRONMENT

CentOS Linux release 7.2.1511 (Core)
##### SUMMARY

The IAM user is not added to the IAM group.
##### STEPS TO REPRODUCE

```
- name: Create IAM user
  iam:
    iam_type: user
    name: proj_user
    path: '/'
    state: present

- name: Add IAM user to IAM groups
  iam:
    iam_type: user
    name: proj_user
    path: '/'
    state: update
    groups: TestGroup
```

Followed the example given here http://docs.ansible.com/ansible/iam_module.html
##### EXPECTED RESULTS

The proj_user should become a member of  TestGroup.
##### ACTUAL RESULTS

Test Group is empty but module returns status as changed which is not true.
Sequential re-runs do not change the situation.

```
TASK: [Add IAM user to IAM groups] *********************************
changed: [127.0.0.1] => {"changed": true, "groups": ["TestGroup"], "keys": {}, "user_name": "proj_user"}
```
