### ISSUE TITLE
Show diff when copying files

### ISSUE THREAD

**Issue by martenlehmann** [ansible/ansible-modules-core#3715]
##### ISSUE TYPE
- Feature Idea
##### COMPONENT NAME

files/copy
##### ANSIBLE VERSION

```
ansible 2.0.2.0
  config file =
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

The diff mode is very helpful, but unfortunately – as http://docs.ansible.com/ansible/glossary.html confirms – it's only "to show how _template_ files change". Since a lot of configuration files may be just static, it would be overkill to transform all of them to template files only for the sake of seeing changes in the diff mode.
##### STEPS TO REPRODUCE

Create a playbook or role for an application, that requires configuration files that don't include hostnames, IP addresses etc.

```
- name: Copy config files
  copy:
    src: '{{ item}}'
    dest: '/opt/open-xchange/etc/{{ item}}'
    owner: root
    group: open-xchange
    mode: '0640'
  with_items:
    - AdminUser.properties
    - as-config.yml
    - attachment.properties
    - caldav.properties
    - ...
```
##### EXPECTED RESULTS

See _what_ changed rather then only _that_ something changed, as with template files. The diff output may be limited to ASCII files.
##### ACTUAL RESULTS

 The current output is not very helpful.

```
changed: [host] => (item=AdminUser.properties)
ok: [host] => (item=as-config.yml)
ok: [host] => (item=attachment.properties)
ok: [host] => (item=caldav.properties)
```
