### ISSUE TITLE
nxos_config issue with creating L2 vlans using transport cli

### ISSUE THREAD

**Issue by heathdbrown** [ansible/ansible-modules-core#3718]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

module
- nxos_config
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 1861151fa4) last updated 2016/05/20 16:06:57 (GMT +000)
  lib/ansible/modules/core: (detached HEAD d3097bf580) last updated 2016/05/20 16:12:00 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD ce5a9b6c5f) last updated 2016/05/20 16:12:01 (GMT +000)
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible/']
```
##### OS / ENVIRONMENT

Cisco NXOS - n3000-uk9.6.0.2.U5.2.bin
##### SUMMARY

When running nxos_config with transport cli L2 vlans are created, however, name is ignored.

Currently, I believe this is due to the need to create the parent, but when no name is supplied the vlan is not in the running-configuration. 

```
show run | i vlan
```
##### STEPS TO REPRODUCE

```
    - name: Setup Bridging (Vlans)
      nxos_config:
        lines:
          - 'name {{ item.name }}'
        parents:
          - 'vlan {{ item.id }}'
        host: "{{ inventory_hostname }}"
        username: "{{ cisco.nexus.username }}"
        password: "{{ cisco.nexus.password }}"
        transport: cli
        use_ssl: yes
        validate_certs: false
      when: vlans is defined
      with_items:
        - "{{ vlans }}"
```

group_vars or host_vars

```

---
vlans:
  - id: 10
    name: Ansible
```

##### EXPECTED RESULTS

```
TASK [Setup Bridging (Vlans)] **************************************************
changed: [nxos1] => (item={u'id': 10, u'name': u'Ansible'})
```

On NXOS:
show run vlan

```
vlan 10
  name Ansible
```
##### ACTUAL RESULTS

```
TASK [Setup Bridging (Vlans)] **************************************************
changed: [nxos1] => (item={u'id': 10, u'name': u'Ansible'})
```

On NXOS:
show run vlan

```
vlan 10
```
