### ISSUE TITLE
Pulling repository when using net option in docker module with nonexistent network

### ISSUE THREAD

**Issue by ghost** [ansible/ansible-modules-core#3733]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

_docker
##### ANSIBLE VERSION

```
ansible 2.0.2.0
```
##### SUMMARY

Ansible is pulling repository when using net option in docker module, even if the option
pull: missing
is set and the image is allready on the system.
In our case there was also an error message regarding the repo pull (private repo): unauthorized: authentication required
This occurs when the network is not created before using the net option.
##### STEPS TO REPRODUCE

```
- name: some container
  docker:
    name: "some container"
    image: myhost/image
    pull: missing
    restart_policy: always
    env:
      ES_HEAP_SIZE: 4g
    memory_limit: '8192MB'
    net: 'mynetwork'
    state: started
```
##### EXPECTED RESULTS

There should be an error message stating, that the network is not existing.
Its very hard for users to identify the problem, as there is no correct error message and the message regarding image pull is misleading.
After creating the network with
docker network create mynetwork
the container is started without pull.
##### ACTUAL RESULTS

```
```
