### ISSUE TITLE
docker_service fails with inspection['NetworkSettings']['Networks'][key]['Aliases'] KeyError: 'Aliases'

### ISSUE THREAD

**Issue by joshunger** [ansible/ansible-modules-core#3740]
- Bug Report
- docker_service

ansible 2.1.0.0
  config file =
  configured module search path = Default w/o overrides

OS X 10.11.1 to Amazon Linux 

Running the following docker-compose.yml with docker_service fails with the following error message but works when run directly with `docker-compose`

`FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_lWusF9/ansible_module_docker_service.py\", line 760, in <module>\r\n    main()\r\n  File \"/tmp/ansible_lWusF9/ansible_module_docker_service.py\", line 755, in main\r\n    result = ContainerManager(client).exec_module()\r\n  File \"/tmp/ansible_lWusF9/ansible_module_docker_service.py\", line 510, in exec_module\r\n    result = self.cmd_up()\r\n  File \"/tmp/ansible_lWusF9/ansible_module_docker_service.py\", line 613, in cmd_up\r\n    aliases=inspection['NetworkSettings']['Networks'][key]['Aliases'],\r\nKeyError: 'Aliases'\r\n", "msg": "MODULE FAILURE", "parsed": false}`

**docker-compose.yml**

```
prestashop:
  image: prestashop/prestashop
  links:
    - mysql
  environment:
    DB_SERVER: mysql
    DB_PASSWD: foo
  ports:
    - "80:80"

mysql:
  image: mysql:5.6
  environment:
    MYSQL_ROOT_PASSWORD: foo
  ports:
    - "3306:3306"
```

**playbook**

```
    - name: copy docker-compose
      copy: src=docker-compose.yml dest=~/

    - name: docker service
      docker_service:
        project_src: .
```
