### ISSUE TITLE
win_feature failing

### ISSUE THREAD

**Issue by dan-petty** [ansible/ansible-modules-core#3746]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

win_feature
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible']
```
##### CONFIGURATION

Default
##### OS / ENVIRONMENT

Ubuntu 14.04.4
ppa:ansible/ansible
##### SUMMARY

Attempting to install .NET feature on Windows Server 2008 R2 (powershell v4) fails
##### STEPS TO REPRODUCE

Run the following item:

```
- name: install .NET framework
  win_feature:
    name: NET-Framework-Core
    state: present
    restart: yes
    include_sub_features: no
    include_management_tools: yes
  register: result
```
##### EXPECTED RESULTS

Windows Feature successfully installed
##### ACTUAL RESULTS

```
FAILED! => {"changed": false, "failed": true, "msg": "Method invocation failed because [System.Management.Automation.PSCustomObject] does not contain a method named 'Remove'."}
```

This worked as of Ansible 2.0.0.0
