### ISSUE TITLE
ansible 2.1.0, s3 module bug

### ISSUE THREAD

**Issue by alxschwarz** [ansible/ansible-modules-core#3758]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

s3 module
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

Only default settings
##### OS / ENVIRONMENT

I think N/A. But we use Ubuntu:

```
NAME="Ubuntu"
VERSION="14.04.4 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.4 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
```
##### SUMMARY

Error during using s3 module. For example, during get file from s3 bucket.
##### STEPS TO REPRODUCE

Run playbook

```

---
- name: Test playbook
  hosts: localhost
  tasks:
    - name: Get file from S3
      s3: bucket=<bucket_name> object=/path/to/file> dest=/tmp/file mode=get
```
##### EXPECTED RESULTS

File to /tmp directory
##### ACTUAL RESULTS

Error during ansible task running.

```
TASK [Get file from S3] ************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to connect to S3: Region  does not seem to be available for aws module boto.s3. If the region definitely exists, you may need to upgrade boto or extend with endpoints_path"}
```
