### ISSUE TITLE
ansible docker_image can't find a locally available image on build

### ISSUE THREAD

**Issue by jordy25519** [ansible/ansible-modules-core#3760]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

docker_image
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /home/user/scratch/deployment/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

OS: N/A
docker-py 1.8.1
docker version

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64
```
##### SUMMARY

When building a docker image locally Ansible fails to find a locally available base image specified in the  `FROM` directive of the dockerfile. 
Resulting Error:

```
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error building localhost:5000/image - code: None message: Error: image library/base_image not found"}
```

[See this similar issue with docker compose](https://github.com/docker/compose/issues/1568)
##### STEPS TO REPRODUCE

Create docker registry

```
-   name: Creating docker registry
    docker:
        name: registry
        image: "registry:2"
        state: started
        restart_policy: always
        ports:
            - "5000:5000"
        env:
            REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
        volumes:
            "{{host_registry_dir}}:/var/lib/registry"
```

Build, tag, push base image

```
-   name: Create base_image locally
    docker_image:
        name: "{{private_docker_registry}}/base_image"
        path: "{{build_folder}}/dockerfiles/base_image"
        dockerfile: base_image.Dockerfile
```

Build,tag,push child image

```
-   name: Create image locally
    docker_image:
        name: "{{private_docker_registry}}/image"
        path: "{{build_folder}}/dockerfiles/image"
        dockerfile: image.Dockerfile
```

Simplified `image.Dockerfile` using the locally built base_image as its base:

```
FROM base_image

EXPOSE 5555

ENTRYPOINT ["./entrypoint.sh"]
```
##### EXPECTED RESULTS

docker image to be built, tagged, and pushed to the local registry.
##### ACTUAL RESULTS

The image failed to build as its base image could not be located.

Output:

```
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error building localhost:5000/image - code: None message: Error: image library/base_image not found"}
```

Setting `pull: no` seemed to resolve this. But there are two issues with this firstly it is confusing as the docs state 

> "When building an image downloads any updates to the FROM image in Dockerfile." 

and secondly executed unusually slow and produced another error:

```
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error: configuration for localhost:5000 not found. Try logging into localhost:5000 first."}
```

**Comment by raffienficiaud** [comment]
Hitting the same issue. Why is `library/` prepended to the image name?

**Comment by ansibot** [comment]
@ansible, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/jctanner/ansibullbot/blob/ISSUE_TRIAGE_CLASS/ISSUE_HELP.md)

**Comment by jordy25519** [comment]
raffienficiaud I think this is may actually be caused by changes to the docker implementation. Even using docker 1.11 without ansible, building fails to find the image locally.

**Comment by raffienficiaud** [comment]
I think I do not experience the same issue as explained here. The problem I was hitting is that, as soon as there is a `/` in the image name, it is interpreted as a registry. Removing all namespace `/` do actually work.
Sorry for the noise... (however the problem I had coincides well with the subject of this bug :) )

**Comment by chouseknecht** [comment]
notabug

The _pull_ parameter defaults to True, which causes the build process to attempt pulling the FROM image. The only option for stopping the pull is setting _pull_ to False. 

Prepending 'library' to the FROM image name is the default behavior when pulling from Docker Hub when the image name does not include an owner.  So if your pulling an image owned by me, for example, the image name would be 'chouseknecht/foo'. If you leave off of my username, then the pull defaults to using 'library/foo'. That's being done by Docker, not by the docker_image module. 

The error "Error: configuration for localhost:5000 not found. Try logging into localhost:5000 first." is happening, I suspect, because docker_image does not support the insecure_registry option when pulling images. The same is true when pushing images. According to the docker-py code the insecure_registry option is deprecated for [the pull method ](https://github.com/docker/docker-py/blob/master/docker/api/image.py#L154) as well as [the push method](https://github.com/docker/docker-py/blob/master/docker/api/image.py#L210). It does not seem as though there is much value in adding and maintaining deprecated parameters.

That being said, docker_image does not attempt to enforce a secure registry. It does not check that you have a valid login. It does not attempt to access ~/.docker/config.json  and see. So it _may_ be possible to get an insecure registry to work. 

When I test with a local registry I [secure it using self-signed certs](https://docs.docker.com/registry/insecure/#/using-self-signed-certificates) and [basic auth](https://docs.docker.com/registry/deploying/#/native-basic-auth). It works as long as you access the registry using server name _localhost_. It's rudimentary and not really secure, but close enough for testing. Here is a[ role to help you create a local, secure registry](https://github.com/ansible/role-local-registry).

The following playbook builds a base_image, tags it and pushes it, then builds a child_image, tags and pushes it. Works with ansible 2.1.0 and 2.1.1.0. It's pushing images into a secure registry that I have already logged into.

```
---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Create base_image:latest and push to local registry
      docker_image:
        name: base_image
        path: ~/flask
        repository: localhost:5000/myimages/base_image
        dockerfile: base_image.Dockerfile

    - name: Create child image of base_image and push to local registry
      docker_image:
        name: child_image
        path: ~/child_image
        repository: localhost:5000/myimages/child_image
        dockerfile: child_image.Dockerfile
        pull: false
```

Here are the resulting images:

```
$ docker images

REPOSITORY                            TAG                 IMAGE ID            CREATED             SIZE
child_image                           latest              7807e282b7e8        35 minutes ago      708.9 MB
localhost:5000/myimages/child_image   latest              7807e282b7e8        35 minutes ago      708.9 MB
base_image                            latest              6588d7b77841        35 minutes ago      708.9 MB
localhost:5000/myimages/base_image    latest              6588d7b77841        35 minutes ago      708.9 MB
python                                2.7                 c30b98f002e0        3 days ago          676 MB
registry                              2                   c6c14b3960bd        7 days ago          33.28 MB
```
