### ISSUE TITLE
docker_container doesn't (can't) easily work on Atomic and similar OS's

### ISSUE THREAD

**Issue by jduncan-rva** [ansible/ansible-modules-core#3762]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

docker_container
##### ANSIBLE VERSION

```

ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```
##### CONFIGURATION

none
##### OS / ENVIRONMENT

ansible - Fedora 23
targets - RHEL Atomic 7.2
##### SUMMARY

docker_container doesn't work for Atomic Hosts (or any OS styled similarly)

docker_container looks like it requires docker-py to be installed on the target systems for the plugin to work. You can't (easily) do that in an OS like Atomic Host. 

I couldn't find an issue to track making this work. Since this is new to 2.1 I'm assuming it's the path forward. Is there a plan to get this to work without target-based dependencies being needed?
##### STEPS TO REPRODUCE

```
- name: create glusterfs server container
  docker_container:
    name: gluster-fs
    image: registry.access.redhat.com/rhgs3/rhgs-server-rhel7
    privileged: yes
    network_mode: host
    volumes_from: glusterdata
    volumes:
      - /mnt/brick1:/mnt/container_brick1[:z]

```
##### EXPECTED RESULTS

the play should run
##### ACTUAL RESULTS

the play errors out looking for a dependency that isn't there

```

fatal: [kube2]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to import docker-py - cannot import name NotFound. Try `pip install docker-py`"}

```

**Comment by bcoca** [comment]
docker-py needs to be installed on the host with access to manage containers, not the containers themselves. We don't have testing with atomic (yet), currently the module should work with most other distros and a docker install.

**Comment by jduncan-rva** [comment]
I guessed when I ran into it. The work-around is pretty straight-forward. I wanted to get it recorded in here so we can add it to the TODO.

-jduncan

**Comment by dhuette13** [comment]
I get a similar error when using docker_service:

```
fatal: [testhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to import docker-py - cannot import name NotFound. Try `pip install docker-py`"}
```

Here is the play:

```
- name: compose project
    docker_service:
      project_src: /srv/docker-test
      state: present
      build: true
```

Both my local machine and target are running Ubuntu 14.04. Same version of ansible: 2.1.0.0
