### ISSUE TITLE
docker_image in ansible 2.1 forcefully tries to push image

### ISSUE THREAD

**Issue by berlic** [ansible/ansible-modules-core#3763]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

docker_image
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### CONFIGURATION

Default
##### OS / ENVIRONMENT

Docker daemon:

```
Server:
 Version:      1.11.1
 API version:  1.23
```
##### SUMMARY

When building an image, docker_image always try to push image to repo.
##### STEPS TO REPRODUCE

```
- name: Build image
  docker_image:
    path: "/containers/test_container/build"
    name: "my/test_container"
    state: present
    pull: yes
```
##### EXPECTED RESULTS

Image `my/test_container:latest` is built locally. Period!
##### ACTUAL RESULTS

Image is built, but task fails when trying to upload it.

```
FAILED! => {"changed": false, "failed": true, "msg": "Error: configuration for docker.io not found. Try logging into docker.io first."}
```

Line of code in question: https://github.com/ansible/ansible-modules-core/blob/04a871d0070719a870286e22eb0a4a3bde8ecb4d/cloud/docker/docker_image.py#L270

**Comment by wrgeorge1983** [comment]
I just hit this myself.  Looking at the linked file on line 278 it also looks as if it force a push even when it is loading an image from an archive.

**Comment by GeorgeDewar** [comment]
I spent some time trying to figure out why this was happening for one of my applications and not another. I've now figured out that this behaviour only occurs of the image name contains a forward slash. Just noting this in case anyone else comes across this issue and isn't aware of this.

This also means that not putting a slash in the image name may be a viable workaround for some users.

P.S. Is this not a terrible security vulnerability? It would seem that through this behaviour, an entire codebase (with sensitive configuration data if the user has been silly and included that in their image) could be published to Docker Hub without the user ever realising... I would think that would warrant an urgent patch.

**Comment by imincik** [comment]
I also confirm this behavior. Urgent security fix is required !

**Comment by dgjnpr** [comment]
Ack on the forcible push behaviour. If your image name contains a "/" this module will try to push it a registry - regardless of the argument 'push' value. And I tend to agree that this is not expected behaviour.

Removing or replacing the "/" from the image name resolves the problem.

**Comment by mckelvin** [comment]
I also encountered this issue

> Error: configuration for registry.corp.private.com not found. Try logging into registry.corp.private.com first.

while building an image with:

``` yaml
- name: Build docker image my-image-name
  docker_image:
    name: registry.corp.private.com/my-image-name
    path: "{{ dockerfiles_path }}/my-image-name"
```

The image can be built successfully but I don't why it failed to push to my private docker registry since there's no problem while running`docker push registry.corp.private.com/my-image-name` in terminal. Anyway in my case, whether pushed to the registry is OK to me so long as it doesn't break the ansible pipeline.

And finally, I managed to stop it from pushing to the registry by adding the `repository` parameter:

``` yaml
- name: Build docker image my-image-name
  docker_image:
    name: registry.corp.private.com/my-image-name
    path: "{{ dockerfiles_path }}/my-image-name"
    repository: registry.corp.private.com/my-image-name
```
