### ISSUE TITLE
docker_container removes and recreates containers when using the env parameter

### ISSUE THREAD

**Issue by genei09** [ansible/ansible-modules-core#3775]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

docker_container
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### CONFIGURATION

none
##### OS / ENVIRONMENT

OSx 10.11.4
docker 1.11.1
##### SUMMARY

docker_container removes and recreates containers when using the env parameter
##### STEPS TO REPRODUCE

with the example playbook saved as test.yml run the following twice and note the container ID changes
ansible-playbook test.yml && docker ps

```
- hosts: localhost
  connection: local
  tasks:
  - name: try simple docker image
    docker_container:
      name: "dbs_test_databasehost"
      image: "postgres:latest"
      state: started
      recreate: false
      pull: false
      env:
        POSTGRES_USER: dbuser
        PGDATA: test
```
##### EXPECTED RESULTS

the docker container ids to not change as no configuration has changed
##### ACTUAL RESULTS

the container is removed and a new one is created
