### ISSUE TITLE
docker_container with 'command' returns 'not found or does not exist' (old 'docker' module works fine)

### ISSUE THREAD

**Issue by dcbishop** [ansible/ansible-modules-core#3783]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

docker_container
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

No changes to ansible.cfg.
##### OS / ENVIRONMENT

Arch
##### SUMMARY

When using the new docker_container module with the command argument.
`"Container command 'SOME_COMMAND' not found or does not exist."`

The exact same setup, with the deprecated 'docker' module used in place of 'docker_container' works fine.
##### STEPS TO REPRODUCE

```
- hosts: main
  tasks:
     - name: Setup test container
       docker_container:
         name: test-container
         image: ubuntu:16.04
         command: sleep infinity
```
##### EXPECTED RESULTS

A container should start with sleep as the running command.
##### ACTUAL RESULTS

```
PLAY [main] ********************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Setup test container] ************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error starting container b3be845be5f9a40daadfd536028f2d7ec20a71b2d2b5b61a790c2c589f81e44b: 404 Client Error: Not Found (\"Container command 'sleep infinity' not found or does not exist.\")"}

```

**Comment by chouseknecht** [comment]
Working on this. The first part of the problem is the `command` parameter type needs to be `str` and not `list`. Just testing the comparison to make sure we compare command between params and existing container correctly.

**Comment by william20111** [comment]
has this been fixed still appear to be getting this in 2.1? The command is in my dockerfile as list as per normal.

> ansible 2.1.0.0
>   config file = /etc/ansible/ansible.cfg
>   configured module search path = Default w/o overrides

**Comment by mabrek** [comment]
the bug is stil there in 2.1

**Comment by chouseknecht** [comment]
@mabrek I'm running from source and not seeing the bug. 

**Playbook:**

```
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:

     - name: Setup test container
       docker_container:
         name: test-container
         image: busybox
         command: sleep 600
```

**Results:**

```
$ ansible-playbook test.yml

PLAY [localhost] ***************************************************************

TASK [Setup test container] ****************************************************
changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0

~/projects/docker-testing/test $ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
388d7a529ecd        busybox             "sleep 600"         2 seconds ago       Up 1 seconds                            test-container
```

Do you have a specific test case?

**Comment by gloutsch** [comment]
playbook
```yaml
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
     - name: Setup test container
       docker_container:
         name: test
         image: consul
         command: >-
           agent
           -server
           -ui
           -bootstrap expect 1
```
docker inspect test
```
        "Args": [
            "agent -server -ui -bootstrap expect 1\n"
        ],
```
instead of :
```
        "Args": [
            "agent",
            "-server",
            "-ui",
            "-bootstrap",
            "expect",
            "1"
        ],
```
```

**Comment by mckelvin** [comment]
@chouseknecht I can still reproduce the issue in ansible 2.1.0.0. Are you sure you're using 2.1 ?

```
# kelvin @ PANs-MacBook-Pro in /tmp [23:49:43]
$ ansible-playbook poc.yml
 [WARNING]: Host file not found: /usr/local/etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] ***************************************************************

TASK [Setup test container] ****************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error starting container 55a60ea5cf400c61f3ae0b3cbe6fb571ded02ed029ab361b62b2a1d8fc2b354b: 404 Client Error: Not Found (\"oci runtime error: exec: \"sleep 600\": executable file not found in $PATH\")"}

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @poc.retry

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1

(tmp)
# kelvin @ PANs-MacBook-Pro in /tmp [23:49:53] C:2
$ ansible-playbook --version
ansible-playbook 2.1.0.0
  config file =
  configured module search path = Default w/o overrides
(tmp)
# kelvin @ PANs-MacBook-Pro in /tmp [23:50:24]
$ ansible --version
ansible 2.1.0.0
  config file =
  configured module search path = Default w/o overrides
(tmp)
# kelvin @ PANs-MacBook-Pro in /tmp [23:50:28]
$ cat poc.yml
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:

     - name: Setup test container
       docker_container:
         name: test-container
         image: busybox
         command: sleep 600
```

---

Update:

And it works if `command` is modified to a list:

```
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:

     - name: Setup test container
       docker_container:
         name: test-container
         image: busybox
         command: ["sleep", "600"]
```

**Comment by chouseknecht** [comment]
@mckelvin As I mentioned in my response, I'm running from source. I believe the fix is part of stable-2.1 as well.

**Comment by Ehekatl** [comment]
+1, command in string not working on ansible2.1

**Comment by bennetimo** [comment]
+1 just seen this, reverting to the older 'docker' module has no issue

**Comment by rogersmark** [comment]
Seeing this issue as well, even with ansible 2.1.1.0. Converting to a list did not help in my instance however.

**Comment by Ehekatl** [comment]
@f4nt are u using git repo ? make sure you update sub module as well, I can confirm that this fix is already in 2.1.1 now

**Comment by rogersmark** [comment]
@Ehekatl - I'm running on Ubuntu and using the package from the PPA. I am running 2.1.1.0:

```
# ansible-pull --version
ansible-pull 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

However, the docker_container.py module does not contain the changes from what I'm guessing is the [commit that addressed this problem](https://github.com/ansible/ansible-modules-core/commit/a75ee76aa3c359e1b87a136fab71c59f17fe8f9a).  The copy of docker_container.py on my machine doesn't have any of the changes from there. Again though, that's me snooping around and making an educated guess at the solution.

I'm considering switching over to the git repo now to see if it alleviates my problems.

**Comment by chouseknecht** [comment]
I have `pip install ansible==2.1.1.0` running on Centos 7.

```
$ ansible --version 
ansible 2.1.1.0
  config file =
  configured module search path = Default w/o overrides
```

It works fine. Running the task from the original _Steps to Reproduce_:

```
---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
     - name: Setup test container
       docker_container:
         name: test-container
         image: ubuntu:16.04
         command: sleep infinity
```

```
$ ansible-playbook test.yml

PLAY [localhost] ***************************************************************

TASK [Setup test container] ****************************************************
changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0
```

If however, I revert to ansible 2.1.0, the problem appears:

```
$ ansible --version
ansible 2.1.0.0
  config file =
  configured module search path = Default w/o overrides
```

```
$ ansible-playbook test.yml

PLAY [localhost] ***************************************************************

TASK [Setup test container] ****************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error starting container d7c1d714bc6c3f0e7b4aebb9bb3b9d7be77cde1fdc986e77f3ac91a2572a4920: 404 Client Error: Not Found (\"Container command 'sleep infinity' not found or does not exist.\")"}

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @test.retry

PLAY RECAP *****************************************************************
```

So to get the fix you either need to `pip install ansible==2.1.1.0` or [run from source](http://docs.ansible.com/ansible/intro_installation.html#running-from-source).
