### ISSUE TITLE
Modifying a file in-place locally using the shell module

### ISSUE THREAD

**Issue by adonig** [ansible/ansible-modules-core#380]
Issue Type:

Bug Report (probably)

Ansible Version:

1.7.2

Environment:

Mac

Summary:

It seems it's not possible to locally modify a file in-place using the shell module.

Steps To Reproduce:

Try to locally modify a file in-place using the shell module

```
- name: first approach to pretty print the JSON templates
  local_action: >
    shell python -mjson.tool {{ item }} > {{ item }}
  with_fileglob:
    - json/*.json

- name: second approach to pretty print the JSON templates using tee
  local_action: >
    shell python -mjson.tool {{ item }} | tee {{ item }}
  with_fileglob:
    - json/*.json
```

Note: I generate the file freshly before trying each approach.

Expected Results:

The file should be modified in-place.

Actual Results:

The first approach using > fails because the input file is empty. The second one using tee just produces an empty output file.

**Comment by bcoca** [comment]
this is not a module behavior, this is what I would expect if you run this directly in shell.

**Comment by adonig** [comment]
bcoca: You're right. Looks like my UNIX fu is bad. Asked a friend. He told me I could do this

```
- name: pretty print the JSON templates
  local_action: >
    shell echo "$(python -mjson.tool {{ item }})" > {{ item }}
  with_fileglob:
    - json/*.json
```
