### ISSUE TITLE
Creating system user should not create home directory

### ISSUE THREAD

**Issue by lachlansimpson** [ansible/ansible-modules-core#3829]
Bug Report

User modules

```
[root@head-node]# ansible --version
ansible 2.0.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

Centos 7.2 fully up to date.

```
 ---
 - hosts: slurm
   remote_user: root

   tasks:

     - name: Create slurm user
       user: name=slurm system=yes uid=10000
       tags: create-slurm-user
```

creates /home/slurm

the adduser man page states:

```
-r, --system
           Create a system account.

           System users will be created with no aging information in /etc/shadow, and their numeric
           identifiers are chosen in the SYS_UID_MIN-SYS_UID_MAX range, defined in /etc/login.defs,
           instead of UID_MIN-UID_MAX (and their GID counterparts for the creation of groups).

           Note that useradd will not create a home directory for such an user, regardless of the default
           setting in /etc/login.defs (CREATE_HOME). You have to specify the -m options if you want a home
           directory for a system account to be created.
```

This would be less of an issue if the docs reflected that system=yes behaved differently to the expected way system=yes would work (ie, that no home dir would be created), and instructed an explicit createhome=no for expected result.
##### EXPECTED RESULTS

Slurm user created with uid 10000 and no home dir
##### ACTUAL RESULTS

Home dir created.
