### ISSUE TITLE
Potgres9.5 suport in rds_param_group

### ISSUE THREAD

**Issue by washingtoneg** [ansible/ansible-modules-core#3846]
##### ISSUE TYPE

- Feature Idea
##### COMPONENT NAME

`cloud/amazon/rds_param_group.py`
##### ANSIBLE VERSION

```
 $ ansible --version
ansible 2.2.0 (devel 273a965dcc) last updated 2016/06/02 17:32:22 (GMT -400)
  lib/ansible/modules/core: (devel d952087557) last updated 2016/05/31 10:03:19 (GMT -400)
  lib/ansible/modules/extras: (devel 52bee8c11e) last updated 2016/05/24 17:48:43 (GMT -400)
  config file = /Users/elenawashington/.ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

Linux
##### SUMMARY

Amazon RDS now supports Postgres9.5 (details [here](https://aws.amazon.com/about-aws/whats-new/2016/04/rds-postgresql-9-5-support/)), so that option should be available when creating RDS parameter groups.
##### EXPECTED RESULTS

I should be able to create a parameter group like so:

```
- rds_param_group:
    state: present
    name: dev-awesome-parameter-group
    description: 'My awesome parameter group'
    engine: 'postgres9.5'
    params:
      bytea_output: 'escape'
```
##### ACTUAL RESULTS

```
TASK [aws_rds_param_group : rds_param_group] ***********************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "value of engine must be one of: aurora5.6,mariadb10.0,mysql5.1,mysql5.5,mysql5.6,mysql5.7,oracle-ee-11.2,oracle-ee-12.1,oracle-se-11.2,oracle-se-12.1,oracle-se1-11.2,oracle-se1-12.1,postgres9.3,postgres9.4,sqlserver-ee-10.5,sqlserver-ee-11.0,sqlserver-ex-10.5,sqlserver-ex-11.0,sqlserver-ex-12.0,sqlserver-se-10.5,sqlserver-se-11.0,sqlserver-se-12.0,sqlserver-web-10.5,sqlserver-web-11.0,sqlserver-web-12.0, got: postgres9.5"}
```
