### ISSUE TITLE
[ Bug / Regression ] mysql_db reports a "changed" state when "present" used and DB already exists

### ISSUE THREAD

**Issue by bmalynovytch** [ansible/ansible-modules-core#3855]
##### ISSUE TYPE

Bug Report
##### COMPONENT NAME

mysql_db (state=present)
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  configured module search path = Default w/o overrides
```
##### SUMMARY

`mysql_db` with `state=present` reports a `changed` state, even if DB already exists, which is a regression.
`ansible 2.0.2.0` was working perfectly.
##### STEPS TO REPRODUCE

```
- name: Ensure my_db exists
  mysql_db:
  args:
    name: "my_db"
    state: present
    login_host: "{{ mariadb_cluster.host }}"
    login_user: root
    login_password: "{{ mariadb_secrets.users.root.passwd }}"
  register: db_status
```
##### EXPECTED RESULTS

On the first run, module should report a `changed` state.
On the second run, the module should report a `ok` state, which wouldn't trigger initial SQL import (following a DB creation).
##### ACTUAL RESULTS

Module reports as `changed`.
