### ISSUE TITLE
docker_container - env variables with multiple '=' fails

### ISSUE THREAD

**Issue by chouseknecht** [ansible/ansible-modules-core#3866]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

docker_container
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 3bac945147) last updated 2016/06/04 00:59:10 (GMT -400)
  lib/ansible/modules/core: (devel 2bd8d78a8b) last updated 2016/06/04 01:00:29 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD b0aec50b9a) last updated 2016/06/01 10:11:03 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

If an environment variable definition containers multiple _=_ signs, the module's configuration comparison routine incorrectly determines that the container's set of env variables does not match the expected set of environment variables. Environment variable definitions can come from module options or from the image used to create the container.
##### STEPS TO REPRODUCE

Run a play with the following task:

```
- name: Jupyter notebook container
  docker_container:
    image: jupyter/all-spark-notebook
    name: notebook
    ports: "8888:8888"
    volumes: "{{data_location}}:/home/jovyan/work:rw"
    state: started
    restart_policy: on-failure
    restart_retries: 5
    restart: no
    network_mode: "host"
  tags: jupyter
```

NOTE: In the above example, the image definition includes the following env variable:

```
SPARK_OPTS=--driver-java-options=-Xms1024M --driver-java-options=-Xmx4096M --driver-java-options=-Dlog4j.logLevel=info
```

Run the exact same play a second time, but this time pass the _--chedk_ and _--diff_ options. Observe that _changed_ is True and _differences_ includes _expected_env_. If things were working properly, changed would be False and the set of differences would be empty.
