### ISSUE TITLE
ec2 module - dont modify termination protection

### ISSUE THREAD

**Issue by klj613** [ansible/ansible-modules-core#3874]
##### ISSUE TYPE
- Feature Idea
##### COMPONENT NAME

ec2
##### ANSIBLE VERSION

```
ansible 2.0.1.0
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

I was using ansible v1.9.4 to start/stop servers using a playbook. I've recently updated to ansible v2.0.1.0 however the termination_protection option defaults to "no" therefore it tries to disable termination protection on some servers. The playbook sole purpose is to start/stop servers therefore I do not want to enable or disable termination protection. I just want to leave it configured the way it is configured.
##### STEPS TO REPRODUCE

```
- name: start ec2 instance
  hosts: all
  gather_facts: False
  connection: local
  tasks:
    - name: start ec2 instance
      ec2:
        instance_ids: '{{ ec2_id }}'
        region: 'eu-west-1'
        aws_access_key: '{{ aws_access_key }}'
        aws_secret_key: '{{ aws_secret_key }}'
        state: running
        wait: True
```
##### EXPECTED RESULTS

Starts ec2 instance and not modify termination protection
##### ACTUAL RESULTS

Starts ec2 instance and modified termination protection
