### ISSUE TITLE
ec2 module hangs if spot request fails

### ISSUE THREAD

**Issue by kuza55** [ansible/ansible-modules-core#3877]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

ec2 module
##### ANSIBLE VERSION

ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
##### CONFIGURATION

ANSIBLE_HOSTS=/etc/ansible/ec2.py
##### OS / ENVIRONMENT

Ubuntu on Windows 10
##### SUMMARY

When an ec2 spot bid fails, the ansible console hangs (making it seem like it's just taking a while to providion).
##### STEPS TO REPRODUCE

This task failed due to a bad volume name (/dev/sda):

``` yml
    - name: Provision a set of instances
      ec2:
         spot_price: 0.65
         spot_wait_timeout: 600
         key_name: ...
         region: us-east-1
         group_id: ...
         instance_type: g2.2xlarge  
         image: ami-d05e75b8
         wait: true
         exact_count: 1
         count_tag:
            Name: InstanceTag
         instance_tags:
            Name: InstanceTag
         vpc_subnet_id: ...
         assign_public_ip: yes
         zone: us-east-1d
         volumes:
           - device_name: /dev/sda
             volume_type: gp2
             volume_size: 20
```
##### EXPECTED RESULTS

I expected ansible to show me an error when the request failed
##### ACTUAL RESULTS

Ansible hangs
