### ISSUE TITLE
Apt module does not work with with_items when package name is templated

### ISSUE THREAD

**Issue by quixoten** [ansible/ansible-modules-core#390]
##### Issue Type:

Bug Report
##### Ansible Version:

devel
##### Environment:

Managing Ubuntu 14.04 from Arch
##### Summary:

Using a template for the `package` parameter of the `apt` module will break when used with `with_items`
##### Steps To Reproduce:

Run a play with the following task:

``` yaml
- name: install php modules
  apt: package=php5-{{ item }} state=present
  with_items:
    - ldap
    - pgsql
```
##### Expected Results:

Installation of the package `php5-ldap` and `php5-pgsql`
##### Actual Results:

```
failed: [test-host] => (item=ldap,pgsql) => {"failed": true, "item": "ldap,pgsql"}
msg: No package matching 'pgsql' is available

FATAL: all hosts have already failed -- aborting
```
##### Additional Notes:

When I ran `pprint(module.params['package']))` in `apt.py` I got the following result:

``` python
['php5-ldap', 'pgsql']
```

Notice that the template was applied to the first item, but not subsequent items.
