### ISSUE TITLE
The `editable` parameter in pip module does not work

### ISSUE THREAD

**Issue by mdklatt** [ansible/ansible-modules-core#3923]
##### ISSUE TYPE

 Bug Report
##### COMPONENT NAME

pip
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = 
  configured module search path = Default w/o overrides

```
##### OS / ENVIRONMENT

Ansible is running on **OS X 10.11.4** and managing **CentOS 7.2.1511**.
##### SUMMARY

Setting the `editable` parameter to `True` when running a `pip` task does not actually install the requirement as editable. Looking at the module source code, this parameter only has an effect if the requirement is being installed from a VCS, but I would think that the typical use case for an editable install is when installing a locally checked out project, not from a VCS. (As an aside, I think it makes more sense for `editable` to default to False, because most installs are going to be from VCS.)
##### STEPS TO REPRODUCE

```
- name: install local checkout to a virtualenv
  pip:
    name: /path/to/project
    state: present
    executable: /path/to/project/venv/bin/pip
    editable: True
```
##### EXPECTED RESULTS

```
$ /path/to/project/venv/bin/pip freeze
-e git+git@git.repo.org:blah/ProjectName.git@372c59cc437285#egg=ProjectName
```
##### ACTUAL RESULTS

```
$ /path/to/project/venv/bin/pip freeze
ProjectName==0.1.0dev12
```
