### ISSUE TITLE
Docker should support `restart_policy` with value `on-failure:N`

### ISSUE THREAD

**Issue by alaz** [ansible/ansible-modules-core#3935]
##### ISSUE TYPE
- Feature Idea
##### COMPONENT NAME

docker
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /Users/alaz/projects/servers/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Docker component supports `restart_policy` with value `on-failure`, but it does not support the optional part where the maximum number of restarts is allowed. This looks like `on-failure:3`, see [Docker documentation](https://docs.docker.com/engine/reference/run/#restart-policies-restart)
##### STEPS TO REPRODUCE

I would use it like so:

```
  - name: MongoDB container
    docker:
      name: 'mongod'
      image: 'mongod'
      state: started
      restart_policy: 'on-failure:3'
```
##### EXPECTED RESULTS

The Docker container would start with `--restart=on-failure:3`.
##### ACTUAL RESULTS

Currently the module fails with the message `fatal: [XXX]: FAILED! => {"changed": false, "failed": true, "msg": "value of restart_policy must be one of: always,on-failure,no,unless-stopped, got: on-failure:3"}
`

**Comment by chouseknecht** [comment]
Support for 'on-failure' has already been added to docker_container, which is the replacement for docker. **Note** you may need to run from source to get this functionality in docker_container.

The following playbook using the _mongo_ image produces the expected results:

```
- name: Test for 16211
  hosts: localhost
  connection: local
  gather_facts:
  tasks:
    - name: MongoDB container
      docker_container:
        name: mongod
        image: mongo
        state: started
        restart_policy: on-failure
        restart_retries: 3
```

Inspecting the new _mongo_ container returns:

```
...
"HostConfig": {
            "Binds": [],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": null,
            "RestartPolicy": {
                "Name": "on-failure",
                "MaximumRetryCount": 3
            },
...
```
