### ISSUE TITLE
Unable to deploy config to junos

### ISSUE THREAD

**Issue by chrmcd** [ansible/ansible-modules-core#3962]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

modules/core/network/junos/junos_template.py
module_utils/junos.py
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /home/mcdowell/git/stamnet-automasjon-ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

Ubunut 14.04
##### SUMMARY

Unable to deploy a junos template to a router
##### STEPS TO REPRODUCE

Run the playbook under, does not need actual configuration file.

```
 - name: juniper device
   hosts:  all
   gather_facts: no
   connection: local

   tasks:
     - name: push config to host
       junos_template:
         host: "{{ host }}"
         port: 830
         password: "{{ default_pw }}"
         username: "{{ default_user }}"
         src: "{{ build_dir }}{{ ansible_host }}/system_confg"

```

##### EXPECTED RESULTS

Expected the config to be deployed to router.
##### ACTUAL RESULTS

Failed with ascii error.

```
The error was: UnicodeEncodeError: 'ascii' codec can't encode characters in position 13559-13560: ordinal not in range(128)
fatal: [fwbuilder-gw2]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_onhFr8/ansible_module_junos_template.py\", line 151, in <module>\n    main()\n  File \"/tmp/ansible_onhFr8/ansible_module_junos_template.py\", line 135, in main\n    results['_backup'] = str(module.get_config()).strip()\n  File \"/tmp/ansible_onhFr8/ansible_modlib.zip/ansible/module_utils/junos.py\", line 331, in get_config\n  File \"/tmp/ansible_onhFr8/ansible_modlib.zip/ansible/module_utils/junos.py\", line 264, in get_config\nUnicodeEncodeError: 'ascii' codec can't encode characters in position 13559-13560: ordinal not in range(128)\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}
```
##### Potential fix?

Changed the str parsing on line 135 in junos_template.py and on line 264 in junos.py to unicode instead. This seems to have fixed the issue, but not sure if it's a good fix or not, if it is, feel free to take the credits for it.
