### ISSUE TITLE
docker_container wraps command in single quotes which breaks images with startup scripts

### ISSUE THREAD

**Issue by tozz** [ansible/ansible-modules-core#3972]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

docker_container
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### OS / ENVIRONMENT

N/A
##### STEPS TO REPRODUCE

When starting an container that uses a script as entrypoint (like the memcached image) the command will get wrapped in single quotes, this will cause the script to parse the command and the arguments a single entity which will of course break.

```

---
- name: Memcached
  docker_container:
    name: memcached
    image: memcached
    command: memcached -m 64
    state: started
```

Running the same command from the CLI will work, here you can see the difference, the top one is from CLI, the second from Ansible.
`"/entrypoint.sh memcached -m 64"`
`"/entrypoint.sh 'memcached -m 64'"`
##### EXPECTED RESULTS

The command should be passed as specified in the YAML
##### ACTUAL RESULTS

The command gets passed in quotes
