### ISSUE TITLE
git: Add an extra_args option to the git module.

### ISSUE THREAD

**Issue by dflock** [ansible/ansible-modules-core#4002]
##### ISSUE TYPE
- Feature Idea
##### COMPONENT NAME

git module
##### ANSIBLE VERSION

```
ansible 2.0.1.0
  config file = /home/duncan/dev/agile/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

I would like to set extra git options, but still use the ansible `git` module, rather than having to use `shell/command` instead.
##### STEPS TO REPRODUCE

Specifically, I would like to be able to add a proxy config to a particular git clone. This could work in the same way as the `pip` module - for example:

``` yaml
- name: Cloning repo
  git:
    repo: {{ git_repo }}
    version: 'dev'
    dest: {{ repo_dir }}
    extra_args: '--config "http.proxy=proxyHost:proxyPort"'
```

but there are lots of other arguments that one might want to pass.
