### ISSUE TITLE
junos_config.py delete statement not working

### ISSUE THREAD

**Issue by stianvi** [ansible/ansible-modules-core#4007]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

network/junos/junos_config.py
##### ANSIBLE VERSION

```
ansible 2.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

--- JUNOS 15.1R3.6 built 2016-03-24 18:40:35 UTC
##### SUMMARY

delete statements don't work due to bug in if-loop
##### STEPS TO REPRODUCE

add a statement beginning with delete under the lines and run the playbook. diff_config if-loop will never match when action is delete

Example requires already configured description on the ge-0/0/0 interface

```
- name: delete interface ge-0/0/0 description 
  hosts: all
  roles:
  - Juniper.junos
  connection: local
  gather_facts: no

  tasks:
    - name: Delete vlan on Juniper Junos 
      junos_config:
        lines:
        - delete interfaces ge-0/0/0 description
        replace: True 
        host: "{{ inventory_hostname }}"
```

##### EXPECTED RESULTS

The configuration lines would be removed from configuration and will return to default configuration
##### ACTUAL RESULTS

No configuration change. Ansible report change=false

```
Using /etc/ansible/ansible.cfg as config file

PLAYBOOK: debug-delete-vlan.yml ************************************************
1 plays in debug-delete-vlan.yml

PLAY [Create vlan] *************************************************************

TASK [Delete vlan on Juniper Junos] ********************************************
task path: /etc/ansible/playbooks/debug-delete-vlan.yml:11
Using module file /usr/lib/python2.7/site-packages/ansible/modules/core/network/junos/junos_config.py
<netlab-sw01-a.osl.basefarm.net> ESTABLISH LOCAL CONNECTION FOR USER: stianv
<netlab-sw01-a.osl.basefarm.net> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1466596354.01-95243515745333 `" && echo ansible-tmp-1466596354.01-95243515745333="` echo $HOME/.ansible/tmp/ansible-tmp-1466596354.01-95243515745333 `" ) && sleep 0'
<netlab-sw01-a.osl.basefarm.net> PUT /tmp/tmp8Zee8g TO /home/stianv/.ansible/tmp/ansible-tmp-1466596354.01-95243515745333/junos_config.py
<netlab-sw01-a.osl.basefarm.net> EXEC /bin/sh -c 'chmod -R u+x /home/stianv/.ansible/tmp/ansible-tmp-1466596354.01-95243515745333/ && sleep 0'
<netlab-sw01-a.osl.basefarm.net> EXEC /bin/sh -c '/usr/bin/python /home/stianv/.ansible/tmp/ansible-tmp-1466596354.01-95243515745333/junos_config.py; rm -rf "/home/stianv/.ansible/tmp/ansible-tmp-1466596354.01-95243515745333/" > /dev/null 2>&1 && sleep 0'
ok: [netlab-sw01-a.osl.basefarm.net] => {"changed": false, "invocation": {"module_args": {"comment": "configured by junos_config", "confirm": 0, "host": "netlab-sw01-a.osl.basefarm.net", "lines": ["delete interfaces ge-0/0/0 description"], "password": null, "port": null, "provider": null, "replace": true, "rollback": null, "ssh_keyfile": null, "timeout": 0, "transport": "netconf", "username": null, "zeroize": false}, "module_name": "junos_config"}}

PLAY RECAP *********************************************************************
netlab-sw01-a.osl.basefarm.net : ok=1    changed=0    unreachable=0    failed=0   
```
