### ISSUE TITLE
 azure_rm_deployment - After creating new VM's.. Deployment is deleting rest of resources in the resource group

### ISSUE THREAD

**Issue by praneethr** [ansible/ansible-modules-core#4025]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

 azure_rm_deployment
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### SUMMARY

 After creating new VM's.. Deployment is deleting rest of resources in the resource group.

I created a template https://raw.githubusercontent.com/praneethr/Ansible-Azure-Playbooks/master/azureVM/rhel.deploy.json to create new VM with NIC. It worked through Azure template deployment. So i created below play book and executed after execution task create the server but started deleting rest of resorces VM's NIC's in resource groups. Then i cancelled the deployment from azure portal page
##### STEPS TO REPRODUCE

```

---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: "Create Azure Deploy"
      azure_rm_deployment:
        state: present
        subscription_id: 045adb24-f80b-4b59-975a-b5873f9a0e96
        resource_group_name: BUYDEV1NDXNISRG-APP
        location: eastus2
        template_link: 'https://raw.githubusercontent.com/praneethr/Ansible-Azure-Playbooks/master/azureVM/rhel.deploy.json'
        parameters_link: 'https://raw.githubusercontent.com/praneethr/Ansible-Azure-Playbooks/master/azureVM/rhel.parameter.json'
```

##### EXPECTED RESULTS

rest of resources are deleted
##### ACTUAL RESULTS

```
Using /etc/ansible/ansible.cfg as config file
 [WARNING]: provided hosts list is empty, only localhost is available


PLAYBOOK: createwinvm.yml ******************************************************
1 plays in createwinvm.yml

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Create Windows VM] *******************************************************
task path: /home/cd3ans/ansibleplay/createwinvm.yml:5


```
