### ISSUE TITLE
docker_container restart_policy docs do not match module

### ISSUE THREAD

**Issue by ntwrkguru** [ansible/ansible-modules-core#4028]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

docker_container
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = 
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

Source: OS X 10.11.5
Target: Ubuntu 14.04 on AWS
##### SUMMARY

The restart_policy for the docker_container module should allow a value of unless-stopped, however this produces a syntax error.
##### STEPS TO REPRODUCE

Run the example task

```
  - name: Start Gitlab as a container
    docker_container:
      name: gitlab
      image: gitlab/gitlab-ee:latest
      exposed_ports:
        - 80
        - 443
        - 22
      published_ports:
        - 443:443
        - 80:80
        - 22:22
      hostname: gitlab.example.com
      volumes:
        - /opt/gitlab/config:/etc/gitlab
        - /opt/gitlab/logs:/var/log/gitlab
        - /opt/gitlab/data:/var/opt/gitlab
        - /opt/gitlab/certs:/etc/gitlab/ssl
      state: started
      restart_policy: on-failure
    notify:
      - restart gitlab
```

##### EXPECTED RESULTS

It should work.
##### ACTUAL RESULTS

It fails with a syntax error

```
TASK [Start Gitlab as a container] *********************************************
fatal: [gitlab.example.com]: FAILED! => {"changed": false, "failed": true, "msg": "value of restart_policy must be one of: on-failure,always, got: unless-stopped"}
```
