### ISSUE TITLE
Unable to calculate the checksum of the remote file. Shell is bash. ansible ver 2.0.2.0

### ISSUE THREAD

**Issue by AseemKumar** [ansible/ansible-modules-core#4033]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

Fetch
##### ANSIBLE VERSION

ansible 2.0.2.0
##### CONFIGURATION

default config.
##### OS / ENVIRONMENT

Ansible is running on Ubuntu 14.04.4 LTS.
System being managed is running Oracle Linux Server 6.3
##### SUMMARY

When fetching the passwd file, getting the message "unable to calculate the checksum of the remote file"
##### STEPS TO REPRODUCE

When executing the playbook with the fetch module, getting the checksum message and the host in the recap section is counted as OK. This is happening for very few hosts and all hosts are running same version of kernel and bash shell.

```
- hosts: '{{ target }}'
  gather_facts: no
  tasks:
  - name: Copy passwd file to ansible server.
    fetch: src=/etc/passwd dest=/home/vagrant/gatheredData/password_file

```

##### EXPECTED RESULTS

The passwd file should have got copied and the host should show under the Changed count.
##### ACTUAL RESULTS

Got the checksum error message and the file did not get copied. And the Ok count is updated instead of Failed.

```
ok: [HOSTNAME] => {"changed": false, "file": "/etc/passwd", "invocation": {"module_args": {"dest": "/home/vagrant/gatheredData/password_file", "src": "/etc/passwd"}, "module_name": "fetch"}, "msg": "unable to calculate the checksum of the remote file"}

PLAY RECAP *********************************************************************
HOSTNAME : ok=1    changed=0    unreachable=0    failed=0
```
