### ISSUE TITLE
ec2_vol does not allow adding all available volume types

### ISSUE THREAD

**Issue by mvk** [ansible/ansible-modules-core#4041]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

ec2_vol
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

Linux: `CentOS 7.1`, `Ubuntu 14.04`, `Ubuntu 16.04`
arch: `x86_64`
##### SUMMARY

if you want to attach a volume of type not listed in ec2_vol.py explicitly your task fails.
##### STEPS TO REPRODUCE

The following playbook would fail

```
- name: attach new volume
  hosts: localhost
  tasks:
    module: ec2_vol
    instance: '<your instance id>'
    region: '<your region>'
    device_name: '/dev/xvdf' # or whatever
    volume_size: 40
    volume_type: 'st1'
    iops: 100
    delete_on_termination: true

```
##### EXPECTED RESULTS

I would expect the task to succeed :)
##### ACTUAL RESULTS

```
ansible-playbook -i hosts -e <custom params> playbooks/ec2node-provision.yml
TASK [myuser.ec2node : Attach local volumes (storage_type=local)] **************
task path: /home/user/workspace/ansible/ec2/playbooks/roles/myuser.ec2node/tasks/ec2_setup.yml:43
fatal: [localhost]: FAILED! => {"failed": true, "msg": "value of volume_type must be one of: standard,gp2,io1, got: st1"}
to retry, use: --limit @playbooks/ec2node-provision.retry

PLAY RECAP *********************************************************************
```

The code of `ec2_vol.py` clearly limits types in `main()`
