### ISSUE TITLE
ec2_elb_lb is not always idempotent when updating healthchecks

### ISSUE THREAD

**Issue by jamesongithub** [ansible/ansible-modules-core#4053]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

ec2_elb_lb
##### ANSIBLE VERSION

```
ansible 2.0.1.0
  config file = 
  configured module search path = Default w/o overrides

```
##### CONFIGURATION

N/A
##### SUMMARY

ELB healthcheck changes are sometimes ignored.
##### STEPS TO REPRODUCE

Create elb with tcp healthcheck on port 80 with the module. Run the module again, except using a different port. 

##### EXPECTED RESULTS

The healthcheck should be updated with the new target host:port
##### ACTUAL RESULTS

Invocation of the module

```
"invocation": {
    "module_args": {
      "access_logs": null,
      "aws_access_key": null,
      "aws_secret_key": null,
      "connection_draining_timeout": 120,
      "cross_az_load_balancing": true,
      "ec2_url": null,
      "health_check": {
        "healthy_threshold": 2,
        "interval": 5,
        "ping_port": "45784",
        "ping_protocol": "tcp",
        "response_timeout": 2,
        "unhealthy_threshold": 10
      },
      "idle_timeout": null,
      "instance_ids": null,
      "listeners": [
        {
          "instance_port": "45784",
          "instance_protocol": "http",
          "load_balancer_port": 80,
          "protocol": "http"
        },
        {
          "instance_port": "45784",
          "instance_protocol": "http",
          "load_balancer_port": 443,
          "protocol": "https",
          "ssl_certificate_id": "cert_id"
        },
        {
          "instance_port": "60047",
          "instance_protocol": "tcp",
          "load_balancer_port": 8000,
          "protocol": "ssl",
          "ssl_certificate_id": "cert_id"
        }
      ],
      "name": "elbName",
      "profile": null,
      "purge_instance_ids": false,
      "purge_listeners": true,
      "purge_subnets": false,
      "purge_zones": false,
      "region": "us-east-1",
      "scheme": "internal",
      "security_group_ids": null,
      "security_group_names": [
        "sg1",
        "sg2"
      ],
      "security_token": null,
      "state": "present",
      "stickiness": null,
      "subnets": [
        "subnet-1234a",
        "subnet-1234b",
        "subnet-1234c"
      ],
      "tags": null,
      "validate_certs": true,
      "wait": false,
      "wait_timeout": 60,
      "zones": null
    },
    "module_name": "ec2_elb_lb"
  },
  "item": {
    "service1": {
      "host_port": "50765",
      "task": {
        "name": "taskName"
      }
    },
    "service2": {
      "host_port": "60047"
    },
    "service3": {
      "host_port": "45784",
      "ssl_certificate_id": "cert_id",
      "task": {
        "name": "taskName"
      }
    },
    "name": {
      "suffix": "lend"
    },
    "service": {
      "name": "serviceName"
    }
  }
```

output from module

```
"elb": {
    "app_cookie_policy": null,
    "backends": [

    ],
    "connection_draining_timeout": 120,
    "cross_az_load_balancing": "yes",
    "dns_name": "dns_name",
    "health_check": {
      "healthy_threshold": 2,
      "interval": 5,
      "target": "TCP:52359",
      "timeout": 2,
      "unhealthy_threshold": 10
    },
    "hosted_zone_id": "hostedZoneId",
    "hosted_zone_name": null,
    "idle_timeout": 60,
    "in_service_count": 1,
    "instance_health": [
      {
        "instance_id": "i-250534bf",
        "reason_code": "N/A",
        "state": "InService"
      },
      {
        "instance_id": "i-8e68ebcb",
        "reason_code": "Instance",
        "state": "OutOfService"
      }
    ],
    "instances": [
      "i-250534bf"
    ],
    "lb_cookie_policy": null,
    "listeners": [
      [
        8000,
        60047,
        "SSL",
        "TCP",
        "cert_id"
      ],
      [
        80,
        45784,
        "HTTP",
        "HTTP"
      ],
      [
        443,
        45784,
        "HTTPS",
        "HTTP",
        "cert_id"
      ]
    ],
    "name": "elbName",
    "out_of_service_count": 1,
    "proxy_policy": null,
    "region": "us-east-1",
    "scheme": "internal",
    "security_group_ids": [
      "sg1",
      "sg2"
    ],
    "status": "ok",
    "subnets": [
      "subnet-1",
      "subnet-2",
      "subnet-3"
    ],
    "tags": null,
    "unknown_instance_state_count": 0,
    "zones": [
      "us-east-1a",
      "us-east-1b",
      "us-east-1c"
    ]
  }
```

Note the `ping_port` from the invocation does not match what is in the `target:port` from the healthcheck property of the module output. Seems to be ignored in this run.

**Comment by ansibot** [comment]
@jsdalton, @rickmendes, ping. This issue is waiting on your response.
[click here for bot help](https://github.com/jctanner/ansibullbot/blob/ISSUE_TRIAGE_CLASS/ISSUE_HELP.md)

**Comment by ghost** [comment]
@jamesongithub 

I tried several runs each with boto2 and boto3 and I cannot reproduce your issue. The ping_port changes reliably for me.

This is my Ansible version.

```
ansible 2.0.1.0
  config file = /Users/rmendes/tmp/ansible/module-tests/aws_elb_lb/issue-4053/ansible.cfg
  configured module search path = /Users/rmendes/github/oss/ansible-modules-core:/Users/rmendes/github/oss/ansible-modules-extras
```

This is the playbook I used for testing for the second run.

```
- name: create a test elb
  hosts: all
  connection: local
  gather_facts: False

  tasks:

  - name: Create ELB for issue testing
    local_action:
      module: ec2_elb_lb
      profile: "my-test-account"
      region: "us-east-1"
      name: "test-elb-issue-4053"
      state: present
      zones: "us-east-1c"
      tags:
        Name: "testing-issue-4053"
        type: "my-test-elb"
        env: "module testing"
      cross_az_load_balancing: "yes"
      security_group_names: "my-test-sg"
      listeners:
      - protocol: http
        load_balancer_port: 80
        instance_port: 45784
      health_check:
        ping_protocol: tcp
        ping_port: 45784
        response_timeout: 2
        interval: 5
        unhealthy_threshold: 10
        healthy_threshold: 2
      wait: yes
```

Module output snippet from the update run.

```
"health_check": {
  "healthy_threshold": 2, 
  "interval": 5, 
  "target": "TCP:45784", 
  "timeout": 2, 
  "unhealthy_threshold": 10
}
```

You want to give this a try @jsdalton?
