### ISSUE TITLE
uri: An unknown error occurred: object of type 'bool' has no len()

### ISSUE THREAD

**Issue by Delivion-GmbH** [ansible/ansible-modules-core#4071]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

uri

##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file =
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

[defaults]
remote_tmp = /tmp
ssh_args = -v
host_key_checking = False
callback_plugins = plugins

[ssh_connection]
control_path=%(directory)s/a%%h-%%p-%%r
ssh_args = -o StrictHostKeyChecking=no
##### OS / ENVIRONMENT

centos-release-7-2.1511
##### SUMMARY

Instead of putting the value as string "True" ansible automatically sets the value to type bool but then the PUT Requests returns not status code 200
##### STEPS TO REPRODUCE

```
Create an ansible task:
- name: sent some value to some api
       uri: url="http://localhost:{{http_api_port}}/v1/kv/{{example_dict.name}}/{{item.key}}"
         method=PUT
         body="{{item.value}}"
       with_dict: example_dict

The dict that is used here:

example_dict:
   name: example
   port: "{{ ols_port }}"
   health_endpoint_port: "{{ ols_management_port }}"
   use_health_endpoint: "True"
   health_endpoint: "/health"


```

##### EXPECTED RESULTS

```
    ok: [xxx.xxx.xxx.xxx] => (item={'key': 'use_health_endpoint', 'value': 'True'}) => {"changed": false, "content_length": "4", "content_type": "application/json", "date": "Wed, 22 Jun 2016 05:39:10 GMT", "item": {"key": "use_health_endpoint", "value": "True"}, "json": true, "redirected": false, "status": 200}
```
##### ACTUAL RESULTS

```
failed: [xxx.xxx.xxx.xxx] (item={'value': True, 'key': u'use_health_endpoint'}) => {"content": "", "failed": true, "item": {"key": "use_health_endpoint", "value": True}, "msg": "Status code was not [200]: An unknown error occurred: object of type 'bool' has no len()", "redirected": false, "status": -1, "url": "http://localhost:8500/v1/kv/example/use_health_endpoint"}
```

This was working as expected with ansible 1.9.X

**Comment by robertlindner** [comment]
One Addition: This used to work with ansible 1.9.x even when the variable in the dict was unquoted, so I suspect there was some implicit bool-> string type conversion in place.
Now it even fails when you try to explicitly apply a jinja string() filter.

**Comment by nitzmahone** [comment]
YAML type coercion is likely what's biting you here- not a lot we can do about it. It might've worked in some cases in 1.9 due to the templating order- we changed things in 2.x to make that much more consistent. You should be able to work around this by explicitly telling YAML it's a string, eg:

```
example_dict:
   name: example
   port: "{{ ols_port }}"
   health_endpoint_port: "{{ ols_management_port }}"
   use_health_endpoint: !!str "True"
   health_endpoint: "/health"
```

**Comment by Delivion-GmbH** [comment]
Thank you for your reply. I tested it 5 minutes ago but unfortunately i'm still getting the error:

"Status code was not [200]: An unknown error occurred: object of type 'bool' has no len()"

```
example_dict:
   name: example
   port: "{{ ols_port }}"
   health_endpoint_port: "{{ ols_management_port }}"
   use_health_endpoint: !!str "True"
   health_endpoint: "/health"
```

**Comment by nitzmahone** [comment]
Ah, right- forgot you were templating the value on the way into the module. You'll need to use the YAML dict syntax (not Ansible KV syntax) and type-tag it on the actual module arg:

```
     - name: sent some value to some api
       uri: 
         url: "http://localhost:{{http_api_port}}/v1/kv/{{example_dict.name}}/{{item.key}}"
         method: PUT
         body: !!str "{{item.value}}"
       with_dict: example_dict
```
