### ISSUE TITLE
service module used in handler doesn't get excalated privilege

### ISSUE THREAD

**Issue by asmodehn** [ansible/ansible-modules-core#4077]
Similar to https://github.com/ansible/ansible-modules-core/issues/3018 but a tiny bit different...
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

service module
##### ANSIBLE VERSION

```
ansible --version
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

default on ubuntu trusty package Version: 2.1.0.0-1ppa~trusty
##### OS / ENVIRONMENT

Ubuntu Trusty
##### SUMMARY

I am using [supervisor](https://galaxy.ansible.com/tersmitten/supervisor) role as a dependency to ensure all services are restarted after reconfiguration.
I am specifying `become:yes` when using that role. but it seems the handler is not getting that escalated privilege
##### STEPS TO REPRODUCE

I am using supervisor as a dependency like so : 

```

---
# myrole/meta/main.yml
galaxy_info:
...
dependencies:
 - role: tersmitten.supervisor
   supervisor_programs_present:
     syncthing:
       user: yujin
       environment: STNORESTART="1", HOME="/home/some_user"
       command: /usr/bin/syncthing -no-browser -home="/home/yujin/.config/syncthing
       autostart: true
       stdout_logfile: /var/log/supervisor/syncthing.out.log
       stderr_logfile: /var/log/supervisor/syncthing.err.log
```

The playbook containing : 

```
   - role: myrole
     tags: myrole
     become: yes
```

The handler in [supervisor](https://galaxy.ansible.com/tersmitten/supervisor) role looks like : 

```
# handlers file for supervisor

---
- name: restart supervisor
  service:
    name: supervisor
    state: restarted
  when: supervisor_state == 'started'
```
##### EXPECTED RESULTS

I would expect the handler somehow to be aware that it needs to become (root) and supervisor service to be restarted.
##### ACTUAL RESULTS

```
TASK [tersmitten.supervisor : start and enable service] ************************
ok: [gocart-server] => {"changed": false, "enabled": true, "name": "supervisor", "state": "started"}

RUNNING HANDLER [tersmitten.supervisor : restart supervisor] *******************
fatal: [gocart-server]: FAILED! => {"changed": false, "failed": true, "msg": "start-stop-daemon: warning: failed to kill 20874: Operation not permitted\n"}
```

We can reproduce this behavior with a privilege issue like so :

```
alexv@asmodehn:~/Projects/yujin_tools/ansible/namsung$ ansible -i devel gocart-server -K -u yujin -m service -a "name=supervisor state=restarted" -b
SUDO password: 
gocart-server | FAILED! => {
    "changed": false, 
    "failed": true, 
    "msg": "Stopping supervisor: supervisord.\nStarting supervisor: "
}
alexv@asmodehn:~/Projects/yujin_tools/ansible/namsung$ ansible -i devel gocart-server -K -u yujin -m service -a "name=supervisor state=restarted" -b
SUDO password: 
gocart-server | SUCCESS => {
    "changed": true, 
    "name": "supervisor", 
    "state": "started"
}
alexv@asmodehn:~/Projects/yujin_tools/ansible/namsung$ ansible -i devel gocart-server -K -u yujin -m service -a "name=supervisor state=restarted"
SUDO password: 
gocart-server | FAILED! => {
    "changed": false, 
    "failed": true, 
    "msg": "start-stop-daemon: warning: failed to kill 786: Operation not permitted\n"
}
```
