### ISSUE TITLE
ec2_ami not handling wait:no and tags correctly

### ISSUE THREAD

**Issue by hyperized** [ansible/ansible-modules-core#4078]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

ec2_ami.py
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

I have three problems with the current execution:
1. wait: no still waits. It still waits till the AMI is available or a time_out.
2. As shown below, the tags are present but not displayed as output.
3. When the wait time expires, the AMI is created however the tags are ignored, suggesting they are only added after the wait has expired. I would expect this to happen before on wait: no
##### STEPS TO REPRODUCE

Playbook:

```
    - name: create AMI backup
      ec2_ami:
        region: "{{ ec2_region }}"
        instance_id: "{{ ec2_id }}"
        wait: no
        no_reboot: yes
        name: "{{ ec2_tag_Name }}"
        tags:
          creation: "{{ ansible_date_time.epoch }}"
          expiration: "{{ expiration_date.stdout }}"
      register: output
```
##### EXPECTED RESULTS

I expected the following results:
1. The playbook moves on and does not wait for results
2. Tags are shown in the output
3. Tags show in the AWS console after a time_out has been reached.
##### ACTUAL RESULTS

Output on a normal run (after waiting for the task to complete):

```
TASK [create AMI backup] *******************************************************
changed: [*.*.*.*]

TASK [debug] *******************************************************************
ok: [*.*.*.*] => {
    "output": {
        "architecture": "x86_64",
        "block_device_mapping": {
            "/dev/sda1": {
                "delete_on_termination": true,
                "encrypted": false,
                "size": 8,
                "snapshot_id": "snap-*******",
                "volume_type": "gp2"
            }
        },
        "changed": true,
        "creationDate": "2016-06-29T09:31:56.000Z",
        "description": null,
        "hypervisor": "xen",
        "image_id": "ami-******",
        "is_public": false,
        "location": "*******/*****-2016-06-monthly",
        "msg": "AMI creation operation complete",
        "ownerId": "*******",
        "root_device_name": "/dev/sda1",
        "root_device_type": "ebs",
        "state": "available",
        "tags": {},
        "virtualization_type": "hvm"
    }
}
```

In the situation where a time_out occurs:

```
09:12:36            TASK [create AMI backup] *******************************************************
09:28:18            fatal: [*.*.*.* -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error while trying to find the new image. Using wait=yes and/or a longer wait_timeout may help."}
```

Also notice how this is by no means the 300 seconds ( 5 minutes ) specified as the default.

I think this module needs a good once over to verify the combination of delegation, tags and wait functions properly. Thanks!
