### ISSUE TITLE
user: expires expects float epoch time

### ISSUE THREAD

**Issue by marcusspain** [ansible/ansible-modules-core#4084]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

user module
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

inventory      = /var/local/ansible/hosts
roles_path      = /var/local/ansible/roles
log_path = /home/ansible/ansible.log
##### OS / ENVIRONMENT

CentOS Linux release 7.0.1406 (Core) 
##### SUMMARY

When adding a user, with the `expires` option, specifying epoch time as an int throws an error.

```
expires: 3268684800
```

results in:
`"argument expires is of type <type 'int'> and we were unable to convert to float"`

It works when changed to:

```
expires: 3268684800.0
```
##### STEPS TO REPRODUCE

```
  tasks:
  - name: add exampleuser
    user:
      name: exampleuser
      groups: wheel
      append: yes
      password: $1$X65joYEp$WiZRYzEF25NxYjBvmQK/C/
      expires: 3268684800
```

##### EXPECTED RESULTS

```
changed: [192.168.61.180]
```
##### ACTUAL RESULTS

```
fatal: [192.168.61.180]: FAILED! => {"changed": false, "failed": true, "msg": "argument expires is of type <type 'int'> and we were unable to convert to float"}
```
