### ISSUE TITLE
docker_service only finds docker-compose.yml on local runs (CentOS/RHEL)

### ISSUE THREAD

**Issue by andrefernandes** [ansible/ansible-modules-core#4085]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

Module: docker_service
##### ANSIBLE VERSION

Ansible 2.1 (installed with "pip install"). Results from "ansible --version":

```
ansible 2.1.0.0
  config file =
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

Controller node: CentOS 7.2
Remote node: RHEL 7.1
##### SUMMARY

When using playbooks the module only works with "docker-compose.yml" files if ran locally. Remote runs only work with inline definitions.
##### STEPS TO REPRODUCE

Take this simple playbook below (file named "web-deploy.yml"):

```
- name: Nginx deployment
  hosts: '{{ target }}'
  tasks:
  - docker_image:
      name: nginx
  - docker_service:
      project_name: nginx_sample
      project_src: '.'
```
##### EXPECTED RESULTS

It works ok when ran locally:

```
ansible-playbook web-deploy.yml --extra-vars "target=local"

PLAY [Nginx deployment] ********************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [docker_image] ************************************************************
ok: [localhost]

TASK [docker_service] **********************************************************
ok: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0

```
##### ACTUAL RESULTS

Fails when 'target' is a remote host. Please notice that 'docker_image' task runs ok, so I did figure out all the remote python dependencies.

```
ansible-playbook web-deploy.yml --extra-vars "target=dados-t" -u goodsshuser

PLAY [Nginx deployment] ********************************************************

TASK [setup] *******************************************************************
ok: [myserver]

TASK [docker_image] ************************************************************
ok: [myserver]

TASK [docker_service] **********************************************************
fatal: [myserver]: FAILED! => {"changed": false, "failed": true, "msg": "Configuration error - \n        Can't find a suitable configuration file in this directory or any\n        parent. Are you in the right directory?\n\n        Supported filenames: docker-compose.yml, docker-compose.yaml\n        "}

NO MORE HOSTS LEFT *************************************************************
        to retry, use: --limit @web-deploy.retry

PLAY RECAP *********************************************************************
myserver  : ok=2    changed=0    unreachable=0    failed=1

```
##### EXTRA INFO

The remote RHEL node had its python dependencies installed with the following commands:

```
pip install PyYAML
pip install docker-py
pip install docker-compose
```

The remote RHEL node runs Docker's docker engine (1.11), **not** the one in RHEL distro, but this should not be an issue.

**Comment by zagyi** [comment]
I'have also hit this problem. My quick workaround is to upload the docker-compose.yml files as follows:

```
- set_fact: compose_dir=/var/tmp/ansible-docker-service

- file: 
    path: "{{ compose_dir }}"
    state: directory

- name: Upload docker-compose files
  synchronize: 
    src: "{{ item }}"
    dest: "{{ compose_dir }}"
  with_items:
    - gitlab
    - other_prjs
```

And then refer to the project so:

```
- name: Start GitLab
  docker_service:
    project_src: "{{ compose_dir }}/gitlab"
```

Not nice, but works for now.
