### ISSUE TITLE
docker_container command does not accept YAML folded scalars

### ISSUE THREAD

**Issue by guhcampos** [ansible/ansible-modules-core#4099]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

ansible-modules-core/cloud/docker/docker_container
##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

No relevant changes
##### OS / ENVIRONMENT

Confirmed in Mac OSX (installed from Brew) and Archlinux
##### SUMMARY

The `command` parameter does not work if the command is composed of a YAML folded scalar. Returns a `(\"oci runtime error: exec: \"ls\\n\": executable file not found in $PATH\")` **(note the `\n`)** for any command issued.
##### STEPS TO REPRODUCE

```

---

- hosts: localhost
  connection: local
  tasks:
    - name: test without line break
      docker_container:
        image: alpine
        recreate: true
        name: docker_test
        command: ls

- hosts: localhost
  connection: local
  tasks:
    - name: test with line break
      docker_container:
        image: alpine
        recreate: true
        name: docker_test
        command: >
          ls

```
##### EXPECTED RESULTS

Ansible should bring a container and run "ls" on both cases.
##### ACTUAL RESULTS

Second test fails with `404 Client Error: Not Found (\"oci runtime error: exec: \"ls\\n\": executable file not found in $PATH\")`:

```
PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [test without line break] *************************************************
changed: [localhost]

PLAY [localhost] ***************************************************************

TASK [test with line break] ****************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error starting container d178b5a3f07c320603ee504388dbd244992700647ba2ae516a1168db11565b6f: 404 Client Error: Not Found (\"oci runtime error: exec: \"ls\\n\": executable file not found in $PATH\")"}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=1
```

**Comment by guhcampos** [comment]
It seems that

`command: ls -l`

Also does not work.

So the problem might no be with folded scalars at all, but in the way `docker_container` passes the command on to Docker. 

#### Example Playbook

```
# - hosts: localhost
#   connection: local
#   tasks:
#     - name: test without line break
#       docker_container:
#         image: alpine
#         recreate: true
#         name: docker_test
#         command: ls -l
```

#### Example output

```
PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [test without line break] *************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error starting container c7a43ebcfe8ff27dbb1dd06ede2ba4184a88074927eea23a2d3623a68b9d0a53: 404 Client Error: Not Found (\"oci runtime error: exec: \"ls -l\": executable file not found in $PATH\")"}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1
```

**Comment by ghost** [comment]
interesting, I wasn't able to reproduce it.

```
Linux
$ ansible --version
ansible 2.2.0 (devel 0430923647) last updated 2016/07/05 11:27:19 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 1d0d5db97a) last updated 2016/06/30 19:09:37 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 00b8b96906) last updated 2016/06/30 19:09:37 (GMT +200)
  config file = /home/arno/.ansible.cfg
  configured module search path = Default w/o overrides
```

**Comment by chouseknecht** [comment]
Using the latest in devel, I'm not able to reproduce.

The playbook:

```
---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: test without line break
      docker_container:
        image: alpine
        recreate: true
        name: docker_test
        command: ls

    - name: test with line break
      docker_container:
        image: alpine
        recreate: true
        name: docker_test
        command: >
          ls
```

The output: 

```
PLAY [localhost] ***************************************************************

TASK [test without line break] *************************************************
changed: [localhost]

TASK [test with line break] ****************************************************
changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=2    unreachable=0    failed=0
```
