### ISSUE TITLE
--diff options not showing differences for template module when using with_items

### ISSUE THREAD

**Issue by jglapa** [ansible/ansible-modules-core#4106]
So I see that similar issues were reported and closed since a while but whatever version 2.x I wouldn't be using it just doesn't work.
https://github.com/ansible/ansible/issues/15492
https://github.com/ansible/ansible/issues/13232
https://github.com/ansible/ansible-modules-core/issues/3715
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME
- template
##### ANSIBLE VERSION

```
ansible 2.0.2.0
ansible 2.1.0.0
ansible 2.0.0.1
```
##### CONFIGURATION

default
##### OS / ENVIRONMENT

Ubuntu 14
##### SUMMARY

When templating files that have differences I could observe the difference when using --diff (-D) option in version v2.x this seems to be broken
##### STEPS TO REPRODUCE

```

---
- name: Sync files
  hosts: localhost
  remote_user: ubuntu
  vars:
    var_current_time : '{{ ansible_date_time.epoch }}'
  tasks:
  - name: Sync config files
    template: src=files/{{item}} dest=/tmp
    with_items:
        - "config.txt"

```

files/config.txt:

```
foo={{var_current_time}}
```

##### EXPECTED RESULTS

```
PLAY [Sync files] ************************************************************* 

GATHERING FACTS *************************************************************** 

ok: [localhost]

TASK: [Sync config files] ***************************************************** 
--- before: /tmp
+++ after: /home/jglapa/test/files/config.txt
@@ -0,0 +1 @@
+foo=1467724485
changed: [localhost] => (item=config.txt)

PLAY RECAP ******************************************************************** 
localhost                  : ok=2    changed=1    unreachable=0    failed=0   

```
##### ACTUAL RESULTS

```
PLAY [Sync files] **************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Sync config files] *******************************************************
changed: [localhost] => (item=config.txt)

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0   
```
