### ISSUE TITLE
systemd daemon-reload bug

### ISSUE THREAD

**Issue by linusgg** [ansible/ansible-modules-core#4113]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

systemd
##### ANSIBLE VERSION

ansible 2.2.0 (devel 0430923647) last updated 2016/07/05 14:46:17 (GMT +1000)
  lib/ansible/modules/core: (detached HEAD 1d0d5db97a) last updated 2016/07/04 16:05:48 (GMT +1000)
  lib/ansible/modules/extras: (detached HEAD 00b8b96906) last updated 2016/07/04 16:06:19 (GMT +1000)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
##### CONFIGURATION

ansible_managed = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
hostfile = ./inventory
remote_user = centos
host_key_checking = False
log_path = /var/log/ansible.log
##### OS / ENVIRONMENT

control node: ubuntu 14.04 LTS
remote node: centos 7
##### SUMMARY

Hi,
I am having issue with systemd module.
The daemon-reload directive doesn't seem to run before the actual action.
##### STEPS TO REPRODUCE

After I added a new service script in init.d (yeah, it is a systemV script but systemd has no problem running it when I manually execute on remote node) and then run this play

```
- name: test | make sure activemq starts
  systemd:
    daemon_reload: yes
    name: activemq
    enabled: yes
    state: started
```

It gives me 
fatal: [192.168.3.122]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"daemon_reload": true, "enabled": true, "masked": null, "name": "activemq", "state": "started"}, "module_name": "systemd"}, "msg": "Could not find the requested service \"'activemq'\": "}

But if I do a work around to make sure daemon-reload is called before actual action,

```
- name: test | reload daemon
  systemd:
    daemon_reload: yes
    name: sshd

- name: test | make sure activemq starts
  systemd:
    daemon_reload: yes
    name: activemq
    enabled: yes
    state: started
```

Then it works fine.

##### EXPECTED RESULTS

changed with no errors
##### ACTUAL RESULTS

fatal: [192.168.3.122]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"daemon_reload": true, "enabled": true, "masked": null, "name": "activemq", "state": "started"}, "module_name": "systemd"}, "msg": "Could not find the requested service \"'activemq'\": "}

```

```
