### ISSUE TITLE
Unable to list objects in a s3 bucket

### ISSUE THREAD

**Issue by nandakishore15** [ansible/ansible-modules-core#4133]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.1.0
  config file = /home/ubuntu/weyv-deployment/ansible-repo/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

Ubuntu 14.04.4 LTS
##### SUMMARY

Cannot list objects in a bucket.
##### STEPS TO REPRODUCE

```
- name: List objects in a s3 bucket
      s3:
        mode: list
        bucket: mybucket
        prefix: "archive"

- name: List objects in a s3 bucket
      s3:
        mode: list
        bucket: mybucket
```

##### EXPECTED RESULTS

List objects in the bucket.
##### ACTUAL RESULTS

```
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"bucket": "mybucket", "mode": "list", "prefix": "archive"}, "module_name": "s3"}, "msg": "unsupported parameter for module: prefix"}

fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"bucket": "mybucket", "expiry": 600, "mode": "list", "overwrite": true, "validate_certs": true}, "module_name": "s3"}, "msg": "value of mode must be one of: get,put,delete,create,geturl,getstr, got: list"}
```
