### ISSUE TITLE
docker_container module purge_networks FAILS

### ISSUE THREAD

**Issue by ghost** [ansible/ansible-modules-core#4139]
#3796
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

docker_container
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel bbffa0a0e9) last updated 2016/07/08 11:33:09 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 799159b8ee) last updated 2016/07/08 11:33:18 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 8502d2595a) last updated 2016/07/08 11:33:18 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

Added path to my own roles in ansible.cfg
##### OS / ENVIRONMENT

Linux 4.2.0-27-generic #32~14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
##### SUMMARY

Trying to use purge_networks option in a role. Fails while running. Python doesn't like when we call append on a  #dictionary.
##### STEPS TO REPRODUCE

Create a docker network on the host.

```
docker network create my_network
```

Playbook to reproduce the error.

```
- hosts: all
  tasks:
  - name: Create docker container and purge network
    docker_container:
     name: "busybox"
     image: "busybox"
     state: started
     networks:
      - name: "my_network"
     purge_networks: yes

```
##### EXPECTED RESULTS

I expected that a container named "busybox" should be created on the host. The container should only be connected to the network "my_network".
##### ACTUAL RESULTS

```
FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "docker_container"}, "module_stderr": "OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 10933\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\nShared connection to XXXXX closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_10ZY3F/ansible_module_docker_container.py\", line 1921, in <module>\r\n    main()\r\n  File \"/tmp/ansible_10ZY3F/ansible_module_docker_container.py\", line 1914, in main\r\n    cm = ContainerManager(client)\r\n  File \"/tmp/ansible_10ZY3F/ansible_module_docker_container.py\", line 1575, in __init__\r\n    self.present(state)\r\n  File \"/tmp/ansible_10ZY3F/ansible_module_docker_container.py\", line 1620, in present\r\n    container = self.update_networks(container)\r\n  File \"/tmp/ansible_10ZY3F/ansible_module_docker_container.py\", line 1699, in update_networks\r\n    self.diff['differences'].append(dict(purge_networks=extra_networks))\r\nAttributeError: 'dict' object has no attribute 'append'\r\n", "msg": "MODULE FAILURE", "parsed": false}

```

**Comment by ghost** [comment]
Ok, the command doesn't fail but the "bridge" network still exists.

Running with latest

```
ansible 2.2.0 (devel 221520cbad) last updated 2016/07/13 09:46:03 (GMT +200)
  lib/ansible/modules/core: (devel 67dadf3aa4) last updated 2016/07/13 09:34:39 (GMT +200)
  lib/ansible/modules/extras: (devel f2b255ffa3) last updated 2016/07/13 09:52:00 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

**Comment by ghost** [comment]
@chouseknecht Does this work as expected for you?

**Comment by hd-deman** [comment]
@chouseknecht @tecarlsson same for me:
the command doesn't fail but the "bridge" network still exists.
On latest ansible devel. so reopen please.

**Comment by tallandtree** [comment]
I've not tested with ansible 2.2.0, but have a workaround for those that use ansible 2.1.1.x:
1. Create containers using module docker_containers without purge_networks:yes
2. Then start containers using module docker_containers with state=started
3. Disconnect containers from bridge (or other network) with module docker_container and purge_networks: yes and state: started.
   Apparently the purge_networks only works with running containers.

```
- name: Create container
  docker_container:
     name: mycontainer
     image: "busybox"
     networks:
         - name: mynetwork
    state: present
  register: register_mycontainer_created

# do something else here

- name: Start container
  docker_container:
     name: mycontainer
     state: started

- name: Purge networks
  docker_container:
     name: mycontainer
     networks: 
          -name: mynetwork
     purge_networks: yes
     state: started
     when: register_mycontainer_created|changed
```
