### ISSUE TITLE
"docker_service.build" does not recognize "true" (and needs explicit "bool" filter)

### ISSUE THREAD

**Issue by joaocc** [ansible/ansible-modules-core#4158]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

docker_service
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
export ANSIBLE_HOST_KEY_CHECKING=false
export ANSIBLE_GATHERING=smart
export ANSIBLE_ROLES_PATH=/opt/src/ansible/rr
export ANSIBLE_PRIVATE_ROLE_VARS=true

export ANSIBLE_JINJA2_EXTENSIONS=jinja2.ext.do,jinja2.ext.i18n
#export ANSIBLE_KEEP_REMOTE_FILES=1

export ANSIBLE_NOCOWS=1

export ANSIBLE_SSH_ARGS="-o ControlMaster=auto -o ControlPersist=15s -o GSSAPIAuthentication=no -v -o ForwardAgent=yes"
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

"docker_service" doesn't seem to be able to convert boolean parameter passed through a role without explicit "|bool" filter
##### STEPS TO REPRODUCE

Role (with problem)

```
roles/docker-compose-runner
    defaults/main.yml
        ...
        docker_compose_build: false
        ...

    tasks/main.yml
        - name: "execute generated docker-compose"
          become: true
          docker_service:
            project_src:  "{{ remote_compose_repo }}/{{ docker_compose_name }}"
            files: "{{ docker_compose_yml_base |union(docker_compose_yml_override) }}"
            build: "{{ docker_compose_build }}"
            state: "{{ 'present' if docker_compose_up else 'absent' }}"
            stopped: "{{ 'false' if docker_compose_running else 'true' }}"
            debug: yes
          environment: "{{ docker_compose_env_base |combine(docker_compose_env) }}"
          register: a_d_composer_output
          when: "{{ docker_compose__op_run }}"

```

Role (fixed)

```
roles/docker-compose-runner
    tasks/main.yml
        - name: "execute generated docker-compose"
          become: true
          docker_service:
            ...
            build: "{{ docker_compose_build |bool }}"
            ...
```

playbook

```
    ---
    - hosts: dchosts
          vars:
             ...
          roles:
            - role: docker-compose-runner
              docker_compose_name: "cname"
              docker_compose_dir:  "{{ compose_root }}/{{ docker_compose_name }}"
              localvol_mount_root:  "{{ mount_root }}"
              docker_compose_build:   true
              docker_compose_up:      true
              docker_compose_running: true
              docker_compose_debug_out: true
```
##### EXPECTED RESULTS

That the build would be forced without the need to add "| bool" to convert from string to bool
##### ACTUAL RESULTS

Build is not generated
