### ISSUE TITLE
azure_rm_virtualmachine module fails creating a virtualmachine when the name of vm contains upper-case.

### ISSUE THREAD

**Issue by h-hirokawa** [ansible/ansible-modules-core#4174]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

azure_rm_virtualmachine
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 221520cbad) last updated 2016/07/13 15:32:29 (GMT +900)
  lib/ansible/modules/core: (detached HEAD db8af4c5af) last updated 2016/07/13 15:32:38 (GMT +900)
  lib/ansible/modules/extras: (detached HEAD 482b1a640e) last updated 2016/07/13 15:32:38 (GMT +900)
  config file =
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Creating a new azure virtualmachine with upper-cased letter fails without setting a specific storage account because `AzureRMVirtualMachine.create_default_storage_account` try to create a storage account with upper-case.
As described in [this document](https://msdn.microsoft.com/en-us/library/azure/hh264518.aspx), the storage account name can only use numbers and lower-case letters.
##### STEPS TO REPRODUCE

Here is a sample task.

``` yaml
- azure_rm_virtualmachine:
    name: nameWithUpper
    resource_group: Testing
    vm_size: Standard_D1
    public_ip_allocation_method: Dynamic
    admin_username: AdminUserName
    admin_password: AdminP@ssw0rd
    open_ports:
      - 3389
      - 5986
    os_type: Windows
    image:
      publisher: MicrosoftWindowsServer
      offer: WindowsServer
      sku: Windows-Server-Technical-Preview
      version: latest
```
##### EXPECTED RESULTS

The module should convert the vm name to lowercase before trying to create a default storage account.
##### ACTUAL RESULTS

Creating storage account always fails as below.

```
TASK [azure_rm_virtualmachine] *************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to create a unique storage account name for nameWithUpper. Try using a different VM name."}
```
