### ISSUE TITLE
Using backup and with_items can loose the original file as you get the backup of the next to last item

### ISSUE THREAD

**Issue by sigio** [ansible/ansible-modules-core#4177]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

ini_file module
##### ANSIBLE VERSION

ansible 2.1.0
##### OS / ENVIRONMENT

N/A (Linux, Debian Stable, ansible from pip)
##### SUMMARY

When modifying a single file with multiple changes using ini_file and with_items, together with the `backup=yes` option, the (possibly created) backup is overwritten by subsequent loop-runs.

I had a task that modified php.ini in various sections, after a run I noticed there was 1 backup file besides the original file (and a backup I created manually before-hand, just to test).
The created backup file already had the 1st change, and the new php.ini had both changes.
My guess is that since both tasks ran in the same second, the backup-file name was the same on both runs, and therefore the original backup was overwritten.

A single backup-file would be preferred... but I'm guessing every single with_items call will make a new backup file (possibly overwriting the same file every time).
##### STEPS TO REPRODUCE

```
- name: Configure php.ini settings
  ini_file: dest=/etc/php.ini owner=root group=root mode=0644 backup=yes section={{item.section}} option={{item.option}} value={{item.value}}
  with_items:
    - { section: "Date", option: "date.timezone", value: "{{timezone_name}}" }
    - { section: "Session", option: "session.gc_maxlifetime", value: "{{php_session_gc_maxlifetime|default(1440)}}" }
```
##### EXPECTED RESULTS

A single backup file, which is unchanged from the original.
##### ACTUAL RESULTS

```
-rw-r--r-- 1 root root 69113 Jul 13 11:04 php.ini
-rw-r--r-- 1 root root 69113 Jul 13 11:04 php.ini.2016-07-13@11:04:08~
-rw-r--r-- 1 root root 69097 Jul 13 11:03 php.ini.my-own-backup
```
