### ISSUE TITLE
docker_image module always returns changed with state: present

### ISSUE THREAD

**Issue by otaviomedeiros** [ansible/ansible-modules-core#4184]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

docker_image
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /Users/otaviomedeiros/MyProjects/my-evernote/setup-automation/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

My ansible.cfg

```
[defaults]
inventory=./dev
remote_user = vagrant

```
##### OS / ENVIRONMENT

OSX
##### SUMMARY

`docker_image` module always returns `changed` with `state: present`
##### STEPS TO REPRODUCE

```

---
- hosts: webserver
  become: true
  gather_facts: false
  tasks:
    - name: pull node image
      docker_image:
        name: node:argon
        state: present

```
##### EXPECTED RESULTS

I expect that it only should be `changed` when it is executed the first time
##### ACTUAL RESULTS

```
PLAY [webserver] ***************************************************************

TASK [pull node image] *********************************************************
changed: [192.168.99.120]

PLAY RECAP *********************************************************************
192.168.99.120             : ok=1    changed=1    unreachable=0    failed=0   
```

**Comment by otaviomedeiros** [comment]
It is ok when i used this way...

```
tasks:
    - name: pull node image
      docker_image:
        name: node
        state: present
        tag: 'argon'
```

```
TASK [pull node image] *********************************************************
ok: [192.168.99.120]
```
