### ISSUE TITLE
ec2 module does not create root volume as documented

### ISSUE THREAD

**Issue by AgDude** [ansible/ansible-modules-core#4204]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

ec2 module
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### OS / ENVIRONMENT

ubuntu 14.04
##### SUMMARY

Launching an EBS backed ec2 instance with a non-default root volume does not work as shown in the documentation example. Instead it launches an instance with a standard 8GB root volume, and an additional volume per the definition.

The following is the task which was used to launch the instance (some keys removed for brevity):

```
    - name: Launch ec2 instance
      ec2:
        instance_type: "t2.small"
        volumes:
          - device_name: /dev/xvda
            volume_type: gp2
            volume_size: 15
      register: ec2
```

This is the example from http://docs.ansible.com/ansible/ec2_module.html, which shows a non-standard root volume:

```
# Single instance with ssd gp2 root volume
- ec2:
    key_name: mykey
    group: webserver
    instance_type: c3.medium
    image: ami-123456
    wait: yes
    wait_timeout: 500
    volumes:
      - device_name: /dev/xvda
        volume_type: gp2
        volume_size: 8
    vpc_subnet_id: subnet-29e63245
    assign_public_ip: yes
    exact_count: 1
```

**Comment by andreafzo** [comment]
Hello,
I'm having the same problem. In addition, I can say that if you use an AMI that has the root folder set to /dev/sda (such as CentOS one), really weird things happen: from the web console I noticed that an additional EBS volume get created (from the snapshot of the AMI) but it is completely detached from the instance, so it becomes an effective "dangling reference". I tried to reference it from inside the command, but when I use /dev/sda as a device_name I get an error. In order to test it you can use, as ami id, the following one: ami-6d1c2007.

**Comment by marcovnyc** [comment]
I solved this problem instead of using the example
- device_name: /dev/xvda
  i used this instead. 
- device_name: /dev/sda1 

then the root drive was created as a 20 Gig drive as  i had defined it. 

root@ip-172-31-154-181:~# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            7.4G   12K  7.4G   1% /dev
tmpfs           1.5G  352K  1.5G   1% /run
/dev/xvda1       20G  1.2G   18G   7% /

this is on an ubuntu machine.

**Comment by ansibot** [comment]
@ansible, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by chris-neely** [comment]
I'm having a similar issues with windows instances but regardless of the mount point it launches an instances with the default volume_size.  I opened my own problem; but curious if you had any luck with this?

**Comment by mazzystr** [comment]
Confirmed with ansible 2.1.2.0 against Red Hat Cloud Access ami (us-east-1 / ami-10251c7a)

```
  ec2:
    key_name: mykey
    instance_type: "{{ bastion }}"
    image: "{{ ami }}"
    volumes:
      - device_name: /dev/xvda
        volume_type: gp2
        volume_size: 25
        delete_on_termination: true
    monitoring: no
    region: "{{ region }}"
    instance_tags:
      Name: "bastion.{{ public }}"
    termination_protection: no
    vpc_subnet_id: "{{ vpc.subnets.0.id }}"
    assign_public_ip: yes
```

**Comment by ansibot** [comment]
@ansible, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@ansible, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by mazzystr** [comment]
The following works for us

```
- name: Creating AWS EC2 Bastion instances
  ec2:
    assign_public_ip: no
    exact_count: 1
    group: ['BastionSg']
    instance_profile_name: bastion
    instance_type: "{{ type }}"
    image: "{{ ami }}"
    instance_tags:
      Name: "bastion.{{ domain }}"
      Role: "Bastion"
      environment: "dev"
    key_name: "{{ keypair }}"
    monitoring: no
    region: "{{ region }}"
    termination_protection: no
    volumes:
      - device_name: /dev/sda1
        device_type: gp2
        volume_size: 30
        delete_on_termination: true
    vpc_subnet_id: "{{ subnet }}"
```
