### ISSUE TITLE
ELB documentation does not match reality: listeners are mandatory

### ISSUE THREAD

**Issue by minac** [ansible/ansible-modules-core#4227]
##### ISSUE TYPE
- Documentation Report
##### COMPONENT NAME

ec2_elb_lb
##### ANSIBLE VERSION

ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
##### CONFIGURATION

$ env | grep ANSIBLE
ANSIBLE_HOST_KEY_CHECKING=false
##### OS / ENVIRONMENT

Mac OS X El Capitan
##### SUMMARY

The documentation states that listener is an optional item, when it seems it is not.
##### STEPS TO REPRODUCE

Using the following task:

```
- name: Create ELB for sender servers
  local_action:
    module: ec2_elb_lb
    name: "{{ elb_sender }}"
    state: present
    zones: "{{ availability_zones }}"
    tags:
      Name: "{{ elb_sender }}"
      type: "{{ type_sender }}"
      env: "{{ env }}"
    cross_az_load_balancing: "yes"
    security_group_names: "{{ security_group_sender }}"
    wait: yes
```
##### EXPECTED RESULTS

ELB created without listeners as per documentation
##### ACTUAL RESULTS

```
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "At least one port is required for ELB creation"}
```
