### ISSUE TITLE
os_floating_ip shouldn't required server parameter in some cases

### ISSUE THREAD

**Issue by winggundamth** [ansible/ansible-modules-core#4230]
##### ISSUE TYPE

Bug Report
##### COMPONENT NAME

os_floating_ip
##### ANSIBLE VERSION

N/A
##### SUMMARY

I have this use case http://blog.aaronorosen.com/?p=320 to Implementing High Availability Instances with Neutron using VRRP. This need to create fixed-ip and assign floating-ip to fixed-ip that just created with these command

``` bash
neutron port-create --fixed-ip ip_address=192.168.1.2 dev-network
neutron floatingip-create --port-id=$(neutron port-list --fixed-ips ip_address=192.168.1.2 --format value -c id) external-network
```

But when I use this task

``` yml
- os_floating_ip:
     state: present
     reuse: yes
     network: dev-network
     fixed_address: 192.168.1.2
```

I got this error

```
fatal: [haproxy-dev-1 -> 127.0.0.1]: FAILED! => {"changed": false, "failed": true, "msg": "missing required arguments: server"}
```

I succeed by using `neutron floatingip-create` command so it should accept assign floating without server parameter
