### ISSUE TITLE
docker_image module can't pull image from v2 private registry

### ISSUE THREAD

**Issue by Ehekatl** [ansible/ansible-modules-core#4235]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

docker_image
##### ANSIBLE VERSION

```
ansible --version
ansible 2.1.0.0
  config file = /etc/ansible_jp.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
[defaults]
inventory = jp
host_key_checking = False
retry_files_enabled = False
pipelining = True
log_path=/var/log/ansible.log

[ssh_connection]
sudo_flags=-HE
scp_if_ssh = True
control_path = ~/.ssh/mux-%%r@%%h:%%p
```
##### OS / ENVIRONMENT

AWS EC2 AMI
##### SUMMARY

docker_image module can't pull image from v2 private registry
##### STEPS TO REPRODUCE

```
  tasks:
    - name: Pull app image
      docker_image:
        name: "{{ docker_registry }}/{{ env }}/{{ app_name }}:{{ tag }}"
        state: present
```

This task will fail to pull from v2 registry with image not found error, but run docker pull it works.
Log from registry shows that this module using wrong entry point

```
11.0.5.226 - - [22/Jul/2016:02:51:19 +0000] "GET /v1/repositories/v2/test/bobcat/images HTTP/1.1" 404 19 "" "docker/1.11.1 go/go1.5.3 kernel/4.4.14-24.50.amzn1.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.1 \\(linux\\))"
```
##### EXPECTED RESULTS

Image pull should work on v2 registry
##### ACTUAL RESULTS

It still using v1 registry endpoint to pull image

**Comment by ansibot** [comment]
@ansible ping, this issue is waiting for your response.
[click here for bot help](https://github.com/jctanner/ansibullbot/blob/ISSUE_TRIAGE_CLASS/ISSUE_HELP.md)

**Comment by chouseknecht** [comment]
I have tested the following with `pip install ansible==2.1.0`, `pip install ansible==2.1.1.0` and running from source (ansible 2.2). I'm not experiencing any image pull errors.

My installed docker-py is version 1.9 and docker is version 1.11.2

Here's how I'm testing:

Running a local v2 registry, and the only local image is registry:v2:

```
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
c9ebf6ef3b7e        registry:2          "/entrypoint.sh /etc/"   26 minutes ago      Up 26 minutes       0.0.0.0:5000->5000/tcp   registry

$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
registry            2                   c6c14b3960bd        7 days ago          33.31 MB
```

Run the following playbook to pull an image from the local registry https://localhost:5000:

```
- name: Pull from registry v2
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:

    - name: Pull image
      docker_image:
        name: localhost:5000/myflask
        tag: latest

    - name: Start a container
      docker_container:
        name: myflask
        image: localhost:5000/myflask:latest
        command: sleep 600
```

And run the playbook:

```
$ ansible-playbook test2.yml

PLAY [Pull from registry v2] ***************************************************

TASK [Pull image] **************************************************************
changed: [localhost]

TASK [Start a container] *******************************************************
changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=2    unreachable=0    failed=0
```
