### ISSUE TITLE
win_feature source parameter escapes incorrectly

### ISSUE THREAD

**Issue by refinedcranberry** [ansible/ansible-modules-core#4250]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

win_feature
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

Ubuntu Xenial 64
##### SUMMARY

When using an UNC-Path for the Source-Parameter of the win_feature module escaping doesn't work correctly. Any other combination of escape characters doesn't work.
##### STEPS TO REPRODUCE

```

---
# tasks file for vx_dotnet35
- name: Ensure .NET 3.5 feature is present
  win_feature: name="NET-Framework-Features" state=present restart=true source='\\defrasadm01\windvd\sources\sxs'
```

##### EXPECTED RESULTS

Installation of Feature
##### ACTUAL RESULTS

```
fatal: [172.29.84.91]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "win_feature"}, "msg": "Failed to find source path \\\\defrasadm01\\windvd\\sources\\sxs"}
```

**Comment by jhawkesworth** [comment]
Its possible you are hitting the 'second hop' issue.  Unless you are using kerberos and have allowed delegation its possible that you can't use the defrasamd01 machine as winrm typically only allows one 'hop' - from the ansible controller to the machine where you are running win_feature module.

**Comment by refinedcranberry** [comment]
the error seems more to be related with ansible, which says it cant find the path. that makes sense because its completely wrong escaped

`$complex_args = @'
{"_ansible_version": "2.1.0.0", "_ansible_selinux_special_fs": ["fuse", "nfs", "vboxsf", "ramfs"], "_ansible_no_log": false, "_ansible_verbosity": 5, "_ansible_syslog_facility": "LOG_USER", "source": "\\defrasadm01\\windvd\\sources\\sxs", "state": "present", "_ansible_diff": false, "_ansible_debug": false, "_ansible_check_mode": false, "restart": "true", "name": "NET-Framework-Features"}
'@`

**Comment by jhawkesworth** [comment]
Something you could try is switching to using 'yaml-style' module parameters instead of the key=value style.  The yaml style is generally preferred after v2 

So try changing to

```
- name: Ensure .NET 3.5 feature is present
  win_feature: 
    name: "NET-Framework-Features"
    state: present
    restart: true
    source: '\\defrasadm01\windvd\sources\sxs'
```

If this still doesn't work, I worked around the issue in my playbooks by zipping the sources and copying them to the local machine before installing.  My role to do this is on slide 40 of my ansiblefest presentation here: http://www.slideshare.net/jhawkesworth/ansible-20-windows-and-no-powershell-this-year-i-promise-ansiblefest-london-2016

**Comment by refinedcranberry** [comment]
Unfortunately this didn't work.
Using the method you described in your ansiblefest presentation worked for me. Thank you!

Nevertheless the escaping bug should be fixed.

**Comment by ansibot** [comment]
@trondhindenes, ping. This issue is waiting on your response.
[click here for bot help](https://github.com/jctanner/ansibullbot/blob/ISSUE_TRIAGE_CLASS/ISSUE_HELP.md)

**Comment by trondhindenes** [comment]
I haven't done much testing with source. Will have a look at this during the weekend.

**Comment by trondhindenes** [comment]
Pretty sure this is related to second-hop/kerb and not related to win_feature itself. This works as expected:

```
---
- hosts: windows
  tasks:
    - name: install .NET framework
      win_feature:
        name: NET-Framework-Core
        state: present
        restart: yes
        include_sub_features: no
        include_management_tools: yes
        source: "c:/sources/sxs"
```

@mdorenkamp if it's okay with you I'll close this issue.
