### ISSUE TITLE
python-novaclient version issue

### ISSUE THREAD

**Issue by Navdeepuniyal** [ansible/ansible-modules-core#4265]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

nova_compute
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```
##### SUMMARY

while running ansible playbook with nova_compute module in order to deploy a VM, error occurs:
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "python-novaclient is required for this module"}

As per my triage issue seems to be from the _nova_compute.py line no. 25
"from novaclient.v1_1 import client as nova_client"
Using the same lines on python CLI do not fetch any result and throws following error:
ImportError: No module named v1_1

with "from novaclient.v2 import client as nova_client" it works, but I think it is not allowed to be used this way. 

I am not sure if it is exactly a bug but could not get any help regarding the same.
##### STEPS TO REPRODUCE

```
 nova_compute:
         state: present
         login_username: <login_name>
         login_password: <password>
         login_tenant_name: admin
         name: vm
         auth_url: URL
         region_name: 1
         image_id: <image_id>
         key_name: key-gen
         wait_for: 200
         flavor_id: 1
         auto_floating_ip: yes
         nics:
           - net-id: <id>
         meta:
           hostname: test
           group: test
```

##### ACTUAL RESULTS

```
PLAY [launch a nova instance] **************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [launch an instance] ******************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "python-novaclient is required for this module"}

NO MORE HOSTS LEFT *************************************************************
        to retry, use: --limit @upload-image.retry

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1

```
