### ISSUE TITLE
apt_repository with ppa fails on Linux Mint 18 (Sarah)

### ISSUE THREAD

**Issue by dharrigan** [ansible/ansible-modules-core#4282]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

apt_repository
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /home/david/foo/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
[defaults]
ansible_managed = Ansible managed: {file} on {host}
fact_caching = memory
forks = 50
host_key_checking = false
pattern = *
retry_files_enabled = false
var_compression_level = 6

[ssh_connection]
pipelining = True
ssh_args = -o ControlMaster=auto -o ControlPersist=60s -o ForwardAgent=yes
```
##### OS / ENVIRONMENT

```
Linux frodo 4.7.0 #1 SMP Tue Jul 26 08:50:06 BST 2016 x86_64 x86_64 x86_64 GNU/Linux
Linux Mint 18 Sarah 
```
##### SUMMARY

apt_repository fails on Linux Mint 18 when using repo with ppa:foo

This is mentioned here: https://github.com/ansible/ansible/issues/4587 however that ticket has been closed.
##### STEPS TO REPRODUCE

Create a simple main.yml containing this:

```
- name: default Linux configuration
  become: yes
  hosts: linux
  roles:
    - {role: apt, tags: ['apt']}
```

Create a simple roles/apt/tasks/main.yml, containing, for example this:

```
- name: add git ppa
  apt_repository: repo="{{ item }}" update_cache="yes"
  with_items:
    - ppa:git-core/ppa
```

Then run:

```
ansible-playbook -i inventory/linux/hosts.ini -t apt main.yml
```

##### EXPECTED RESULTS

Something similar to this:

```
ok: [foo] => (item=ppa:git-core/ppa)
```
##### ACTUAL RESULTS

```
failed: [foo] (item=ppa:git-core/ppa) => {"failed": true, "invocation": {"module_args": {"filename": null, "install_python_apt": true, "mode": "420", "repo": "ppa:git-core/ppa", "state": "present", "update_cache": true, "validate_certs": true}, "module_name": "apt_repository"}, "item": "ppa:git-core/ppa", "msg": "Invalid repository string: ppa:git-core/ppa"}
```

This does not happen on vanilla Debian or Ubuntu machines.
