### ISSUE TITLE
Select ip for interface on os_router module

### ISSUE THREAD

**Issue by ghost** [ansible/ansible-modules-core#4290]
##### ISSUE TYPE

- Feature Idea
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### SUMMARY

If the first ip of a subnet is alredy assigned, router is created but interfaces are not.
##### STEPS TO REPRODUCE

```
- name: Connect subnets using a router
  os_router:
    cloud: "{{ connection }}"
    state: present
    name: router_internal
    interfaces:
        - security_subnet
          ip: <<fixed ip address or next free ip if not selected>>
        - private_subnet
```

```
TASK [ansible-OpenstackSecurityNetwork : Connect subnets using a router] ***
fatal: [127.0.0.1 -> 127.0.0.1]: FAILED! => {"changed": false, "failed": true, "msg": "Error attaching interface to router 47ce1f62-19c4-4c02-8d88-51afce38a6a9: Unable to complete operation for network c8b362f5-fad4-4b15-9f1d-165f8e20c3bf. The IP address 22.0.0.1 is in use.\nNeutron server returns request_ids: ['req-5f955b8c-ce00-4dd6-8619-e1b21e71cfb7']"}
```

##### EXPECTED RESULTS

If no IP is selected, ansible should use the first free IP on the newtork.
If IP is selected, ansible should use it to create the interface, and fail if IP address is already in use.
##### ACTUAL RESULTS

Actually, only first IP of the network can be used to create the interface, if IP is in use, ansible module fails to create the interface

```

```
