### ISSUE TITLE
Feature request: allow iterating listeners with with_items inside ec2_elb_lb task

### ISSUE THREAD

**Issue by minac** [ansible/ansible-modules-core#4331]
ISSUE TYPE

Feature Idea
ANSIBLE VERSION

```
$ ansible --version
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
CONFIGURATION

$ egrep -v "^#|^$" /etc/ansible/ansible.cfg
[defaults]
gathering = explicit
host_key_checking = False
callback_whitelist = profile_tasks
remote_user = ec2-user
private_key_file = /Users/myuser/.ssh/mykey.pem
ansible_managed = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
display_skipped_hosts = False
command_warnings = True
retry_files_enabled = False
squash_actions = apk,apt,dnf,package,pacman,pkgng,yum,zypper
[privilege_escalation]
[paramiko_connection]
[ssh_connection]
[accelerate]
[selinux]
[colors]
Env vars:

export ANSIBLE_HOST_KEY_CHECKING='false'
export AWS_REGION='eu-central-1'
and the obvious AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY
```

OS / ENVIRONMENT

From Mac OS X Capitan to N/a (AWS)

SUMMARY

I need to create an elastic load balancer which listens on a lot of ports (i.e. 100+). I am aware that AWS ELBs do not allow for port ranges in their ELB module (just on security groups), so I would like to do something like this:

```
- name: Create ELB for sender servers
  local_action:
    module: ec2_elb_lb
    name: "{{ elb_sender }}"
    state: present
    zones: "{{ availability_zones }}"
    tags:
      Name: "{{ elb_sender }}"
    listeners:
      - protocol: tcp
        load_balancer_port: "{{ item }}"
        instance_port: "{{ item }}"
        proxy_protocol: True
    cross_az_load_balancing: "yes"
    security_group_names: "{{ security_group_sender }}"
    wait: yes
  with_items:
    - 80
    - 81
```

Which does not error out but only creates an ELB listening on the last port on the items list.

STEPS TO REPRODUCE

The new feature would be as above.

```
    - name: Create ELB for sender servers
      local_action:
        module: ec2_elb_lb
        name: "{{ elb_sender }}"
        state: present
        zones: "{{ availability_zones }}"
        tags:
          Name: "{{ elb_sender }}"
        listeners:
          - protocol: tcp
            load_balancer_port: "{{ item }}"
            instance_port: "{{ item }}"
            proxy_protocol: True
        cross_az_load_balancing: "yes"
        security_group_names: "{{ security_group_sender }}"
        wait: yes
      with_items:
        - 80
        - 81
```

EXPECTED RESULTS

I expected/hoped for a loop of the listeners part of the task.

ACTUAL RESULTS

An ELB with a listener on port 81.

Thanks for considering it.
