### ISSUE TITLE
docker_container module finishes execution before actual container execution is completed

### ISSUE THREAD

**Issue by orangefiredragon** [ansible/ansible-modules-core#4356]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

docker_container
##### ANSIBLE VERSION

```
ansible 2.1.1.0

```
##### OS / ENVIRONMENT

OSX -> Ubuntu 14
##### SUMMARY

docker_container module finishes execution before actual container is completed
##### STEPS TO REPRODUCE

```
- name: Run letsencrypt-data container
  docker_container:
    name: letsencrypt-data
    image: quay.io/letsencrypt/letsencrypt
    pull: true
    recreate: true
    state: started
    detach: false
    volumes:
    - /etc/letsencrypt
    - /var/lib/letsencrypt
    entrypoint:
    - "/bin/mkdir"
    - "/etc/letsencrypt/webrootauth/"

**- name: Run Diffie-Hellman container
  docker_container:
    name: diffie-hellman
    image: nginx
    recreate: true
    detach: false
    state: started
    interactive: true
    timeout: 600
    tty: true
    volumes_from:
    - letsencrypt-data
    entrypoint:
    - "openssl"
    - "dhparam"
    - "-out"
    - "/etc/letsencrypt/dhparams.pem"
    - "2048"**

```

##### EXPECTED RESULTS

Same as running:
- command: docker run --rm --interactive --volumes-from letsencrypt-data nginx openssl dhparam -out /etc/letsencrypt/dhparams.pem 2048
##### ACTUAL RESULTS

docker_container returns successfully before container completes execution.

```
TASK [web : Run Diffie-Hellman container] **************************************
changed: [162.243.171.156] => {"ansible_facts": {"ansible_docker_container": {"AppArmorProfile": "", "Args": ["dhparam", "-out", "/etc/letsencrypt/dhparams.pem", "2048"], "Config": {"AttachStderr": true, "AttachStdin": true, "AttachStdout": true, "Cmd": null, "Domainname": "", "Entrypoint": ["openssl", "dhparam", "-out", "/etc/letsencrypt/dhparams.pem", "2048"], "Env": ["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", "NGINX_VERSION=1.11.1-1~jessie"], "ExposedPorts": {"443/tcp": {}, "80/tcp": {}}, "Hostname": "27d4813fefbf", "Image": "nginx", "Labels": {}, "OnBuild": null, "OpenStdin": true, "StdinOnce": true, "Tty": true, "User": "", "Volumes": null, "WorkingDir": ""}, "Created": "2016-08-08T09:24:22.588923793Z", "Driver": "aufs", "ExecIDs": null, "GraphDriver": {"Data": null, "Name": "aufs"}, "HostConfig": {"AutoRemove": false, "Binds": [], "BlkioBps": 0, "BlkioDeviceReadBps": null, "BlkioDeviceReadIOps": null, "BlkioDeviceWriteBps": null, "BlkioDeviceWriteIOps": null, "BlkioIOps": 0, "BlkioWeight": 0, "BlkioWeightDevice": null, "CapAdd": null, "CapDrop": null, "Cgroup": "", "CgroupParent": "", "ConsoleSize": [0, 0], "ContainerIDFile": "", "CpuCount": 0, "CpuPercent": 0, "CpuPeriod": 0, "CpuQuota": 0, "CpuShares": 0, "CpusetCpus": "", "CpusetMems": "", "Devices": null, "DiskQuota": 0, "Dns": null, "DnsOptions": null, "DnsSearch": null, "ExtraHosts": null, "GroupAdd": null, "IpcMode": "", "Isolation": "", "KernelMemory": 0, "Links": null, "LogConfig": {"Config": {}, "Type": "json-file"}, "Memory": 0, "MemoryReservation": 0, "MemorySwap": 0, "MemorySwappiness": -1, "NetworkMode": "default", "OomKillDisable": false, "OomScoreAdj": 0, "PidMode": "", "PidsLimit": 0, "PortBindings": null, "Privileged": false, "PublishAllPorts": false, "ReadonlyRootfs": false, "RestartPolicy": {"MaximumRetryCount": 0, "Name": ""}, "SandboxSize": 0, "SecurityOpt": null, "ShmSize": 67108864, "StorageOpt": null, "UTSMode": "", "Ulimits": null, "UsernsMode": "", "VolumeDriver": "", "VolumesFrom": ["letsencrypt-data"]}, "HostnamePath": "/var/lib/docker/containers/27d4813fefbf7a2a049c37f51e89e47b2165ede5f5d91933b18b91b4cf74370b/hostname", "HostsPath": "/var/lib/docker/containers/27d4813fefbf7a2a049c37f51e89e47b2165ede5f5d91933b18b91b4cf74370b/hosts", "Id": "27d4813fefbf7a2a049c37f51e89e47b2165ede5f5d91933b18b91b4cf74370b", "Image": "sha256:0d409d33b27e47423b049f7f863faa08655a8c901749c2b25b93ca67d01a470d", "LogPath": "/var/lib/docker/containers/27d4813fefbf7a2a049c37f51e89e47b2165ede5f5d91933b18b91b4cf74370b/27d4813fefbf7a2a049c37f51e89e47b2165ede5f5d91933b18b91b4cf74370b-json.log", "MountLabel": "", "Mounts": [{"Destination": "/var/lib/letsencrypt", "Driver": "local", "Mode": "", "Name": "e18129d3d37e5f1b03ed2d091a87b3696064362380691012ac3ca62620a49b0c", "Propagation": "", "RW": true, "Source": "/var/lib/docker/volumes/e18129d3d37e5f1b03ed2d091a87b3696064362380691012ac3ca62620a49b0c/_data"}, {"Destination": "/etc/letsencrypt", "Driver": "local", "Mode": "", "Name": "83ba1f7a5ed54167dc0116e08885f42c3db346469fada875482b57833689fc1d", "Propagation": "", "RW": true, "Source": "/var/lib/docker/volumes/83ba1f7a5ed54167dc0116e08885f42c3db346469fada875482b57833689fc1d/_data"}], "Name": "/diffie-hellman", "NetworkSettings": {"Bridge": "", "EndpointID": "fb94a936a07fb414ee833668c659c4bc5350795e77697cc1f9d9aebed1b0fb5e", "Gateway": "172.17.0.1", "GlobalIPv6Address": "", "GlobalIPv6PrefixLen": 0, "HairpinMode": false, "IPAddress": "172.17.0.2", "IPPrefixLen": 16, "IPv6Gateway": "", "LinkLocalIPv6Address": "", "LinkLocalIPv6PrefixLen": 0, "MacAddress": "02:42:ac:11:00:02", "Networks": {"bridge": {"Aliases": null, "EndpointID": "fb94a936a07fb414ee833668c659c4bc5350795e77697cc1f9d9aebed1b0fb5e", "Gateway": "172.17.0.1", "GlobalIPv6Address": "", "GlobalIPv6PrefixLen": 0, "IPAMConfig": null, "IPAddress": "172.17.0.2", "IPPrefixLen": 16, "IPv6Gateway": "", "Links": null, "MacAddress": "02:42:ac:11:00:02", "NetworkID": "69591a0fd4af593395eb663aa086314183960cf1b10b3ad4b4df7cbbe0d43c3d"}}, "Ports": {"443/tcp": null, "80/tcp": null}, "SandboxID": "f8a24fd90b94138b47c3df76cc5d4cd2cbe90ea5861fcd98a8748421ec6118ec", "SandboxKey": "/var/run/docker/netns/f8a24fd90b94", "SecondaryIPAddresses": null, "SecondaryIPv6Addresses": null}, "Path": "openssl", "ProcessLabel": "", "ResolvConfPath": "/var/lib/docker/containers/27d4813fefbf7a2a049c37f51e89e47b2165ede5f5d91933b18b91b4cf74370b/resolv.conf", "RestartCount": 0, "State": {"Dead": false, "Error": "", "ExitCode": 0, "FinishedAt": "0001-01-01T00:00:00Z", "OOMKilled": false, "Paused": false, "Pid": 20038, "Restarting": false, "Running": true, "StartedAt": "2016-08-08T09:24:22.789100426Z", "Status": "running"}}}, "changed": true}
```
