### ISSUE TITLE
ios_config replace: block behaves like replace: line when there are no parents

### ISSUE THREAD

**Issue by Zanthras** [ansible/ansible-modules-core#4368]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

networking/ios_config
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

Fully default
##### OS / ENVIRONMENT

Ansible is running off a RHEL6.8 system
##### SUMMARY

IOS_config "replace: block" does not replace the block when there are no parents defined.
##### STEPS TO REPRODUCE

Existing config:
access-list 1 remark #### This line will be sent ####
access-list 1 remark ### This line wont be sent ###

```
  tasks:
  - name: Block replace failure
    ios_config:
      provider: "{{ provider }}"
      authorize: yes
      replace: block
      match: line
      lines:
        - "access-list 1 remark ### This line will be sent ###"
        - "access-list 1 remark ### This line wont be sent ###"
      before:
        - "no access-list 1"
```
##### EXPECTED RESULTS

access-list 1 remark ### This line will be sent ###
access-list 1 remark ### This line wont be sent ###
##### ACTUAL RESULTS

access-list 1 remark ### This line will be sent ###
