### ISSUE TITLE
IAM module not reliably deleting IAM roles

### ISSUE THREAD

**Issue by willusher** [ansible/ansible-modules-core#4399]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

IAM
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

The IAM module is not reliably deleting IAM roles, returning error: `BotoServerError: 409 Conflict`.
##### STEPS TO REPRODUCE

Deploy new IAM role.

``` yaml
- name: create IAM role
  iam:
    iam_type: role
    name: "{{ iam_role_name }}"
    state: present

- name: create inline IAM policy and attach to Role created above
  iam_policy:
    iam_type: role
    iam_name: "{{ iam_role_name }}"
    policy_name: "default-policy"
    policy_document: "{{ iam_role_policy_file }}"
    skip_duplicates: false
    state: present
```

Then attempt to delete it

``` yaml
- name: destroy inline IAM policy
  iam_policy:
    iam_type: role
    iam_name: "{{ iam_role_name }}"
    policy_name: "default-policy"
    state: absent

- name: destroy IAM role
  iam:
    iam_type: role
    name: "{{ iam_role_name }}"
    state: absent
```
##### EXPECTED RESULTS

IAM role is deleted
##### ACTUAL RESULTS

```
BotoServerError: 409 Conflict
```
