### ISSUE TITLE
win_get_url : Exception calling \"DownloadFile\" with \"2\" argument(s): \"The underlying connection was closed: An unexpected error occurred on a send.\

### ISSUE THREAD

**Issue by arunjohn** [ansible/ansible-modules-core#4437]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

win_get_url 
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### SUMMARY

Unable to download a file from a url using basic authentication to a windows box.
and getting the error:

Exception calling \"DownloadFile\" with \"2\" argument(s): \"The underlying connection was closed: An unexpected error occurred on a send.\
##### STEPS TO REPRODUCE

```
    - name: Copying  files from artifactory
      win_get_url:
         url: 'https://xxxxxx.com/package.zip'
         dest: 'd:\\temp\\package.zip'
         username: 'username'
         password: 'password'

```

##### ACTUAL RESULTS

```

```
