### ISSUE TITLE
ec2_asg doesn't reflect load balancer changes to existing asgs

### ISSUE THREAD

**Issue by jbrockett** [ansible/ansible-modules-core#4460]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

ec2_asg
##### ANSIBLE VERSION

```
ansible 2.0.2.0
  config file = ~/code/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
[defaults]
ansible_managed = Ansible Managed
display_skipped_hosts = False
forks = 50
gathering = explicit
host_key_checking = False
nocows = 1
retry_files_enabled = False
lookup_plugins = ./lookup_plugins
```
##### OS / ENVIRONMENT

From: OS X El Capitan
Managing: AWS
##### SUMMARY

I am using the ec2_asg module to create an auto-scaling group for my application.  When first created, it had one ELB.  I had to add another ELB after it was created, but it would never update the ASG with the second ELB.  If I create a new asg with 2 ELBs, it works as expected.  
##### STEPS TO REPRODUCE

Use the ec2_asg module to create an ASG with 1 ELB like this:

```
- name: create auto scaling group
  ec2_asg:
    wait_for_instances: false
    name: "test-asg"
    desired_capacity: "{{ asg_desired_capacity }}"
    health_check_period: 600
    health_check_type: EC2
    launch_config_name: "test-lc"
    load_balancers: "{{ ext_elb.elb.name }}"
    min_size: "{{ asg_min_size }}"
    max_size: "{{ asg_max_size }}"
    region: "{{ ec2_region }}"
    state: present
    vpc_zone_identifier: "{{ lookup('tier_subnets', 'vpc_id=' + vpc_id + ' tier=dmz1') }}"
    tags:
      - Name: "test-asg"
      - environment: "{{ ec2_env }}"
```

After the ASG is created, attempt to add another ELB:

```
- name: create auto scaling group
  ec2_asg:
    wait_for_instances: false
    name: "test-asg"
    desired_capacity: "{{ asg_desired_capacity }}"
    health_check_period: 600
    health_check_type: EC2
    launch_config_name: "test-lc"
    load_balancers: "{{ ext_elb.elb.name }},{{ int_elb.elb.name }}"
    min_size: "{{ asg_min_size }}"
    max_size: "{{ asg_max_size }}"
    region: "{{ ec2_region }}"
    state: present
    vpc_zone_identifier: "{{ lookup('tier_subnets', 'vpc_id=' + vpc_id + ' tier=dmz1') }}"
    tags:
      - Name: "test-asg"
      - environment: "{{ ec2_env }}"
```
##### EXPECTED RESULTS

I would expect the ASG to be updated to use 2 ELBs instead of just one.  I do not get any errors when running this.
##### ACTUAL RESULTS

The play runs without issue, but the ASG is not updated to use 2 ELBs.  If I run the exact same play and create a new ASG, both ELBs are present.  This only appears to be an issue with updating an existing ASG.
