### ISSUE TITLE
Unarchive Error, No such file or directory

### ISSUE THREAD

**Issue by linusgg** [ansible/ansible-modules-core#4471]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

unarchive
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 3c65c03a67) last updated 2016/08/15 16:01:24 (GMT +1000)
  lib/ansible/modules/core: (detached HEAD decb2ec9fa) last updated 2016/08/15 16:01:29 (GMT +1000)
  lib/ansible/modules/extras: (detached HEAD 61d5fe148c) last updated 2016/08/15 16:01:29 (GMT +1000)
  config file = /home/linus/Documents/ansible-playbooks/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

Ubuntu  management node
Centos 7 managed node
##### SUMMARY

Gives No such file or directory error when added extra_opts: "--strip-components=2"
##### STEPS TO REPRODUCE

```
- name: unpack the artifacts
  unarchive:
    src: /usr/share/stuff.tar.gz
    dest: /usr/share/
    extra_opts: "--strip-components=2"
    owner: nginx
    group: nginx
    copy: no

```

##### EXPECTED RESULTS

Changed
##### ACTUAL RESULTS

The archive file structure is:
dist/production/files
I wan to strip the first two directories

```
fatal: [52.65.150.148]: FAILED! => {"changed": true, "dest": "/usr/share/", "extract_results": {"cmd": "/bin/gtar -C \"/usr/share/\" -xz --strip-components=2 --owner=\"nginx\" --group=\"nginx\" -f \"/usr/share/stuff.tar.gz\"", "err": "", "out": "", "rc": 0}, "failed": true, "gid": 992, "group": "nginx", "handler": "TgzArchive", "mode": "02775", "msg": "Unexpected error when accessing exploded file: [Errno 2] No such file or directory: '/usr/share/stuff/dist/production/'", "owner": "bitbucket", "size": 4096, "src": "/usr/share/stuff.tar.gz", "state": "directory", "uid": 1003}
```
