### ISSUE TITLE
Ansible "fail" module is probably broken in case of using Ansible's tags

### ISSUE THREAD

**Issue by sHaggYcaT** [ansible/ansible-modules-core#4489]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

Ansible fail
##### ANSIBLE VERSION

Ansible 2.1.1, partly 1.9.6 affected too.
##### OS / ENVIRONMENT

Ubuntu 14.04
##### STEPS TO REPRODUCE

==== Old Ansible code ====

```
    - fail: "custom message. It failed1!!"
      when: supervisord_disable_code == '2'
      tags:
       - always
        - bootstrap


    - fail: "custom message. It failed2!!"
      when: supervisord_disable_code == '1'
      tags:
       - always
        - bootstrap
```

=== pip install ansible==1.9.6, It works! ===

```
TASK: [django_init | fail custom message. It failed1!!] ***********************
skipping: [docker]

TASK: [django_init | fail custom message. It failed2!!] ***********************
<docker> ESTABLISH CONNECTION FOR USER: root
failed: [docker] => {"failed": true}
msg: Failed as requested from task

FATAL: all hosts have already failed -- aborting

```

=== pip install ansible==2.1.1 This syntax doesn't works! ===

```
ERROR! this task 'fail' has extra params, which is only allowed in the following modules: command, shell, script, include, include_vars, add_host, group_by, set_fact, raw, meta

The error appears to have been in '/home/shaggycat/cl.b.ans2/***/*yml': line 28, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    - fail: "custom message. It failed1!!"
      ^ here


The error appears to have been in '/home/shaggycat/cl.b.ans2/***/**.yml': line 28, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    - fail: "custom message. It failed1!!"
      ^ here

```

=== Try to write new syntax===

```

    - name: "test | Test/debug"
      debug: msg="supervisord_disable_code={{ supervisord_disable_code  }}"
      tags:
      - always
       - bootstrap


    - name: "test_fail| test fail, it have to not Fail! "
      fail:
        when: supervisord_disable_code == '2'
        msg: 'custom message. It failed1!!'
      tags:
       - always
        - bootstrap


    - name: "test_fail| test fail, it have to Fail! "
      fail:
        when: supervisord_disable_code == '1'
        msg: 'custom message. It failed2!!'
      tags:
       - always
        - bootstrap

```

=== It doesn't works anyway (1.9.6 and 2.1.1 versions doesn't support this syntax, and fail in all cases!)

```



TASK: [django_init | test | Test/debug] ***************************************
<docker> ESTABLISH CONNECTION FOR USER: root
ok: [docker] => {
    "msg": "supervisord_disable_code=1"
}

TASK: [django_init | test_fail| test fail, it have to not Fail! ] *************
<docker> ESTABLISH CONNECTION FOR USER: root
failed: [docker] => {"failed": true}
msg: custom message. It failed1!!

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/home/shaggycat/appservers.retry

docker                     : ok=3    changed=0    unreachable=0    failed=1

```
##### EXPECTED RESULTS

I expected, Ansible have to check conditionals before make failed. But it fact it doesn't works, and Ansible failed anyway!

**Comment by ansibot** [comment]
@dagwieers ping, this issue is waiting for your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by dagwieers** [comment]
I see more than one issue with your examples.
- You _need_ to add `msg=` or `msg:` when using the fail module (in some examples you didn't)
- Your `when:` statement needs to be defined on the task-level, not as an option to the fail module (in some examples it's done wrong)
- Some examples do not use the proper indentation (e.g. list items with different indentation will not work and lead to syntax errors)

So I am afraid that this has nothing to do with the fail module whatsoever, but errors in your example.
I have rewritten your examples and fixed the errors and all examples work correctly.

Example1:

``` yaml
- hosts: localhost
  gather_facts: no
  vars:
    supervisord_disable_code: '1'                                                         
  tasks:
    - fail: msg="custom message. It failed1!!"
      when: supervisord_disable_code == '2'
      tags:
       - always
        - bootstrap


    - fail: msg="custom message. It failed2!!"
      when: supervisord_disable_code == '1'
      tags:
       - always
        - bootstrap
```

Gives:

```
[dag@moria ansible.testing]$ ansible-playbook -vv test114.yml
Using /home/dag/home-made/ansible.testing/ansible.cfg as config file

PLAYBOOK: test114.yml **********************************************************
1 plays in test114.yml

PLAY [localhost] ***************************************************************

TASK [fail] ********************************************************************
task path: /home/dag/home-made/ansible.testing/test114.yml:6
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}

TASK [fail] ********************************************************************
task path: /home/dag/home-made/ansible.testing/test114.yml:13
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "custom message. It failed2!!"}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1   
```

Example2:

``` yaml
- hosts: localhost
  gather_facts: no
  vars:                                                                                                      
    supervisord_disable_code: '1'
  tasks:
    - name: "test | Test/debug"
      debug:
        msg: supervisord_disable_code={{ supervisord_disable_code  }}
      tags:
      - always
      - bootstrap


    - name: "test_fail| test fail, it have to not Fail! "
      fail:
        msg: 'custom message. It failed1!!'
      when: supervisord_disable_code == '2'
      tags:
      - always
      - bootstrap


    - name: "test_fail| test fail, it have to Fail! "
      fail:
        msg: 'custom message. It failed2!!'
      when: supervisord_disable_code == '1'
      tags:
      - always
      - bootstrap
```

Gives:

```
[dag@moria ansible.testing]$ ansible-playbook -vv test115.yml
Using /home/dag/home-made/ansible.testing/ansible.cfg as config file

PLAYBOOK: test115.yml **********************************************************
1 plays in test115.yml

PLAY [localhost] ***************************************************************

TASK [test | Test/debug] *******************************************************
task path: /home/dag/home-made/ansible.testing/test115.yml:6
ok: [localhost] => {
    "msg": "supervisord_disable_code=1"
}

TASK [test_fail| test fail, it have to not Fail!] ******************************
task path: /home/dag/home-made/ansible.testing/test115.yml:14
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}

TASK [test_fail| test fail, it have to Fail!] **********************************
task path: /home/dag/home-made/ansible.testing/test115.yml:23
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "custom message. It failed2!!"}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1   
```

So everything works as expected.

notabug
