### ISSUE TITLE
rds module sets Postgres to listen on port 3306 if not specified

### ISSUE THREAD

**Issue by danvaida** [ansible/ansible-modules-core#452]
##### Issue Type:

Bug Report
##### Ansible Version:

``` bash
[dvaida@scat Atlassian-Stash-Ansible]$ ansible --version
ansible 1.9 (devel ef9cb19976) last updated 2014/12/02 17:29:39 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 63e81cfc2e) last updated 2014/10/30 15:43:29 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD a0df36c6ab) last updated 2014/10/30 15:43:35 (GMT +200)
  v2/ansible/modules/core: (detached HEAD cb69744bce) last updated 2014/10/30 15:43:42 (GMT +200)
  v2/ansible/modules/extras: (detached HEAD 8a4f07eecd) last updated 2014/10/30 15:43:54 (GMT +200)
  configured module search path = None
[dvaida@scat Atlassian-Stash-Ansible]$
```
##### Environment:

FC19
##### Summary:

When the 'port' parameter is not specified, the rds module creates the Postgres instance listening on port 3306 (MySQL).
If the 'port' is set in the playbook to '5432', the DB instance is created correctly.
##### Steps To Reproduce:

```
- name: adding the RDS instance
    local_action:
      module: rds
      backup_retention: 14
      backup_window: 03:00-04:00
      command: create
      db_engine: postgres
      db_name: "{{ db_name }}" 
      engine_version: 9.3.5
      instance_name: "{{ db_instance_name }}"
      instance_type: db.t2.small
      maint_window: Sat:02:00-Sat:03:00
      size: 5
      subnet: "{{ db_subnet }}" 
      vpc_security_groups: "{{ private_postgres_sg_creation.group_id }}"
      username: "{{ db_master_username }}"
      password: "{{ db_master_password }}"
      region: "{{ region }}" 
      wait: yes
      wait_timeout: 1800
    register: rds_instance
```
##### Expected Results:

DB instance gets created and listens on correct port.
##### Actual Results:

Postgres RDS DB listens on port 3306.
