### ISSUE TITLE
[ecs_service_facts] value of details must be one of: true,false, got: True

### ISSUE THREAD

**Issue by rafi** [ansible/ansible-modules-core#4537]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

`ecs_service_facts`
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /srv/code/ops/ansible/ansible.cfg
  configured module search path = ['./library']
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

OSX
##### SUMMARY

Running this playbook (with `details: true`):

```
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - ecs_service_facts:
        region: "us-west-1"
        cluster: "my-cluster"
        service: "my-service"
        details: true
```
##### EXPECTED RESULTS

Detailed result as mentioned in [docs](http://docs.ansible.com/ansible/ecs_service_facts_module.html).
##### ACTUAL RESULTS

```
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"cluster": "mtdev-microservices-cluster", "details": "True", "region": "us-west-2", "service": "mtdev-threat-service", "validate_certs": true}, "module_name": "ecs_service_facts"}, "msg": "value of details must be one of: true,false, got: True"}
```
