### ISSUE TITLE
os_user to not force updating password on existing users

### ISSUE THREAD

**Issue by ggillies** [ansible/ansible-modules-core#4546]
##### ISSUE TYPE

- Feature Idea
##### COMPONENT NAME

os_user
##### ANSIBLE VERSION

```
ansible 2.1.1.0
```
##### OS / ENVIRONMENT

Fedora 24, ansible installed from pip, ansible.cfg as follows

```
[defaults]
host_key_checking = False
remote_user = root
hostfile = ./inventory
roles_path = ./roles
remote_tmp = /tmp
command_warnings = True
ansible_managed = "This file is managed by Ansible - changes may be lost"
retry_files_enabled = False

[ssh_connection]
# pipelining = True
control_path = %(directory)s/ssh-%%h-%%p-%%r
```
##### SUMMARY

When using the os_user module, you need to specify the password attribute for users you wish to create when they are brand new users, and also if the users exist. This can cause workflow issues as, if I wish to use an ansible playbook to boostrap/configure users in my Openstack environment (and update the playbook as new users come online), I no longer wish for my ansible playbook to change the password of the users that exist (as they have already changed their password to something they know)
##### STEPS TO REPRODUCE

Consider a playbook with the following

```

---
- hosts: localhost
  vars:
    cloud: cloud
    users:
      - name: ggillies
        email: ggillies@redhat.com
      - name: testuser1
        email: testuser@test.com
    projects:
      - name: ggillies
        description: ggillies
        members:
          - ggillies
      - name: test
        description: test
        members:
          - ggillies
          - testuser1
  tasks:
    - name: create openstack projects
      os_project: name={{ item.name }} description={{ item.description }} cloud={{ cloud }}
      with_items: "{{ projects }}"

    - name: create openstack users
      os_user: name={{ item.name }} email={{ item.email }} cloud={{ cloud }}
      with_items: "{{ users }}"
      register: new_users

    - name: set password for new users
      os_user: name={{ item.name }} password='CHANGEME' email={{ item.email }} cloud={{ cloud }}
      with_items: "{{ users }}"
      when: new_users.changed

    - name: assign users to projects
      os_user_role: user={{ item.1 }} project={{ item.0.name }} role='_member_' cloud={{ cloud }}
      with_subelements:
        - "{{ projects }}"
        - members

```

At the moment I always have to specify a password, when what I would like to be able to do is not include the password for users that already exist, so that way I can run the playbook once to setup the users, tell them to change the password, then add new users and keep running the playbook, and have it not revert the password for users that already exist.

##### EXPECTED RESULTS

Have new users created with their password set to 'CHANGEME', while existing users are left alone
##### ACTUAL RESULTS

The playbook fails because I have an os_user task with state present, but the password field is not set (because I do not wish to modify it)

```
failed: [localhost] (item={u'name': u'ggillies', u'email': u'ggillies@redhat.com'}) => {"failed": true, "item": {"email": "ggillies@redhat.com", "name": "ggillies"}, "msg": "state is present but the following are missing: password"}
failed: [localhost] (item={u'name': u'testuser1', u'email': u'testuser@test.com'}) => {"failed": true, "item": {"email": "testuser@test.com", "name": "testuser1"}, "msg": "state is present but the following are missing: password"}
```
