### ISSUE TITLE
unarchive in 2.2 fails to unarchive a zip file

### ISSUE THREAD

**Issue by mgedmin** [ansible/ansible-modules-core#4554]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

unarchive

```
ansible 2.2.0 (devel 6f678e36d6) last updated 2016/08/23 09:52:36 (GMT +300)
  lib/ansible/modules/core: (devel 91a839f1e3) last updated 2016/08/18 20:46:51 (GMT +300)
  lib/ansible/modules/extras: (detached HEAD 1aeb9f8a8c) last updated 2016/08/23 09:03:03 (GMT +300)
  config file = /home/mg/src/deployments/provisioning/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

nothing pertinent
##### OS / ENVIRONMENT

Ubuntu 16.04 controller, Ubuntu 14.04 target
##### SUMMARY

The unarchive module in current git devel fails to extract a zip file.  This is a regression: the same playbook works fine with Ansible 2.1.1.0.

The playbook is

```
# variables:
# logicaldoc_version: "7.3"
# logicaldoc_installer_url: "http://netcologne.dl.sourceforge.net/project/logicaldoc/distribution/LogicalDOC%20CE%207.3/logicaldoc-community-installer-7.3.zip"
# logicaldoc_installer_sha256sum: "c0379767b80b225468c068615fc21573405aac9687c3fb5526c71373c827eb3b"
# logicaldoc_installer_jar: "logicaldoc-community-installer-7.3/logicaldoc-installer.jar"

- name: download logicaldoc installer
  get_url: dest=/tmp/logicaldoc-installer-{{ logicaldoc_version }}.zip url={{ logicaldoc_installer_url }} sha256sum={{ logicaldoc_installer_sha256sum }}

- name: create a directory for the installer
  file: dest=/tmp/logicaldoc-installer-{{ logicaldoc_version }} owner=logicaldoc state=directory

- name: extract logicaldoc installer
  unarchive: dest=/tmp/logicaldoc-installer-{{ logicaldoc_version }} src=/tmp/logicaldoc-installer-{{ logicaldoc_version }}.zip copy=no creates=/tmp/logicaldoc-installer-{{ logicaldoc_version }}/{{ logicaldoc_installer_jar }} owner=logicaldoc
```

The error given is

```
fatal: [trusty]: FAILED! => {"changed": true, "dest": "/tmp/logicaldoc-installer-7.3", "extract_results": {"cmd": "/usr/bin/unzip -o \"/tmp/logicaldoc-installer-7.3.zip\" \"logicaldoc-community-installer-7.3/\" -d \"/tmp/logicaldoc-installer-7.3\"", "err": "", "out": "Archive:  /tmp/logicaldoc-installer-7.3.zip\n", "rc": 0}, "failed": true, "gid": 0, "group": "root", "handler": "ZipArchive", "mode": "0755", "msg": "Unexpected error when accessing exploded file: [Errno 2] No such file or directory: '/tmp/logicaldoc-installer-7.3/logicaldoc-community-installer-7.3/CHANGELOG.txt'", "owner": "logicaldoc", "size": 4096, "src": "/tmp/logicaldoc-installer-7.3.zip", "stat": {"exists": false}, "state": "directory", "uid": 995}
```

The directory structure after the failure looks like this:

```
root@vagrant-ubuntu-trusty-64:/tmp# tree /tmp/logicaldoc-installer-7.3
/tmp/logicaldoc-installer-7.3
└── logicaldoc-community-installer-7.3
    └── INSTALL.txt
```

i.e. one of the files is successfully extracted, but none of the rest.
##### STEPS TO REPRODUCE

Run a playbook like mine -- the logicaldoc installer zip is publically accessible at the URL given.

``` yml
# test.yml

---
- hosts: localhost
  gather_facts: no
  tasks:
    - get_url: dest=/tmp/logicaldoc-installer-7.3.zip url=http://netcologne.dl.sourceforge.net/project/logicaldoc/distribution/LogicalDOC%20CE%207.3/logicaldoc-community-installer-7.3.zip
    - file: dest=/tmp/logicaldoc-installer-7.3 state=directory
    - unarchive: dest=/tmp/logicaldoc-installer-7.3 src=/tmp/logicaldoc-installer-7.3.zip copy=no
    - stat: path=/tmp/logicaldoc-installer-7.3/logicaldoc-community-installer-7.3/logicaldoc-installer.jar
      register: result
    - assert: that=result.stat.exists
```

`ansible-playbook -i localhost, -c local test.yml`

##### EXPECTED RESULTS

No error
##### ACTUAL RESULTS

```
...
fatal: [trusty]: FAILED! => {
    "changed": true, 
    "dest": "/tmp/logicaldoc-installer-7.3", 
    "diff": {
        "prepared": ".d....o..?? logicaldoc-community-installer-7.3/\n"
    }, 
    "extract_results": {
        "cmd": "/usr/bin/unzip -o \"/tmp/logicaldoc-installer-7.3.zip\" \"logicaldoc-community-installer-7.3/\" -d \"/tmp/logicaldoc-installer-7.3\"", 
        "err": "", 
        "out": "Archive:  /tmp/logicaldoc-installer-7.3.zip\n", 
        "rc": 0
    }, 
    "failed": true, 
    "gid": 0, 
    "group": "root", 
    "handler": "ZipArchive", 
    "invocation": {
        "module_args": {
            "backup": null, 
            "content": null, 
            "copy": false, 
            "creates": "/tmp/logicaldoc-installer-7.3/logicaldoc-community-installer-7.3/logicaldoc-installer.jar", 
            "delimiter": null, 
            "dest": "/tmp/logicaldoc-installer-7.3", 
            "directory_mode": null, 
            "exclude": [], 
            "extra_opts": [], 
            "follow": false, 
            "force": null, 
            "group": null, 
            "keep_newer": false, 
            "list_files": false, 
            "mode": null, 
            "original_basename": "logicaldoc-installer-7.3.zip", 
            "owner": "logicaldoc", 
            "regexp": null, 
            "remote_src": false, 
            "selevel": null, 
            "serole": null, 
            "setype": null, 
            "seuser": null, 
            "src": "/tmp/logicaldoc-installer-7.3.zip", 
            "unsafe_writes": null, 
            "validate_certs": true
        }
    }, 
    "mode": "0755", 
    "msg": "Unexpected error when accessing exploded file: [Errno 2] No such file or directory: '/tmp/logicaldoc-installer-7.3/logicaldoc-community-installer-7.3/CHANGELOG.txt'", 
    "owner": "logicaldoc", 
    "size": 4096, 
    "src": "/tmp/logicaldoc-installer-7.3.zip", 
    "stat": {
        "exists": false
    }, 
    "state": "directory", 
    "uid": 995
}
```
