### ISSUE TITLE
docker_container not preserving case for boolean environmental variables

### ISSUE THREAD

**Issue by JacobHenner** [ansible/ansible-modules-core#4587]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

docker_container
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

Default configuration is being used.
##### OS / ENVIRONMENT

Running on Arch Linux, managing Ubuntu
##### SUMMARY

When passing an environmental variable to docker using docker_container, a key with a value of _true_ will be passed to Docker as _True_ instead of _true_. Placing _true_ in quotes fixes this issue.
##### STEPS TO REPRODUCE

```
- name: Restart gitlab
  docker_container:
    name: gitlab
    image: sameersbn/gitlab
    state: started
    recreate: yes
    pull: true
    ports:
      - "443:443"
      - "80:80"
      - "22:22"
    links:
      - "redis:redisio"
      - "postgresql:postgresql"
    env:
      GITLAB_HTTPS: "true" # Works properly
      GITLAB_HTTPS: true # Passes True to Docker instead of true
```

##### EXPECTED RESULTS

The GITLAB_HTTPS variable should be set to _true_
##### ACTUAL RESULTS

The GITLAB_HTTPS variable is set to _True_, breaking the container's configuration. 

```

```
