### ISSUE TITLE
docker_service: Failed to cast value to int in scale parameter while using variable

### ISSUE THREAD

**Issue by jaydg** [ansible/ansible-modules-core#4592]
Partially copied from https://github.com/ansible/ansible/issues/17017
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

docker_service
##### ANSIBLE VERSION

```
ansible 2.1.1.0
```
##### CONFIGURATION

No special configuration required
##### SUMMARY

Throws `unsupported operand type(s) for -: 'str' and 'int'"` while using variable in docker_service scale parameter even if variable is casted to int like `{{ num_procs | int }}`
##### STEPS TO REPRODUCE

Play:

```
- hosts: all
  roles:
  - role: test

```

Role:

```

---
- set_fact: num_instances=3

- docker_service:
    project_name: webserver
    scale:
        nginx: "{{ num_instances }}"
    definition:
        version: "2"
        services:
            nginx:
                image: nginx

```
##### EXPECTED RESULTS

Three running nginx containers.
##### ACTUAL RESULTS

`Error scaling web - unsupported operand type(s) for -: 'str' and 'int'"`
