### ISSUE TITLE
replace.py is failing with an UnboundLocalError

### ISSUE THREAD

**Issue by jgrigonis** [ansible/ansible-modules-core#4634]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

replace
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel d99c58ee55) last updated 2016/09/01 10:10:05 (GMT -700)
  lib/ansible/modules/core: (detached HEAD 7e79c59d38) last updated 2016/09/01 10:10:05 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD e8a5442345) last updated 2016/09/01 10:10:05 (GMT -700)
  config file = /Users/jgrigonis/projects/omicia_ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

OS X controller
centos 6 target
##### SUMMARY

Seems like a bad commit
5728ef89f0764be9066fc1bf0fbbf7785e60f4cb
##### STEPS TO REPRODUCE

```
- name: fix ctypes file
  replace:
    dest: '/usr/local/lib/python2.7/ctypes/__init__.py'
    regexp: '^(    CFUNCTYPE.c_int..lambda: None.)'
    replace: '    # CFUNCTYPE(c_int)(lambda: None)'
  when: init.stat.exists == True
```
##### EXPECTED RESULTS

Do a replacement
##### ACTUAL RESULTS

```
{"changed": false, "failed": true, "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_Kl6JDv/ansible_module_replace.py\", line 179, in <module>\r\n    main()\r\n  File \"/tmp/ansible_Kl6JDv/ansible_module_replace.py\", line 173, in main\r\n    module.exit_json(changed=changed, msg=msg, diff=diff)\r\nUnboundLocalError: local variable 'diff' referenced before assignment\r\n", "msg": "MODULE FAILURE"}
```
