### ISSUE TITLE
Log output for git module does not redact all password references

### ISSUE THREAD

**Issue by jamesmarshall24** [ansible/ansible-modules-core#4668]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

Git module
http://docs.ansible.com/ansible/git_module.html
##### ANSIBLE VERSION

```
[WARNING]: log file at /var/log/ansible.log is not writeable and we cannot create it, aborting

ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

Everything default except:
log_path = /var/log/ansible.log

/var/log/ansible.log owned by awx:awx, but this condition is not necessary
##### OS / ENVIRONMENT

CentOS 7, but not platform specific
##### SUMMARY

Passwords passed through the git module should be redacted within standard output which occurs in two locations of the log, but is ignored later in the same log entry.
##### STEPS TO REPRODUCE

1. Create an ansible playbook where the repo URL forces an HTTP error (simply input % at the end of the git repository URL or input localhost)
2. Run the play:
   ansible-playbook -i hosts testingGit.yml

```

---
- hosts: all
  connection: local
  gather_facts: false
  tasks:
    - name: update project using git
      git: dest=/destination/path repo=https://testuser:testpassword@localhost version=master force=no
```

##### EXPECTED RESULTS

All references of the github repo redacts testpassword
##### ACTUAL RESULTS

Only 2 out of 3 references to testpassword are redacted

```
TASK [update project using git] ************************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "/usr/bin/git ls-remote 'https://testuser:********@localhost' -h refs/heads/master", "failed": true, "msg": "fatal: unable to access 'https://testuser:********@localhost/': Peer's certificate issuer has been marked as not trusted by the user.", "rc": 128, "stderr": "fatal: unable to access 'https://testuser:testpassword@localhost/': Peer's certificate issuer has been marked as not trusted by the user.\n", "stdout": "", "stdout_lines": []}
```
