### ISSUE TITLE
os_security_group_rule does not implement delete/remove actions

### ISSUE THREAD

**Issue by logronoide** [ansible/ansible-modules-core#4720]
##### ISSUE TYPE
- Feature Idea
##### COMPONENT NAME

os_security_group_rule
##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.1.0.0
  config file = 
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

I want to implement a cleanup process that removes some specific security group rules. Reading and reviewing the code I cannot see how to remove the security group rule once I have the uuid with the security rule ID. The documentation says it's possible to add/delete a rule but the fact is that only rule creation is described in the docs here: http://docs.ansible.com/ansible/os_security_group_rule_module.html
##### STEPS TO REPRODUCE

I have an already created security group called 'redis'. I can add a new rule successfully as follows, to allow connection to my redis instance from a specific IP.

```
- name: Open security group to the new IP of the VM
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Create security group rule for REDIS
    os_security_group_rule:
      auth:
        auth_url: https://OS_API/v2.0/
        username: USERNAME
        password: "{{os_password}}"
        project_name: TENANT_NAME
      security_group: redis
      protocol: tcp
      port_range_min: 1234
      port_range_max: 1234
      remote_ip_prefix: "{{ public_ip }}/32"
```

Now, I cannot find the way to remove/delete this rule.
##### EXPECTED RESULTS

All create actions should have a delete/remove as a rule of thumb. I can't find a valid delete/remove action.
##### ACTUAL RESULTS

Rule is created successfully, but I have to delete the security group rule using the OpenStack API directly.
