### ISSUE TITLE
os_image module does not delete image

### ISSUE THREAD

**Issue by eleonora-ciceri** [ansible/ansible-modules-core#4722]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

os_image
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = 
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

None.
##### OS / ENVIRONMENT

OSX 10.11.13
##### SUMMARY

When trying to use Ansible to delete an OpenStack image, an error saying "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER" for auth values is specified.
##### STEPS TO REPRODUCE

```

---
- name: Delete the image.
  hosts: localhost

  tasks:
     - name: Delete the old OpenStack image version
       os_image:
         auth:
           auth_url: http://my_openstack_server:5000/v3
           password: mypassword
           project_name: myproject
           username: admin
         name: CoreOS-certified-Docker
         state: absent
```

##### EXPECTED RESULTS

At least, a connection to OpenStack
##### ACTUAL RESULTS

The following error is displayed:

```
fatal: [localhost]: FAILED! => {"changed": false, "extra_data": null, "failed": true, "invocation": {"module_args": {"api_timeout": null, "auth": {"auth_url": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "project_name": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"}, "auth_type": null, "availability_zone": null, "cacert": null, "cert": null, "cloud": null, "container_format": "bare", "disk_format": "qcow2", "endpoint_type": "public", "filename": null, "is_public": false, "kernel": null, "key": null, "min_disk": 0, "min_ram": 0, "name": "CoreOS-certified-Docker", "owner": null, "properties": {}, "ramdisk": null, "region_name": null, "state": "absent", "timeout": 180, "verify": true, "wait": true}, "module_name": "os_image"}, "msg": "Error fetching image list: Could not determine a suitable URL for the plugin"}
```
