### ISSUE TITLE
docker_image module doesn't work with local registry

### ISSUE THREAD

**Issue by gcontiu** [ansible/ansible-modules-core#4791]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

docker_image
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### OS / ENVIRONMENT

Ubuntu 16.04 LTS
##### SUMMARY

I installed my own local registry on localhost 5000:

```
docker run -d -p 5000:5000 --restart=always registry:2
```

 and when triggering the docker_image module I get:

```
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error: configuration for localhost:5000 not found. Try logging into localhost:5000 first."}
```

I am able to push an image to this registry using docker push from the command line.
##### STEPS TO REPRODUCE

I use the docker_image module in the following way, in a basic playbook:

Tag the image:

```
docker tag my_image localhost:5000/my_image
```

Use the docker_image module:

```
- name: Try local registry
    docker_image:
      path: "{{my_image_dir}}"
      name: localhost:5000/my_image
      force: true
      state: present
```

I do curl 

```
http://localhost:5000/v2/_catalog  
```

and this returns fine, so the registry works at localhost:5000 but the image doesn't get pushed.
##### EXPECTED RESULTS

Get the image to the local registry.
##### ACTUAL RESULTS

```
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error: configuration for localhost:5000 not found. Try logging into localhost:5000 first."}
```

**Comment by ansibot** [comment]
@ansible ping, this issue is waiting for your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by chouseknecht** [comment]
notabug

Not able to reproduce using the `devel` branch. 

Here's my test playbook:

```
- name: Test local registry
  connection: local
  gather_facts: no
  hosts: localhost
  tasks:
    - docker_image:
        name: busybox
        repository: localhost:5000/my_image
        tag: latest
        force: true
        state: present
        push: yes
```

Run:

```
$ ansible-playbook test.yml

PLAY [Test local registry] *****************************************************

TASK [docker_image] ************************************************************
changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0
```

...and check the repository:

```
$ curl http://localhost:5000/v2/_catalog
{"repositories":["my_image"]}
```
