### ISSUE TITLE
oracle-se2 support needed. 

### ISSUE THREAD

**Issue by xhibit** [ansible/ansible-modules-core#4808]
##### ISSUE TYPE
- Feature Idea
- Documentation Report
##### COMPONENT NAME

RDS
##### ANSIBLE VERSION

```
2.1.1.0
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

db_engine "oracle-se2" isn't listed in the documentation as supported.

It is however a supported AWS version:
https://aws.amazon.com/about-aws/whats-new/2016/08/amazon-rds-now-supports-se2-license-included/
##### STEPS TO REPRODUCE

```

  server_rds_prd:
    multi_zone_option: no
    db_engine: oracle-se2
    db_size: 100
    instance_type: db.m4.xlarge
    db_name: ORCLPRD
    db_username: secret
    db_password: secrettoo
    backup_retention_period: 5

- name: RDS - PRD | Create RDS Instance
    rds:
      command: create
      instance_name: "{{account_name}}-db-prd"
      db_name: "{{ server_rds_prd.db_name|upper }}"
      db_engine: "{{ server_rds_prd.db_engine }}"
      # engine_version: # If not specified then the current Amazon RDS default engine version is used.
      region: "{{ aws_region }}"
      multi_zone: "{{ server_rds_prd.multi_zone_option }}"
      subnet: "{{ account_name }}-db-sng"
      vpc_security_groups: "{{aws_vpc_sg_private_prd_db_id}}"
      size: "{{ server_rds_prd.db_size }}"
      license_model: license-included
      instance_type: "{{ server_rds_prd.instance_type }}"
      username: "{{ server_rds_prd.db_username }}"
      password: "{{ server_rds_prd.db_password }}"
      backup_retention: "{{ server_rds_prd.backup_retention_period }}"
      # maint_window: Sun:22:00-Sun:23:15 # If not specified then a random maintenance window is assigned.
      # backup_window: hh24:mi-hh24:mi # If not specified then a random backup window is assigned.
      tags: { Name: "{{account_name}}-db-prd", type: db, env: test }
      wait: yes
      wait_timeout: 1200

```
##### EXPECTED RESULTS

Support for db-engine oracle-se2
##### ACTUAL RESULTS

```
task path: /home/vagrant/ansible/roles/ec2/tasks/ec2_rds_prd.yml:27
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: vagrant
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1473771612.52-139906728735613 `" && echo ansible-tmp-1473771612.52-139906728735613="` echo $HOME/.ansible/tmp/ansible-tmp-1473771612.52-139906728735613 `" ) && sleep 0'
<localhost> PUT /tmp/tmp4cWTS_ TO /home/vagrant/.ansible/tmp/ansible-tmp-1473771612.52-139906728735613/rds
<localhost> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1473771612.52-139906728735613/rds; rm -rf "/home/vagrant/.ansible/tmp/ansible-tmp-1473771612.52-139906728735613/" > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"apply_immediately": false, "backup_retention": "5", "command": "create", "db_engine": "oracle-se2", "db_name": "ORCLPRD", "force_failover": false, "instance_name": "axesso-dev-db-prd", "instance_type": "db.m4.xlarge", "license_model": "license-included", "multi_zone": false, "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "region": "us-west-2", "size": "100", "subnet": "axesso-dev-db-sng", "tags": {"Name": "axesso-dev-db-prd", "env": "test", "type": "db"}, "upgrade": false, "username": "master", "validate_certs": true, "vpc_security_groups": ["sg-448f4c3d"], "wait": true, "wait_timeout": 1200}, "module_name": "rds"}, "msg": "value of db_engine must be one of: MySQL,oracle-se1,oracle-se,oracle-ee,sqlserver-ee,sqlserver-se,sqlserver-ex,sqlserver-web,postgres, got: oracle-se2"}
```
