### ISSUE TITLE
eos_config match:none has become idempotent - improve docs

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible-modules-core#4810]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

eos_config
And possibly other `_config` modules
##### ANSIBLE VERSION

```
ansible 2.2.0 (eos_cmd_v_item 15cf123420) last updated 2016/09/13 12:04:55 (GMT +100)
  lib/ansible/modules/core: (devel ae6992bf8c) last updated 2016/09/13 09:19:01 (GMT +100)
  lib/ansible/modules/extras: (devel 1f6f3b72db) last updated 2016/09/13 09:19:10 (GMT +100)
```
##### SUMMARY

This is most likely going to be a documentation issue rather than a code issue.

In `eos_template` when `force: true` was used we to always report as changed.
From the documentation for eos_template

> The force argument instructs the module to not consider the current devices running-config. When set to true, this will cause the module to push the contents of src into the device without first checking if already configured.

For `eos_config` (and possibly all `_config` modules) it appears that force does an idempotent check. Which you could strongly argue is the "right thing", however in the `eos_config` documentation we state:

> The force argument instructs the module to not consider the current devices running-config. When set to true, this will cause the module to push the contents of src into the device without first checking if already configured.
> Note this argument should be considered deprecated. To achieve the equivalient, set the match argument to none. This argument will be removed in a future release.

Note using `match: none` and `force: true` with `eos_config` both do the same thing, i.e. are idempotent
##### STEPS TO REPRODUCE

```
- name: configure device with config
  eos_config:
    src: basic/config.j2
    provider: "{{ cli }}"
    match: none
  register: result

- name: configure device with config
  eos_config:
    src: basic/config.j2
    provider: "{{ cli }}"
    match: none
  register: result

- assert:
    that:
      - "result.changed == true"
```
##### EXPECTED RESULTS

Documentation and implementation to match
