### ISSUE TITLE
docker_container fails to restart containers

### ISSUE THREAD

**Issue by antigremlin** [ansible/ansible-modules-core#4815]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

docker_container
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = __some_local_file__
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
[defaults]
inventory=hosts
remote_tmp=/tmp/${USER}/.ansible
transport=ssh
roles_path=../ansible-roles

[ssh_connection]
ssh_args=
```
##### OS / ENVIRONMENT

OS: Windows 7 Enterprise. Cygwin version:

```
Cygwin DLL version info:
        DLL version: 2.5.2
```
##### SUMMARY

Ansible cannot restart the docker container and the container is killed instead.
##### STEPS TO REPRODUCE
1. In a playbook task, use docker_container to start something
2. In a playbook handler, use docker_container to restart
3. (alternatively) In a different playbook, use docker_container to restart the same container

```
docker_container: name=container_name status=started restart=yes
```

EDIT: I don't have a minimal set-up to expose the problem, but I can try and create a create it when I have some spare time.
##### EXPECTED RESULTS

The container should be restarted. Best option would be to use the /restart API endpoint. I understand that now /stop and /start are used sequentially.
##### ACTUAL RESULTS

The container is stopped and destroyed. Ansible reports the following error:

```
fatal: [hostname]: FAILED! => {"changed": false, "failed": true, "msg": "Error creating container: 500 Server Error: Internal Server Error (\"No command specified\")"}
```

Docker engine log contains these lines:

```
Sep 13 17:00:16 _hostname_ docker[23355]: time="2016-09-13T17:00:16.873965272+02:00" level=warning msg="container c52f0aca40c41828174817ce2cc7d06bb9837e33d943b5047fa9db632b2b2647 restart canceled"
Sep 13 17:00:16 _hostname_ docker[23355]: time="2016-09-13T17:00:16.962864620+02:00" level=error msg="Handler for POST /v1.22/containers/create returned error: No command specified"
```

**Comment by ansibot** [comment]
@ansible ping, this issue is waiting for your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by chouseknecht** [comment]
needs_info

I'm not able to reproduce this with a simple test, as you describe. Here's my test:

Run the following playbook to create a container:

```
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - docker_container:
        image: busybox
        name: blazing_saddle
        command: sleep 1d
```

Then run the following to restart the container:

```
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - docker_container:
        name: blazing_saddle
        state: started
        restart: yes
```

Observe that the container is restarted and retains the same Container ID value, indicating that it was not destroyed. 

It is possible that there is some configuration comparison that is failing. In other words, there may be a property you're setting when the container is created that the module is not properly evaluating during subsequent calls.

**Comment by ansibot** [comment]
@antigremlin ping, this issue is still waiting on your feedback. We will close the issue if you do not respond.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by yiwork** [comment]
I'm experiencing the same issue (and it is mostly related to, i believe, attaching a device to the container)

Test playbook:

```
---
- hosts: localhost
  tasks:
    - name: start a container
      docker_container:
        image: redis
        name:  redis1
        state: started
        pull: yes
        devices:
          - "/dev/xvdf:/dev/xvdf:rwm"
    - name: start the same container again with diff command
      docker_container:
        image: redis
        name:  redis1
        state: started
        recreate: yes
        command: "redis-server"
        devices:
          - "/dev/xvdf:/dev/xvdf:rwm"
```

Here is the output:

```
% ansible-playbook -i localhost test_container.yml
 [WARNING]: Host file not found: localhost

 [WARNING]: provided hosts list is empty, only localhost is available

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [start a container] *******************************************************
changed: [localhost]

TASK [start the same container again with diff command] ******************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: unhashable type: 'dict'
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_dt8
VuZ/ansible_module_docker_container.py\", line 1921, in <module>\n    main()\n  File \"/tmp/ansible_dt8VuZ/ansible_module_docker_container.py\",
line 1914, in main\n    cm = ContainerManager(client)\n  File \"/tmp/ansible_dt8VuZ/ansible_module_docker_container.py\", line 1583, in __init__\
n    self.present(state)\n  File \"/tmp/ansible_dt8VuZ/ansible_module_docker_container.py\", line 1611, in present\n    different, differences =
container.has_different_configuration(image)\n  File \"/tmp/ansible_dt8VuZ/ansible_module_docker_container.py\", line 1216, in has_different_conf
iguration\n    set_b = set(value)\nTypeError: unhashable type: 'dict'\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}

NO MORE HOSTS LEFT *************************************************************
 [WARNING]: Could not create retry file 'test_container.retry'.         [Errno 2] No such file or directory: ''


PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=1
```

The docker command obviously on the 2nd task has to be different to get Ansible to replace the existing running container, however it is the same command that is issued the redis-image itself uses as the run command. 

I'm currently running Ansible 2.1.1, can test on 2.1.2 if you want me to.  No inventory/hosts file needed for this playbook to run.  I have no custom `ansible.cfg` or environment set when running that playbook.
