### ISSUE TITLE
ec2 module - root volume size customization

### ISSUE THREAD

**Issue by chris-neely** [ansible/ansible-modules-core#4821]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

ec2 module
##### ANSIBLE VERSION

```
ansible 2.1.1.0
```
##### OS / ENVIRONMENT

Ubuntu 14.04
##### SUMMARY

I'm working on a playbook to launch a windows ec2 instance with a custom root volume size.  It appears that my play is completely overlooking the 'volumes' attribute when creating the instance though.  I'm not getting any errors.. but the instance is created with the default 30GB root volume size.
##### STEPS TO REPRODUCE

Below is an example playbook as well as an example role that we have created.  Using this configuration it appears that the volumes info is not being taken into consideration when creating an instance.

Playbook:

```

---
- include: aws.yml
- name: create server in availbility zone
  hosts: control
  gather_facts: yes
  vars_files:
    - group_vars/secret.yml
  vars:
    - app_name: "TEST"
    - app_updates: "Yes"
    - app_persistence: "Yes"
    - instance_type: m3.medium
    - instance_count: 1
    - term_protect: yes
    - vpc_subnet_id: my-subnet-id
    - instance_zone: my-az-info
  roles:
    - win_launch
```

win_launch role:

```
- name: Launch new instance
  ec2:
    region: "{{ region }}"
    keypair: "{{ keypair }}"
    zone: "{{ instance_zone }}"
    group_id: [ "{{ sg_out.group_id }}" ]
    image: "{{ win_ami_id }}"
    instance_type: "{{ instance_type }}"
    assign_public_ip: no
    termination_protection: "{{ term_protect }}"
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    wait: yes
    exact_count: "{{ instance_count }}"
    count_tag:
      Name: "{{ app_name }}"
    instance_tags:
      Name: "{{ app_name }}"
      Updates: "{{ app_updates }}"
      Persistent: "{{ app_persistence }}"
    user_data: "{{ lookup('template','userdata.txt.j2') }}"
    volumes:
      - device_name: /dev/xvda
        volume_size: 80
        volume_type: gp2
  register: ec2
```
##### EXPECTED RESULTS

Expect a windows root drive to be created with the size of my picking.
##### ACTUAL RESULTS

ec2 instance is created with the default root volume size.
