### ISSUE TITLE
ios_config does not allow looping under parents

### ISSUE THREAD

**Issue by wintermute000** [ansible/ansible-modules-core#4903]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

ios_config
##### ANSIBLE VERSION

ansible 2.1.1.0
  config file = /home/ansible/ios_config/ansible.cfg
  configured module search path = Default w/o overrides
ansible@unl01:~/ios_config$ 
##### CONFIGURATION

default ansible.cfg
##### OS / ENVIRONMENT

Ubuntu 14.04 LTS
##### SUMMARY

I am unable to use looping (with_items) with the parents option of ios_config.
##### STEPS TO REPRODUCE

```
  - name: no shut
    ios_config:
      provider: "{{ provider }}"
      lines:
        - no shutdown
      parents: "interface {{ item.interface }}"
      with_items:
        - { interface : Ethernet0/1 }
        - { interface : Ethernet0/2 }
        - { interface : Ethernet0/3 }
```

OR:

```
  - name: no shut
    ios_config:
      provider: "{{ provider }}"
      lines:
        - no shutdown
      parents: "interface {{ item.interface }}"
      with_items:
        - "{{ ip_addresses }}"


(in host inventory)
ip_addresses:
  - interface: Loopback0
    description: Router-ID
    ip_address: 1.1.1.1
    ip_mask: 255.255.255.255
  - interface: Ethernet0/1
    description: "To-ISP1"
    ip_address: 172.31.1.2
    ip_mask: 255.255.255.252
  - interface: Ethernet0/2
    description: "To-SW1"
    ip_address: 10.1.1.2
    ip_mask: 255.255.255.0
    standby_grp: 1
    standby_ip: 10.1.1.1
    standby_pri: 200
  - interface: Ethernet0/3
    description: "To-WAN2"
    ip_address: 10.1.254.253
    ip_mask: 255.255.255.252
```

---------------- OUTPUT-----------------

---

< TASK [no shut] >

---

```

task path: /home/ansible/ios_config/ios_config_play.yml:38
fatal: [wan1.cisco.com]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'item' is undefined\n\nThe error appears to have been in '/home/ansible/ios_config/ios_config_play.yml': line 38, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n  - name: no shut\n    ^ here\n"}

msg: the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'item' is undefined

The error appears to have been in '/home/ansible/ios_config/ios_config_play.yml': line 38, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


  - name: no shut
    ^ here

```
##### EXPECTED RESULTS

the no shut command is run under interface X, interface Y, interface Z as defined in the with_items list
##### ACTUAL RESULTS

With this debug, I can see that the with_items should work

```
  - name: test
    debug: msg="{{ item.interface }}"
    with_items:
      - "{{ ip_addresses }}"

```

```
_____________
< TASK [test] >
 -------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

task path: /home/ansible/ios_config/ios_config_play.yml:33
ok: [wan1.cisco.com] => (item={u'interface': u'Loopback0', u'ip_mask': u'255.255.255.255', u'ip_address': u'1.1.1.1', u'description': u'Router-ID'}) => {
    "invocation": {
        "module_args": {
            "msg": "Loopback0"
        }, 
        "module_name": "debug"
    }, 
    "item": {
        "description": "Router-ID", 
        "interface": "Loopback0", 
        "ip_address": "1.1.1.1", 
        "ip_mask": "255.255.255.255"
    }, 
    "msg": "Loopback0"
}
ok: [wan1.cisco.com] => (item={u'interface': u'Ethernet0/1', u'ip_mask': u'255.255.255.252', u'ip_address': u'172.31.1.2', u'description': u'To-ISP1'}) => {
    "invocation": {
        "module_args": {
            "msg": "Ethernet0/1"
        }, 
        "module_name": "debug"
    }, 
    "item": {
        "description": "To-ISP1", 
        "interface": "Ethernet0/1", 
        "ip_address": "172.31.1.2", 
        "ip_mask": "255.255.255.252"
    }, 
    "msg": "Ethernet0/1"

```

etc.

This is an extremely standard networking use case (i.e. making selective changes under defined interface parent sections). If I've messed up anything basic then I apologise in advance, but I can't see how the debug works but the real thing fails. I've even gone back to basics and manually defined the dictionary instead of calling it

**Comment by ansibot** [comment]
@privateip, @gundalow, ping. This issue is waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by privateip** [comment]
Your task is malformed.  The `with_items` directive should be aligned with the module (ios_config).

```
  - name: no shut
    ios_config:
      provider: "{{ provider }}"
      lines:
        - no shutdown
      parents: "interface {{ item.interface }}"
    with_items:
      - { interface : Ethernet0/1 }
      - { interface : Ethernet0/2 }
      - { interface : Ethernet0/3 }
```
