### ISSUE TITLE
eos_eapi http_port only set when enable_http: true

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible-modules-core#4905]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

eos_eapi
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 697888965e) last updated 2016/09/16 13:36:43 (GMT +100)
  lib/ansible/modules/core: (devel 1df235f8ca) last updated 2016/09/19 09:15:02 (GMT +100)
  lib/ansible/modules/extras: (devel 88464efdc4) last updated 2016/09/19 09:15:26 (GMT +100)

```
##### STEPS TO REPRODUCE

```
- name: Change endpoint ports
  eos_eapi:
    enable_http: false # HACK
    http_port: 8080
    https_port: 14443
    enable_local_http: yes
    local_http_port: 18181
    provider: "{{ cli }}"
  register: eos_eapi_output
  connection: local

```
##### EXPECTED RESULTS

`http_port` to be set even though `enable_http` is false
##### ACTUAL RESULTS

Only ports for services that are enabled are
