### ISSUE TITLE
Mount With Complex Password Hangs Forever

### ISSUE THREAD

**Issue by DaytonG** [ansible/ansible-modules-core#4915]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

mount
##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

No changes were made to ansible configuration.
##### OS / ENVIRONMENT

ubuntu 12.04 (target host)
ubuntu 14.04 (ansible controller)
##### SUMMARY

When a mount password is provided that has unacceptable characters, fstab is not parsed properly which results in /bin/mount prompting for a password. This causes the mount command to hang silently forever.
##### STEPS TO REPRODUCE

We're mounting an NFS drive, which (eventually) uses AD as the auth mechanism. I don't believe that contributes to the issue. The whole issue seems to be that /bin/mount is asking for stdin.

```
- name: setup NFS host
  hosts: nfs_host
  vars: 
    mount_password: 'MyPassword/["HasFunnyCharacters'
  tasks:
    - name: mount nfs share
      mount:
        name: "/mnt/myshare"
        src: "//myshare/somedir"
        fstype: "cifs"
        opts: "domain=mydomain,user=myuser,password={{ mount_password }}"
        state: mounted
```

##### EXPECTED RESULTS

I believe that mount should timeout or die rather quickly if input is requested but unavailable.

I realize there are various other mount options to use to avoid this scenario, but it would be nice if the mount module handled the input request in some elegant way and fail out.
##### ACTUAL RESULTS

Mount will hang forever when `/bin/mount /mnt/myshare` is called.
