### ISSUE TITLE
role dependency doesn't work as expected

### ISSUE THREAD

**Issue by liuyong2000** [ansible/ansible-modules-core#4932]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

role definintion and playbook execution
##### ANSIBLE VERSION

ansible 2.1.0.0
##### CONFIGURATION

None change to ansible.cfg
##### OS / ENVIRONMENT

N/A
##### SUMMARY

In official ansible document site,
http://docs.ansible.com/ansible/playbooks_roles.html
It said,
Roles dependencies are always executed before the role that includes them, and are recursive. By default, roles can also only be added as a dependency once - if another role also lists it as a dependency it will not be run again.
but sometimes, it doesn't work as expected, the same role were executed multiple times. Maybe we need consider what role object is?  the same role definition with different variable input may be considered different role object, but if we add conditional dependency for a role, that is we use "when",  is the role with "when" different with role without "when"?
##### STEPS TO REPRODUCE

Suppose we have a playbook, which has a role named csf that depends on csfA/csfB/csfC, and csfB and csfA depends on csfC in some condition, 

```
# main playbook
#ls.yml

---
- name: play1
  hosts: SSHproxy
  remote_user: root
  gather_facts: false
  roles:
    - {role: csf, taskN: task1 }

#csf role definition
#roles/csf/meta/main.yml

---
dependencies:
- role: csfC
- role: csfA
- role: csfB

# csfA role defintion
#roles/csfA/meta/main.yml

---
dependencies:
- {role: csfC, when: taskN=='task1'}

#roles/csfA/tasks/main.yml
- shell: ls


# csfB role definition
#roles/csfB/meta/main.yml

---
dependencies:
- {role: csfC, when: taskN=='task1'}

#roles/csfB/tasks/main.yml
- shell: ls

```

##### EXPECTED RESULTS

role csfC will be executed just one time

PLAY [play1] *******************************************************************

TASK [csfC : command] **********************************************************
changed: [SSHproxy]

TASK [csfA : command] **********************************************************
changed: [SSHproxy]

TASK [csfB : command] **********************************************************
changed: [SSHproxy]

PLAY RECAP *********************************************************************
SSHproxy                   : ok=3    changed=3    unreachable=0    failed=0   
##### ACTUAL RESULTS

role csfC were executed two times.

PLAY [play1] *******************************************************************

TASK [csfC : command] **********************************************************
changed: [SSHproxy]

TASK [csfC : command] **********************************************************
changed: [SSHproxy]

TASK [csfA : command] **********************************************************
changed: [SSHproxy]

TASK [csfB : command] **********************************************************
changed: [SSHproxy]

PLAY RECAP *********************************************************************
SSHproxy                   : ok=4    changed=4    unreachable=0    failed=0
