### ISSUE TITLE
Error bring dockercompose up

### ISSUE THREAD

**Issue by andreea-vld** [ansible/ansible-modules-core#4936]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

docker_service
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

n/a
##### OS / ENVIRONMENT

Ubuntu 14.04
##### SUMMARY

I am trying to call docker-compose from Ansible using docker_service module and I get an error with very few details. 
If I call docker-compose directly, everything works correctly.
Other tools versions:
Python 2.7.6
pip 8.1.2 from /usr/local/lib/python2.7/dist-packages (python 2.7)
docker_py-1.9.0
docker-compose version 1.7.1, build 6c29830
##### STEPS TO REPRODUCE

1. Have a playbook containing a docker_service module
2. Run playbook

```
 - name: Start Docker-compose
      docker_service:
        project_src: ../docker-compose/
        files: dev.yml
        state: present
        scale: 
          server1: 2
```

##### EXPECTED RESULTS

Docker-compose starts all containers without errors.
##### ACTUAL RESULTS

Received following error (-vvvv) :

```
TASK [Start Docker-compose] **************************************
task path: /home/andreeav/workspace/docker-workspace/ansible/start.yml:17
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: andreeav
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1474364184.49-149863168021526 `" && echo ansible-tmp-1474364184.49-149863168021526="` echo $HOME/.ansible/tmp/ansible-tmp-1474364184.49-149863168021526 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpzmVeR1 TO /home/andreeav/.ansible/tmp/ansible-tmp-1474364184.49-149863168021526/docker_service
<127.0.0.1> EXEC /bin/sh -c 'LANG=en_GB.UTF-8 LC_ALL=en_GB.UTF-8 LC_MESSAGES=en_GB.UTF-8 /usr/bin/python /home/andreeav/.ansible/tmp/ansible-tmp-1474364184.49-149863168021526/docker_service; rm -rf "/home/andreeav/.ansible/tmp/ansible-tmp-1474364184.49-149863168021526/" > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"api_version": null, "build": true, "cacert_path": null, "cert_path": null, "debug": false, "definition": null, "dependencies": true, "docker_host": null, "files": ["dev.yml"], "filter_logger": false, "hostname_check": false, "key_path": null, "project_name": null, "project_src": "../docker-compose/", "recreate": "smart", "remove_images": null, "remove_orphans": false, "remove_volumes": false, "restarted": false, "scale": {"server1": 2}, "services": null, "ssl_version": null, "state": "present", "stopped": false, "timeout": null, "tls": null, "tls_hostname": null, "tls_verify": null}, "module_name": "docker_service"}, "msg": "Error bring dockercompose up - "}

```

**Comment by ansibot** [comment]
@ansible ping, this issue is waiting for your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by chouseknecht** [comment]
@andreea-vld

A copy of your dev.yml would be helpful. 

Attempting to reproduce the error with the following playbook and dev.yml files:

test.yml (playbook):

```
- name: Start Docker-compose
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - docker_service:
        project_src: ./docker-compose/
        files: dev.yml
        state: present
        scale:
          test: 2
```

My docker-compose directory is next to the playbook, and it contains the following dev.yml:

```
version: "2"
services:
   test:
     image: centos:7
     command: sleep 1d
```

Running the playbook works fine. I can get it to throw the same error, however, if I change the tag on the `image` directive to something invalid like `12`. The error you're experience gets thrown when the call to the compose up method fails.

It does look like the error handling has a bug, as it references `self.project.name`, which is probably incorrect. I've added that fix. So now, using the code from source (once my PR is merged), and putting a bad value in the compose file, it throws a useful message like the following:

```
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error starting project - Tag 12 not found in repository docker.io/library/centos"}
```

Anyway, given the circumstances under which this error message gets thrown, I suspect your compose file might contain an incorrect value.
