### ISSUE TITLE
iam_cert module error : value of dup_ok must be one of: False,True, got: True

### ISSUE THREAD

**Issue by endling1** [ansible/ansible-modules-core#4938]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

iam_cert
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /Users/ABC16gb/Documents/Projects/AWS/jenkins/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```
##### CONFIGURATION

ansible.cfg : 
[defaults]
host_file = inventory/ec2.py
inventory = inventory/
host_key_checking = False

[ssh_connection]
control_path = %(directory)s/%%h-%%r
##### OS / ENVIRONMENT

NA
##### SUMMARY

Get the above mentioned error even when dup_ok is set to True
##### STEPS TO REPRODUCE

```
- name: "SSL: self-signed: Upload certificate into AWS/IAM"
  iam_cert:
    name: "{{ aws_name_tag }}"
    state: present
    cert: "{{ ssl_cert_path_local }}"
    key: "{{ ssl_key_path_local }}"
    dup_ok: True

```
##### EXPECTED RESULTS

Upload certificates
##### ACTUAL RESULTS

Fatal error

```
localhost> ESTABLISH LOCAL CONNECTION FOR USER: abc16gb
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1474370591.44-108967808855571 `" && echo ansible-tmp-1474370591.44-108967808855571="` echo $HOME/.ansible/tmp/ansible-tmp-1474370591.44-108967808855571 `" ) && sleep 0'
<localhost> PUT /var/folders/c1/mmksrrsd2xz59lm25277m4cc0000gn/T/tmp02Kpb9 TO /Users/tesco16gb/.ansible/tmp/ansible-tmp-1474370591.44-108967808855571/iam_cert
<localhost> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /Users/tesco16gb/.ansible/tmp/ansible-tmp-1474370591.44-108967808855571/iam_cert; rm -rf "/Users/tesco16gb/.ansible/tmp/ansible-tmp-1474370591.44-108967808855571/" > /dev/null 2>&1 && sleep 0'


fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"cert": "dev-jenkins.crt", "dup_ok": "True", "key": "dev-jenkins.key", "name": "dev-jenkins", "path": "/", "state": "present", "validate_certs": true}, "module_name": "iam_cert"}, "msg": "value of dup_ok must be one of: False,True, got: True"}

```
