### ISSUE TITLE
including a play will cause load error for the role behind it 

### ISSUE THREAD

**Issue by liuyong2000** [ansible/ansible-modules-core#4944]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

It is not specific to a module, it is a bug/issue for the role/include mechinism implementation
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### CONFIGURATION

No change to ansible.cfg
##### OS / ENVIRONMENT

N/A
##### SUMMARY

including a play which has a relative path in a playbook, will cause load error for  role in late play  
##### STEPS TO REPRODUCE

pls follow the playbook below

```
- include: tasks/common/em2.yml
- name: play1
  hosts: SSHproxy
  remote_user: root
  gather_facts: false
  roles:
  - csfA

```

no specific requirement for the play included and role behind it.

##### EXPECTED RESULTS

It will cause a playbook loading error. Pls see the below error information. 
##### ACTUAL RESULTS

ERROR! the role 'csfA' was not found in /home/rover/ansible/tasks/common/roles:/home/rover/ansible/tasks/common:/etc/ansible/roles /home/rover/ansible/tasks/common

The error appears to have been in '/home/rover/ansible/inc.yml': line 8, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
- csfA
  ^ here
  

```

```
