### ISSUE TITLE
ios_config does not work for sub-commands of config t

### ISSUE THREAD

**Issue by salman1485** [ansible/ansible-modules-core#4953]
checked already. Only 4 threads for ios_config and none are related to my issue.
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

ios_config
##### ANSIBLE VERSION

ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
##### CONFIGURATION

Default
##### OS / ENVIRONMENT

Running on CentOS 7.

Managing 

```
Switch      Ports      Model                        SW Version

    1             52           WS-C3650-48TD      03.07.04E

Switch        Ports      Model                    SW Version
    1               54         WS-C3750X-48       15.0(1)SE3

```
##### SUMMARY

The job of below two commands on IOS is to update description of GigabithEthernet1/0/2. While these when executed manually on IOS do work just fine, but they fail when integrated with playbook.
interface GigabitEthernet1/0/2
description to test
##### STEPS TO REPRODUCE

When executed directly on switch, it looks like below:

<hostname>#config t
Enter configuration commands, one per line.  End with CNTL/Z.
<hostname>(config)#interface GigabitEthernet1/0/2
<hostname>(config-if)#description to test

As you can see, after running interface command prompt changes from (config) to (config-if). Now, here is the PB.

```yaml
---
- hosts: cisco
  gather_facts: no
  connection: local

  vars_files:
    - vars/secrets.yml
  tasks:

  - name: Test basic commands
    ignore_errors: yes
    ios_config:
      lines:
        - interface GigabitEthernet1/0/2
        - description to test
      authorize: yes
      provider: "{{ cli }}"

```
##### EXPECTED RESULTS

Should just perform updates on the remote device.
##### ACTUAL RESULTS

Here is the error:
fatal: [<hostname-edited>]: FAILED! => {"changed": false, "commands": ["configure terminal", "description to test"], "failed": true, "msg": "matched error in response: description to test\r\n                           ^\r\n% Invalid input detected at '^' marker.\r\n\r\n<hostname-edited>(config)#"}

More details:
As you can see from error, the 2nd command is executed on prompt (config) due to which we get error. Ideally, ios_config module should execute both commands in order just like they get executed manually in remote IOS device.

I hope someone has tried this.

Interestingly, below PB works just fine. All that I did was that I applied the 2nd "description" command on a range of interfaces. 

```yaml
---
- hosts: cisco
  gather_facts: no
  connection: local

  vars_files:
    - vars/secrets.yml
  tasks:

  - name: Test basic commands
    ignore_errors: yes
    ios_config:
      lines:
        - interface range GigabitEthernet1/0/2-20
        - description to test
      authorize: yes
      provider: "{{ cli }}"
```

**Comment by ansibot** [comment]
@privateip, @gundalow, ping. This issue is waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by privateip** [comment]
Your task is not structured properly.  You need to specify the parents argument.

```
  - name: Test basic commands
    ignore_errors: yes
    ios_config:
      lines:
        - description to test
      parents: interface range GigabitEthernet1/0/2-20
      authorize: yes
      provider: "{{ cli }}"
```
