### ISSUE TITLE
nxos_config isn't idempotent (in some cases)

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible-modules-core#4963]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

nxos_config
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 547cea556f) last updated 2016/09/20 12:12:18 (GMT +100)
  lib/ansible/modules/core: (devel 12a7027c49) last updated 2016/09/20 15:11:43 (GMT +100)
  lib/ansible/modules/extras: (devel db7a3f48e1) last updated 2016/09/20 11:53:00 (GMT +100)
```
##### STEPS TO REPRODUCE

```
- name: setup
  nxos_config:
    commands:
      - no description
      - no shutdown
    parents:
      - interface Ethernet2/5
    match: none
    provider: "{{ cli }}"

- name: configure device with config
  nxos_config:
    src: basic/config.j2
    provider: "{{ cli }}"
    match: none
  register: result

- assert:
    that:
      - "result.changed == true"
# https://github.com/ansible/ansible-modules-core/issues/4807
      - "result.updates is not defined"

- name: check device with config
  nxos_config:
    src: basic/config.j2
    provider: "{{ cli }}"
    match: none
  register: result

- assert:
    that:
      # Idempotent test
# https://github.com/ansible/ansible-modules-core/issues/4807
      - "result.changed == false"
      - "result.updates is not defined"

```

```
cat templates/basic/config.j2 
interface Ethernet2/5
   description this is a test
   shutdown

```
##### ACTUAL RESULTS

```
TASK [test_nxos_config : configure device with config] *************************
task path: /home/johnb/git/ansible-inc/test-network-modules/roles/test_nxos_config/tests/cli/src_match_none.yaml:14
Using module file /home/johnb/git/ansible-inc/ansible/lib/ansible/modules/core/network/nxos/nxos_config.py
<nxos01> ESTABLISH LOCAL CONNECTION FOR USER: johnb
<nxos01> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1474483552.07-278464852480214 `" && echo ansible-tmp-1474483552.07-278464852480214="` echo $HOME/.ansible/tmp/ansible-tmp-1474483552.07-278464852480214 `" ) && sleep 0'
<nxos01> PUT /tmp/tmpmSyMj7 TO /home/johnb/.ansible/tmp/ansible-tmp-1474483552.07-278464852480214/nxos_config.py
<nxos01> EXEC /bin/sh -c 'chmod u+x /home/johnb/.ansible/tmp/ansible-tmp-1474483552.07-278464852480214/ /home/johnb/.ansible/tmp/ansible-tmp-1474483552.07-278464852480214/nxos_config.py && sleep 0'
<nxos01> EXEC /bin/sh -c 'python /home/johnb/.ansible/tmp/ansible-tmp-1474483552.07-278464852480214/nxos_config.py; rm -rf "/home/johnb/.ansible/tmp/ansible-tmp-1474483552.07-278464852480214/" > /dev/null 2>&1 && sleep 0'
changed: [nxos01] => {
    "changed": true, 
    "invocation": {
        "module_args": {
            "after": null, 
            "auth_pass": null, 
            "authorize": false, 
            "backup": false, 
            "before": null, 
            "config": null, 
            "defaults": false, 
            "force": false, 
            "host": "nxos01", 
            "lines": null, 
            "match": "none", 
            "parents": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": null, 
            "provider": {
                "host": "nxos01", 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "transport": "cli", 
                "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
            }, 
            "replace": "line", 
            "save": false, 
            "src": "interface Ethernet2/5\n   description this is a test\n   shutdown\n\n", 
            "ssh_keyfile": null, 
            "timeout": 10, 
            "transport": "cli", 
            "use_ssl": false, 
            "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "validate_certs": true
        }
    }, 
    "warnings": []
}

TASK [test_nxos_config : assert] ***********************************************
task path: /home/johnb/git/ansible-inc/test-network-modules/roles/test_nxos_config/tests/cli/src_match_none.yaml:21
ok: [nxos01] => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "that": [
                "result.changed == true", 
                "result.updates is not defined"
            ]
        }, 
        "module_name": "assert"
    }, 
    "msg": "all assertions passed"
}

TASK [test_nxos_config : check device with config] *****************************
task path: /home/johnb/git/ansible-inc/test-network-modules/roles/test_nxos_config/tests/cli/src_match_none.yaml:27
Using module file /home/johnb/git/ansible-inc/ansible/lib/ansible/modules/core/network/nxos/nxos_config.py
<nxos01> ESTABLISH LOCAL CONNECTION FOR USER: johnb
<nxos01> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1474483562.39-244603509576702 `" && echo ansible-tmp-1474483562.39-244603509576702="` echo $HOME/.ansible/tmp/ansible-tmp-1474483562.39-244603509576702 `" ) && sleep 0'
<nxos01> PUT /tmp/tmpTQ_P7m TO /home/johnb/.ansible/tmp/ansible-tmp-1474483562.39-244603509576702/nxos_config.py
<nxos01> EXEC /bin/sh -c 'chmod u+x /home/johnb/.ansible/tmp/ansible-tmp-1474483562.39-244603509576702/ /home/johnb/.ansible/tmp/ansible-tmp-1474483562.39-244603509576702/nxos_config.py && sleep 0'
<nxos01> EXEC /bin/sh -c 'python /home/johnb/.ansible/tmp/ansible-tmp-1474483562.39-244603509576702/nxos_config.py; rm -rf "/home/johnb/.ansible/tmp/ansible-tmp-1474483562.39-244603509576702/" > /dev/null 2>&1 && sleep 0'
changed: [nxos01] => {
    "changed": true, 
    "invocation": {
        "module_args": {
            "after": null, 
            "auth_pass": null, 
            "authorize": false, 
            "backup": false, 
            "before": null, 
            "config": null, 
            "defaults": false, 
            "force": false, 
            "host": "nxos01", 
            "lines": null, 
            "match": "none", 
            "parents": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": null, 
            "provider": {
                "host": "nxos01", 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "transport": "cli", 
                "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
            }, 
            "replace": "line", 
            "save": false, 
            "src": "interface Ethernet2/5\n   description this is a test\n   shutdown\n\n", 
            "ssh_keyfile": null, 
            "timeout": 10, 
            "transport": "cli", 
            "use_ssl": false, 
            "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "validate_certs": true
        }
    }, 
    "warnings": []
}

TASK [test_nxos_config : assert] ***********************************************
task path: /home/johnb/git/ansible-inc/test-network-modules/roles/test_nxos_config/tests/cli/src_match_none.yaml:34
fatal: [nxos01]: FAILED! => {
    "assertion": "result.changed == false", 
    "changed": false, 
    "evaluated_to": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "that": [
                "result.changed == false", 
                "result.updates is not defined"
            ]
        }, 
        "module_name": "assert"
    }
}
    to retry, use: --limit @/home/johnb/git/ansible-inc/test-network-modules/nxos.retry

PLAY RECAP *********************************************************************
nxos01                     : ok=46   changed=12   unreachable=0    failed=1   

```

**Comment by privateip** [comment]
Play is not setup properly.  Setting match to none will always result in a change as it signals to the module to not consider the current configuration. Correct task below.

Change this task

```
- name: check device with config
  nxos_config:
    src: basic/config.j2
    provider: "{{ cli }}"
    match: none
  register: result
```

to this by removing match: none

```
- name: check device with config
  nxos_config:
    src: basic/config.j2
    provider: "{{ cli }}"
  register: result
```
