### ISSUE TITLE
Conditional on include task fails

### ISSUE THREAD

**Issue by andreea-vld** [ansible/ansible-modules-core#4971]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

include
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```
##### CONFIGURATION

n/a
##### OS / ENVIRONMENT

Ubuntu 14.04
##### SUMMARY

I have an include task conditioned by a when clause which resolves to True, but the playbook is not included. If I add the SAME condition in a variable and use that variable in _when_ , it is evaluated to true and the playbook is included.
##### STEPS TO REPRODUCE

Run site.yml with --extra-vars '{"scale"}': <br>
**ansible-playbook --extra-vars '{"scale"}' site.yml** <br>
site.yml that fails (skips acq.yml):

```
- name: Top-level playbook
  hosts: localhost
  pre_tasks:
    - name: Check dev type
      set_fact: DEV=true
      when: scale is not defined

    - name: Check test type
      set_fact: TEST=true
      when: scale is defined

- include: acq.yml
  when: ((TEST is defined) or (DEV is defined and (USE_ACQ is defined or USE_3DS is defined)))
```

Run site2.yml with --extra-vars '{"scale"}': <br>
**ansible-playbook --extra-vars '{"scale"}' site2.yml** <br>
site2.yml that passes (executes acq.yml): <br>

```
- name: Top-level playbook
  hosts: localhost
  pre_tasks:
    - name: Check dev type
      set_fact: DEV=true
      when: scale is not defined

    - name: Check test type
      set_fact: TEST=true
      when: scale is defined

    - name: Set var
      set_fact: var={{((TEST is defined) or (DEV is defined and (USE_ACQ is defined or USE_3DS is defined)))}}

- include: acq.yml
  when: var
```

##### EXPECTED RESULTS

In both cases, run acq.yml
##### ACTUAL RESULTS

For site.yml, acq.yml is skipped <br>
For site2.yml, acq.yml is executed

```
skipping playbook include 'acq.yml' due to conditional test failure
```
