### ISSUE TITLE
yum module should report installation errors properly

### ISSUE THREAD

**Issue by duck-rh** [ansible/ansible-modules-core#4981]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

yum
##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = /home/duck/test/ansible.cfg
  configured module search path = Default w/o overrides
```

It is rc3.
##### CONFIGURATION

only role path is altered.
##### OS / ENVIRONMENT

Host is Debian unstable and target is CentOS 7.2
##### SUMMARY

When a key is not registered for whatever reason, the module says OK but the playbook run stop with a failure and no useful explanation (-vvvv did not help).
##### STEPS TO REPRODUCE

I'm using Vagrant 'centos/7' image, which happens to have the RPM keys not registered yet (confirmed by manual yum install test). The you can try to install any package not present on the system to trigger the problem.
##### EXPECTED RESULTS

An error message telling me the installation failed because the key is not registered.
##### ACTUAL RESULTS

```
TASK [base : install base rpms] ************************************************
ok: [host.domain.tld] => (item=[u'screen', u'htop', u'iftop', u'iotop', u'strace', u'vim-enhanced', u'tcpdump', u'chrony', u'psmisc', u'rsync'])

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @playbooks/deploy_base.retry

PLAY RECAP *********************************************************************
host.domain.tld       : ok=0    changed=0    unreachable=0    failed=1   
```

Having the tasked marked "ok" and then a failure is very misleading.

**Comment by mscherer** [comment]
I do see that as well. The snippet causing trouble is the following:

```
---
- name: install base rpms
  package: pkg={{ item }} state=present
  with_items:
  - screen
  - htop
  - iftop
  - iotop
```

I suspect the issue is the with_items, as I also seen the problem when 1 package fail to install and not the others. 

Would a simple install with 1 single item and no loop exhibit the same issue ?

**Comment by duck-rh** [comment]
I thought the problem was solved, went too fast.

I experimented on the list of package to install, until I found this interesting message:

> failed: [host.domain.tld](item=[u'iftop', u'iotop', u'strace']) => {"changed": false, "failed": true, "item": ["iftop", "iotop", "strace"], "msg": "No Package matching 'iftop' found available, installed or updated", "rc": 0, "results": []}

So the failure to install two of the packages (in the original list) causes this problem. The result aggregation is not done right.

I tested without these packages and the key is not the problem at all, sorry for the mistake.

**Comment by karlkfi** [comment]
I've seen this problem with the following:

```
- yum: >
    name={{item}}
    state=present
  with_items:
   - curl
   - bash
   - ping
   - tar
   - xz
   - unzip
   - ipset
```

Verbose log (from packer building a virtualbox-iso with ansible-local)

```
    virtualbox-iso: ok: [127.0.0.1] => (item=[u'curl', u'bash', u'ping', u'tar', u'xz', u'unzip', u'ipset']) => {"changed": false, "failed": true, "invocation": {"module_args": {"conf_file": null, "disable_gpg_check": false, "disablerepo": null, "enablerepo": null, "exclude": null, "install_repoquery": true, "list": null, "name": ["curl", "bash", "ping", "tar", "xz", "unzip", "ipset"], "state": "present", "update_cache": false, "validate_certs": true}, "module_name": "yum"}, "item": ["curl", "bash", "ping", "tar", "xz", "unzip", "ipset"], "msg": "No Package matching 'ping' found available, installed or updated", "rc": 0, "results": ["curl-7.29.0-25.el7.centos.x86_64 providing curl is already installed", "bash-4.2.46-20.el7_2.x86_64 providing bash is already installed"]}
    virtualbox-iso:
    virtualbox-iso: NO MORE HOSTS LEFT *************************************************************
    virtualbox-iso: to retry, use: --limit @/tmp/packer-provisioner-ansible-local/dcos-node.retry
    virtualbox-iso:
    virtualbox-iso: PLAY RECAP *********************************************************************
    virtualbox-iso: 127.0.0.1                  : ok=18   changed=14   unreachable=0    failed=1
```

Basically the task exits green and ok, but is marked as failure. Then the playbook exits because of the failure. Without ansible debug, it's impossible to know what's wrong because the error message isn't printed. You can't even tell which task that failed.

With debug, you can see the task output is green and marked `ok` even tho `"failed": true` from `"msg": "No Package matching 'ping' found available, installed or updated"`.

This was using `2.1.2`, but I saw the same on `2.1.1`.
