### ISSUE TITLE
ini_file module doesn't match existing key when it is indented

### ISSUE THREAD

**Issue by agaffney** [ansible/ansible-modules-core#4997]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

`ini_file` module
##### ANSIBLE VERSION

```
ansible 2.1.1.0
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

When a key in an INI file exists but is prefixed with whitespace, the `ini_file` module adds a new entry rather than updating the existing entry.
##### STEPS TO REPRODUCE

Playbook:

```
- hosts: localhost
  gather_facts: no
  tasks:
    - ini_file:
        dest: ./foo.ini
        section: main
        option: foo
        value: baz
```

INI file:

```
[main]
  foo = bar
```
##### EXPECTED RESULTS

```
[main]
  foo = baz
```
##### ACTUAL RESULTS

```
[main]
  foo = bar
foo = baz
```
