### ISSUE TITLE
ios_config isn't idempotent (in some cases)

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible-modules-core#5003]
##### ISSUE TYPE
- Bug Report
  ##### COMPONENT NAME
  ios_config
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 1c7890bf86) last updated 2016/09/26 10:42:34 (GMT +100)
  lib/ansible/modules/core: (devel cf243860ff) last updated 2016/09/26 10:42:39 (GMT +100)
  lib/ansible/modules/extras: (devel 7aab9cd93b) last updated 2016/09/26 10:42:41 (GMT +100)

```
##### SUMMARY

May be similar issue to nxos_config https://github.com/ansible/ansible-modules-core/issues/4963
##### STEPS TO REPRODUCE

``` yaml

---
- debug: msg="START cli/src_match_none.yaml"

- name: setup
  ios_config:
    commands:
      - no description
      - no shutdown
    parents:
      - interface Loopback999
    match: none
    provider: "{{ cli }}"

- name: configure device with config
  ios_config:
    src: basic/config.j2
    provider: "{{ cli }}"
    match: none
  register: result

- assert:
    that:
      - "result.changed == true"
# https://github.com/ansible/ansible-modules-core/issues/4807
      - "result.updates is not defined"

- name: check device with config
  ios_config:
    src: basic/config.j2
    provider: "{{ cli }}"
    match: none
  register: result

- assert:
    that:
      # Idempotent test
# https://github.com/ansible/ansible-modules-core/issues/4807
      - "result.changed == false"
      - "result.updates is not defined"

- debug: msg="END cli/src_match_none.yaml"
```

**templates/basic/config.j2**

```
interface Loopback999
 description this is a test
 shutdown

```
##### ACTUAL RESULTS

``` yaml
TASK [test_ios_config : configure device with config] **************************
task path: /home/johnb/git/ansible-inc/testing-ios/roles/test_ios_config/tests/cli/src_match_none.yaml:14
Using module file /home/johnb/git/ansible-inc/ansible/lib/ansible/modules/core/network/ios/ios_config.py
<ios01> ESTABLISH LOCAL CONNECTION FOR USER: johnb
<ios01> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1474895611.33-274042674420897 `" && echo ansible-tmp-1474895611.33-274042674420897="` echo $HOME/.ansible/tmp/ansible-tmp-1474895611.33-274042674420897 `" ) && sleep 0'
<ios01> PUT /tmp/tmp1I6w4V TO /home/johnb/.ansible/tmp/ansible-tmp-1474895611.33-274042674420897/ios_config.py
<ios01> EXEC /bin/sh -c 'chmod u+x /home/johnb/.ansible/tmp/ansible-tmp-1474895611.33-274042674420897/ /home/johnb/.ansible/tmp/ansible-tmp-1474895611.33-274042674420897/ios_config.py && sleep 0'
<ios01> EXEC /bin/sh -c 'python /home/johnb/.ansible/tmp/ansible-tmp-1474895611.33-274042674420897/ios_config.py; rm -rf "/home/johnb/.ansible/tmp/ansible-tmp-1474895611.33-274042674420897/" > /dev/null 2>&1 && sleep 0'
changed: [ios01] => {
    "changed": true, 
    "invocation": {
        "module_args": {
            "after": null, 
            "auth_pass": null, 
            "authorize": false, 
            "backup": false, 
            "before": null, 
            "config": null, 
            "defaults": false, 
            "force": false, 
            "host": "ios01", 
            "lines": null, 
            "match": "none", 
            "parents": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": null, 
            "provider": {
                "host": "ios01", 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "transport": "cli", 
                "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
            }, 
            "replace": "line", 
            "save": false, 
            "src": "interface Loopback999\n description this is a test\n shutdown\n\n", 
            "ssh_keyfile": null, 
            "timeout": 10, 
            "transport": "cli", 
            "use_ssl": true, 
            "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "validate_certs": true
        }
    }, 
    "warnings": []
}

TASK [test_ios_config : assert] ************************************************
task path: /home/johnb/git/ansible-inc/testing-ios/roles/test_ios_config/tests/cli/src_match_none.yaml:21
ok: [ios01] => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "that": [
                "result.changed == true", 
                "result.updates is not defined"
            ]
        }, 
        "module_name": "assert"
    }, 
    "msg": "All assertions passed"
}

TASK [test_ios_config : check device with config] ******************************
task path: /home/johnb/git/ansible-inc/testing-ios/roles/test_ios_config/tests/cli/src_match_none.yaml:27
Using module file /home/johnb/git/ansible-inc/ansible/lib/ansible/modules/core/network/ios/ios_config.py
<ios01> ESTABLISH LOCAL CONNECTION FOR USER: johnb
<ios01> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1474895624.05-125920805740612 `" && echo ansible-tmp-1474895624.05-125920805740612="` echo $HOME/.ansible/tmp/ansible-tmp-1474895624.05-125920805740612 `" ) && sleep 0'
<ios01> PUT /tmp/tmpkKpaLt TO /home/johnb/.ansible/tmp/ansible-tmp-1474895624.05-125920805740612/ios_config.py
<ios01> EXEC /bin/sh -c 'chmod u+x /home/johnb/.ansible/tmp/ansible-tmp-1474895624.05-125920805740612/ /home/johnb/.ansible/tmp/ansible-tmp-1474895624.05-125920805740612/ios_config.py && sleep 0'
<ios01> EXEC /bin/sh -c 'python /home/johnb/.ansible/tmp/ansible-tmp-1474895624.05-125920805740612/ios_config.py; rm -rf "/home/johnb/.ansible/tmp/ansible-tmp-1474895624.05-125920805740612/" > /dev/null 2>&1 && sleep 0'
changed: [ios01] => {
    "changed": true, 
    "invocation": {
        "module_args": {
            "after": null, 
            "auth_pass": null, 
            "authorize": false, 
            "backup": false, 
            "before": null, 
            "config": null, 
            "defaults": false, 
            "force": false, 
            "host": "ios01", 
            "lines": null, 
            "match": "none", 
            "parents": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": null, 
            "provider": {
                "host": "ios01", 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "transport": "cli", 
                "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
            }, 
            "replace": "line", 
            "save": false, 
            "src": "interface Loopback999\n description this is a test\n shutdown\n\n", 
            "ssh_keyfile": null, 
            "timeout": 10, 
            "transport": "cli", 
            "use_ssl": true, 
            "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "validate_certs": true
        }
    }, 
    "warnings": []
}

TASK [test_ios_config : assert] ************************************************
task path: /home/johnb/git/ansible-inc/testing-ios/roles/test_ios_config/tests/cli/src_match_none.yaml:34
fatal: [ios01]: FAILED! => {
    "assertion": "result.changed == false", 
    "changed": false, 
    "evaluated_to": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "that": [
                "result.changed == false", 
                "result.updates is not defined"
            ]
        }, 
        "module_name": "assert"
    }
}

```

**Comment by privateip** [comment]
Test is invalid in its current form.  Setting match to none will always result in a change as it signals to the module to not consider the current configuration.   Correct task below.

Change this task

```
- name: check device with config
  ios_config:
    src: basic/config.j2
    provider: "{{ cli }}"
    match: none
  register: result
```

to this by removing match: none

```
- name: check device with config
  ios_config:
    src: basic/config.j2
    provider: "{{ cli }}"
  register: result
```
