### ISSUE TITLE
ios_config save: true - "unable to load backup configuration"

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible-modules-core#5008]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

ios_config
iosxr_config
##### ANSIBLE VERSION

```
ansible --version
ansible 2.2.0 (devel 1c7890bf86) last updated 2016/09/26 10:42:34 (GMT +100)
  lib/ansible/modules/core: (devel cf243860ff) last updated 2016/09/26 10:42:39 (GMT +100)
  lib/ansible/modules/extras: (devel 7aab9cd93b) last updated 2016/09/26 10:42:41 (GMT +100)
```
##### SUMMARY

From the code in `ios_config` looks like we've got an exception in the exception handler

```
try:
    run(module, result)   # Triggers exception
except NetworkError:
    load_backup(module)
    exc = get_exception()
    module.fail_json(msg=str(exc))
...
def load_backup(module):
    try:
        module.cli(['exit', 'config replace flash:/ansible-rollback force']) # triggers exception
    except NetworkError:
        module.fail_json(msg='unable to load backup configuration')
```

1) Underlying issue needs fixing
2) Would it be worth Should we capture the exception earlier on in `main()`
3) In `load_backup` can be give the user more feedback about why the error occured?
##### STEPS TO REPRODUCE

``` yaml
- name: setup
  ios_config:
    commands:
      - no description
      - no shutdown
    parents:
      - interface Loopback999
    match: none
    provider: "{{ cli }}"


- name: save config
  ios_config:
    save: true
    provider: "{{ cli }}"
  register: result
```
##### ACTUAL RESULTS

``` yaml
TASK [test_ios_config : save config] *******************************************
task path: /home/johnb/git/ansible-inc/testing-ios/roles/test_ios_config/tests/cli/save.yaml:15
Using module file /home/johnb/git/ansible-inc/ansible/lib/ansible/modules/core/network/ios/ios_config.py
<ios01> ESTABLISH LOCAL CONNECTION FOR USER: johnb
<ios01> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1474897504.34-175123254234396 `" && echo ansible-tmp-1474897504.34-175123254234396="` echo $HOME/.ansible/tmp/ansible-tmp-1474897504.34-175123254234396 `" ) && sleep 0'
<ios01> PUT /tmp/tmp5Z2AeZ TO /home/johnb/.ansible/tmp/ansible-tmp-1474897504.34-175123254234396/ios_config.py
<ios01> EXEC /bin/sh -c 'chmod u+x /home/johnb/.ansible/tmp/ansible-tmp-1474897504.34-175123254234396/ /home/johnb/.ansible/tmp/ansible-tmp-1474897504.34-175123254234396/ios_config.py && sleep 0'
<ios01> EXEC /bin/sh -c 'python /home/johnb/.ansible/tmp/ansible-tmp-1474897504.34-175123254234396/ios_config.py; rm -rf "/home/johnb/.ansible/tmp/ansible-tmp-1474897504.34-175123254234396/" > /dev/null 2>&1 && sleep 0'
fatal: [ios01]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "after": null, 
            "auth_pass": null, 
            "authorize": false, 
            "backup": false, 
            "before": null, 
            "config": null, 
            "defaults": false, 
            "force": false, 
            "host": "ios01", 
            "lines": null, 
            "match": "line", 
            "parents": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": null, 
            "provider": {
                "host": "ios01", 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "transport": "cli", 
                "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
            }, 
            "replace": "line", 
            "save": true, 
            "src": null, 
            "ssh_keyfile": null, 
            "timeout": 10, 
            "transport": "cli", 
            "use_ssl": true, 
            "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "validate_certs": true
        }
    }, 
    "msg": "unable to load backup configuration"
```
