### ISSUE TITLE
"Unable to load config: ConfigLoadError(severity: warning, bad_element: None, message: warning: statement not found)"junos_config: 

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible-modules-core#5040]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

junos_config
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 1c7890bf86) last updated 2016/09/26 10:42:34 (GMT +100)
  lib/ansible/modules/core: (devel cf243860ff) last updated 2016/09/26 10:42:39 (GMT +100)
  lib/ansible/modules/extras: (devel 7aab9cd93b) last updated 2016/09/26 10:42:41 (GMT +100)

```
##### STEPS TO REPRODUCE

``` yaml
- name: setup
  junos_config:
    lines:
      - "set system host-name {{ inventory_hostname }}"
      - "delete interfaces lo0"
    provider: "{{ netconf }}"
  register: test

```
##### ACTUAL RESULTS

``` yaml
TASK [test_junos_config : setup] ***********************************************
task path: /home/johnb/git/ansible-inc/test-junos/roles/test_junos_config/tests/netconf/multiple.yaml:4
Using module file /home/johnb/git/ansible-inc/ansible/lib/ansible/modules/core/network/junos/junos_config.py
<vsrx01> ESTABLISH LOCAL CONNECTION FOR USER: johnb
<vsrx01> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1474911943.93-57045240123737 `" && echo ansible-tmp-1474911943.93-57045240123737="` echo $HOME/.ansible/tmp/ansible-tmp-1474911943.93-57045240123737 `" ) && sleep 0'
<vsrx01> PUT /tmp/tmpN4Hbzl TO /home/johnb/.ansible/tmp/ansible-tmp-1474911943.93-57045240123737/junos_config.py
<vsrx01> EXEC /bin/sh -c 'chmod u+x /home/johnb/.ansible/tmp/ansible-tmp-1474911943.93-57045240123737/ /home/johnb/.ansible/tmp/ansible-tmp-1474911943.93-57045240123737/junos_config.py && sleep 0'
<vsrx01> EXEC /bin/sh -c 'python /home/johnb/.ansible/tmp/ansible-tmp-1474911943.93-57045240123737/junos_config.py; rm -rf "/home/johnb/.ansible/tmp/ansible-tmp-1474911943.93-57045240123737/" > /dev/null 2>&1 && sleep 0'
fatal: [vsrx01]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "auth_pass": null, 
            "authorize": false, 
            "backup": false, 
            "comment": "configured by junos_config", 
            "confirm": 0, 
            "host": "vsrx01", 
            "lines": [
                "set system host-name vsrx01", 
                "delete interfaces lo0"
            ], 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": null, 
            "provider": {
                "host": "vsrx01", 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "transport": "netconf", 
                "username": "ansible"
            }, 
            "replace": false, 
            "rollback": null, 
            "src": null, 
            "src_format": null, 
            "ssh_keyfile": null, 
            "timeout": 10, 
            "transport": "netconf", 
            "username": "ansible", 
            "zeroize": false
        }
    }, 
    "msg": "Unable to load config: ConfigLoadError(severity: warning, bad_element: None, message: warning: statement not found)"
}

```
