### ISSUE TITLE
mysql_user: db host wildcard 

### ISSUE THREAD

**Issue by bbaassssiiee** [ansible/ansible-modules-core#5053]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

mysql_user:
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /Users/bas/code/mvp/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

I want to set   host='%' in mysql_user module to be equivalent with:
grant all on _._ to 'my_user'@'%' identified by 'mypassword';

James seems to think a '*' should be used 
https://groups.google.com/forum/#!topic/ansible-project/FgZ0ReK3B-Q

Ansible inserts a user with host='*', but we need host='%' which does not work.
1396, \"Operation CREATE USER failed 
##### STEPS TO REPRODUCE
- name: install mysql
  yum: name=mysql state=present
- name: start mysql
  service: name=mysql state=started
- name: Create remote users
  mysql_user: name={{ user_name }} password={{ user_password }} host='%' state=present login_user=root login_password={{ mysql_root_password }}
##### EXPECTED RESULTS

A user exists that can connect remotely. select Host,User from user; Has a row with % in the host column (% is the SQL wildcard).
##### ACTUAL RESULTS

"msg": "(1396, \"Operation CREATE USER failed for 'my_writer'@'%'\"

**Comment by ansibot** [comment]
@Jmainguy ping, this issue is waiting for your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by nsteinmetz** [comment]
Hi,

Weird as it works for me with `10.235.8.%` with this code using the same version as you for Ansible.

```
- name: Create mysql users
  mysql_user:
    name: "{{ item.name }}"
    host: "{{ item.host|default('localhost') }}"
    password: "{{ item.password }}"
    priv: "{{ item.priv|default('*.*:USAGE') }}"
    login_host: "{{ mysql_login_host|default(omit) }}"
    login_port: "{{ mysql_login_port|default(omit) }}"
    config_file: "{{ mysql_config_file|default(omit) }}"
    state: present
  with_items: "{{ mysql_users }}"
  no_log: yes
```

It inherits from `host_vars/<environment>`:

```
mysql_users:
  - name: "{{ project_user }}"
    host: "{{ rds_host }}"
    password: "{{ lookup('password', project_passwd) }}"
    priv: "{{ cwf_i15n_user }}.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,INDEX,ALTER,CREATE TEMPORARY TABLES,LOCK TABLES"
```

Which inherits also from host vars (in `hosts/<environment>`):

```
[all:vars]
cwf_i15n_rds_host=10.235.8.%
```

Did not try with `%` only but maybe a yaml syntax instead of `key=value` may help ?

My 2 cents, hope it helps...
