### ISSUE TITLE
ignore this

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible-modules-core#5056]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

asa_command
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel eb33ed4219) last updated 2016/09/27 09:18:44 (GMT +100)
  lib/ansible/modules/core: (devel c03697c81e) last updated 2016/09/27 09:18:49 (GMT +100)
  lib/ansible/modules/extras: (devel 119bc466be) last updated 2016/09/27 09:18:51 (GMT +100)

```
##### SUMMARY

Running `asa_command` with an invalid `commands:` no longer bombs out
##### STEPS TO REPRODUCE

```
- name: run commands that include invalid command
  asa_command:
    commands:
      - show version
      - show foo
    provider: "{{ cli }}"
  register: result
  ignore_errors: yes
```
##### ACTUAL RESULTS

```
Task to report error (gracefully)
```
