### ISSUE TITLE
docker_image module: "Error searching for image .... [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

### ISSUE THREAD

**Issue by gtinjr** [ansible/ansible-modules-core#5085]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

docker_image
##### ANSIBLE VERSION

```
ansible 2.2.0
  config file = 
  configured module search path = Default w/o overrides
```
##### SUMMARY

Trying to a load docker image from a tar file into a secure private docker registry
##### STEPS TO REPRODUCE

```
- name: download marathon-lb image
  get_url: url={{marathonlb_artifact}} dest=/opt/marathon-lb-{{marathonlb.version}}.tar mode=0440

- name: Log into private registry and force re-authorization
  docker_login:
    registry={{registry.url}}
    username={{registry.username}}
    password={{registry.password}}
    email={{registry.email}}
    reauthorize=yes
- name: Load marathon-lb image in private registry
  docker_image:
    name={{marathonlb.image_name}}
    repository={{registry.url}}
    push=yes
    load_path=/opt/marathon-lb-{{marathonlb.version}}.tar
    docker_host=https://{{registry.url}}
    state=present
    debug=True
    api_version=1.23
    cacert_path=/usr/local/share/ca-certificates/docker-cert/devdockerCA.crt
    tls_verify=no
```

##### EXPECTED RESULTS

The image should have been loaded into the secure docker private registry
##### ACTUAL RESULTS

```
fatal: [mmesos-01]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "api_version": "1.23", 
            "archive_path": null, 
            "buildargs": null, 
            "cacert_path": "/usr/local/share/ca-certificates/docker-cert/devdockerCA.crt", 
            "cert_path": null, 
            "container_limits": null, 
            "debug": true, 
            "docker_host": "https://registry.technautas.net:5043", 
            "dockerfile": null, 
            "filter_logger": false, 
            "force": false, 
            "http_timeout": null, 
            "key_path": null, 
            "load_path": "/opt/marathon-lb-1.3.3.tar", 
            "name": "registry.technautas.net:5043/gtinjr/odroidc2-marathon-lb", 
            "nocache": "False", 
            "path": null, 
            "pull": true, 
            "push": true, 
            "repository": "registry.technautas.net:5043", 
            "rm": true, 
            "ssl_version": null, 
            "state": "present", 
            "tag": "latest", 
            "timeout": null, 
            "tls": null, 
            "tls_hostname": null, 
            "tls_verify": false, 
            "use_tls": "no"
        }, 
        "module_name": "docker_image"
    }, 
    "msg": "Error searching for image registry.technautas.net:5043/gtinjr/odroidc2-marathon-lb - [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)"
}
```

**Comment by ansibot** [comment]
@ansible ping, this issue is waiting for your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by chouseknecht** [comment]
@gtinjr, noticing you are passing `docker_host`, `cacert_path`, and `tls_verify` to the _docker_image_ module, but not to _docker_login_. It may be nothing, but curious why they're different. 

I'm wondering if the failure is between the module and the Docker daemon because of the connection parameters being sent. Are you using Docker Machine or Docker for Mac? If so, can you provide the result of `env | grep DOCKER`. Are the environment values different than what you're passing to the _docker_image_ module?

In fact, it looks as though your `docker_host` and registry URL are the same. Is that correct?

The way I test the module is by doing the load in one step, and then tagging and pushing in a second step as follows:

```
- name: Load image from archive
  docker_image:
    name: mysinatra
    tag: v1
    load_path: my_sinatra.tar
  register: output
```

```
- name: Tag and push sinatra to local registry
  docker_image:
    name: mysinatra
    tag: v1
    repository: "{{ registry_host }}:5000/dcoppenhagan/mysinatra"
    push: yes
  register: output
```

That mirrors how you would do it with the Docker CLI as well. You would load the image, then tag it into the repository, and then push it.

I think you could combine the two by doing the following:

```
docker_image:
  name: odroidc2-marathon-lb
  load_path: /opt/marathon-lb-{{marathonlb.version}}.tar
  repository: registry.technautas.net:5043/gtinjr/odroidc2-marathon-lb
  tag: latest
  push: yes
```

And, I'm fairly certain you don't need to put the protocol (https) in the `repository` value.
