### ISSUE TITLE
eos_command: unable to load response from device

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible-modules-core#5092]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

eos_command
##### ANSIBLE VERSION

```
ansible --version
ansible 2.2.0 (devel c5b4369ae7) last updated 2016/09/29 09:04:31 (GMT +100)
  lib/ansible/modules/core: (devel 537a7eb924) last updated 2016/09/29 09:04:36 (GMT +100)
  lib/ansible/modules/extras: (devel a58e1d59c0) last updated 2016/09/29 09:04:38 (GMT +100)
  config file = /home/johnb/.ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

This may be a different issue to last time, looks like I'm getting some response back.
##### STEPS TO REPRODUCE

``` yaml
- name: test lt operator
  eos_command:
    commands:
      - show version
      - show interfaces Management1 | json
    wait_for:
      - "result[1].interfaces.Management1.mtu lt 1600"
    provider: "{{ cli }}"
  register: result

```
##### ACTUAL RESULTS

``` yaml

TASK [test_eos_command : test lt operator] *************************************
task path: /home/johnb/git/ansible-inc/test-cleanup/roles/test_eos_command/tests/cli/lessthan.yaml:4
Using module file /home/johnb/git/ansible-inc/ansible/lib/ansible/modules/core/network/eos/eos_command.py
<veos01> ESTABLISH LOCAL CONNECTION FOR USER: johnb
<veos01> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1475164803.47-23419549866980 `" && echo ansible-tmp-1475164803.47-23419549866980="` echo $HOME/.ansible/tmp/ansible-tmp-1475164803.47-23419549866980 `" ) && sleep 0'
<veos01> PUT /tmp/tmpS3uu0X TO /home/johnb/.ansible/tmp/ansible-tmp-1475164803.47-23419549866980/eos_command.py
<veos01> EXEC /bin/sh -c 'chmod u+x /home/johnb/.ansible/tmp/ansible-tmp-1475164803.47-23419549866980/ /home/johnb/.ansible/tmp/ansible-tmp-1475164803.47-23419549866980/eos_command.py && sleep 0'
<veos01> EXEC /bin/sh -c 'python /home/johnb/.ansible/tmp/ansible-tmp-1475164803.47-23419549866980/eos_command.py; rm -rf "/home/johnb/.ansible/tmp/ansible-tmp-1475164803.47-23419549866980/" > /dev/null 2>&1 && sleep 0'
fatal: [veos01]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "auth_pass": null, 
            "authorize": true, 
            "commands": [
                "show version", 
                "show interfaces Management1 | json"
            ], 
            "host": "veos01", 
            "interval": 1, 
            "match": "all", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": null, 
            "provider": {
                "authorize": true, 
                "host": "veos01", 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "transport": "cli", 
                "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
            }, 
            "retries": 10, 
            "ssh_keyfile": null, 
            "timeout": 10, 
            "transport": "cli", 
            "use_ssl": true, 
            "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "validate_certs": true, 
            "wait_for": [
                "result[1].interfaces.Management1.mtu lt 1600"
            ]
        }, 
        "module_name": "eos_command"
    }, 
    "msg": "unable to load response from device", 
    "response": "show version\nArista vEOS\nHardware version:    \nSerial number:       \nSystem MAC address:  0050.564a.009e\n\nSoftware image version: 4.15.4F\nArchitecture:           i386\nInternal build version: 4.15.4F-2923910.4154F\nInternal build ID:      d8a3c846-c735-4766-93cd-82bb7427da51\n\nUptime:                 13 weeks, 3 days, 21 hours and 43 minutes\nTotal memory:           1897592 kB\nFree memory:            209780 kB\n\nfoo#show interfaces Management1 | json\n{\n    \"interfaces\": {\n        \"Management1\": {\n            \"lastStatusChangeTimestamp\": 1466965066.8416328, \n            \"name\": \"Management1\", \n            \"interfaceStatus\": \"connected\", \n            \"autoNegotiate\": \"success\", \n            \"burnedInAddress\": \"00:50:56:bc:1d:fd\", \n            \"loopbackMode\": \"loopbackNone\", \n            \"interfaceStatistics\": {\n                \"inBitsRate\": 2247.995639109516, \n                \"inPktsRate\": 0.0, \n                \"outBitsRate\": 5790.649372166647, \n                \"updateInterval\": 300.0, \n                \"outPktsRate\": 2.6539536623065527\n            }, \n            \"mtu\": 1500, \n            \"hardware\": \"ethernet\", \n            \"duplex\": \"duplexFull\", \n            \"bandwidth\": 1000000000, \n            \"forwardingModel\": \"routed\", \n            \"lineProtocolStatus\": \"up\", \n            \"interfaceCounters\": {\n                \"outBroadcastPkts\": 0, \n                \"linkStatusChanges\": 3, \n                \"totalOutErrors\": 0, \n                \"inMulticastPkts\": 0, \n                \"counterRefreshTime\": 1475164806.976286, \n                \"inBroadcastPkts\": 0, \n                \"outputErrorsDetail\": {\n                    \"deferredTransmissions\": 0, \n                    \"txPause\": 0, \n                    \"collisions\": 0, \n                    \"lateCollisions\": 0\n                }, \n                \"inOctets\": 400367950, \n                \"outDiscards\": 0, \n                \"outOctets\": 118902991, \n                \"inUcastPkts\": 0, \n                \"inputErrorsDetail\": {\n                    \"runtFrames\": 0, \n                    \"rxPause\": 0, \n                    \"fcsErrors\": 0, \n                    \"alignmentErrors\": 0, \n                    \"giantFrames\": 0, \n                    \"symbolErrors\": 0\n                }, \n                \"outUcastPkts\": 653260, \n                \"outMulticastPkts\": 0, \n                \"totalInErrors\": 0, \n                \"inDiscards\": 0\n            }, \n            \"interfaceAddress\": [\n                {\n                    \"secondaryIpsOrderedList\": [], \n                    \"broadcastAddress\": \"255.255.255.255\", \n                    \"secondaryIps\": {}, \n                    \"primaryIp\": {\n                        \"maskLen\": 24, \n                        \"address\": \"172.26.4.24\"\n                    }, \n                    \"virtualIp\": {\n                        \"maskLen\": 0, \n                        \"address\": \"0.0.0.0\"\n                    }\n                }\n            ], \n            \"physicalAddress\": \"00:50:56:bc:1d:fd\", \n            \"description\": \"\"\n        }\n    }\n}"
}


```
