### ISSUE TITLE
nxos_config:  'copy running-config startup-config  | xml '\n\n\nCmd exec error.\n", nxos_config: 

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible-modules-core#5094]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

nxos_config
##### ANSIBLE VERSION

```
ansible --version
ansible 2.2.0 (devel c5b4369ae7) last updated 2016/09/29 09:04:31 (GMT +100)
  lib/ansible/modules/core: (devel 537a7eb924) last updated 2016/09/29 09:04:36 (GMT +100)
  lib/ansible/modules/extras: (devel a58e1d59c0) last updated 2016/09/29 09:04:38 (GMT +100)
  config file = /home/johnb/.ansible.cfg

```
##### SUMMARY

I'm sure this was working...
##### STEPS TO REPRODUCE

``` yaml
- name: save config
  nxos_config:
    save: true
    provider: "{{ nxapi }}"
  register: result
```
##### ACTUAL RESULTS

``` yaml
TASK [test_nxos_config : save config] ******************************************
task path: /home/johnb/git/ansible-inc/test-cleanup/roles/test_nxos_config/tests/nxapi/save.yaml:15
Using module file /home/johnb/git/ansible-inc/ansible/lib/ansible/modules/core/network/nxos/nxos_config.py
<nxos01> ESTABLISH LOCAL CONNECTION FOR USER: johnb
<nxos01> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1475167263.13-259006155680305 `" && echo ansible-tmp-1475167263.13-259006155680305="` echo $HOME/.ansible/tmp/ansible-tmp-1475167263.13-259006155680305 `" ) && sleep 0'
<nxos01> PUT /tmp/tmpBbDf8w TO /home/johnb/.ansible/tmp/ansible-tmp-1475167263.13-259006155680305/nxos_config.py
<nxos01> EXEC /bin/sh -c 'chmod u+x /home/johnb/.ansible/tmp/ansible-tmp-1475167263.13-259006155680305/ /home/johnb/.ansible/tmp/ansible-tmp-1475167263.13-259006155680305/nxos_config.py && sleep 0'
<nxos01> EXEC /bin/sh -c 'python /home/johnb/.ansible/tmp/ansible-tmp-1475167263.13-259006155680305/nxos_config.py; rm -rf "/home/johnb/.ansible/tmp/ansible-tmp-1475167263.13-259006155680305/" > /dev/null 2>&1 && sleep 0'
fatal: [nxos01]: FAILED! => {
    "changed": false, 
    "clierror": "Syntax error while parsing 'copy running-config startup-config  | xml '\n\n\nCmd exec error.\n", 
    "code": "400", 
    "failed": true, 
    "input": "copy running-config startup-config", 
    "invocation": {
        "module_args": {
            "after": null, 
            "auth_pass": null, 
            "authorize": false, 
            "backup": false, 
            "before": null, 
            "config": null, 
            "defaults": false, 
            "force": false, 
            "host": "nxos01", 
            "lines": null, 
            "match": "line", 
            "parents": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": null, 
            "provider": {
                "host": "nxos01", 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "transport": "nxapi", 
                "use_ssl": false, 
                "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
            }, 
            "replace": "line", 
            "save": true, 
            "src": null, 
            "ssh_keyfile": null, 
            "timeout": 10, 
            "transport": "nxapi", 
            "use_ssl": false, 
            "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "validate_certs": true
        }
    }, 
    "msg": "Input CLI command error", 
    "output": {
        "clierror": "Syntax error while parsing 'copy running-config startup-config  | xml '\n\n\nCmd exec error.\n", 
        "code": "400", 
        "input": "copy running-config startup-config", 
        "msg": "Input CLI command error"
    }, 
    "url": "http://nxos01:80/ins"
}

```
