### ISSUE TITLE
YAML support not working correctly

### ISSUE THREAD

**Issue by joewoz** [ansible/ansible-modules-core#5112]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

ansible-modules-core/cloud/amazon/cloudformation
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 29fda4be1e) last updated 2016/09/16 18:26:39 (GMT +000)
  lib/ansible/modules/core: (detached HEAD 2e1e3562b9) last updated 2016/09/16 18:26:41 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD 9b5c64e240) last updated 2016/09/16 18:26:42 (GMT +000)
  config file = /opt/ansible_dev/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

n/a
##### OS / ENVIRONMENT

Amazon Linux
##### SUMMARY

When using the CloudFormation template in YAML format, the scripts are encountering an error. It appears that line 277 of the 'cloudformation.py' module attempts to parse the template as valid YAML with the standard yaml library and then convert that into JSON.  This is completely unnecessary as the CloudFormation engine will throw back an error if there is some kind of formatting issue. In fact, attempting to convert the YAML file back to JSON will almost always break the format in some way.
##### WORKAROUND:

Commenting out lines 276 and 277 allows the module to work fine using a YAML formatted template.
##### STEPS TO REPRODUCE

```
--- Sample playbook ---

---
- hosts: localhost
  tasks:
  - name: Build EC2 windows instance
    cloudformation:
      stack_name: "ansibleTestInstance"
      state: "present"
      region: "us-east-1"
      disable_rollback: true
      template: "files/generic_cf_template.yml"
      template_format: "yaml"
      template_parameters:
        InstanceType: "t2.medium"
        KeyName: "your-master-key"
        RDPSecurityGroup: "sg-12345678"
        DestinationSubnet: "subnet-12345678"
        WindowsAMI: "ami-ee7805f9"
        InstanceIAMRoleName: "test_iam_role"
      tags:
        Name: "ansible-test-instance"

--- Sample CloudFormation.yml file: ---
AWSTemplateFormatVersion: '2010-09-09'
Description: >
  This template creates Amazon EC2 Windows instance and related resources. You will
  be billed for the AWS resources used if you create a stack from this template.
Outputs:
  EC2InstanceId:
    Description: The ID of the instance created.
    Value: !Ref WindowsServer
Parameters:
  InstanceType:
    ConstraintDescription: Must be a valid EC2 instance type.
    Default: t2.medium
    Description: Amazon EC2 instance type
    Type: String
  KeyName:
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
    Description: Name of an existing EC2 KeyPair
    Type: AWS::EC2::KeyPair::KeyName
  RDPSecurityGroup:
    Description: Select the security group that will allow RDP connections to this machine.
    Type: AWS::EC2::SecurityGroup::Id
  DestinationSubnet:
    Description: Select the subnet where to place the new instance.
    Type: AWS::EC2::Subnet::Id
  WindowsAMI:
    Description: Enter the id of the Windows AMI you wish to use.
    Default: ami-ee7805f9
    Type: AWS::EC2::Image::Id
  InstanceIAMRoleName:
    Description: Enter the name of the IAM Role you wish to use for this instance. (NOTE this is just the role name, not an ARN)
    Type: String
Resources:
  WindowsServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId:
        Ref: WindowsAMI
      InstanceType:
        Ref: InstanceType
      KeyName:
        Ref: KeyName
      SubnetId:
        Ref: DestinationSubnet
      SecurityGroupIds:
      - Ref: RDPSecurityGroup
      IamInstanceProfile:
        Ref: InstanceIAMRoleName
```
