### ISSUE TITLE
get_url does not change mode when checksum matches

### ISSUE THREAD

**Issue by sfilipov** [ansible/ansible-modules-core#5141]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

get_url
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = 
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

None
##### OS / ENVIRONMENT

Host: Ubuntu 16.04
Managed: Ubuntu 14.04
##### SUMMARY

`get_url` does not change mode when the checksum of the file matches. If the file needs to be downloaded due to the checksum not matching, then after download, the correct mode will be set.
##### STEPS TO REPRODUCE
1. Define a `get_url` task where destination is a file and set the checksum to the sha256 of the file. After the first run, the file will be downloaded and the checksum will match.
2. Now add a `mode` argument to `get_url` such that it differs from the one on the downloaded file and Ansible needs to make a change.
3. Rerun task.

```
- name: Download file
  get_url:
    url: https://xxxxxxxxxxx
    dest: /usr/local/bin/some_executable
    checksum: "sha256:somehash"
  become: yes

- name: Mode needs to be changed
  get_url:
    url: https://xxxxxxxxxxx
    dest: /usr/local/bin/some_executable
    checksum: "sha256:somehash"
    mode: 0755
  become: yes
```
##### EXPECTED RESULTS

Mode is changed on second run to match one described in task -- task is changed
##### ACTUAL RESULTS

Changing mode is short circuited due to checksum match -- task OKs
