### ISSUE TITLE
User module does not add groups

### ISSUE THREAD

**Issue by diego-treitos** [ansible/ansible-modules-core#5163]
##### ISSUE TYPE
- Feature Idea
- ~~Bug Report~~
##### COMPONENT NAME

user module
##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

Linux
##### SUMMARY

The `groups`argument for the `user` module is not parsed properly in this [line](https://github.com/diego-treitos/ansible-modules-core/blob/devel/system/user.py#L521).
The final group name has the format `'sftpjail']`. 
Error example:

```
fatal: [anstest]: FAILED! => {"changed": false, "failed": true, "msg": "Group  'sftpjail'] does not exist"
```
##### STEPS TO REPRODUCE

Just use the `user` module with the `groups` argument adding at least 2 groups (although it may fail with only 1).

```
- name: Create os user
  user:
      name: john
      password: smith
      shell: /usr/bin/rssh
      home: /path/to/jail
      group: john
      groups:
        - sshgroup
        - sftpjail
```
##### EXPECTED RESULTS

User created and added to groups
##### ACTUAL RESULTS

```
fatal: [anstest]: FAILED! => {"changed": false, "failed": true, "msg": "Group  'sftpjail'] does not exist"
```
##### COMMENTS

I think this is an important regression as it affects an important core module. It would be great to have a fix asap.
