### ISSUE TITLE
gce_pd: libcloud with GCE support (0.17.0+) is required for this module

### ISSUE THREAD

**Issue by basictheprogram** [ansible/ansible-modules-core#5196]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

gce_pd
##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.3.0 (devel 9265016b95) last updated 2016/10/07 13:59:01 (GMT -500)
  lib/ansible/modules/core: (detached HEAD b4f6a25195) last updated 2016/10/06 13:07:51 (GMT -500)
  lib/ansible/modules/extras: (detached HEAD 118fe8283e) last updated 2016/10/06 13:07:51 (GMT -500)
  config file = /Users/tanner/projects/ansible.git/playbooks.git/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

Control host OS X 10.11.6
##### SUMMARY

Attempting to use the  gce_pd module and getting an error message that my installed libcloud is too old.
##### STEPS TO REPRODUCE

```
- name: add disk space
  gce_pd:
    name: default
    project_id: "{{ project_id }}"
    credentials_file: "{{ credentials_file }}"
    service_account_email: "{{ service_account_email }}"
    size_gb: "{{ size_gb }}"
```

```
$ pip freeze | grep -i cloud
apache-libcloud==1.2.1
gcloud==0.18.3
```

##### EXPECTED RESULTS

A "{{ size_gb }}" size disk would be added to my GCE virtual machine.
##### ACTUAL RESULTS

```
FAILED! => {"changed": false, "failed": true, "msg": "libcloud with GCE support (0.17.0+) is required for this module"}
```
