### ISSUE TITLE
Exception when using nxos_snmp_community

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ansible/ansible-modules-core#5214]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

nxos_snmp_community
##### ANSIBLE VERSION

```
ansible 2.3.0~git20161010.03765ba
or
ansible 2.2.0.0-0.1.rc1
(ansible 2.1.2.0-1 does not include the module)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

inventory   = ./hosts
gathering = explicit
roles_path = /home/actionmystique/Program-Files/Ubuntu/Ansible/Roles/roles
private_role_vars = yes
log_path = /var/log/ansible.log
fact_caching = redis
fact_caching_timeout = 86400
retry_files_enabled = False
##### OS / ENVIRONMENT
- host: Ubuntu 16.04 4.4.0
- target: **NX-OSv 7.3(0)D1(1)**
##### SUMMARY

cf. title
##### STEPS TO REPRODUCE

**Inventory ./hosts**:

```
[all:vars]
nms_mgt_ip_address=172.21.100.1
[spines]
NX_OSv_Spine_11 ansible_host=172.21.100.11 
NX_OSv_Spine_12 ansible_host=172.21.100.12 
```

Structure passed as "**provider**": connections.ssh
Defined in group_vars/nx_osv/connections.yml and a symbolic link in roles/nxos_snmp/defaults points to nx_osv

```
connections
...
        nxapi:
          transport: nxapi
          host: "{{ ansible_host }}"
          # ansible_port
          port: "{{ http.port }}"
          # ansible_user
          username: admin
          password: xxxxxxxx
          # enable_secret_password
          auth_pass: xxxxxxxx
          # http or https
          use_ssl: no
          validate_certs: "{{ https.validate_certs }}"
```

**Role**: nxos_snmp:

```
- include_vars: "../defaults/{{ os_family }}/connections.yml"
...
- name: Configuring the ACL for authorized NMS in new SNMPv2c
  nxos_config:
        provider: "{{ connections.nxapi }}"
        parents:
          - "ip access-list authorized-snmp-nms"
        lines:
          - "permit ip host {{ nms_mgt_ip_address }} host {{ ansible_host }} log"
  register: result

- name: Configuring RO/RW community string in new IPv4/SNMPv2c
  nxos_snmp_community:
        provider: "{{ connections.nxapi }}"
        community: whatever
        access: rw
        acl: authorized-snmp-nms
        state: present
  register: result
```

**Playbook**:

```
- name: Configuring SNMP on NX-OS/NX-OSv
  hosts:
    - nx_osv
  roles:
    - nxos_snmp
```
##### EXPECTED RESULTS

The community should be configured without an exception.
##### ACTUAL RESULTS

```
TASK [nxos_snmp : Configuring the ACL for authorized NMS in new SNMPv2c] *******
changed: [NX_OSv_Spine_12] => {"changed": true, "updates": ["ip access-list authorized-snmp-nms", "permit ip host 172.21.100.1 host 172.21.100.12 log"], "warnings": []}
changed: [NX_OSv_Spine_11] => {"changed": true, "updates": ["ip access-list authorized-snmp-nms", "permit ip host 172.21.100.1 host 172.21.100.11 log"], "warnings": []}
...
TASK [nxos_snmp : Configuring RO/RW community string in new IPv4/SNMPv2c] ******
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: string indices must be integers
fatal: [NX_OSv_Spine_11]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_55m6Ao/ansible_module_nxos_snmp_community.py\", line 499, in <module>\n    main()\n  File \"/tmp/ansible_55m6Ao/ansible_module_nxos_snmp_community.py\", line 458, in main\n    existing = get_snmp_community(module, community)\n  File \"/tmp/ansible_55m6Ao/ansible_module_nxos_snmp_community.py\", line 389, in get_snmp_community\n    community_table = data['TABLE_snmp_community']['ROW_snmp_community']\nTypeError: string indices must be integers\n", "module_stdout": "", "msg": "MODULE FAILURE"}
```

No issue when configuring through the CLI:

```
NX_OSv_Spine_11(config)# snmp-server community whatever rw
NX_OSv_Spine_11(config)# snmp-server community whatever use-ipv4acl authorized-snmp-nms 
NX_OSv_Spine_11(config)#
```

**Comment by jean-christophe-manciot** [comment]
No issue configuring the same community through nxos_config:

```
- name: Configuring RO/RW community string in new IPv4/SNMPv{{ snmp.new_version }}
  nxos_config:
        provider: "{{ connections.nxapi }}"
        lines:
          - "snmp-server community whatever rw"
          - "snmp-server community whatever use-ipv4acl authorized-snmp-nms"
  register: result

```

leading to:

```
TASK [nxos_snmp : Configuring RO/RW community string in new IPv4/SNMPv2c] ******
changed: [NX_OSv_Spine_11] => {"changed": true, "updates": ["snmp-server community xxxxxxxx rw", "snmp-server community xxxxxxxx use-ipv4acl authorized-snmp-nms"], "warnings": []}
changed: [NX_OSv_Spine_12] => {"changed": true, "updates": ["snmp-server community xxxxxxxx rw", "snmp-server community xxxxxxxx use-ipv4acl authorized-snmp-nms"], "warnings": []}

```

**Comment by ansibot** [comment]
@jedelman8, @GGabriele, @privateip, @gundalow, ping. This issue is waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by GGabriele** [comment]
Hey @jean-christophe-manciot , can you please test this on a physical 5K/7K? This work on 9K, but it seems NXOSv doesn't support structured data for `show snmp community`.  We can work on a longer term fix to support NXOSv, but all testing and bugs need to be done against physical devices.

**Comment by jean-christophe-manciot** [comment]
Hello, @GGabriele you can consider NX-OSv equivalent to 7k as far as most non ASIC-dependant features are concerned. 
Also, if you dismiss all virtual appliances, you'll soon be facing a wall: I'm sure NFV rings a bell.

**Comment by jean-christophe-manciot** [comment]
It's very easy to get one NX-OSv for yourself through [VIRL](http://virl.cisco.com/getvirl/) so you can conduct your own tests. You'll also get all other Cisco's virtual appliances.

**Comment by ansibot** [comment]
@jedelman8, @GGabriele, @privateip, @gundalow, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@jedelman8, @GGabriele, @privateip, @gundalow, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by GGabriele** [comment]
We can close this as #5450 has been merged.

**Comment by jean-christophe-manciot** [comment]
@GGabriele 
With ansible **2.3.0 commit 20161111.3f785ee**, it is still not functioning correctly:

```
- name: Configuring RO/RW community string & allowed NMS in new IPv4/SNMPv{{ snmp.new_version }}
  nxos_snmp_community:
        provider: "{{ connections.nxapi }}"
        community: "{{ snmp.ssh.community }}"
        access: "{{ snmp.community_type }}"
        acl: "{{ snmp.acl_name }}"
        state: present
  when: snmp.ip_version == 'ip'
  register: result
```

leads to:

```
TASK [nxos_snmp : Configuring RO/RW community string & allowed NMS in new IPv4/SNMPv2c] **********************************************************************************
task path: /home/actionmystique/Program-Files/Ubuntu/Ansible/Roles/roles/nxos_snmp/tasks/2c.yml:53
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/core/network/nxos/nxos_snmp_community.py
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/core/network/nxos/nxos_snmp_community.py
<172.21.100.11> ESTABLISH LOCAL CONNECTION FOR USER: root
<172.21.100.11> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1478888079.99-211115341228348 `" && echo ansible-tmp-1478888079.99-211115341228348="` echo $HOME/.ansible/tmp/ansible-tmp-1478888079.99-211115341228348 `" ) && sleep 0'
<172.21.100.12> ESTABLISH LOCAL CONNECTION FOR USER: root
<172.21.100.12> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1478888079.99-22908292694190 `" && echo ansible-tmp-1478888079.99-22908292694190="` echo $HOME/.ansible/tmp/ansible-tmp-1478888079.99-22908292694190 `" ) && sleep 0'
<172.21.100.12> PUT /tmp/tmpsKxig8 TO /root/.ansible/tmp/ansible-tmp-1478888079.99-22908292694190/nxos_snmp_community.py
<172.21.100.11> PUT /tmp/tmpvTuXnY TO /root/.ansible/tmp/ansible-tmp-1478888079.99-211115341228348/nxos_snmp_community.py
<172.21.100.12> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1478888079.99-22908292694190/ /root/.ansible/tmp/ansible-tmp-1478888079.99-22908292694190/nxos_snmp_community.py && sleep 0'
<172.21.100.11> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1478888079.99-211115341228348/ /root/.ansible/tmp/ansible-tmp-1478888079.99-211115341228348/nxos_snmp_community.py && sleep 0'
<172.21.100.12> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1478888079.99-22908292694190/nxos_snmp_community.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1478888079.99-22908292694190/" > /dev/null 2>&1 && sleep 0'
<172.21.100.11> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1478888079.99-211115341228348/nxos_snmp_community.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1478888079.99-211115341228348/" > /dev/null 2>&1 && sleep 0'
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_iL6vdm/ansible_module_nxos_snmp_community.py", line 499, in <module>
    main()
  File "/tmp/ansible_iL6vdm/ansible_module_nxos_snmp_community.py", line 458, in main
    existing = get_snmp_community(module, community)
  File "/tmp/ansible_iL6vdm/ansible_module_nxos_snmp_community.py", line 389, in get_snmp_community
    community_table = data['TABLE_snmp_community']['ROW_snmp_community']
TypeError: string indices must be integers

fatal: [NX_OSv_Spine_11]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_name": "nxos_snmp_community"
    }, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_iL6vdm/ansible_module_nxos_snmp_community.py\", line 499, in <module>\n    main()\n  File \"/tmp/ansible_iL6vdm/ansible_module_nxos_snmp_community.py\", line 458, in main\n    existing = get_snmp_community(module, community)\n  File \"/tmp/ansible_iL6vdm/ansible_module_nxos_snmp_community.py\", line 389, in get_snmp_community\n    community_table = data['TABLE_snmp_community']['ROW_snmp_community']\nTypeError: string indices must be integers\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE"
```

Although **using nxos_config works fine** on the same target:

```
- name: Configuring RO/RW community string & allowed NMS in new IPv4/SNMPv{{ snmp.new_version }} with nxos_config
  nxos_config:
        provider: "{{ connections.nxapi }}"
        lines:
          - "snmp-server community {{ snmp.ssh.community }} group {{ snmp.ssh.group_name }}"
          - "snmp-server community {{ snmp.ssh.community }} use-ipv4acl {{ snmp.acl_name }}"
  when: snmp.ip_version == 'ip'
  register: result
```

leads to:

```
TASK [nxos_snmp : Configuring RO/RW community string & allowed NMS in new IPv4/SNMPv2c with nxos_config] *****************************************************************
changed: [NX_OSv_Spine_11] => {"changed": true, "updates": ["snmp-server community xxxxxxxx group network-admin", "snmp-server community xxxxxxxx use-ipv4acl authorized-snmp-nms"], "warnings": []}
```
