### ISSUE TITLE
Timeout: Cannot save running-config with nxos_command or save: yes in nxos_config

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ansible/ansible-modules-core#5215]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

nxos_command
nxos_config
##### ANSIBLE VERSION

```
ansible 2.3.0~git20161010.03765ba
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

inventory   = ./hosts
gathering = explicit
roles_path = /home/actionmystique/Program-Files/Ubuntu/Ansible/Roles/roles
private_role_vars = yes
log_path = /var/log/ansible.log
fact_caching = redis
fact_caching_timeout = 86400
retry_files_enabled = False
##### OS / ENVIRONMENT
- host: Ubuntu 16.04 4.4.0
- target: **NX-OSv 7.3(0)D1(1)**
##### SUMMARY

cf. title
##### STEPS TO REPRODUCE

**Inventory ./hosts**:

```
[all:vars]
nms_mgt_ip_address=172.21.100.1
[spines]
NX_OSv_Spine_11 ansible_host=172.21.100.11 
NX_OSv_Spine_12 ansible_host=172.21.100.12 
```

Structure passed as "**provider**": connections.ssh
Defined in group_vars/nx_osv/connections.yml and a symbolic link in roles/nxos_snmp/defaults points to nx_osv

```
connections
...
        nxapi:
          transport: nxapi
          host: "{{ ansible_host }}"
          # ansible_port
          port: "{{ http.port }}"
          # ansible_user
          username: admin
          password: xxxxxxxx
          # enable_secret_password
          auth_pass: xxxxxxxx
          # http or https
          use_ssl: no
          validate_certs: "{{ https.validate_certs }}"
```

**Role**: nxos_snmp:

```
- include_vars: "../defaults/{{ os_family }}/connections.yml"
...
- name: Saving the running-config
  nxos_command:
        provider: "{{ connections.nxapi }}"
        commands:
          - "copy running-config startup-config"
  register: result
```

**Playbook**:

```
- name: Configuring SNMP on NX-OS/NX-OSv
  hosts:
    - nx_osv
  roles:
    - nxos_snmp
```
##### EXPECTED RESULTS

We should be able to save the modifications.
##### ACTUAL RESULTS

```
TASK [nxos_snmp : Saving the running-config] ***********************************
fatal: [NX_OSv_Spine_12]: FAILED! => {"changed": false, "clierror": "Syntax error while parsing 'copy running-config startup-config  | xml '\n\n\nCmd exec error.\n", "code": "400", "failed": true, "input": "copy running-config startup-config", "msg": "Input CLI command error", "output": {"clierror": "Syntax error while parsing 'copy running-config startup-config  | xml '\n\n\nCmd exec error.\n", "code": "400", "input": "copy running-config startup-config", "msg": "Input CLI command error"}, "url": "http://172.21.100.12:8080/ins"}
```

No issue when configuring through the CLI:

```
NX_OSv_Spine_12# copy running-config startup-config 
[########################################] 100%
Copy complete.
NX_OSv_Spine_12# show startup-config

!Command: show startup-config
!Time: Mon Oct 10 18:12:08 2016
!Startup config saved at: Mon Oct 10 18:01:55 2016

version 7.3(0)D1(1)
power redundancy-mode redundant

```

**Comment by jean-christophe-manciot** [comment]
Using `save: yes` in `nxos_config` leads to no error during execution, but afterwards:

```
NX_OSv_Spine_11# show startup-config 
2016 Oct 10 18:11:45 NX_OSv_Spine_11 %PSS-2-PSS_INVALID_SIZE: ngoam: database /var/sysmgr/startup-cfg/bin/ngoam_config (.pss) has invalid size 0 (block size -1)
```

**Comment by ansibot** [comment]
@jedelman8, @GGabriele, @privateip, @gundalow, ping. This issue is waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jean-christophe-manciot** [comment]
A workaround is to replace nxos_command module call by nxos_config.

**Comment by jean-christophe-manciot** [comment]
The previous workaround is not possible anymore with ansible 2.3.0~git20161011.6be09ee:

```
- name: Saving the running-config
  nxos_config:
        provider: "{{ connections.nxapi }}"
        commands:
          - "copy running-config startup-config"
  register: result
```

leads to:

```
TASK [nxos_snmp : Saving the running-config] ***********************************
fatal: [NX_OSv_Spine_12]: FAILED! => {"changed": false, "clierror": "ERROR: Copy r s / partial mem write in progress. Please try after some time.\n", "code": "400", "failed": true, "input": "rollback running-config checkpoint ansible_1476288874", "msg": "CLI execution error", "output": {"clierror": "ERROR: Copy r s / partial mem write in progress. Please try after some time.\n", "code": "400", "input": "rollback running-config checkpoint ansible_1476288874", "msg": "CLI execution error"}, "url": "http://172.21.100.12:8080/ins"}
```

It is barely possible to perform the same task from the CLI:

```
copy running-config startup-config 
[#################                       ]  42%2016 Oct 12 16:26:15 NX_OSv_Spine_12 %PSS-2-PSS_ERROR: Failed to add pages to director, PSS_MALLOC failed, errno 12 (Cannot allocate memory)
[##################                      ]  43%2016 Oct 12 16:26:15 NX_OSv_Spine_12 %PSS-2-PSS_ERROR: Page director has non zero number of pages
[########################################]  100%
Copy complete.
```

It took a time too long for ansible to complete.
However, I suspect that the multiple nxos_config which have run previously are responsible for this situation, because throwing more RAM does not remove the error.
