### ISSUE TITLE
"Unsupported parameter for module: type" although it is defined in the documentation and is necessary

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ansible/ansible-modules-core#5216]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

nxos_snmp_host
##### ANSIBLE VERSION

```
ansible 2.3.0~git20161010.03765ba
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

inventory   = ./hosts
gathering = explicit
roles_path = /home/actionmystique/Program-Files/Ubuntu/Ansible/Roles/roles
private_role_vars = yes
log_path = /var/log/ansible.log
fact_caching = redis
fact_caching_timeout = 86400
retry_files_enabled = False
##### OS / ENVIRONMENT
- host: Ubuntu 16.04 4.4.0
- target: **NX-OSv 7.3(0)D1(1)**
##### SUMMARY

cf. title. Using `type: traps` or `type: trap` leads to the same issue.
##### STEPS TO REPRODUCE

**Inventory ./hosts**:

```
[all:vars]
nms_mgt_ip_address=172.21.100.1
[spines]
NX_OSv_Spine_11 ansible_host=172.21.100.11 
NX_OSv_Spine_12 ansible_host=172.21.100.12 
```

Structure passed as "**provider**": connections.ssh
Defined in group_vars/nx_osv/connections.yml and a symbolic link in roles/nxos_snmp/defaults points to nx_osv

```
connections
...
        nxapi:
          transport: nxapi
          host: "{{ ansible_host }}"
          # ansible_port
          port: "{{ http.port }}"
          # ansible_user
          username: admin
          password: xxxxxxxx
          # enable_secret_password
          auth_pass: xxxxxxxx
          # http or https
          use_ssl: no
          validate_certs: "{{ https.validate_certs }}"
```

**Role**: nxos_snmp:

```
- include_vars: "../defaults/{{ os_family }}/connections.yml"
...
- name: Configuring the allowed NMS for that community in new SNMPv2c
  nxos_snmp_host:
        provider: "{{ connections.nxapi }}"
        community: whatever
        snmp_host: "{{ nms_mgt_ip_address }}"
        type: traps
        udp: 162
        version: v2c
        state: present
    register: result
```

**Playbook**:

```
- name: Configuring SNMP on NX-OS/NX-OSv
  hosts:
    - nx_osv
  roles:
    - nxos_snmp
```
##### EXPECTED RESULTS

The type parameter - traps or informs - is necessary.. The [documentation](http://docs.ansible.com/ansible/nxos_snmp_host_module.html) has forgotten the trailing s.
##### ACTUAL RESULTS

```
TASK [nxos_snmp : Configuring the allowed NMS for that community in new SNMPv2c] ***
fatal: [NX_OSv_Spine_12]: FAILED! => {"changed": false, "failed": true, "msg": "unsupported parameter for module: type"}
```

No issue when configuring through the CLI:

```
NX_OSv_Spine_11(config)# snmp-server host 172.21.100.1 traps version 2c whatever udp-port 162
NX_OSv_Spine_11(config)#
```
