### ISSUE TITLE
Add update_password option to os_user module

### ISSUE THREAD

**Issue by parberge** [ansible/ansible-modules-core#5217]
##### ISSUE TYPE

- Feature Idea
##### COMPONENT NAME

os_user
##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.1.2.0
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

The `os_user` module with a password specified for a user will always report 'changed'.
The conclusion of the bug report in #5183 was that in order to "fix" this we need to add another parameter like the on in the `user` module.
I.e a parameter called `update_password` that has options `on_create` or `always`.
##### STEPS TO REPRODUCE

```
  - name: "Create test user"
    os_user:
      name: test
      state: present
      password: very-secret
      default_project: a-existing-project
      update_password: on_create
```
##### EXPECTED RESULTS

On first run, the user would be created and the password set.
On the second run, given that nothing changed, the task would say `ok`.
If the parameter would be `update_password: always` on the other hand, the module should always set the password and would always report `changed`
