### ISSUE TITLE
deadlock using win_shell and Write-Host

### ISSUE THREAD

**Issue by caphrim007** [ansible/ansible-modules-core#5229]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

windows/win_shell.ps1
##### ANSIBLE VERSION

```
ansible 2.3.0
  config file = 
  configured module search path = Default w/o overrides
```

Installed via github and pip
##### OS / ENVIRONMENT

Running from: OS X El Capitan 10.11.6
Managing: Windows Server 2016 TP 4, Version 10.0.10586 Build 10586
##### SUMMARY

win_shell appears to block when using a combination of `Write-Host` and `Select-String` with `-Context`

The script being run remotely is located here
https://github.com/Azure/AzureStack-Tools/blob/master/Deployment/PrepareBootFromVHD.ps1
##### STEPS TO REPRODUCE

Playbook

```
- name: Deploy AzureStack
  hosts: windows

  tasks:
      - name: Deploy the AzureStack VHDX
        win_shell: 'C:\AzureStack_TP2_SupportFiles\foo.ps1'
        args:
            chdir: C:\AzureStack_TP2_SupportFiles
            creates: C:\CloudDeployment
```

Content of foo.ps1

```
$bootOptions = bcdedit /enum | Select-String 'path' -Context 2,1
$bootOptions | ForEach {
    Write-Host 'foo' -ForegroundColor Cyan
    Write-Host 'bar' -ForegroundColor Cyan
    }

exit
```

##### EXPECTED RESULTS

The win_shell will successfully exit when it reaches the `exit` in the PowerShell script.
##### ACTUAL RESULTS

The powershell script will appear to hang and the task will never complete.

https://gist.github.com/caphrim007/200f878a66741751b773ee79af0f6db3

Curiously, if I leave out either the `Select-String` or the `Write-Host`, the PowerShell script will complete just fine.

I've also tried commenting out the `ReadToEnd` lines here

https://github.com/ansible/ansible-modules-core/blame/b4f6a25195d8d2420184347bc65e89d9da4f592a/windows/win_shell.ps1#L86

without success.

Changing all of the `Write-Host` lines in the script to `Write-Output` causes the PowerShell script to succeed.
