### ISSUE TITLE
Can't get job to skip steps when a variable exists

### ISSUE THREAD

**Issue by philipcowgill** [ansible/ansible-modules-core#5235]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

set_fact
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```
##### SUMMARY

I want this project to skip all steps only under one condition: the version and haproxy.stat.exists match.  For some reason the entire playbook runs despite the two matching perfectly.
##### STEPS TO REPRODUCE

```

---

- include_vars: /var/lib/awx/projects/haproxy/roles/haproxy_role/vars/version.yml
- include_vars: /var/lib/awx/projects/haproxy/roles/haproxy_role/vars/oam.yml
### Check to see if HAProxy is already installed ###
- name: Check if HAProxy is already installed
  stat: path=/root/haproxy-1.6.9/VERSION
  register: haproxy

### Fetch the HAProxy version start file from remote host and copy to local server ###
### This file will contain the current version number of HAProxy  ###
- fetch:
    src: "/root/haproxy-1.6.9/VERSION"
    dest: "/tmp/HAPROXY.txt"
    flat: yes
  changed_when: False
  when: haproxy.stat.exists

### Set variable HAProxy.exists to contents of version file ###
- set_fact:
    contents: "{{ lookup('file', '/tmp/HAPROXY.txt') }}"
    when: haproxy.stat.exists

### Placeholder variable so next steps won't fail ###
### Only used when no version of HAProxy is installed ###
- set_fact:
   contents: ""
   when: haproxy.stat.exists is not defined

- name: Copy HAProxy File
  copy: src=haproxy.tar.gz dest=/root
  when: "'{{ VERSION }}' not in contents"

```

##### ACTUAL RESULTS

```
I expect it to skip the Copy HAProxy File as HAProxy is installed and the version matches
```
