### ISSUE TITLE
[security] apt_key module does not verify key fingerprints

### ISSUE THREAD

**Issue by ypid** [ansible/ansible-modules-core#5237]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

apt_key module
##### ANSIBLE VERSION

devel
##### CONFIGURATION

not relevant
##### OS / ENVIRONMENT

not relevant
##### SUMMARY

apt_key module does not verify key fingerprints and imports keys based on 16 digits long id.
This is a serious problem because it is easy to generate a OpenPGP key with a desired 16 digit key IDs.
Also, hkp is unauthenticated so it it becomes trivial to offer a wrong key to a victim.

The problem is [this workaround](https://github.com/ansible/ansible-modules-core/blob/683e5e4d1ad1e779d27d58af4ae7fdcda9881ab2/packaging/os/apt_key.py#L240-L250).
##### STEPS TO REPRODUCE

``` yaml

- name: Try to import key without verifying that we import the correct key
  hosts: 'dev.example.com'
  become: True

  tasks:

    - apt_key:
        id: '00000000000000000000000047AE7F72479BC94B'
        keyserver: 'hkp://pool.sks-keyservers.net'

```
##### EXPECTED RESULTS

That key does not exist. No key is added.
##### ACTUAL RESULTS

The key id 479BC94B is imported.
##### EXAMPLE FIX

Enforce correct key fingerprint with a trick such as:

``` shell

mkdir /tmp/gpg && chmod 700 /tmp/gpg
gpg --homedir /tmp/gpg --recv-keys --keyserver hkp://pool.sks-keyservers.net --recv 479BC94B
gpg --homedir /tmp/gpg --export DDA2C105C4B73A6649AD2BBD47AE7F72479BC94B | apt-key add -

```
