### ISSUE TITLE
iptables policy never state changed

### ISSUE THREAD

**Issue by crane-denny** [ansible/ansible-modules-core#5243]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

iptables
##### ANSIBLE VERSION

```
ansible 2.3.0 (devel 6be09ee866) last updated 2016/10/12 15:01:20 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 275fa3f055) last updated 2016/10/12 21:06:11 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 6c31d91fa5) last updated 2016/10/12 21:06:16 (GMT +200)
  config file = /Users/crane/live/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

When using the policy feature in the module iptables the task which changes the policy is never the state changed even when it has changed the policy.
##### STEPS TO REPRODUCE

```
- name: Setting policy drop
  iptables:
    chain: "{{ item[0] }}"
    policy: DROP
    ip_version: "{{ item[1] }}"
  with_nested:
    - ['INPUT', 'OUTPUT', 'FORWARD']
    - ['ipv4', 'ipv6']
```
##### EXPECTED RESULTS

A changed when stuff is changed
##### ACTUAL RESULTS

No changed tasks
