### ISSUE TITLE
OpenStack modules don't work with cloud specified auth

### ISSUE THREAD

**Issue by jackivanov** [ansible/ansible-modules-core#5250]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

os_keystone_service, os_user, etc..
##### ANSIBLE VERSION

```
ansible 2.2.0
  config file = 
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
[defaults]
hostfile = hosts
host_key_checking = False
retry_files_enabled = False
#deprecation_warnings=False
#display_skipped_hosts=False

[paramiko_connection]
record_host_keys = False

[ssh_connection]
ssh_args = -o ControlMaster=auto -o ControlPersist=60s -o UserKnownHostsFile=/dev/null  -o IdentitiesOnly=yes
```
##### SUMMARY

I get an error with modules for OpenStack. `openstack` cli works well with the same parameters
##### STEPS TO REPRODUCE

```
- os_keystone_service:
    cloud: local_bypass
    state: present
    name: keystone
    service_type: identity
    description: 'OpenStack Identity'
```

```
[root@domain ~]# cat /etc/openstack/clouds.yaml 
clouds:
  local_bypass:
    auth_type: token_endpoint
    identity_api_version: 3
    auth:
      token: QWESDFwse423fs
      url: http://domain.com:35357/v3
```
##### EXPECTED RESULTS

Create a service suceffull
##### ACTUAL RESULTS

```
fatal: [domain.com]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "api_timeout": null, 
            "auth": null, 
            "auth_type": null, 
            "availability_zone": null, 
            "cacert": null, 
            "cert": null, 
            "cloud": "local_bypass", 
            "description": "OpenStack Identity", 
            "enabled": true, 
            "endpoint_type": "public", 
            "key": null, 
            "name": "keystone", 
            "region_name": null, 
            "service_type": "identity", 
            "state": "present", 
            "timeout": 180, 
            "verify": true, 
            "wait": true
        }, 
        "module_name": "os_keystone_service"
    }, 
    "msg": "Problem with auth parameters"
}
```

but with `openstack-cli` it works well

```
# openstack --os-cloud local_bypass service create --name keystone --description "OpenStack Identity" identity
+-------------+----------------------------------+
| Field       | Value                            |
+-------------+----------------------------------+
| description | OpenStack Identity               |
| enabled     | True                             |
| id          | c70acc58b250421d8084c2a26f358e88 |
| name        | keystone                         |
| type        | identity                         |
+-------------+----------------------------------+
```

**Comment by jackivanov** [comment]
The same behavior if use credentials directly in the module:

```
- os_keystone_service:
    auth_type: token_endpoint
    auth:
      token: QWESDFwse423fs
      url: http://domain.com:35357/v3
    state: present
    name: keystone
    service_type: identity
    description: 'OpenStack Identity'
```

```
fatal: [domain.com]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "api_timeout": null, 
            "auth": {
                "token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "url": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
            }, 
            "auth_type": "token_endpoint", 
            "availability_zone": null, 
            "cacert": null, 
            "cert": null, 
            "cloud": null, 
            "description": "OpenStack Identity", 
            "enabled": true, 
            "endpoint_type": "public", 
            "key": null, 
            "name": "keystone", 
            "region_name": null, 
            "service_type": "identity", 
            "state": "present", 
            "timeout": 180, 
            "verify": true, 
            "wait": true
        }, 
        "module_name": "os_keystone_service"
    }, 
    "msg": "Problem with auth parameters"
}
```
