### ISSUE TITLE
git: Doesn't pick up new tags for already installed revision

### ISSUE THREAD

**Issue by pfalcon** [ansible/ansible-modules-core#527]
If git module sees that revision to install matches that of already installed, it stop there. However, it may be the case that this revision was tagged since the previous install, and with the current behavior, git module won't fetch this new tag. This may in turn affect software which uses "git describe" command to show version information - instead the latest of tag it shows something else (raw revision or version based on previous tag).

**Comment by pfalcon** [comment]
```
$ ansible-playbook --version
ansible-playbook 1.7.1
```

**Comment by abadger** [comment]
If you can give examples of ansible playbooks or command lines that misbehave and show what hte desired outcome vs the current outcome is, that would help us look into this.  Thanks!

**Comment by cjunge-work** [comment]
I've just run into this issue but for branches. Below is the steps on how it happened for us.

Ansible 1.8.4

1) Create playbook with task that checks out master branch:

```
-   name: Clone/update repo
    git:
        dest: "{{ cache_dir }}"
        repo: "git@github.com:{{ repo }}"
        version: "master"
        update: yes
        force: yes
        recursive: yes
```

2) Add new branch to repo (eg. production), do not add new commit. Push branch to origin.

3) Run playbook again with new branch name

```
-   name: Clone/update repo
    git:
        dest: "{{ cache_dir }}"
        repo: "git@github.com:{{ repo }}"
        version: "production"
        update: yes
        force: yes
        recursive: yes
```

error: `msg: Failed to checkout production`

Doing a manual git fetch origin fixes it. I assume this would apply to tags as well.
