### ISSUE TITLE
RFE/Feature Idea: os_object - be able to specify the amount of threads used in operations

### ISSUE THREAD

**Issue by dmsimard** [ansible/ansible-modules-core#5272]
##### ISSUE TYPE
- Feature Idea
##### COMPONENT NAME

openstack/os_object
##### ANSIBLE VERSION

Not relevant
##### CONFIGURATION

Not relevant
##### OS / ENVIRONMENT

Not relevant
##### SUMMARY

swiftclient has built-in parameters in order to split tasks into different threads in order to speed up operations, example:

```
--object-threads=OBJECT_THREADS
                    Number of threads to use for uploading full objects.
                    Default is 10.
--segment-threads=SEGMENT_THREADS
                    Number of threads to use for uploading object
                    segments. Default is 10.
```

the os_object module does not expose these and it would be an interesting feature to add in order to speed up long operations involving many files.
##### EXPECTED RESULTS

```
# Takes two minutes
- os_object:
    cloud: mordred
    state: present
    name: huge_folder
    container: destfolder
    filename: huge_folder
    object_threads: 100
```
##### ACTUAL RESULTS

```
# Takes two hours
- os_object:
    cloud: mordred
    state: present
    name: huge_folder
    container: destfolder
    filename: huge_folder
```
