### ISSUE TITLE
iam update user fails to find existing user

### ISSUE THREAD

**Issue by kellenanker** [ansible/ansible-modules-core#5288]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

iam core module
##### ANSIBLE VERSION

```
ansible 2.0.1.0
  config file = /Users/ME/.ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

Running on OS X Sierra (10.12)
##### SUMMARY

I was using the `iam` core module, and ran into an interesting bug when attempting to update an existing IAM user.

I first created an IAM user (whether this was done through Ansible or through AWS, the result was still the same). I then attempted to use the `iam` module to update this user, but received an error stating that `The user USER does not exist`. 

In one particular test, I used the update user functionality to check for the existence of the user, and then proceeded to create the user if it did not exist (a `FAILED` status = user does not exist, so go ahead and create it). Before this run, the user in question had already been created; as such, the first action should have succeeded, and the second action should have skipped. However, updating the user failed, spitting out the error supplied above, which made the playbook attempt to create the user, which failed because the user already existed!

The aforementioned test was done as a workaround to, what I believe is, a gap in functionality of the `iam` module. Ansible is fantastically idempotent, but this module appears not to be. When creating a new IAM user, it would be extremely beneficial for the task to not error out if the user already exists, but rather skip the task and move on (like when you try to `yum` install a package that is already installed).
##### STEPS TO REPRODUCE

I am running this all locally. The relevant snippets of the playbook are the following:

```
...
- name: Check for existence of user
  connection: local
  iam:
    iam_type: user
    name: USER
    state: update
    access_key_state: create
  register: user_creation
  ignore_errors: yes

- name: Create user
  connection: local
  iam:
    iam_type: user
    name: USER
    state: present
    access_key_state: create
  register: user_creation
  when: user_creation.failed == true
...
```
##### EXPECTED RESULTS

I expected to successfully update the existing IAM user when using the `iam` module, with `state: update`.
##### ACTUAL RESULTS

Here is the output from the test case described above. You will see two contradicting output messages!

```
...
TASK [Check for presence of user] **********************************************
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "The user USER does not exist. No update made."}
...ignoring

TASK [Create user] *************************************************************
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "BotoServerError: 409 Conflict\n<ErrorResponse xmlns=\"https://iam.amazonaws.com/doc/2010-05-08/\">\n  <Error>\n    <Type>Sender</Type>\n    <Code>EntityAlreadyExists</Code>\n    <Message>User with name USER already exists.</Message>\n  </Error>\n  <RequestId>5f797c8d-948f-11e6-9002-172eb1b2f46a</RequestId>\n</ErrorResponse>\n"}
...
```
