### ISSUE TITLE
git module always fails on update if local has modification

### ISSUE THREAD

**Issue by wangjild** [ansible/ansible-modules-core#5292]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

git
##### ANSIBLE VERSION

```
2.2.0
```
##### OS / ENVIRONMENT

debian:8.0 jessie
##### SUMMARY

If local git repository has modification, an update attempt of always fails with Local modifications exist, even if force=yes was given.
##### STEPS TO REPRODUCE

```
  tasks:
    - name: update project dependency
      git: dest={{item.location|quote}} repo={{item.scm_url|quote}} version={{item.scm_revision|quote}} force=yes refspec={{item.scm_refspec}} accept_hostkey=yes
      with_items: "{{ deps }}"
```

##### ACTUAL RESULTS

```
failed: [127.0.0.1] => {
    "failed": true,
    "invocation": {
        "module_name": "git"
    },
    "item": {
        "location": "/opt/tiger/neihan/conf",
        "name": "neihan/conf",
        "scm_refspec": "refs/heads/master",
        "scm_revision": "master",
        "scm_url": "ssh://*********/neihan/conf"
    },
    "module_stderr": "Shared connection to 127.0.0.1 closed.\r\n",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_U00Fwd/ansible_module_git.py\", line 1023, in <module>\r\n    main()\r\n  File \"/tmp/ansible_U00Fwd/ansible_module_git.py\", line 974, in main\r\n    result.update(changed=True, after=remote_head, msg='Local modifications exist')\r\nUnboundLocalError: local variable 'remote_head' referenced before assignment\r\n",
    "msg": "MODULE FAILURE"
}
```
