### ISSUE TITLE
docker_service doesn't pass environment to docker-compose

### ISSUE THREAD

**Issue by davojan** [ansible/ansible-modules-core#5295]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

docker_service
##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = /usr/local/etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

`docker_service` task doesn't pass environment variables defined using `environment` option at task- or playbook-level to the `docker-compose.yml` when using `project_src`.
##### STEPS TO REPRODUCE

Playbook:

``` yaml

---
- name: demo
  tasks:
  - docker_service: project_src=/tmp/compose-dir
    environment:
      MYSQL_DB: "test"
```

`docker-compose.yml` at `/tmp/compose-dir`:

``` yaml
version: '2'
services:
  mysql:
    image: mysql:5.7
  environment:
    MYSQL_DATABASE: ${MYSQL_DB}
```

##### EXPECTED RESULTS

`mysql` container should see `MYSQL_DATABASE=test` and create database "test".
##### ACTUAL RESULTS

"test" database doesn't created

But when calling docker-compose directly:

```
MYSQL_DB=test docker-compose up
```

the "test" database is created
