### ISSUE TITLE
junos_netconf Module Failing With Local Connection: Paramiko required, yet is installed

### ISSUE THREAD

**Issue by kkirsche** [ansible/ansible-modules-core#5336]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

junos_netconf module
##### ANSIBLE VERSION

```
~/g/y/shield_config_backups ❯❯❯ ansible --version                             ⏎
ansible 2.1.2.0
  config file = /Users/kkirsche/git/yaml/config_backups/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
[defaults]
inventory: ./inventories/production/hosts.ini
forks: 20
pipelining: true
```
##### OS / ENVIRONMENT

From:

```
OS X El Capitan 10.11.6
```

Managing:

```
JUNOS 14.2R5.8 built 2015-11-25 00:47:56 UTC
```
##### SUMMARY

When running junos_netconf module with `connection: local`, the output is:

```
 _____________________________________________________
< TASK [juniper : Enable netconf service on port 830] >
 -----------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

fatal: [hostname]: FAILED! => {"changed": false, "failed": true, "msg": "paramiko is required but does not appear to be installed"}
```

yet Paramiko is installed:

```
~/g/y/config_backups ❯❯❯ pip install paramiko --upgrade                ⏎
Requirement already up-to-date: paramiko in /usr/local/lib/python2.7/site-packages
Requirement already up-to-date: cryptography>=1.1 in /usr/local/lib/python2.7/site-packages (from paramiko)
Requirement already up-to-date: pyasn1>=0.1.7 in /usr/local/lib/python2.7/site-packages (from paramiko)
Requirement already up-to-date: cffi>=1.4.1 in /usr/local/lib/python2.7/site-packages (from cryptography>=1.1->paramiko)
Requirement already up-to-date: six>=1.4.1 in /usr/local/lib/python2.7/site-packages (from cryptography>=1.1->paramiko)
Requirement already up-to-date: idna>=2.0 in /usr/local/lib/python2.7/site-packages (from cryptography>=1.1->paramiko)
Requirement already up-to-date: enum34 in /usr/local/lib/python2.7/site-packages (from cryptography>=1.1->paramiko)
Requirement already up-to-date: setuptools>=11.3 in /usr/local/lib/python2.7/site-packages (from cryptography>=1.1->paramiko)
Requirement already up-to-date: ipaddress in /usr/local/lib/python2.7/site-packages (from cryptography>=1.1->paramiko)
Requirement already up-to-date: pycparser in /usr/local/lib/python2.7/site-packages (from cffi>=1.4.1->cryptography>=1.1->paramiko)
```

I would expect that the local connection wouldn't state this either.
##### STEPS TO REPRODUCE

Auth Variables:

``` yaml

---
# inventories/production/group_vars/juniper.yml
cli_auth:
    host: "{{ inventory_hostname }}"
    username: kkirsche
    ssh_keyfile: /Users/kkirsche/.ssh/id_rsa
    transport: cli
```

Deploy role with:

``` yaml

---
# site.yml
- include: juniper.yml

---
# juniper.yml
- name: Backup Juniper Device Configurations
  hosts: juniper
  tags: ['backup', 'juniper', 'junos']
  gather_facts: no
  connection: local
  ignore_errors: no
  roles:
    # Packages
    - { role: juniper, tags: ['backup', 'juniper', 'junos'] }
```

Role task:

``` yaml

---
# roles/juniper/tasks/main.yml
- name: Enable netconf service on port 830
  junos_netconf:
    listens_on: 830
    state: present
    provider: "{{ cli_auth }}"
```

Inventory:

```
[juniper]
... list of hostnames ...
```

##### EXPECTED RESULTS

For the local connection to use `junos-eznc` to connect to the remote host and enable netconf on port 830
##### ACTUAL RESULTS

Ansible stated that I needed paramiko

```
~/g/y/config_backups ❯❯❯ ansible-playbook site.yml -vvvv               ⏎
Using /Users/kkirsche/git/yaml/config_backups/ansible.cfg as config file
Loaded callback default of type stdout, v2.0
 ____________________
< PLAYBOOK: site.yml >
 --------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

1 plays in site.yml
 _____________________________________________
< PLAY [Backup Juniper Device Configurations] >
 ---------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

 _____________________________________________________
< TASK [juniper : Enable netconf service on port 830] >
 -----------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

task path: /Users/kkirsche/git/yaml/config_backups/roles/juniper/tasks/main.yml:4
<example.host.net> ESTABLISH LOCAL CONNECTION FOR USER: kkirsche
<example.host.net> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1476990651.89-125212332990145 `" && echo ansible-tmp-1476990651.89-125212332990145="` echo $HOME/.ansible/tmp/ansible-tmp-1476990651.89-125212332990145 `" ) && sleep 0'
<example.host.net> PUT /var/folders/8y/pj9zz4b12r37490xnlqb7gb13tt57z/T/tmpI4oHRK TO /Users/kkirsche/.ansible/tmp/ansible-tmp-1476990651.89-125212332990145/junos_netconf
<example.host.net> EXEC /bin/sh -c 'chmod u+x /Users/kkirsche/.ansible/tmp/ansible-tmp-1476990651.89-125212332990145/ /Users/kkirsche/.ansible/tmp/ansible-tmp-1476990651.89-125212332990145/junos_netconf && sleep 0'
<example.host.net> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /Users/kkirsche/.ansible/tmp/ansible-tmp-1476990651.89-125212332990145/junos_netconf; rm -rf "/Users/kkirsche/.ansible/tmp/ansible-tmp-1476990651.89-125212332990145/" > /dev/null 2>&1 && sleep 0'
fatal: [example.host.net]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"host": "example.host.net", "listens_on": 830, "password": null, "port": null, "provider": {"host": "example.host.net", "ssh_keyfile": "/Users/kkirsche/.ssh/id_rsa", "transport": "cli", "username": "kkirsche"}, "ssh_keyfile": "/Users/kkirsche/.ssh/id_rsa", "state": "present", "timeout": 0, "transport": "cli", "username": "kkirsche"}, "module_name": "junos_netconf"}, "msg": "paramiko is required but does not appear to be installed"}
 ____________________
< NO MORE HOSTS LEFT >
 --------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

    to retry, use: --limit @/Users/kkirsche/git/yaml/config_backups/site.retry
 ____________
< PLAY RECAP >
 ------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

example.host.net          : ok=0    changed=0    unreachable=0    failed=1
```

I attempted to see if #3422 was my issue, but it does not appear to be. Any help would be greatly appreciated.
