### ISSUE TITLE
pip uses pip2 and ignores virtualenv

### ISSUE THREAD

**Issue by JulienPalard** [ansible/ansible-modules-core#5347]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

pip
##### ANSIBLE VERSION

```
ansible 2.3.0 (devel 2804e64ed5) last updated 2016/10/21 09:59:53 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 6f15dfd464) last updated 2016/10/18 16:01:36 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 3f77bb6857) last updated 2016/10/18 16:01:38 (GMT +200)
  config file = 
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

ø
##### OS / ENVIRONMENT

Debian 8.6 jessie on both machines.
##### SUMMARY

Using the ansible `pip` module with a virtualenv, ansible uses `/usr/bin/pip2` instead of the shiny pip3 contained in the virtualenv.
##### STEPS TO REPRODUCE

```
  - name: pip install requirements
    become: yes
    become_user: test
    pip:
      chdir: /home/test/
      requirements: requirements.txt
      virtualenv: /home/test/
      virtualenv_command: pyvenv
      virtualenv_python: python3
```

```
fatal: [dev]: FAILED! => {"changed": false, "cmd": "/usr/bin/pip2 install -r requirements.txt",
```
##### EXPECTED RESULTS

I expect the `ansible pip module` to use `python3 -m pip`, or at least a `pip3` found in the virtualenv (there is one).
##### ACTUAL RESULTS

Ansible uses `/usr/bin/pip2`.
