### ISSUE TITLE
Changes to env vars on tasks to do not see prev changes

### ISSUE THREAD

**Issue by mindojo-victor** [ansible/ansible-modules-core#5355]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

lookup env
##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible']
```
##### OS / ENVIRONMENT

Ubuntu 14.04
##### SUMMARY

If I set an environment variable at playbook level, the change is not seen in tasks in which I do `lookup('env', ...)`
##### STEPS TO REPRODUCE

```
- hosts: localhost
  connection: local

  environment:
    PATH: "/home/jenkins/nvm:{{ lookup('env', 'PATH') }}"

  tasks:
    - name: Install Bower
      shell: nvm-exec npm install bower
      environment:
        PATH: "{{workspace_dir}}/node_modules/.bin:{{ lookup('env', 'PATH') }}"
```

##### EXPECTED RESULTS

The task command should see both changes to `PATH` env var.
##### ACTUAL RESULTS

Tasks which do not change environment see the playbook level changes to `PATH`. If a task has `environment` arguments, it does not see the playbook level changes. It sees value of `PATH` before the playbook level changes.

```
TASK [setup] *******************************************************************
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: jenkins
...
<localhost> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 PATH=/home/jenkins/nvm:/home/ubuntu/nvm/versions/node/v6.3.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games /usr/bin/python /var/lib/jenkins/.ansible/tmp/ansible-tmp-1477137522.21-102488172848925/setup; rm -rf "/var/lib/jenkins/.ansible/tmp/ansible-tmp-1477137522.21-102488172848925/" > /dev/null 2>&1 && sleep 0'
ok: [localhost]
```

`/home/jenkins/nvm` was added to `PATH`. Then in a task:

```
<localhost> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 PATH=/home/jenkins/workspace/FrontendStartServer/node_modules/.bin:/home/ubuntu/nvm/versions/node/v6.3.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games /usr/bin/python /var/lib/jenkins/.ansible/tmp/ansible-tmp-1477137549.95-119094824025418/command; rm -rf "/var/lib/jenkins/.ansible/tmp/ansible-tmp-1477137549.95-119094824025418/" > /dev/null 2>&1 && sleep 0'
failed: [localhost] => {"cmd": "nvm-exec npm install bower", "stderr": "/bin/sh: 1: nvm-exec: not found", ...}
```
