### ISSUE TITLE
ios_facts: gather_facts :hardware crash on cisco switches

### ISSUE THREAD

**Issue by boudreau** [ansible/ansible-modules-core#5372]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

ios_facts: gather_facts : hardware 
##### ANSIBLE VERSION

```
ansible 2.2.0.0 (stable-2.2 b702d3810e)
```
##### SUMMARY

Looks like the process to check the memory on the ios device uses "show memory statistics | include Processor". This command is not available on the Cisco switches and makes the module fail. Tested with Cisco 3850 switches.
##### STEPS TO REPRODUCE

```
   vars:
      cli:
        timeout: 15
        host: "{{ inventory_hostname }}"
        username: "{{ creds_sw['username'] }}"
        password: "{{ creds_sw['password'] }}"
        auth_pass: "{{ creds_sw['auth_pass'] }}"
        transport: cli
   tasks:
         - name: Get login info
           include_vars: secret.yml

     - name: get facts
           ignore_errors: yes
           ios_facts:
              authorize: yes
              provider: "{{ cli }}"
              gather_subset:
                - "hardware"

```

##### ACTUAL RESULTS

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: <Hostname>#
fatal: [hostname]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_p2ys4P/ansible_module_ios_facts.py\", line 461, in <module>\n    main()\n  File \"/tmp/ansible_p2ys4P/ansible_module_ios_facts.py\", line 443, in main\n    runner.run()\n  File \"/tmp/ansible_p2ys4P/ansible_modlib.zip/ansible/module_utils/netcli.py\", line 170, in run\n  File \"/tmp/ansible_p2ys4P/ansible_modlib.zip/ansible/module_utils/netcli.py\", line 98, in run_commands\n  File \"/tmp/ansible_p2ys4P/ansible_modlib.zip/ansible/module_utils/shell.py\", line 257, in run_commands\n  File \"/tmp/ansible_p2ys4P/ansible_modlib.zip/ansible/module_utils/shell.py\", line 254, in execute\nansible.module_utils.network.NetworkError: matched error in response:  statistics | include Process         r\r\n**_show memory statistics | include Processor_**\r\n             ^\r\n% Invalid input detected at '^' marker.\r\n\r\nhostname#\n", "module_stdout": "", "msg": "MODULE FAILURE"}

```

```
