### ISSUE TITLE
Key does not seem to have been added (but it has)

### ISSUE THREAD

**Issue by tristanbes** [ansible/ansible-modules-core#5386]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

`apt_key`
##### ANSIBLE VERSION

```
ansible 2.1.2.0
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

The module says it fails but the key has successfully been added on servers
##### STEPS TO REPRODUCE

```
- name: add key for yarn package
  apt_key:
    keyserver: pgp.mit.edu
    id: D101F7899D41F3C3
  #temp fix because of the "key does not seem to have been added"
  #ignore_errors: yes
  become: yes
  become_user: root
```

##### EXPECTED RESULTS

Changed or OK output
##### ACTUAL RESULTS

```
FAILED! => {"changed": false, "failed": true, "id": "9D41F3C3", "msg": "key does not seem to have been added"}
```

But when running the command `apt-key list`, **the right key for yarn is listed**.
