### ISSUE TITLE
win_user module check mode always returns skipping (never changed or OK)

### ISSUE THREAD

**Issue by juanjomm** [ansible/ansible-modules-core#5391]
##### ISSUE TYPE

- Feature idea
##### COMPONENT NAME

win_user module
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel c9a5b1c555) last updated 2016/06/02 15:42:56 (GMT +200)
  lib/ansible/modules/core: (detached HEAD ca4365b644) last updated 2016/06/02 15:43:14 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD b0aec50b9a) last updated 2016/06/02 15:43:15 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

Python 2.7.5 (default, Oct 11 2015, 17:47:16)
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)] on linux2

```
##### CONFIGURATION

 ansible_user: xxxx
 ansible_pass: xxxxx
 ansible_connection: winrm
 ansible_ssh_port: 5986
##### OS / ENVIRONMENT

Ansible running in RHEL 7.2
OS remote is Windows 2012R2 with powershell 4.0
##### SUMMARY

When i execute the playbook in check mode on remote node (windows) the win_user module always return skipping, never return state: Changed or OK.
##### STEPS TO REPRODUCE

```
ANSIBLE COMMAND:
ansible-playbook -i ./inv/invs ./site.yml --check
```

```
ANSIBLE CODE:
$cat site.yml
- name: User Account Disabled
  hosts: "{{hosts|default('all')}}"

  vars_files:
    - group_vars/User_Account_Disabled

  tasks:
    - name: "User Account Disabled"
      win_user:
        name: "User"
        account_disabled: "yes"
```

##### EXPECTED RESULTS

When i execute the playbook in check mode on remote node (windows) with the Win account disabled, the win_user module always return skipping, never return state: Changed or OK.
##### ACTUAL RESULTS

```
PLAY [User Account Disabled] ***************************************************

TASK [setup] *******************************************************************
skipping: [server.com]

TASK [User_Account_Disabled : UserAccount=guest Disabled=yes] ******************
skipping: [server.com]

PLAY RECAP *********************************************************************
server.com : ok=1    changed=0    unreachable=0    failed=0
```
