### ISSUE TITLE
Yum ignores notify handlers

### ISSUE THREAD

**Issue by jamesmarshall24** [ansible/ansible-modules-core#5396]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

yum
##### ANSIBLE VERSION

```
ansible 2.2.0.0 (stable-2.2 deb1e3ebc7) last updated 2016/10/26 14:40:50 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 0881ba15c6) last updated 2016/10/26 14:43:13 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 47f4dd44f4) last updated 2016/10/26 14:43:17 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

ansible 2.3.0 (devel 56086f3b9e) last updated 2016/10/26 15:06:06 (GMT -400)
  lib/ansible/modules/core: (detached HEAD c51ced56cc) last updated 2016/10/26 15:06:48 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 8ffe314ea5) last updated 2016/10/26 15:06:52 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

Default
##### OS / ENVIRONMENT

RHEL 7.2
##### STEPS TO REPRODUCE

1. Build a project directory similar to the one below:

```
./
├── group_vars
│   └── rhel
│       └── vars
├── hosts
├── main.yml
└── roles
    └── test
        ├── handlers
        │   └── main.yml
        └── tasks
            └── main.yml
```
1. Run playbook:
   ansible-playbook -i hosts main.yml

./main.yml

```
- hosts: all
  become: yes
  roles:
    - test
```

./roles/test/handlers/main.yml

```
- name: handler1
  debug:
    msg: "handler 1 run"

- name: handler2
  debug:
    msg: "handler 2 run"
```

./roles/test/tasks/main.yml

```
- block:
    - name: "ensure lsof is not installed"
      yum:
        name: lsof
        state: absent

    - name: "Double check"
      command: "yum list installed lsof"
      ignore_errors: true

    - name: "this should run handlers"
      yum:
        name: lsof
        state: present
      notify:
        - handler1
        - handler2

    - name: "Double check"
      shell: "yum list installed lsof"

  tags:
    - t-test
```
##### EXPECTED RESULTS

As seen in 2.1.2:

```
PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [host]

TASK [test : ensure lsof is not installed] *************************************
changed: [host]

TASK [test : Double check] *****************************************************
fatal: [host]: FAILED! => {"changed": true, "cmd": ["yum", "list", "installed", "lsof"], "delta": "0:00:00.260975", "end": "2016-10-26 16:07:16.555671", "failed": true, "rc": 1, "start": "2016-10-26 16:07:16.294696", "stderr": "Error: No matching Packages to list", "stdout": "Loaded plugins: amazon-id, rhui-lb, search-disabled-repos", "stdout_lines": ["Loaded plugins: amazon-id, rhui-lb, search-disabled-repos"], "warnings": ["Consider using yum module rather than running yum"]}
...ignoring

TASK [test : this should run handlers] *****************************************
changed: [host]

TASK [test : Double check] *****************************************************
changed: [host]
 [WARNING]: Consider using yum module rather than running yum


RUNNING HANDLER [test : handler1] **********************************************
ok: [host] => {
    "msg": "handler 1 run"
}

RUNNING HANDLER [test : handler2] **********************************************
ok: [host] => {
    "msg": "handler 2 run"
}

PLAY RECAP *********************************************************************
host             : ok=7    changed=3    unreachable=0    failed=0
```

Handlers are ran
##### ACTUAL RESULTS

Observed in 2.2 and 2.3:

```
PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [host]

TASK [test : ensure lsof is not installed] *************************************
changed: [host]

TASK [test : Double check] *****************************************************
fatal: [host]: FAILED! => {"changed": true, "cmd": ["yum", "list", "installed", "lsof"], "delta": "0:00:00.270957", "end": "2016-10-26 16:05:45.987169", "failed": true, "rc": 1, "start": "2016-10-26 16:05:45.716212", "stderr": "Error: No matching Packages to list", "stdout": "Loaded plugins: amazon-id, rhui-lb, search-disabled-repos", "stdout_lines": ["Loaded plugins: amazon-id, rhui-lb, search-disabled-repos"], "warnings": ["Consider using yum module rather than running yum"]}
...ignoring

TASK [test : this should run handlers] *****************************************
changed: [host]

TASK [test : Double check] *****************************************************
changed: [host]
 [WARNING]: Consider using yum module rather than running yum


PLAY RECAP *********************************************************************
host             : ok=5    changed=3    unreachable=0    failed=0
```

Handlers are not run
