### ISSUE TITLE
Error: docker-py version is 1.10.5. Minimum version required is 1.7.0.

### ISSUE THREAD

**Issue by dgellow** [ansible/ansible-modules-core#5422]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

docker_service
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = <MY_PATH>/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

Nothing relevant here
##### OS / ENVIRONMENT

From: MacOS
To: Debian 8
##### SUMMARY

I get the following error when I'm trying to use `docker_service`:

```
TASK [<projectname> : docker_service] ************************************************
fatal: [<hostname>]: FAILED! => {"changed": false, "failed": true, "msg": "Error: docker-py version is 1.10.5. Minimum version required is 1.7.0."}
```

The error message doesn't make any sense, the minimum version is 1.7.0 and I have 1.10.5.
##### STEPS TO REPRODUCE

I set up a github repo with a Vagrantfile and a playbook reproducing the problem:
https://github.com/dgellow/ansible_issue_docker-py

You should get the same error by running `vagant up` (you obviously need vagrant installed on your machine).

```
- hosts: all
  user: vagrant
  sudo: yes

  vars:
    dockercompose_version: 1.9.0-rc1
    dockercompose_platform: Linux-x86_64
    dockercompose_url: https://github.com/docker/compose/releases/download/{{ dockercompose_version }}/docker-compose-{{ dockercompose_platform }}
    dockercompose_install_dir: /usr/local/bin/docker-compose

  tasks:
    - name: Install pip
      apt: name=python-pip state=latest update_cache=yes

    - name: Install docker python client
      pip: name=docker-py state=latest

    - name: Install python-yaml
      apt: name=python-yaml state=latest

    - name: Install docker-compose
      get_url:
        url: "{{ dockercompose_url }}"
        dest: "{{ dockercompose_install_dir }}"
        mode: a+x

    - name: Run redis from docker-compose
      docker_service:
        project_name: reproduceissue
        definition:
          version: '2'
          services:
            redis:
              image: redis
```

##### EXPECTED RESULTS

It shouldn't fail. And if it fails, the error message should be correct.
##### ACTUAL RESULTS

```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'debian/jessie64' is up to date...
==> default: Resuming suspended VM...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
==> default: Machine booted and ready!
==> default: [vagrant-hostsupdater] Checking for host entries
==> default: Running provisioner: ansible...
    default: Running ansible-playbook...
[DEPRECATION WARNING]: Instead of sudo/sudo_user, use become/become_user and 
make sure become_method is 'sudo' (default).
This feature will be removed in a 
future release. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.

PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [default]

TASK [Install pip] *************************************************************
ok: [default]

TASK [Install docker python client] ********************************************
changed: [default]

TASK [Install python-yaml] *****************************************************
changed: [default]

TASK [Install docker-compose] **************************************************
changed: [default]

TASK [Run redis from docker-compose] *******************************************
fatal: [default]: FAILED! => {"changed": false, "failed": true, "msg": "Error: docker-py version is 1.10.5. Minimum version required is 1.7.0."}

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @./site.retry

PLAY RECAP *********************************************************************
default                    : ok=5    changed=3    unreachable=0    failed=1  
```
