### ISSUE TITLE
parsing oddity: escaping level different depending on distribution???

### ISSUE THREAD

**Issue by juju4** [ansible/ansible-modules-core#5433]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

replace module but might be deeper level
##### ANSIBLE VERSION

installed inside container with python-pip

```
ansible 2.1.2.0
  config file = 
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

Travis
##### OS / ENVIRONMENT

Travis with lxd container
##### SUMMARY

Fails on xenial
https://travis-ci.org/juju4/ansible-scumblr/jobs/171808676#L1365

```
ERROR! Syntax Error while loading YAML.

The error appears to have been in '/etc/ansible/roles/ansible-scumblr/tasks/main.yml': line 254, column 108, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
- name: set services API key config - facebook_app_id
  replace: "dest='{{ scumblr_root }}/config/initializers/scumblr.rb' regexp='^  #config.facebook_app_id = \'\'' replace='  config.facebook_app_id = \'{{ scumblr_facebook_app_id }}\''"
                                                                                                           ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes.  Always quote template expression brackets when they
start a value. For instance:
    with_items:
      - {{ foo }}
Should be written as:
    with_items:
      - "{{ foo }}"
```

but same code works with
trusty container: https://travis-ci.org/juju4/ansible-scumblr/jobs/171808679
precise container: https://travis-ci.org/juju4/ansible-scumblr/jobs/171808680
xenial docker: https://travis-ci.org/juju4/ansible-scumblr/jobs/171802804
##### STEPS TO REPRODUCE

not sure how to reproduce outside of taking travis execution.
My local test with kitchen/lxd_cli works fine.

Thanks

**Comment by ansibot** [comment]
@EvanK ping, this issue is waiting for your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by EvanK** [comment]
This is a wild guess, but it may have something to do with ansible's yaml parsing of the playbook. You could simplify the quoting (and do away with the need for escaping quotes) by using the long form for a task this complex:

``` yml
- name: set services API key config - facebook_app_id
  replace:
    dest: "{{ scumblr_root }}/config/initializers/scumblr.rb"
    regexp: "^  #config.facebook_app_id = ''"
    replace: "  config.facebook_app_id = '{{ scumblr_facebook_app_id }}'"
```
