### ISSUE TITLE
apache2_module fails for libapache2-mod-proxy-uwsgi

### ISSUE THREAD

**Issue by brantlk** [ansible/ansible-modules-core#5455]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
apache2_module

##### ANSIBLE VERSION
```
$ ./ansible --version
ansible 2.2.0.0
  config file = 
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
None

##### OS / ENVIRONMENT
Ubuntu 14.04

##### SUMMARY
A playbook that was working with ansible 2.1.2.0 started failing when 2.2.0.0 was released. The playbook:

1) apt installs a bunch of packages, including apache2, libapache2-mod-proxy-html, and libapache2-mod-proxy-uwsgi, uwsgi, etc.
2) Uses apache2_module to enable proxy_http

#### Analysis

The apache2_module module was changed to use `apache2ctl -M` to list modules in 2.2.0.0, which fails with the playbook due to an oddity of the Ubuntu packages:

- libapache2-mod-proxy-html : installs the modules disabled.
- libapache2-mod-proxy-uwsgi : installs the module enabled.

But, mod_proxy_uwsgi requires mod_proxy_http to be enabled, and since mod_proxy_uwsgi is enabled but mod_proxy_http is disabled, `apache2ctl -M` fails with a confusing error (see output below)

See https://github.com/ansible/ansible-modules-core/pull/2417 for the change that added use of `apache2ctl -M`.

A potential fix is to provide special handling for mod_proxy_uwsgi so that it doesn't use `apache2ctl -M` or something.

##### STEPS TO REPRODUCE

```
- name: Install packages
  become: true
  apt: name={{ item }}
  with_items:
    - apache2
    - git
    - libapache2-mod-proxy-html
    - libapache2-mod-proxy-uwsgi
    - python-dev
    - python-pip
    - python-virtualenv
    - uwsgi-emperor
    - uwsgi-plugin-python

- name: Enable modules for mod_proxy_uwsgi
  become: true
  apache2_module: name={{ item }}
  with_items:
    - proxy_http
  notify:
    - Restart httpd
```

##### EXPECTED RESULTS
Expected the old playbook to work.

##### ACTUAL RESULTS
```
failed: [default] (item=proxy_http) => {
    "failed": true, 
    "invocation": {
        "module_args": {
            "force": false, 
            "name": "proxy_http", 
            "state": "present"
        }, 
        "module_name": "apache2_module"
    }, 
    "item": "proxy_http", 
    "msg": "Error executing /usr/sbin/apache2ctl: apache2: Syntax error on line 140 of /etc/apache2/apache2.conf: Syntax error on line 1 of /etc/apache2/mods-enabled/proxy_uwsgi.load: Cannot load /usr/lib/apache2/modules/mod_proxy_uwsgi.so into server: /usr/lib/apache2/modules/mod_proxy_uwsgi.so: undefined symbol: ap_proxy_backend_broke\n"
}
```

As you can see the error isn't very useful as far as figuring out the problem.

##### Workaround

The following steps worked around the issue:

```
- name: Install packages
  become: true
  apt: name={{ item }}
  with_items:
    - apache2
    - git
    - libapache2-mod-proxy-html
    - python-dev
    - python-pip
    - python-virtualenv
    - uwsgi-emperor
    - uwsgi-plugin-python
- name: Enable modules for mod_proxy_uwsgi
  become: true
  apache2_module: name={{ item }}
  with_items:
    - proxy_http
  notify:
    - Restart httpd
- name: Install mod-proxy-uwsgi
  become: true
  apt: name={{ item }}
  with_items:
    - libapache2-mod-proxy-uwsgi
  notify:
    - Restart httpd
```
