### ISSUE TITLE
unarchive: "creates" parameter ignored

### ISSUE THREAD

**Issue by fdutheil** [ansible/ansible-modules-core#546]
##### Issue Type:

Bug Report
##### Ansible Version:

1.8.1
##### Environment:

Ubuntu 14.04 as master for CentOS 6.5
##### Summary:

In the unarchive module, I want the "creates" parameter to do as documented: "a filename, when it already exists, this step will not be run. (added in Ansible 1.6)" So that the module doesn't report a change when the content is already present
##### Steps To Reproduce:

```
  tasks:
    - name: extract some files
      unarchive:
       src: mytar.tar.gz
       dest: /opt/
       creates: "/opt/directory_in_mytar/file_in_mytar.thing"
    - name: fixing unix permissions
      file:
        path: "/opt/directory_in_mytar"
        owner: "apache"
        group: "apache"
        mode: "u=rwX,g=rX,o=rX"
        recurse: yes
        state: directory
```
##### Expected Results:

No "changed" stated and no extraction of the archive if the file is present on the remote system.
##### Actual Results:

Unarchive module is always executed, never skipped/stating "OK".
