### ISSUE TITLE
ini_file create option break backwards incompatibility

### ISSUE THREAD

**Issue by jsok** [ansible/ansible-modules-core#5488]
##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
`ini_file`

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = /Users/jsok/.../ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY

Previous to 2.2, `ini_file` would create the `dest` file if it did not exist. However with the introduction of the `create` option in 2.2 this breaks backwards incompatibility since any module which previously assumed the `dest` would be created now instead fails with a error: "Destination /path/to/file.ini does not exist !"

Furthermore, the documentation still suggest that `dest` will be created.

Regression appears to have come from https://github.com/ansible/ansible-modules-core/pull/4544

##### STEPS TO REPRODUCE

Remove the ini file:, e.g. `rm /etc/pip.conf`

Run the task:

```yaml
- name: Create site-wide pip.conf
  ini_file:
    dest: /etc/pip.conf
    section: global
    option: index-url
    value: https://pypi.python.org
```

##### EXPECTED RESULTS

The INI file was created.

##### ACTUAL RESULTS

```
failed: [node-1] (item={u'section': u'global', u'option': u'index-url', u'value': u'https://pypi.python.org'}) => {"failed": true, "item": {"option": "index-url", "section": "global", "value": "https://pypi.python.org"}, "msg": "Destination /etc/pip.conf does not exist !", "rc": 257}
```
