### ISSUE TITLE
Unarchive module thinks existing local archive is nonexistent

### ISSUE THREAD

**Issue by agajdosi** [ansible/ansible-modules-core#5499]
Issue close to this one: #932 

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- unarchive module

##### ANSIBLE VERSION

```
ansible 2.1.2.0
```

##### CONFIGURATION

Nothing changed.

##### OS / ENVIRONMENT

from Fedora 24 workstation, to RHEL 7.2 workstation

##### SUMMARY

Unarchive module is unable to unzip file located on remote machine (I am using remote_src=yes), failing with: 
> FAILED! => {"failed": true, "msg": "file or module does not exist: /home/cdk/cdk.zip"}

When using default remote_src=no, module is able to unzip /home/agajdosi/cdk.zip on local machine and put it in /home/cdk/ on remote machine.

##### STEPS TO REPRODUCE

1. Put .zip file in remote machine.
2. Write unarchive task into playbook.
3. Run playbook.

```

---
- hosts: [rhel]
  remote_user: cdk
  tasks:
    - name: Unzip CDK zip
      unarchive:
        remote_src: yes
        src: /home/cdk/cdk.zip
        dest: /home/cdk/
```

##### EXPECTED RESULTS

Should unzip local cdk.zip file and extract it into home directory of user cdk.

##### ACTUAL RESULTS

Fails.

```
fatal: [foo]: FAILED! => {"failed": true, "msg": "file or module does not exist: /home/cdk/cdk.zip"}
```

**Comment by ansibot** [comment]
@dagwieers, @pileofrogs, ping. This issue is waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jotunskij** [comment]
I'm having the same problem.

**Commands**

```
- name: Download Docker binaries
  get_url:
    url: https://get.docker.com/builds/Linux/x86_64/docker-1.12.3.tgz
    dest: /tmp/docker.tgz
    mode: 700
    force: yes
    # Checksum is retrieved by appending .sha256 to the end of the above url
    checksum: "sha256:626601deb41d9706ac98da23f673af6c0d4631c4d194a677a9a1a07d7219fa0f"

- name: Unarchive Docker binares to /usr/local/bin
  unarchive:
    src: /tmp/docker.tgz
    dest: /usr/local/bin
    remote_src: yes
    extra_opts: ["strip-components=1"]
```

**Result**

```
TASK [install-docker : Unarchive Docker binares to /usr/local/bin] *************
Monday 14 November 2016  08:54:53 +0100 (0:00:04.071)       0:02:34.731 ******* 
fatal: [tt2-management]: FAILED! => {"failed": true, "msg": "file or module does not exist: /tmp/docker.tgz"}
```

**Versions** 
ansible 2.1.1.0 running on Mac OSX El Capitan 10.11.6 (15G1004)
