### ISSUE TITLE
ansible 2.2: docker_service 'Error starting project - '

### ISSUE THREAD

**Issue by jaccoh** [ansible/ansible-modules-core#5513]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
docker_service

##### ANSIBLE VERSION
ansible 2.2.0.0
  config file = /home/jhoeve-a/GitCollections/authdns-ansible-code/ansible.cfg
  configured module search path = Default w/o overrides

##### CONFIGURATION
In version 2.2 I use:
```
- name: starting bind9 in docker
  docker_service:
    pull: yes
    project_name: bind9
    timeout: 120
    definition:
      version: '2'
      services:
        bind9:
          restart: always
          logging:
            driver: syslog
            options:
              syslog-facility: local6
              tag: bind9
          image: docker.solvinity.net/bind9
          network_mode: host
          volumes:
            - /export/bind/chroot/usr/local/bind/data:/usr/local/bind/data
            - /export/bind/chroot/usr/local/bind/etc:/usr/local/bind/etc
  register: output
  tags:
    - docker
```
In version 2.1.2 I used (due to lack of pull statement):
```
- name: pull image bind9
  docker_image:
    name: docker.solvinity.net/bind9
    pull: yes
    force: yes
  tags:
    - docker

- name: starting bind9 in docker
  docker_service:
    # pull: yes
    project_name: bind9
    timeout: 120
    definition:
      version: '2'
      services:
        bind9:
          restart: always
          logging:
            driver: syslog
            options:
              syslog-facility: local6
              tag: bind9
          image: docker.solvinity.net/bind9
          network_mode: host
          volumes:
            - /export/bind/chroot/usr/local/bind/data:/usr/local/bind/data
            - /export/bind/chroot/usr/local/bind/etc:/usr/local/bind/etc
  register: output
  tags:
    - docker
```

##### OS / ENVIRONMENT
Ubuntu 16.04 / Ansible 2.2 from ppa

##### SUMMARY
It used to work in 2.1.2 but now fails.

##### STEPS TO REPRODUCE
Simply update to Ansible 2.2 and run playbook with snippet above.

##### EXPECTED RESULTS
Upgrade / Start docker container

##### ACTUAL RESULTS
```
fatal: [lnx2346vm.internal.asp4all.nl]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "api_version": null, 
            "build": false, 
            "cacert_path": null, 
            "cert_path": null, 
            "debug": false, 
            "definition": {
                "services": {
                    "bind9": {
                        "image": "docker.solvinity.net/bind9", 
                        "logging": {
                            "driver": "syslog", 
                            "options": {
                                "syslog-facility": "local6", 
                                "tag": "bind9"
                            }
                        }, 
                        "network_mode": "host", 
                        "restart": "always", 
                        "volumes": [
                            "/export/bind/chroot/usr/local/bind/data:/usr/local/bind/data", 
                            "/export/bind/chroot/usr/local/bind/etc:/usr/local/bind/etc"
                        ]
                    }
                }, 
                "version": "2"
            }, 
            "dependencies": true, 
            "docker_host": null, 
            "files": null, 
            "filter_logger": false, 
            "hostname_check": false, 
            "key_path": null, 
            "nocache": false, 
            "project_name": "bind9", 
            "project_src": null, 
            "pull": true, 
            "recreate": "smart", 
            "remove_images": null, 
            "remove_orphans": false, 
            "remove_volumes": false, 
            "restarted": false, 
            "scale": null, 
            "services": null, 
            "ssl_version": null, 
            "state": "present", 
            "stopped": false, 
            "timeout": 120, 
            "tls": null, 
            "tls_hostname": null, 
            "tls_verify": null
        }, 
        "module_name": "docker_service"
    }, 
    "msg": "Error starting project - "
}
```
