### ISSUE TITLE
mysql_user support for FUNCTION and PROCEDURE privileges

### ISSUE THREAD

**Issue by mklassen** [ansible/ansible-modules-core#5518]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
mysql_user

##### ANSIBLE VERSION
```
ansible 2.2.0.0
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Currently only `TABLE` privileges can be manipulated with `mysql_user`

Granting execute privileges on a mysql `FUNCTION` requires an SQL statement of the form

```
GRANT EXECUTE ON FUNCTION dbname.function_name TO 'user';
```

Unfortunately if the `FUNCTION` keyword is included in `mysql_user` modules's `priv` parameter it is not recognized as a valid privilege level. 

Object types of `FUNCTION` and `PROCEDURE` are supported by `mysql` (http://dev.mysql.com/doc/refman/5.7/en/grant.html) and it would be nice if the `priv` parameter supported specifying 'object_type', so that task like the following could be executed

```
- mysql_user:
    user: db_user
    priv: FUNCTION dbname.function_name:EXECUTE
    state: present
```
