### ISSUE TITLE
please add more options to authorized_key

### ISSUE THREAD

**Issue by mapreri** [ansible/ansible-modules-core#552]
##### ISSUE TYPE

Feature Idea
##### COMPONENT NAME

authorized_key module
##### ANSIBLE VERSION

N/A
##### SUMMARY

I'd like to be able to specify:
1) owner/group of the AuthorizedKeysFile directory (currently weird: it's the last processes users, in my case where I iterate over a list of user+keys and put them in /etc/ssh/authorized_keys)
2) mode of the file: there is rarely point in having it 0600 (the standard, ok, but still)....
3) owner/group of the file: let's say I don't want to let the user to be able to change the file on their own.

**Comment by techno-wizardry** [comment]
:+1: 

Specifically though get_url's `validate_certs=no` option.

Edited to fix formatting

**Comment by jody-frankowski** [comment]
How is this any better than using the file module?

**Comment by techno-wizardry** [comment]
My use case was:

```
# Using github url as key source
- authorized_key: user=charlie key=https://github.com/charlie.keys
```

But to an internal gitlab server without valid certs.  Ideally:

```
- authorized_key: user=charlie key=https://gitlab.internal/charlie.keys valid_certs=no
```

Which is the same as http://docs.ansible.com/ansible/get_url_module.html option.

I agree though - I wonder if the OP would be better using `file` after authorized_key?  I leave that to Mapreri though

**Comment by mapreri** [comment]
I do this:

``` yaml
- name: Install the ssh keys
  authorized_key:
        user={{ item.0.name }}
        key="{{ item.1.key }}"
        state={{ item.1.state }}
        path='/etc/ssh/authorized_keys/{{ item.0.name }}'
        manage_dir=no
  with_subelements:
     - users
     - keys
```

in a var file I have stuff like this:

``` yaml
users:
  - name: mattia
    keys:
      - key: "{{ lookup('file', 'mattia-043077617d4f87f89626b4bf420ea9b3') }}"
        comment: mattia@chase
        state: present
      - key: "{{ lookup('file', 'mattia-644f16a5e99646eea7e8aced5178fe72') }}"
        comment: mattia@kahlan
        state: present
```

So, I have all the keys in different files, and `authorized_key` takes care of concatenating them; that would be annoying to do without.
I found easier to use `authorized_key` and then add 3 more tasks to fix the permissions rather than using the the `file` module.
