### ISSUE TITLE
timeout: ios_config: save times out

### ISSUE THREAD

**Issue by chrmcd** [ansible/ansible-modules-core#5520]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ios_config
##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /home/mcdowell/git/stamnet-automasjon-ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

Pretty much default, nothing that applies to this.

##### OS / ENVIRONMENT

Ubuntu 16.04
##### SUMMARY

When using:
save: yes
in ios_config while trying to push configuration and saving it, ansible times out with the message:
timeout trying to send command: copy running-config startup-config
##### STEPS TO REPRODUCE

Try pushing any working configuration to an ios router with ios_config while the option "save: yes" is enabled.

```
    - name: Push full BGP border configuration to host
      ios_config:
        match: none
        authorize: yes
        save: yes
        auth_pass: "{{ root_pw }}"
        src: "{{ build_dir }}/{{ ansible_host}}/bgp_confg"
        host: "{{ host }}"
        username: "{{ default_user }}"
        password: "{{ ansible_ssh_pass|default(default_pw) }}"
        timeout: 120
      when: "'{{ os }}' == 'ios'"
```

##### EXPECTED RESULTS

I expected the running-config to be saved as the starting-config
##### ACTUAL RESULTS

```
The command timed out with the message:
timeout trying to send command: copy running-config startup-config
```
##### Possible solution
Change the module to use the command "write mem" instead of "copy running-config startup-config".
This is because the latter command asks you to specify a destination filename when run, and I assume it is stuck there, and therefore times out.
