### ISSUE TITLE
Ansible docker_container not exposing ports (2.2.0.0)

### ISSUE THREAD

**Issue by rilindo** [ansible/ansible-modules-core#5523]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
docker_container

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = /Users/rilindo/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
Using the following config:

```
stardust:ansible_docker_demo rilindo$ export ANSIBLE_CONFIG=$(pwd)/ansible.cfg
stardust:ansible_docker_demo rilindo$ export ANSIBLE_HOSTS=$(pwd)/hosts
stardust:ansible_docker_demo rilindo$ cat ansible.cfg 
[defaults]
roles_path=~/src/ansible_docker_demo/roles
stardust:ansible_docker_demo rilindo$ cat hosts 
192.168.64.8
```

##### OS / ENVIRONMENT
- Workstation OS X MacSiera
- Server: Ubuntu 14.04 with port 2375 open for docker
- Python version: 2.7.10
List of python modules:

```
altgraph (0.10.2)
ansible (2.2.0.0)
argparse (1.2.1)
awscli (1.7.36)
bdist-mpkg (0.5.0)
bonjour-py (0.3)
boto (2.10.0)
botocore (1.0.1)
cached-property (1.3.0)
colorama (0.3.3)
docker-compose (1.9.0rc3)
docker-py (1.10.6)
docker-pycreds (0.2.1)
dockerpty (0.4.1)
docopt (0.6.2)
docutils (0.12)
ecdsa (0.13)
elasticsearch (1.6.0)
enum34 (1.1.6)
```

##### SUMMARY
The docker_container does not appear to be configuring and exposing the ports

##### STEPS TO REPRODUCE
Here is the code I am using:

```

---
- hosts: all
  remote_user: ubuntu
  vars_files:
    - secret.yml
  become: yes
  become_method: sudo
  tasks:
  - name: create custom docker container
    docker_container:
      name: mycustomcontainer
      image: rilindo/myapacheweb:v1
      state: present
      network_mode: bridge
      exposed_ports: "80"
      published_ports: "80:80"
```

##### EXPECTED RESULTS
I expect to see this in docker ps -a

```
root@ubuntu:~# docker run -d -p 80:80 rilindo/myapacheweb:v1 --name mycontainer
30d6c5ceb274bf4e0b3767eac0c3df3ed9b58c480f0d25378c1e66bf2b106767
root@ubuntu:~# docker ps -a
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS              PORTS                NAMES
30d6c5ceb274        rilindo/myapacheweb:v1   "/bin/sh -c 'apachect"   3 seconds ago       Up 2 seconds        0.0.0.0:80->80/tcp   angry_stonebraker
root@ubuntu:~# 
```
##### ACTUAL RESULTS
This is what it looks like from my workstation

```
stardust:ansible_docker_demo rilindo$ ansible-playbook create_custom_docker_container.yml 

PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [192.168.64.8]

TASK [create custom docker container] ******************************************
changed: [192.168.64.8]

PLAY RECAP *********************************************************************
192.168.64.8               : ok=3    changed=1    unreachable=0    failed=0   
```

So far, so good.

This is what I see on the docker host:

```
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS              PORTS               NAMES
ff35fdf076de        rilindo/myapacheweb:v1   "/bin/sh -c 'apachect"   57 seconds ago      Created                                 mycustomcontainer
```

Note that the ports do not appear to be present under the **PORTS** column
