### ISSUE TITLE
rds param group module to enable logging 

### ISSUE THREAD

**Issue by tuwid** [ansible/ansible-modules-core#5544]
There is no option to enable logging by default 
##### ISSUE TYPE
 - Bug Report
 - Feature Idea
 - Documentation Report

##### COMPONENT NAME
rds_param_group_module

##### SUMMARY
There is no option to change logging behaviour on RDSs

**Comment by ansibot** [comment]
@ansible ping, this issue is waiting for your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by tuwid** [comment]
Managed a workaround like this : 

```
    - name: pre-Create logging for RDS
      rds_param_group:
          state: present
          name: rdsgroup
          description: 'Logging group and stuff'
          engine: 'mysql5.6'
          params:
              log_output: "FILE"
              # log_queries_not_using_indexes: "1"
              # general_log : "1"
              # slow_query_log : "2"
              # long_query_time : "2"
      tags: [database,init,web]
```
