### ISSUE TITLE
cloudformation  zero length field name in format when creating a stack

### ISSUE THREAD

**Issue by skapykat** [ansible/ansible-modules-core#5551]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

cloudformation
##### ANSIBLE VERSION

```
2.3.0
```

##### SUMMARY

When running the Cloudformation module, the tasks says it fails with "ValueError: zero length field name in format". However, the stack does get created correctly.

##### STEPS TO REPRODUCE

```
---
- name: Launch Base VPC
  cloudformation:
    stack_name: "{{ vpc_stack_name }}" # Test-VPC
    state: "present"
    region: "{{ vpc_region }}
    template: "files/VPC.yml"
    template_parameters:
      ClassC: "{{ vpc_classc }}"
    tags:
      BuiltWith: "Ansible"

```

##### EXPECTED RESULTS

Cloudformation stack gets built and the tasks returns with changed or OK
##### ACTUAL RESULTS

Stack gets created, but the tasks fails blocking further tasks from being ran.

```
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "/tmp/ansible_n9rFoj/ansible_module_cloudformation.py:203: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6\n  elif hasattr(err, 'message'):\n/tmp/ansible_n9rFoj/ansible_module_cloudformation.py:204: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6\n  error = err.message + ' ' + str(err) + ' - ' + str(type(err))\nTraceback (most recent call last):\n  File \"/tmp/ansible_n9rFoj/ansible_module_cloudformation.py\", line 479, in <module>\n    main()\n  File \"/tmp/ansible_n9rFoj/ansible_module_cloudformation.py\", line 407, in main\n    result = stack_operation(cfn, stack_params['StackName'], 'CREATE')\n  File \"/tmp/ansible_n9rFoj/ansible_module_cloudformation.py\", line 262, in stack_operation\n    ret = get_stack_events(cfn, stack_name)\n  File \"/tmp/ansible_n9rFoj/ansible_module_cloudformation.py\", line 237, in get_stack_events\n    eventline = 'StackEvent {} {} {}'.format(e['ResourceType'], e['LogicalResourceId'], e['ResourceStatus'])\nValueError: zero length field name in format\n", "module_stdout": "", "msg": "MODULE FAILURE"}

```
