### ISSUE TITLE
Cannot pull facts with snmp_facts on ASA

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ansible/ansible-modules-core#5553]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

snmp_facts
##### ANSIBLE VERSION

```
ansible --version
2.3.0 (commit 20161110.abc9133)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

inventory   = ./hosts
gathering = explicit
roles_path = /home/actionmystique/Program-Files/Ubuntu/Ansible/git-Ansible/Roles/roles
private_role_vars = yes
log_path = /var/log/ansible.log
fact_caching = redis
fact_caching_timeout = 86400
retry_files_enabled = False
##### OS / ENVIRONMENT
- **Local host**: Ubuntu 16.10 4.8
- **Target nodes**: ASAv 9.5
##### SUMMARY

Running snmp_facts on this particular type of target triggers a fatal error (Permission denied), whereas I can manually login into the target node with SSH or run snmp_facts without issue on IOSv targets.
We will continue to experience issues with this module as long as the API is not consistent with other networking modules (no provider, no ssh_keyfile, no password,...). Cf. the [provider proposal](https://github.com/ansible/ansible-modules-extras/issues/3176).
##### STEPS TO REPRODUCE

```
- name: Fetching SNMPv{{ snmp.new_version }} facts from the remote node
  snmp_facts:
        community: "{{ snmp.ssh.community }}"
        host: "{{ snmp.ssh.host }}"
        version: "{{ snmp.ssh.version }}"
  register: facts
```
##### EXPECTED RESULTS

Successful snmp_facts
##### ACTUAL RESULTS

```
fatal: [ASAv2]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Permission denied (publickey,password).\r\n", "unreachable": true}
```
Despite the fact that SNMP is configured on the target with the same community:
```
sh run | inc snmp   
...
snmp-server host management 172.21.100.1 community ***** version 2c
snmp-server location California
snmp-server contact xxxxxxxxxxxxxxxx
snmp-server community *****
snmp-server enable traps syslog
...
```
Also:
```
ssh admin@172.21.100.251
Type help or '?' for a list of available commands.
ASAv1> en
Password: **********
ASAv1# sh ver

Cisco Adaptive Security Appliance Software Version 9.5(2)204 
Device Manager Version 7.5(2)
...
```
