### ISSUE TITLE
apache2_module fails on enabling shib2 when it's already enabled

### ISSUE THREAD

**Issue by geekofalltrades** [ansible/ansible-modules-core#5559]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
apache2_module

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /home/wmd/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
My non-default configuration:

```
gathering = smart
fact_caching = jsonfile
fact_caching_connection = /var/tmp/ansible_facts
fact_caching_timeout = 86400

jinja2_extensions = jinja2.ext.do

ask_pass = True
ask_sudo_pass = True
ask_vault_pass = True
```

But this problem also affects a coworker whose configuration is different than mine.

##### OS / ENVIRONMENT

Ubuntu 16.04 host managing Ubuntu 16.04 nodes.

##### SUMMARY

When using apache2_module to enable the third-party shib2 (shibboleth) module, apache2_module fails if the module is already enabled. It does not fail in check mode.

##### STEPS TO REPRODUCE

```
- name: Install apache2 and apache2 shibboleth module
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apache2
    - libapache2-mod-shib2

- name: Enable shib2 apache module
  apache2_module:
    name: shib2
    state: present
```

##### EXPECTED RESULTS

apache2_module to correctly identify that the shib2 module is already enabled, and then *not* fail.

##### ACTUAL RESULTS

```
TASK [wtf : Enable shib2 apache module] ****************************************
fatal: [yorkium]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to set module shib2 to enabled: Module shib2 already enabled\n", "rc": 0, "stderr": "", "stdout": "Module shib2 already enabled\n", "stdout_lines": ["Module shib2 already enabled"]}
	to retry, use: --limit @/home/wmd/git/ehit/projects/ansible/wtf.retry
```
