### ISSUE TITLE
vmware_vm_shell: "The guest operations agent could not be contacted"

### ISSUE THREAD

**Issue by mikecali** [ansible/ansible-modules-core#5561]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
vmware_vm_shell

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /home/mikecali/dao-infra/ansible.cfg
  configured module search path = ['./library']
Python 2.7.5
Vsphere 6.0
```

##### CONFIGURATION
Default configuration

##### OS / ENVIRONMENT
RHEL 7.2

##### SUMMARY
vmware_vm_shell module seems unable to find the vm shell on Vcenter even with successful login to vsphere. I am using this module to execute a script that is pre-loaded to the template that I baked using packer.

##### STEPS TO REPRODUCE
running playbook below

```

- name: Reconfigure VM network
  hosts: localhost
  gather_facts: False

  vars:
    vsphere: alabs
    instance_set: chorus-7.2

    pre_tasks:
      - include_vars: ../../secrets/{{vsphere}}-vsphere.yml
      - include_vars: ../../vars/global-constants.yml
      - include_vars: ../../vars/{{instance_set}}-instances.yml

  tasks:
  - name: Reconfigure instance neworking
    vmware_vm_shell:
      hostname: 172.17.203.6
      username: create_vm
      password: 'xxxxxxx'
      datacenter: ALABS-xxxx
      vm_id: RH-BUILD2
      vm_id_type: vm_name
#     validate_certs: false
      vm_username: rhel
      vm_password: *****
      vm_shell: /dnz_support/ngito-reconfigure-network.sh
      vm_shell_args: " >> reconfigure-networking.log"
      vm_shell_env:
        - "RECONFIGURE_IPADDR=172.17.203.10"
        - "RECONFIGURE_NETMASK=255.255.255.192"
        - "RECONFIGURE_GW=172.17.203.1"
        - "RECONFIGURE_NAME=ens32"
        - "RECONFIGURE_DEVICE=ens32"
        - "RECONFIGURE_ONBOOT=yes"
        - "RECONFIGURE_TYPE=Ethernet"
        - "RECONFIGURE_BOOTPROTO=none"
        - "REBOOT_ON_RECONFIGURE=true"
      vm_shell_cwd: "/tmp"

```

##### EXPECTED RESULTS

vmware_vm_shell should login to the server using the username and password provided and execute the script /dnz_support/ngito-reconfigure-network.sh which is preloaded to the OS and then reboot.

##### ACTUAL RESULTS
PLAY [Reconfigure VM network] **************************************************

```
TASK [Reconfigure instance neworking] ******************************************
task path: /home/mikecali/dao-infra/playbooks/vcenter/guest-create-pysphere.yml:85
Using module file /home/mikecali/dao-infra/library/vmware_vm_shell.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: mikecali
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1478813226.44-34711828301532 `" && echo ansible-tmp-1478813226.44-34711828301532="` echo $HOME/.ansible/tmp/ansible-tmp-1478813226.44-34711828301532 `" ) && sleep 0'
<localhost> PUT /tmp/tmpTmMbHC TO /home/mikecali/.ansible/tmp/ansible-tmp-1478813226.44-34711828301532/vmware_vm_shell.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/mikecali/.ansible/tmp/ansible-tmp-1478813226.44-34711828301532/ /home/mikecali/.ansible/tmp/ansible-tmp-1478813226.44-34711828301532/vmware_vm_shell.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /home/mikecali/.ansible/tmp/ansible-tmp-1478813226.44-34711828301532/vmware_vm_shell.py; rm -rf "/home/mikecali/.ansible/tmp/ansible-tmp-1478813226.44-34711828301532/" > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "datacenter": "ALABS-Wellington", 
            "hostname": "172.17.203.6", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "username": "administrator@vsphere.local", 
            "validate_certs": true, 
            "vm_id": "RH-BUILD2", 
            "vm_id_type": "vm_name", 
            "vm_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "vm_shell": "/dnz_support/ngito-reconfigure-network.sh", 
            "vm_shell_args": " >> reconfigure-networking.log", 
            "vm_shell_cwd": "/tmp", 
            "vm_shell_env": [
                "RECONFIGURE_IPADDR=172.17.203.10", 
                "RECONFIGURE_NETMASK=255.255.255.192", 
                "RECONFIGURE_GW=172.17.203.1", 
                "RECONFIGURE_NAME=ens32", 
                "RECONFIGURE_DEVICE=ens32", 
                "RECONFIGURE_ONBOOT=yes", 
                "RECONFIGURE_TYPE=Ethernet", 
                "RECONFIGURE_BOOTPROTO=none", 
                "REBOOT_ON_RECONFIGURE=true"
            ], 
            "vm_username": "rhel"
        }, 
        "module_name": "vmware_vm_shell"
    }, 
    "msg": "The guest operations agent could not be contacted."
}
	to retry, use: --limit @/home/mikecali/dao-infra/playbooks/vcenter/guest-create-pysphere.retry

PLAY RECAP *********************************************************************
localhost                  : ok=5    changed=1    unreachable=0    failed=1   
```
