### ISSUE TITLE
lineinfile module does not detect the existence of multiline strings in file

### ISSUE THREAD

**Issue by dmlary** [ansible/ansible-modules-core#557]
With the following tasks, I am able to create the file correctly on the first run, but on the second run, the multiple line chunk is written a second time.

Playbook tasks:

``` yaml
- name: single line in file
  lineinfile:
    dest: /tmp/junk
    create: true
    state: present
    line: "# single line in file"
- name: Multiple lines in file
  lineinfile:
    dest: /tmp/junk
    create: true
    state: present
    line: |
      # These are my multiple lines of text
      # they are really long and important
```

After the first run of the playbook, the contents of the file are correct:

```
root@trusty:~# cat /tmp/junk
# single line in file
# These are my multiple lines of text
# they are really long and important

```

Following the second run of the playbook, the multi-line chunk is in the file twice:

```
root@trusty:~# cat /tmp/junk
# single line in file
# These are my multiple lines of text
# they are really long and important

# These are my multiple lines of text
# they are really long and important

```

**Comment by abadger** [comment]
This is a known limitation of lineinfile with no plans to add multiline functionality.  from the docs:

> This module will search a file for a line, and ensure that it is present or absent. This is primarily useful when you want to change a single line in a file only. See the replace module if you want to change multiple, similar lines; for other cases, see the copy or template modules.
> http://docs.ansible.com/lineinfile_module.html

# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

In particular, we believe you have asked for lineinfile to operate on multiline strings.

However, lineinfile is only designed to work on one line of text, not multiple lines.

We would suggest: Using the replace module instead.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by dmlary** [comment]
Toshio,

I'm probably missing something, but I'm unable to see how to use the replace module for my purposes.  The same is true for the copy and template modules.

The scenario I am handling is that I have a non-empty configuration file that is not solely under ansible management.  I need to add a multiline block to the end of that file if it's not already present.  I'm not replacing an existing string, and I'm not assembling the majority of the file's contents.  The configuration file is `/etc/ufw/before.rules`; for more details, take a look at the **Port Redirections** section of the `ufw-framework` manpage -- http://manpages.ubuntu.com/manpages/precise/en/man8/ufw-framework.8.html.

Is there some arrangement of arguments, for any of these modules, that allow me to perform this task?  Or is this something that can't be done in ansible without resorting to a shell script?

**Comment by abadger** [comment]
These kinds of questions are probably best asked on the mailing list as I'm more of a coder than a sysadmin; the user list will have more people who have looked at problems like this and have a broader set of potential solutions.  That said here's a few things I'd try if faced with this:
- If there's only a few lines, I'd try using a few separate lineinfiles to do this:

```
- hosts: localhost
  tasks:
  - lineinfile:
      create: yes
      dest: /var/tmp/example
      insertafter: EOF
      state: present
      line:  First line
  - lineinfile:
      dest: /var/tmp/example
      insertafter: First line
      state: present
      line: Second line
```
- Other people advocate using template.  The file has to be under ansible's control for this.
- Might be able to make a sort of hybrid of ansible's control and another program's control using assemble.  Have the other program write out config then use ansible's fetch module to copy the file to a local directory with the fragments of config that you want ansble to append to the file.  Then use assemble to put together all of the pieces.
- Lastly, there's no shame in using shell :-)  I often find that shell can have undesired consequences but it's been the sysadmin's friend for decades so if you can clearly visualize the solution in shell there's no reason not to make use of that as a solution.
