### ISSUE TITLE
args alias unsupported by service module

### ISSUE THREAD

**Issue by jimmymccrory** [ansible/ansible-modules-core#5584]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

service module

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

Ubuntu 16.04

##### SUMMARY

The 'args' alias for the 'arguments' parameter is not recognized as valid by the service module.

##### STEPS TO REPRODUCE

```
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - service:
        name: ssh
        state: started
        args: ""
```

##### EXPECTED RESULTS

The playbook to complete successfully.

##### ACTUAL RESULTS

```
fatal: [localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "args": "",
            "name": "ssh",
            "state": "started"
        }
    },
    "msg": "unsupported parameter for module: args"
}
```
