### ISSUE TITLE
Package module fails to install multiple packages on OpenBSD

### ISSUE THREAD

**Issue by sparunakian** [ansible/ansible-modules-core#5595]
Hi!

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
- package

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /home/stephane/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

Nothing special

##### OS / ENVIRONMENT

Ansible running from ArchLinux, managing an OpenBSD machine

##### SUMMARY

When using the module package for installing multiple packages on OpenBSD, the installation fails. It works if the module openbsd_pkg is called directly.

##### STEPS TO REPRODUCE

Just use this task, to install packages on an OpenBSD machine:
```yaml
- name: install essential packages
  package: name={{ item }} state=present
  with_items:
    - curl
    - lsof
```

##### EXPECTED RESULTS

The packages curl and lsof should be installed after the execution of this task.

##### ACTUAL RESULTS

The task fails, without anything done. Curl and lsof are not installed.

It returns this, in verbose mode:
```
failed: [openbsd-machine] (item=[u'curl', u'lsof']) => {
    "failed": true, 
    "invocation": {
        "module_args": {
            "build": false, 
            "name": "['curl', 'lsof']", 
            "ports_dir": "/usr/ports", 
            "state": "present"
        }
    }, 
    "item": [
        "curl", 
        "lsof"
    ], 
    "msg": "failed in get_package_state(): Error from http://ftp.eu.openbsd.org/pub/OpenBSD/5.7/packages/amd64/lsof].tgz\nftp: Error retrieving file: 404 Not Found\n"
}
```
If I use the module openbsd_pkg directly, it works:
```yaml
- name: install essential packages
  openbsd_pkg: name={{ item }} state=present
  with_items:
    - curl
    - lsof
```
Note that the package module works with only one package (without with_items)

Let me know if I can be of any help concerning this issue!

Stéphane
