### ISSUE TITLE
Synchronize module ignores remote_user parameter

### ISSUE THREAD

**Issue by RokLenarcic** [ansible/ansible-modules-core#5635]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Module `synchronize`

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT
macOS Sierra

##### SUMMARY
Synchronize module doesn't use user specified in `remote_user` to connect to another system.
Works correctly in `2.0.2.0`.

##### STEPS TO REPRODUCE
You need a machine that runs Ansible.

A host, let's call it `staging_machine`, where the `ansible_user` is `staging_user`.

Another host called `my_server`, where the `ansible_user` is `deploy_user`. 

Both the ansible machine and `staging_machine` have keys on `my_server` for `deploy_user`.

Then run
```
- name: Deploy java versions and scripts
  hosts: my_server
  any_errors_fatal: true
  tasks:
    - name: "Install JDK"
      synchronize: src="jdk_folder" dest="deploy_area/jdkfolder/"
      delegate_to: staging_machine
      remote_user: "deploy_user"
```

##### EXPECTED RESULTS
Files being copied.

##### ACTUAL RESULTS
Server `staging_machine` tries to connect with it's own ansible_user `staging_user` instead of with `deploy_user`.

```
TASK [Install JDK] *************************************************************
staging_user@my_server's password: 
```

This works in `2.0.2.0`.
