### ISSUE TITLE
count_tag ignored tag value

### ISSUE THREAD

**Issue by sikanhe** [ansible/ansible-modules-core#5643]
##### ISSUE TYPE
 - Bug Report
##### COMPONENT NAME
ec2

##### ANSIBLE VERSION
ansible 2.2.0.0

##### CONFIGURATION
[defaults]
host_key_checking = False
inventory = hosts.ini
vault_password_file = vault_pass.txt

[ssh_connection]
ssh_args=-o ForwardAgent=yes
control_path = %(directory)s/%%h-%%r

##### OS / ENVIRONMENT
OS X El capitan

##### SUMMARY
when using count_tag like so: 

`count_tag: Name=TagValue `

or 

```
count_tag: 
  Name: TagValue 
```
 In both cases ec2 will only check for existance of tags named Name but failed to check for the value. So even if I have an instance already running with Name=SomeOtherValue. The  instance will not be instantiated because it is not checking for the value I specified (needing to be TagValue)

However, it works if I format it like this: 
`count_tag: { "TagName": "TagValue" }`

##### STEPS TO REPRODUCE
```
---
- hosts: localhost
  connection: local
  vars_files:
    - vault/aws_user.yml
  vars:
    ami_id: ami-c8580bdf
  tasks:
  - name: Provision a set of app servers
    ec2:
      aws_access_key: "{{ access_key }}"
      aws_secret_key: "{{ secret_key }}"
      key_name: quesly_app
      assign_public_ip: yes
      group: ['home_access', 'instances']
      instance_type: t2.small
      region: us-east-1
      image: "{{ ami_id }}"
      vpc_subnet_id: subnet-094fd323
      exact_count: 1
      count_tag:
        TagName: TagValue
      instance_tags:
        TagName: TagValue
      # IAM role
      instance_profile_name: app_server
      wait: yes
    register: ec2
```

##### EXPECTED RESULTS
A new instance with TagName=TagValue should be created

##### ACTUAL RESULTS
Ansible thinks the instance has already been created because another instance with the same tag name TagName=SomeOtherTagValue exists
