### ISSUE TITLE
Mount nfs to AIX managed host

### ISSUE THREAD

**Issue by markusyou** [ansible/ansible-modules-core#5656]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- mount
##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = /home/admin/SA/myou/.ansible.cfg
  configured module search path = Default w/o overrides

```

##### OS / ENVIRONMENT

Running Ansible from Red Hat Enterprise Linux Server release 6.7 (Santiago)
managing AIX 7.1.0.0

##### SUMMARY

Unable to mount NFS filesystem to managed host.  Tried NFS server on Redhat and NFS server on AIX,

##### STEPS TO REPRODUCE

```
---
- hosts: all
  tasks:
  - name: Mount AIX Filesets
    become: yes
    mount:
      name: /mnt
      src: nfshost:/home/ftp
      fstype: nfs
      state: mounted
```

##### ACTUAL RESULTS

Created a file /etc/fstab file as opposed to adding an entry in /etc/filesystems 

```
TASK [Mount /mnt] **************************************************************
fatal: [is-deva30nb]: FAILED! => {"changed": false, "failed": true, "msg": "Error mounting /mnt: mount: /mnt is not a known file system\n"}

```

**Comment by ansibot** [comment]
@ansible ping, this issue is waiting for your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jctanner** [comment]
@markusyou are you saying that it could not mount on the rhel server either?

needs_info

**Comment by markusyou** [comment]
@jctanner The issue looks to only be related to mounting to an AIX managed host. Aix uses /etc/filesystems not /etc/fstab

**Comment by chuckyz** [comment]
@markusyou have you tried using the `fstab` flag like the following:

```
---
- hosts: all
  tasks:
  - name: Mount AIX Filesets
    become: yes
    mount:
      name: /mnt
      src: nfshost:/home/ftp
      fstype: nfs
      state: mounted
      fstab: /etc/filesystems
```
