### ISSUE TITLE
add_host should accept a list in the groups parameter

### ISSUE THREAD

**Issue by bmalynovytch** [ansible/ansible-modules-core#5683]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
core module: `add_host`

##### ANSIBLE VERSION
```
ansible 2.1.2.0
  config file = /path/to/my/custom/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
```
[defaults]
host_key_checking = False
forks=500
pipelining=True
retry_files_enabled = False
force_handlers = True

[ssh_connection]
control_path = %(directory)s/%%h-%%p-%%r
ssh_args = -o ControlMaster=auto -o ControlPersist=30m
```

##### OS / ENVIRONMENT
Mac OS X 10.12.1

##### SUMMARY
Adding a host with `add_host` module fails when `groups` is provided as a list.

##### STEPS TO REPRODUCE
```
- name: Add backup server to inventory
  add_host:
  args:
    name: backup
    groups:
      - backup
      - unmanaged
    ansible_host: XXX
    ansible_port: XXX
    ansible_user: XXX
  changed_when: false
  always_run: yes
```

##### EXPECTED RESULTS
Should run without error

##### ACTUAL RESULTS
Fails with following error:
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'list' object has no attribute 'split'
fatal: [web1]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}
```
