### ISSUE TITLE
set_fact doesn't override role parameters

### ISSUE THREAD

**Issue by hryamzik** [ansible/ansible-modules-core#5686]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

set_fact

##### ANSIBLE VERSION

```
2.2.0.0
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

set_fact doesn't override role parameters

##### STEPS TO REPRODUCE

playbook:
```yml
- hosts: all
  become: true
  roles:
    - role: my_role
      some_var: a
```

my_role/tasks/main.yml
```yml
- set_fact:
      some_var: b
```

##### EXPECTED RESULTS

some_var: b

##### ACTUAL RESULTS

some_var: a
