### ISSUE TITLE
ec2_elb_facts should support check mode

### ISSUE THREAD

**Issue by tomislacker** [ansible/ansible-modules-core#5701]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ec2_elb_facts

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = 
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
*N/A*

##### OS / ENVIRONMENT
*N/A*

##### SUMMARY
Since the `ec2_elb_facts` is strictly a read-only operation, it should support running with `--check`

##### STEPS TO REPRODUCE

```sh
ansible-playbook \
    -i hosts \
    -l my-elb-host \
    ec2_elb_facts_check.yml \
    -vv \
    --check
```

```yaml
- hosts: all
  connection: local
  gather_facts: no

  tasks:
    - name: Collect ELB facts
      ec2_elb_facts:
        names: "my-elb"
        region: "us-east-1"
      register: elbfacts
      tags: always
```

##### EXPECTED RESULTS
It would be expected that `ec2_elb_facts` would still fetch the instance information. This being omitted, prevents the ability to enumerate ELB instance hosts, dynamically add them to the inventory, and then conduct `--check` mode against what would *actually* be getting done.

##### ACTUAL RESULTS

```
TASK [Collect ELB facts] ***********************************************
task path: /Projects/ec2_elb_facts_check.yml:6
skipping: [my-elb-host] => {
    "changed": false, 
    "skipped": true
}

MSG:

remote module (ec2_elb_facts) does not support check mode
```
