### ISSUE TITLE
vsphere_guest: datastore does not exist when deploying on esxi 6

### ISSUE THREAD

**Issue by christiancruz11** [ansible/ansible-modules-core#5718]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

vsphere_guest
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY
We have a playbook that provision a VM. We run this from Ansible tower.
It works on ESXi 5 but fails on ESXi 6.
We tried to hard code the datastore but still same error.

##### STEPS TO REPRODUCE

```
This the play where it failed. This play is run from a role that we created.
   - name: Creating VM
     vsphere_guest:
      vcenter_hostname: "{{env}}"
      username: "{{user_name}}"
      password: "{{password}}"
      guest: "{{item.0}}"
      state: powered_on
      vm_extra_config:
       vcpu.hotadd: yes
       mem.hotadd:  yes
      vm_disk:
        disk1:
         size_gb: 70
         type: thin
         datastore: "ESX_PRD_VIDEO_APP_Green_DP0_DS1"
      vm_nic:
        nic1:
         type: vmxnet3
         network: "{{vlan_prefix}}130"
         network_type: dvs
      vm_hardware:
       memory_mb: "{{item.1}}"
       num_cpus: "{{item.2}}"
       osid: centos64Guest
       scsi: paravirtual
       vm_cdrom:
        type: "iso"
        iso_path: "{{isods}}/ISOs/kdc-auto-build.{{item.0}}.iso"
      esxi:
       datacenter: "{{datacenter}}"
       hostname: "{{esx_server.stdout}}"
      validate_certs: False
     register: vm_create
     with_together:
       - "{{server_name}}.ds.acc.co.nz"
       - "{{memory}}"
       - "{{cpu}}"

```

##### EXPECTED RESULTS

It should create the VM and boot from ISO.
##### ACTUAL RESULTS

It failed and the error is the datastore does not exist.
"msg": "Datastore: ESX_PRD_VIDEO_APP_Green_DP0_DS1 does not appear to exist"}

```
TASK [vm-provision : Creating VM] **********************************************
task path: /var/lib/awx/projects/vm-provision-project-test/roles/vm-provision/tasks/create-vm.yml:16
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: ansible
<127.0.0.1> EXEC /bin/sh -c 'LANG=C LC_ALL=C LC_MESSAGES=C /usr/bin/python2.6 && sleep 0'
failed: [localhost] (item=[u'kdctestguest99.ds.acc.co.nz', u'2048', u'1']) => {"failed": true, "invocation": {"module_args": {"cluster": null, "esxi": {"datacenter": "Kapiti Datacenter", "hostname": "kdcvmh5101.ds.acc.co.nz"}, "force": false, "from_template": null, "guest": "kdctestguest99.ds.acc.co.nz", "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "power_on_after_clone": true, "resource_pool": null, "snapshot_to_clone": null, "state": "powered_on", "template_src": null, "username": "DS\\cruzc", "validate_certs": false, "vcenter_hostname": "kdcwvc0003", "vm_disk": {"disk1": {"datastore": "ESX_PRD_VIDEO_APP_Green_DP0_DS1", "size_gb": 70, "type": "thin"}}, "vm_extra_config": {"mem.hotadd": true, "vcpu.hotadd": true}, "vm_hardware": {"memory_mb": "2048", "num_cpus": "1", "osid": "centos64Guest", "scsi": "paravirtual", "vm_cdrom": {"iso_path": "ESX_DEV_Green_DP8_SR1/ISOs/kdc-auto-build.kdctestguest99.ds.acc.co.nz.iso", "type": "iso"}}, "vm_hw_version": null, "vm_nic": {"nic1": {"network": "dvPortGroup_DEV_Green_PortGroup_130", "network_type": "dvs", "type": "vmxnet3"}}, "vmware_guest_facts": null}, "module_name": "vsphere_guest"}, "item": ["kdctestguest99.ds.acc.co.nz", "2048", "1"], "msg": "Datastore: ESX_PRD_VIDEO_APP_Green_DP0_DS1 does not appear to exist"}
```
