### ISSUE TITLE
blockinfile marker is null while replace the last line

### ISSUE THREAD

**Issue by richardweiu** [ansible/ansible-modules-core#5740]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- blockinfile

##### ANSIBLE VERSION

```
ansible 2.2.0.0
```

##### CONFIGURATION

the default setting

##### OS / ENVIRONMENT

ubuntu 14.04 3.16.0-37-generic 
##### SUMMARY

- I don't want inser any marker info,but when I set 

+ `no` , it will inser `False` befor and after the content
+ `null`,it will inser `None` befor and after the content
+ `""`, it will inser space line befor and after the content

- when set it to "",it will replace the last line

##### STEPS TO REPRODUCE

```
        - name: update nrpe config in /etc/nagios
          blockinfile:
                backup: yes
                marker: ""
                dest: /path/to/nrpe_local.cfg
                block: command[check_tomcat_curl]=/usr/local/control/nrpe_check/check_tomcat.sh

```

##### EXPECTED RESULTS

I just don't inser any  marker info

##### ACTUAL RESULTS

befor running playbook the file is
```
123456
123456
```

after running playbook the file is

```
123456

command[check_tomcat_curl]=/usr/local/control/nrpe_check/check_tomcat.sh

```
