### ISSUE TITLE
 win_service trouble with Windows 2012R2

### ISSUE THREAD

**Issue by tdjfr** [ansible/ansible-modules-core#5751]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.1.1.0

```

##### SUMMARY

I want to start (or stop) service on Windows2012R2 server and take this error
An exception occurred during task execution. The full traceback is:
At C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1480354748.14-17345256285605\win_service.ps1:296 char:5
+     Set-Attr $result "start_mode" $svcMode.StartMode.ToLower()
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The service is a service provided by one editor (not a standard windows service) and run under a specific user.

With a standard windows service (like CertPropSvc) the module runs fine.

##### STEPS TO REPRODUCE

```
- name: Start services
  hosts: srv
  vars:
    services:
      - 'service_name'
  tasks:
    - name: Start services
      win_service:
        name: '{{ services }}'
        state: started

```

##### ACTUAL RESULTS

```

```
