### ISSUE TITLE
docker_container never starts containers

### ISSUE THREAD

**Issue by gvilarino** [ansible/ansible-modules-core#5774]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
`docker_container`

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /usr/src/playbooks/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT
```
Linux 37059fd9679f 3.13.0-91-generic #138-Ubuntu SMP Fri Jun 24 17:00:34 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

##### SUMMARY
Containers are created with the wrong name, outside network and never start

##### STEPS TO REPRODUCE
Run a playbook that does the following:

```
- name: ensure docker network exists
  docker_network:
    appends: True
    connected:
      - existing_container
    name: my_network
    state: present

- name: ensure new container is running
  docker_container:
    image: mongo:3.2
    name: new-container
    networks:
      - name: my_network
    state: started
```

##### EXPECTED RESULTS
A container named `new-container` running, and in the `my_networ` network

##### ACTUAL RESULTS
Container with generic name is `Created` outside network, not running

[`ansible` `-vvvvv` output](https://gist.github.com/gvilarino/5b4c71773dee722005ca3777230f1cda)

[`dockerd -D` output](https://gist.github.com/gvilarino/b8acb2d76dfdc02f133da29766718614)

`docker ps -a` yields:
```
CONTAINER ID        IMAGE                                            COMMAND                  CREATED             STATUS              PORTS               NAMES
c2d470cdcc51        mongo:3.2                                        "/entrypoint.sh mongo"   21 minutes ago      Created                                 stupefied_pasteur
```

According to the docker daemon logs, the daemon never gets the `/start` instruction, just the `/create`

**Comment by ansibot** [comment]
@ansible ping, this issue is waiting for your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by gitgc** [comment]
I'm seeing the exact same issue. Container with state "started" creates a container with a generic Docker assigned name instead of one specified in Ansible, and with "created" status instead of running.

I'm running Ansible 2.2.0.0 with docker-py 1.10.6:

```
- name: Seed tenant database
  docker_container:
    name: "test"
    image: "mydockerhub/image:latest"
    command: "create-tenant"
    labels:
      tenant: "{{ tenant_name }}"
    state: started
```

results in a Docker container with a generic name like "hungy_tesla" and STATUS of "Created" instead of "Running".
