### ISSUE TITLE
docker_container pull 'Get http://: http: no Host in request URL'

### ISSUE THREAD

**Issue by davegallant** [ansible/ansible-modules-core#5775]
**ISSUE TYPE**
- Bug Report

**COMPONENT NAME**
- docker_container

**ANSIBLE VERSION**
- 2.2.0.0

**OS**
Ubuntu 14.04.5 LTS

**Summary:**
This docker_container module was working up until now and have not changed any code. When I try to pull the image manually in a ssh session, it works.

```
- name: Kazoo Install
  docker_container:
    name: soa-kazoo
    docker_api_version: "{{ docker_api_version }}"
    image: blah-testing.artifactory.internal/soa-kazoo
    env:
      ZOOKEEPER_PORT: "{{ zookeeper_host }}"
    log_driver: syslog
    command: /bin/bash -c 'export HOME={{ working_dir }}; ./run_api.sh'
    state: started
```

Error:
_fatal: [api]: FAILED! => {"changed": false, "failed": true, "msg": "Error pulling blah-testing.artifactory.internal/soa-kazoo - code: None message: Get http://: http: no Host in request URL"}_
