### ISSUE TITLE
digital_ocean private networking option does not work

### ISSUE THREAD

**Issue by jerrac** [ansible/ansible-modules-core#581]
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible --version
ansible 1.9 (devel 41399dedaf) last updated 2014/12/28 10:29:49 (GMT -700)
  lib/ansible/modules/core: (detached HEAD f9574cc318) last updated 2014/12/28 10:30:08 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD 317654dba5) last updated 2014/12/28 10:30:08 (GMT -700)
  v2/ansible/modules/core: (detached HEAD cb69744bce) last updated 2014/11/07 12:35:55 (GMT -700)
  v2/ansible/modules/extras: (detached HEAD 8a4f07eecd) last updated 2014/11/07 12:36:08 (GMT -700)
  configured module search path = /usr/share/ansible
```
##### Environment:

Ubuntu 14.04 64bit on both client and server.

pip install dopy outputs:

```
Downloading/unpacking dopy
  Downloading dopy-0.3.0.tar.gz
  Running setup.py (path:/tmp/pip_build_root/dopy/setup.py) egg_info for package dopy

Requirement already satisfied (use --upgrade to upgrade): requests>=1.0.4 in /usr/lib/python2.7/dist-packages (from dopy)
Installing collected packages: dopy
  Running setup.py install for dopy
```
##### Summary:

Setting `private_networking: yes` does not initiate a private networking NIC on my droplets. The droplets are in the nyc2 region, which is listed as supporting private networking.
##### Steps To Reproduce:

Run this task:

``` yaml
- name: Intiate example.com
    digital_ocean:
      name: example.com
      state: present
      api_key: "{{ digitalocean_api_v1_key }}"
      backups_enabled: yes
      client_id: "{{ digitalocean_api_v1_client_id }}"
      command: droplet
      image_id: "{{ digitalocean_api_v1_ubuntu_64bit_id }}"
      private_networking: yes
      region_id: "{{ digitalocean_api_v1_nyc2_id }}"
      size_id: "{{ digitalocean_api_v1_512MB_id }}"
      ssh_key_ids: "{{ digitalocean_api_v1_ssh_key_ids }}"
      unique_name: yes
      virtio: yes
      wait: yes
      wait_timeout: 300
```

Check DO settings page for private networking, and find none. SSH into droplet, and find no private network NIC.
##### Expected Results:

A private networking NIC enabled on the droplet.
##### Actual Results:

No private networking NIC enabled on the droplet.
