### ISSUE TITLE
Elasticache: Use of cache security groups is not permitted in this API version for your account

### ISSUE THREAD

**Issue by mario21ic** [ansible/ansible-modules-core#5815]
##### ISSUE TYPE

- Bug Report

##### COMPONENT NAME

elasticache

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
[defaults]
hostfile = hosts

##### OS / ENVIRONMENT

macOS Sierra

##### SUMMARY

I cannot create a cluster elasticache like the example http://docs.ansible.com/ansible/elasticache_module.html

##### STEPS TO REPRODUCE

ansible-playbook example.yml

```
- elasticache:
    name: "test-please-delete"
    state: present
    engine: memcached
    cache_engine_version: 1.4.14
    node_type: cache.m1.small
    num_nodes: 1
    cache_port: 11211
    cache_security_groups:
      - default
    region: us-east-1
    zone: us-east-1d
```

##### EXPECTED RESULTS

cluster created

##### ACTUAL RESULTS

Use of cache security groups is not permitted in this API version for your account

```

```
