### ISSUE TITLE
[Openstack-newton] Openstack modules with 'cloud' authentication give fatal error: "Could not find a suitable endpoint for client version: 2.0"

### ISSUE THREAD

**Issue by ghost** [ansible/ansible-modules-core#5822]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Openstack modules with clouds.yaml authentication

##### ANSIBLE VERSION
ansible 2.1.1.0

##### CONFIGURATION
Default configuration

##### OS / ENVIRONMENT
Fedora 24 for the Ansible host and CentOS 7 for the remote target systems

##### SUMMARY
I'm currently trying to create Openstack projects using the os_project module and when using the 'cloud' authentication method I get the following error: 
`fatal: [REDACTED]: FAILED! => {"changed": false, "extra_data": null, "failed": true, "invocation": {"module_args": {"api_timeout": null, "auth": null, "auth_type": null, "availability_zone": null, "cacert": null, "cert": null, "cloud": "openstack-newton", "description": "Service Project", "enabled": true, "endpoint_type": "public", "key": null, "name": "default", "region_name": null, "state": "present", "timeout": 180, "verify": true, "wait": true}, "module_name": "os_project"}, "msg": "Could not find a suitable endpoint for client version: 2.0"}`

The playbook in question that gives that error is:
```
- name: Loome default project-i
  os_project:
      cloud: openstack-newton
      state: present
      name: default
      description: "Service Project"
      enabled: True
```
The content of clouds.yml is:
```
clouds:
  openstack-newton:
    auth:
        auth_url: http://<REDACTED>:35357/v3/
        username: admin
        password: keystonepassword
        project_name: admin
        user_domain_name: default
        project_domain_name: default
```

##### STEPS TO REPRODUCE

To recreate the error use the following playbook with the clouds.yml defined below
```
- name: Loome default project-i
  os_project:
      cloud: openstack-newton
      state: present
      name: default
      description: "Service Project"
      enabled: True
```
clouds.yml:
```
clouds:
  openstack-newton:
    auth:
        auth_url: http://<REDACTED>:35357/v3/
        username: admin
        password: keystonepassword
        project_name: admin
        user_domain_name: default
        project_domain_name: default
```
##### EXPECTED RESULTS
Creation of 'default' project under keystone

##### ACTUAL RESULTS
`fatal: [REDACTED]: FAILED! => {"changed": false, "extra_data": null, "failed": true, "invocation": {"module_args": {"api_timeout": null, "auth": null, "auth_type": null, "availability_zone": null, "cacert": null, "cert": null, "cloud": "openstack-newton", "description": "Service Project", "enabled": true, "endpoint_type": "public", "key": null, "name": "default", "region_name": null, "state": "present", "timeout": 180, "verify": true, "wait": true}, "module_name": "os_project"}, "msg": "Could not find a suitable endpoint for client version: 2.0"}`

```
