### ISSUE TITLE
yum module appends unwanted data to value of {{ item }} variable

### ISSUE THREAD

**Issue by iamtrump** [ansible/ansible-modules-core#5856]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

yum module
##### ANSIBLE VERSION
2.2.0.0.

##### CONFIGURATION
Default configuration.

##### OS / ENVIRONMENT

Ansible host: Ubuntu 16.10.
Managed host: CentOS 7.

##### SUMMARY

yum can append unwanted data to variable {{ item }} after using.

##### STEPS TO REPRODUCE

I tried to run something like this:

```
tasks:
  - name: Install packages with handlers                                                                                                                                             
    yum: name=/tmp/{{ item }} state=present
    notify: restart {{ item }}
    with_items:
      - ntp-4.2.6p5-22.el7.centos.2.x86_64.rpm

handlers:
  - name: restart ntp-4.2.6p5-22.el7.centos.2.x86_64.rpm
    service: name=ntpd state=restarted enabled=yes
```

##### EXPECTED RESULTS

I expected to see something like this:
```
TASK [Install packages with handlers] ******************************************
changed: [hostname] => (item=ntp-4.2.6p5-22.el7.centos.2.x86_64.rpm)

RUNNING HANDLER [restart ntp-4.2.6p5-22.el7.centos.2.x86_64.rpm] ***************
changed: [hostname]
```
##### ACTUAL RESULTS

But actually I've got the following:

```
TASK [Install packages with handlers] ******************************************
ERROR! The requested handler 'restart [u'/tmp/ntp-4.2.6p5-22.el7.centos.2.x86_64.rpm']' was not found in either the main handlers list nor in the listening handlers list
```
As you can see "/tmp/" has been appended after first call {{ item }} variable.

**Comment by chuckyz** [comment]
Jinja2 should be wrapped with quotes (See "Gotchas" on this page http://docs.ansible.com/ansible/YAMLSyntax.html).  What occurs when you change your notify line to the following?

`notify: "restart {{ item }}" `

**Comment by iamtrump** [comment]
OK, I tried this way and I've got the same:
`ERROR! The requested handler 'restart [u'/tmp/ntp-4.2.6p5-22.el7.centos.2.x86_64.rpm']' was not found in either the main handlers list nor in the listening handlers list`

I'm absolutely sure that it is a yum module bug: I tried the same with copy module and it works as expected:
```
- name: Copy packages with handlers
  copy: src=/opt/repository/project/7/x86_64/{{ item }} dest=/tmp/{{ item }}
  notify: restart {{ item }}
  with_items:
    - ntp-4.2.6p5-22.el7.centos.2.x86_64.rpm
```
Output:
```
TASK [Copy packages with handlers] ******************************************
changed: [hostname] => (item=ntp-4.2.6p5-22.el7.centos.2.x86_64.rpm)

RUNNING HANDLER [restart ntp-4.2.6p5-22.el7.centos.2.x86_64.rpm] ***************
changed: [hostname]
```
