### ISSUE TITLE
ec2 module returns wrong state on instance termination

### ISSUE THREAD

**Issue by ghost** [ansible/ansible-modules-core#600]
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible --version
 ansible 1.8.2
  configured module search path = None
```
##### Environment:

OS X 10.9.5 -> Amazon Linux 2014.09
##### Summary:

For the ec2 module, I run assert against the results I get back from calls with state present, stopped, running and absent. The only state that does not work is the absent state. It always returns a state of running even though it terminates the instance on AWS. I would expect it to return a terminated state.
##### Steps To Reproduce:

Playbook snippet.

```
- name: terminate instance
  local_action:
    module: ec2
    region: "{{ region }}"
    wait: yes
    instance_ids: "{{ aws_instance_ids }}"
    state: absent
  register: terminated_instances

- name: test for absent state
    assert: { that: "'{{ item.state }}' == 'terminated'" }
    with_items: terminated_instances.instances
```
##### Expected Results:

Abbreviated output.

```
{"changed": true, "instance_ids": ["i-xxxxxxx"], "instances":
 [{"instance_type": "t2.micro", "region": "us-east-1", "state": "terminated"}]}
```
##### Actual Results:

Abbreviated output.

```
{"changed": true, "instance_ids": ["i-xxxxxxx"], "instances":
 [{"instance_type": "t2.micro", "region": "us-east-1", "state": "running"}]}
```
