### ISSUE TITLE
Bad value substitution in ini_file Module with percent placeholder values

### ISSUE THREAD

**Issue by viktorbreitenbuecher** [ansible/ansible-modules-core#627]
##### Issue Type:

Bug
##### Component Name:

ini_file module
##### Ansible Version:

1.7.2
1.8.2
##### Environment:

Mac OSX 10.10.1 Yosemite
##### Summary:

I need special values in an ini-file to configure my supervisor-daemon. For example a value looks like this:
process_name=%(program_name)s
##### Steps To Reproduce:

To reporduce this issue run following playbook twice.

```

---
- hosts: all
  tasks:
    - ini_file: dest="/tmp/tmp.ini" section="program:update" option="process_name" value="%(program_name)s"
```
##### Expected Results:

After first run everything OK, after second run I get an error and nothing happens.
##### Actual Results:

```
ConfigParser.InterpolationMissingOptionError: Bad value substitution:
    section: [program:update]
    option : process_name
    key    : program_name
    rawval : %(program_name)s
```
