### ISSUE TITLE
Allow AWS RDS SSD Storage Type

### ISSUE THREAD

**Issue by rhunwicks** [ansible/ansible-modules-core#633]
##### Issue Type:

Feature Request
##### Ansible Version:

ansible 1.8.2
  configured module search path = None
##### Environment:

N/A
##### Summary:

RDS supports _General Purpose (SSD)_ as a Storage Type alongside the original _Magnetic_ and _Provisioned IOPs_ entries. This is equivalent to the GP2 volume type for EBS volumes.

It would be good if we could set this when creating an RDS instance, in the same was as you now can for EBS volumes - see #3 
##### Steps To Reproduce:

```
- name: Provision Postgresql RDS
  rds:
    command: create
    region: "{{ aws_region }}"
    multi_zone: no
    instance_name: "{{ aws_db_name }}"
    db_engine: postgres
    port: 5432
    size: 100
    storage_type: ssd
```
##### Expected Results:

The RDS instance is created with the SSD storage type, and the storage type is returned in the output if you register it as a variable.
##### Actual Results:

N/A - not supported yet

**Comment by ansibot** [comment]
Can You Help Us Out?
====================

Thanks for filing a ticket! I am the friendly GitHub Ansibot. 

It looks like you might not have filled out the issue description based on our standard issue template.  You might not have known about that, and that's ok too, we'll tell you how to do it.

We have a standard template because Ansible is a really busy project and it helps to have some standard information in each ticket, and GitHub doesn't yet provide a standard facility to do this like some other bug trackers.  We hope you understand as this is really valuable to us!. 

Solving this is simple: please copy the contents of this [template](https://raw.githubusercontent.com/ansible/ansible/devel/ISSUE_TEMPLATE.md) and **paste it into the description** of your ticket.  That's it!

If You Had A Question To Ask Instead
====================================

If you happened to have a "how do I do this in Ansible" type of question, that's probably more of a user-list question than a bug report, and you should probably ask this question on the project mailing list instead.  

However, if you think you have a bug, the report is the way to go!  We definitely want all the bugs filed :)  Just trying to help!

About Priority Tags
===================

Since you're here, we'll also share some useful information at this time.

In general tickets will be assigned a priority between P1 (highest) and P5, and then worked in priority order. We may also have some follow up questions along the way, so keeping up with follow up comments via GitHub notifications is a good idea.

Due to large interest in Ansible, humans may not comment on your ticket immediately.  

Mailing Lists
=============

If you have concerns or questions, you're welcome to stop by the ansible-project or ansible-development mailing lists, as appropriate.  Here are the links:

  * https://groups.google.com/forum/#!forum/ansible-project - for discussion of bugs and how-to type questions
  * https://groups.google.com/forum/#!forum/ansible-devel - for discussion on how to implement a code change, or feature brainstorming among developers

Thanks again for the interest in Ansible!

**Comment by rhunwicks** [comment]
The `facts` command in the `rds` module should also be updated to report the `storage-type`.

**Comment by rhunwicks** [comment]
I am working around this for now using:

``` yaml
- name: Create Postgresql RDS instance using SSD storage
  command: "aws rds create-db-instance
            --db-instance-identifier {{ aws_db_name }}
            --storage-type gp2
            --allocated-storage {{ aws_db_size }}
            --db-instance-class {{ aws_db_instancetype }}
            --engine {{ aws_db_engine }}
            --master-username {{ aws_db_username }}
            --master-user-password {{ aws_db_password }}
            --vpc-security-group-ids {{ vpc_group_postgresql_server.group_id }}
            --availability-zone {{ aws_primary_az }}
            --db-subnet-group-name {{ aws_db_subnet_group_name }}
            --preferred-maintenance-window {{ aws_db_maint_window }}
            --db-parameter-group-name {{ aws_db_parameter_group_name }}
            --backup-retention-period {{ aws_db_backup_retention_days }}
            --preferred-backup-window {{ aws_db_backup_window }}
            --port 5432
            --no-multi-az"
  register: result
  failed_when: >
    result.rc != 0 and ('DBInstanceAlreadyExists' not in result.stderr)
  changed_when: "result.rc == 0"

- name: Wait Postgresql RDS to be available
  rds:
    command: facts
    region: "{{ aws_region }}"
    instance_name: "{{ aws_db_name }}"
  register: result
  until: result.instance.status == "available"
  retries: 20
  delay: 60
```

**Comment by stevenscg** [comment]
@rhunwicks Thanks for the cli command and +1 on the request.

**Comment by wimnat** [comment]
This isn't supported downstream by boto yet.  I'd like this feature too!  I'll keep an eye on boto and maybe submit a PR when available https://github.com/boto/boto/issues/2761

**Comment by wimnat** [comment]
Unfortunately this is not supported downstream by boto yet (https://github.com/boto/boto/issues/2923).  I'll keep an eye on boto and maybe submit a PR when available

**Comment by attenda-johnmcmillan** [comment]
@rhunwicks Thanks very much for the Workaround. I'm waiting onthis feature too, you're workaround is useful in the meantime.

**Comment by ferrants** [comment]
Great work-around. I've tried to put some pressure on getting https://github.com/boto/boto/pull/2794 merged so this can be implemented in the rds module.

**Comment by jonathanhle** [comment]
+1

**Comment by gacyun** [comment]
+1

**Comment by worldofchris** [comment]
+1

**Comment by dragonde** [comment]
+1

**Comment by bpesics** [comment]
+1

**Comment by a-b** [comment]
+1

**Comment by bcoca** [comment]
my guess is that we are waiting for these:
https://github.com/boto/boto/issues/2761
https://github.com/boto/boto/pull/2794

**Comment by groorj** [comment]
+1

**Comment by jonathan-keenan** [comment]
+1

**Comment by DanielFerreiraJorge** [comment]
+1

**Comment by mdaize** [comment]
+1
I vote that the tags changed to a P2 Bug. This is clearly not intended.

**Comment by arturmartins** [comment]
This is still an issue. I am using
boto==2.39.0
ansible==2.0.1.0

**Comment by filipenf** [comment]
Wouldn't be easier to switch this module to boto3 rather than waiting for it to be implemented on boto2?

**Comment by mikhailjan** [comment]
+1

**Comment by wimnat** [comment]
@filipenf at the moment you can't change this whole module to boto3 as the core team want to maintain backward compatibility for the time being.  However, it is possible to implement just the feature using boto3 if you want and mark clearly in the documentation that boto3 is required.

**Comment by snakelab** [comment]
+1

**Comment by aboutlo** [comment]
I wonder how it's possible this feature is still missing. Without, the module is useless. 
By the way, thank you @rhunwicks to provide a workaround.

**Comment by pierreant-p** [comment]
+1

thanks for the workaround @rhunwicks

**Comment by lpaulmp** [comment]
+1 to add this ASAP
Thanks @rhunwicks for your workaround

**Comment by bobobox** [comment]
This really needs some attention from the Ansible team. If boto2 is abandonware at this point (which it looks to be) then pointing to lack of boto2 support for this is less and less of an excuse. Especially for such an important RDS option that was added almost two years ago.

**Comment by ferrants** [comment]
The whole module (and other modules using boto2) should be upgraded to start using boto3.

**Comment by ansibot** [comment]
@bpennypacker, @willthames, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/jctanner/ansibullbot/blob/ISSUE_TRIAGE_CLASS/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@bpennypacker, @willthames, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@bpennypacker, @willthames, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by discretepackets** [comment]
+1

Thanks for the workaround @rhunwicks

**Comment by willthames** [comment]
needs_contributor

**Comment by willthames** [comment]
LInking to #5343

**Comment by hlpinform** [comment]
+1

issue affects also newer versions like mine:

ansible 2.3.0 (devel 8ba5a41a33) last updated 2016/12/01 13:12:04 (GMT +000)
  lib/ansible/modules/core: (detached HEAD 6890003c4f) last updated 2016/12/01 13:12:11 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD 20ea46642b) last updated 2016/12/01 13:12:11 (GMT +000)

**Comment by ansibot** [comment]
This repository has been locked. All new issues and pull requests should be filed in https://github.com/ansible/ansible

Please read through the <a href="http://docs.ansible.com/ansible/dev_guide/repomerge.html#move-issues-and-prs-to-new-repo">repomerge</a> page in the dev guide. The guide contains links to tools which automatically move your issue or pull request to the ansible/ansible repo.

**Comment by flj** [comment]
+1

**Comment by lfventura** [comment]
Since this is now supported on boto3 , cant this be added to ansible?
we are really missing this feature.

**Comment by willthames** [comment]
This really isn't the right place for this discussion - this whole repository is now locked

See https://github.com/ansible/ansible/pull/25646 for the move of RDS to boto3

**Comment by jamiejamison** [comment]
I ran into this problem and put this together based upon the task that @rhunwicks wrote. It's based upon the following assumptions:

1) You have an S3 bucket configured to store the database credentials
and have the keys to access that bucket stored in your $HOME/.ssh
directory.

2) You have an IAM role defined that allows full access to RDS
and a set of access keys for that role stored in your
$HOME/.ssh directory.

3) You have the parameters for your RDS instance stored in
a file in the host_vars directory of your Ansible project.

4) Your RDS instance is defined in your ansible hosts file.

5) You have the aws cli package installed. I recommend
installing this via PIP as the Ubuntu packages are out of
date and don't support all of the features of the CLI.

The playbook downloads the database master user password from S3, adds the keys
for creating the RDS instance to the AWS credential store, creates the RDS instance
and then removes the keys from the AWS credentials store.

You invoke the script with the environments and extra-vars arguments like this:

```
create_rds_instance.yml --inventory-file=environments/testing --extra-vars='instance_name=rds-master-testing'
```

FILE: host_vars/rds-master-testing
```yaml
---
# vim: ft=ansible
#

instance_name: rds-master-testing
region: us-east-1
availability_zone: us-east-1d
multiple_az: no
instance_type: db.m4.large
subnet: test-db-subnet-group
vpc_subnet_group: test-db-subnet-group
security_groups: sg-XXXXXXXX
db_engine: MySQL
db_engine_version: 5.6
maint_window: 'Wed:22:00-Wed:23:15'
allow_minor_db_upgrades: yes
storage_type: gp2
storage_size: 500
encrypt_storage: no
username: mysql_admin
public_access: no
backup_retention: 0
```
FILE: group_vars/testing

```yaml
---
# vim:ft=ansible:

environment: testing
#
# S3 bucket where credentials are stored.
#
s3_credentials_bucket: "{{ environment }}-system-configuration"
#
# S3 key file containing the keypair for downloading credentials
# from S3.
#
s3_key_file: "{{ environment }}-system-configuration.yml"
```

FILE: create_rds_instance.yml

```yaml
#!/usr/bin/env ansible-playbook

# vim: ft=ansible
#

#
# This playbook spins up an RDS instance
#
- hosts: localhost
  connection: local
  gather_facts: False
  become: False
  #
  vars:
    #
    aws_key_file: 'rds_instance_maintainer.yml'
    environment: "{{ inventory_file | basename }}"
    default_maint_window: 'Sun:19:00-Sun:20:15'
    default_backup_window: '08:00-09:00'
    default_parameter_group: 'mysql5-6-default'
  #
  vars_files:
    #
    - "{{ lookup('env','HOME') }}/.ssh/{{ aws_key_file }}"
    - "{{ lookup('env','HOME') }}/.ssh/{{ s3_key_file }}"
    - "{{ playbook_dir }}/host_vars/{{ instance_name }}"
    - "{{ playbook_dir }}/group_vars/{{ environment }}"
  #
  tasks:
  #
  - name: Create a temporary file to store the database master user password
    set_fact:
      database_master_password_file: "{{ lookup('pipe', 'mktemp /tmp/ansible.XXXXXXXX') }}"
  #
  - name: Download the password for the database master user from S3
    s3:
      ec2_url: "{{ s3_credentials_endpoint }}"
      bucket: "{{ s3_credentials_bucket }}"
      object: '/passwords/rds/database-master-user-password'
      dest: "{{ database_master_password_file }}"
      mode: get
      aws_access_key: "{{ s3_access_key_id }}"
      aws_secret_key: "{{ s3_secret_access_key }}"
  #
  - name: Configure the rds_create profile for the awscli tool
    ini_file:
      dest: "{{ lookup('env','HOME') }}/.aws/config"
      section: profile rds_create
      option: "{{ item.option }}"
      value: "{{ item.value }}"
      state: present
    with_items:
      - { option: 'output', value: 'json' }
      - { option: 'region', value: "{{ region }}" }
  #
  - name: Configure the credentials for the rds_create AWS profile
    ini_file:
      dest: "{{ lookup('env','HOME') }}/.aws/credentials"
      section: rds_create
      option: "{{ item.option }}"
      value: "{{ item.value }}"
      state: present
    with_items:
      - { option: 'aws_access_key_id', value: "{{ aws_access_key_id }}" }
      - { option: 'aws_secret_access_key', value: "{{ aws_secret_access_key }}" }
  #
  - name: Create an RDS instance in a single availability zone
    command: "aws --profile rds_create rds create-db-instance
             --db-instance-identifier {{ instance_name }}
             --db-instance-class {{ instance_type }}
             --{{ (availability_zone is defined | ternary('availability-zone ' + availability_zone, 'no-multi-az')) }}
             --engine {{ db_engine }}
             --engine-version {{ db_engine_version }}
             --db-parameter-group-name {{ (parameter_group is defined | ternary(parameter_group, default_parameter_group) }}
             --storage-type {{ ( storage_type is defined | ternary('gp2', storage_type)) }}
             --{{ ((encrypt_storage is defined and encrypt_storage == 'yes') | ternary('storage-encrypted', 'no-storage-encrypted')) }}
             --allocated-storage {{ storage_size }}
             --master-username {{ username }}
             --master-user-password {{ lookup('file', database_master_password_file) }}
             --vpc-security-group-ids {{ security_groups }}
             --db-subnet-group-name {{ vpc_subnet_group }}
             --{{ ((public_access is defined and public_access == 'yes') | ternary('publicly_accessible', 'no-publicly-accessible')) }}
             --preferred-maintenance-window {{ (( maint_window is defined) | ternary(maint_window, default_maint_window)) }}
             --{{ ((allow_minor_db_upgrades is defined and allow_minor_db_upgrades == 'yes') | ternary('auto-minor-version-upgrade', 'no-auto-minor-version-upgrade')) }}
             --backup-retention-period {{ (backup_retention is undefined | ternary('0', backup_retention)) }}
             --preferred-backup-window {{ (backup_window is defined | ternary(backup_window, default_backup_window)) }}
             --tags Key=Name,Value={{ instance_name }},Key=Environment,Value={{ environment }}"
    register: single_zone_result
    failed_when: single_zone_result.rc != 0 and ('DBInstanceAlreadyExists' not in single_zone_result.stderr)
    changed_when: "single_zone_result.rc == 0"
    when: multiple_zone is undefined or multiple_zone == 'no'
  #
  - name: Create an RDS instance across multiple availability zones
    command: "aws rds create-db-instance --profile rds_create
             --db-instance-identifier {{ instance_name }}
             --db-instance-class {{ instance_type }}
             --multi-az
             --engine {{ db_engine }}
             --engine-version {{ db_engine_version }}
             --db-parameter-group-name {{ (parameter_group is defined | ternary(parameter_group, default_parameter_group) }}
             --storage-type {{ ( storage_type is defined | ternary('gp2', storage_type)) }}
             --{{ ((encrypt_storage is defined and encrypt_storage == 'yes') | ternary('no-storage-encrypted', 'storage-encrypted')) }}
             --allocated-storage {{ storage_size }}
             --master-username {{ username }}
             --master-user-password {{ lookup('file', database_master_password_file) }}
             --vpc-security-group-ids {{ security_groups }}
             --db-subnet-group-name {{ vpc_subnet_group }}
             --{{ ((public_access is defined and public_access == 'yes') | ternary('publicly_accessible', 'no-publicly-accessible')) }}
             --preferred-maintenance-window {{ (( maint_window is defined) | ternary(maint_window, default_maint_window)) }}
             --{{ ((allow_minor_db_upgrades is defined and allow_minor_db_upgrades == 'yes') | ternary('auto-minor-version-upgrade', 'no-auto-minor-version-upgrade')) }}
             --backup-retention-period {{ (backup_retention is undefined | ternary('0', backup_retention)) }}
             --preferred-backup-window {{ (backup_window is defined | ternary(backup_window, default_backup_window)) }}
             --tags Key=Name,Value={{ instance_name }},Key=Environment,Value={{ environment }}"
    register: multi_zone_result
    failed_when: multi_zone_result.rc != 0 and ('DBInstanceAlreadyExists' not in multi_zone_result.stderr)
    changed_when: "multi_zone_result.rc == 0"
    when: multiple_zone is defined and multiple_zone == 'no'
  #
  - name: Remove the AWS rds_create profile
    ini_file:
      dest: "{{ lookup('env','HOME') }}/.aws/config"
      section: profile rds_create
      state: absent
  #
  - name: Remove rds_create profile credentials
    ini_file:
      dest: "{{ lookup('env','HOME') }}/.aws/credentials"
      section: rds_create
      state: absent
```
