### ISSUE TITLE
apache2_module errors out with CentOS 6 target

### ISSUE THREAD

**Issue by activekjw** [ansible/ansible-modules-core#635]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.9 (devel 8bcd2b8f9c) last updated 2015/01/12 13:07:20 (GMT -700)
  lib/ansible/modules/core: (detached HEAD 8c8be0e48c) last updated 2015/01/12 13:07:38 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD ffa8abf979) last updated 2015/01/12 13:07:41 (GMT -700)
  v2/ansible/modules/core: (detached HEAD 27d5e5124f) last updated 2015/01/12 13:08:05 (GMT -700)
  v2/ansible/modules/extras: (detached HEAD 8a4f07eecd) last updated 2015/01/12 13:08:15 (GMT -700)
  configured module search path = None
##### Environment:

Running Ansible from Fedora 21, managing CentOS 6, fresh out of the box.
##### Summary:

Given the following playbook:

```

---
- hosts: extern
  remote_user: root
  tasks:
    - name: install the latest version of Apache.
      yum: name=httpd state=latest
      yum: name=mod_ssl state=latest
    - name: install mods
      apache2_module: state=present name=ssl
      notify:
        - restart apache
  handlers:
    - name: restart apache
      service: name=httpd state=restarted
```

I get the following error listed in Expected Results.
##### Steps To Reproduce:
- set up ssh keys on target host
- test with ping
- attempt to run the above playbook against the host using `ansible-playbook install-apache.yml`
##### Expected Results:

Expect that the play will succeed; if mod_ssl isn't already enabled it should enable it, if it is already enabled it should still succeed, and if the operation isn't applicable on CentOS (possibly because it doesn't use a2enmod or similar) it should probably be a no-op.
##### Actual Results:

```TASK: [install mods] *********************************************************\* 
failed: [ansible.doglet.ca] => {"cmd": "None ssl", "failed": true, "rc": 2}
msg: [Errno 2] No such file or directory

FATAL: all hosts have already failed -- aborting

```
```

**Comment by ansibot** [comment]
Can You Help Us Out?
====================

Thanks for filing a ticket! I am the friendly GitHub Ansibot. 

It looks like you might not have filled out the issue description based on our standard issue template.  You might not have known about that, and that's ok too, we'll tell you how to do it.

We have a standard template because Ansible is a really busy project and it helps to have some standard information in each ticket, and GitHub doesn't yet provide a standard facility to do this like some other bug trackers.  We hope you understand as this is really valuable to us!. 

Solving this is simple: please copy the contents of this [template](https://raw.githubusercontent.com/ansible/ansible/devel/ISSUE_TEMPLATE.md) and **paste it into the description** of your ticket.  That's it!

If You Had A Question To Ask Instead
====================================

If you happened to have a "how do I do this in Ansible" type of question, that's probably more of a user-list question than a bug report, and you should probably ask this question on the project mailing list instead.  

However, if you think you have a bug, the report is the way to go!  We definitely want all the bugs filed :)  Just trying to help!

About Priority Tags
===================

Since you're here, we'll also share some useful information at this time.

In general tickets will be assigned a priority between P1 (highest) and P5, and then worked in priority order. We may also have some follow up questions along the way, so keeping up with follow up comments via GitHub notifications is a good idea.

Due to large interest in Ansible, humans may not comment on your ticket immediately.  

Mailing Lists
=============

If you have concerns or questions, you're welcome to stop by the ansible-project or ansible-development mailing lists, as appropriate.  Here are the links:

  * https://groups.google.com/forum/#!forum/ansible-project - for discussion of bugs and how-to type questions
  * https://groups.google.com/forum/#!forum/ansible-devel - for discussion on how to implement a code change, or feature brainstorming among developers

Thanks again for the interest in Ansible!

**Comment by activekjw** [comment]
##### Issue Type:

Bug Report

##### Ansible Version:

ansible 1.9 (devel 8bcd2b8f9c) last updated 2015/01/12 13:07:20 (GMT -700)
  lib/ansible/modules/core: (detached HEAD 8c8be0e48c) last updated 2015/01/12 13:07:38 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD ffa8abf979) last updated 2015/01/12 13:07:41 (GMT -700)
  v2/ansible/modules/core: (detached HEAD 27d5e5124f) last updated 2015/01/12 13:08:05 (GMT -700)
  v2/ansible/modules/extras: (detached HEAD 8a4f07eecd) last updated 2015/01/12 13:08:15 (GMT -700)
  configured module search path = None

##### Environment:

Running Ansible from Fedora 21, managing CentOS 6, fresh out of the box.

##### Summary:

Given the following playbook:

```
---
- hosts: extern
  remote_user: root
  tasks:
    - name: install the latest version of Apache.
      yum: name=httpd state=latest
      yum: name=mod_ssl state=latest
    - name: install mods
      apache2_module: state=present name=ssl
      notify:
        - restart apache
  handlers:
    - name: restart apache
      service: name=httpd state=restarted
```

I get the following error listed in Expected Results.

##### Steps To Reproduce:

- set up ssh keys on target host
- test with ping
- attempt to run the above playbook against the host using `ansible-playbook install-apache.yml`

##### Expected Results:

Expect that the play will succeed; if mod_ssl isn't already enabled it should enable it, if it is already enabled it should still succeed, and if the operation isn't applicable on CentOS (possibly because it doesn't use a2enmod or similar) it should probably be a no-op.

##### Actual Results:

```TASK: [install mods] ********************************************************** 
failed: [ansible.doglet.ca] => {"cmd": "None ssl", "failed": true, "rc": 2}
msg: [Errno 2] No such file or directory

FATAL: all hosts have already failed -- aborting
```
