### ISSUE TITLE
Cannot use rds modify to increase storage size on Postgresql databases

### ISSUE THREAD

**Issue by rhunwicks** [ansible/ansible-modules-core#636]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.8.2
  configured module search path = None
##### Environment:

N/A
##### Summary:

Attempting to increase the size of an RDS instance using rds modify silently fails. I tested using Postgres, but it may affect other database engines
##### Steps To Reproduce:

```

---
- hosts: local
  connection: local
  gather_facts: False
  tasks:

    - name: Provision Postgresql RDS
      rds:
        command: create
        region: us-east-1
        instance_name: rds-resize-test
        db_engine: postgres
        port: 5432
        size: 5
        instance_type: db.t1.micro
        username: rds_resize_test
        password: rds_resize_test
        wait: yes
        wait_timeout: 1200 
      register: rds

    - name: Convert Postgresql RDS instance to SSD storage
      rds:
        command: modify
        region: us-east-1
        instance_name: rds-resize-test
        size: 10
        apply_immediately: yes
        wait: yes
        wait_timeout: 1200 
```
##### Expected Results:

The RDS instance is created, and then available storage is increased.
##### Actual Results:

The RDS instance is created, and the modify command runs successfully, and returns a `changed` status but the storage size remains the same. Rebooting the instance doesn't affect it, so I don't think it is an issue with `apply_immediately`

```
<localhost> REMOTE_MODULE rds command=modify instance_name=rds-resize-test region=us-east-1
...
changed: [localhost] => {"changed": true, "instance": {"availability_zone": "us-east-1c", "backup_retention": 1, "backup_window": "10:22-10:52", "create_time": "2015-01-13T08:39:26.191Z", "endpoint": "rds-resize-test.ctshriqocnec.us-east-1.rds.amazonaws.com", "id": "rds-resize-test", "instance_type": "db.t1.micro", "iops": null, "maintenance_window": "mon:05:58-mon:06:28", "multi_zone": false, "port": 5432, "replication_source": null, "status": "available", "username": "rds_resize_test", "vpc_security_groups": ""}}
```
