### ISSUE TITLE
unarchive - bug with tilde in dest value

### ISSUE THREAD

**Issue by tphummel** [ansible/ansible-modules-core#682]
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible --version
ansible 1.9 (devel 2a04663255) last updated 2015/01/20 14:15:43 (GMT -700)
  lib/ansible/modules/core: (detached HEAD 396c399b54) last updated 2015/01/20 14:21:03 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD 2396f36f11) last updated 2015/01/20 14:21:07 (GMT -700)
  v2/ansible/modules/core: (detached HEAD 8ba8f5ef4d) last updated 2015/01/20 14:21:11 (GMT -700)
  v2/ansible/modules/extras: (detached HEAD 2396f36f11) last updated 2015/01/20 14:21:14 (GMT -700)
  configured module search path = None
```

_note:_ https://github.com/ansible/ansible-modules-core/pull/681 also needs to be applied otherwise you run into that issue. 
##### Environment:

master OSX 10.10.1 controlling ubuntu 14.04.1
##### Summary:

using tilde characters in a variable to the `dest` of unarchive does not find the directory. 
##### Steps To Reproduce:

```
- name:
  hosts: all
  vars: 
    dest_dir: /home/com.generic~my-app~v1.1.0
  tasks:
    - name: create directory
      sudo: yes
      file:
        path: "{{ dest_dir }}"
        state: directory

    - name: expand package
      sudo: yes
      unarchive:
        src: /tmp/pkg.zip
        dest: "{{ dest_dir }}"
        copy: no
```
##### Expected Results:

when running the above example with `test` in place of `/home/com.generic~my-app~v1.1.0` I get: 

```
TASK: [myrole | create directory] ********************************* 
ok: [host]

TASK: [myrole | expand package] ******************************************* 
changed: [host]
```
##### Actual Results:

```
TASK: [myrole | create directory] ********************************* 
changed: [host]

TASK: [myrole | expand package] ******************************************* 
failed: [host] => {"failed": true}
msg: dest '/home/com.generic~my-app~v1.1.0' must be an existing dir

FATAL: all hosts have already failed -- aborting
```

**Comment by tphummel** [comment]
also possibly relevant: 
- https://groups.google.com/forum/#!topic/ansible-project/VQ61xDXePfs 
- https://github.com/ansible/ansible-modules-core/issues/348

although in my example the value doesn't begin with `~`. I haven't dug further yet.

**Comment by tphummel** [comment]
the fact that the `~` appears in a variable doesn't seem to matter. using a string literal for the `dest` var surfaces the same issue as above. 

```
- name: create application directory
  sudo: yes
  file:
    path: /home/com.generic~my-app~v1.1.0
    state: directory

- name: expand app package
  sudo: yes
  unarchive:
    src: /tmp/app.pkg
    dest: /home/com.generic~my-app~v1.1.0
    copy: no

```

**Comment by tphummel** [comment]
and of course this works:

```
- name: expand app package
  command: unzip /tmp/app.zip -d /home/com.generic~my-app~v1.1.0
  args:
    creates: "/home/com.generic~my-app~v1.1.0/mod.json"
```
