### ISSUE TITLE
ec2_vol does not exit with change=True upon volume creation

### ISSUE THREAD

**Issue by moorereason** [ansible/ansible-modules-core#695]
##### Issue Type:

Bug Report
##### Ansible Version:

1.8.2 (with latest patches to ec2_vol.py for `volume_type` feature)
##### Environment:

RHEL 7, python-boto-2.34.0-4.el7.noarch
##### Summary:

`ec2_vol` should return `changed=True` upon volume creation.  Example of the problem area from the end of `main` line 450:

``` python
module.exit_json(volume_id=volume.id, device=device_name, volume_type=volume.type)
```
##### Steps To Reproduce:

Attempt to attach a new volume to an EC2 instance:

``` yaml
- hosts: tag_Role_blah
  connection: local
  gather_facts: true
  tasks:
    - name: gather EC2 facts
      local_action: ec2_facts

    - name: add encrypted EBS for /blah
      delegate_to: localhost
      ec2_vol:
        instance: "{{ ec2_id }}"
        device_name: /dev/xvdh
        encrypted: true
        volume_size: 10
        volume_type: gp2
        region: "{{ ec2_region }}"
```

Assume successful creation.
##### Expected Results:

I expect the task to return a result of `changed` instead of `ok`.

```
TASK: [add encrypted EBS for /blah] ******************************************* 
changed: [172.31.0.1 -> localhost]
```
##### Actual Results:

```
TASK: [add encrypted EBS for /blah] ******************************************* 
ok: [172.31.0.1 -> localhost]
```
