### ISSUE TITLE
Docker: detach=False not working as expected

### ISSUE THREAD

**Issue by bentruyman** [ansible/ansible-modules-core#706]
##### Issue Type:

Bug Report
##### Ansible Version:

Latest release:

```
ansible 1.8.2
  configured module search path = None
```

And HEAD (as of this posting):

```
ansible 1.9 (devel c8ed12a69c) last updated 2015/01/26 23:16:46 (GMT -500)
  lib/ansible/modules/core: (detached HEAD 99a8caf409) last updated 2015/01/26 23:16:51 (GMT -500)
  lib/ansible/modules/extras: (detached HEAD 21126a4af3) last updated 2015/01/26 23:16:57 (GMT -500)
  v2/ansible/modules/core: (detached HEAD 99a8caf409) last updated 2015/01/26 23:17:03 (GMT -500)
  v2/ansible/modules/extras: (detached HEAD 21126a4af3) last updated 2015/01/26 23:17:11 (GMT -500)
  configured module search path = None
```
##### Environment:

OS X 10.10.1
##### Summary:

I expect Docker tasks ran with `detach=False` to wait until the task completes and to stop execution of subsequent tasks if they don't exit with a non-zero code. Additionally, it doesn't appear as though `detach=False` is actually waiting for the container to exit (i.e. 10 tasks defined with `detach=False` will run almost asynchronously instead of sequentially).

From my understanding, there are two main uses for Docker containers: short-lived tasks and long-running processes. The former is useful in my case like using `npm install` to install node modules for a project. The latter is useful for actually using `node` to run my application. But if `npm install` is a task that needs to finish successfully before running my app, I can't use the existing Docker module (unless I'm using it wrong). My current workaround is to simply use the `shell` module to run an equivalent task.
##### Steps To Reproduce:

The following tasks will generate the below "Actual Results":

``` yaml
- name: testing
  docker: image=busybox detach=False command="sh -c 'exit 1'"

- name: should not execute
  shell: "echo Hello, world!"
```

However, the following will fail and generate the below "Expected Results":

``` yaml
- name: testing
  shell: "docker run busybox sh -c 'exit 1'"

- name: should not execute
  shell: "echo Hello, world!"
```
##### Expected Results:

I expect something such as the following (generated using the shell-based task above):

```
PLAY [test] **************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [test]

TASK: [docker_test | testing] ************************************************* 
failed: [test] => {"changed": true, "cmd": "docker run busybox sh -c 'exit 1'", "delta": "0:00:00.153095", "end": "2015-01-27 05:52:18.267979", "rc": 1, "start": "2015-01-27 05:52:18.114884", "warnings": []}

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/Users/btruyman/playbook.retry

test                          : ok=1    changed=0    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```
##### Actual Results:

```
PLAY [test] **************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [test]

TASK: [docker_test | testing] ************************************************* 
changed: [test]

TASK: [docker_test | should not execute] ************************************** 
changed: [test]

PLAY RECAP ******************************************************************** 
test                          : ok=3    changed=2    unreachable=0    failed=0   
```

**Comment by tobscher** [comment]
I had the same expectation and solved it with the following workaround which is not ideal but works for now:

``` yaml
- name: Migrate database
  docker:
    image: foo
    name: db_migrate
    detach: false
    volumes:
      - /tmp/ansible:tmp/ansible
    links:
      - mysql:mysql
    command: sh -c -e "bundle exec rake db:migrate; touch /tmp/ansible/db-migrate"

- name: Wait for db:migrate to finish
  wait_for:
    path: /tmp/ansible/db-migrate

- name: Clean up db:migrate
  shell: rm /tmp/ansible/db-migrate
```

Note: The wait_for module probably needs a timeout.

**Comment by bentruyman** [comment]
That's a clever workaround. I imagine this would fail if one were to use the `count` param with the Docker module.

**Comment by daviddyball** [comment]
I know the docker client API is capable of this functionality, so it shouldn't be too difficult to replicate in the module.

I might have some time to try out a few things and I'll see how far I can get.

**Comment by ddub** [comment]
I had similar expectations dashed and found pull #588 which I think is the correct answer.

**Comment by bentruyman** [comment]
@ddub Maybe. I guess it's unclear to me what the purpose of the `detach` parameter is then. That PR, though, does achieve what I think everyone here is talking about: blocking until the execution of docker command has finished.

**Comment by conormullen** [comment]
As a workaround for this you could use something like:

``` yml
- name: Some process
  docker:
    image: foo
    name: my_container
    detach: false

- name: wait for my_container to finish
  shell: >
    docker wait my_container
```
