### ISSUE TITLE
Bug Report: ec2_group.py purges wrong rule from security group

### ISSUE THREAD

**Issue by bobobox** [ansible/ansible-modules-core#748]
##### Issue Type:

Bug Report
##### Ansible Version:

1.8.2, but also present in current devel branch 1.9 (devel 8f06ba2bc1)
##### Environment:

n/a
##### Summary:

ec2_group module purges the wrong rule when EC2 Security Group rules are updated in certain situations.
##### Steps To Reproduce:

Sample playbook:

```
- name: EC2 security group bug demo                                                                                                                                                                                                                                       
  hosts: localhost                                                                                                                                                                                                                                                        
  gather_facts: no                                                                                                                                                                                                                                                        
  tasks:                                                                                                                                                                                                                                                                  
    - name: Maintain VPC Security Group                                                                                                                                                                                                                                   
      local_action:                                                                                                                                                                                                                                                       
        module: ec2_group                                                                                                                                                                                                                                                 
        region: "{{ aws_region }}"                                                                                                                                                                                                                                        
        vpc_id: "{{ vpc_id }}"                                                                                                                                                                                                                                            
        name: Ansible Rule Update Bug Demo                                                                                                                                                                                                                                
        description: Demonstrating rule purge bug                                                                                                                                                                                                                         
        rules:                                                                                                                                                                                                                                                            
          - proto: tcp                                                                                                                                                                                                                                                    
            from_port: 8080                                                                                                                                                                                                                                               
            to_port: 9090                                                                                                                                                                                                                                                 
            cidr_ip: "{{ source_cidr_1 }}"                                                                                                                                                                                                                                
            purge_rules: yes                                                                                                                                                                                                                                              
            rules_egress:                                                                                                                                                                                                                                                 
            purge_rules_egress: yes                                                                                                                                                                                                                                       
          - proto: tcp                                                                                                                                                                                                                                                    
            from_port: 8080                                                                                                                                                                                                                                               
            to_port: 9090                                                                                                                                                                                                                                                 
            cidr_ip: "{{ source_cidr_2 }}"                                                                                                                                                                                                                                
            purge_rules: yes                                                                                                                                                                                                                                              
            rules_egress:                                                                                                                                                                                                                                                 
            purge_rules_egress: yes                                                                                                                                                                                                                                       
        state: present 
```

Save this playbook as bug_demo.yml and run it the first time like so (this assumes AWS credentials are available as environment variables):

```
$ ansible-playbook bug_demo.yml --extra-vars 'vpc_id=<your vpc> aws_region=us-east-1 source_cidr_1=1.1.1.1/32 source_cidr_2=2.2.2.2/32'
```

Observe that the Security Group 'Ansible Rule Update Bug Demo' is created correctly, with ingress rules for IPs 1.1.1.1 and 2.2.2.2.

Now, re-run it (once only) changing the value of source_cidr_2 variable to 3.3.3.3/32:

```
$ ansible-playbook bug_demo.yml --extra-vars 'vpc_id=<your vpc> aws_region=us-east-1 source_cidr_1=1.1.1.1/32 source_cidr_2=3.3.3.3/32'
```
##### Expected Results:

The security group should now have rules for source IPs 1.1.1.1 and 3.3.3.3.
##### Actual Results:

The wrong rule is purged, and the security group now has rules for source IPs 2.2.2.2 and 3.3.3.3, despite no rule specified in the playbook for IP 2.2.2.2. In addition, the rule for 1.1.1.1 is missing.
