### ISSUE TITLE
apt: return cache update status

### ISSUE THREAD

**Issue by tetherit** [ansible/ansible-modules-core#749]
Hi there,

I'm trying to detect when apt cache changes, I am doing this:

To make sure cache is old, on my vagrant host:

``` bash
$ rm -R /var/lib/apt/lists/* /var/lib/apt/periodic/update-success-stamp /var/cache/apt/*
```

In my ansible task

``` yaml
- apt: update_cache=true cache_valid_time=1
  register: apt_cache

- name: "Dist-Upgrade All Packages"
  apt: upgrade=dist
  when: apt_cache.changed
```

When I run my playbook, I see:

```
TASK: [common | apt update_cache=true cache_valid_time=1] ********************* 
ok: [deployer@127.0.0.1]

TASK: [common | Upgrade All Packages] ************************************ 
skipping: [deployer@127.0.0.1]
```

Why isn't ansible reporting a change?
