### ISSUE TITLE
rds module does not support the documented 'publicly_accessible' parameter

### ISSUE THREAD

**Issue by danvaida** [ansible/ansible-modules-core#795]
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible 1.9 (devel 76a5dd7f62) last updated 2015/02/09 17:47:39 (GMT +200)
  lib/ansible/modules/core: (detached HEAD b766390ae2) last updated 2014/12/05 14:16:32 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 19e688b017) last updated 2014/12/05 14:16:37 (GMT +200)
  v2/ansible/modules/core: (detached HEAD cb69744bce) last updated 2014/12/05 14:16:41 (GMT +200)
  v2/ansible/modules/extras: (detached HEAD 8a4f07eecd) last updated 2014/12/05 14:16:46 (GMT +200)
  configured module search path = None
```
##### Environment:

FC 19, AWS.
##### Summary:

Although advertised in the online documentation: http://docs.ansible.com/rds_module.html (but not in the ansible-doc page), the parameter 'publicly_accessible' is not accepted while creating a Postgres DB in RDS.
##### Steps To Reproduce:

```
   - name: adding the Postgres RDS instance
      local_action:
        module: rds
        backup_retention: 7 
        backup_window: 03:00-04:00
        command: create
        db_engine: postgres
        engine_version: 9.3.5
        instance_name: postgres_db
        instance_type: db.m3.large
        maint_window: Sat:02:00-Sat:03:00
        size: 100
        subnet: subnet_name
        username: "{{ user }}"
        password: "{{ password }}"
        region: "{{ region }}" 
        vpc_security_groups:
          - "{{ postgres_sg_creation.group_id }}"
        port: 5432
        publicly_accessible: yes
        wait: yes
        wait_timeout: 1800
    when: "{{ rds|bool }}"
```
##### Expected Results:

The DB instance is successfully created and is publicly accessible.
##### Actual Results:

```
TASK: [adding the DWH RDS instance] ******************************************* 
failed: [localhost -> 127.0.0.1] => {"failed": true}
msg: unsupported parameter for module: publicly_accessible

FATAL: all hosts have already failed -- aborting
```
