### ISSUE TITLE
when role A depends on role B, role B is run only once for multiple occurences of role A

### ISSUE THREAD

**Issue by ghost** [ansible/ansible-modules-core#804]
My playbook and roles A, B are defined as follows:
### test.yml

``` yaml

---
- hosts: all
  gather_facts: no
  roles:
  - { role: A, var: called_from_play_1 }
  - { role: A, var: called_from_play_2 }
```
### roles/A/tasks/main.yml

``` yaml

---
- debug: var=var

- { include: ../../B/tasks/main.yml, var: called_from_include_in_A }
```
### roles/A/meta/main.yml

``` yaml

---
allow_duplicates: yes
dependencies:
- { role: B, var: called_from_meta }
```
### roles/B/tasks/main.yml

``` yaml

---
- debug: var=var
```

Now when I run `ansible-playbook -i test.ini test.yml`, I **expect that**
this dependency role B is triggered for the both occurrences of A.

The **actual result** is however:

```
PLAY [all] ******************************************************************** 

TASK: [B | debug var=var] ***************************************************** 
ok: [daredevil] => {
    "var": "called_from_meta"
}

TASK: [A | debug var=var] ***************************************************** 
ok: [daredevil] => {
    "var": "called_from_play_1"
}

TASK: [A | debug var=var] ***************************************************** 
ok: [daredevil] => {
    "var": "called_from_include_in_A"
}

TASK: [A | debug var=var] ***************************************************** 
ok: [daredevil] => {
    "var": "called_from_play_2"
}

TASK: [A | debug var=var] ***************************************************** 
ok: [daredevil] => {
    "var": "called_from_include_in_A"
}

PLAY RECAP ******************************************************************** 
daredevil                  : ok=5    changed=0    unreachable=0    failed=0   
```

This means that role B is only triggered **once** if defined as dependency of role A. The workaround in my specific case would be to instead use `include:` as also shown here for comparison, but it would be great to see role dependencies behave properly.
