### ISSUE TITLE
lineinfile state=absent does not remove line

### ISSUE THREAD

**Issue by tetherit** [ansible/ansible-modules-core#810]
I'm using Ansible 1.8.2, I have this code:

``` yaml
- name: 'Ensure DPKG will overwrite old configs'
  lineinfile:
    dest: '/etc/apt/apt.conf.d/local'
    line: 'DPkg::options { "--force-confdef"; "--force-confnew"; }'
    create: 'yes'
  when: 'ansible_lsb.id == "Ubuntu" and ansible_lsb.release|float < {{ ubuntu_release }}'

- name: "Do Release Upgrade"
  action: "command do-release-upgrade -f DistUpgradeViewNonInteractive"
  when: 'ansible_lsb.id == "Ubuntu" and ansible_lsb.release|float < {{ ubuntu_release }}'
  register: release_upgraded

- name: 'Remove temporary DPKG overwriting all old configs'
  lineinfile:
    dest: '/etc/apt/apt.conf.d/local'
    line: 'DPkg::options { "--force-confdef"; "--force-confnew"; }'
    state: 'absent'
```

The line is added correctly, but not removed :( - any ideas?

The worst is that Ansible reports "ok" so the expectation is the line was successfully removed when in reality the command was ignored.
