### ISSUE TITLE
Cannot specify volume_size and either one of name or id

### ISSUE THREAD

**Issue by raven-kg** [ansible/ansible-modules-core#834]
Hello everyone. I have a problem - trying to automate the purchase of new EC2 instances. Here's my playbook:

```
---                               
  - name: Provision new EC2 instance
    hosts: local
    connection: local
    gather_facts: False
    tags: provisioning
    vars:
      instance_type: t2.micro
      security_group: <my sec. group>
      image: <my ami>
      region: <my region>
      keypair: <my keypair>
      subnet: <my subnet>
      zone: <my availability zone>
    tasks:
      - name: Launch new Instance
        local_action:
           module: ec2
           instance_tags: "Name=TestInstance"
           group: "{{ security_group }}"
           instance_type: "{{ instance_type}}"
           image: "{{ image }}"
           wait: true
           count: 1
           region: "{{ region }}"
           zone: "{{ zone }}"
           vpc_subnet_id: "{{ subnet }}"
           keypair: "{{ keypair }}"
           register: ec2
      - name: Create new EBS-storage
        local_action:
           module: ec2_vol
           device_name: /dev/xvdf
           volume_type: gp2
           name: docker_"{{ item.id }}"
           region: "{{ region }}"
           volume_size: 5
           instance: "{{ item.id }}"
           with_items: ec2.instances
  - name: With the newly provisioned EC2 node configure that thing
    hosts: launched
    sudo: yes
    remote_user: centos
    gather_facts: True
```

The first task is performed - an instance is created. The second task fails with following error:

> TASK: [Create new EBS-storage] ****************************************\* 
> failed: [localhost -> 127.0.0.1] => {"failed": true}  
> msg: Cannot specify volume_size and either one of name or id                    
> 
> FATAL: all hosts have already failed -- aborting

My current Ansible version is 1.9 (from git, updated to have gp2 volume_type works), but I got that error with 1.8.3 too.
