### ISSUE TITLE
'InvalidIPAddress.InUse: Address XXX is in use' error when re-running task calling ec2 module

### ISSUE THREAD

**Issue by daniilyar** [ansible/ansible-modules-core#835]
Consider Ansible playbook creating a single Amazon EC2 instance:

```

---
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:

    - name: Launch a single Amazon EC2 instance
      ec2:
        region: us-west-2
        group: test_grp
        keypair: test_key
        instance_type: t2.micro
        image: ami-25ebb515
        instance_tags:
          Name: XXX
        vpc_subnet_id: subnet-ca4fefbc
        private_ip: 10.118.20.40
        assign_public_ip: false
        source_dest_check: true
        wait: true
```

It works well for the first launch and successfully spins up an AWS instance.
But if I relaunch the play I am getting an error:

```
failed: [localhost] => {"failed": true}
msg: Instance creation failed => InvalidIPAddress.InUse: Address 10.118.20.40 is in use.
```

It is contantly reproducable on ansible 1.8.2+, no matter if you use "state=present" parameter or not.

For me it looks more as bug than feature. As for me, expected behavior for this case should be like below:
- If host with specified IP is already present, check it's settings (assign_public_ip, source_dest_check, volumes, and so on)
- If host settings matches, return with 'ok'. Otherwise update host's settings appropriately (add missing volumes, update boolean params and so on).

That's if we live in ideal world. But, ofc, that would be hard to implement that checking down of all instance props in some prioritized order and matching them to playbook values.

So I'd be happy just if ec2 module stop failing on second launch by skipping instance creation if instance with given IP is already present.

**Comment by MrMMorris** [comment]
+1

I am creating multiple instances with private_ip set using with_items and although they are created, subsequent runs error with `InvalidIPAddress.InUse`

``` yaml
- name: Create AWS resources
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    keypair: blah
    security_group: sg-a888eecc
    instance_type: t2.small
    image: ami-xxxxxxx
    region: us-east-1
  tasks:
  - name: create an EC2 instance
    local_action:
      module: ec2
      key_name: "{{ keypair }}"
      group_id: "{{ security_group }}"
      vpc_subnet_id: "{{ item.subnet }}"
      instance_type: "{{ instance_type }}"
      image: "{{ image }}"
      region: "{{ region }}"
      private_ip: "{{ item.ip }}"
      wait: yes
      instance_tags:
        Name: "{{ item.name }}"
        type: consul
      volumes:
        - device_name: /dev/sda1
          volume_size: 25
    with_items:
      - { ip: 10.0.0.5, subnet: subnet-edffb4d7, name: 'Consul Server 1' }
      - { ip: 10.0.0.6, subnet: subnet-edffb4d7, name: 'Consul Server 2' }
      - { ip: 10.0.1.5, subnet: subnet-b7fc9bc0, name: 'Consul Server 3' }
```

**Comment by bennojoy** [comment]
The default behaviour of the module is to try to create the instance if the exact_count parameter is not given and hence getting this message, adding exact_count and count_tag should get this sorted out.

**Comment by MrMMorris** [comment]
@bennojoy 

``` yaml
- name: Create AWS resources
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    keypair: blah
    security_group: sg-a888eecc
    instance_type: t2.small
    image: ami-xxxxxxx
    region: us-east-1
  tasks:
  - name: create an EC2 instance
    local_action:
      module: ec2
      key_name: "{{ keypair }}"
      group_id: "{{ security_group }}"
      vpc_subnet_id: "{{ item.subnet }}"
      instance_type: "{{ instance_type }}"
      image: "{{ image }}"
      region: "{{ region }}"
      private_ip: "{{ item.ip }}"
      wait: yes
      instance_tags:
        Name: "{{ item.name }}"
        type: consul
      exact_count: 3
      count_tag:
        type: consul
      volumes:
        - device_name: /dev/sda1
          volume_size: 25
    with_items:
      - { ip: 10.0.0.5, subnet: subnet-edffb4d7, name: 'Consul Server 1' }
      - { ip: 10.0.0.6, subnet: subnet-edffb4d7, name: 'Consul Server 2' }
      - { ip: 10.0.1.5, subnet: subnet-b7fc9bc0, name: 'Consul Server 3' }
```

`msg: Instance creation failed => InvalidParameterCombination: You may only launch a single instance when specifying private IP addresses. You have specified '3' instances`

**Comment by bennojoy** [comment]
can you please try exact_count: 1 and 
count_tag: 
   name: "{{ item.name }}"

**Comment by MrMMorris** [comment]
@bennojoy 

``` yaml
- name: Create AWS resources
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
  - name: create an EC2 instance
    local_action:
      module: ec2
      wait: yes
      instance_tags:
        Name: "{{ item.name }}"
        type: consul
      exact_count: 1
      count_tag:
        name: "{{ item.name }}"l
      volumes:
    with_items:
      - { ip: 10.0.0.5, subnet: subnet-edffb4d7, name: 'Consul Server 1' }
      - { ip: 10.0.0.6, subnet: subnet-edffb4d7, name: 'Consul Server 2' }
      - { ip: 10.0.1.5, subnet: subnet-b7fc9bc0, name: 'Consul Server 3' }
```

`msg: Instance creation failed => InvalidIPAddress.InUse: Address 10.0.0.10 is in use.`
