### ISSUE TITLE
file module dereferences relative symlinks incorrectly

### ISSUE THREAD

**Issue by ngaya-ll** [ansible/ansible-modules-core#852]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.8.4
##### Environment:

Ubuntu 12.04
##### Summary:

The file module dereferences symlinks with relative paths incorrectly when follow=yes.
##### Steps To Reproduce:

The following playbook demonstrates the issue:

```

---
- hosts: 127.0.0.1
  connection: local
  tasks:
    # Create test directory
    - file: name=foo state=directory
    - file: name=foo/bar state=touch

    # Create relative symlink
    - file: state=link src=bar dest=foo/baz

    # Test that symlink target exists
    - file: name=foo/baz state=file follow=yes
```
##### Expected Results:

All tasks should succeed.
##### Actual Results:

The last task fails with message "file (bar) is absent, cannot continue".
##### Discussion:

The problem is due to a misuse of [`os.readlink()`](https://docs.python.org/2/library/os.html#os.readlink).  The docs suggest using `os.path.join(os.path.dirname(path), os.readlink(path))` to get a correct path (this will work for both absolute and relative symlinks).  This does not deal with symlinks that point to other symlinks, however.  It might be better to avoid the problem by using [`os.path.realpath()`](https://docs.python.org/2/library/os.path.html#os.path.realpath) to get a canonical filename.

One place in the code where this bug occurs is on [line 247 of files/file.py](https://github.com/ansible/ansible-modules-core/blob/release1.8.4/files/file.py#L247), but there may be other occurrences as well.
