### ISSUE TITLE
service 'enabled=yes' parameter is not idempotent

### ISSUE THREAD

**Issue by drybjed** [ansible/ansible-modules-core#875]
##### Issue Type:

Bug Report
##### Ansible Version:

Ansible devel, possibly Ansible 1.8.x
##### Environment:

Ubuntu, Debian Wheezy
##### Summary:

`service: enabled=yes` parameter is not idempotent and always resutls in a changed state. I have bisected the problem to https://github.com/ansible/ansible/commit/dd484e82111e2856af0dbcf6c48f2385743cbd63
##### Steps To Reproduce:

```

---
- hosts: all
  sudo: True
  tasks:

    - name: Start redis and enable
      service: name=redis-server state=started enabled=yes

    - name: Start redis
      service: name=redis-server state=started

    - name: Start redis and enable
      service: name=redis-server state=started enabled=yes

    - name: Start redis
      service: name=redis-server state=started
```
##### Expected Results:

If `redis-server` was previously installed, all tasks should result in "OK" state. If it was installed by the playbook, I expect 1 changed state (first task).
##### Actual Results:

```
PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [coder]

TASK: [Start redis and enable] ************************************************ 
changed: [coder]

TASK: [Start redis] *********************************************************** 
ok: [coder]

TASK: [Start redis and enable] ************************************************ 
changed: [coder]

TASK: [Start redis] *********************************************************** 
ok: [coder]

PLAY RECAP ******************************************************************** 
Start redis and enable -------------------------------------------------- 0.17s
Start redis ------------------------------------------------------------- 0.16s
coder                      : ok=5    changed=2    unreachable=0    failed=0
```
