### ISSUE TITLE
Add state=empty into file module

### ISSUE THREAD

**Issue by Nindaleth** [ansible/ansible-modules-core#902]
**Issue Type:**

Feature Idea

**Ansible Version:**

```
$ ansible --version
ansible 1.8.4
  configured module search path = None
```

**Environment:**

N/A

**Summary:**

In our playbooks we need to empty some folders, but currently our only option seems to be using `command` or `shell` module. It has its uses to leave the folder intact as there may have been some owner/permission changes, or alternatively it may be a mountpoint that is not even possible to delete.
Similar ideas might be had about files as well.
###### Proposed behaviour:
- Directories: remove all files and subdirectories inside so that the directory contains nothing
- Files: truncate the target file, if it was empty then touch it
- Symlinks/Hardlinks: check which of the previous 2 types it is, act accordingly

State change changed if previously non-empty, ok if previously empty, failed if still non-empty.
###### Example of usage:

```
- name: Clean folders
  file: path=/var/zookeeper state=empty

- name: Truncate logs
  file: path=/var/log/local6 state=empty
```

**Workaround (how to empty a directory completely):**

```
- find: path=/my/dir file_type=file
  register: files

- find: path=/my/dir file_type=directory
  register: directories

- file: state=absent path={{ item.path }}
  with_items: 
    - "{{ files }}"
    - "{{ directories }}"
```

Not sure if there is a reasonable workaround for emptying _multiple_ directories.

**Comment by pako-pl** [comment]
+1

**Comment by monkseal** [comment]
+1

**Comment by maticmeznar** [comment]
I just needed this myself. +1 indeed. Please make it happen!

**Comment by DavidGoodwin** [comment]
+1

**Comment by lerouxju** [comment]
+1

**Comment by gechr** [comment]
+1

**Comment by adeelshahid** [comment]
+1

**Comment by mutantcornholio** [comment]
+1

**Comment by Element20Three** [comment]
+1

**Comment by rafaelmagu** [comment]
Please click the Subscribe button on the right instead of adding `+1` as a comment.

**Comment by mutantcornholio** [comment]
Github truly needs issue voting...

**Comment by adeelshahid** [comment]
I need to hit the unsubscribe button with all these +1's coming into my inbox :smile:

**Comment by m11y** [comment]
+1

**Comment by tduchateau** [comment]
+1

**Comment by tersmitten** [comment]
+1

**Comment by thom8** [comment]
+1

**Comment by caljess599** [comment]
This would be great!

**Comment by bcoca** [comment]
```
- find: path=/my/dir
  register: files

- file: state=absent path={{item}}
  with_items: "{{files}}"
```

**Comment by Nindaleth** [comment]
Thanks Brian! That should help in most cases. With that in mind:

completely empty a directory
```
- find: path=/my/dir file_type=file
  register: files

- find: path=/my/dir file_type=directory
  register: directories

- file: state=absent path={{ item.path }}
  with_items: 
    - "{{ files }}"
    - "{{ directories }}"
```

Now, say I want to do the above for 10 directories, how could I go about that in a smart way? E.g. for an installed product clear any present logs, dumps, user configuration overrides, plugins, databases, downloads...

**Comment by thom8** [comment]
Something like this should work >

```
vars:
  empty_dirs:
    - "/dir1"
    - "/dir2"
    - ...

- file: state=absent path={{ item }}
  with_items: empty_dirs

- file: state=directory path={{ item }}
  with_items: empty_dirs
```

However this feature would be nice as it doesn't require multiple tasks or separate methods for files and directories.

**Comment by Nindaleth** [comment]
@thom8 That would discard the owner/group/access metadata, which is why I created this issue in the first place:

> It has its uses to leave the folder intact as there may have been some owner/permission changes, or alternatively it may be a mountpoint that is not even possible to delete.

**Comment by m-emelchenkov** [comment]
+1

**Comment by jc888** [comment]
+1

**Comment by st3fanK** [comment]
+1

**Comment by j-carpentier** [comment]
+1

**Comment by robputt** [comment]
+1

**Comment by caspark** [comment]
Until #3095 gets merged (fingers crossed), here's a workaround snippet which will empty a list of directories of files without deleting the directories themselves:

```
- name: Find files to purge
  find:
    path: "{{ item }}"
  register: find_results
  with_items: "{{ directories_to_purge_files_from }}"

  # ugly hack to extract paths; e.g. we want find_results.results[0].files[0].path (except for 0 to n in each case)
- name: Extract files to purge from find result
  local_action: command python -c "print '\n'.join([f['path'] for r in {{ find_results.results }} for f in r['files']])"
  register: find_results
  changed_when: false

- name: Ensure files to purge are absent
  file:
    state: absent
    path: "{{ item }}"
  with_items: "{{ find_results.stdout_lines|default([]) }}"

  # clean up just in case, since registered variables live on for the whole playbook
- name: Clean up temporary variable
  set_fact:
    find_results: ""
```

I want this as sort of a partial reset button, so I've got this as a role in `purge-files/tasks/main.yml` and it's set up in my playbook so that it requires a specific variable to be set:

```
- hosts: all
  roles:
  - role: purge-files
    tags: purge
    when: do_explicit_config_purge
    directories_to_purge_files_from:
      - /etc/nginx/sites-available
      - /etc/nginx/sites-enabled
      # you get the idea
```

So I can invoke it with something like `ansible-playbook myplaybook.yml --tags purge -e 'do_explicit_config_purge=true'`

(If you want to always run the "empty these directories" tasks, then you don't need `|default([])` - but I needed to add it to avoid a warning about `find_results.stdout_lines` being undefined when `not do_explicit_config_purge`; that smelt like a bug to me but seems to stem from `when` on roles being implemented as pushing the `when` down to tasks in a role, and `with_*` loops will be evaluated before `when`s.)
