### ISSUE TITLE
unarchive + folded scalar vs structured map

### ISSUE THREAD

**Issue by JeffHailer-MRM** [ansible/ansible-modules-core#913]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.8.2
  configured module search path = None
##### Environment:

Centos 6
##### Summary:

I'm seeing a difference between running a task that uses "unarchive" using folded scalar line breaks vs structured map notation.
##### Steps To Reproduce:

If I run this, ansible honors the "creates" and properly skips if the specified directory exists - seemingly regardless of file ownership/permissions.

```
- name: copy and unpack form1
  unarchive: >
    src={{ java_archive }}
    dest={{ jdk_install_dir }}/
    copy=yes
    creates={{ jdk_install_dir }}/{{ java_dir }}
```

If I run this, and then subsequently chown the installation, ansible ALWAYS performs the unarchive.  In vv output I see it doing a recursive analysis of all files in the target dir and sees ownership is different, whereas in "form1" above it does not.

```
- name: copy and unpack form2
  unarchive:
    src: "{{ java_archive }}"
    dest: "{{ jdk_install_dir }}/"
    copy: yes
    creates: "{{ jdk_install_dir }}/{{ java_dir }}"
```
##### Expected Results:

behavior should be consistent between "form1" and "form2"
##### Actual Results:

"form1" seems to ignore changes in ownership/permissions -- checking for existence only.
