### ISSUE TITLE
Avahi does not disable properly with systemd on centos 7

### ISSUE THREAD

**Issue by mattstep** [ansible/ansible-modules-core#917]
The following results in a stopped avahi-daemon, however it remains enabled.

```
- name: Disable avahi-daemon.socket
  service: name=avahi-daemon.socket enabled=no state=stopped
- name: Disable avahi-daemon
  service: name=avahi-daemon enabled=no state=stopped
- name: Disable avahi-daemon.service
  service: name=avahi-daemon.service enabled=no state=stopped
```

**Comment by dbrgn** [comment]
Similar issue here:

``` yaml
- name: Disable graphical target
  service: name=graphical.target enabled=no
- name: Enable multi-user target
  service: name=graphical.target enabled=yes
```

None of these has any effects.
- Ansible version: `ansible 1.9.0.1`
- Host: Arch Linux
- Target: Raspberry Pi with Raspbian and Systemd
