### ISSUE TITLE
Subversion: unsupported parameter for module: --password

### ISSUE THREAD

**Issue by brettheath** [ansible/ansible-modules-core#929]
Issue Type:

Bug Report

Ansible Version:

ansible 1.8.2
  configured module search path = None

Environment:

CentOS release 6.5 (Final)
Linux vzw-cadc-ca0 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

Summary:

Using the subversion module I'm getting an error in the execution saying

msg: unsupported parameter for module: --password

It appears that this error is saying that the --password flag is not supported for the subversion module, when in the documentation for this module it shows the --password flag as being available.

Steps To Reproduce:
1. Run the below playbook against a Centos 6.5 host
2. Need eforge host on the network, with a repo available to download via https and requiring a username and password

playbook:
    ---

```
- name: Configure cadc server with subversion
  hosts: 192.168.1.211
  sudo: True
  vars_prompt:
    - name: 'eforge_user'
      prompt: 'eforge username '
      private: no
    - name: 'eforge_pass'
      prompt: 'password: '
      private: yes
  vars:
    eforge_repo: "https://eforge-svn.mydomain.net/svn/repos/cadc_pas_rnam_common_rsgtunnelkeeper/tags"
    user: attca0
  tasks:
    - name: install subversion
      yum: name={{ item }} state=present
      with_items:
        - subversion
        - nc
    - name: create directory
      file: path=/home/{{ user }}/RSGTunnelKeeper state=directory owner=attca0 group=attca0 mode=0755
    - name: install RSG Tunnel Keeper
      sudo_user: attca0
      subversion: --username="{{ eforge_user }}" --password="{{ eforge_pass }}" repo={{ eforge_repo }} dest=/home/{{ user }}/RSGTunnelKeeper
    - name: configure subversion
      copy: src=files/config.subversion dest=/home/{{ user }}/.subversion/config owner=attca0 group=attca0 mode=0664
```

Expected Results:

Could you please check if this module is supporting the --password flag in my configuration, if not could you please add that feature? If it does, could you please tell me what bone head mistake I am making in my code to cause this issue?

Actual Results:
ansible-playbook -vvv cadc.yml output:

```
TASK: [install RSG Tunnel Keeper] *********************************************
<192.168.1.211> ESTABLISH CONNECTION FOR USER: dummy on PORT 22 TO 192.168.1.211
<192.168.1.211> REMOTE_MODULE subversion --username="dummy" --password="password" repo=https://eforge-svn.mydomain.net/svn/repos/cadc_pas_rnam_common_rsgtunnelkeeper/tags     dest=/home/attca0/RSGTunnelKeeper
<192.168.1.211> EXEC /bin/sh -c 'mkdir -p /tmp/ansible-tmp-1426137053.09-121205343506454 && chmod a+rx /tmp/ansible-tmp-1426137053.09-121205343506454 && echo /tmp/ansible-    tmp-1426137053.09-121205343506454'
<192.168.1.211> PUT /tmp/tmpg4rfCK TO /tmp/ansible-tmp-1426137053.09-121205343506454/subversion
<192.168.1.211> EXEC /bin/sh -c 'chmod a+r /tmp/ansible-tmp-1426137053.09-121205343506454/subversion'
<192.168.1.211> EXEC /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=kdzozvwdnprthrqorawjvnptjwiogykt] password: " -u attca0 /bin/sh -c '"'"'echo SUDO-SUCCESS-    kdzozvwdnprthrqorawjvnptjwiogykt; LANG=C LC_CTYPE=C /usr/bin/python /tmp/ansible-tmp-1426137053.09-121205343506454/subversion'"'"''
<192.168.1.211> EXEC /bin/sh -c 'rm -rf /tmp/ansible-tmp-1426137053.09-121205343506454/ >/dev/null 2>&1'
failed: [192.168.1.211] => {"failed": true}
msg: unsupported parameter for module: --password

FATAL: all hosts have already failed -- aborting
```
