### ISSUE TITLE
ec2_asg : can't set desired_capacity to 0

### ISSUE THREAD

**Issue by Seraf** [ansible/ansible-modules-core#931]
##### Issue Type:

Bug Report
##### Ansible Version:

Ansible version 1.8.1 installed with pip
##### Environment:

Debian 7 Wheezy 64bits
boto==2.36.0
botocore==0.76.0
ansible==1.8.4
##### Summary:

I'm trying to use the ec2_asg module here : http://docs.ansible.com/ec2_asg_module.html
The goal is to kill all instances during the night and boot them the morning.
Ansible doesn't accept to set an minimum of 0 and a desired capacity of 0. Changes are ignored but works if I set a value > 0.
##### Steps To Reproduce:

Here is my playbook. These values works on AWS Web Console : 

```
- name: Shutdown PREPROD
  hosts: localhost
  remote_user: root

  tasks:
  - name: Shutdown instances
    ec2_asg:
      region: eu-west-1
      name: MYASGNAME
      min_size: 0
      max_size: 0
      desired_capacity: 0
```
##### Expected Results:

The autoscaling group should be setup correctly with values of 0.
##### Actual Results:

Changes are ignored if values are 0, but if these values are > 0, it works correctly.
