### ISSUE TITLE
yum state=latest does not handle URL

### ISSUE THREAD

**Issue by gtirloni** [ansible/ansible-modules-core#948]
Issue Type: Bug Report

Ansible Version:

```
$ ansible --version
ansible 1.9 (devel caf2a96ef9) last updated 2015/03/15 16:31:02 (GMT -400)
  lib/ansible/modules/core: (detached HEAD aa6c73f11b) last updated 2015/02/16 14:30:49 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 2ffd7235e5) last updated 2015/02/16 10:12:13 (GMT -400)
  v2/ansible/modules/core: (detached HEAD 34784b7a61) last updated 2015/02/16 10:12:16 (GMT -400)
  v2/ansible/modules/extras: (detached HEAD 312d59061c) last updated 2015/02/16 10:12:20 (GMT -400)
  configured module search path = None
```

Environment: Fedora 21

Summary:

The yum module does not handle URLs in variables correctly ("No Package matching 'URL_HERE' found available, installed or updated").

Steps To Reproduce:

```
hosts: localhost
sudo: yes
vars:
    - vbox_pkg: http://download.virtualbox.org/virtualbox/4.3.24/VirtualBox-4.3-4.3.24_98716_fedora18-1.x86_64.rpm
tasks:
  - name: Ensure VirtualBox package is installed
    yum:
      name: "{{ vbox_pkg }}"
      state: latest
```

Expected Results:

Same results as running task using Ansible syntax (package is installed/updated).

```
tasks:
  - name: Ensure VirtualBox package is installed
    yum: name="{{ vbox_pkg }}"
```

Actual Results:

```
TASK: [Ensure VirtualBox package is installed] ******************************** 
failed: [localhost] => {"changed": false, "failed": true, "rc": 0, "results": []}
msg: No Package matching 'http://download.virtualbox.org/virtualbox/4.3.24/VirtualBox-4.3-4.3.24_98716_fedora18-1.x86_64.rpm' found available, installed or updated
```
