### ISSUE TITLE
vsphere_guest module: cluster parameter not optional when deploying from template

### ISSUE THREAD

**Issue by sebastienbonami** [ansible/ansible-modules-core#951]
##### Issue Type:

Bug Report
##### Ansible Version:

```
$ ansible --version
ansible 1.9 (devel b11be68249) last updated 2015/03/16 22:21:38 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 8658b82de7) last updated 2015/03/16 22:22:58 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 696bc60caa) last updated 2015/03/16 22:23:01 (GMT -400)
  v2/ansible/modules/core: (detached HEAD 34784b7a61) last updated 2015/03/16 22:23:04 (GMT -400)
  v2/ansible/modules/extras: (detached HEAD 46e316a20a) last updated 2015/03/16 22:23:07 (GMT -400)
  configured module search path = None
```
##### Environment:

N/A
##### Summary:

The cluster parameter should be optional when deploying a guest from a template. For example, with a standalone ESXi host.
##### Steps To Reproduce:

Playbook example below.

```

---
- hosts: localhost
  tasks:
    - name: deploy new vm from template
    - vsphere_guest:
          vcenter_hostname: "{{ esxi_hostname }}"
          username: "{{ esxi_username }}"
          password: "{{ esxi_password }}"
          guest: newvm001
          from_template: yes
          template_src: "{{ esxi_template }}"
          resource_pool: "{{ esxi_pool }}"
```
##### Expected Results:

The task should be executed successfully without the need of a cluster parameter.
##### Actual Results:

```
TASK: [deploy new vm from template] ***********************************************
failed: [localhost] => {"failed": true}
msg: parameters are required together: ['resource_pool', 'cluster']

FATAL: all hosts have already failed -- aborting
```
