### ISSUE TITLE
Conditional pause does not work as expected

### ISSUE THREAD

**Issue by nikut** [ansible/ansible-modules-core#96]
##### Issue Type:

Bug report
##### Ansible Version:

ansible 1.7.2
##### Environment:

CentOS release 5.9 (Final)
##### Summary:

When using the pause module together with a when: conditional, it's not always executed when it should. Looks like the condition is only evaluated against the first host in the host list. This makes it impossible to use pause e.g. after a conditional restart of some service to allow the service to come back up before continuing.
##### Steps To Reproduce:

Inventory:

```
[testhosts]
hosta
hostb
hostc
hostd
```

Playbook:

```

---
- name: Test pause
  hosts: testhosts
  gather_facts: no
  tasks:
    - name: Pause for hosta
      local_action: pause seconds=5
      when: inventory_hostname == 'hosta'

    - name: Pause for hostb
      local_action: pause seconds=5
      when: inventory_hostname == 'hostb'

    - name: Pause for hostd
      local_action: pause seconds=5
      when: inventory_hostname == 'hostd'
```
##### Expected Results:

Three 5 second pauses, one for hosta, one for hostb and one for hostd.
##### Actual Results:

Only one pause for hosta. The hostb and hostd pauses are skipped.

```
PLAY [Test pause] ************************************************************* 

TASK: [Pause for hosta] ******************************************************* 
(^C-c = continue early, ^C-a = abort)
[hosta, hostb, hostc, hostd]
Pausing for 5 seconds
ok: [hosta -> 127.0.0.1]

TASK: [Pause for hostb] ******************************************************* 
skipping: [hosta -> 127.0.0.1]

TASK: [Pause for hostd] ******************************************************* 
skipping: [hosta -> 127.0.0.1]

PLAY RECAP ******************************************************************** 
hosta                      : ok=1    changed=0    unreachable=0    failed=0   
hostb                      : ok=1    changed=0    unreachable=0    failed=0   
hostc                      : ok=1    changed=0    unreachable=0    failed=0   
hostd                      : ok=1    changed=0    unreachable=0    failed=0   
```

**Comment by sivel** [comment]
The `pause` action_plugin is what is referred to as a host list bypass plugin. This means that `pause` will not execute for every host targeted by a playbook. Instead `pause` will only execute on the first host in the hosts list as defined by inventory. Due to this, `inventory_hostname` will always evaluate to `hosta`, making some of your `when` statements false.

With that understanding, your tasks are doing what they are instructed to do.

**Comment by nikut** [comment]
Thanks for the explanation, @sivel . This behaviour is not mentioned in the documentation and I think it's highly counterintuitive. Also, it's not an issue only with `inventory_hostname`, please consider the following playbook:

```
---
- name: Test pause
  hosts: testhosts
  gather_facts: no
  tasks:
    - local_action: set_fact pause_needed=true
      when: inventory_hostname == 'hostb'

    - local_action: pause seconds=5
      when: pause_needed is defined and pause_needed
```

I think it would be reasonable to assume that the above playbook would pause for 5 seconds at hostb, but this does not happen:

```
PLAY [Test pause] ************************************************************* 

TASK: [set_fact pause_needed=true] ******************************************** 
skipping: [hosta -> 127.0.0.1]
skipping: [hostc -> 127.0.0.1]
skipping: [hostd -> 127.0.0.1]
ok: [hostb -> 127.0.0.1]

TASK: [pause seconds=5] ******************************************************* 
skipping: [hosta -> 127.0.0.1]

PLAY RECAP ******************************************************************** 
hosta                      : ok=0    changed=0    unreachable=0    failed=0   
hostb                      : ok=1    changed=0    unreachable=0    failed=0   
hostc                      : ok=0    changed=0    unreachable=0    failed=0   
hostd                      : ok=0    changed=0    unreachable=0    failed=0   
```

How would you achieve the following?
1. Update a configuration on a number of hosts and register the result (`register: update`)
2. Restart the affected services `when: update.changed`
3. Pause for a moment after each restart so that the cluster can realign itself (I tried to use  `pause ... when: update.changed` for this but, obviously, failed)
