### ISSUE TITLE
[Docker] Old containers aren't cleaned up when using count

### ISSUE THREAD

**Issue by MrMMorris** [ansible/ansible-modules-core#989]
**Issue Type:**

Bug Report 

**Ansible Version:**

ansible 1.9 (devel 85cfe1bd52)

**Environment:**

Ubuntu 14.04

**Summary:**

When using `count`, old containers are not removed

**Steps To Reproduce:**

Create containers with `count: 2`, `pull: always`, and `state: reloaded`. Run task to pull an updated image.

```
- name: run node client container
  docker:
    image: "company/tv-client:dev-latest"
    env: "SERVICE_NAME=client,SERVICE_TAGS=dev"
    ports: 80
    restart_policy: always
    pull: always
    state: reloaded
    count: 2
```

**Expected Results:**

The 2 original containers are gone and 2 new ones with the latest image are running in their place

**Actual Results:**

The 2 original containers are still running alongside the new containers, but without image tags

```
CONTAINER ID        IMAGE                                  COMMAND                CREATED             STATUS              PORTS                            NAMES
eda5d790bbc1        company/tv-client:dev-latest           "nginx -g 'daemon of   5 seconds ago       Up 5 seconds        443/tcp, 0.0.0.0:49204->80/tcp   serene_blackwell
fce2c32876eb        company/tv-client:dev-latest           "nginx -g 'daemon of   6 seconds ago       Up 5 seconds        443/tcp, 0.0.0.0:49203->80/tcp   agitated_lumiere
05ef9af927ee        147b87b45e35                           "nginx -g 'daemon of   20 minutes ago      Up 20 minutes       443/tcp, 0.0.0.0:49202->80/tcp   clever_pike
0bdeb3ef8f37        147b87b45e35                           "nginx -g 'daemon of   20 minutes ago      Up 20 minutes       443/tcp, 0.0.0.0:49201->80/tcp   lonely_nobel
```

**Comment by MrMMorris** [comment]
CCing @smashwilson

**Comment by smashwilson** [comment]
Thanks. Yeah, `get_deployed_containers` still needs some work.

**Comment by smashwilson** [comment]
@MrMMorris I have a fix ready in #993. Would you mind trying it out?

**Comment by smashwilson** [comment]
As a workaround for anyone finding this before 1.9.1 ships, you can emulate the same behavior with named containers and `with_sequence`:

``` yaml
- name: launch four containers
  docker:
    image: whatever
    command: sleep 1d
    name: whatever_{{ item }}
    pull: always
    state: reloaded
 with_sequence: count=4
```
