### ISSUE TITLE
Subsequent clone uses depth 1

### ISSUE THREAD

**Issue by warvariuc** [ansible/ansible-modules-core#996]
##### Issue Type:

Bug report
##### Component Name:

git module
##### Ansible Version:

ansible 1.8.4
##### Environment:

Ubuntu 14.10. Installed using `sudo pip install ansible`
##### Summary:

I have two subsequent `git clone` from two different repos on github. The first clone uses `depth 1`. The second does not. Looks like Ansible still uses depth 1 for the second clone so checkout to a branch doesn't work.
##### Steps To Reproduce:

``` yaml
- name: clone project
  git:
    repo: git@github.com:user/app_1.git
    version: develop
    dest: "{{ app_1_dir }}"
    depth: 1
    accept_hostkey: yes

- name: clone project
  git:
    repo: git@github.com:user/app_2.git
    version: develop
    dest: "{{ app_2_dir }}"
    accept_hostkey: yes
```
##### Expected Results:

Both clones should be successful.
##### Actual Results:

```
PLAY [webservers] ************************************************************* 

GATHERING FACTS *************************************************************** 
ok: [virtualbox]

TASK: [fail msg="These tasks were made for Ubuntu 14.04 LTS"] ***************** 
skipping: [virtualbox]

TASK: [clone project] ********************************************************* 
changed: [virtualbox]

TASK: [clone project] ********************************************************* 
failed: [virtualbox] => {"failed": true}
msg: Failed to checkout develop
```

When replaying -- the same result.

When commenting  `depth: 1` in the first clone -- the same result.

When I remove both cloned repos and re-run -- it goes ok.

**Comment by robinro** [comment]
@warvariuc 
Can you please recheck with ansible 2.1?
I guess this should be fixed now.

**Comment by mindojo-victor** [comment]
@robinro I don't have the infrastructure at hand to verify this. Let's close and reopen if someone stumbles on this again.

**Comment by ansibot** [comment]
@warvariuc we are unable to validate that "" is an existing ansible module.

We are expecting a component name that matches something that can be found in:
* http://docs.ansible.com/ansible/list_of_all_modules.html

Please revise the component name in the description.

[click here for bot help](https://github.com/jctanner/ansibullbot/blob/ISSUE_TRIAGE_CLASS/ISSUE_HELP.md)

**Comment by jctanner** [comment]
Testcase ...

```
[jtanner@fedmac AMC-996]$ cat site.yml 
- hosts: f23host
  user: root
  gather_facts: False
  tasks:

    - name: cleanup
      file:
        path: "{{ item }}"
        state: absent
        force: yes
      with_items:
        - dir1
        - dir2

    - name: clone 1
      git:
        repo: https://github.com/ansible/ansibullbot
        dest: /tmp/dir1
        version: master
        depth: 1
    - name: check depth on 1
      shell: cd /tmp/dir1; git log --oneline | wc -l  
      register: depth1

    - name: clone 2
      git:
        repo: https://github.com/ansible/ansibullbot
        dest: /tmp/dir2
        version: master
    - name: check depth on 2
      shell: cd /tmp/dir2; git log --oneline | wc -l  
      register: depth2

    - assert:
        that:
            - 'depth1.stdout == "1"'
            - 'depth2.stdout != "1"'
```

Test Script ...

```
[jtanner@fedmac AMC-996]$ cat test.sh 
#!/bin/bash
VERSION=$(ansible --version | head -n1 | awk '{print $2}')
ansible-playbook -vvvv -i inventory site.yml
RC=$?
exit $RC
```

Results ...

```
v1.6.2 ; 0
v1.6.3 ; 0
v1.6.4 ; 0
v1.6.5 ; 0
v1.6.6 ; 0
v1.6.7 ; 0
v1.6.8 ; 0
v1.6.9 ; 0
v1.7.0 ; 0
v1.7.1 ; 0
v1.7.2 ; 0
v1.8.0 ; 0
v1.8.1 ; 0
v1.8.2 ; 0
v1.8.3 ; 0
v1.8.4 ; 0
v1.9.0-0.1.rc1 ; 0
v1.9.0-0.2.rc2 ; 0
v1.9.0-1 ; 0
v1.9.0-2 ; 0
v1.9.0.1-1 ; 0
v1.9.1-0.1.rc1 ; 0
v1.9.1-0.2.rc2 ; 0
v1.9.1-0.3.rc3 ; 0
v1.9.1-0.4.rc4 ; 0
v1.9.1-1 ; 0
v1.9.2-0.1.rc1 ; 0
v1.9.2-0.2.rc2 ; 0
v1.9.2-1 ; 0
v1.9.3-0.1.rc1 ; 0
v1.9.3-0.2.rc2 ; 0
v1.9.3-0.3.rc3 ; 0
v1.9.3-1 ; 0
v1.9.4-0.1.rc1 ; 0
v1.9.4-0.2.rc2 ; 0
v1.9.4-0.3.rc3 ; 0
v1.9.4-1 ; 0
v1.9.5-0.1.rc1 ; 0
v1.9.5-1 ; 0
v1.9.6-0.1.rc1 ; 0
v1.9.6-1 ; 0
v2.0.0-0.6.rc1 ; 0
v2.0.0-0.7.rc2 ; 0
v2.0.0-0.8.rc3 ; 0
v2.0.0-0.9.rc4 ; 0
v2.0.0.0-1 ; 0
v2.0.0.1-1 ; 0
v2.0.0.2-1 ; 0
v2.0.1.0-0.1.rc1 ; 0
v2.0.1.0-0.2.rc2 ; 0
v2.0.1.0-1 ; 0
v2.0.2.0-0.1.rc1 ; 0
v2.0.2.0-0.2.rc2 ; 0
v2.0.2.0-0.3.rc3 ; 0
v2.0.2.0-0.4.rc4 ; 0
v2.0.2.0-1 ; 0
v2.1.0.0-0.1.rc1 ; 0
v2.1.0.0-0.2.rc2 ; 0
v2.1.0.0-0.3.rc3 ; 0
v2.1.0.0-0.4.rc4 ; 0
v2.1.0.0-1 ; 0
v2.1.1.0-0.1.rc1 ; 0
v2.1.1.0-0.2.rc2 ; 0
v2.1.1.0-0.3.rc3 ; 0
v2.1.1.0-0.4.rc4 ; 0
v2.1.1.0-0.5.rc5 ; 0
v2.1.1.0-1 ; 0
devel-f62df4e ; 0
```
